### ISSUE TITLE
Is ImportExcel not Compatible with XLSM files (macros)

### ISSUE THREAD

**Issue by TrevorWesterdahl** [dfinke/ImportExcel#1004]
When I tried to edit an XLSM Excel workbook, the file was corrupted (all the macros were deleted). Is ImportExcel not compatible with XLSM files?

**Comment by TrevorWesterdahl** [comment]
Note: Technically, I used: Open-ExcelPackage and Close-ExcelPackage corrupted the file. My objective is to open an XLSM file, select a worksheet and loop through specific cell values to change as necessary. Then save the file.

**Comment by dfinke** [comment]
The library being used to serialize the Excel file I don't believe supports writing out the the macros.

Just curious, are the values you change saved?

When you say "corrupted" is the data in the spreadsheet, but the macros are no longer there?

**Comment by TrevorWesterdahl** [comment]
Yes, the values are saved. I didn’t get a screenshot. Essentially, when you open the file you get an error that the file was corrupted and it offers an auto-fix. The fix makes it so you can open the file and the data is there, but the file was half the size and all macros gone. Admittedly this file has a lot of macros.

 

Trevor

**Comment by dfinke** [comment]
Thanks for the info. Unfortunately the serialization library does not support saving to xlsm files.
