### ISSUE TITLE
Question: PivotData % of Grand Total? Not sure if this is the place to ask

### ISSUE THREAD

**Issue by jacobt5603** [dfinke/ImportExcel#1005]
How do you show the pivot data column as % of grand total?
-PivotData @{"filedname"="Count"} 

![grandtotal](https://user-images.githubusercontent.com/18044690/110035381-360a0e00-7d01-11eb-885b-00cf00385f9d.png)

**Comment by dfinke** [comment]
Sorry, that feature is not available and won't be implmented.
