### ISSUE TITLE
Export-Excel - Not exporting hashtables

### ISSUE THREAD

**Issue by TrevorWesterdahl** [dfinke/ImportExcel#1006]
I am testing the Export-Excel functionality with data from Microsoft's API for its Security Guide. The download has properties (I.e. KBArticle) which might have a hashtable value like this: 

@{ID=4577015; URL=https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4577015; SubType=Security Update}

When I export the object to OGV (grid view in PowerShell), the data is displayed properly. When I use Export-Excel, every property with a Hashtable for a value is blank.

In PowerShell, if I convert a a single property value where the property value is a hashtable, this is what I get:
>[string]$propVal = $result[1].KBArticle
>$propVal
@{ID=4577015; URL=https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4577015; SubType=Security Update}
>

If I try ToString(), I get a similar result to Export-Excel:
>$result[1].KBArticle.ToString()

>
NOTE: Output is blank like what I am seeing in the Export-Excel xlsx file.

Is there a way to force Export-Excel to convert property values to a string, rather than what I suspect its doing... using ToString()?

**Comment by dfinke** [comment]
`Export-Excel` doesn't inspect the data to see if it is hashtable like OGV does.

You need to do something like this:

```powershell
[pscustomobject]@{ID=4577015; URL='https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4577015'; SubType='Security Update'}|Export-Excel
```

**Comment by TrevorWesterdahl** [comment]
FYI: I worked around this by modifying the data to something other than arrays or hash tables (a string representation). Continuing the example:

function Get-KBarticleInfo { 
    param(
        [parameter(Position = 0)]
        [System.Array]$KBArticles
    )
    if ($KBArticles -eq $null) {
        return "None Provided"
    }
    $kbText = ""
    foreach ($article in $KBArticles) {
        [string] $text = "ID=$($article.ID); URL=$($article.URL); SubType=$($article.SubType)"
        $kbText += "@{$($text)}"
    }
    return $kbText
}

This function loops through the array of KBArticles and builds a single text value representing the result which does display properly. Would be nice if Export-Excel, recognized a hash table or array property, would get the properties (I.e. ID, URL, and SubType in this example), and output something similar rather than a blank entry or System.Object[].
