### ISSUE TITLE
Equals Sign + Noob Question

### ISSUE THREAD

**Issue by eriksonssilva** [dfinke/ImportExcel#1007]
Hello Doug! Thanks for the amazing module! It's been super helpful!
However I have an issue and a question that I couldn't find answers anywhere...

First the "issue".
I want to export an array that contains an "x" number of equal signs.
But I can't do that, no matter what.
Here's a sample:

```
$a = [System.Collections.ArrayList]@()

for ($i = 0; $i -lt 45; $i++) {

    [void]$a.Add("=")

}

$a | Export-Excel test.xlsx -StartRow 2
```

However, the output is blank!

If I try the same thing with whatever inside the quotes, it works:

```
$a = [System.Collections.ArrayList]@()

for ($i = 0; $i -lt 45; $i++) {

    [void]$a.Add("Something")

}

$a | Export-Excel test.xlsx -StartRow 2
```

I have tried simple quotes, no avail.
Also tried """=""", but then the output is "=", and I need it to be = only...
What am I doing wrong?

The second question I'm sure is simple, but I cannot find a way and reading the samples didn't help.

Let's say I have the same scenery as above, but I want more than one array to be exported, but each to a different column:

```
$a = [System.Collections.ArrayList]@()
$b = [System.Collections.ArrayList]@()
$c = [System.Collections.ArrayList]@()

for ($i = 0; $i -lt 45; $i++) {

    [void]$a.Add("Something")
    [void]$b.Add("Another Something")
    [void]$c.Add("Yet Something")

}

```

How would I export that? I have tried

$a, $b, $c | Export-Excel test.xlsx -StartRow 2
But it exports in the same column.

Thanks in advance!

**Comment by dfinke** [comment]
Try this video.

[![IMAGE ALT TEXT](http://img.youtube.com/vi/fvKKdIzJCws/0.jpg)](http://www.youtube.com/watch?v=fvKKdIzJCws "PowerShell+Excel Hello World")

**Comment by eriksonssilva** [comment]
Thanks, Doug! I have watched this and all the other videos.
I have read the Help and also tried all the examples, but somehow, I cannot figure how to put one array per column.
The only way I have found was to export each separately:

$array1 | Export-Excel test.xlsx Start-Column 1
$array2 | Export-Excel test.xlsx Start-Column 2
$array3 | Export-Excel test.xlsx Start-Column 3

This way works but I don't know if that's the correct approach.

And regarding the "=" string, I have searched a lot and couldn't find an answer. Sorry!

**Comment by dfinke** [comment]
## For Arrays

`Export-Excel` works with data shaped like this. Your approach is the way to go.

```powershell
$(
    [PSCustomObject]@{Array1 = 1; Array2 = 4; Array3 = 7 }
    [PSCustomObject]@{Array1 = 2; Array2 = 5; Array3 = 8 }
    [PSCustomObject]@{Array1 = 3; Array2 = 6; Array3 = 9 }
) | Export-Excel
```

## Equal signs

Excel interprets the `=` at the start as an Excel formula.
You would need to add a `'` at the start of that, or pick another character other than `=`.

```powershell
[PSCustomObject]@{Field1 = "'" + ("=" * 10) } | Export-Excel
```

**Comment by eriksonssilva** [comment]
Thanks, Doug! That takes care of the arrays.
But still no lucky with the equals sign...
The way you told, will be shown like this:

```
'=
'=
'=
'=
'=
```

I am seeking for a way of having only the = output...

The "workaround" I have been using is adding the = array to a csv, and using Csv import.
But them I think this is an ugly approach...
Any ideas?

**Comment by dfinke** [comment]
Yup, cannot be done - Excel interprets the = at the start as an Excel formula.

**Comment by eriksonssilva** [comment]
Ok, that's fine then!
Just one question. 
Does the module have some way of selecting the index of a combobox?
That would suffice my needing without having to use this workaround.
Thanks again!

**Comment by dfinke** [comment]
No, there is nothing for that

**Comment by eriksonssilva** [comment]
Ok then! 
If I come up with a cleaner workaround I'll let you know.
Thanks again!
