### ISSUE TITLE
Refresh Pivot Table in a sheet with data coming from a table in another Excel sheet

### ISSUE THREAD

**Issue by UnDon3** [dfinke/ImportExcel#1010]
Hi,

i just developed a script that fill an Excel file using this module **(thanks to DarkLite1 in Stackoverflow)**:

```
# *** Variables Declaration ***
    [String]$Report = "Tariffe Aeree"
    [String]$Detail = "0"
    [String]$QueryFullPath = ($QueryPath + "ControlloTariffeAeree.sql")
    [String]$QueryReplacedFullPath = ($QueryReplacedPath + "ControlloTariffeAeree_" + $Detail + "_$dtStr.sql")
    [String]$SheetName = "1"
    $dt1 = New-Object System.Data.Dataset

    # *** Replace Query with scope ***
    if (Test-Path -Path $QueryReplacedFullPath)
    {
	    Remove-Item -Path $QueryReplacedFullPath
    }

    (Get-Content $QueryFullPath) | Foreach-Object {
        $_  -replace '@GRSTA@', $GRSTA `
            -replace '@Report@', $Report `
            -replace '@Detail@', $Detail `
            -replace '@Mese@', $Mese `
            -replace '@Anno@', $Anno `
            -replace '@Day@', $Day
    } | Set-Content $QueryReplacedFullPath

    # *** Data Retrieve ***
    $dt1 = SQLCommand -File_Path $QueryReplacedFullPath -Server "ServerTest" -Name "DBTest" -Out
    $dt_table1 = $dt1.Tables[0]

    # *** Excel Preparation ***
    

    if ($dt_table1.Rows.Count -eq 0)
    {
        $WorkSheet.Visible = $false
    }
    else
    {
        $exportToExcel = ForEach ($Row in $dt1.Tables[0].Rows) {
            $properties = @{}
            ForEach ($Col in $dt1.Tables[0].Columns.ColumnName) {
                $properties[$Col] = $Row.$Col 
            }
            [PSCustomObject]$properties
        }
    }

    $params = @{
    Path          = $DestinationExcelFilePath 
    WorksheetName = $SheetName
    #ClearSheet = $true
    TableName     = 'Tabella1'
    FreezeTopRow  = $true
    HideSheet     = $SheetName
    Calculate = $true
    }
    $exportToExcel | Export-Excel @params
```

So, the scope is to fill several sheets in this Excel file in tables.

I have several pivot tables in another sheets that are linked to those Excel tables filled before in order to show the information correctly, they are custom and they have graphics as well.

However, after filling all the sheet i open my final Excel file generated but it ask me if i want to update the information in the sheet where my graphics and pivot tables are, if i click yes it refresh but the scope is to refresh the workbook in order to avoid refreshing manually each time i open it.

There is a way to refresh all pivot tables in the Excel file?

Thanks in advance!

**Comment by dfinke** [comment]
See if the `-Calculate` switch works on `Export-Excel`

**Comment by UnDon3** [comment]
> See if the `-Calculate` switch works on `Export-Excel`

Hi! Thanks for the answer, as you can see in my code I used that switch already, or maybe I'm using it wrong...

**Comment by dfinke** [comment]
Missed that. Yeah, don't know of another way.

**Comment by UnDon3** [comment]
> Missed that. Yeah, don't know of another way.

If you don't know I think there is not for sure :D. I will try to open Excel with COM object at the end of the elaboration in order to refresh the entire workbook and then save it. I was trying to avoid using COM object but at this point I don't have alternative.

**Comment by dfinke** [comment]
Let me know how it goes
