### ISSUE TITLE
Apply same formatting to saved spreadsheets as with -show parameter

### ISSUE THREAD

**Issue by jmcarthurcorr** [dfinke/ImportExcel#1015]
I've searched through the code to see what formatting is applied when using the -show parameter so I can apply it when using the -path parameter, but cannot find it anywhere. Is Excel doing this on its own, as it does when importing csv data? I would like my users to have nicely styled sheets when opening saved files.

**Comment by dfinke** [comment]
Here is where the defaults start getting set if you plain `Export-Excel`.

https://github.com/dfinke/ImportExcel/blob/master/Public/Export-Excel.ps1#L108

**Comment by jmcarthurcorr** [comment]
Thanks for pointing out that section. I sorted out that by specifying the -TableName and -Autosize parameters, I achieve the same results. Cheers.
