### ISSUE TITLE
Performance of export-excel

### ISSUE THREAD

**Issue by Schwanowski** [dfinke/ImportExcel#1018]
Hi there,

I when I export a simple xlsx file:

```
$tmp = get-service  
    $excelFile = ("$workfolderCurTime\Übersicht.xlsx")  
    Remove-Item $excelFile -Force  
    Measure-Command {  
    Export-Excel $excelFile -WorksheetName 'Übersicht' -AutoSize -AutoFilter -InputObject $tmp  
}
```

or 

```
$tmp = get-service  
    $excelFile = ("$workfolderCurTime\Übersicht.xlsx")
    Remove-Item $excelFile -Force
    Measure-Command {
    $tmp | Export-Excel $excelFile -WorksheetName 'Übersicht' -AutoSize -AutoFilter
}
```

It takes up to 4 seconds to write the file.

Is this normal?

As I am writing serveral files (like 50) with several worksheets, it needs overall up to 30 minutes which is really annoying.

Thanks

Alex

**Comment by dfinke** [comment]
The first way is the fastest, it is quicker to use `-InputObject` over the pipeline.

On my machine, it is only a year old, my `get-service` generates 312 rows and 21 columns in 548 milliseconds. I'm running Win10, PS 7.1.3, and ImportExcel 7.1.2.

**Comment by Schwanowski** [comment]
Thanks, I have tested it on another machine and it takes also just also about 0.5 Seconds... Will have to investigate what's going
