### ISSUE TITLE
Refresh command Missing - Cannot Refresh Workbooks

### ISSUE THREAD

**Issue by UnDon3** [dfinke/ImportExcel#1019]
Hi,

after I filled my Workbook with all the information I would like to refresh all the workbook in order to update the different pivot tables and charts across the worksheets. I'm doing now using COM Object with the RefreshAll() command but the scope is to avoid the COM Object to Refresh the entire workbook. It's possible?

Thanks!

**Comment by dfinke** [comment]
You can try the `-Calculate` switch on `Export-Excel`. Doing it on the static file is a no go, unfortunately COM is the way.

**Comment by UnDon3** [comment]
Is not working, the same for the Pivots? there is no way to refresh pivots?

Thanks!

Il giorno sab 10 apr 2021 alle ore 01:01 Doug Finke <
***@***.***> ha scritto:

**Comment by dfinke** [comment]
No, they need to be read by Excel to make that happen, that's why COM works, although not optimal.
