### ISSUE TITLE
Compatibility Issues with PS V 3 

### ISSUE THREAD

**Issue by davidearnest** [dfinke/ImportExcel#102]
Good evening,

Thank you for creating this module. I have been trying to use it with powershell version 3, but there are a lot of compatibility issues. The main function that I am trying to use is converting an excel sheet from .xlsx to .csv. The server instance that I am running it on does not have excel or access installed, which is the reason for me attempting to use the module. What steps could I take in terms of modifying certain ps1 files to have backwards compatibility with powershell version 3? 

I was able to run the ConvertFrom-ExcelSheet on my laptop, which worked fine, as I have the newest version of powershell on it. That is the main function that I need, along with Import-Excel, which is called by ConvertFrom-ExcelSheet, to have backwards compatibility with powershell version 3. If such compatibility is not possible, please let me know. Thanks in advance for your help.

Thanks,
David Earnest

**Comment by dfinke** [comment]
Please post the errors you are getting. From there I can see the level of difficulty of making this work with version 3

**Comment by davidearnest** [comment]
The main error that I am running into is with this line at the end of the function ConvertFrom-ExcelSheet: Import-Excel $Path -Sheet $($sheet.Name) | Export-Csv @params

The error message is as follows: Export-Csv : Cannot bind argument to parameter 'InputObject' because it is null.
+         Import-Excel $Path -Sheet $($sheet.Name) | Export-Csv <<<<  $params
    + CategoryInfo          : InvalidData: (:) [Export-Csv], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ExportCsvCommand

Thanks in advance for your help.

**Comment by dfinke** [comment]
Can you try two things:

### First

Does this throw an error?

```powershell
function test {
    param($a,$b)

    "`$a: $a"
    "`$b: $b"
}

$params = @{a=1;b=2}
test @params
```

### Second

Can you try to do an Import-Excel on the xlsx and worksheet directly and see if that has a problem.

Thanks
Doug

**Comment by davidearnest** [comment]
The function test does not throw an error.

I tried Import-Excel .\temp.xlsx but I do not see anything.
From the example, I should be able to see the data right? I can open the same xlsx from powershell by calling .\temp.xlsx, but if I try to call Import-Excel on it I do not see anything. Perhaps this is an error in compatibility with powershell version 3? 

Thanks in advance for your help.

**Comment by dfinke** [comment]
Good, so that rules out splatting as being a problem.

I'm guessing the temp.xlsx has only 1 worksheet and has the name sheet1?

Did you get the module from the PowerShell Gallery or here on GitHub?

**Comment by davidearnest** [comment]
Yes that is correct. I got the module from here on GitHub. I used the statement iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfinke/ImportExcel/master/Install.ps1') to download the module.

**Comment by dfinke** [comment]
Hmm. I'm out of ideas.

The answer I have, which won't work, is to upgrade to PowerShell.

If I or someone come up with something. We'll be sure to post it.
