### ISSUE TITLE
Question concerning export of multiple Spreadsheets

### ISSUE THREAD

**Issue by Schwanowski** [dfinke/ImportExcel#1020]
Hi Dough,

I have resolved the performance issue of https://github.com/dfinke/ImportExcel/issues/1018

But now I have another question. I need to create an excel worksheet with several e.g. 50 spreadsheets. 

When i do it via:
```
$tmp = get-service  
$excelFile = ("$workfolderCurTime\Übersicht.xlsx") 
for($i=0;$i-lt 50; $i++){
    Export-Excel $excelFile -WorksheetName $i -AutoSize -AutoFilter -InputObject $tmp  
}
```
individually, (e.g. over a for loop) it seems that it reads the worksheet in the backgroud, modifies the data and than saves it again, which is pretty slow. I have also check the ExportMultipleExcelSheets but it seems to do the very same. I have done a tiny example in python where you have the possibility to open one excel writer and then write several spreadsheets and its way faster but I am addicted to powershell and your module and want to stick with it.

Do you have any suggestions?

Thanks,

Alex

**Comment by dfinke** [comment]
`Export-Excel` mimics the built-in idea of `Excport-Csv`. It takes the data passed to it and and outputs it to the xlsx/worksheet and saves it.

**Comment by Schwanowski** [comment]
Ok thx. I dont think there will be any improvment there soon? If no we can leave this topic for now.

If its on your top list for 7.2 I could also take  a look if I can give a helping hand

**Comment by dfinke** [comment]
Not looking to do any changes there, it's been working fine for users for a few years.
