### ISSUE TITLE
Export function corrupting data model. Cannot refresh data model

### ISSUE THREAD

**Issue by jorgechoypernia** [dfinke/ImportExcel#1021]
Hi,

I am facing an issue with the export function. I already have an excel file with several tables. When I create the tables, I always specify that it contains headers.

When checking the "Name Manager" I can see the range of the tables. The range includes the header row.

When I export data from PowerShell, it work nicely and data is updated correctly on the tables. However the range of the tables change. It no longer include the header row as a part of the range.

A consequence of this issue is that when I open the "Manage Data Model" in excel and I click refresh, all the relationships among tables are mess up and not recognizable.

After I execute the export function I end up fixing the range of all the tables within excel.

An example I used: 

$dataPrj | ConvertFrom-Csv | Export-Excel -Path 'C:\TEMP\VDI_USERS.xlsx' -AutoSize -TableName PROJECT -WorksheetName S_PROJECT

Thanks

**Comment by dfinke** [comment]
I suspect there may be an issue in here https://github.com/dfinke/ImportExcel/blob/master/Public/Add-ExcelTable.ps1#L37

Not sure when it can be checked, and fixed if there is a problem.

**Comment by jorgechoypernia** [comment]
Sorry, forget about the range and row 1. I was wrong with the range defined for the tables. The range of tables are fine. I was not saving the correct Column name from the powerShell... My Bad.

However, after correcting my business logic, I still have issues with the excel file. The main problem is that it is messing up the "Data Model". If you clcik refresh, then none of the table are refreshed. Error for all tables appears.
![AddingTableRefreshWork](https://user-images.githubusercontent.com/8151529/114912332-c74bc480-9e17-11eb-8d7d-aa051f28c4e7.PNG)
![ErrorRefresh](https://user-images.githubusercontent.com/8151529/114912336-c87cf180-9e17-11eb-994c-295fb8248485.PNG)

If I re-add an existing table from the excel spreadsheet into the excel Data Model, then it get duplicated in the model, but it is able to refresh it.

For example, a table called "Office" does not refresh, but the duplicated table "Office1" that I add afterward successfully refresh.

Please refer to the attached pictures for a better understanding... That only happen after I update the excel file from the powershell using the export functionality.

![AddingTableRefreshWork](https://user-images.githubusercontent.com/8151529/114912601-1a257c00-9e18-11eb-9528-584b0a634f70.PNG)
![ErrorRefresh](https://user-images.githubusercontent.com/8151529/114912607-1abe1280-9e18-11eb-95db-36f5c22380c7.PNG)

**Comment by dfinke** [comment]
Please can you rename the issue. Would need the smallest possible repro for this. I have not worked with models in Excel. It is possible this doesn't work.
