### ISSUE TITLE
Label Position - Best Fit

### ISSUE THREAD

**Issue by 777black777** [dfinke/ImportExcel#1022]
Trying to build out an Excel report which will ultimately have 4 or 5 charts, showing various top 10 user pie charts. Hitting a roadblock on making the pie chart exactly perfect. I cannot seem to find a way to duplicate one of the PivotChart Quick Layout settings. Specifically, the Add Chart Element -> More Data Label Options... -> Format Data Labels -> Label Position - Best Fit.

Code so far:
```
$ChatData | Export-Excel -Path $OutFile -Title "Top Teams Chatters" -WorksheetName "ChatData" -TitleFillPattern DarkGray -AutoSize -AutoFilter

$Excel = Open-ExcelPackage -Path $OutFile -KillExcel

$PTParams = @{
    PivotTableName = "ChatData_Pivot"
    Address = $Excel.Workbook.Worksheets["ChatData"].Cells["D2"]
    SourceWorkSheet = $Excel.Workbook.Worksheets["ChatData"]
    SourceRange = "A2:B12"
    PivotRows = @("Teams User")
    PivotData = @{'ChatMessages' = 'Sum'}
    ChartTitle = "Top 10 Chatters"
    PivotTableStyle = 'Medium6'
    #StyleName = 'PivotStyleMedium9'
    IncludePivotChart = $True
    ChartType = 'PieExploded3D'
    Activate = $True
    ShowCategory = $Treu
    ShowPercent = $True
    NoLegend = $True
}
Write-Host "Hmm"

$PT = Add-PivotTable @PTParams -PassThru
#$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Style = "Style4"
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].RoundedCorners = $True
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series.DataLabel.ShowPercent = $True
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series.DataLabel.ShowCategory = $True
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series.DataLabel.ShowLeaderLines = $True
```
This code gives me this result (hoping to hide columns A-D later on, so just the pie charts):
![CodedVersion](https://user-images.githubusercontent.com/19959615/115052919-222afd80-9ea4-11eb-9439-138d00fa6cfc.png)

Via Excel -> Quick Layout --> Layout 1, I get this result, which is perfect.
![ExcelVersionv1](https://user-images.githubusercontent.com/19959615/115053264-91a0ed00-9ea4-11eb-8e37-b83e8d20b08b.png)

I narrowed it down to needing to change the Label Position to best fit, but cannot seem to figure out where to accomplish that within ImportExcel.

Add Chart Element -> More Data Label Options... -> Format Data Labels -> Label Position - Best Fit.
![Label Position](https://user-images.githubusercontent.com/19959615/115053365-abdacb00-9ea4-11eb-94b7-ffaf3c46566c.png)

Any help in pointing out where I screwed up is greatly appreciated or if it can't be done, that would save me a ton of more "down the rabbit hole" effort. :)

**Comment by dfinke** [comment]
Hmm, don't know if it can be done. I suspect no, but maybe it can. 

doing 

```powershell
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series.DataLabel | Get-Member
# And/Or
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series | Get-Member
# And/Or
$Excel.Workbook.Worksheets["ChatData"].Drawings[0] | Get-Member
```
There may be a property|method on there that can be set to `Best Fit`

**Comment by 777black777** [comment]
### **SOLVED!**

Hours of work and you nail it in seconds. :) DataLabel.Position, I had noticed that property, but assumed it had to do with text alignment (center, left, right) but when I attempted to set it to "Best Fit", I received an error with informative information.

```
[DBG]: PS C:\TeamsUsageReport>> $Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series[0].DataLabel.Position = "Best Fit"
Exception setting "Position": "Cannot convert value "Best Fit" to type "OfficeOpenXml.Drawing.Chart.eLabelPosition". Error: "Unable to match the identifier name Best Fit to a valid enumerator name. Specify one of the following enumerator names and try 
again:
BestFit, Left, Right, Center, Top, Bottom, InBase, InEnd, OutEnd""
At line:1 char:1
+ $Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series[0].DataLabe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

I just attempted to set the Position value to "BestFit" and now everything is perfect!

```
$Excel.Workbook.Worksheets["ChatData"].Drawings[0].Series[0].DataLabel.Position = "BestFit"

Position        : BestFit
Fill            : OfficeOpenXml.Drawing.ExcelDrawingFill
Border          : OfficeOpenXml.Drawing.ExcelDrawingBorder
Font            : OfficeOpenXml.Style.ExcelTextFont
ShowValue       : False
ShowCategory    : True
ShowSeriesName  : False
ShowPercent     : True
ShowLeaderLines : False
ShowBubbleSize  : False
ShowLegendKey   : False
Separator       : 
```
![image](https://user-images.githubusercontent.com/19959615/115075013-10575380-9ec0-11eb-8f5b-c6db2da07d76.png)



Now it looks great, other than hiding the A-D columns. Now onto adding the other 5 pie charts. Thank you so much for this Module and all the work you do!

**Comment by dfinke** [comment]
@777black777 glad it worked! Could I ask you a favor. Could you either, do a pull request of a simple example of this working. If you're not comfortable with doing a pull request, could you post a small example so I can add to the Examples directory.

Thank you!
