### ISSUE TITLE
Error when using TableName and IncludePivotChart on same file for multiple Sheets.

### ISSUE THREAD

**Issue by midiman369** [dfinke/ImportExcel#1024]
Hi.

When trying to Export-Excel more than once to the same output file, if the TableName, or TableStyle parameters are used along with IncludePivotChart, one (or more?) of the PivotTables do not work and the spreadsheet opens asking to be repaired.

This may be the same issue as https://github.com/dfinke/ImportExcel/issues/768

![image](https://user-images.githubusercontent.com/12787525/116148762-52964700-a6af-11eb-98e8-8430b89ad3a1.png)
![image](https://user-images.githubusercontent.com/12787525/116148924-883b3000-a6af-11eb-8810-9b418a4d14bf.png)

Repair log:  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error215760_01.xml</logFileName><summary>Errors were detected in file 'C:\temp\UsageReport.xlsx'</summary><removedFeatures><removedFeature>Removed Feature: PivotTable report from /xl/pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)</removedFeature><removedFeature>Removed Feature: PivotTable report from /xl/pivotTables/pivotTable1.xml part (PivotTable view)</removedFeature></removedFeatures><removedRecords><removedRecord>Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)</removedRecord></removedRecords></recoveryLog>`

```PowerShell
$EmailReport | Export-Excel `
	-Path 'C:\temp\UsageReport.xlsx' `
	-WorksheetName 'Email Report' `
	-Title 'Email Usage Report - Last 7 days' `
	-TitleFillPattern MediumGray `
	-TitleBackgroundColor 'green' `
	-TitleBold `
	-AutoSize `
	-FreezeTopRowFirstColumn `
	-TableStyle Medium7 `
	-IncludePivotChart `
	-ChartType LineStacked `
	-PivotRows "Display Name" `
	-PivotDataToColumn `
	-PivotFilter "Department", "Title" `
	-PivotData @{"Send Count" = "Sum"; "Receive Count" = "Sum"}

$TeamsReport | Export-Excel `
	-Path 'C:\temp\UsageReport.xlsx' `
	-WorksheetName 'Teams Report' `
	-Title 'Teams Usage Report - Last 7 days' `
	-TitleFillPattern MediumGray `
	-TitleBackgroundColor 'green' `
	-TitleBold `
	-AutoSize `
	-FreezeTopRowFirstColumn `
	-TableStyle Medium7 `
	-IncludePivotChart `
	-ChartType LineStacked `
	-PivotRows "Display Name" `
	-PivotDataToColumn `
	-PivotFilter "Department", "Title" `
	-PivotData @{"Private Chat Message Count" = "Sum"; "Call Count" = "Sum"}
```

I'd love to be able to use both options, any workaround would be appreciated!

**Comment by dfinke** [comment]
So if you remove `-TableStyle` this works? Add it back or add `-TableName` and Excel has a problem opening it?

**Comment by midiman369** [comment]
Correct, but you lose the nice formatted table obviously.  Seems you can have a pivottable/chart or a "table table", but not both in this scenario.

As a workaround I've been attempting to learn to use Open-ExcelPackage and/or other functions to modify the saved file afterword.  That is:  do the initial export with either the tablestyle or the pivotchart but not both first, then add the table/formatting in a separate operation after, but admittedly am still learning to use that function.  (though I'd not consider that an issue in the context here)

**Comment by midiman369** [comment]
Not sure if this is of any further insight, but when I run the following, it creates a workbook with no errors. 

Using `-TableStyle` in the second operation produces no errors, but using it in the first operation causes the error after running the second operation:

``` PowerShell
$emailReportArgs = @{
	Path = 'C:\temp\UsageReport.xlsx'
	WorksheetName = 'Email Report'
	Title = 'Email Usage Report - Last 7 days'
	TitleFillPattern = 'MediumGray '
	TitleBackgroundColor = 'green'
	TitleBold = $true
	AutoSize = $true
	FreezeTopRowFirstColumn = $true
#	TableStyle = 'Medium7'
	IncludePivotChart = $true
	ChartType = 'LineStacked'
	PivotRows = "Display Name"
	PivotDataToColumn = $true
	PivotFilter = "Department", "Title"
	PivotData = @{"Send Count" = "Sum"; "Receive Count" = "Sum"}
}
$EmailReport | Export-Excel @emailReportArgs

$teamsReportArgs = @{
	Path = 'C:\temp\UsageReport.xlsx'
	WorksheetName = 'Teams Report'
	Title = 'Teams Usage Report - Last 7 days'
	TitleFillPattern = 'MediumGray '
	TitleBackgroundColor = 'green'
	TitleBold = $true
	AutoSize = $true
	FreezeTopRowFirstColumn = $true
	TableStyle = 'Medium7'
	IncludePivotChart = $true
	ChartType = 'LineStacked'
	PivotRows = "Display Name"
	PivotDataToColumn = $true
	PivotFilter = "Department", "Title"
	PivotData = @{"Private Chat Message Count" = "Sum"; "Call Count" = "Sum"}
}
$TeamsReport | Export-Excel @teamsReportArgs
```

**Comment by midiman369** [comment]
I've found a workaround.  So far, my attempts to put the formatted tables in after the pivottables instead of before seems to meet with issues.  The below works! :)

``` PowerShell
Remove-Item C:\temp\UsageReport.xlsx

$emailReportArgs = @{
	Path = 'C:\temp\UsageReport.xlsx'
	WorksheetName = 'Email Report'
	Title = 'Email Usage Report - Last 7 days'
	TitleFillPattern = 'MediumGray '
	TitleBackgroundColor = 'green'
	TitleBold = $true
	AutoSize = $true
	FreezeTopRowFirstColumn = $true
	TableName = 'EmailTable'
	TableStyle = 'Medium7'
#	IncludePivotChart = $true
#	ChartType = 'BarClustered'
#	PivotRows = "Department"
#	PivotDataToColumn = $true
#	PivotFilter = "Display Name", "Title"
#	PivotData = @{"Send Count" = "Sum"; "Receive Count" = "Sum"}
}
$EmailReport | Export-Excel @emailReportArgs

$teamsReportArgs = @{
	Path = 'C:\temp\UsageReport.xlsx'
	WorksheetName = 'Teams Report'
	Title = 'Teams Usage Report - Last 7 days'
	TitleFillPattern = 'MediumGray '
	TitleBackgroundColor = 'green'
	TitleBold = $true
	AutoSize = $true
	FreezeTopRowFirstColumn = $true
	TableName = "TeamsTable"
	TableStyle = 'Medium7'
#	IncludePivotChart = $true
#	ChartType = 'BarClustered'
#	PivotRows = "Department"
#	PivotDataToColumn = $true
#	PivotFilter = "Display Name", "Title"
#	PivotData = @{"Private Chat Message Count" = "Sum"; "Call Count" = "Sum"}
}
$TeamsReport | Export-Excel @teamsReportArgs

#Start C:\temp\UsageReport.xlsx

$wb = Open-ExcelPackage -Path C:\temp\UsageReport.xlsx
$emailTableRange = $wb.'Email Report'.Cells[$wb.'Email Report'.Tables.Address]
$teamsTableRange = $wb.'Teams Report'.Cells[$wb.'Teams Report'.Tables.Address]

$emailPivotArgs = @{
	ExcelPackage = $wb
	SourceWorkSheet = $wb.'Email Report'
	SourceRange = $emailTableRange
	IncludePivotChart = $true
	PivotTableName = 'EmailPivotTable'
	ChartType = 'BarClustered'
	PivotRows = "Department"
	PivotDataToColumn = $true
	PivotFilter = "Display Name", "Title"
	PivotData = @{"Send Count" = "Sum"; "Receive Count" = "Sum"}
}

$teamsPivotArgs = @{
	ExcelPackage = $wb
	SourceWorkSheet = $wb.'Teams Report'
	SourceRange = $teamsTableRange
	IncludePivotChart = $true
	PivotTableName = 'TeamsPivotTable'
	ChartType = 'BarClustered'
	PivotRows = "Department"
	PivotDataToColumn = $true
	PivotFilter = "Display Name", "Title"
	PivotData = @{"Private Chat Message Count" = "Sum"; "Call Count" = "Sum"}
}

Add-PivotTable @emailPivotArgs
Add-PivotTable @teamsPivotArgs

#NO WORKY   -  replaced this with the reverse attempt above to put formated tables in via initial export-excel commands and add the pivottables seperately
#Add-ExcelTable -Range ($wb.'Email Report'.Cells[$wb.'Email Report'.Dimension.Address -replace "A1","A2"]) -TableStyle Medium7
#Add-ExcelTable -Range ($wb.'Teams Report'.Cells[$wb.'Teams Report'.Dimension.Address -replace "A1","A2"]) -TableStyle Medium7
#NO WORKY

Close-ExcelPackage -ExcelPackage $wb
```

**Comment by dfinke** [comment]
What if you go back to the original setup you had and on each `Export-Excel` you add `-PivotTableName` with the names you provided in the last attempt?

**Comment by midiman369** [comment]
gives the same errors with the first PivotTable and chart not working:

**Comment by midiman369** [comment]
Gives the same errors with the first PivotTable and Chart not working.  :(

![image](https://user-images.githubusercontent.com/12787525/116302070-c0557800-a76e-11eb-8c87-e54c5ed2789b.png)

![image](https://user-images.githubusercontent.com/12787525/116302095-c77c8600-a76e-11eb-90ac-14bf182af102.png)

![image](https://user-images.githubusercontent.com/12787525/116302161-db27ec80-a76e-11eb-819c-010891e45641.png)

**Comment by dfinke** [comment]
Thanks for trying

**Comment by dfinke** [comment]
@midiman369 would you be up for posting the sanitized `teams` and `emails` approach you used? This would be a great example to showcase. If so, and you're up for it, be great for you to do a `pull request` and add that the `Examples` directory.

**Comment by midiman369** [comment]
Sure, I'd be happy to!  I'm still working on the rest of it.  It's working now but messy.  I have a "local" version and an Azure Runbook version as well.  The Runbook version Authenticates with the AzureRunAsConnection, gets the Secret from a Vault, Retrieves the usage data from M365 via the Graph, curates it, and generates the report, and uploads it to OneDrive via Graph.  Unless you only are looking for the parts relevant to the Excel module?

**Comment by dfinke** [comment]
All of that is great. Sounds like a great blog post :smirk:

Curious, do you have a similar workflow all from a PowerShell Azure Function?

For the example, I was thinking just the part that queries the sources, exports to Excel, and then the customization of sheets. 

That would be great.
