### ISSUE TITLE
Feature Request: add support for worksheet property "ZeroHeight"

### ISSUE THREAD

**Issue by mikerosile** [dfinke/ImportExcel#1025]
While I was trying to find a way to hide all unused rows in a worksheet using the ImportExcel PowerShell module, I came to learn about the ZeroHeight Worksheet property which causes all rows to be hidden by default, and displays only explicitly defined non-hidden rows.

From [Microsoft's documentation](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.sheetformatproperties?view=openxml-2.8.1):
"This setting is an optimization used when most rows of the sheet are hidden. In this case, instead of writing out every row and specifying hidden, it is much shorter to only write out the rows that are not hidden, and specify here that rows are hidden by default, and only not hidden if specified."

From what I can tell, ImportExcel does not currently support the ZeroHeight worksheet property, therefore I am requesting that support for the ZeroHeight worksheet property be added as a means to efficiently hide unused rows.

I'm creating this GitHub Issue to start the conversation -- assuming the author(s) is in agreement, I'm willing to contribute code to support this effort and submit a Pull Request especially if the author(s) is time constrained.

**Comment by dfinke** [comment]
Haven not heard of `ZeroHeight` and is not in the module. Please investigate if the version of the EPPlus library in use supports that, if not, that will be a show stopper.
