### ISSUE TITLE
Applying -AsText to multiple columns?

### ISSUE THREAD

**Issue by TommySharpNZ** [dfinke/ImportExcel#1026]
Could I get some guidance on how to force more than one date column to be imported as text?
This works great! But I also need to import HireDate as text...

`Import-Excel -Path C:\test.xlsx -AsText "BirthDate"`

**Comment by stahler** [comment]
This works for me:
```PowerShell
Import-Excel -path C:\temp\AsText.xlsx -AsText 'HireDate', 'BirthDate'
```
# before -AsText
![image](https://user-images.githubusercontent.com/1991193/118343451-207e4500-b4f7-11eb-8f36-dc1b7d2e02c4.png)

# after -AsText
![image](https://user-images.githubusercontent.com/1991193/118343464-3986f600-b4f7-11eb-9eb9-973db25017be.png)
