### ISSUE TITLE
SQL table support

### ISSUE THREAD

**Issue by DavidYacouel** [dfinke/ImportExcel#1027]
Hi Doug,

So I use Invoke-Sqlcmd to insert data to Azure SQL databases. 
I used a connection string like this one:
$ConnectionString = "Data Source=tcp:$($SqlServer).database.windows.net;Initial Catalog=$($SqlDatabase);Authentication=Active Directory Password;User Id='$($account)';Password='$($SqlCredsSecretValue)'"

And then I saw the ConvertFromExcelToSQLInsert ​cmdlet that helps write the INSERT commands to SQL.
Obviously the combination of the two will insert the data to the table.

Do you have anything that would CREATE the table in the database from an Excel sheet? 
Or similarly to ConvertFromExcelToSQLInsert, generate the sql commands to create the table with the right column names and types?

Thank you!

**Comment by dfinke** [comment]
No, don't have that. Interesting idea though.

**Comment by chrgraefe** [comment]
In combination with dbatools you can solve this easily

```powershell

Import-Module dbatools
Import-Module ImportExcel

$database = "MY_DB"

$importExcel = "D:\Temp\Customers.xlsx"

Import-Excel -Path $importExcel -WorksheetName "Customers" 
	| Select-Object CustomerId, CustomerName
		| ConvertTo-DbaDataTable  
			| Write-DbaDataTable -SqlInstance $sqlInstance -Database $database -Schema INPUT -Table Customers -Truncate
```

**Comment by dfinke** [comment]
Nice! Does the `ConvertTo-DbaDataTable` infer the datatypes too?

**Comment by chrgraefe** [comment]
Yes it does!
https://docs.dbatools.io/#ConvertTo-DbaDataTable
