### ISSUE TITLE
Time format (hh:mm:ss) not working

### ISSUE THREAD

**Issue by PeterGeelen** [dfinke/ImportExcel#103]
I’m using your ImportExcel Github project to create some PivotTable Excel sheet for reporting on a MS Forefront Identity Manager setup. Purpose is to export task run time statistics to Excel.

/../
    $selection |
      Export-Excel $file -WorksheetName 'Average' `
        -IncludePivotTable`
        -PivotRows MaName `
        -PivotColumns RunProfile`
        -PivotData @{RunTime='Average'} `
        -PivotDataToColumn`
        -Numberformat 'hh:mm:ss'
/../

The data export into Excel is working fine, but I’m struggling a bit with data formatting.
Data dumped into Excel is using the time format (hh:mm:ss), as the execution time for tasks that run.

I tried to use the Numberformat parameter, but that doesn’t work.
The numbers get saved in basic number format.

After manually re-formatting in Excel, it works out, but I would like to get it fixed in the PowerShell.

Do you have any suggestions? (or is it a feature request?)

**Comment by dfinke** [comment]
Any chance you could post sample data I can use as a test case?

**Comment by PeterGeelen** [comment]
Here are some samples.
- Script 
[runhistory powershell.txt](https://github.com/dfinke/ImportExcel/files/269795/runhistory.powershell.txt)
- 
[fimrunprofiles_afterexport.xlsx](https://github.com/dfinke/ImportExcel/files/269881/fimrunprofiles_afterexport.xlsx)
[fimrunprofiles_manual_updated_withcolor.xlsx](https://github.com/dfinke/ImportExcel/files/269882/fimrunprofiles_manual_updated_withcolor.xlsx)

**Comment by PeterGeelen** [comment]
Ouch, wrong button..., issue is still open... ;)

**Comment by dfinke** [comment]
OK, don't have an Export-Excel answer, I may have a PowerShell solution in your script.

`([DateTime]::Parse($e).Subtract([DateTime]$s)).ToString("g")`

**Comment by ranjeet21r** [comment]
Any Update on this. I am also facing same issue
