### ISSUE TITLE
[Question] Set Worksheet color

### ISSUE THREAD

**Issue by ben-5555** [dfinke/ImportExcel#1033]
Hello,

I find your powershell module for Excel export excellent. Many thanks for it. I use the module mainly to create automated system documentation. To better identify the individual worksheets, I would highlight them in color (as in the screenshot). Is this possible? 

![image](https://user-images.githubusercontent.com/84332967/118506286-7b00e680-b72d-11eb-92c5-1bdae7e6c2e0.png)

Thanks,
Ben

**Comment by dfinke** [comment]
```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = "./testColorization.xlsx"
Remove-Item  $xlfile -ErrorAction SilentlyContinue

$data | Export-Excel $xlfile -WorksheetName tabnumber1
$xlpkg = $data | Export-Excel $xlfile -WorksheetName tabnumber2 -PassThru

$xlpkg.tabnumber1.TabColor = "Green"
$xlpkg.tabnumber2.TabColor = "Orange"

Close-ExcelPackage $xlpkg -Show
```

**Comment by ben-5555** [comment]
Hello Doug,
Thank you for your quick reply. It works very well.
Ben
