### ISSUE TITLE
Export-Excel: Issues with date when view in the xlsx file

### ISSUE THREAD

**Issue by suhaimi-cyber4n6** [dfinke/ImportExcel#1035]
Hello and good day all.
I am having issues with Export-Excel saving the data as date in xlsx file. I have look through all the issues regarding date in this github but I still not understand what is the solution. I am not a programmer by nature. But I am willing to try and open for any suggestions. Thanks.

Sample Code:
`$xlfile = "$env:TEMP\expiration.xlsx"`
`rm $xlfile -ErrorAction SilentlyContinue`

`$excel = ConvertFrom-Csv @"`
`Expires,Month,Day,Year`
`"2020-10-26 12:58:54","=month(Expires)","=day(Expires)","=year(Expires)"`
`"2019-05-17 02:39:42","=month(Expires)","=day(Expires)","=year(Expires)"`
`"2017-06-13 17:16:38","=month(Expires)","=day(Expires)","=year(Expires)"`
`"@ | Export-Excel $xlfile -WorksheetName 'Test' -AutoNameRange -PassThru -AutoSize -TableStyle Medium2`

`Set-ExcelColumn -Worksheet $excel.Workbook.Worksheets["Test"] -Column 1 -NumberFormat "MM/dd/yyyy HH:mm:ss"`
`Close-ExcelPackage $excel -Show`

Result produce date format "yyyy-mm-dd HH:mm:ss":
![image](https://user-images.githubusercontent.com/61304851/119482662-b7b08b80-bd86-11eb-8508-a0d20294b5d7.png)

As you can see above the result does not produce the date format as "MM/dd/yyyy HH:mm:ss". However if I select the cell by pressing (F2) and press "Enter" button, it will updates the cell to the date format I want as below.

Result after select the cell by pressing (F2) and press "Enter" button:
![image](https://user-images.githubusercontent.com/61304851/119484914-1545d780-bd89-11eb-8d09-dfb4c839357e.png)

Excel version:
Microsoft 365 Apps for enterprise
Version 2008 (Build 13127.216xx Click-to-Run)
 
Question:
1. How to format the date automatically using Export-Excel and get the correct date format in the xlsx file? Please help.

Thank you very much in advance.

**Comment by stahler** [comment]
[https://github.com/dfinke/ImportExcel/issues/984](https://github.com/dfinke/ImportExcel/issues/984) offers a clue.

Try something like:
```Powershell
$xlfile = "$env:TEMP\expiration.xlsx"
Remove-Item -Path $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Expires,Month,Day,Year
"2020-10-26 12:58:54","=month(Expires)","=day(Expires)","=year(Expires)"
"2019-05-17 02:39:42","=month(Expires)","=day(Expires)","=year(Expires)"
"2017-06-13 17:16:38","=month(Expires)","=day(Expires)","=year(Expires)"
"@

foreach ($row in $data) {
    $row.Expires = Get-Date $row.Expires 
} 

$xl = $data | Export-Excel $xlfile -WorksheetName 'Test' -AutoNameRange -PassThru -AutoSize -TableStyle Medium2

Set-ExcelColumn -ExcelPackage $xl -WorksheetName Test -Column 1 -NumberFormat 'MM/dd/yyyy HH:mm:ss'
Close-ExcelPackage -ExcelPackage $xl -Show
```

**Comment by suhaimi-cyber4n6** [comment]
Hi @stahler ,

I have try your sample code and it works like charm :). Thank you very much and I really appreciate it.

`foreach ($row in $AD_Records) {`
    `$row.DateTime_UTC= Get-Date $row.DateTime_UTC`
`}`

Note: I noticed that if I try to do like below it will still not work. Looks like the `foreach ($row in $data) {$row.Expires = Get-Date $row.Expires}` need to run after below code.

`$AD_Records = Import-CSV -Path $Get_AD_Csv_File | Select-Object @{Name='DateTime_UTC'; Expression={DateTime $_.LastModified}}`
