### ISSUE TITLE
Import-Html not working 

### ISSUE THREAD

**Issue by eggcaker** [dfinke/ImportExcel#1036]
$  import-html https://www.science.co.il/elements/ 0                                          

 InvalidOperation: C:\Users\admin\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Get-HtmlTable.ps1:15
Line |
  15 |      $table = $r.ParsedHtml.getElementsByTagName("table")[$TableIndex]
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\admin\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Get-HtmlTable.ps1:21
Line |
  21 |          $row = $table.rows[$idx]
     |          ~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

**Comment by stahler** [comment]
I noticed this not working with PowerShell version 7.1.3 but works as designed with Windows PowerShell (5.1).
Will dig deeper.....

**Comment by eggcaker** [comment]
@stahler yes, I'm using pwsh 7.1.3, the current version of Invoke-WebRequest returns the Basic

**Comment by stahler** [comment]
I recall reading about some of the issues with Invoke-WebRequest on PWSH.  Here is a chain that while interesting, doesn't necessarily provide a solution: [https://github.com/PowerShell/PowerShell/issues/2867](https://github.com/PowerShell/PowerShell/issues/2867)

**Comment by dfinke** [comment]
Thanks Wes! Yeah, if failed for me on 7.1.3. Also tried just the `iwr` and getElementId, it didn't but got no data in the `ParsedHtml`. I used and tweaked Lee Holmes code from his blog to put that together. Haven't had a chance to look to see if he may have an updated version somewhere, or how 7.1.3 works.

**Comment by scriptingstudio** [comment]
https://github.com/PowerShell/PowerShell/issues/15500

**Comment by dfinke** [comment]
Thanks @scriptingstudio, I suspected, good to get confirmation.
