### ISSUE TITLE
Using Add-PivotTable and then adding more worksheets

### ISSUE THREAD

**Issue by DavidYacouel** [dfinke/ImportExcel#1037]
Hi Doug,

Is there any issue with using Add-PivotTable, closing the Excel package, and then adding more worksheets?

This is the fragment I use to create a couple of pivot tables. The issue is the same with just one pivot table. 
I only added the Add-Worksheet here in order to help position the pivot tables before the 'Statistics' tab which I want to be last (I know that Add-PivotTable uses Add-Worksheet internally).

```
# create a fourth tab - user count by Department
write-host 'Creating Excel file with tab #4 - Users by Dept'
$excel = Open-ExcelPackage -Path $filepath
Add-Worksheet -ExcelPackage $excel -WorksheetName 'Users by Dept' -MoveBefore 'Statistics'
Add-Worksheet -ExcelPackage $excel -WorksheetName 'Users by City' -MoveBefore 'Statistics'
Add-PivotTable -ExcelPackage $excel -PivotTableName 'Users by Dept' -SourceWorksheet $excel.Workbook.Worksheets[1] -PivotRows 'Department' -PivotColumns 'City' -PivotData 'UserPrincipalName' -Activate # -NoTotalsInPivot
Add-PivotTable -ExcelPackage $excel -PivotTableName 'Users by City' -SourceWorksheet $excel.Workbook.Worksheets[1] -PivotRows 'City'                            -PivotData 'UserPrincipalName' -Activate # -NoTotalsInPivot
Close-ExcelPackage -ExcelPackage $excel

```
When I use this code BEFORE creating the Statistics tab (and without using the Add-Worksheet cause I create Statistics with -MoveToEnd ), and then I create the last worksheet 'Statistics' (sample code below), then the resulting Excel file is corrupt and when I open it I receive the following message.

```
# create the last tab - Statistics
write-host 'Creating Excel file with tab #5 - Statistics'
$excel = Open-ExcelPackage -Path $filepath
Add-Worksheet -ExcelPackage $excel -WorksheetName 'Statistics' -MoveToEnd
$SummaryReport | Export-Excel -ExcelPackage $excel -WorksheetName 'Statistics' -TableStyle Medium1 -BoldTopRow -AutoSize -Numberformat '@'

```
![image](https://user-images.githubusercontent.com/83780565/120457398-685cf300-c364-11eb-8d67-bc7055f7b8a4.png)

![image](https://user-images.githubusercontent.com/83780565/120458937-b3c3d100-c365-11eb-93b0-8c1a37da4d0b.png)

I do make sure I use -Activate with Add-PivotTable and then I Close-ExcelPackage.

Also, when I debug the code when creating the pivot table before Statistics, and I stop running before creating the last tab (Statistics), then the file is healthy and readable. It's the adding of the additional tab that 'causes' the corruption. Well, I am guessing it's not the adding of the last tab, but something in Add-PivotTable leaves the workbook in a non healthy way.

OR, I am doing something wrong, in which case I'd love to find what it is. 

I reviewed the code for Add-PivotTable and I can't find a reason for this either, but maybe I am missing it. I do admit that I don't understand the need for -Activate parameter, but I didn't dig in the Add-Worksheet code for it.

I can provide a full script sample for this.

Thank you,
David Y.

**Comment by dfinke** [comment]
Thanks @DavidYacouel, any way you can make a small repro? `-Activate` makes the pivot table sheet the active sheet.

**Comment by DavidYacouel** [comment]
yes, @dfinke , I will put something simple together, thanks.
