### ISSUE TITLE
Refresh problem with conditional type "Expression" that uses a logical function

### ISSUE THREAD

**Issue by OcasoProtal** [dfinke/ImportExcel#1039]
Hi!

Whenever I use a logical function (AND/OR) in a conditional text Excel seems to not refresh the column that this conditional text is applied to:

`Get-Process|select Company, name, Handles| export-excel -Path "test.xlsx" -Now -ConditionalText $(New-ConditionalText -Range "C2:C9999" -ConditionalType Expression -ConditionValue '=AND($B2="svchost",$C2<1000)' -BackgroundColor Orange)`

This wil  fire up Excel without any errors but it seems like the conditional formatting is not applied or the condition is not fulfilled for any of the rows. But when you manage your conditional formattings in Excel and go to that condition and change the last character of the condition from `)` to `)` - meaning in fact you change nothing - the condition is working.

Is this an ImportExcel problem or a problem of Excel itself? Simpler conditions like `=$C2<1000` work flawlessly.

**Comment by stahler** [comment]
Interesting, your exact code works perfect for me.
![image](https://user-images.githubusercontent.com/1991193/121404822-55c95780-c92a-11eb-9eff-e58591b03bf5.png)

What version of Excel?
![image](https://user-images.githubusercontent.com/1991193/121405215-c7090a80-c92a-11eb-9823-1060b7c69c18.png)

**Comment by OcasoProtal** [comment]
My Excel version:

![image](https://user-images.githubusercontent.com/9254093/121485989-0a1db900-c9d1-11eb-9bd7-100673afe80f.png)

Unfortunately I cannot update or change my Excel because this is a company managed computer.
Import-Excel is version 7.1.2

**Comment by OcasoProtal** [comment]
Just tested with two other machines where this works. So it seems there is a problem with my installation but not with ImpoertExcel.
