### ISSUE TITLE
Exception calling "Save" with "1" argument(s): "Error saving file "

### ISSUE THREAD

**Issue by neildeadman** [dfinke/ImportExcel#1040]
I have a script that pulls information from another service and then writes that to a password protected Excel file. This has been working for a few months, running on the 1st of each month without any issues.

However, this month, it ran but the document failed to email out. Something to do with our SMTP server. Having sorted that I ran the script again but get a 0KB file attached.

Debugging my script I can see the data is pulled from the other service fine, but I get the above error when I try to use a password for the Excel file. Without the password, it saves correctly.

I was using v7.1.1 of the module but the same occurs with 7.1.2.

I have tried this on 2 machines and get the same. It seems only specific to my script but I don't understand what would cause this since it has been working....

**Comment by maparaschivei** [comment]
Hello @neildeadman,

I see that your script has been running successfully for some time, but has the password changed at all?

It sounds like the password may contain a character that needs to be 'escaped'.

How does your 'Close-ExcelPackage' command look like?

`Close-ExcelPackage $excel -SaveAs $pathSaveAs -Password 'my-password'`

**Comment by neildeadman** [comment]
Password has not changed, but I have tried other passwords too to no avail.

Maybe I'm doing something not correct, but I only use Export-Excel. I've not used any other function from the module yet it was working.

At this stage, it didn't get beyond the export command before script dies.

Could the data be the cause? Might try with fewer rows.

**Comment by maparaschivei** [comment]
Are you passing the password string directly to Export-Excel via the command argument?

`Export-Excel ... -Password 'mypass'`

Have you tried storing it in a variable and passing it via variable?

```
$mypass = 'super_secure_password'

Export-Excel ... -Password $mypass
```

It certainly wouldn't hurt to try your data import with fewer rows.

**Comment by neildeadman** [comment]
My script uses a variable, but I have also tried passing it directly. Same result.

I have tried in my script to pass a single row of data and it still fails with the same error. I've even passed it a simple `@("one", "two)` and I get the same.

I'll try some other things I have in mind and see what I can shed on this issue...

**Comment by artarik** [comment]
Hello. a have the same problem. But in my case, the problem occurred when I tried to create a new style.
e.g.
```
$e = Open-ExcelPackage -path C:\temp\test.xlsx
$ws = $e.Workbook.WorkSheets.Item("TDSheet)
Set-ExcelRange -Range "A1:G1" -Merge -Bold -FontName 'Arial' -Worksheet $ws -VerticalAlignment Center -HorizontalAlignment Center -Value "New Report"
$e.SaveAs("C:\temp\Openxml\newlist.xlsx")
```
**Success**
But if i try to create a new Named Style:
```
$hyperLinkStyle = $ws.Workbook.Styles.CreateNamedStyle("href")
$e.SaveAs("C:\temp\Openxml\newlist.xlsx")
Исключение при вызове "SaveAs" с "1" аргументами: "Error saving file C:\temp\Openxml\newlist.xlsx"
строка:1 знак:1
+ $e.SaveAs("C:\temp\Openxml\newlist.xlsx")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```
Can you check your code on the same problems, or save file after  each step?

**Comment by ansandfo** [comment]
I have a similar issue, error:

```
MethodInvocationException: C:\Users\user\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Export-Excel.ps1:672
Line |
 672 |              else           {   $pkg.Save() }
     |                                 ~~~~~~~~~~~
     | Exception calling "Save" with "0" argument(s): "Error saving file C:\Temp\Workbook4.xlsx"

PS C:\Users\user>
```
The code where this is failing is calling either Copy-ExcelWorkSheet or Export-Excel. This error has been happening since 7.1.2 was installed.

**Comment by dfinke** [comment]
## I cannot reproduce that error

Don't post your full script, you'll need to try and create the smallest possible script that demos that error and post it

I'm running.

![image](https://user-images.githubusercontent.com/67258/123545805-ff308b80-d727-11eb-8b46-286f2ee596b9.png)

This goes through several code paths in the module.

```powershell
Get-Service | select -First 5 Name, Status, StartType | Export-Excel
```
![image](https://user-images.githubusercontent.com/67258/123545840-238c6800-d728-11eb-8f38-09baaafff8a4.png)

**Comment by NeilBird** [comment]
I have seen the "Exception calling "Save" with "1" argument(s): "Error saving file" error on a few occasions, in my case I believe it was caused by another process having a handle or file lock on the file whilst it is being saved, such as One Drive if you are replicating or syncing the folder that you are saving the excel file to. If I pause replication or save to another location, it stopped all occurrences of error.

I thought it worth sharing this information, in case others might have another process or syncing like service trying to read the target excel file during the save operation.

**Comment by ansandfo** [comment]
> ## I cannot reproduce that error

Thanks Doug for checking this out. Here’s some more info to help troubleshoot:

```
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32> Get-Module -ListAvailable ImportExcel

    Directory: C:\Users\ansandfo\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     7.1.2                 ImportExcel                         Desk      {Add-ConditionalFormatting, Add-ExcelCh…

PS C:\Windows\System32> 
```

In VS Code I set $ErrorActionPreference to ‘break’ and stepped through my code. 

```
$ExcelFile = 'C:\Temp\Workbook5.xlsx'
foreach($blah in $multipleBlah)
{
        Copy-ExcelWorkSheet -SourceWorkbook $template -SourceWorkSheet template -DestinationWorkbook $ExcelFile -DestinationWorksheet $blah.Device
}
```
Going to where the code breaks, I tried a couple of manual steps:
`
[DBG]: PS C:\Windows\System32> $ExcelPackage

Blah1   : Blah1
Sheet1           : Sheet1
Blah2   : Blah2
Package          : OfficeOpenXml.Packaging.ZipPackage
Encryption       : OfficeOpenXml.ExcelEncryption
Workbook         : OfficeOpenXml.ExcelWorkbook
DoAdjustDrawings : True
File             : C:\Users\ansandfo\Downloads\Blah.xlsx
Stream           : System.IO.MemoryStream
Compression      : Level6
Compatibility    : OfficeOpenXml.Compatibility.CompatibilitySettings

[DBG]: PS C:\Windows\System32> $ExcelPackage.Save()

MethodInvocationException: Exception calling "Save" with "0" argument(s): "Error saving file C:\Users\ansandfo\Downloads\Blah.xlsx"
`
I hope this helps.

**Comment by neildeadman** [comment]
I have found that in PowerShell 5.1 Export-Excel with/without a password works:

![image](https://user-images.githubusercontent.com/52315/123930219-71eb7200-d987-11eb-8945-efde68443933.png)

However, in PSCore 7.1 it fails when saving with a password and gives the above error I reported initially:

![image](https://user-images.githubusercontent.com/52315/123930295-862f6f00-d987-11eb-91ed-986b04cf4995.png)

Would be good to sort this, as it was working before, but I have my script running again ready for tomorrow's monthly scheduled run in PS5.1.

**Comment by ansandfo** [comment]
> I have found that in PowerShell 5.1 Export-Excel with/without a password works:

Thanks @neildeadman unfortunately PS 5.1 doesn't work for me either:

``
Exception calling "Save" with "0" argument(s): "Error saving file C:\Users\ansandfo\Downloads\Temp6.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Close-ExcelPackage.ps1:27 char:29
+             else           {$ExcelPackage.Save()          }
+                             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
``

**Comment by ansandfo** [comment]
```
foreach ($device in $devices) 
    { 
        Copy-ExcelWorkSheet -SourceWorkbook $template -SourceWorkSheet device -DestinationWorkbook $ExcelFile -DestinationWorksheet $device.deviceName
    }
    Copy-ExcelWorkSheet -SourceWorkbook $template -SourceWorkSheet Overview -DestinationWorkbook $ExcelFile
```
The issue does not transpire during the 'foreach' loop but when I call 'Copy-ExcelWorkSheet' again for a different sheet in the template. Hopefully that might help with the troubleshooting? Thanks Andrew

**Comment by ansandfo** [comment]
This is still an issue even with ImportExcel 7.2.2.

**Comment by chr0ustik** [comment]
Hi, seems the issue is still there. PS 5.1 works and PS 7.5 does not.

<img width="1023" height="148" alt="Image" src="https://github.com/user-attachments/assets/6faaec92-c5a3-48da-acfc-7e3ccbc8e190" />

**Comment by dfinke** [comment]
Yup, feel free to look at line 685 in the Export-Excel. Don't know why the underlying DLL call is failing. The method signature lines up.
