### ISSUE TITLE
WARNING: 1.sql is not allowed as a table name because it does not begin with a letter.

### ISSUE THREAD

**Issue by francesco1119** [dfinke/ImportExcel#1042]
I'm re-writing a script that I first wrote many years ago. 
I'm using `dbatools `and `ImportExcel `to query a SQL Server estate.
I'm trying to execute [Glenn's SQL Server Performance](https://glennsqlperformance.com/) queries in bulk. 
The script overall is working and is saving the data correctly, it just rise a waring like: 

![image](https://user-images.githubusercontent.com/3397477/122775563-8d30f000-d2aa-11eb-902d-0398422426fa.png)

```
WARNING: 1.sql is not allowed as a table name because it does not begin with a letter.
Executing 1.sql on localhost
WARNING: 2.sql is not allowed as a table name because it does not begin with a letter.
Executing 2.sql on localhost
WARNING: 3.sql is not allowed as a table name because it does not begin with a letter.
Executing 3.sql on localhost
WARNING: 4.sql is not allowed as a table name because it does not begin with a letter.
Executing 4.sql on localhost
WARNING: 5.sql is not allowed as a table name because it does not begin with a letter.
Executing 5.sql on localhost
WARNING: 6.sql is not allowed as a table name because it does not begin with a letter.
Executing 6.sql on localhost
WARNING: 7.sql is not allowed as a table name because it does not begin with a letter.
Executing 7.sql on localhost
WARNING: 8.sql is not allowed as a table name because it does not begin with a letter.
Executing 8.sql on localhost
WARNING: 9.sql is not allowed as a table name because it does not begin with a letter.
Executing 9.sql on localhost
WARNING: 10.sql is not allowed as a table name because it does not begin with a letter.
Executing 10.sql on localhost
WARNING: At least one character in SYSDatabases.sql is illegal in a table name and will be replaced with '_' .
Executing SYSDatabases.sql on localhost
```

I's just very ugly to see and I would like to know if there is a way to suppress it or a better way to code.

This is my script: 

```
$SqlInstance = 'localhost'
$destinationDatabase = 'master'
$folderPath = '.\Queries'
$DateTime = (Get-Date).tostring("yyyy-MM-dd")
  
# Create a connection to the server that we will reuse - can use SqlCredential for alternative creds
$sqlInst = Connect-DbaInstance -SqlInstance $SqlInstance
  
(Get-ChildItem $folderPath | sort-object {if (($i = $_.BaseName -as [int])) {$i} else {$_}} ).Foreach{
    Invoke-DbaQuery -SqlInstance $sqlInst -Database $destinationDatabase -File $psitem.FullName | Export-Excel -Path ".\Results\$SqlInstance`_$DateTime`.xlsx" -AutoSize -TableName $psitem -WorksheetName $psitem
	write-host "Executing $psitem on $SqlInstance"
}
```
The script is picking up the queries from a folder called `Queries `and is saving them in a folder called `Results`. 

The queries in the folder  `Queries ` are indeed called: 
```
1.sql
2.sql
3.sql
4.sql
5.sql
etc...
```
And you can also download them from [here](https://github.com/francesco1119/QueryLauncher/tree/master/QueryLauncher).

So the question is: is there a way to suppress the `WARNING `or a better way to handle the` -AutoSize -TableName`?

**Comment by dfinke** [comment]
## Turn off warning

```powershell
$prefBackup = $WarningPreference
$WarningPreference = 'SilentlyContinue'
.\Test.ps1
$WarningPreference = $prefBackup
```

You could use `$psitem` and "scrub" it so it is a valid unique name for Excel to use.

**Comment by dfinke** [comment]
Table names can't start with a #, `sql_1` is valid. If you strip off the first two characters `1.sql` -> `sql`, `2.sql` -> `sql` then Excel will have issues cause those would not be unique tablenames.

**Comment by francesco1119** [comment]
Hi @dfinke , I changed the file name from `1.sql` to `sql_1.sql` and I now receive a new warning: 

`WARNING: At least one character in sql_1.sql is illegal in a table name and will be replaced with '_' .
`
![image](https://user-images.githubusercontent.com/3397477/122924672-4e607000-d366-11eb-9f2d-4e64ff4eb097.png)

Even the last query which is called `SYSDatabases.sql` has the same issue. Is this error prompted by ImportExcel or Powershell?

**Comment by dfinke** [comment]
That is generated by `ImportExcel`. I think the `.` is invalid.

**Comment by francesco1119** [comment]
Is getting interesting. 
I removed all but these queries: 

```
1.sql
2.sql
SYSDatabases.sql
```
The warning is the same as before: not allowed for numbers and illegal where there are only characters: 

```
WARNING: 1.sql is not allowed as a table name because it does not begin with a letter.
Executing 1.sql on localhost
WARNING: 2.sql is not allowed as a table name because it does not begin with a letter.
Executing 2.sql on localhost
WARNING: At least one character in SYSDatabases.sql is illegal in a table name and will be replaced with '_' .
Executing SYSDatabases.sql on localhost
```
But as you can see from the video the table is not generated for the first 2 queries but it's all good for the last one: 

![Error_symbol](https://user-images.githubusercontent.com/3397477/122933294-cc287980-d36e-11eb-938e-096dcfbd5982.gif)

Looks like a bug trigged by the numbers in the name. 
But once again, why it warns also with the last query where there are no numbers...?

**Comment by francesco1119** [comment]
I confirm you that the error persists even if I remove the file extension: 

![image](https://user-images.githubusercontent.com/3397477/122933864-4fe26600-d36f-11eb-9c0f-e3ee0556b986.png)

**Comment by dfinke** [comment]
I'm a bit confused the `WARNING: 1.sql is not allowed as a table name because it does not begin with a letter.` is saying the `-Tablename` being set is having the issue. That gets set inside the xlsx.

**Comment by francesco1119** [comment]
[Test.zip](https://github.com/dfinke/ImportExcel/files/6694819/Test.zip)

Look I upload here the whole script in a .zip file. 
Do you have a SQL Server where you can test?
