### ISSUE TITLE
Is it possible to add a average line in a chart?

### ISSUE THREAD

**Issue by Zuldan** [dfinke/ImportExcel#1044]
Here is an example:

![A2E5BF08-5E55-4F32-83BF-0AD947BA5087](https://user-images.githubusercontent.com/12680150/123543152-903b4d00-d790-11eb-83d3-c77f24d4575e.png)

**Comment by dfinke** [comment]
Seems only a `Moving Average` trend line is built in. You'd have to calculate that in PowerShell, add it to your dataset and include that column in the graph. 

![image](https://user-images.githubusercontent.com/67258/123546426-76ffb580-d72a-11eb-8ddc-34b185bff644.png)


```powershell
$data = ConvertFrom-Csv @"
Month,Sales
Jan,10
Feb,50
Mar,25
Apr,100
May,75
Jun,175
Jul,90
Aug,80
Sep,70
Oct,60
Nov,155
Dec,66
"@


$chartParams = @{    
    XRange         = 'Month'
    YRange         = 'Sales '
    Title          = "Sales" 
    ChartType      = 'ColumnClustered'
    ChartTrendLine = 'MovingAvgerage'
    NoLegend       = $true
}

$xlfilename = "./test.xlsx"
Remove-Item $xlfilename -ErrorAction SilentlyContinue

$data | Export-Excel $xlfilename -ExcelChartDefinition (New-ExcelChartDefinition @chartParams) -autosize -autoname -show 
```

**Comment by Zuldan** [comment]
@dfinke thank you so much for the quick response.

It looks like Excel calls it “Combo Charts”. Here is an example https://www.xelplus.com/learn-excel-macros/

Do you know if the API reveals anything similar to that?
