### ISSUE TITLE
Error with Add-ExcelName

### ISSUE THREAD

**Issue by jmilleretc** [dfinke/ImportExcel#1045]
I'm trying to use Add-ExcelName using the value in the variable $datarange for the "Range" parameter. I ma getting an error: 

Add-ExcelName : Cannot bind argument to parameter 'Range' because it is null.

Here is the code used to setup the $datarange variable and use it with Add-ExcelName:

# $datarange ends up with a value of "A2:A45"
$datarange = [char]34 + "A2:A" + ($concats.count + 2) + [char]34
$pltest=$xl.workbook.worksheets['Lists']
Add-ExcelName -Range $pltest.Cells[$datarange] -Rangename "Locations"

I've tried it with and without the double quotes. It works fine when I use:

Add-ExcelName -Range $pltest.Cells["A2:A3"] -Rangename "Locations"

When I did $datarange.gettype() it reports as a String with a Base Type of System.object

I also have the problem with the Name being localized to the Worksheet and not Global in the Workbook. I'm going to try this sample code that I saw in another issue to resolve this:

                  $xl=Open-ExcelPackage C:\temp\Test3.xlsx
                  $ws=$xl.Workbook.Worksheets["Sheet1"]
                  $RangeCells=$ws.cells["A1:A5"]
                  $xl.Workbook.Names.Add("MyRange",$RangeCells)
                 Close-ExcelPackage $xl -Show

Thanks in advance,

--John

**Comment by dfinke** [comment]
This works for `Add-ExcelName`. Names are not added to the Global space, don't have the anything for that.

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

Remove-Item ./test.xlsx -ErrorAction 'SilentlyContinue'

$xlpkg = $data | Export-Excel -Path .\Test.xlsx -AutoSize -PassThru

$cells = "A2:A" + $data.Count
$range = $xlpkg.sheet1.cells[$cells]

Add-ExcelName -Range $range -RangeName Region

Close-ExcelPackage $xlpkg -Show
```

**Comment by jmilleretc** [comment]
Hey Doug,

Thanks for responding. I was actually able to work around it with something I found on a similar issue. This gave the range name "Locations" a Global scope and didn't throw an error:

$wslisports = Add-Worksheet -ExcelPackage $xl -WorksheetName 'LISPorts'
$Rangecells=$wslists.cells["A2:A" + ($Locations.count + 1)]
$xl.Workbook.Names.Add("Locations",$RangeCells)

--John
