### ISSUE TITLE
Set-ExcelColumn not filling values (newbie question)

### ISSUE THREAD

**Issue by p2635** [dfinke/ImportExcel#1046]
It's my first time using this and I'm having trouble with Set-ExcelColumn, my script has no effect and I don't know why. I expected the last column to have "this is a test" for each row.

```
$excel = Open-ExcelPackage -Path "test.xlsx"
$ws = $excel.Workbook.Worksheets["Sheet"]
Set-ExcelColumn -Worksheet $ws -Heading "Notes" -Value {"this is a test"}
```

File: [test.xlsx](https://github.com/dfinke/ImportExcel/files/6765503/test.xlsx)

**Comment by stahler** [comment]
Specify a column for your values.

```PowerShell
$excel = Open-ExcelPackage -Path "test.xlsx"
$ws = $excel.Workbook.Worksheets["Sheet"]
Set-ExcelColumn -Worksheet $ws -Heading "Notes" -Column 9 -Value {"this is a test"}
Close-ExcelPackage $excel -Show
```

**Comment by p2635** [comment]
Thanks @stahler , it works now!

**Comment by p2635** [comment]
I don't know what is happening but this isn't working anymore. I didn't change the script so it must be my office or OS that updated. Is this command still working for people? In my case, what I mean by 'not working' is that the file becomes corrupt so I don't know where the issue is.

**Comment by p2635** [comment]
After investigating further, the issue was with bad data. The xlsx file that I was working with convert from a csv using a python script. False alam.
