### ISSUE TITLE
Import CSV into Existing XLSX with Pivot Table

### ISSUE THREAD

**Issue by pltrant** [dfinke/ImportExcel#1047]
Due to the issue noted in #249 (Pivot Table Corrupts Excel File), I'm trying to come up with a good way to import several CSV files into an existing XLSX file with pivot tables.  Because I need to add the data to an existing workbook (that has pivot tables), I can't just `Import-CSV <CSVfile> | Export-Excel <newExcelFile>`.  I believe I'm going to need to use `Open-ExcelPackage` to open the existing workbook in memory, then import the CSV files and add them as new worksheets.  There is `Add-Worksheet`, but that only creates an empty worksheet unless you also specify an existing worksheet to copy from.  Is there any easy way to import a CSV file, then copy that to a worksheet?  Or do I need to convert all the CSV files to XLSX files first, then loop through those and get a handle on their worksheets and use `Add-Worksheet -CopySource`?  Thanks!

**Comment by dfinke** [comment]
Not sure if you'll hit that issue, but maybe.

I'd start with something along the lines:

```powershell

$c=0
dir *.csv | % { 
    $wsn="wsn$($c)"
    import-csv $_ | export-excel ./existing.xlsx -WorksheetName  $c
    $c++
}
```

This creates a new sheet for each csv, you'll need to figure out how you want to name the sheet.
Yes, once the sheets are added, you'll need to use `Open-ExcelPackage` and `Close-ExcelPackage`.

Do you want to put the pivot table on the same sheet? Or a diff sheet for each pivot table?

Check this example for adding pivot tables to a sheet. 
https://github.com/dfinke/ImportExcel/blob/master/Examples/PivotTable/MultiplePivotTables.ps1
