### ISSUE TITLE
Creating excel load with data and encrypt with password and export

### ISSUE THREAD

**Issue by AshokPadarthi** [dfinke/ImportExcel#105]
Hi Team,

Is there any way by using this module " we can create a new excel,load values into it from PS Object and protect it with password and then export it to local rive"

Is there any code sample some thing which does this operation with this module

**Comment by AshokPadarthi** [comment]
Hi Team,

Is there any way by using this module " we can create a new excel,load values into it from PS Object and protect it with password and then export it to local rive"

Is there any code sample some thing which does this operation  with this module

**Comment by dfinke** [comment]
Currently only worksheet passwords are supported.

```powershell
rm C:\Temp\pwd.xlsx -ErrorAction Ignore

Get-Service | select Name,StartType,Status | 
    Export-Excel C:\Temp\pwd.xlsx -Password TestPwd -Show
```
