### ISSUE TITLE
How to have all values of object[] array "property" in single cell?

### ISSUE THREAD

**Issue by TrevorWesterdahl** [dfinke/ImportExcel#1050]
This issue is surfacing for me a lot. I am getting an object array returned with a few properties that are object arrays themselves. Almost all of these array properties have 1 to 5 values. 

This is not happening because of a one-to-many relationship. Its simply where properties are representing multiple options that were selected.  

By default, in Export-Excel, if there is one value for an object array property, the values IS placed in the cell. If there are 2 or more values, System.Object[] is placed for the value in the cell (the actual values are lost).

What I would much prefer is a comma separated list of values in the cell. 

Is there a way I can do this without pre-looping through the array and building my own custom array to export? I am writing queries against typical Microsoft code. For example, querying DFS (distributed file system) servers for namespace information. I would much prefer that Export-Excel have way to handle these properties (one solution), rather than requiring I create custom objects every time (there are many, many similar scenarios). 

I understand there would be a performance cost, but there always would be,

Hoping for something like this:

$ObjectArray | Select-Object -Property Path, Description, Type, State, Flags, TimeToLiveSec | Export-Excel -ArrayProperty State, Flags -Path $FilePath -AutoSize -AutoFilter 

In my example, the properties State and Flags can have multiple values supplied as an object[] array and I would like the cell to contain a comma-separated list of values. the "ArrayProperty" parameter is a suggestion to tell Export-Excel to loop through the values when exporting rather than the default behavior of showing System.Object[] with multiple values present..

Something like this might already exist and I don't know it.

Thanks,
Trevor

**Comment by scriptingstudio** [comment]
As a workaround you may want to explicitly convert an array to a string.
``` powershell
$ObjectArray | Select-Object -Property Path, Description, Type, 
@{n='State'; e={$_.state -join ','}}, 
@{n='Flags'; e={$_.flags -join ','}}, 
TimeToLiveSec
```

**Comment by TrevorWesterdahl** [comment]
Just confirming that the workaround does indeed work. My request was just to avoid having to do that so often. Appreciate your time and support.

**Comment by dfinke** [comment]
@TrevorWesterdahl will think about it, probably won't add it though.
