### ISSUE TITLE
How to set footer and header in the worksheet?

### ISSUE THREAD

**Issue by badboylolipop** [dfinke/ImportExcel#1052]
Sorry I tried searching all over but can’t seem to find any answer. I’m using the this importexcel module and can’t seem to find any way to add footer and header to the worksheet. Grateful for any help given. Thanks.

**Comment by dfinke** [comment]
```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
"@

$xlfileName = ".\HeaderFooter.xlsx"
Remove-Item $xlfileName -ErrorAction SilentlyContinue

$xlpkg = $data | Export-Excel -Path $xlfileName -PassThru

$xlpkg.Sheet1.HeaderFooter.OddHeader.CenteredText = "Hello From PowerShell"
$xlpkg.Sheet1.HeaderFooter.OddFooter.RightAlignedText = (Get-Date).ToShortDateString()

Close-ExcelPackage $xlpkg -Show
```

![image](https://user-images.githubusercontent.com/67258/126542358-433456b8-60c4-48fa-81f1-b2606595d7f6.png)

**Comment by badboylolipop** [comment]
Thank you dfinke. Much appreciated. I think it will be good to have this added in the module as well. Closing this now.
