### ISSUE TITLE
Read (import-excel) in chunks

### ISSUE THREAD

**Issue by delcorral** [dfinke/ImportExcel#1053]
I have a very large excel files (some of them below 10MB, and others ca 60MB each) where all the data is on 1 worksheet (other sheets are PVs of the data), and I would like to be able to read it in 'chunks' while processing it, as I have realized that reading end-2-end files in excess of 10k records then it slows down the process (and some times failing when running out of memory); so when I try to read the file in 'chunks' by strep 1) `$ep=(Open-ExcelPackage -path "$sourcePath\$fileName");` step 2) `$buffer=(import-excel -ExcelPackage $ep -verbose -worksheetname $worksheet -HeaderName $headers -startrow $firstDataRow -EndRow $lastDataRow)`  it fails when the 1st row is bigger than a 10000.

Is there any way that I could read the excel file (xlsx) in chunks and overcomming this error when reaching 10k records per page/cunk?

**Comment by dfinke** [comment]
I like the idea. Nothing exits that helps there, you'd to handle everything on your own. Reading the data, transforming to PS objects with properties, and chunking it.

**Comment by delcorral** [comment]
Hi, thanks for the response,

I was thinking of increasing the limit of the -startrow variable so it could support a larger integer, as it works great for the 1st 10k records, and the speed is good enough.

Do you think that is possible for -startrow variable so to support a larger integer?
