### ISSUE TITLE
Excel Row Height and AutoSize

### ISSUE THREAD

**Issue by swpsnovice** [dfinke/ImportExcel#1058]
I have been looking for a solution to an issue that I am just at my limits of personal knowledge. This is related to https://github.com/dfinke/ImportExcel/issues/295.

I run a number of SQL files that I then dump the data into Excel. The data is then used to build a user friendly report by adding line breaks and headings. With ImportExcel, I can set my ExcelRange to a specific row height, however, the data set is dynamic in size. Are there any workarounds that anyone has discovered to setting a dynamic row height after exporting the data into the Excel file?

As can be read in the script below, all of the data is first imported to the "RawData" worksheet, and then I use Excel formulas in two other worksheets to build the more consumable data, which ends up being the report that is shared.

Unfortunately, the rows of these other two worksheets all stay with the default height, 15.75. I can set the height to a specific number (409 is the largest), but the data set is dynamic in length, so I need it to snap to the actual height (like Excel AutoFit).

**Comment by swpsnovice** [comment]
My current script:

#File Date
$Date = (Get-Date).tostring("MM-dd-yyyy-hh-mm")

#Define File that will be used to contain all data
$xlfile = "\\servername\Report_$date.xlsx"

#.csv File Path's
$Path = "\\servername\path"

#Remove file so that any new changes can be applied
#Remove-Item $xlfile -ErrorAction Ignore
Remove-Item \\servername\*.csv

Invoke-Sqlcmd -InputFile "\\servername\import1.sql" -ServerInstance "servername" -database "database1" | Export-Csv -notypeinformation -Path "\\servername\export1.csv"
Invoke-Sqlcmd -InputFile "\\servername\import2.sql" -ServerInstance "servername" -database "database1" | Export-Csv -notypeinformation -Path "\\servername\export2.csv"
Invoke-Sqlcmd -InputFile "\\servername\import3.sql" -ServerInstance "servername" -database "database1" | Export-Csv -notypeinformation -Path "\\servername\export3.csv"
Invoke-Sqlcmd -InputFile "\\servername\import4.sql" -ServerInstance "servername" -database "database1" | Export-Csv -notypeinformation -Path "\\servername\export4.csv"

#Required Parameters
$params = @{
    AutoSize             = $true
    Path                 = $xlfile
}

#Import .csv files into main file, using the parameters above.
Import-Csv "$Path\export1.csv"  | Export-Excel -WorkSheetname RawData -StartRow 1 -StartColumn 1 @params
Import-Csv "$Path\export2.csv"  | Export-Excel -WorkSheetname Open_Unapproved -StartRow 1 -StartColumn 1 @params
Import-Csv "$Path\export3.csv" | Export-Excel -WorkSheetname RawData -StartRow 1 -StartColumn 17 @params
Import-Csv "$Path\export4.csv" | Export-Excel -WorkSheetname Approved_Past_Imp -StartRow 1 -StartColumn 1 @params

$pkg = Export-Excel -Path $xlfile -AutoSize -PassThru
$RawData = $pkg.Workbook.Worksheets["RawData"]
$Open_Unapproved = $pkg.Workbook.Worksheets["Open_Unapproved"]
$Approved_Past_Imp = $pkg.Workbook.Worksheets["Approved_Past_Imp"]

#Create worksheets
Add-Worksheet -ExcelPackage $pkg -WorksheetName "Open_Unapproved"
Add-Worksheet -ExcelPackage $pkg -WorksheetName "Approved_Past_Imp"
Add-Worksheet -ExcelPackage $pkg -WorksheetName "RawData"

#Add Data to Open_Unapproved
[int]$incre = 2
2..($Open_Unapproved.Dimension.Rows) |
    ForEach-Object {
        $Open_Unapproved.Cells["B$_"].Formula = '="Status: "&CHAR(10)&RawData!C'+$incre+'&CHAR(10)&CHAR(10)&"Assigned To: "&CHAR(10)&RawData!D'+$incre+'&CHAR(10)&CHAR(10)&"Downtime: "&CHAR(10)&IF(RawData!J'+$incre+'=TRUE,"Yes","No")&CHAR(10)&CHAR(10)&"Change Type: "&CHAR(10)&RawData!N'+$incre+''
        $Open_Unapproved.Cells["C$_"].Formula = '="Description: "&CHAR(10)&CLEAN(RawData!B'+$incre+')&CHAR(10)&CHAR(10)&"Reason: "&CHAR(10)&CLEAN(RawData!K'+$incre+')&CHAR(10)&CHAR(10)&"Backout Plan: "&CHAR(10)&CLEAN(RawData!M'+$incre+')'
        $Open_Unapproved.Cells["D$_"].Formula = '="Start Date: "&CHAR(10)&TEXT(RawData!F'+$incre+',"m/d/yyyy h:mm am/pm")&CHAR(10)&CHAR(10)&"End Date: "&CHAR(10)&TEXT(RawData!G'+$incre+',"m/d/yyyy h:mm am/pm")&IF(IF(RawData!J'+$incre+'=TRUE,"Yes","No")="Yes",(CHAR(10)&CHAR(10)&"Downtime Start: "&CHAR(10)&TEXT(RawData!H'+$incre+',"m/d/yyyy h:mm am/pm")&CHAR(10)&CHAR(10)&"Downtime End: "&CHAR(10)&TEXT(RawData!I'+$incre+',"m/d/yyyy h:mm am/pm")),"")'
        $Open_Unapproved.Cells["E$_"].Formula = '=MOD(ROW(),2)=0'
        $incre++
    }

#Alternate Color Open_Unapproved. Note the Dynamic Address Dimension, which applies to the whole used range!
Add-ConditionalFormatting -Worksheet $Open_Unapproved -Address $Open_Unapproved.Dimension.Address -BackgroundColor "LightGray" -RuleType Expression -ConditionValue "=`$E2=FALSE"

#Format Open_Unapproved
#Set-ExcelRange -Worksheet $Open_Unapproved -Range $Open_Unapproved.Dimension.Address -AutoSize
Set-ExcelRange -Worksheet $Open_Unapproved -Range "A1" -Value "Change Request" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Open_Unapproved -Range "B1" -Value "Overview" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Open_Unapproved -Range "C1" -Value "Details and Plan" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Open_Unapproved -Range "D1" -Value "Date/Time" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Open_Unapproved -Range "A1:D1" -FontColor White -BackgroundColor MidnightBlue
Set-ExcelRange -Worksheet $Open_Unapproved -Range $Open_Unapproved.Dimension.Address -BorderBottom Thin -BorderTop Thin -BorderLeft Thin -BorderRight Thin
#Set-ExcelRange -Worksheet $Open_Unapproved -Range "A:D" -VerticalAlignment Center
Set-ExcelRange -Worksheet $Open_Unapproved -Range "A:A" -Width 20
Set-ExcelRange -Worksheet $Open_Unapproved -Range "B:B" -Width 30
Set-ExcelRange -Worksheet $Open_Unapproved -Range "C:C" -Width 80
Set-ExcelRange -Worksheet $Open_Unapproved -Range "D:D" -Width 30
Set-ExcelColumn -Worksheet $Open_Unapproved -Column 5 -Hide
Set-Excelrange -Worksheet $Open_Unapproved -Range "A1:D1" -Height 16
Set-ExcelRange -Worksheet $Open_Unapproved -Range "A:D" -VerticalAlignment Center -WrapText

#Add Data to Approved_Past_Imp
[int]$incre = 2
2..($Approved_Past_Imp.Dimension.Rows) |
    ForEach-Object {
        $Approved_Past_Imp.Cells["B$_"].Formula = '="Status: "&CHAR(10)&RawData!S'+$incre+'&CHAR(10)&CHAR(10)&"Assigned To: "&CHAR(10)&RawData!T'+$incre+'&CHAR(10)&CHAR(10)&"Downtime: "&CHAR(10)&IF(RawData!Z'+$incre+'="TRUE","Yes","No")&CHAR(10)&CHAR(10)&"Change Type: "&CHAR(10)&RawData!AD'+$incre+''
        $Approved_Past_Imp.Cells["C$_"].Formula = '="Description: "&CHAR(10)&CLEAN(RawData!R'+$incre+')&CHAR(10)&CHAR(10)&"Reason: "&CHAR(10)&CLEAN(RawData!AA'+$incre+')&CHAR(10)&CHAR(10)&"Backout Plan: "&CHAR(10)&CLEAN(RawData!AC'+$incre+')'
        $Approved_Past_Imp.Cells["D$_"].Formula = '="Start Date: "&CHAR(10)&TEXT(RawData!V'+$incre+',"m/d/yyyy h:mm am/pm")&CHAR(10)&CHAR(10)&"End Date: "&CHAR(10)&TEXT(RawData!W'+$incre+',"m/d/yyyy h:mm am/pm")&IF(IF(RawData!Z'+$incre+'="TRUE","Yes","No")="Yes",(CHAR(10)&CHAR(10)&"Downtime Start: "&CHAR(10)&TEXT(RawData!X'+$incre+',"m/d/yyyy h:mm am/pm")&CHAR(10)&CHAR(10)&"Downtime End: "&CHAR(10)&TEXT(RawData!Y'+$incre+',"m/d/yyyy h:mm am/pm")),"")'
        $Approved_Past_Imp.Cells["E$_"].Formula = '=MOD(ROW(),2)=0'
        $incre++
    }

#Alternate Color Approved_Past_Imp. Note the Dynamic Address Dimension, which applies to the whole used range!
Add-ConditionalFormatting -Worksheet $Approved_Past_Imp -Address $Approved_Past_Imp.Dimension.Address -BackgroundColor "LightGray" -RuleType Expression -ConditionValue "=`$E2=FALSE"

#Format Open_Unapproved
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "A1" -Value "Change Request" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "B1" -Value "Overview" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "C1" -Value "Details and Plan" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "D1" -Value "Date/Time" -Bold -FontSize 12
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "A1:D1" -FontColor White -BackgroundColor Red
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range $Approved_Past_Imp.Dimension.Address -BorderBottom Thin -BorderTop Thin -BorderLeft Thin -BorderRight Thin
Set-ExcelRange -Worksheet $Approved_Past_Imp - #-Range $Approved_Past_Imp.Dimension.Address -Height 409
#Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "A:D" -VerticalAlignment Center
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "A:A" -Width 20
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "B:B" -Width 30
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "C:C" -Width 80
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "D:D" -Width 30
Set-ExcelColumn -Worksheet $Approved_Past_Imp -Column 5 -Hide
Set-Excelrange -Worksheet $Approved_Past_Imp -Range "A1:D1" -Height 16
Set-ExcelRange -Worksheet $Approved_Past_Imp -Range "A:D" -VerticalAlignment Center -WrapText

Close-ExcelPackage -ExcelPackage $pkg -Show

**Comment by swpsnovice** [comment]
So this weekend I wrote the following within PowerShell, but outside of the ImportExcel realm. This gets me what I am looking for, but I have to re-open the Excel file. Any thoughts on how to not have to reopen?

#Open Excel File
$Excel = New-Object -ComObject Excel.Application
$Excel.displayalerts = $false
$Workbook = $Excel.Workbooks.Open($xlfile)

#Connect to first worksheet to rename and make active
$serverInfoSheet1 = $workbook.Worksheets.Item(2)
$serverInfoSheet1.Activate() | Out-Null

#Auto fit everything so it looks better
$serverInfoSheet1.rows.AutoFit() | Out-Null
$ws.PageSetup.LeftHeader = ""

$serverInfoSheet2 = $workbook.Worksheets.Item(3)
$serverInfoSheet2.Activate() | Out-Null

#Auto fit everything so it looks better
$serverInfoSheet2.rows.AutoFit() | Out-Null

#Pending Approval
$filepath1 = Join-Path -Path $path -ChildPath ("ReportName_Worksheet1_$date.pdf”)
$serverInfoSheet2.PageSetup.FitToPagesTall = 9999
$serverInfoSheet1.PageSetup.Orientation = 2
$serverInfoSheet1.pagesetup.Zoom = $false
$serverInfoSheet1.PageSetup.FitToPagesWide = 1
$serverInfoSheet1.ExportAsFixedFormat($xlFixedFormat::xlTypePDF, $filepath1)

#Past Due
$filepath2 = Join-Path -Path $path -ChildPath ("ReportName_Worksheet2_$date.pdf”)
$serverInfoSheet2.PageSetup.FitToPagesTall = 9999
$serverInfoSheet2.PageSetup.Orientation = 2
$serverInfoSheet2.pagesetup.Zoom = $false
$serverInfoSheet2.PageSetup.FitToPagesWide = 1
$serverInfoSheet2.ExportAsFixedFormat($xlFixedFormat::xlTypePDF, $filepath2)

#Quit the application
$excel.Quit()

#Release COM Object
[System.Runtime.InteropServices.Marshal]::ReleaseComObject([System.__ComObject]$excel) | Out-Null

**Comment by rywards** [comment]
Coming across this a few years later - has anyone been able to get something like this working with ImportExcel?
