### ISSUE TITLE
Web pages with authentication does not work get-htmltable

### ISSUE THREAD

**Issue by cocana** [dfinke/ImportExcel#106]
I added "-usedefaultcredentials" (get-htmltable.ps1 file)

`$r = Invoke-WebRequest $url -UseDefaultCredentials`

maybe an additional parameter to include credentials would be better.

**Comment by dfinke** [comment]
Added https://github.com/dfinke/ImportExcel/commit/2da4575496bb6bf574290c9b47c3f9db8adc1d95
