### ISSUE TITLE
Error when using Add-Worksheet

### ISSUE THREAD

**Issue by micromega-prog** [dfinke/ImportExcel#1061]
I'm currently running version 7.1.1 of the ImportExcel module. I was running 7.2.2 but I reverted to 7.1.1 thinking that it might be an issue with the newer version. However, it seems to happen in both versions.

When running the following commands we are consistently getting an error:

`$excel = Open-ExcelPackage -Path $excelPath`
`Add-Worksheet -ExcelPackage $excel -WorksheetName Values -MoveToEnd`

The error message is:

_Exception calling "Add" with "1" argument(s): "Object reference not set to an instance of an object." At C:\Modules\User\ImportExcel\7.1.1\Public\Add-Worksheet.ps1:38 char:11 + $ws = $ExcelWorkbook.Worksheets.Add($WorksheetName) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : NullReferenceException_ 

And then we'll get a second error as follows:

_Get-Member : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again. At C:\Modules\User\ImportExcel\7.1.1\Public\Add-Worksheet.ps1:75 char:78 + ... e -and -not (Get-Member -InputObject $ExcelPackage -Name $ws.Name)) { + ~~~~~~~~ + CategoryInfo : InvalidData: (:) [Get-Member], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetMemberCommand_ 

I found a temporary workaround which involves running the Add-Worksheet command a second time. The second attempt always appears to work.

**Comment by dfinke** [comment]
## This worked for me

I don't recall any changes being made to `Add-Worksheet`. Don't know why you're bumping into that.

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$excelPath = ".\Test.xlsx"
Remove-Item $excelPath -ErrorAction SilentlyContinue

$data | Export-Excel $excelPath 

$excel = Open-ExcelPackage -Path $excelPath
$ws = Add-Worksheet -ExcelPackage $excel -WorksheetName Values -MoveToEnd

$ws.Cells["A1"].Value = "Test Data"

Close-ExcelPackage $excel -Show
```

![image](https://user-images.githubusercontent.com/67258/128947732-ebecd425-83a6-4f86-9691-4d6026bd4cbf.png)


## Running

```powershell
ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     7.2.2                 ImportExcel                         Desk     
                                                                              
```

```powershell

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
