### ISSUE TITLE
Formatting Values in a Column (Please Help)

### ISSUE THREAD

**Issue by Kerryoaks** [dfinke/ImportExcel#1063]
Newbie PowerShell user here.  Thanks so much for ImportExcel!!!

I’m creating an automated daily report on various server checks.  An example is DHCP scopes and the percentage used per scope.  I can’t seem to be able to format the Percentage in Use column (Column E) as a percentage.  I have a number of other similar outputs with the same issue.  Please can someone help as this would be great to crack!

Thanks in advance.  Please see example code:

#Variable for DHCP Servers
$DHCPServers = "DHCP001", "DHCP002", "DHCP003", "DHCP004", "DHCP005"
 
#Conditional Format Variables
$ScopeRed = New-ConditionalText -Range "E2:E1081" -ConditionalType GreaterThan 75  -BackgroundColor Red -ConditionalTextColor Black
$ScopeAmber = New-ConditionalText -Range "E2:E1081" -ConditionalType GreaterThan 50 -BackgroundColor LightYellow -ConditionalTextColor Orange
$ScopeGreen = New-ConditionalText -Range "E2:E1081" -ConditionalType LessThan 50  -BackgroundColor lightgreen -ConditionalTextColor Green
 
ForEach ($DHCPServer in $DHCPServers)
    {
    $DHCPScope = Get-DhcpServerv4Scopestatistics -ComputerName $DHCPServer | select ScopeID, Free, InUse, Reserved, PercentageInUse | Sort-Object ScopeID
    $Line +=  $DHCPScope
    }
 
 $Line | Export-Excel -AutoSize  -FreezeTopRowFirstColumn -AutoFilter -WorksheetName "DHCPScopes" -Path "$Path\Server Checks - $Date.xlsx" -ConditionalText$ScopeRed, $ScopeAmber, $ScopeGreen
   
 #Set-ExcelRange -Worksheet 'DHCPScopes' -Range e:e -NumberFormat 'Percentage'
#I can’t get this bit to work!!^^^^

**Comment by dfinke** [comment]
## Try this

```powershell
$xlpkg = $Line | Export-Excel -AutoSize -FreezeTopRowFirstColumn -AutoFilter -WorksheetName "DHCPScopes" -Path "$Path\Server Checks - $Date.xlsx" -ConditionalText$ScopeRed, $ScopeAmber, $ScopeGreen -PassThru

Set-ExcelRange -Worksheet $xlpkg.DHCPScopes -Range e:e -NumberFormat 'Percentage'

Close-ExcelPackage $xlpkg -Show
```

**Comment by Kerryoaks** [comment]
Thanks so much for your answer.  That’s worked!!!
Although I need to divide the percentage values by 100 to display properly.  As an example the output value is showing as 4237.29%
There’s probably an easy way to do that.  But as the PercentageInUse is not a variable I don’t know how to achieve that?
So sorry, just trying to learn and getting caught with these gotchas
(I know this has nothing to do with Import-Excel and all to do with my lack of knowledge)

**Comment by Kerryoaks** [comment]
@dfinke 
Please ignore my last comment.  I’ve managed to learn how to create a label and expression to get the values I wanted.

Thanks so much for your help, very much appreciated!
