### ISSUE TITLE
Question: How I can use variable as sheet name in $sheet1 = $xl.Workbook.Worksheets["Sheet1"]

### ISSUE THREAD

**Issue by mihadro** [dfinke/ImportExcel#1065]
I try to use variable as sheet name in $sheet1 = $xl.Workbook.Worksheets["Sheet1"] and powershell said me:
ParserError: xlscd.ps1:57
Line |
  57 |      $sheet = $excel.Workbook.Worksheets [$mtikname]
     |                                                                    ~~~~~~~~~~~
     | Unexpected token '[$mtikname]' in expression or statement.

**Comment by JimBobUKII** [comment]
@mihadro  Althoogh this is closed issue, encapsulating may be your answer

```powershell
$sheet1 = $($xl.Workbook.Worksheets["Sheet1"])
```
