### ISSUE TITLE
Question - "Display" a Cell (Scrolling)

### ISSUE THREAD

**Issue by hpwhite** [dfinke/ImportExcel#1066]
I am writing a script to clean up an existing spreadsheet that comes out of a legacy system, and this module has been a god send. The one thing I have not been able to figure out is how to "Display" a given cell when the worksheet is opened. I can select a cell ($Worksheet.Select('A2')), but it does not "Display" it. 

To be clear, what I mean by "Display" is  actually scroll that cell into view, so when someone opens that worksheet  that cell will be selected and in view.

I can live with just forcing scrollbars all the way up and over so that A1 is in the upper left corner as well (for my immediate need), but knowing how to "Display" any general cell would be handy.

Please let me know.

**Comment by hpwhite** [comment]
Is there a way to do this with ImportExcel? I know it can be done with the Excel COM object, but I would rather not resort to that.

**Comment by dfinke** [comment]
I believe it can only be done via COM. This module interacts with the xlsx content, not UI interaction.

**Comment by hpwhite** [comment]
OK, thanks for the feedback, but keep in mind this "Startup Position" is save in the xlsx file "someplace", since when the file is opened on any machine that cell will be selected and brought into view. Basically,  Excel opens the xlsx in the display state (scroll positions, cell selected, etc.) of when the xlsx was last saved, so this info is in the xlsx someplace! :-)

**Comment by dfinke** [comment]
Hmm. If you could look into "startup position epplus" let me know what you find. Have you renamed the xlsx to zip, and unzip it to find the actual xml tag name that has that? Also good to search on. EPPlus may not support that though.

**Comment by hpwhite** [comment]
Doug:

So I did what you asked (renamed .zip and looked at the results). I made a very simple Excel file (1,2,3,4,5 in A1 – A5) with A1 selected in both cases.
 
Case 1: A1 in view (top left corner) when saved
Case 2: A100 in view (top left corner) when saved
 
The resulting stuff in the zip file were exactly the same EXCEPT the following (In the file /xl/worksheets/sheet1.xml):
 
Case 1 (A1 in view):
<dimension ref="A1:A5"/>
<sheetViews> <file:///C:/Users/pwhite.MSISAC/Desktop/Excel%20Test/A1/A1%20in%20view/xl/worksheets/sheet1.xml>
   <sheetView workbookViewId="0" tabSelected="1"/>
</sheetViews>
 
 
Case 2 (A100 in view):
<dimension ref="A1:A5"/>
<sheetViews> <file:///C:/Users/pwhite.MSISAC/Desktop/Excel%20Test/A100/A100%20in%20view/xl/worksheets/sheet1.xml>
   <sheetView workbookViewId="0" topLeftCell="A100" tabSelected="1"/>
</sheetViews>
 
So, topLeftCell=”A100” is added.
 
Is this something that can be added when the file is saved? With the Excel COM Obj, this location seem to follow what cell was active when saved. In your case maybe use the same, or a separate “TopLeftCell” property. Whatever you think is best.
 
Please let me know your thoughts.

**Comment by dfinke** [comment]
Thanks for the details and investigating. Next is to see if EPPlus supports that. If it doesn't then probably won't add it to the PS module.

**Comment by dfinke** [comment]
Looks the `TopLeftCell` setting is only added in the new version of EPPlus. Doesn't look good getting it into the PS module.
https://epplussoftware.com/docs/5.2/articles/fixedissues.html

**Comment by hpwhite** [comment]
Doug:

Thanks for the reply and the clarification. So, based on this I assume you have standardize on some older version of EPPlus and are not planning on updating?

Phil

**Comment by dfinke** [comment]
The new version of EPPlus requires each user to purchase a license if used in a commercial setting. In addition, they have fixed and updated many issues that create breaking changes.

This PS module is based on the last free EPPlus offering. I am still evaluating moving to the new paid version.

**Comment by hpwhite** [comment]
I see, thanks for explaining.

All I can say is your product is super useful !!!! Maybe a "go fund me" or something to pay for the commercial license.

Yeah, sometimes “backward” compatibility is not the first priority for some SW developers… :-) 

Thanks for what you are doing and let me know what you decide.

Phil

**Comment by dfinke** [comment]
Thanks! For the EPPlus license, each user of ImportExcel would have to buy a license, not me. Then that gets into all kinds of support issues etc. We'll see.
