### ISSUE TITLE
Open-ExcelPackage opens local files (path) - how would I open a file stored in a variable?

### ISSUE THREAD

**Issue by DEberhardt** [dfinke/ImportExcel#1068]
Hello,

I am playing around with Files from Sharepoint and have so far been able to:
- [X] Download a file
- [X] Download a file into a variable
- [X] Process the downloaded file
- [ ] Process directly through file in variable

```powershell
$LocalFolder = 'C:\Temp'

# Connecting to PNP
Connect-PnPOnline -Url https://tenant.sharepoint.com/sites/SiteName -UseWebLogin # haven't tested Interactive yet, but getting warning for it, will deal with this later
$fileRelativeURL = '/sites/SiteName/Shared Documents/test.xlsx'
$fileName = 'test.xlsx'

# Downloading my File locally (works)
Get-PnPFile -Url $RelativeFilePath -Path $LocalFolder -Filename $Filename -AsFile -Force

# File parsed directly from Sharepoint (works)
$File1 = Get-PnPFile -Url $RelativeFilePath -AsFileObject #-AsString -Force # AsString does not work :/

# Getting ChildItem
$File2 = Get-ChildItem $LocalFilePath | Select-Object -First 1

# Type Test
$File1 | Get-Member
$File2 | Get-Member
#endregion


#region File Upload
#TEST This needs validation - is untested currently!
#Add-File -Path $File2 -Folder $RemoteFolder -Checkout -Publish
#endregion

$InputFile = Open-ExcelPackage -Path $LocalFilePath
```

`$File1` is of type: `Microsoft.SharePoint.Client.File`
`$File2` is of type: `System.IO.FileInfo`

`$File2` can be handled with Open-ExcelPackage
`$File1` cannot - Is there a way for me to coax this one to be opened?

Do I need to employ the native methods they provide?
I can check out the file, update and even check it back in again, but I don't seem to be able to load `$File1` into anything.
I know I am (probably daft and am just) missing a step, could someone nudge me please? 😄

**Comment by dfinke** [comment]
Sorry, I have no experience with `Get-PnPFile`

**Comment by scriptingstudio** [comment]
@DEberhardt download your file just a file:
`$File1 = Get-PnPFile -Url $RelativeFilePath`
see doc example1:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfile?view=sharepoint-ps

**Comment by DEberhardt** [comment]
Yes, I do this currently. Downloading is working fine. I have also explored uploading it afterwards as a new version of the same file.
The idea was to not exactly download it, but open it in PowerShell as a variable and changing it there immediately. Saving it afterwards (like editing it in the web view)... but I guess download/reupload will have to do :)

**Comment by scriptingstudio** [comment]
The module works with files, not streams. I have no idea if it can.

**Comment by dfinke** [comment]
`Open-ExcelPackage` works with a `$Path`.
https://github.com/dfinke/ImportExcel/blob/master/Public/Open-ExcelPackage.ps1#L30

`New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path`

Check out `Import-Excel`, it works with a `FileStream`, but points to a file. This may give some clues how you can point to to the remote file, and then coerce it so the `OfficeOpenXml.ExcelPackage` can work with it.

https://github.com/dfinke/ImportExcel/blob/694fcdd8c1b5c993feba67fc56fb7a5209a926be/Public/Import-Excel.ps1#L110-L111

**Comment by scriptingstudio** [comment]
I think I got it. The problem is how to convert `Get-PnPFile` output stream to `System.IO.FileStream` and then customize `Open-ExcelPackage` or `Import-Excel` path parameter. But the easiest way is just download a file and open it with the module.

**Comment by dfinke** [comment]
@scriptingstudio Yes, that would be it. Then there could be an `Open-ExcelPackageStream`. I probably would not add that to the `ImportExcel` module, so yes, download the file and go from there :)
