### ISSUE TITLE
Pivot Table/Chart Grouping

### ISSUE THREAD

**Issue by JohnD76** [dfinke/ImportExcel#107]
Hi, 

Is it possible to group and ungroup large Row Labels ?

For example, Date Time Row Labels into Years/Quarters/Months and Days?

Thanks,

John.

**Comment by dfinke** [comment]
Could you say a bit more. Can you post a screen shot?

**Comment by JohnD76** [comment]
Hi,

I am running the following:

`Clear-host

$orgCulture = Get-Culture
[System.Threading.Thread]::CurrentThread.CurrentCulture = New-Object "System.Globalization.CultureInfo" "en-US"

$EventFiles=Get-ChildItem C:\RCA\Exchange -Filter *.evtx -recurse | Select Fullname, Directory, Basename

ForEach ($Eventlog in $EventFiles)
{
    $XLSFile=(Join-Path $Eventlog.Directory $Eventlog.Basename)+".xlsx"
    Get-winevent -path $Eventlog.FullName | Select TimeCreated,Level,LevelDisplayName,ID,ProviderName,Message | Where Level -lt 3 |  Export-Excel $XLSFile -Show -IncludePivotTable -PivotRows "TimeCreated" -PivotColumns "ProviderName" -PivotData @{ID=”count”} -IncludePivotChart -ChartType Line
}

[System.Threading.Thread]::CurrentThread.CurrentCulture = $orgCulture
Remove-Variable -Name * -ErrorAction SilentlyContinue`

I would ideally like to be able to parse a parameter to group the PivotTable items. At present, I am doing this manually via Excel, which can be see in the example.

[Example.pdf](https://github.com/dfinke/ImportExcel/files/331719/Example.pdf)
