### ISSUE TITLE
How to insert a value into a specific cell of an existing excel file?

### ISSUE THREAD

**Issue by lil-S** [dfinke/ImportExcel#1070]
I know kind of a noob question but I can't figure out how to put a value into specific cell of an existing excel file.

For example I have an excel file with the headers "First Name" "Surname" and "Phone Number" and now I want to insert a value into cell B2. How can I do that?

This is a code snippet from what I already (unsuccessfully) tried:
Import-Module ImportExcel

$directory = get-location
$excelFile = Open-ExcelPackage "$directory\Test123.xlsx"

Set-ExcelColumn -ExcelPackage $excelFile -Worksheetname "Tabelle1" -StartRow 2 -Value "Smith!"

Close-ExcelPackage -ExcelPackage $excelFile -Show

And this is the exmaple excel file:
[Test123.xlsx](https://github.com/dfinke/ImportExcel/files/7047441/Test123.xlsx)

Thanks for your help! :D

**Comment by dfinke** [comment]
`-PassThru` returns the "Excel Object" same as the `Open-ExcelPackage`.

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

Remove-Item ./test.xlsx -ErrorAction SilentlyContinue
$xlpkg = $data | Export-Excel ./test.xlsx -PassThru

Set-ExcelRange -Worksheet $xlpkg.Sheet1 -Range "D13" -Value "Hello World" -AutoSize -BackgroundColor Red

Close-ExcelPackage $xlpkg -Show
```

![image](https://user-images.githubusercontent.com/67258/130825260-3ad63e39-9dfa-4693-9d97-9e849be178a8.png)

**Comment by lil-S** [comment]
Closing this issue now, found a work around with CSV files.
