### ISSUE TITLE
How to Insert and Delete Columns when working with Package

### ISSUE THREAD

**Issue by rlefever** [dfinke/ImportExcel#1073]
Please provide an example of how to insert/delete a column once worksheet has been opened via Open-ExcelPackage or Import-Excel.  I need to insert the column in the middle of the existing data. The only way I can think of is to convert it to CSV, change the data, and convert it back. Working with strings doesn't seem like it would be the proper PowerShell way. Hoping this wonderful module has a way.

Thanks for the module and the assistance,

**Comment by dfinke** [comment]
## DeleteColumn is straightforward 

```powershell
$ws.DeleteColumn

OverloadDefinitions
-------------------
void DeleteColumn(int column)
void DeleteColumn(int columnFrom, int columns)
```

## Insert is more challenging

The module has no helper functions to transform a  PS array to a column etc for an existing sheet.

These lines (off the top of my head), would need to be worked into a function, generalized, handle error conditions, and be tested using Pester.

```powershell
$ws.InsertColumn(2, 1)

$row = 1
$ws.Cells[$row, 2].Value = 'Month'
$row += 1
for ($i = 0; $i -lt $months.Count; $i++) {
    $ws.Cells[$row, 2].Value = $months[$i]
    $row += 1
}
```

## Insert Example

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = "./test.xlsx"
Remove-Item  $xlfile -ErrorAction SilentlyContinue

$xlpkg = $data | Export-Excel $xlfile -PassThru

$ws = $xlpkg.Sheet1

$months = @("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep")

$ws.InsertColumn(2, 1)

$row = 1
$ws.Cells[$row, 2].Value = 'Month'
$row += 1
for ($i = 0; $i -lt $months.Count; $i++) {
    $ws.Cells[$row, 2].Value = $months[$i]
    $row += 1
}

Close-ExcelPackage $xlpkg -Show
```

**Comment by rlefever** [comment]
Thank you very much
