### ISSUE TITLE
RunTotal on PivotData

### ISSUE THREAD

**Issue by bwcrowder** [dfinke/ImportExcel#1075]
Looked around for a couple hours. Just wondering if your module currently supports putting a value field setting "show value as" for the pivotdata values. I am trying to view the running total specifically. For now I am just making the change manually as I could not figure out how to change the extra value field setting in an automated fashion.

Hope this makes sense. I tried briefly looking at this, but I need to learn more about EPPlus, because I couldn't figure out how to set this data on my PivotTable other than manually at this point
https://www.epplussoftware.com/docs/5.1/api/OfficeOpenXml.Table.PivotTable.eShowDataAs.html

Thanks for your module makes my life much easier! Hoping I just need to know how to format data correctly using the -pivotdata parameter and maybe you can provide an example.

**Comment by dfinke** [comment]
Please could you post a small sample of the input data and how you are using Export-Excel to create the sheet and also post the xlsx with the pivot table updated how you would like it.

**Comment by bwcrowder** [comment]
Hope this works. New to Github as well.

` function Get-RandomDateBetween{
        <#
        .EXAMPLE
        Get-RandomDateBetween -StartDate (Get-Date) -EndDate (Get-Date).AddDays(15)
        #>
        [Cmdletbinding()]
        param(
            [parameter(Mandatory=$True)][DateTime]$StartDate,
            [parameter(Mandatory=$True)][DateTime]$EndDate
            )

        process{
           return Get-Random -Minimum $StartDate.Ticks -Maximum $EndDate.Ticks | Get-Date -Format d
        }
    }

    
    function Get-RandomTimeBetween{
      <#
        .EXAMPLE
        Get-RandomTimeBetween -StartTime "08:30" -EndTime "16:30"
        #>
         [Cmdletbinding()]
        param(
            [parameter(Mandatory=$True)][string]$StartTime,
            [parameter(Mandatory=$True)][string]$EndTime
            )
        begin{
            $minuteTimeArray = @("00","15","30","45")
        }    
        process{
            $rangeHours = @($StartTime.Split(":")[0],$EndTime.Split(":")[0])
            $hourTime = Get-Random -Minimum $rangeHours[0] -Maximum $rangeHours[1]
            $minuteTime = "00"
            if($hourTime -ne $rangeHours[0] -and $hourTime -ne $rangeHours[1]){
                $minuteTime = Get-Random $minuteTimeArray
                return "${hourTime}:${minuteTime}"
            }
            elseif ($hourTime -eq $rangeHours[0]) { # hour is the same as the start time so we ensure the minute time is higher
                $minuteTime = $minuteTimeArray | ?{ [int]$_ -ge [int]$StartTime.Split(":")[1] } | Get-Random # Pick the next quarter
                #If there is no quarter available (eg 09:50) we jump to the next hour (10:00)
                return (.{If(-not $minuteTime){ "${[int]hourTime+1}:00" }else{ "${hourTime}:${minuteTime}" }})               
             
            }else { # hour is the same as the end time
                #By sorting the array, 00 will be pick if no close hour quarter is found
                $minuteTime = $minuteTimeArray | Sort-Object -Descending | ?{ [int]$_ -le [int]$EndTime.Split(":")[1] } | Get-Random
                return "${hourTime}:${minuteTime}"
            }
        }
    }
  
    
    #create data
    while ($i -lt 40){
    $user = ('UserA', 'UserB', 'UserC' | Get-Random)
    $group = ('GroupA', 'GroupB' | Get-Random)
    [datetime]$randdate = Get-RandomDateBetween -StartDate (Get-Date).AddDays(-15) -EndDate (Get-Date)
    $outtime = $randdate + (Get-RandomTimeBetween -StartTime "08:30" -EndTime "9:30")
    $intime = $randdate + (Get-RandomTimeBetween -StartTime "19:30" -EndTime "23:30")
    $Datetime =    
        $test += @(
        [pscustomobject]@{User=$user;Group=$Group;Date=$randdate;Time=$outtime;Direction='1'}
        )
        $test += @(
        [pscustomobject]@{User=$user;Group=$Group;Date=$randdate;Time=$intime;Direction='-1'}
        )     
    $i++
    }

    $test | Export-Excel -path 'C:\Users\Brad\Documents\test.xlsx' -KillExcel -WorkSheetname "Testpt1" -ClearSheet -IncludePivotChart -PivotChartType ColumnStacked -PivotRows 'Time' -PivotColumns 'Group' -PivotData @{"Direction"="Sum"}`

[ShowValueasRunningTotalTime.xlsx](https://github.com/dfinke/ImportExcel/files/7140651/ShowValueasRunningTotalTime.xlsx)
[test.xlsx](https://github.com/dfinke/ImportExcel/files/7140652/test.xlsx)

**Comment by dfinke** [comment]
Yeah, the EPPlus library I use to create the xlsx does not support that. The new EPPlus lib does, lot's of breaking changes and they require a paid license to use it in a business setting. So, at the moment that cannot be accomplished.

**Comment by bwcrowder** [comment]
Totally understand. Thanks for the fast feedback!
