### ISSUE TITLE
Casting Error in Export-Excel

### ISSUE THREAD

**Issue by fmichaleczek** [dfinke/ImportExcel#108]
I have an reccurent error in Export-Excel.ps1

The french message error is (sorry I don't have a english system available now) :
`Surcharge introuvable pour « TryParse » et le nombre d'arguments « 4 ».`

Problem is a casting problem that can be resolve in ligne 184 : 

Before :
`if( [Double]::TryParse( $cellValue, [System.Globalization.NumberStyles]::Any, [System.Globalization.NumberFormatInfo]::InvariantInfo, [ref]$r ) ) {
`

After :
`if( [Double]::TryParse( [string]$cellValue, [System.Globalization.NumberStyles]::Any, [System.Globalization.NumberFormatInfo]::InvariantInfo, [ref]$r ) ) {`

**Comment by dfinke** [comment]
Thanks, I'll investigate.

**Comment by dfinke** [comment]
@fmichaleczek Please, could you post a small sample of data that causes the problem

**Comment by fmichaleczek** [comment]
```
gps | Export-Clixml -Path $env:temp\a.clixml
$gps = Import-Clixml -Path $env:temp\a.clixml
$gps | Export-Excel -Path $env:temp\a.xlsx
```

**Comment by dfinke** [comment]
Great, could you post the a.clixml file?

**Comment by dfinke** [comment]
never mind. it caused the error on my side
