### ISSUE TITLE
Help Join 2 excel sheets based on a column

### ISSUE THREAD

**Issue by mailsanchu** [dfinke/ImportExcel#1081]
Hi, I am new to PowerShell world, and my need is very simple. But I am struggling to find an answer.ANy help is appreciated
My data model is as follows 

$leftCsv = @"
Column1,Column2,Id
1,2,10
11,22,100
"@ | ConvertFrom-Csv

$rightCsv = @"
Column3,Column4,Id
3,4,10
33,44,100
"@ | ConvertFrom-Csv

and the expected output is 
Id,Column1,Column2,Column3,Column4
10,1,2,3,4
100,11,22,33,44

Thanks 
Sanchu

**Comment by dfinke** [comment]
This question needs to be posted on Stackoverflow.

**Comment by mailsanchu** [comment]
Posted here. Could not find a suitable tag to tag your utility
https://stackoverflow.com/questions/69213930/powershell-join-excel-files-using-importexcel

**Comment by dfinke** [comment]
That is fine, they are pointing to solutions. Once you've joined the data, you should be able to take that result and pipe it to `Export-Excel`
