### ISSUE TITLE
Transpose Powershell Output or even output to rows

### ISSUE THREAD

**Issue by simplest-circuits** [dfinke/ImportExcel#1084]
Hey everybody,
this is not an issue, your tool works like a charm.
For now i need .5% of your tool.

In my example:
`Get-MpComputerStatus | Export-Excel -Path $outputpath -AutoSize -TableName Stats -WorksheetName MpComputerStatus`

The output to the excel sheet is going to columns instead to rows.

Val1, Val2, Val3, Val4

I need the output as the same as the raw `Get-MpComputerStatus ` in the powershell.
Val1
Val2
Val3
Val4

Is there a function of Transpose the data or even write directly to rows instead to columns for each stat?

Thanks to all devs which are working on here --> Great tool and worth to work with it more and more in the future!

**Comment by scriptingstudio** [comment]
Quick solution
```powershell
function transpose {
    process {
        $_.psobject.properties.where{$_.name -notmatch '^cim'}.foreach{
            [pscustomobject]@{property=$_.name; value=$_.value}
        }
   }
}
Get-MpComputerStatus | transpose | Export-Excel -Path $outputpath -AutoSize -TableName Stats -WorksheetName MpComputerStatus -noheader
```

**Comment by simplest-circuits** [comment]
Thank you very much, the transpose works perfectly.
But I have seen, the formating is lost. So for numbers in the powershell output for e.g. 1.234.567 is gone.
The value in the excel after transpose looks like 1234567. The dots between the numbers are lost and i wish the values in the columns are left aligned.
Can i do that as well?

**Comment by scriptingstudio** [comment]
```powershell
$r = Get-MpComputerStatus
# original object in Excel
$r | Export-Excel -Path 111.xlsx -AutoSize -TableName Stats -WorksheetName MpComputerStatus
# transposed object
$r.psobject.properties.where{$_.name -notmatch '^cim'}.foreach{[pscustomobject]@{property=$_.name; value=$_.value}} | 
Export-Excel -Path 222.xlsx -AutoSize -TableName Stats -WorksheetName MpComputerStatus
```
111.xlsx
![image](https://user-images.githubusercontent.com/17237559/133919834-b9d5d726-f251-439e-b6c8-17a2bae8d957.png)

222.xlsx
![image](https://user-images.githubusercontent.com/17237559/133919835-693fb548-8ba0-4402-b27d-f364db135c90.png)

As you can see nothing lost

**Comment by scriptingstudio** [comment]
Yea, looking promising. I even can invent use cases for my current projects.
If I got it right `$Vars` acts as a property filter, `$Id` - object extender, only missing exclude parameter like `Select-Object -ExcludeProperty` does, imo (but it may be overkill).
