### ISSUE TITLE
Set-ExcelColumn error

### ISSUE THREAD

**Issue by Gtoml** [dfinke/ImportExcel#1085]
I am a very , very green beginner with Import-Excel.  So far I love it.  I am trying to use the below Set-ExcelColumn.  Now I have used the Add-Worksheet with the same variable (for the package) with no error.

Set-ExcelColumn -ExcelPackage $VDIUsagePkg -Worksheet "Entitled Users" -Heading "30 Days" -Column 4

I recieve the following Error:

Set-ExcelColumn : Cannot process argument transformation on parameter 'Worksheet'. Cannot convert the "Entitled Users"
value of type "System.String" to type "OfficeOpenXml.ExcelWorksheet".
At C:\Scripts\VDIUSage\EntitledUsers_3.ps1:118 char:55
+ ... Column -ExcelPackage $VDIUsagePkg -Worksheet "Entitled Users" -Headin ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-ExcelColumn], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-ExcelColumn

**Comment by dfinke** [comment]
Need a little more context, could you post some more of the script?

Also, try removing the `-ExcelPackage` and just use the `-Worksheet` parameter.

```powershell
Set-ExcelColumn -Worksheet $VDIUsagePkg."Entitled Users"
```

**Comment by Gtoml** [comment]
Be glad to provide a little context. I did change the syntax as you suggested, and it worked.    I will include the snippet of code where I am combining about four workbooks into one (just to see if there can be any consolidation in my code .  It will create workbook (or package) with four tabs: Entitled Users, 30 Days, 60 Days, 90 Days (this all works).  It will then open the package and add a tab at the beginning called Dashboard (this works).  Then it will begin adding headers and to Entitled Users (also formulas referencing the 30/60/90 days tabs , but taking it baby steps right now).    

###############
##  Combine all data workbooks into one
###############

Write-Host "Creating Report at $VDIUsage."
foreach($workbook in Get-ChildItem $DataPath *.xlsx) {
		$wsName = $workbook.BaseName
		
		Export-Excel -InputObject (Import-Excel -Path $workbook.FullName) -Path $VDIUsage -WorksheetName $wsName -Autosize
}


########################
## Format Final Report
########################
$SheetNames = $(
	'Entitled Users'
	'30 Days'
	'60 Days'
	'90 Days'
	)
	
$VDIUsagePkg = Open-ExcelPackage $VDIUsage 

foreach ($sheetName in $SheetNames) {
	$Null = Add-WorkSheet -ExcelPackage $VDIUsagePkg -WorkSheetname $sheetName -MoveToEnd
}

# Adds Dashboard Worksheet
Add-Worksheet -ExcelPackage $VDIUSagePkg -WorkSheetName "Dashboard" -MoveToStart

#Adds Days columns on Entitled Users Worksheet
#Here is where I removed the ExcelPackage parameter and it worked.
Set-ExcelColumn  -Worksheet $VDIUSagePkg."Entitled Users" -Heading "30 Days" -Column 4

Close-ExcelPackage $VDIUsagePkg

Thanks, 
Tom

**Comment by dfinke** [comment]
Thanks for the context. Good use of the `ImportExcel' module. May need to tweak the parameters on the `Set-ExcelColumn`.
