### ISSUE TITLE
2.2.6 issues under PS v4

### ISSUE THREAD

**Issue by lucdekens** [dfinke/ImportExcel#109]
When I install the **2.2.6** version (current **master** on GitHub) on a PS v4 (on a Win7 32-bit), I only get a very restricted set of functions.

![v2_2_6_psv4](https://cloud.githubusercontent.com/assets/7760649/16442996/6c4d6990-3dd6-11e6-94e0-a122d430f02c.png)

With **2.2.4** I get all the functions (except plot.ps1) on that same station.

![v2_2_4_psv4](https://cloud.githubusercontent.com/assets/7760649/16442916/f11460c6-3dd5-11e6-8dab-78dce6becdbf.png)

Is 2.2.5 still available via GitHub somewhere ?

**Comment by dfinke** [comment]
Thanks Luc. I haven't been tagging specific versions here in GitHub. 

2.2.5 is on the PowerShellGallery.

**Comment by lucdekens** [comment]
The problem was that I trying to update the module on a station with PSv4.
But I can work around it.

**Comment by dfinke** [comment]
OK. Is there anything I can do to improve the install from GitHub?

**Comment by lucdekens** [comment]
Would tagging with the module version be an option ?
Not enough of a github person to know if that would allow me to download a specific version ?

Btw, is 2.2.6 supposed to support PSv4 ?

**Comment by dfinke** [comment]
Tagging would help if you know github. The current and previous releases are all on the PowerShell 
Gallery.

I do not test with PSv4. The community has been a great help there. I added PSv5 classes and it completely broke on v4. One of the folks wrote a workaround and I merged it, it fixed it.

I believe 2.2.6 should work with  v4, and I have not pushed it to the gallery yet.

**Comment by lucdekens** [comment]
As you can see from my screenshot, the 2.2.6 on github does not seem to work with PSv4.
One only gets 4 functions.

**Comment by dfinke** [comment]
Yeah, you pulled that from GitHub? Wondering  if the install from GitHub needs to be tweaked. Might be time to spin up an Azure VM and try it out .

**Comment by lucdekens** [comment]
Yes, I did.
If you need me to test something, give me a shout

**Comment by dfinke** [comment]
Hey @lucdekens, what did you do to work around the issue?

**Comment by lucdekens** [comment]
Downloaded 2.2.5 from the PSGallery on a station that has PSv5.
