### ISSUE TITLE
Using Set-Column / Set-ExcelColumn to set format for a column as text?

### ISSUE THREAD

**Issue by riahc3** [dfinke/ImportExcel#1094]
Hello

From the Get-Help, I see that Set-Column / Set-ExcelColumn is used to format a column.

Id like to use it to set it as text/general/etc but I only see the option for NumberFormat.

How could I do this?

Thanks

**Comment by stahler** [comment]
`Set-Column -ExcelPackage $excel -WorksheetName $ws -Column 4 -NumberFormat 'Text'`

You have lots of options:
![image](https://user-images.githubusercontent.com/1991193/137373194-4186097f-eaa9-4d4b-9b77-5061b14d8f94.png)
