### ISSUE TITLE
Import-Excel command count giving null if single row in the Excel

### ISSUE THREAD

**Issue by lovethakker02** [dfinke/ImportExcel#1095]
Hi. I am reading an excel file in PowerShell and performing some action on data returned. Everything works fine if the excel has multiple rows. If Excel contains only single row, it is giving Count null. That is where my loop fails. Can you please provide any way to get 1 count if there is one row?

My code:

$exceldata = Import-Excel "File with 40 rows.xlsx"
$exceldata.Count
$exceldata2 = Import-Excel "File with single row.xlsx"
$exceldata2.Count
$exceldata2

My Outcome
![powershell](https://user-images.githubusercontent.com/42000241/137293302-21eefb73-dfc6-4aa0-9b28-e002e4bbc5d6.png)

**Comment by DaveyRance** [comment]
Make sure that you specifically say that you want the results as an array. 

`$exceldata2 = @(Import-Excel "File with single row.xlsx")
$exceldata2.Count
$exceldata2`

Notice the @() around the import excel it will make sure that the results are always cast as an array object.

You can check this by doing 
`$ExcelData2 -is [array]` and on your code it will return false and on the code above with the @() it will return true.

Hope this helps

**Comment by lovethakker02** [comment]
Thank you Devey Rance for quick update. This is very helpful. How do you find this trick? Is there any hidden blogs or documentation that I am missing? If so, please share. So, anyone else facing issue can check that first before reporting issue.
