### ISSUE TITLE
module doesn't load properly

### ISSUE THREAD

**Issue by marthektheman** [dfinke/ImportExcel#11]
added the module to the modules folder. 
even when I run as administrator I still get this:

Add-Type -Path "$($PSScriptRoot)\EPPlus.dll" fails. ERROR message:
 Add-Type : Could not load file or assembly 'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\EPPlus.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:1 char:1
+ Add-Type -Path "$($PSScriptRoot)\EPPlus.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 + CategoryInfo : NotSpecified: (:) [Add-Type], FileLoadException
 + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand

**Comment by marthektheman** [comment]
help

**Comment by marthektheman** [comment]
OK the secret is to right click on the zip file and unblock then unzip it.  Then rename the folder from ImportExcel-Master to ImportExcel.  Then copy ImportExcel to the modules folder.  Then add Import-Module ImportExcel to profile.ps1.

**Comment by dfinke** [comment]
Yes that is it. I will publish this module to the PowerShell Gallery and if you are using PowerShell v5 (or the next preview which will be available down-level for Windows 7) you can use `Install-Module` which downloads, unblocks, unzips and copies it to the module directory.
