### ISSUE TITLE
Support channel?

### ISSUE THREAD

**Issue by riahc3** [dfinke/ImportExcel#1100]
Hello

I feel like asking questions in the Issues section of the project isnt really a good idea.

@dfinke Do you recommend somewhere else? Or as a proposal, maybe Discord. Im not sure your point of view.

Thank you for your help and this project.

**Comment by dfinke** [comment]
@riahc3 were you able to connect to the discord channel? Wanted to make sure I posted the correct link.

**Comment by riahc3** [comment]
@dfinke I apoligize for not replying. I have been sick these days and didnt remember about this.

Im actually part of that Discord :) and never noticed there was a module section. I will attempt to post the OTHER question I was gonna ask here, on there.

Thank you very much. Closing this now.
