### ISSUE TITLE
Add-ExcelName with formula parsing

### ISSUE THREAD

**Issue by darg2012** [dfinke/ImportExcel#1104]
Hi,

I have enjoyed your module and was wondering if it's possible to add a formula parameter to the Add-ExcelName function and parsing similar to Set-ExcelRange in order to make it more dynamic, instead of a fixed range evaluated only once the named range is defined.

Let me know if there's better ways to achieve this.

**Comment by dfinke** [comment]
Thanks. Could you say a bit more about what you're trying to do? Post and small would be great too.

**Comment by darg2012** [comment]
For example, 

I want a named range of a constant value:
Name: tax_rate
Value: =1.0725

And be able to use it the named range in formulas like
=275*tax_rate

The more complicated example includes defined a ranged of cells which I vaguely know the limits:
Name: range1
Value:
=OFFSET(INDIRECT(ADDRESS(1,1,1,1,
"Sheet1"
)),0,0,COUNTA(OFFSET(INDIRECT(ADDRESS(1,1,1,1,
"Sheet1"
)),0,0,1300)),COUNTA(OFFSET(INDIRECT(ADDRESS(1,1,1,1,
"Sheet1"
)),0,0,,25)))

and be able to use it in formulas like
=OFFSET(range1,0,0,,1)

I would prefer to define the names from powershell using this module instead of relying on VBA to define the named ranges

**Comment by dfinke** [comment]
@MikeyBronowski wanted to get your thoughts on this when you have time

**Comment by darg2012** [comment]
Looking thru StackOverflow answers and the EPPlus docs (https://epplussoftware.com/docs/5.7/api/OfficeOpenXml.ExcelNamedRangeCollection.html) I found the solution:

You just need to access the Names property inside the workbook and use the respective Add() method:

Set-Location $env:TEMP
$excelFiles = "~/ImportExcelHowTo_v1.xlsm"
Remove-Item $excelFiles -ErrorAction SilentlyContinue

$excelPackage = Get-Process | Export-Excel -Path $excelFiles -PassThru

$wb = $excelPackage.workbook
$sh = $wb.worksheets['sheet1']
$null = $wb.Names.Add('range1', $sh.cells['A1'])
$null = $wb.Names.AddValue('value2', 53)
$null = $wb.Names.AddFormula('formula3', 'MAX(5,3)')

Close-ExcelPackage $excelPackage

**Comment by dfinke** [comment]
@darg2012 Thanks! Would you be up to doing a PR and adding this in the Examples folder? `\Examples\AddExcelName`.

**Comment by darg2012** [comment]
Yes, I saw it but since the sheets I used for the named ranges are querytables to external files I needed a dynamic formula instead of a static range.

@dfinke Of course, let me just finish this semester and I'll learn github's collab tools and do the contributions early next year.

Thanks for your time and help!
