### ISSUE TITLE
Using formula2 instead of formula

### ISSUE THREAD

**Issue by darg2012** [dfinke/ImportExcel#1105]
I was trying to use the complex formula:

=IF(ISNUMBER(MATCH(1,
(INDIRECT(ADDRESS(ROW(),1))=OFFSET(
Sheet1!$A$1:$D$53,0,MATCH($A$1,OFFSET(
Sheet1!$A$1:$D$53,0,0,1),0)-1,,1))*
(INDIRECT(ADDRESS(ROW(),2))=OFFSET(
Sheet1!$A$1:$D$53,0,MATCH($B$1,OFFSET(
Sheet1!$A$1:$D$53,0,0,1),0)-1,,1))*
1,0)),1,0)

But export-excel appears to add the implicit intersection operator @ to the indirect and offset functions and it appears to be because currently export-excel uses .formula instead of .formula2 in line 328.

Is it possible to a switch to add this functionality?

**Comment by dfinke** [comment]
@darg2012 were you looking at a newer version of EPPlus when you see `.Formula2`? I don't see that on the version that currently being used.

**Comment by darg2012** [comment]
My bad, I assumed there was an .formula2 equivalent of .formula similar to how .value2 and .value both exists. For now, I'm just doing a simple search and replace but would like to avoid that step during file creation. Will keep looking for possible solutions that preferably avoid using VBA.
