### ISSUE TITLE
Importing data from Excel sheet into another one on a daily basis 

### ISSUE THREAD

**Issue by moh30ly** [dfinke/ImportExcel#1108]
Hi Doug, 

I am trying to use your PowerShell to automate adding the data from the source files below .csv into another file called main-xlsx.
The Main file have two sheets normally or more as I add more data in it from the source but mainly I would like the script to create a new column with date of previous day and get the data from the HotRecipient.csv files and fit it right into the correct cell (for example a user called john@domain.com will fit into the row where John@domain.com but in yesterday's date. 

I would appreciate if you could direct me on how to do this. 

[HotRecipientReport_24-11-2021.csv](https://github.com/dfinke/ImportExcel/files/7598468/HotRecipientReport_24-11-2021.csv)
[HotRecipientReport_27-11-2021.csv](https://github.com/dfinke/ImportExcel/files/7598469/HotRecipientReport_27-11-2021.csv)

[main.xlsx](https://github.com/dfinke/ImportExcel/files/7598482/main.xlsx)

**Comment by dfinke** [comment]
@moh30ly Yeah, that is a lot of work even for the Excel PowerShell module. The PowerShell module is tuned to handle "tabular" or pre-shaped data.

**Comment by moh30ly** [comment]
Yea I know, I would really appreciate if you could guide me on how to do the import of data from source into target file's cells using your script. that would be a good place to start for me. Thanks

**Comment by dfinke** [comment]
Not sure exactly what you are asking.

This will take that file and create a spreadsheet. 

```powershell
Import-Csv .\HotRecipientReport_24-11-2021.csv | Export-Excel
```

The other parts you are asking about are really creating a customized PS script.

This reads "imports" your existing xlsx

```powershell
Import-Excel .\main.xlsx  | format-table
```

Hope this helps
