### ISSUE TITLE
Export-Excel formula as string

### ISSUE THREAD

**Issue by LewisAlex** [dfinke/ImportExcel#1109]
Hi,
A little like it was asked in the issue #1105, I'm trying too to export an array of object which one property of these objects is a complex formula (in french) :  =SI(ESTERREUR(EQUIV(B$($x); Postes;0)); "n/d";INDIRECT("Stats!C" & EQUIV(B$($x); Postes;0)+1))

I tried to store that formula in a string, and the only way I could successfully export my array was to delete the '=' sign from the string... But doing that, I lost the 'automatic' way I aiming .....

I looked at the line 328 (mentioned in the #1105, but I did not find any clue.....

do you have any idea ?

**Comment by dfinke** [comment]
I don't know off the top of my head, in that issue they thought the answer was using a different property, but `.formula2` does not exist. They are going to get back to me when/if they figure it out.

**Comment by LewisAlex** [comment]
Hi, 
What I wondered wasn't the existence of the _formula2_ thing... Indeed, it does not exist at all :-P

My question was, and it wasn't clear enough - apologies, about the use of Export-Excel to export a complex formula.....?

I mentioned the #1105 just for the complex-formula-part ....

**Comment by dfinke** [comment]
It could be the formula has issues the EPPlus DLL translates wrong. There were ones early on that the PowerShell munges so it gets setup correctly.

We'd need to have the simplest scenario to begin to debug and see if there is a work around. A simpler formula the shows the problem is the place to start.

Is the `$x` a variable in the PS script, and is being replaced? Is that a `row` number?

`=SI(ESTERREUR(EQUIV(B$($x); Postes;0)); "n/d";INDIRECT("Stats!C" & EQUIV(B$($x); Postes;0)+1))`

**Comment by LewisAlex** [comment]
That's what I also thought - for the translation part....
That is why I already tested with a simpler formula, which is actually a portion of the complex one.
=EQUIV(B$($x);Postes;0) (in eng it's a MATCH formula)
I also tried to simplify more the _Postes_, which is a tablename, by indicate its reference **Stats!B:B**

but when I debugged in ISE, I saw that the $x was well translate (at least, during the _Export-Excel_ process)
where did EPPlus takes care of the translation, where do I should look ?...

**Comment by dfinke** [comment]
EPPlus is the C# library I use to create the xlsx. I think this issue came up with another formula early on (a long time ago) and in the PS script munged to formula to work. I don't know where in the EPPlus lib where and which formulas it tries to translate. 
Sorry

**Comment by LewisAlex** [comment]
allright then...
don't be sorry...at all ! 

You did very great with your PS module !!,,

**Comment by LewisAlex** [comment]
Hi,
I know the issue is closed, but I find my way through my problem and I though you may find it of interest.
The problems (there was two - or maybe they were related ...) was around the translation, as you proposed.
As you may have noticed, I was in a french Excel and I couldn't insert french formulas in my worksheet.
I had to translate the whole thing myself to be able to export it.

But, in addition, I was forced to did so with an Excel.Application COM object in my script.....

$objExcel = New-Object -ComObject Excel.Application
... <do stuff - as the Export-Excel of my [object[]]>
$Workbook  = $objExcel.Workbooks.Open($filename)
$Worksheet = $Workbook.Sheets.item($WksheetName)
$Desc = '=IF(ISERROR(MATCH(B2,Stats!B:B,0)),"n/d",INDIRECT("Stats!C"& MATCH(B2,Postes, 0)+1))'
$Worksheet.cells.Range('F1') = "Description"
$Worksheet.cells.Range('F2').Formula = $Desc

$Workbook.Save()
$Workbook.Close()

The only thing it left was the page layout (autosize, autofit, ....)

thnx again for your awesome module !!!

**Comment by dfinke** [comment]
Thanks for the information.
