### ISSUE TITLE
Unable to successfully export two different pivot tables to the same workbook

### ISSUE THREAD

**Issue by hugh-martin** [dfinke/ImportExcel#1113]
I am trying to create a single workbook with two sheets and a corresponding pivot table per sheet.  However, when I do this, I get errors opening the workbook and when I get it open, I can see that the first pivot table is blank, but the two data sheets and the last pivot table are good.

Here’s a shortened version of the code.

```
$UserWorksheetName = "Name Data"
$GroupWorksheetName = "AD Group Data"
    
$UserPivotTableDef = New-PivotTableDefinition -PivotTableName "SS AD Groups per user" -SourceWorksheet $UserWorksheetName -PivotRows "Name" -PivotData @{ Name = 'count' } -NoTotalsInPivot

$GroupPivotTableDef = New-PivotTableDefinition -PivotTableName "Servers per SS AD Group" -SourceWorksheet $GroupWorksheetName -PivotRows "ADGroupName" -PivotData @{ ADGroupName = 'count' } -NoTotalsInPivot
    
    Import-Excel <input data and params> | `
    Export-Excel -Path $OutputExcel -WorksheetName $UserWorksheetName -FreezeTopRow -AutoSize -TableStyle Medium6 `
    -PivotTableDefinition $UserPivotTableDef
    
    Import-Excel <input data and params> | `
    Export-Excel -Path $OutputExcel -WorksheetName $GroupWorksheetName -FreezeTopRow -AutoSize -TableStyle Medium6 `
    -PivotTableDefinition $GroupPivotTableDef
```

Running each Export-Excel block of code against separate output files works as expected.  The problem comes in when running the second Export-Excel block against the workbook created by the first block.

I can get the desired results by defining a single variable with both pivot table definitions, excluding the -PivotTableDefinition param from both Export-Excel commands, and adding a final line that generates both pivot tables and hides the unwanted sheet that is generated by this third call of Export-Excel:

```
$PivotTableDefs = New-PivotTableDefinition -PivotTableName "SS AD Groups per user" -SourceWorksheet $UserWorksheetName -PivotRows "Name" -PivotData @{ Name = 'count' } -NoTotalsInPivot
$PivotTableDefs += New-PivotTableDefinition -PivotTableName "Servers per AD Groups" -SourceWorksheet $GroupWorksheetName -PivotRows "ADGroupName" -PivotData @{ ADGroupName = 'count' } -NoTotalsInPivot
```

```
Export-Excel -Path $OutputExcel -PivotTableDefinition $PivotTableDefs -WorksheetName "Empty sheet" -HideSheet "Empty sheet"
```

Below is the xml output of the errors from Excel:
```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">

<logFileName>error170320_01.xml</logFileName>

<summary>Errors were detected in file '\\hmaapp299\documents\test.xlsx'</summary>


-<removedFeatures>

<removedFeature>Removed Feature: PivotTable report from /xl/pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)</removedFeature>

<removedFeature>Removed Feature: PivotTable report from /xl/pivotTables/pivotTable1.xml part (PivotTable view)</removedFeature>

</removedFeatures>


-<removedRecords>

<removedRecord>Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)</removedRecord>

</removedRecords>

</recoveryLog>
```

Any suggestions are greatly appreciated.

**Comment by dfinke** [comment]
I believe that may be an issue with the EPPlus interface. I will check it out.  So you have a workaround?

If you haven't seen this, it is possibly another way to get the results you want.

https://github.dev/dfinke/ImportExcel/blob/2ca870a88922bc9069faa5f1728017d3963843f6/Examples/PivotTable/MultiplePivotTables.ps1#L1

**Comment by hugh-martin** [comment]
Thanks for the quick response.  Yes, the workaround I have is fine.  I had not seen MultiplePivotTables.ps1, so thanks for that.
