### ISSUE TITLE
Ubuntu 20.04 PWSH 7.2.0 GDIP threw an exception

### ISSUE THREAD

**Issue by siddalluk** [dfinke/ImportExcel#1114]
Hi we have recently been updating our linux machines to use the latest version of Ubuntu 20.04.

Along side that we install powershell 7.2.

When running this on previous versions, we've had no issue with using the ImportExcel module, but since our upgrades we are now getting ...

WARNING: ImportExcel Module Cannot Autosize. Please run the following command to install dependencies:
apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev

We have obviously checked that both of these dependencies are in-place, but the module still reports the error.

On closer examination using the code you use to check AutoFitColumns ... we get the following error relating to gdip.

MethodInvocationException: Exception calling "AutoFitColumns" with "0" argument(s): "**The type initializer for 'Gdip' threw an exception.**"

I've exhausted my googling and I can see that there was a similar issue back in 2018... but I've not found anything that relates to this for Ubuntu 20.04 in recent months.

Could you suggest any way we could fix this please.

Thanks

Martin

**Comment by dfinke** [comment]
Thanks for reporting that. Unfortunately, I don't have an answer for this. I started noticing the auto size issue when I ran the module in a GitHub Action on an Ubuntu image. I switched to a Windows image to work around.

If I find something out, I will post it.

**Comment by siddalluk** [comment]
Thanks dfinke 

Having done a bit more research I've found the possible issue.

https://stackoverflow.com/questions/67091719/system-drawing-common-the-type-initializer-for-gdip-threw-an-exception

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

And then having a quick review of the EPPlus / OpenOffice module that you're PS module uses that project which in turn uses the System.Drawing.Common reference.

 <PackageReference Include="System.Drawing.Common">

I'm going to log a similar bug / feature request with EPPlus and see what happens.

**Comment by dfinke** [comment]
@siddalluk thanks for drilling down on that. I don't think EPPlus will do anything with that, unfortunately. It's worth trying and checking out. The EPPlus developers have moved on to a new version of EPPlus in a new repo. That version requires a paid license though.

Let me know what you find. Thanks again!

**Comment by ChrisPetr0** [comment]
Just an update for others.  In the link that @siddalluk posted, https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action (recommended action section) MS has a workaround posted:  (```"Alternatively, you can enable support for non-Windows platforms by setting the System.Drawing.EnableUnixSupport runtime configuration switch to true in the runtimeconfig.json file:"```)

On our ubuntu 20 container build pipeline, I added these steps to the Dockerfile (install `jq`, add line to `/opt/microsoft/powershell/7/pwsh.runtimeconfig.json`:
```
RUN apt update && apt install --no-install-recommends -y jq
```

```
RUN cat /opt/microsoft/powershell/7/pwsh.runtimeconfig.json | jq '.runtimeOptions.configProperties."System.Drawing.EnableUnixSupport" = true' >> pwsh.runtimeconfig.json_TMP;\
  mv pwsh.runtimeconfig.json_TMP /opt/microsoft/powershell/7/pwsh.runtimeconfig.json
```

Tested and autosize working again with no errors on `ubuntu 20.04` and `pwsh core 7.2`

**Comment by dfinke** [comment]
Thanks @ChrisPetr0 ! What would be need to be added to the `AutosSize` message for other folks using the module on Linux?

**Comment by ChrisPetr0** [comment]
> Thanks @ChrisPetr0 ! What would be need to be added to the `AutosSize` message for other folks using the module on Linux?

@dfinke Sure no worries!

I assume you are talking about 
```
ImportExcel Module Cannot Autosize. Please run the following command to install dependencies:
apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
```

Tough to be succinct with this one.  

How about:
```
ImportExcel Module Cannot Autosize. Please run the following command to install dependencies:
apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev 

If dependencies are met, known issue with Non-Windows OS and Powershell 7.2+ see 
https://github.com/dfinke/ImportExcel/issues/1114 for details and workaround
```

I'm not sure you'd want any more than that, this github issue documents the details and also the Microsoft link is quite long to include (and they can get it here).  I don't know if it's possible to check explicitly for powershell 7.2 and then display the 2nd part of the message which would probably be a bit more elegant.

**Comment by dfinke** [comment]
Thanks again, I'll think about it. Yes, you can check the specific version of PS `($PSVersionTable).psversion`. That message would've helped me when I was using the module in GH Codespaces :-)

**Comment by corbob** [comment]
This also occurs on MacOS, it appears for the same reason. The workaround (burried in here somewhere) also appears to work on MacOS with a few modifications. I would suggest two things:

1. The message should ideally link to a more static page than an issue with a burried workaround (or at least the workaround made more prominent)
2. the file to edit is in `$PSHome` (found this information here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.2) so it's possible to use that instead of a hardcoded path (that is different at least on MacOS). 

I think I can see a way to do it with PowerShell, so perhaps I'll try to throw something together later and report back.

**Comment by corbob** [comment]
Alright, after a little trial and error, a pure PowerShell workaround (note that you must run as root or a user that can modify files in `$PSHOME`):

```powershell
$a = Get-Content $PSHOME/pwsh.runtimeconfig.json | convertfrom-json -AsHashtable
$a.runtimeOptions.configProperties['System.Drawing.EnableUnixSupport'] = $true
$a | ConvertTo-Json -Depth 5 | out-file $PSHOME/pwsh.runtimeconfig.json
```

**Comment by robertstrom** [comment]
@ChrisPetr0 and / or @corbob 

I am trying to use Export-Excel to `-AutoFilter -AutoSize -FreezeTopRow -BoldTopRow` and I am getting the following messages:

```
WARNING: ImportExcel Module Cannot Autosize. Please run the following command to install dependencies:
apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
WARNING: Auto-fitting columns is not available with this OS configuration.
```

I have installed the dependencies and I have modified the **$PSHOME/pwsh.runtimeconfig.json** file as documented in this thread  but it is not working.

```
└─PS> Get-Content $PSHOME/pwsh.runtimeconfig.json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.10"
      }
    ],
    "rollForwardOnNoCandidateFx": 1,
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false,
      "System.Runtime.TieredCompilation": true,
      "System.Runtime.TieredCompilation.QuickJit": true,
      "System.Runtime.TieredCompilation.QuickJitForLoops": true,
      "System.Drawing.EnableUnixSupport": true
    }
  }
}
```

It's almost 4 years later now so I am wondering if this is still a solution that is supposed to work or if it no longer works (I saw another thread that seems to suggest that this fix no longer works).

PowerShell is running on Kali Linux 

```
└─PS> cat /etc/os-release                                                    
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.4"
VERSION="2024.4"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

PowerShell version is:
```
└─PS> $psVersionTable                                                                                                 
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Kali GNU/Linux Rolling
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Hopefully you will see a notification about this and will be able to reply.

Thanks in advance!

**Comment by vikingtiger** [comment]
@robertstrom: It is no longer a viable workaround. It was only valid for .NET 6.0.
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/system-drawing

**Comment by pr0vieh** [comment]
ok is this now broken on Linux or are there other solutions?

**Comment by dfinke** [comment]
🤷🏻‍♂️
