### ISSUE TITLE
Retrieving Table Data based on Header?

### ISSUE THREAD

**Issue by DarylGraves** [dfinke/ImportExcel#1115]
Sorry this isn't an issue but a question.

I was wondering if there's an easy way to import an Excel Table which does not start on cell A1? Maybe on a different row, cell or both? I can't find anything in the examples/documentation.

In my situation I have a lot of variables in my spreadsheet which feed into the table. I've put these down the side as a sort of side pain and so my Table starts at C1. So far, the only solution I've found is the below:

```
$Excel = Open-ExcelPackage file.xlsmx
$Start = $Excel.Sheet1.Tables.Address.Start
$End = $Excel.Sheet1.Tables.Address.End
```

This returns the coordinates and then I can use 

> $Excel.Sheet1.Cells[$Start.Row, $Start.Column]

 and

>  .Offset() 

to get around but I'd prefer to be able to reference the table headers to retrieve data, instead of coordinates. 

Also, if you're reading this Doug, thank you so much for making such an incredible module!

Thanks!

**Comment by DarylGraves** [comment]
I'm an idiot - Just looked at the code for Import-Excel and I can see there's a Startrow and Start Column flag. Thanks!

**Comment by dfinke** [comment]
Glad you found it.
