### ISSUE TITLE
Export Excel - a String with a Colon causes the cell to be created with a hyperlink

### ISSUE THREAD

**Issue by robhudsonnc** [dfinke/ImportExcel#1116]
I was writing a script to dump the O365 licenses for our tenant and whenever I create a string with a colon it causes the cell created to have a hyperlink.  See sample code below:
# Begin Code
Function TstExcel {

    $ms365 = [PSCustomObject]@{
        DisplayName = "Test Subject"
        UserPrincipalName = "test@contoso.com"
        licenses = "cognc:MCOMEETADV_GOV,cognc:M365_G3_GOV,cognc:ENTERPRISEPACK_GOV,cognc:RIGHTSMANAGEMENT_ADHOC"
        }
         $ms365
}

# Filename Creation For Source and Datestamp
$FileDate= Get-Date -format filedate 
$FHome = "C:\Users\test\Documents\O365\"
# Clean up old files from the Current Day
$Filenames = @("$FHome$Filedate-TestExcel.xlsx")
 foreach($filename in $filenames) { 
     if (Test-Path   $filename) { remove-Item $filename }}
TstExcel | Export-excel -Path "$RobHome$Filedate-TestExcel.xlsx" -AutoSize -FreezeTopRow -AutoFilter -TableStyle Medium6
# End Code

**Comment by stahler** [comment]
Debugging shows it is passing the test
`[System.Uri]::IsWellFormedUriString($v , [System.UriKind]::Absolute)`
in the Export-Excel call and explicitly setting the Font color to Blue and Underlining.

@dfinke Should that be a Relative check?

**Comment by dfinke** [comment]
@stahler thanks for stepping through that, good question, let me experiment

**Comment by dfinke** [comment]
Need to dig deeper, changeing to `Relative` breaks tests. Yes, it handles the `license` string above as *not* being a hyperlink

**Comment by robhudsonnc** [comment]
Doug,
  I changed my test code to be simpler. 
# Test Code
#   licenses = "cognc:MCOMEETADV_GOV,cognc:M365_G3_GOV,cognc:ENTERPRISEPACK_GOV,cognc:RIGHTSMANAGEMENT_ADHOC"
    $data =  ConvertFrom-Csv @"
    ID,UPN,Department,License
    12001,rhudson,IT,cognc:MCOMEETADV
    12004,rhudson@contoso.com,Finance,cognc:MCOMEETADV
    12003,rhudson,HR,cognc:MCOMEETADV
    12002,rhudson,CAO,cognc-MCOMEETADV
    12006,rhudson,CAO,cognc-MCOMEETADV
    12005,rhudson,CAO,cognc-MCOMEETADV
"@
    $xlfile = "C:\Users\rob\Google Drive\Work\O365\TestExcelDept.xlsx"
  
    $data | Export-Excel -Path $xlFile -autofilter -autosize

Very similar to one of your examples.  I tried mixing the value up to see if the value for upn mattered if it had an @ site or not.  It doesn't.  One anomaly I found is if I do not delete the excel file and I reorder the lines (swap one of the lines with a colon with one that doesn't have the colon) it will cause the cells to have the hyperlink in them. 

On another note I have noticed if I don't delete an excel file and use the -tablestyle medium6 option twice it will give an error in excel 
![image](https://user-images.githubusercontent.com/10088295/147167186-488765fd-375c-4bfd-9e3e-d9a2d52f10bc.png)

**Comment by robhudsonnc** [comment]
I didn't mean to close this issue.  I'm reopening it.

**Comment by dfinke** [comment]
I experimented a bit with adding `NoHyperlinkConversion`

Wanted to get your thoughts. Using `Relative` in the `wellformed` check, two things, it formatted the email as a link, but as file, it broke existing tests in other parts of the code.

So using `NoHyperlinkConversion` may be a good compromise.

```powershell
$ms365 | Export-Excel $xlfilename -Show -AutoSize -NoHyperlinkConversion 'licenses'
```

**Comment by stahler** [comment]
I think that is a good compromise.  Also familiar to those using -NoNumberConversion.

**Comment by sjborque** [comment]
The source code could be modified to:
Modules\ImportExcel\7.4.1\Public\Import-Excel.ps1
find:
elseif ( [System.Uri]::IsWellFormedUriString($v , [System.UriKind]::Absolute) )  {
replace:
elseif (( [System.Uri]::IsWellFormedUriString($v , [System.UriKind]::Absolute) ) -and (($v -match "\\.") -or ($v -match "\/."))) {

**Comment by robhudsonnc** [comment]
So is -NoHyperLinkConversion a valid option?

**Comment by dfinke** [comment]
Need to make time to add it, include unit tests, and publish

**Comment by robhudsonnc** [comment]
Still interested in a solution.

**Comment by dfinke** [comment]
Yeah, I'm leaning towards not adding this as an option. I believe it is better handled by folks creating the xlsx. You can add PS code to process that, as a data/formatting scrubbing process.

**Comment by vpaesa** [comment]
There are a lot of non-URL strings that IsWellFormedUriString is tagging as well formed URLs.
Example, this snippet returns True:
```
$v = 'aa:a'
[System.Uri]::IsWellFormedUriString($v , [System.UriKind]::Absolute)

```
May I ask to reconsider adding the "-NoHyperLinkConversion" opption?

If not, may you please suggest some PS code to scrub these fake URLs out of Excel files?

**Comment by dfinke** [comment]
@vpaesa, please could you open a new issue for this about adding `-NoHyperLinkConversion`

**Comment by vpaesa** [comment]
> @vpaesa, please could you open a new issue for this about adding `-NoHyperLinkConversion`

[I gladly opened 1316 :-) ](https://github.com/dfinke/ImportExcel/issues/1316)
Thanks!
