### ISSUE TITLE
Advanced Pivot Table question

### ISSUE THREAD

**Issue by jaswicki** [dfinke/ImportExcel#1117]
Having some Pivot Table issues. I am trying to set the following in a pivot table:
     Design...Report Layout...Show in Tabular Format
     Pivot Table Options..Display...(Turn off)Classic PivotTableLayout
     Don't show subtotals
     -PivotTableStyle none still applies the Medium Blue Style

I also can't move more than one sheet. I am creating 3 pivot tables and want them to be the first 3 sheets in the workbook

**Comment by jaswicki** [comment]
Figured out the moving sheets issue. I was trying to move the sheets using 

Export-Excel -ExcelPackage $xlp -WorksheetName "C" -MoveToStart
Export-Excel -ExcelPackage $xlp -WorksheetName "B" -MoveToStart
Export-Excel -ExcelPackage $xlp -WorksheetName "A" -MoveToStart

which would throw an error for any additional sheet moves. However

Export-Excel -path $xlfile -WorksheetName "C" -MoveToStart
Export-Excel -path $xlfile -WorksheetName "B" -MoveToStart
Export-Excel -path $xlfile -WorksheetName "A" -MoveToStart

Works fine

**Comment by scriptingstudio** [comment]
@jaswicki Your first code block looks at least incomplete because `-ExcelPackage` implies using `-passthru` parameter to keep an Excel object state in a variable that you probably missed.

**Comment by jaswicki** [comment]
Ahh thank you. I did miss that. Makes sense

**Comment by jaswicki** [comment]
I had a lot more question than the one that was answered. Can this be ledt
open?

**Comment by dfinke** [comment]
@jaswicki if you have additional issues or question, feel free to open another one.
