### ISSUE TITLE
Import-Excel fails with 'null array' error: no worksheets after Load

### ISSUE THREAD

**Issue by sba923** [dfinke/ImportExcel#1119]
I'm facing the following symptom that's actually common to a number of other issues (that's quite expected given the "generic trap" `try`/`catch` construct in `Import-Excel.ps1`):

````
PS❯  import-excel .\test.xlsm
Exception: ...\Modules\ImportExcel\7.4.1\Public\Import-Excel.ps1:227
Line |
 227 |  …     catch { throw "Failed importing the Excel workbook '$Path' with w …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed importing the Excel workbook
     | '...\test.xlsm' with worksheet '': Cannot
     | index into a null array.
````

I've started to investigate this and found out that after loading the file, the `$ExcelPackage` object has no `Worksheets` property:

````
PS❯  $ExcelPackage = New-Object -TypeName OfficeOpenXml.ExcelPackage
PS❯  $stream = New-Object -TypeName System.IO.FileStream -ArgumentList (resolve-path 'test.xlsm').Path, 'Open', 'Read', 'ReadWrite'
PS❯  $ExcelPackage.Load($stream)
PS❯  $excelpackage.Workbook.Worksheets.Count
PropertyNotFoundException: The property 'Worksheets' cannot be found on this object. Verify that the property exists.
````

Here's the file: [test.zip](https://github.com/dfinke/ImportExcel/files/7796245/test.zip)

Any clue as to how to solve this?

**Comment by scriptingstudio** [comment]
I removed all sheets and created empty one. Did not help. Exported cleaned doc to XLSX  - did not help.
Then I removed all VBA modules from the origin doc kept all sheets - it worked, the error gone.
I think a specific VBA script doing something or interfering. Also I could not remove your custom ribbon tab to see changes. 
So, play with VBA scripts removing all and adding one by one.

**Comment by sba923** [comment]
> I removed all sheets and created empty one. Did not help. Exported cleaned doc to XLSX - did not help. Then I removed all VBA modules from the origin doc kept all sheets - it worked, the error gone. I think a specific VBA script doing something or interfering. Also I could not remove your custom ribbon tab to see changes. So, play with VBA scripts removing all and adding one by one.

I'm trying to programmatically create a copy of the `.xlsm` file without the problematic part(s) by manipulating it as a zip archive, but I can't get that to work. Any clue / pointers?

**Comment by dfinke** [comment]
No pointers. The xlsm is a zip, the contents are xml. You need to know a lot about the xml structure to get it right.

**Comment by sba923** [comment]
> No pointers. 

😭

> The xlsm is a zip, the contents are xml. You need to know a lot about the xml structure to get it right.

Was my starting point. Will continue experimenting, and maybe check out the format specs.

**Comment by sba923** [comment]
No clue as to what could cause that failure? Shouldn't importing data just ignore the code parts?

**Comment by sba923** [comment]
@dfinke FYI, this is still an important use case for me, and I'd like to find a solution.

I know, I need to spend some time investigating / experimenting with hand-crafted test files....

**Comment by dfinke** [comment]
Sorry @sba923, I don't have a solution.

**Comment by sba923** [comment]
@dfinke I have successfully implemented a first version of a `Import-ExcelMacroEnabledWorkbook.ps1` proxy script, that relies on a `Save-ExcelWorkbookWithoutMacros.ps1` that saves a `.xlsm` file to a `.xlsx` file that is accepted by `Import-Excel`.

I'll probably publish this to https://gist.github.com/sba923 once ready for prime time.

**Comment by dfinke** [comment]
Sounds great, let me know.
