### ISSUE TITLE
How to set green background color on pricing

### ISSUE THREAD

**Issue by ttt-dlloyd** [dfinke/ImportExcel#1122]
Greetings,

I attempted to set a fill color of green on a summary price sheet that I created using the ImportExcel module to take care of the generated data. When I do, the method I have tried says it needs a pattern first to be set. Can you recommend a way to do this?

https://i.imgur.com/x0jjKNg.png

**Comment by dfinke** [comment]
Please post a sample of the code and data of what you have tried.

**Comment by ttt-dlloyd** [comment]
I removed the code because it didn't work. I was looking at the straight source code for your module to get the syntax. Is there documentation for background coloring by chance that isn't conditional formatting? These cells will always be that color. Unless maybe conditional formatting would be a workaround for this and just set the condition to always be true.

**Comment by dfinke** [comment]
I don't know of any "documentation for background coloring by chance that isn't also conditional formatting documentation"

**Comment by ttt-dlloyd** [comment]
I'll attempt to make this work using conditional formatting. There isn't
any documentation. I was looking at the module source code as I said.

Take care!

**Comment by dfinke** [comment]
yeah, the coloring and conditional aspects are just calling the underlying mechanism that sets things up in the xlsx. You may be able to find out more about that by Googling "EPPlus background coloring conditional formatting". If you get hits, make sure you read the docs for the version prior to EPPlus 5.0
