### ISSUE TITLE
"Could not get worksheet $WorksheetName" error creates the sheet but does not populate

### ISSUE THREAD

**Issue by mprentice22153** [dfinke/ImportExcel#1123]
Doug,
I know this particular has been raised in some other issues but I'm hoping we can take some time to dig into this.  Here's the situation. 
 We use some template spreadsheets (XLSM with Macros) for reporting. I use ImportExcel to update some sheets and add more sheets to provide the backup data. The macro functionality does not come into play until one of our staff members chooses to output a PDF report for a customer. The names below have been changed to hopefully clearly identify what happens.

TemplateFileA.XLSM
Worksheets: sheet1, sheet2, sheet3, sheet4, sheet5
Sheets 1-3 are password locked, with sheets 1-2 using VLookup to reference data on sheets 4-5
ImportExcel is used to replace the content in sheets 4-5, then add sheets6-15.
Everything is successful. Sheet1 shows the customer name, etc. Sheet 2 shows the summary of results based on sheets 4-5.

TemplateFileA is modified by unlocking sheet1, changing a version field and data field (non-impacting to any functionality), then locked again with a password. This is now TemplateFileB.

TemplateFileB.XLSM
Worksheets: sheet1, sheet2, sheet3, sheet4, sheet5
Sheets 1-3 are password locked, with sheets 1-2 using VLookup to reference data on sheets 4-5
ImportExcel properly replaces the content in sheets 4-5
When attempting to add sheets 6-15, the "Could not get worksheet $WorksheetName" error occurs, however, the new worksheet is added to the spreadsheet file but it contains no content.  (Each attempt to update or add a sheet is a try-catch.)

The only change that has occurred is the minor adjustment to the spreadsheet.  This makes it sound like a corruption in the spreadsheet occurs but we have tried with various templates, various changes, etc.

I'd appreciate the opportunity to work with you to try to troubleshoot this issue and see if we can identify the issue.

Thank you,
Matthew Prentice

**Comment by dfinke** [comment]
Hi Matthe @mprentice22153, I'm don't think I can help out on this, there is a lot going on here. I would try to scale back what you are doing and add each piece incrementally to see what causes the issue. If you can create a small reproducible script that demonstrates the issue, please post it.

Hope this helps
