### ISSUE TITLE
Pivot Table Numeric Row Groups Fail with Blank Cell in Data Row Field

### ISSUE THREAD

**Issue by dlwearl** [dfinke/ImportExcel#1125]
Doug,

I have a dataset that consists of three columns with headers, not in an Excel table, and all with whole numbers as follows:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/David/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/David/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Item1 | Item2 | Item3
-- | -- | --
1 | 1 | 100
2 | 2 | 200
3 | 3 | 300
4 |   | 400

</body>

</html>

The data reside on Sheet1. The only difference between Item1 and Item2 is the null value in the final row for Item2.

**The code I use to generate pivot tables is as follows:**

$exceltest = Export-Excel -Path $wbsource -WorksheetName "Sheet1" -PassThru

$wksht = Add-Worksheet $exceltest -WorksheetName "Test" -MoveToEnd

$pt = Add-PivotTable -SourceWorksheet $exceltest.Sheet1 -PivotTableName "PT1" -Address $wksht.Cells["A3"] -PivotRows Item1 -PivotData @{"Item3" = 'count'} `
-GroupNumericRow Item1 -GroupNumericMin 1 -GroupNumericMax 4 -GroupNumericInterval 2 -PassThru

$pt = Add-PivotTable -SourceWorksheet $exceltest.Sheet1 -PivotTableName "PT2" -Address $wksht.Cells["D3"] -PivotRows Item2 -PivotData @{"Item3" = 'count'} `
-GroupNumericRow Item2 -GroupNumericMin 1 -GroupNumericMax 4 -GroupNumericInterval 2 -PassThru

Close-ExcelPackage $exceltest -Show

Results are in the screen shot below, along with the desired pivot table. When the pivotrows source is Item1, the grouping works as expected; when it is Item2, the grouping syntax fails silently. The desired pivot table is in the screenshot.

![pivot table grouping](https://user-images.githubusercontent.com/97625853/149198282-c9f69ed8-9360-4fce-a8a0-c812817fdf0e.jpg)

Thanks,
David

**Comment by dfinke** [comment]
@dlwearl The far right pic, you did that manually in Excel? Yeah, not sure, could be the Export-Excel, the underlying EPPlus, or a missing setting,

**Comment by dlwearl** [comment]
@dfinke Yes, the Desired PT2 is created manually.

**Comment by dfinke** [comment]
At the moment, looks like a bug in how the underlying library I use to create the xlsx has a bug. I don't have control over that library.

https://github.com/dfinke/ImportExcel/blob/6d97018de672f2f4f4b3b1c47dbf2262f2d35ea2/ExportedCommands/Add-PivotTable.ps1#L137

**Comment by dfinke** [comment]
@dlwearl I used `Export-Excel` to create a worksheet with that dataset, did not use the module to create the pivot table. I created the pivot table manually, tried to group it, and get this error. I suspect the `Export-Excel` function cannot detect that error when the xlsx is created.

![image](https://user-images.githubusercontent.com/67258/149666171-6f9e8493-60f0-416a-a491-970afe53cde4.png)
