### ISSUE TITLE
Unable to set number format as type 'Accounting'; however, the type of 'Currency' does work

### ISSUE THREAD

**Issue by ttt-dlloyd** [dfinke/ImportExcel#1126]
Set-Format -WorkSheet $Sheet -Address "H$i" -NumberFormat 'Accounting'
    $i++
    Set-Format -WorkSheet $Sheet -Range "H$i" -FontSize 16
    Set-Format -WorkSheet $Sheet -Address "H$i" -NumberFormat 'Accounting'
    $i--
    Set-Format -WorkSheet $Sheet -Range "A10:I10" -FontSize 30
    Set-Format -WorkSheet $Sheet -Address "G16:G40" -NumberFormat 'Currency'
    Set-Format -WorkSheet $Sheet -Address "H16:H40" -NumberFormat 'Currency'

**Comment by stahler** [comment]
Looking at the NumberFormat choices, I do not see 'Accounting'

![image](https://user-images.githubusercontent.com/1991193/149602891-da67284e-cf72-4269-ab28-375ca99849af.png)

**Comment by ttt-dlloyd** [comment]
Accounting is a type built into Excel. It formats the numbers with the
dollar sign left justified. It seems that the module doesn't support all of
the built in Excel format types.

**Comment by dfinke** [comment]
That type is not part of the dll that creates the xlsx, so it won't be available. You can pass `"$#,##0.#0"` or whatever pattern fits your needs for a workaround.
