### ISSUE TITLE
Cannot save excelpackage

### ISSUE THREAD

**Issue by rodmarten** [dfinke/ImportExcel#1128]
Open-ExcelPackage works and data seems fine.
Close-ExcelPackage fails

PS C:\test> Close-ExcelPackage $result
Exception calling "Save" with "0" argument(s): "Error saving file C:\test\testInventory.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\importexcel\7.4.1\Public\Close-ExcelPackage.ps1:29 char:20
+             else { $ExcelPackage.Save() }
+                    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

This is data specific.  Any way to get OfficeOpenXml.ExcelPackage.Save() to give more error info?

**Comment by dfinke** [comment]
No, there is nothing that can give those details. At this point, you'll need to insert the data chunks at a time to see where the issue is.

**Comment by rodmarten** [comment]
Thanks.  It looks like the problem is in the underlying library.  I think
it has a max record issue.  Will test as I have time.

**Comment by dfinke** [comment]
Please let me know what you find out.
