### ISSUE TITLE
-SeriesHeader   (ChartDefinition)

### ISSUE THREAD

**Issue by mjd106** [dfinke/ImportExcel#1131]
Firstly, thank you for producing and sharing such an amazing module!

Not sure if this is an issue, but I find that if I create a table and a chart the _-SeriesHeaders_ in the chart don't work if **_all_** the columns of the table are included in the chart.
 E.G:

`    
 $chartDefinition = New-ExcelChart -XRange name -YRange percent_used, percent_free -Title Datastores -Row $nextStartingRow -Column 6 -ChartType ColumnStacked1003D -Width 900 -SeriesHeader percent_used, percent_free`

`
 $excelpackage = $SummaryTableDatastores | Export-Excel -ExcelPackage $excelpackage -WorksheetName "Summary"  -StartRow $nextStartingRow -AutoSize -AutoNameRange -TableName datastores -ExcelChartDefinition $chartDefinition -PassThru 
`

To workaround, I can reference some cells '_directly_' for the series headers:
`-SeriesHeader "=Summary!`$B`$$nextStartingRow", "=Summary!`$C`$$nextStartingRow", "=Summary!`$D`$$nextStartingRow"`

Or, if I add an additional column to the table (but not include it in the chart) the _seriesHeaders_ seem to work (i.e. the above example works if the table has more columns than just **_name_**, **_percent_Used_** and **_percent_free_**).

**Comment by dfinke** [comment]
Thanks for reporting, there has been odd things with the `-SeriesHeaders` this may give some clues. When I can, I will take a look.

**Comment by mjd106** [comment]
Hi, 

Thanks for your reply.

Here's an example which shows the effect for me (Windows 10 / Excel 365)

The following example charts **Age** against **Name** - but the _seriesHeader_ doesn't work (it just shows "Series1")

```
$ArrayData = [System.Collections.ArrayList] @(           


[PSCustomObject]@{'Name' = 'rod'; 'age' = 25}
[PSCustomObject]@{'Name' = 'Jane'; 'age' = 23}
[PSCustomObject]@{'Name' = 'freddie'; 'age' = 24}

) 

$chartDefinition = New-ExcelChart -XRange name -YRange age  -Title Datastores  -ChartType ColumnStacked3D -Width 900 -SeriesHeader Age

$excelpackage = $ArrayData | Export-Excel  -WorksheetName "Summary" -AutoSize -AutoNameRange -TableName datastores -ExcelChartDefinition $chartDefinition -PassThru

Close-ExcelPackage -ExcelPackage $excelpackage -SaveAs d:\seriesHeadersTest.xlsx -show

```



By simply adding another column to the data  (but still just charting **_Name/Age_**)   ..........
```
$ArrayData = [System.Collections.ArrayList] @(           


[PSCustomObject]@{'Name' = 'rod'; 'age' = 25; 'height' = 160}
[PSCustomObject]@{'Name' = 'Jane'; 'age' = 23; 'height' = 170}
[PSCustomObject]@{'Name' = 'freddie'; 'age' = 24; 'height' = 165}

) 

$chartDefinition = New-ExcelChart -XRange name -YRange age  -Title Datastores  -ChartType ColumnStacked3D -Width 900 -SeriesHeader Age

$excelpackage = $ArrayData | Export-Excel  -WorksheetName "Summary" -AutoSize -AutoNameRange -TableName datastores -ExcelChartDefinition $chartDefinition -PassThru

Close-ExcelPackage -ExcelPackage $excelpackage -SaveAs d:\seriesHeadersTest.xlsx -show
```

The seriesHeader works (it shows "Age").

Now, adding that "_new_" column to the chart as well ......


```
$ArrayData` = [System.Collections.ArrayList] @(           


[PSCustomObject]@{'Name' = 'rod'; 'age' = 25; 'height' = 160}
[PSCustomObject]@{'Name' = 'Jane'; 'age' = 23; 'height' = 170}
[PSCustomObject]@{'Name' = 'freddie'; 'age' = 24; 'height' = 165}

) 

$chartDefinition = New-ExcelChart -XRange name -YRange age, height  -Title Datastores  -ChartType ColumnStacked3D -Width 900 -SeriesHeader Age, Height

$excelpackage = $ArrayData | Export-Excel  -WorksheetName "Summary" -AutoSize -AutoNameRange -TableName datastores -ExcelChartDefinition $chartDefinition -PassThru

Close-ExcelPackage -ExcelPackage $excelpackage -SaveAs d:\seriesHeadersTest.xlsx -show
```

stops the _-seriesHeader_ again - untill I add another additional column - and so on.

It doesn't seem to matter where the "additional' uncharted column is in the table/data.
