### ISSUE TITLE
Extended HeaderName functionality?

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#1132]
I'm trying to run this:
`$t = import-excel  'C:\temp\Scan Analysis - Vulnerability - dummy.xlsx' -Startrow 4 -StartColumn 2 -WorksheetName "Vulnerability Report" -HeaderName ([Ordered]@{IP = 'IP Address';Host = 'Host Name';LS_User='LS_User'})`

Using the functionality from [this PR](https://github.com/dfinke/ImportExcel/pull/579/commits).  
Was this PR ever merged? (more likely I am doing wrong!)

The command above results in this structure:
```
❯ $t[2]|gm

   TypeName: System.Management.Automation.PSCustomObject

Name                                             MemberType   Definition
----                                             ----------   ----------
Equals                                           Method       bool Equals(System.Object obj)
GetHashCode                                      Method       int GetHashCode()
GetType                                          Method       type GetType()
ToString                                         Method       string ToString()
System.Collections.Specialized.OrderedDictionary NoteProperty string System.Collections.Specialized.OrderedDictionary=
```

**Comment by uSlackr** [comment]
Let me validate my installed version, first

**Comment by uSlackr** [comment]
OK - 7.4.1 confirmed.  Same results:
```
PS C:\temp> $t[2]|gm


   TypeName: System.Management.Automation.PSCustomObject

Name                                             MemberType   Definition
----                                             ----------   ----------
Equals                                           Method       bool Equals(System.Object obj)
GetHashCode                                      Method       int GetHashCode()
GetType                                          Method       type GetType()
ToString                                         Method       string ToString()
System.Collections.Specialized.OrderedDictionary NoteProperty string System.Collections.Specialized.OrderedDictionar...


PS C:\temp> get-installedmodule -name importexcel

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
7.4.1      ImportExcel                         PSGallery            PowerShell module to import/export Excel spreads...
```

**Comment by scriptingstudio** [comment]
It is all correct and incorrect at the same time.
The type of `-HeaderName` parameter is string `array`. You are passing a hashtable instead of an array. 
If you cast hashtable to array you will get an array.
```powershell
[string[]]([Ordered]@{IP = 'IP Address';Host = 'Host Name';LS_User='LS_User'})
System.Collections.Specialized.OrderedDictionary
```
As you can see from your output `System.Collections.Specialized.OrderedDictionary` is the column name of your header. That is correct.
Your argument of `-HeaderName` parameter is not correct by type. See `Import-Excel` function help.

**Comment by uSlackr** [comment]
Thanks, I'm not sure I understand what I need to do, but I'll try something today.  I did look at [this example](https://github.com/ili101/ImportExcel/blob/Import-ExcelExtendedHeaderName/Examples/Import-ExcelWithHeaderName.ps1) in the original pull request.  It was the only example I found .

FWIW, I'm trying to accomplish two things - convert a couple column names and add a couple new columns to the data.

**Comment by scriptingstudio** [comment]
Omit `-HeaderName` parameter. `Import-Excel` does not support a selective parameter conversion. Put conversion after import using `Select-Object`.
```powershell
$t = import-excel 'C:\temp\Scan Analysis - Vulnerability - dummy.xlsx' -Startrow 4 -StartColumn 2 -WorksheetName "Vulnerability Report" | 
Select-Object @{n = 'IP Address'; e = {$_.IP}}, @{n = 'Host Name'; e = @{$_.host}}, 'LS_User' ,'custom-column1','custom-column2'
```
Correct column definition expressions as you need.

**Comment by scriptingstudio** [comment]
@dfinke, currently `-HeaderName` does not support name conversion and adding new columns at the same time. My suggestion is to make little change.
Test code:
```powershell
$Columns = 'IP','Host','col3','col4'
$HeaderName = 'Ip address','host name','col3','col4' ,'col5','col6'
#region code from Import-Excel function
$i = 0
foreach ($H in $HeaderName) {
	$colname,$colval = if ($Columns[$i]) {$Columns[$i],$H} else {$H,''} # addition
	$H | Select-Object @{N = 'Column'; E = { $colname } }, @{N = 'Value'; E = { $colval } }
	$i++
}
#endregion
Column Value
------ -----
IP     Ip address
Host   host name
col3   col3
col4   col4
col5
col6
```

**Comment by scriptingstudio** [comment]
@dfinke Small improvement.
Because original expression `$H | Select-Object @{N = 'Column'; E = { $Columns[$i] } }, @{N = 'Value'; E = { $H } }` does not use pipe object `$_`, hence we can eliminate overhead of piping and cmdlet invocation altogether.
```powershell
[pscustomobject]@{Column = $Columns[$i]; Value = $H}
```
It is 3-5 times faster and is neat.

And final code will be
```powershell
$i = 0
foreach ($H in $HeaderName) {
    $colname,$colval = if ($Columns[$i]) {$Columns[$i],$H} else {$H,''}
    [pscustomobject]@{Column = $colname; Value = $colval}
    $i++
}
```

**Comment by scriptingstudio** [comment]
@dfinke, My bad. Sorry.
I tested just part of the code, not the solution. `-HeaderName` works as expected.
The only optimization I would suggest is to replace piping and `select-object`
```powershell
[pscustomobject]@{Column = $Columns[$i]; Value = $H}
```

@uSlackr
If your excel has only 3 columns it is possible to accomplish your task using `-HeaderName`
```powershell
$t = import-excel 'C:\temp\Scan Analysis - Vulnerability - dummy.xlsx' -Startrow 4 -StartColumn 2 -WorksheetName "Vulnerability Report" -HeaderName 'IP Address','Host Name','LS_User',customcol1,customcol2
```

**Comment by uSlackr** [comment]
> 
> @uSlackr If your excel has only 3 columns it is possible to accomplish your task using `-HeaderName`
 Thanks.  I used you select-object example.  I learned something I need to do regularly.  Worked great.

THank you
