### ISSUE TITLE
Export-Excel AutoSize not working correctly for some columns

### ISSUE THREAD

**Issue by Philenst** [dfinke/ImportExcel#1134]
I unfortunately cannot provide the full code however I'll provide as much as I can. 

I am feeding the output of a Invoke-Sqlcmd query to Export-Excel as such:
` "Invoke-sqlcmd query" | Export-Excel -Path "$DesktopPath\Result.xlsx" -Append -AutoSize -BoldTopRow`

I have 3 fields that I export, "Study Description", "Study Date" and "Report Time".

The study description field scales correctly, however the "Study Date" and "Report Time" fields do not, and result in hashes in the result field, as the column is too short.

![image](https://user-images.githubusercontent.com/20720278/152564608-e5145613-06ea-4c06-a0d7-a17533729d26.png)

Note that Study Description field is "General" format while both Study Date and Report Time fields are "Custom" format.

When I double click it in Excel, the width changes from 13.29 to 15.14 and the text is displayed correctly.

Not sure if this is an issue with my command or something else, however would appreciate any feedback.

**Comment by dfinke** [comment]
`ImportExcel` makes best efforts for auto sizing. For dates/times the xlsx that gets created is before it renders in Excel. Use `Set-ExcelRange` after the xlsx is exported and you can use the `-Width` parameter to handle that better.

**Comment by Philenst** [comment]
Seems that `Set-ExcelRange` with the `-Width` parameter was exactly what I needed!

Thanks very much!
