### ISSUE TITLE
Lookup one value in col and retun one/more values from other col's in same row?

### ISSUE THREAD

**Issue by mc1903** [dfinke/ImportExcel#1135]
Hi Doug,

Is there a function that will allow me to lookup a value in one column and return value(s) from other column(s) in that row?

Thanks.
M

**Comment by dfinke** [comment]
Hi, I'm not sure if you are asking if Excel can do that or the PowerShell module. In Excel you can use `VLookup` or `HLookup` to do that.

there is no function that does that in the PowerShell module. You would either need to read in all the data to an array using `Import-Excel` and then figure out those values etc., or use `Open-ExcelPackage` to open the xlsx and then find the `Cell`, inspect it and then reference the other columns.

**Comment by stahler** [comment]
Here is an example that has a dynamic vlookup, hope it helps:
https://gist.github.com/stahler/51e84413e4c05d9a563dc7cac766b5cc

**Comment by mc1903** [comment]
> Hi, I'm not sure if you are asking if Excel can do that or the PowerShell module. In Excel you can use `VLookup` or `HLookup` to do that.
> 
> there is no function that does that in the PowerShell module. You would either need to read in all the data to an array using `Import-Excel` and then figure out those values etc., or use `Open-ExcelPackage` to open the xlsx and then find the `Cell`, inspect it and then reference the other columns.

Hi Doug,

Doh, sorry... I meant to have said "_Is there a function within the ImportExcel module..._"

:-) `VLookup` or `HLookup`  in Excel are the bain of my life.

I'll have a play with both `Import-Excel` & `Open-ExcelPackage` and see if I can work it out.

It's just looking up values in specific columns in one workbook to copy a subset of the returned row's columns into another workbook. Currently it's a thankless manual task that is mind numbingly boring and error prone.

Cheers
M

**Comment by mc1903** [comment]
> Here is an example that has a dynamic vlookup, hope it helps: https://gist.github.com/stahler/51e84413e4c05d9a563dc7cac766b5cc

Thank you. I will have a tinker with this as well. M

**Comment by mc1903** [comment]
Hi Doug. @dfinke.

I am having some luck with `Import-Excel` but my source workbook/worksheet (over which I have no control) is in a poor state.

Trying to import the 10Mb .xlsx file ‘as is’ ran for 20 minutes and consumed over 14Gb of system memory (before I terminated the PowerShell process). I think the worksheet has ‘blank’ data or formatting in some/all of the 1048576 rows x 16384 columns.

When I cut the 10000xCB range out (where the data I care about resides) and pasted it into a new worksheet as clean data, the import took seconds and consumed minimal memory.

Can I limit the scope of the import to just the first 10000 rows, and just from columns A through CB.

Also, the row 1 column header names make truly awful PowerShell property names (long, lots of spaces). They get truncated and this causes duplicates. Can I just have the column letters returned as the property names?

Any help or advice will be appreciated.

Thanks
M
