### ISSUE TITLE
Export-Excel / Freeze top row not correct when title is set

### ISSUE THREAD

**Issue by Smeulf** [dfinke/ImportExcel#1137]
Hi all.

First of all, I want to thank everyone working on that wonderful module.

That said, it seems there's a little glitch in the Export-Excel function with the FreezeTopRow option. 

When a title is set, only the first row is frozen. If I'm correct, the issue is here: https://github.com/dfinke/ImportExcel/blob/0c8bb2300aed581bf507aa102a1f33cf79d858a5/Public/Export-Excel.ps1#L496

I think it should be `$ws.View.FreezePanes(3, 1)` (but I may be wrong?)

Sorry if I don't send a PR for this, but it's a so small glitch...

Anyway if anyone can fix it, it would allow me to save a few lines of code in my own functions ;)

All the best.
Smeulf.

**Comment by dfinke** [comment]
You need to use the parameter `-FreezePane 3, 1`

**Comment by Smeulf** [comment]
Thank for the tip. Indeed it will work.

However, please let me point out the code can then be cleaned IMHO:

```
elseif ($FreezeTopRow) {
                if ($Title) {
                    $ws.View.FreezePanes(2, 1)
                    Write-Verbose -Message "Froze title and header rows"
                }
                else {
                    $ws.View.FreezePanes(2, 1)
                    Write-Verbose -Message "Froze top row"
                }
```
If Title then freeze the second line, if no title freeze also the second line. That's why I thought something was wrong 😉

**Comment by dfinke** [comment]
Thanks, understood, that code has been there for quite a long time, and could be a problematic breaking change :)

**Comment by Smeulf** [comment]
> could be a problematic breaking change :)
I must admit I didn't though about breaking already built scripts... My bad. Now it's up to you!

You guided me to a working direction, I'm fine with that!

**Comment by dfinke** [comment]
No worries. You wouldn't have known about that. Comes with the territory when you maintain open source 🙂
