### ISSUE TITLE
Identify Hidden Rows/Columns?

### ISSUE THREAD

**Issue by Relaxdaws** [dfinke/ImportExcel#1139]
Hello - I'm working with some Excel files that have hidden rows/columns and converting them to CSV.  The entire file is converted to CSV regardless of a row/column being hidden. Is it possible to identify these hidden columns and/or rows?

**Comment by dfinke** [comment]
@Relaxdaws, you need to get to the Excel "object model" for this. You can use `-PassThru` on `Export-Excel` or use `Open-ExcelPackage` on the saved xlsx. Below is how you can loop through rows and columns to see if that target is hidden or not. Adjust this to fit your scenario.

```powershell
$xlfilename = 'testHidden.xlsx'

$xl = Open-ExcelPackage $xlfilename

$rowCount = $xl.Sheet1.Dimension.Rows
$columnCount = $xl.Sheet1.Dimension.Columns

foreach ($ridx in 1..$rowCount) {
    "R{0} hidden = {1}" -f $ridx, $xl.Sheet1.Row($ridx).Hidden    
}

foreach ($cidx in 1..$columnCount) {
    "C{0} hidden = {1}" -f $cidx, $xl.Sheet1.Column($cidx).Hidden    
}


Close-ExcelPackage $xl -NoSave
```

**Comment by Relaxdaws** [comment]
This is great. Thank you 👍

**Comment by dfinke** [comment]
If you hit issues, or have more questions, please post them.
