### ISSUE TITLE
Convert HTML table to Excel without invoke-webrequest

### ISSUE THREAD

**Issue by smwk** [dfinke/ImportExcel#114]
Finding ImportExcel a great use but a lot of my scripts are not one-liners and have a number of conditions before being outputted to a table. It would be great to pipe this HTML table straight to Excel rather than using ImportHTML. 

Importing the cell colours would also be very useful.

**Comment by dfinke** [comment]
Looking forward to your PR :-)

**Comment by smwk** [comment]
I'll give it a try anyway :)

**Comment by dfinke** [comment]
Could  you say more about "pipe this HTML table straight to Excel" or post an example if you have one?

**Comment by smwk** [comment]
`$table = "<table><tr><td>value1</td><td>value2</td></tr></table>"`

So as far as I'm aware to export this to Excel would be to output this to a HTML page, save it to a webserver and then call Get-HtmlTable http://webserver/page.html 0 

It would be great just to be able to call Get-HtmlTable $table

**Comment by dfinke** [comment]
Got it. `Import-Html` uses `Invoke-WebRequest` which parses the HTML into PowerShell objects. To parse HTML it would need something like this, https://htmlagilitypack.codeplex.com/

**Comment by smwk** [comment]
I think for now I can work with PSObjects instead of HTML. It would still be nice to have cell backgrounds as a feature.
