### ISSUE TITLE
Create a Drop-down List with ImportExcel

### ISSUE THREAD

**Issue by marcosfreccia** [dfinke/ImportExcel#1142]
Hi Folks,

Sorry if this is not the right place for the question. I am wondering if it is possible to create with ImportExcel a column with a drop-down list of options.

For example, like having a column named Status and the values be a drop-down list being 0 or 1.

Thanks,
Marcos

**Comment by dfinke** [comment]
Maybe this?

https://github.dev/dfinke/ImportExcel/blob/cb7f2a06f49eeeb47b8e463fee8529b0db38dd6d/Examples/ExcelDataValidation/MutipleValidations.ps1#L1

**Comment by marcosfreccia** [comment]
That seems to be exactly what I need... Thanks a lot!
