### ISSUE TITLE
How to compare PS configuration CSV files against baseline configuration data  in excel 

### ISSUE THREAD

**Issue by Rowem1** [dfinke/ImportExcel#1143]
How can I use importexcel to import CSV configuration files and compare with a baseline configuration data in excel and report any discrepancies in excel using if functions or lookups  or run by a automated  process?

**Comment by dfinke** [comment]
Check this for examples and description of `Compare-Worksheet`. See if this helps.

https://github.dev/dfinke/ImportExcel/blob/cb7f2a06f49eeeb47b8e463fee8529b0db38dd6d/mdHelp/en/compare-worksheet.md#L1

**Comment by Rowem1** [comment]
Thanks!
