### ISSUE TITLE
Enable opening a workbook Read-Only even if it is already open elsewhere

### ISSUE THREAD

**Issue by robbratton** [dfinke/ImportExcel#1144]
I would like to be able to open a workbook in a read-only mode even if it's already open in the Excel application or through a COM object.

When I use the Open-ExcelPackage method while I have the same file open in the Excel application, I get an exception.
`$ExcelDoc = Open-ExcelPackage $AppDEnvMatrixPath`

"Exception calling ".ctor" with "1" argument(s): "The process cannot access the file 'Filename.xlsx' because it is being used by another process."

**Comment by dfinke** [comment]
Check out how the function `Import-Excel` does it. I can have the sheet open and still read it. This approach is more low level.

https://github.com/dfinke/ImportExcel/blob/master/Public/Import-Excel.ps1#L121-L122
