### ISSUE TITLE
BUG: Cell color not default

### ISSUE THREAD

**Issue by GamerClassN7** [dfinke/ImportExcel#1146]
Hello, whe i try to export file with library, all empty cells are yellow from no reason
![image](https://user-images.githubusercontent.com/22167469/159012324-05eff3d0-7dac-45ae-893c-dad853cbd5e4.png)

can anybody help  ?

**Comment by GamerClassN7** [comment]
COnnection ? https://github.com/dfinke/ImportExcel/issues/532

**Comment by lschums** [comment]
I have the same Issue. It seems like the default cell style is altered with a yellow background on saving (or even an additional style is added, as I suddently have a default 2, but all are with yellow background).

In my case I open an existing workbook, remove sone sheets, and save it.
