### ISSUE TITLE
How to prevent an Excel file from being accidentally overwritten when using Export-Excel?

### ISSUE THREAD

**Issue by claudio-salvio** [dfinke/ImportExcel#1147]
Hello,

From my point of view, it is a good practice that functions that create files (or any other object) do not overwrite them by default if they already exist.
I consider it reasonable that the `-Force` parameter should be used to produce the overwrite.

If for some reason you want to opt for default overwrite, I think it is good to have a configuration parameter (for example something like `$ExportExcelOverwrite`) that can be properly configured to generate that behavior for those who feel as I do in this regard.

I have searched the issues and found that at one time there was the `-Force` parameter and at another time the `-NoClobber` parameter.
However, from what I saw, currently both parameters are not available.
I have yet to find an explanation as to why they were discarded.

That said, is there a way to prevent `Export-Excel` from overwriting existing Excel files?

In case there isn't, would it be possible for you to add some alternative so that it can be achieved?

Best regards,
Claudio Salvio

P.D.: 🙏Thanks to all (obviously especially to @dfinke) who invested time and effort in this module and for sharing it with the community.

**Comment by dfinke** [comment]
Thanks @claudio-salvio. Don't remember why those switches were deprecated.

As for preventing the overwriting. It is left to the scripter to handle that. 

Following the behavior of `Export-Csv`, this will overwrite `test.csv` each time it is run.

```powershell
Get-Process | Select-Object Company,name | Export-Csv test.csv
```

**Comment by claudio-salvio** [comment]
@dfinke 

Thanks for your prompt reply.
As I commented in my first post, in general terms, I consider that inadvertent overwrites should not occur.
In my opinion overwriting should always be explicit but I know that not everyone shares this point of view.

I am sorry that `Export-Excel` does not have an option to handle this, but being aware I will take the appropriate precautions.
Because of the above, I would like no `Export-*` function overwrite. 

I honestly don't know if there is any official position (or any good community practice) in PowerShell about how functions that can overwrite such as Export-*, Move-*, New-*, etc. should behave in this regard.
I asked the question because I wanted to make sure there wasn't some mechanism to work more safely and I wasn't seeing it.

Anyway, thanks again for getting back to me.

Regards,
Claudio
