### ISSUE TITLE
Extra columns at the end export-excel

### ISSUE THREAD

**Issue by mohammad-amiri** [dfinke/ImportExcel#1152]
hi,
I downloaded the latest version of ImportExcel and tried to use it for a project I am working on. This is the PowerShell script I am using. 

Remove-Item -Path $fileName -ErrorAction ignor
Invoke-Sqlcmd -Query $sqlcmd -ServerInstance $Server_Instance -OutputAs DataRows |Export-Excel -AutoSize -AutoFilter -BoldTopRow  -Path $fileName -WorksheetName $xlsxName

Everything is working well.
I see the XLSX file, but there are some extra columns at the end that I don't need in this file.
How can we not generate these columns? Is there an option that I missed?
Thanks
[Test_Case.xlsx](https://github.com/dfinke/ImportExcel/files/8366603/Test_Case.xlsx)

**Comment by AikenBM** [comment]
I also get this with exporting with `Read-SqlTableData` or `Read-SqlViewData` from the SqlServer module. No matter what I do, I can't seem to get it to exclude the columns.

Even this does not work:

```
Read-SqlTableData @SqlParameters -TableName MyTable -ColumnName A,B,C |
Export-Excel -Path 'X:\Path\to\File.xlsx' -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors
```

The columns remain.

This does not work, either:

```
Read-SqlTableData @SqlParameters -TableName MyTable -ColumnName A,B,C |
Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors |
Export-Excel -Path 'X:\Path\to\File.xlsx'
```

The OutputAs parameter of Read-SqlTableData doesn't seem to change the behavior, either.

`Export-Csv` does not have this issue.

**Comment by dfinke** [comment]
@AikenBM, running this, are those properties excluded? 

```powershell
Read-SqlTableData @SqlParameters -TableName MyTable -ColumnName A,B,C |
Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors
```

**Comment by AikenBM** [comment]
@dfinke Those columns don't display in Powershell at all. Those are properties built in to the System.Data.DataRow class, but they never display.

It appears to be a problem with DataRows.

Here's a reproducible example that doesn't require any external database.

```
# Make a new DataTable
$DataTable = New-Object -TypeName System.Data.DataTable

# Create columns and add them to the DataTable
$DataColumn1 = New-Object -TypeName System.Data.DataColumn -ArgumentList 'ID', ([int])
$DataTable.Columns.Add($DataColumn1)
$DataColumn2 = New-Object -TypeName System.Data.DataColumn -ArgumentList 'First Name', ([string])
$DataTable.Columns.Add($DataColumn2)
$DataColumn3 = New-Object -TypeName System.Data.DataColumn -ArgumentList 'Last Name', ([string])
$DataTable.Columns.Add($DataColumn3)

# Instance a new row, assign values, assign it to the table
$DataRow = $DataTable.NewRow()
$DataRow['ID'] = 1
$DataRow['First Name'] = 'Frank'
$DataRow['Last Name'] = 'Miller'
$DataTable.Rows.Add($DataRow)

# Instance a new row and assign values
$DataRow = $DataTable.NewRow()
$DataRow['ID'] = 2
$DataRow['First Name'] = 'Neil'
$DataRow['Last Name'] = 'Gaiman'
$DataTable.Rows.Add($DataRow)

# The unwanted properties do not display when displaying a table
# This is a DataTable
$DataTable

# Or when displaying the rows
# This is DataRowCollection, which works like an array of data rows
$DataTable.Rows
# This is an array of DataRows
[System.Data.DataRow[]]$DataTable.Rows


# But the properties certainly exist
$DataTable | Format-Table *

$DataTable.Rows[0] | Format-Table *

([System.Data.DataRow[]]$DataTable.Rows)[0] | Format-Table *

# And you can exclude them
$DataTable | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Format-Table *

$DataTable.Rows | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Format-Table *

[System.Data.DataRow[]]$DataTable.Rows | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Format-Table *

# And they don't export to CSV
# Export table to CSV, ConvertTo-Csv
$DataTable | ConvertTo-Csv
$DataTable.Rows | ConvertTo-Csv
[System.Data.DataRow[]]$DataTable.Rows | ConvertTo-Csv

# But they *always* export to Excel
$DataTable | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel .\Test-DataTable.xlsx
$DataTable.Rows | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel .\Test-DataRowCollection.xlsx
[System.Data.DataRow[]]$DataTable.Rows | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel .\Test-DataRowArray.xlsx
```

I did discover that `ConvertTo-Html` includes them:

```
$DataTable | ConvertTo-Html -Fragment
```

But you can successfully exclude them if you want:

```

**Comment by dfinke** [comment]
@AikenBM thanks for the repro. Not sure, it works for me.

I did add `Remove-Item` and the `-Show` on Export-Excel.

What version of PS and the Excel module are you running?

```powershell
# Make a new DataTable
$DataTable = New-Object -TypeName System.Data.DataTable

# Create columns and add them to the DataTable
$DataColumn1 = New-Object -TypeName System.Data.DataColumn -ArgumentList 'ID', ([int])
$DataTable.Columns.Add($DataColumn1)
$DataColumn2 = New-Object -TypeName System.Data.DataColumn -ArgumentList 'First Name', ([string])
$DataTable.Columns.Add($DataColumn2)
$DataColumn3 = New-Object -TypeName System.Data.DataColumn -ArgumentList 'Last Name', ([string])
$DataTable.Columns.Add($DataColumn3)

# Instance a new row, assign values, assign it to the table
$DataRow = $DataTable.NewRow()
$DataRow['ID'] = 1
$DataRow['First Name'] = 'Frank'
$DataRow['Last Name'] = 'Miller'
$DataTable.Rows.Add($DataRow)

# Instance a new row and assign values
$DataRow = $DataTable.NewRow()
$DataRow['ID'] = 2
$DataRow['First Name'] = 'Neil'
$DataRow['Last Name'] = 'Gaiman'
$DataTable.Rows.Add($DataRow)

Remove-Item .\Test-DataTable.xlsx -ErrorAction SilentlyContinue
$DataTable | Select-Object -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel .\Test-DataTable.xlsx -show
```

**Comment by dfinke** [comment]
There is also `-ClearSheet` on `Export-Excel`, not sure if that solves it. I'd need to look, the EPPlus DLL used to create the xml in xlsx file to recall how and why. It's been that way since the start, I think this is maybe the first time it has come up.

**Comment by mohammad-amiri** [comment]
hi,
Thanks for the feedback.
This worked for me:

Remove-Item  $File_Full_Path -ErrorAction Ignore
$SQL_CMD= ' select * from '+$Data_Base + '.dbo.'+$SQL_Table
Write-Host $SQL_CMD

$SQL_Conn='Data Source='+$SQLHost_Name+';Initial Catalog='+$Data_Base+';Integrated Security=True;ApplicationIntent=ReadOnly'
Write-Host $SQL_Conn
$SQL_Data=SqlServer\Invoke-Sqlcmd  -Query $SQL_CMD -ConnectionString $SQL_Conn 


$SQL_Data | 
    Sort -Property ID -Descending |
    Export-Excel -Path $File_Full_Path -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors
