### ISSUE TITLE
CSV to XLSX Conversion Oddity

### ISSUE THREAD

**Issue by skinnyl** [dfinke/ImportExcel#1153]
Hi there,

There's a fair chance I've missed the switch to solve this somewhere, but I haven't found anything too similar searching previous issues. Although I did see something about blanks in a pivot table and wonder it this might be releted, and possibly not fixable from what I read. But just in case...

I'm converting a CSV to XLSX, the file is respondent level market research verbatim (respondents down the side and answered questions across the top) and the problems I'm having after conversion is a) text isn't overspilling into the adjacent cell if the adjacent cell is empty b) imported dates don't behave correctly in autofilter. Open the CSV in excel before converting and all is well.

This is all solved by copying everything into notepad and pasting it back in to the XLSX. However, I'm keen to remove this step for end users if possible. 

Thanks in advance,

Jack.

**Comment by dfinke** [comment]
Would need to see the csv to better diagnose.

**Comment by dfinke** [comment]
@skinnyl good one, don't know. Thought it might be the `Q22a` column and how `Import-Csv` handled it, but that didn't pan out.

A possible alternative is to use `-AutoSize`, but then other columns will also resize. If I find something, I will post it.

```powershell
Import-Csv 'Output\LatestOutputCSV.csv' | Export-Excel 'Output\LatestOutputXLSX.xlsx' -AutoSize
```
