### ISSUE TITLE
not saving correctly

### ISSUE THREAD

**Issue by computechrr** [dfinke/ImportExcel#1155]
this is the part of my script that exports the data to excel 
foreach($tedserver in $tedservers) {
$kbtenables | Where-Object {$_.'dns name' -match $tedserver} | Export-Excel -Path 'D:\Powershell Scripts\Data\WindowsUpdates\Tenable.xlsx' -WorksheetName Ted-KB -Append -AutoSize
$othertenables | Where-Object {$_.'dns name' -match $tedserver} | Export-Excel -Path 'D:\Powershell Scripts\Data\WindowsUpdates\Tenable.xlsx' -WorksheetName Ted-Other -Append -AutoSize
}
i have the same thing about 6 times, one for each tech. when i run one loop everything works but doing 2 or more i get this error message
MethodInvocationException: C:\Users\my user\Documents\PowerShell\Modules\ImportExcel\7.4.1\Public\Export-Excel.ps1:679:20
Line |
 679 |              else { $pkg.Save() }
     |                     ~~~~~~~~~~~
     | Exception calling "Save" with "0" argument(s): "Error saving file D:\Powershell Scripts\Data\WindowsUpdates\Tenable.xlsx"

what i end up with is a spreadsheet with 2 sheets which is from the last loop instead of all sheets for all techs
Thank you

**Comment by computechrr** [comment]
i went back to this the next day, closed code and reran the script and everything works

**Comment by dfinke** [comment]
Sometimes it only works every other Thursday ;-)
