### ISSUE TITLE
Export-Excel Warnings when on Linux

### ISSUE THREAD

**Issue by Clifra-Jones** [dfinke/ImportExcel#1156]
Is there anyway to suppress this warning "Auto-fitting columns is not available with this OS configuration." when using export-excel on Linux. I get it, auto-fitting isn't working but I'll deal with that. It c;utters up the output and makes debugging a long script cumbersome.

Thanks.

**Comment by dfinke** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.2#warningpreference
