### ISSUE TITLE
Summation of Values Issue - ImportExcel/ExportExcel

### ISSUE THREAD

**Issue by kpippy27** [dfinke/ImportExcel#1157]
Hello, this is my first comment on Github and I am newer to PowerShell so please bare with me.... I am creating a pivot table on the same excel workbook as the raw data and am dealing with the summation of the values. It is putting the summation into rows and I need it in columns, is there anyway to programmatically move it from rows to columns? 
See the two pictures below if I explained things poorly....
![CorrectValuesSummation](https://user-images.githubusercontent.com/85600004/162246432-ac51313c-43b6-42e9-9d82-c84568022825.JPG)
![WrongValuesSummation](https://user-images.githubusercontent.com/85600004/162246448-6b9d049b-ca7d-49fd-b899-679400ffa0ff.JPG)
-Thank you!!

**Comment by dfinke** [comment]
Are you generating this with PowerShell and the ImportExcel module? Or is this a general Excel question?
