### ISSUE TITLE
Export-Excel Issue

### ISSUE THREAD

**Issue by bacchus21** [dfinke/ImportExcel#1158]
Hello, All

I'm having some strange issue in powershell when exporting get-aduser output.

My script working
============
#Open Excel Object
$ExcelObj = New-Object -comobject Excel.Application
$ExcelObj.visible=$False

$CardUsers = Get-ADUser -Properties * -Filter{(extensionAttribute9 -like "*") } 
$CardUsers | Export-Excel 'C:\Users\(username)\Downloads\employee_list.xlsx' -WorksheetName "Current Employee" -MoveAfter "All Employee"  -AutoSize 

=> Get-ADUser info is being saved as worksheet name "Current Employee" after "All Employee" worksheet. This is expected result.

My script not working
===============
#Open Excel Object
$ExcelObj = New-Object -comobject Excel.Application
$ExcelObj.visible=$False
$SOURCE_DATA = $env:USERPROFILE + "\Downloads"

$CardUsers = Get-ADUser -Properties * -Filter{(extensionAttribute9 -like "*") } 
$CardUsers | Export-Excel '$SOURCE_DATA\employee_list.xlsx' -WorksheetName "Current Employee" -MoveAfter "All Employee"  -AutoSize 

=>Getting the following error message.

WARNING: Can't find worksheet 'All Employee'; worsheet 'Current Employee' will not be moved.
---------------------------------------------------------------------------------------------------------

Only difference is that I was trying to use $env:USERPROFILE, and it's pointing the same location basically. But, not sure why the error is occurring. Anyone has clue? Please advise. I really appreciate it. Thank you in advance.

**Comment by dfinke** [comment]
Sorry, this module does not use COM to interact with Excel. Probably better to post this on stackoverflow.

**Comment by bacchus21** [comment]
Thank you very much for your advice.
