### ISSUE TITLE
Export-Excel using -CellStyleSB, the $LastColumn variable contains wrong value

### ISSUE THREAD

**Issue by lukeb1961** [dfinke/ImportExcel#1160]
using 7.4.1 and trying to export into excel a block of data of circa 319 columns and 6000+ rows.
I find the call wandered off into space and consumed 6Gb of RAM after a solid hour of I don't know what!

I find the args to -CellStyleSB have passed in an automatic variable LastColumn with wrong information, which may be related to the row count. Instead of 'LG' it had LG671 or similar. I overrode this with my own calculated variable and all is now well.

**Comment by dfinke** [comment]
Thank you, could you post a simple repro of that?
