### ISSUE TITLE
Question: what property == "show item labels in tabular form"

### ISSUE THREAD

**Issue by lukeb1961** [dfinke/ImportExcel#1162]
Created some pivot tables to match an example from an existing sheet and I find the layout requires ticking the box 
"Show Item Labels In Tabular Form".

Can this be done via ImportExcel? 
I have been digging all afternoon without success, so time to ask the wizards.

**Comment by dfinke** [comment]
Please could you post an xlsx with that ticked. I'm not familiar with thar feature.
