### ISSUE TITLE
Cell limit exceeded

### ISSUE THREAD

**Issue by kspeeckaert** [dfinke/ImportExcel#1166]
Using `Export-Excel` with columns that contain > 32,767 characters (see [Excel specifications and limits](https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3)) will result in a corrupt Excel file. When opening, Excel will show the error message: "_We found a problem with some content in 'test.xlsx. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes._"

![Error message](https://user-images.githubusercontent.com/6348619/164024369-df88ef5a-e746-4426-9b18-77c0f9a8df07.png)

Proof:
```
[PSCustomObject] @{
        'TooLarge' = '*' * 32768
    } | Export-Excel -Path $env:TEMP\test.xlsx -NoHeader
```

Tested with:

- ImportExcel 7.4.1
- PowerShell 5.1.19041.1645
- Excel for Microsoft 365

**Comment by dfinke** [comment]
Yup, it's a limitation.
