### ISSUE TITLE
Export-Excel columns positioning issue

### ISSUE THREAD

**Issue by pietropiz** [dfinke/ImportExcel#1167]
Hello,
i would like to use the Export-Excel function to fill a custom Excel file, but i have some problems with the columns positioning in the output file.
The attached "example.xlsx" is an example of my starting file, for which i cannot modify the structure. The original file I need to fill, would be a xlsm file with some macros and much more columns (162), but the end result is the same.

The column headers i need to reference are the ones on row 5
What i would like to do is appending data to the Excel file starting from row 6
I'm trying to use some sample code like this:

```
$excelOutput = [PSCustomObject][Ordered]@{
    Header_1  = 'String1'
    Header_2  = 'String2'
    Header_4  = 'String3'
    Header_6  = 'String4'
    Header_8  = 'String5'
    Header_10 = 'String6'
} | Export-Excel "<path_to_excel_file>" -Append -WorksheetName 'MySheet' -StartRow 6
```

If I execute this, i would expect to find my data on row 6, under the correct column headers.
Instead my data is (correctly) on row 6, but moved to the right exactly 2x the number of column headers, so 20 columns to the right in this case (see attached file "example_output.xlsx", data is on row 6, starting from column AE)
I also tried to play with -StartRow 5, -StartRow 6 and the -NoHeader attributes, but the end result is always similar.
If i remove rows 1 to 4 from the Excel file, leaving only the column headers, my sample script (without -StartRow 6 of course) is working as expected.

I also have another custom Excel file with a similar structure, for which i get the same result.
I'm using version 7.4.1 of the ImportExcel module.

Am I doing something wrong or is this a bug within the module?
Thanks.

[example.xlsx](https://github.com/dfinke/ImportExcel/files/8529684/example.xlsx)
[example_output.xlsx](https://github.com/dfinke/ImportExcel/files/8529686/example_output.xlsx)

**Comment by dfinke** [comment]
Please could you post a small PS script that repos this

**Comment by pietropiz** [comment]
> Please could you post a small PS script that repos this

the PS command I'm using is in my first message. If you use that command with the excel file i provided (example.xlsx), you should be able to reproduce the issue.
The only difference with my script is that i have some variables for some of the values, but the problem occurs even with plain strings like in my example

**Comment by dfinke** [comment]
The `-Append` works based on the dimensions of the sheet. My guess is the button does not factor into the # of rows.

Start with a simpler worksheet, just headers at in row 1, and then experiment from there.

**Comment by pietropiz** [comment]
The problem is not the first row with the button.
The problem is that the data appended to the excel file is shifted to the right by several columns (see the attached "example_output.xlsx"), exactly 2x the number of columns, which i find it quite suspicious.
It seems to me that the different rows with different headers are messing with your module, causing it to misbehave.

I also cannot modify the worksheet since it's a template used in my company for some compliance process

**Comment by dfinke** [comment]
Don't know. The data did not to the right when I ran it.

You can always use `Open-ExcelPackage` & `Close-ExcelPackage`, and place the data exactly where you need it. Finer grained control, and more work for you.
