### ISSUE TITLE
Exporting from SQL - SQL int converts to Excel "Custom" number format

### ISSUE THREAD

**Issue by MKaidan** [dfinke/ImportExcel#1168]
### Powershell Script
```
#requirements
#Install-Module Sqlserver
#Install-Module ImportExcel

# Notes
# NoNumberConversion: https://stackoverflow.com/a/69400119/2457222

$sqlquery = "SELECT * FROM viewItems;"

$sqlserver = "####"
$sqlusername = "####"
$sqlpassword = "####"
$sqlcredential = (New-Object System.Management.Automation.PSCredential($sqlusername,($sqlpassword | ConvertTo-SecureString -asPlainText -force)))
$sqldb = "####"

Invoke-SqlCmd -serverInstance $sqlserver -Database $sqldb -credential $sqlcredential -Query $sqlquery |select * -ExcludeProperty ItemArray, RowError, RowState, HasErrors, Table | export-excel "\Inventory.xlsx" -autosize  -NoNumberConversion BarcodeNum, substylecount
```

### Exported File
[Inventory.xlsx](https://github.com/dfinke/ImportExcel/files/8557112/Inventory.xlsx)

### The Problem
The **substylecount** is a column of data type *int* in SQL which should be presented as such, but instead you see in the attached file that it displays as a custom number format (`m/d/yyy h:mm`) for some strange reason.

**Comment by MKaidan** [comment]
> Please, could you post a repro of the data and export. Capture or manually create a csv file, then I can better review it.

I posted the export from the Powershell export.

If you mean the export of the original data in SQL Server, here it is: [inventory.csv](https://github.com/dfinke/ImportExcel/files/8573275/inventory.csv)

**Comment by MKaidan** [comment]
I posted the export from the Powershell export.

If you mean the export of the original data in SQL Server, here it is: [inventory.csv](https://github.com/dfinke/ImportExcel/files/8573333/inventory.csv)

**Comment by dfinke** [comment]
Not clear why xlsx is different.

```powershell
import-csv .\inventory.csv | export-excel "Inventory.xlsx" -autosize  -NoNumberConversion BarcodeNum, substylecount
```

![image](https://user-images.githubusercontent.com/67258/165554483-dbef40f1-c83e-4e43-b25b-2f9b8ca338e4.png)
