### ISSUE TITLE
How to query dimension and values from specific column by column name?

### ISSUE THREAD

**Issue by Noizcontroller** [dfinke/ImportExcel#1169]
Hi

I'm struggling to understand this module so I can get the result I want. I want to use a specific sheet in my Excel file to store different lists of values so I can use them for data validation. The lists all have different lengths and I want to read the values and get the length of the list so I can use them for data validation. It would be handy if I can search a column by name to get this info. Any ideas how to achieve this?

![image](https://user-images.githubusercontent.com/30369760/165154051-12c7dfed-0dcd-4ec2-8c67-7ab8708fe0b0.png)

Kind regards

**Comment by stahler** [comment]
Here is something to explore with:

```PowerShell
# Create an excel package
$package = Open-ExcelPackage -Path C:\temp\Validation.xlsx

# How many validation columns does the validation worksheet (sheet1) have?
$names = $package.Sheet1.Workbook.Names
"There are {0} validation columns." -f $names.count

# What are the Column names
$names | Select-Object -Property name 

# How man rows are there and what are the values
$Driver = $Names['Driver']

"There are {0} Driver rows.`n" -f $Driver.Rows

# What are the Color column values
$Driver.ForEach({$PSItem.Value})
```
[Validation.xlsx](https://github.com/dfinke/ImportExcel/files/8565821/Validation.xlsx)

**Comment by Noizcontroller** [comment]
Hi stahler

Thanks for your reply. I tried it but it doesn't work. It's like the script doesn't see any names in the sheet (called blad1) because my Excel is in dutch.

![image](https://user-images.githubusercontent.com/30369760/165581851-b2044525-ee34-4cb6-80e7-9f2a40fd3873.png)

Kind regards

**Comment by stahler** [comment]
Wouldn't think that would matter.  Did you try to actually iterate over the names?
I see the same thing you do until I actually iterate over them.
```PowerShell
$package.Sheet1.Workbook.Names | Select name

**Comment by dfinke** [comment]
@Noizcontroller curious, could you post what you get back from this.

```powershell
Get-ExcelFileSummary C:\Users\finke\Downloads\Validation.xlsx
```

**Comment by Noizcontroller** [comment]
> @Noizcontroller curious, could you post what you get back from this.
> 
> ```powershell
> Get-ExcelFileSummary .\Validation.xlsx
> ```

Hi dfinke

I'm getting this as a result:

`ExcelFile     : Validation.xlsx
WorksheetName : Blad1
Rows          : 5
Columns       : 2
Address       : A1:B5
Path          : C:\Temp`

Kind regards

**Comment by dfinke** [comment]
Sorry, didn't get the gist of the thread.

Not sure I am on the right page yet. To create names in the sheet, on the export you use `-AutoNameRange` then you can work with it. That's one way.

```
gsv | select DisplayName, Name, Status | export-excel .\gsv.xlsx -AutoNameRange
$excel= Open-ExcelPackage .\gsv.xlsx
$excel.Sheet1.Names
```

```
$excel.Sheet1.Names['status'] | group value
```

**Comment by stahler** [comment]
Good point @dfinke  - I wrongly assumed the named ranges were already in existence when they might not have been.

**Comment by dfinke** [comment]
@stahler cool, yeah, don't know if the were or not. Tough to glean this from these threads. Good clue on your end though.

**Comment by Noizcontroller** [comment]
> Sorry, didn't get the gist of the thread.
> 
> Not sure I am on the right page yet. To create names in the sheet, on the export you use `-AutoNameRange` then you can work with it. That's one way.
> 
> ```
> gsv | select DisplayName, Name, Status | export-excel .\gsv.xlsx -AutoNameRange
> $excel= Open-ExcelPackage .\gsv.xlsx
> $excel.Sheet1.Names
> ```
> 
> ```
> $excel.Sheet1.Names['status'] | group value
> ```
> 
> Not sure I'm answering the right question.

This was helpful. I recreated my Excel file with the -AutoNameRange parameter and I was able to query the names. This is my code so far:

`
# Initialise variables
$excelPath = "C:\Temp\PrinterExcel.xlsx"
$listsSheetName = "Lists"
$listsSheetColumns = [PSCustomObject]@{Printserver='';Status='';Support='';Stuurprogramma='';Merk='';Model='';Kleur=''}
$printersSheetName = "Printers"
$printersSheetColumns = [PSCustomObject]@{Printernaam='';Printserver='';Locatie='';Status='';Support='';Stuurprogramma='';Merk='';Model='';Kleur='';Firmware='';MAC='';Hostname='';IP=''}
$firmwareSheetName = "Firmware"
$firmwareSheetColumns = [PSCustomObject]@{Merk='';Model='';Firmware_local='';Firmware_latest=''}

# Check if Excel file exists
If(-Not(Test-Path -Path $excelPath -PathType Leaf)){
    $listsSheetColumns | Export-Excel -Path $excelPath -WorksheetName $listsSheetName -AutoNameRange
    $printersSheetColumns | Export-Excel -Path $excelPath -WorksheetName $printersSheetName -AutoNameRange
    $firmwareSheetColumns | Export-Excel -Path $excelPath -WorksheetName $firmwareSheetName -AutoNameRange
}

$printersExcel = Open-ExcelPackage -Path $excelPath -KillExcel
$printersExcel.Lists.Names['PRINTSERVER']
`
Which results in:

`
Style                 : OfficeOpenXml.Style.ExcelStyle
StyleName             : Normal
StyleID               : 0
Value                 : PRINTDOC
Text                  : PRINTDOC
Formula               : 
FormulaR1C1           : 
Hyperlink             : 
Merge                 : False
AutoFilter            : False
IsRichText            : False
IsArrayFormula        : False
RichText              : {}
Comment               : 
Worksheet             : Lists
FullAddress           : 'Lists'!A2
FullAddressAbsolute   : 'Lists'!$A$2
ConditionalFormatting : OfficeOpenXml.ConditionalFormatting.RangeConditionalFormatting
DataValidation        : OfficeOpenXml.DataValidation.RangeDataValidation
Current               : 
Address               : A2
Start                 : OfficeOpenXml.ExcelCellAddress
End                   : OfficeOpenXml.ExcelCellAddress
Table                 : 
IsName                : False
Rows                  : 1
Columns               : 1
`
I'm going to try and figure out how to add additional values and such. But I did notice something when I manually (in Excel) added an extra value to the "Printserver" column. When I run this again, the extra value is not returned. Any idea why?

`
$printersExcel = Open-ExcelPackage -Path $excelPath -KillExcel
$printersExcel.Lists.Names['PRINTSERVER']
`

**Comment by dfinke** [comment]
@Noizcontroller The `Named` ranges in Excel relate to the rows and columns for that data. If you manually add data you need to, in Excel add it to the name ranges. I'm not sure if you can extend the name range or delete and re-add with the new data.

**Comment by stahler** [comment]
The -AutoNameRange created the range when you first saved it.
Manually adding data, doesn't automatically update the named range.
If you adjust the NameRange after you manually edit it, it will work.

**Comment by stahler** [comment]
Opps - sorry Doug - collision :)

**Comment by stahler** [comment]
@Noizcontroller  - You can modify the named range by going to Formulas - Name Manager
<img width="416" alt="image" src="https://user-images.githubusercontent.com/1991193/165866473-58d16ebd-d9ad-4dc5-9c61-1a781de17c50.png">
