### ISSUE TITLE
Windows 10 and Office 2016

### ISSUE THREAD

**Issue by TheInfamousOne** [dfinke/ImportExcel#117]
Hello all.

I've installed this on my Windows 7 machine with Office 2010.  It works perfect.  But I tried to run this on my Windows 10 machine with Office 2016, the excel sheet will launch with nothing in it. The command I'm running is this.

Export-Excel .\UserInfo.xlsx -WorkSheetname UserInfo -ChartType PieExploded3D -IncludePivotChart -IncludePivotTable -Show -PivotRows Office -PivotData Department.

Does anyone know what might be happening?

**Comment by TheInfamousOne** [comment]
I found an EPPlus.dll on version 4.1, that did not work either.   the current version I found in 2.27 was 4.05.  I was throwing darts in the dark here. and guessing Office 2016 needed an updated DLL.

If anyone has a clue, please let me know.

**Comment by dfinke** [comment]
I haven't tested this with 2016. So I don't have any insight at the moment. Thanks for trying out the EPPlus 4.1.

**Comment by TheInfamousOne** [comment]
No Problem.  the EPPlus did seem to launch Excel more thoroughly if that makes any sense.,  With version 4.05, excel would launch without any plugs ins loading.  With 4.1, I could see excel try to launch with plugins.

**Comment by dfinke** [comment]
OK, I was able to export data to Excel 2016. If possible, could you post some sample data?

![image](https://cloud.githubusercontent.com/assets/67258/17912074/61e3fa82-695f-11e6-8f93-5d11c1e14bbd.png)

**Comment by TheInfamousOne** [comment]
Microsoft Office Professsional Plus 2016
Microsoft Excel 2016 MSO (16.0.4266.1001) 32-bit

When you say "Sample Data".  Do you mean you would like a copy of the excel sheet I'm trying to convert to a Pivot Table?

**Comment by TheInfamousOne** [comment]
I'll look for that patch and upgrade to 16.0.7030.1021 and see if that works.

**Comment by TheInfamousOne** [comment]
Hello dfinke.

Do you know the KB number for Microsoft Excel 2016 MSO (16.0.7030.1021) 32-bit?  I can't find it to download it.

Also, when I run the module on Windows 10 with Excel 2016 with EPPlus.dll version 4.1.  I see these two errors. 

"We found a problem with some content in "UserInfo.xlsx". Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

If I click "Yes", I see this next message.

"The workbook cannot be opened or repaired by Microsoft Excel because it's corrupt."

![repair](https://cloud.githubusercontent.com/assets/9556465/17947478/dbf617ae-6a1a-11e6-8a03-ebc273953408.PNG)
![yes](https://cloud.githubusercontent.com/assets/9556465/17947477/dbecc956-6a1a-11e6-9668-ee95db9c6bc0.PNG)

But, if I roll back the EPPlus.dll version to 4.0.5, which is the version I downloaded from GitHub.  Excel will open with "no errors" but there is no data in any workbooks, it's just blank.  It's kind of strange.

After I saw you were using Excel version 16.0.7030.1021, I could not find it on the internet to download the update.  So I'm assuming you're running "auto update" through excel.  I think we have that feature turned off where I work and manage our updates on our own.  So that is why I was asking for the KB number so I can download this update myself and update it to match your version and test it.  I can not seem to find it.  Do you know where I can get it?

**Comment by TheInfamousOne** [comment]
Issue resolved.  I got it to work with Office 2016 and Windows 10. Thanks for the help.

**Comment by dfinke** [comment]
Great! What was the resolution?

**Comment by TheInfamousOne** [comment]
I found an excel patch.

**Before:** Microsoft Excel 2016 MSO (16.0.4266.1001) 32-bit
**After:** Microsoft Excel 2016 MSO (16.0.4400.1000) 32-bit

I ran the script and it worked fine.  Although I still tried to use the "exploding pie chart" for Office 2016, I discovered it was no longer available.   It still worked, it just created a normal pie chart.

**Comment by dfinke** [comment]
Thanks! Wow, Excel needed to be patched. I'll try the charts and see the issues.

Thanks for reporting it.
