### ISSUE TITLE
export-excel not respecting new lines

### ISSUE THREAD

**Issue by sloth-101** [dfinke/ImportExcel#1170]
i try to export an array into a single excel cell but no matter how i try it, excel puts it all into one line.

![export-ecxcel_output](https://user-images.githubusercontent.com/56531003/165288726-479486b3-c6bd-4cdf-9c7f-c0850cddde28.PNG)

reproduce:

```
$diskid = invoke-command -computername "SRVwithmorethan1physicaldisk" -scriptblock {get-physicaldisk | select -expand objectid}
$a = [pscustomobject]@{
  a = $diskid
  b = $diskid |  join-string -Separator "`r`n"
  c = $diskid |  join-string -Separator "`c`r"
  d = $diskid |  join-string -Separator "`n`l"
  e = $diskid |  join-string -Separator "`cr"
  f = $diskid |  join-string -Separator "`nl"
}
$a | export-excel .\testexport.xlsx -TableName "newlinetest" -AutoSize
```

When I manually doubleclick cells b,c,d and f of the output file, excel will convert the single line into multiple lines! 
![export-ecxcel_expectedoutput](https://user-images.githubusercontent.com/56531003/165288723-3ab5d211-ebb7-4d5f-a579-b1159d9091af.PNG)
maybe touching the output with a some import-excel command will do the trick?

**Comment by dfinke** [comment]
Please can you try 

```
  x = $diskid |  join-string -Separator "`r"
  y = $diskid |  join-string -Separator "`n"
```

**Comment by sloth-101** [comment]
both behave the same as cells b,c,d and f. They are a single line initially, but separate upon double clicking the cell.

here is a gif of the behavior
![export-excel](https://user-images.githubusercontent.com/56531003/165450870-afa33a02-c85b-4314-ac63-8a104e718f2c.gif)

**Comment by sloth-101** [comment]
I posted an example in the first post...
you just need to run this against a computer that returns more then 1 object with get-physicaldisk.
if your machine has more then one you can just run
```
$diskid = get-physicaldisk | select -expand objectid
$a = [pscustomobject]@{
  a = $diskid
  b = $diskid |  join-string -Separator "`r`n"
  c = $diskid |  join-string -Separator "`c`r"
  d = $diskid |  join-string -Separator "`n`l"
  e = $diskid |  join-string -Separator "`cr"
  f = $diskid |  join-string -Separator "`nl"
  x = $diskid |  join-string -Separator "`r"
  y = $diskid |  join-string -Separator "`n"
}
$a | export-excel .\testexport.xlsx -TableName "newlinetest" -AutoSize
ii .\testexport.xlsx
```

but, any array will do, so this does it, too

```
$test = @("first row", "second row")

$a = [pscustomobject]@{
  a = $test
  b = $test |  join-string -Separator "`r`n"
  c = $test |  join-string -Separator "`c`r"
  d = $test |  join-string -Separator "`n`l"
  e = $test |  join-string -Separator "`cr"
  f = $test |  join-string -Separator "`nl"
  x = $test |  join-string -Separator "`r"
  y = $test |  join-string -Separator "`n"
} 
$file = "test.xlsx"
remove-item .\$file -force -ErrorAction SilentlyContinue
$a | export-excel .\$file -TableName "newlinetest" -AutoSize
ii .\$file
```

**Comment by dfinke** [comment]
Sorry, I meant with data not using get-physicaldisk. Can you repro this with a text or csv file? It will be easier to diagnose what part is not doing the right thing.

**Comment by sloth-101** [comment]
i dont really see how that makes it different (2nd example of last post), but here you go, attached are the files:

```
$test = @("__111111__", "__222222__")
$test | out-file .\test.txt
$import = get-content .\test.txt

$a = [pscustomobject]@{
  a = $import
  b = $import |  join-string -Separator "`r`n"
  c = $import |  join-string -Separator "`c`r"
  d = $import |  join-string -Separator "`n`l"
  e = $import |  join-string -Separator "`cr"
  f = $import |  join-string -Separator "`nl"
  x = $import |  join-string -Separator "`r"
  y = $import |  join-string -Separator "`n"
} 

$output = "test.xlsx"
remove-item .\$output-force -ErrorAction SilentlyContinue
$a | export-excel .\$output -TableName "newlinetest" -AutoSize
Invoke-Item .\$output

```

[test.txt](https://github.com/dfinke/ImportExcel/files/8580231/test.txt)
[test.xlsx](https://github.com/dfinke/ImportExcel/files/8580232/test.xlsx)

**Comment by dfinke** [comment]
I was just curious, wanted to cut down on the moving parts, don't know what `get-physicaldisk` outputs in terms of strings. I'll take a look, not sure if I've run this through `Export-Excel`, I believe it is the first-time hearing about it.

**Comment by sloth-101** [comment]
ok cool. but yeah, its not get-physicaldisk that causes the issues, just any array will do.

**Comment by dfinke** [comment]
Looks like you need to turn on text wrap, it is off by default.

```powershell
$data = [PSCustomObject]@{
    "Region" = "East"
    "State1" = "NY`r`nVT"
    "State2" = "NY`rVT"
    "State3" = "NY`nVT"
}

$excel = $data | Export-Excel .\test.xlsx -PassThru

Set-ExcelRange -Worksheet $excel.Sheet1 -Range "B:B" -WrapText 
Set-ExcelRange -Worksheet $excel.Sheet1 -Range "C:C" -WrapText 
Set-ExcelRange -Worksheet $excel.Sheet1 -Range "D:D" -WrapText 

Close-ExcelPackage $excel -Show
```

![image](https://user-images.githubusercontent.com/67258/166128858-20e861bb-3f83-42a3-8d8e-7118692b5379.png)

**Comment by sloth-101** [comment]
oh man, thats fantastic. Works like a charm. Thanks so much!
