### ISSUE TITLE
Importing multiple files with Import-Excel by pipeline uses only the first file for the row count

### ISSUE THREAD

**Issue by AikenBM** [dfinke/ImportExcel#1172]
# Version information

I am using:

- ImportExcel 7.4.2
- PowerShell v7.2.3
- Windows 10.0.19044 (21H2) x64

# Issue Description

I was importing about 20 Excel files that all have the same columns, but I found that many of the rows were missing. I discovered that even though some files had thousands of records, I was only getting a few. The command I was using was:

```
Get-ChildItem *.xlsx | Import-Excel
```

What I discovered was that Import-Excel always limits itself to the number of rows it discovers in the first file. My first file had only 30 records, so every subsequent file in the pipeline only imported 30 records.

To confirm it, I did this:

```
Get-ChildItem *.xlsx | Sort-Object -Property Name -Descending | Import-Excel
```

This still didn't import all the records, but it gave me the number of records in the last file. I also noted that I got a lot of blank records, because that last file, while not the longest, was one of the longer ones.

# Steps to Reproduce

First, generate a series of documents with the same columns but different numbers of rows.

```
foreach ($FileId in (1..5)) {
    1..$FileId | ForEach-Object {
        [PSCustomObject]@{
            FileId = $FileId
            FieldValue = Get-Random
        }
    } | Export-Excel ".\File$FileId.xlsx"
}
```

The above script creates 5 files numbered 1 through 5. The first file has one record, the second has two, and so on. The `FileId` column is a number indicating which file it came from.

Now, import them in a pipeline in ascending order. I'm using `Group-Object -Property FileId -NoElement` to quickly count the number of records from each file:

```
Get-ChildItem *.xlsx |
    Sort-Object -Property Name |
    Import-Excel |
    Group-Object -Property FileId -NoElement
```

And I get this output:

```
Count Name
----- ----
    1 1
    1 2
    1 3
    1 4
    1 5
```

If I try it again and *reverse* the order:

```
Get-ChildItem *.xlsx |
    Sort-Object -Property Name -Descending |
    Import-Excel |
    Group-Object -Property FileId -NoElement
```

I get this:

```
Count Name
----- ----
   10
    1 1
    2 2
    3 3
    4 4
    5 5
```

It did get all the data since this method happens to import the longest file (a coincidence of how we generated the data files), but see that it also imported 10 records with no value for `Name`. Import-Excel found the first file had 5 records, and then imported 5 records for every file.

The bad part of this is that this behavior is totally silent, and `Import-Csv` doesn't behave this way. If I didn't notice that the data was orders of magnatude too small, I'd have missed that data was lost.

# Workaround

The workaround I have found is to do this:

```
Get-ChildItem *.xlsx |
    Sort-Object -Property Name |
    ForEach-Object { Import-Excel $_ } |
    Group-Object -Property FileId -NoElement
```

Which gets me the correct results:

```
Count Name
----- ----
    1 1
    2 2
    3 3
    4 4
    5 5
```

**Comment by AikenBM** [comment]
@stahler That might be what the help says, but that's not how the command is written.

Check: https://github.com/dfinke/ImportExcel/blob/master/Public/Import-Excel.ps1#L10

It's clearly `[string[]]$Path`.

You can even check introspection:

```
Get-Command -Name Import-Excel |
    Select-Object -ExpandProperty ParameterSets |
    ForEach-Object {
        $ParameterSetName = $_.Name
        $_.Parameters |
            Where-Object { $_.ValueFromPipeline -eq $true } |
            Select-Object -Property @{n='ParameterSetName';e={$ParameterSetName}}, @{n='ParameterName';e={$_.Name}}, ValueFromPipeline, ParameterType
    }
```

I get:

```
ParameterSetName ParameterName ValueFromPipeline ParameterType
---------------- ------------- ----------------- -------------
PathC            Path                       True System.String[]
PathB            Path                       True System.String[]
PathA            Path                       True System.String[]
```

Even if that weren't the case, I just don't find it credible that the intended design was to only allow one file at a time to pipeline in. If accepting pipeline input to -Path cause it to break when the pipeline has multiple items, why does -Path accepting pipeline input _at all_? The whole purpose of the pipeline is to construct a sequence which affects every object in the pipeline.

As I see it, the command should either:

1. It should not accept pipeline input, which would be a breaking change.
2. It should handle multiple files coming through the pipeline without silently truncating or generating data.

**Comment by dfinke** [comment]
New version with the fix is published. Thanks for reporting it.

https://github.com/dfinke/ImportExcel/releases/tag/v7.5.0
