### ISSUE TITLE
Adding formulas to a range

### ISSUE THREAD

**Issue by Gtoml** [dfinke/ImportExcel#1175]
I have created a package with Import-Excel.  It has two worksheets (VMs, BU Tags).  Within the script, I have opened the package and create an additional column  (at J1).  I am wanting to to insert a formula within the range of J2:J.  This will be a Vlookup formula to test if the Backup Tag (column E) is valid.  The values are on the worksheet Backup Tags.  I have tried several iterations of the formula and not working.   The formula works if I simply copy it into the cell (and copy/paste it down).  Obviously you want everything automated.  Here is the formula that works when copied into the cell.

=IF(ISNA(VLOOKUP(E2,'Backup Tags'!A2:A5,1,FALSE)),"No","Yes")

Here is what I have tried with the results:

`Set-Format -Address $VMSheet.Cells["J2:J"] -Formula "=IF(ISNA(VLOOKUP(E2,'Backup Tags'!A2:A5,1,FALSE)),"No","Yes")"`
Result - A positional parameter cannot be found that accepts argument 'No,Yes)'.

`Set-Format -Address $VMSheet.Cells["J2:J"] -Formula "=IF(ISNA(VLOOKUP(E2,'Backup Tags'!A2:A5,1,FALSE)),""No"",""Yes"")"`
Result - It will run, however, when I open the xlsx file, it claims that there is corruption and it will try and clean it.  It appears that it removes the values/formula from the column.

Now, I can remove or comment the line out and the script runs perfectly; minus this bit of course.  

Any help will be greatly appreciated.

**Comment by dfinke** [comment]
Hmm, don't know. Below is another way, doubt it will work, but worth a try.

You could try renaming the corrupted xlsx ext to zip, and then unzip it.
Using your favorite editor, open the XML files, and search for the VLOOKUP formula that got added.

Could provide a clue to why the formatted string causes the corruption.

```powershell
Set-Format -Address $VMSheet.Cells["J2:J"] -Formula '=IF(ISNA(VLOOKUP(E2,''Backup Tags''!A2:A5,1,FALSE)),"No","Yes")'
```

**Comment by Gtoml** [comment]
`Set-Format -Address $VMSheet.Cells["J2:J"] -Formula '=IF(ISNA(VLOOKUP(E2,''Backup Tags''!A2:A5,1,FALSE)),"No","Yes")'
Well, my thinking with the range is j2:j for the entire column of data based upon some of your examples in videos where you specifiy j:j for the range to select all (I thought I saw that).  Well, I  Cant really provide a static range in that each time the script is run, it could/will have different number of rows.  What would be the appropriate way to select the entire range?

**Comment by dfinke** [comment]
Yeah `j:j` selects the entire column. I've never tried `j2:j`, it may work.

You can print and work with `$VMSheet.Dimension` to get figure out total rows for the entire sheet.

May be a good starting point.

```
Start   : OfficeOpenXml.ExcelCellAddress
End     : OfficeOpenXml.ExcelCellAddress
Table   : 
Address : A1:D10
IsName  : False
Rows    : 10
Columns : 4
```

**Comment by Gtoml** [comment]
Alright, I found the issue and a workaround.  Got the formula to work.  
`Set-ExcelRange -Worksheet $VMsheet -Range j2i:j$RowsBackupTags -Formula "= IF(ISNA(VLOOKUP(E`$$VMi,'BackupTags'!A`$2:A`$$RowsBackupTags,1,FALSE)),""No"",""Yes"")"`

Using the above formula, it would truncate the lookup range.    However, if I -Range to a j2:j2 (the first row in the sheet), the formula would work great.  I then set the -Range to j2:j3.  Still failed.  So I guessed that there was an issue with applying this a a range.  So I came up with this to loop thru the rows.  Seems to be working.  Even added another lookup (will be four).   Have to say, that this module is a game changer.   

```
# Rows counts
$RowsVMs = $VMsheet.Dimension.Rows
$RowsBackupTags = $BackupSheet.Dimension.Rows
$RowsAppTags = $AppsSheet.Dimension.Rows

#Lookup Forulas 
$VMi = 2
Do {
    Write-Host "Row $VMi"
    Set-ExcelRange -Worksheet $VMsheet -Range j$VMi:j$VMi -Formula "= IF(ISNA(VLOOKUP(E`$$VMi,'BackupTags'!A`$2:A`$$RowsBackupTags,1,FALSE)),""No"",""Yes"")" 
    Set-ExcelRange -Worksheet $VMsheet -Range k$VMi:k$VMi -Formula "= IF(ISNA(VLOOKUP(F`$$VMi,'App Tags'!A`$2:A`$$RowsAppTags,1,FALSE)),""No"",""Yes"")"
    $VMi++
}
until ($VMi-gt $RowsVMs)
```

**Comment by dfinke** [comment]
> Have to say, that this module is a game changer

Thank you. Yes, this module has been fun to build, so much you can do with it, and more to come.

I don't fully get how you solved it. Looks like you are programmatically handling the cells the formula needs to work on, rather than depending on Excel to figure it out?

Also, seems like you added a space after the `=` sign, is that required for the solution?

**Comment by Gtoml** [comment]
Not sure about the = sign.  I didnt cognitively change it. But it is clear I did change it .   Yeah, it was weird. While I would rather Excel figure it out, however, not so much of a show stopper.   Truth be told, I had to move onto to other things.  I will take a look more at it a little later.  But for now, the work around is working with no sign of performance issues (at least on a couple hundred rows).  Would be interested to see how it works on larger data sets.   My thinking is with the formula syntax, possibly with the escape characters usage.  Still learning here.  

Speaking of still learning, I have one last thing for now I came across.  The original data I use to create the xlsx package has columns out to column I.  I also apply -Autofilter as well -ConditionalText (to columns J and K).  Later,  I add additional four columns (J - M) using the Set-Format command later after opening the package.  This columns of cells contains the formula I was working with above to validate the data in the original data set.  Interesting thing is that the Conditional Text parameter worked perfectly on the newly created Columns; however, the Autofilter did not carry over to the new columns.  The Autofilter stopped at the original columns of the imported data set.  How can I get the Auto filter to extend to the new columns I created. 

```
Import-CSV $CSV | Export-Excel -Worksheet "VMs" -AutoSize -path $file -BoldTopRow -FreezeTopRow -AutoFilter -ConditionalText $(
    New-ConditionalText No -Range j:j  -BackgroundColor Yellow
    New-ConditionalText No -Range k:k  -BackgroundColor Yellow
)
```

```
# Additional Headers
Set-Format -Address $VMSheet.Cells["J1"] -HorizontalAlignment Right -Bold -Value "BackUp Tag Valid" -AutoSize
Set-Format -Address $VMSheet.Cells["K1"] -HorizontalAlignment Right -Bold -Value "App Tag Valid" -AutoSize 
Set-Format -Address $VMSheet.Cells["L1"] -HorizontalAlignment Right -Bold -Value "Bus Unit Tag Valid" -AutoSize 
Set-Format -Address $VMSheet.Cells["M1"] -HorizontalAlignment Right -Bold -Value "Organization Tag Valid" -AutoSize 
```

**Comment by MartinParis** [comment]
@Gtoml I see your using VLOOKUP, did you already check if XLOOKUP would make it easier?
https://support.microsoft.com/en-us/office/xlookup-function-b7fd680e-6d10-43e6-84f9-88eae8bf5929

BTW, I like your no bullshit solution of just adding the formulas to all cells :-).

**Comment by dfinke** [comment]
@Gtoml, yeah some features of Excel are when the sheet is opened, they get applied. For the `Filter`, I have not tried that scenario. In a recent version I added `Enable-ExcelAutoFilter`. Works on an entire sheet. The scenario I solved for was using `Open-ExcelPackage` and then `Enable-ExcelAutoFilter` on the sheets I wanted. I have not tried it on a sheet that already had `filters` on. Please try and let me know.
