### ISSUE TITLE
Excel sheet linked to Sharepoint Data set to auto refresh on open does not refresh

### ISSUE THREAD

**Issue by delioden** [dfinke/ImportExcel#1176]
Good morning

I have an excel spreadsheet which has a connection to sharepoint and connection is set to refresh on open.  However when using the import-excel module it does not refresh.  Is this the intended behaviour? or have I missed something

**Comment by dfinke** [comment]
Good question. I don't use sharepoint. The `Import-Excel` function does not "load" the spreadsheet, so it cannot refresh it. I have not looked into if that is possible.

**Comment by delioden** [comment]
Thank you for replying.

Yeah I did think that but I thought I would ask.

I cant use COM to open the xls beforehand and save.   Unsure where to go on this ☹

**Comment by dfinke** [comment]
I'd post the question on https://stackoverflow.com/
