### ISSUE TITLE
Question: Is there support for setting the chart style?

### ISSUE THREAD

**Issue by Fragmachine** [dfinke/ImportExcel#1177]
Hi,
When creating charts it would be nice if one could set the chart style, is this possible? 
Thanks for this great PowerShell module!
![image](https://user-images.githubusercontent.com/36921966/166982894-770bb949-8917-4973-957a-d3eaa96f8b0d.png)

**Comment by dfinke** [comment]
I will investigate. Please could you post sample data and a script.

**Comment by Fragmachine** [comment]
Sure, here's one of the commands lines I've been trying things out with

`PS> $trigdef = New-ExcelChartDefinition -Title "Trigonometric Functions" -XAxisTitleText "x (deg)" -YAxisTitleText "Amplitude" -XRange 'x' -YRange 'SinX','CosX' -SeriesHeader 'sin(x)','cos(x)' -ChartType line  -XAxisTitleSize 12 -YAxisTitleSize 12 -TitleSize 14 -XMajorUnit 45 -XMinorUnit 10 -YMaxValue 1 -YMinValue -1
PS> -180..180 | % {[pscustomobject]@{x=$_;SinX=[math]::Sin(2*$_*[math]::pi/360);CosX=[math]::Cos(2*$_*[math]::pi/360)}} | Export-Excel -AutoNameRange -ExcelChartDefinition $trigDef`

Would be cool if it was possible to add a new argument like this `New-ExcelChartDefinition -ChartStyle 3`. Not sure if it's relevant but I found this [link](https://docs.microsoft.com/en-us/javascript/api/excel/excel.chart?view=excel-js-preview#excel-excel-chart-style-member) that hints at this capability being exposed.

**Comment by dfinke** [comment]
`EPPlus` is used to create the xlsx file. Need to see if `-ChartStyle` is implemented and go from there

**Comment by Fragmachine** [comment]
Turned out to be tricky? I did try your suggestion but no dice unfortunately. I'll survive :-)
