### ISSUE TITLE
The '-SeriesHeader' argument fails to set the name in certain scenarios. 

### ISSUE THREAD

**Issue by Fragmachine** [dfinke/ImportExcel#1178]
Hi,

I found an issue when testing out the API. When running the below I end up with the default series name and not 'sin(x)'.

`PS> $trigdef = New-ExcelChartDefinition -Title "Trigonometric Functions" -XAxisTitleText "x (deg)" -YAxisTitleText "Amplitude" -XRange 'x' -YRange 'SinX' -SeriesHeader 'sin(x)' -ChartType line  -XAxisTitleSize 12 -YAxisTitleSize 12 -TitleSize 14 -XMajorUnit 45 -XMinorUnit 10 -YMaxValue 1 -YMinValue -1
PS> -180..180 | % {[pscustomobject]@{x=$_;SinX=[math]::Sin(2*$_*[math]::pi/360)}} | Export-Excel -AutoNameRange -ExcelChartDefinition $trigDef`

![image](https://user-images.githubusercontent.com/36921966/167103839-18eb21f4-13ea-443c-9ca5-cb71ff71293d.png)

I can work around this by adding a dummy entry to the custom object,

`PS> -180..180 | % {[pscustomobject]@{x=$_;SinX=[math]::Sin(2*$_*[math]::pi/360);dummy=$null}} | Export-Excel -AutoNameRange -ExcelChartDefinition $trigDef`

![image](https://user-images.githubusercontent.com/36921966/167104389-153375da-92b1-497f-9c7b-2ea2074f0c39.png)

**Comment by dfinke** [comment]
Thanks, will take a look

**Comment by Fragmachine** [comment]
Did you manage to reproduce this? Or did I not use the API correctly?

**Comment by dfinke** [comment]
@Fragmachine just a data point.

Removing `-Tablename` with no `dummy` entry solves this.
Need to investigate this.

Looks like the PS code is just setting properties. My be a side effect of the interaction.

```powershell
$xlfilename = '.\badlegend.xlsx'
Remove-Item $xlfilename -ErrorAction SilentlyContinue

# Bad Legend
$trigdef = New-ExcelChartDefinition -Title "Trigonometric Functions" -XAxisTitleText "x (deg)" -YAxisTitleText "Amplitude" -XRange 'x' -YRange 'SinX' -SeriesHeader 'sin(x)' -ChartType line -XAxisTitleSize 12 -YAxisTitleSize 12 -TitleSize 14 -XMajorUnit 45 -XMinorUnit 10 -YMaxValue 1 -YMinValue -1 

-180..180 | ForEach-Object { 
    [pscustomobject]@{x = $_; SinX = [math]::Sin(2 * $_ * [math]::pi / 360) }
} | Export-Excel -AutoNameRange -ExcelChartDefinition $trigDef -Path $xlfilename -AutoFilter -Show #-TableName TestData -Show
```

**Comment by dfinke** [comment]
@Fragmachine this works.  Using the named range, it does not include the "Header".  I need to look at `-AutoNameRange ` to see if it can be made to include the data and the heading when it is created, and then consider the impact if it can.


```powershell
$xlfilename = '.\badlegend.xlsx'
Remove-Item $xlfilename -ErrorAction SilentlyContinue

$trigdef = New-ExcelChartDefinition `
    -Title "Trigonometric Functions" `
    -XAxisTitleText "x (deg)" `
    -YAxisTitleText "Amplitude" `
    -XRange 'x'  `
    -SeriesHeader 'sin(x)' `
    -ChartType line `
    -XAxisTitleSize 12 `
    -YAxisTitleSize 12 `
    -TitleSize 14 `
    -XMajorUnit 45 `
    -XMinorUnit 10 `
    -YMaxValue 1 `
    -YMinValue -1 

$data = -180..180 | ForEach-Object { 
    [pscustomobject]@{x = $_; SinX = [math]::Sin(2 * $_ * [math]::pi / 360) }
}

$trigdef.YRange = "B1:B{0}" -f ($data.Count + 1)
$data | Export-Excel -AutoNameRange -ExcelChartDefinition $trigDef -Path $xlfilename -AutoFilter -Show -TableName TestData 
```
