### ISSUE TITLE
Question - Add Colum on imported table

### ISSUE THREAD

**Issue by Panchistiko** [dfinke/ImportExcel#1179]
Hi. New to ExportExcel (and little experience with PS). I have an already written script that export data queried from SQL (data stored in $dt). Data comes with a few columns, and I need to add some more columns with headers but no data to the right (data will be provided manually afterwards). How and where do I insert those columns?

`$dtExcel = $dt  | select * -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors  | Export-Excel -Path $FilesPath\$SheetName.xlsx -BoldTopRow -AutoSize -WorksheetName $SheetName  -CellStyleSB {param($SheetName) $SheetName.Cells["1:1"].Style.HorizontalAlignment="Center"} `

Thank you!

**Comment by dfinke** [comment]
Look at the `-Property` parameter, add an `*` to select all the properties, then use the `@{name='';expression={}}` syntax to add the properties you need. Keep the `-ExcludeProperty` to remove unwanted ones.

```powershell
$xlfilename = './test.xlsx'
Remove-Item $xlfilename -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
OrderId,Category,Sales,Quantity,Discount
1,Cosmetics,744.01,07,0.7
2,Grocery,349.13,25,0.3
3,Apparels,535.11,88,0.2
4,Electronics,524.69,60,0.1
5,Electronics,439.10,41,0.0
6,Apparels,056.84,54,0.8
7,Electronics,326.66,97,0.7
8,Cosmetics,017.25,74,0.6
9,Grocery,199.96,39,0.4
10,Grocery,731.77,20,0.3
"@ 

$data | Select-Object -ExcludeProperty Sales -Property *, @{name = 'Test1'; Expression = { '' } }, @{name = 'Test2'; Expression = { '' } } | Export-Excel $xlfilename -AutoNameRange -AutoSize -Show
```

**Comment by Panchistiko** [comment]
Wow! Thank you very much!
