### ISSUE TITLE
PivotTable - Report  Layout

### ISSUE THREAD

**Issue by daviscraigs** [dfinke/ImportExcel#1182]
I am looking to change the Pivot table layout from the default "show in compact form" to "show in tabular form".  Additional I would like to be able to set Subtotals to "Do not show subtotals".  Sample Excel file attached,

[ImportExcelPivotTableLayout.xlsx](https://github.com/dfinke/ImportExcel/files/8647107/ImportExcelPivotTableLayout.xlsx)

**Comment by dfinke** [comment]
Check the `New-PivotTableDefinition` function. I believe there should be an example in the https://github.com/dfinke/ImportExcel/tree/master/Examples. Or clues in the unit `__tests__`

**Comment by daviscraigs** [comment]
> 

I see the option for PivotTableStyle, but not for Layout

**Comment by dfinke** [comment]
Don't know off the top of my head, may be `-NoTotalsInPivot`. If not, you can create Pivot table `Add-PivotTable`, use `-PassThru` to get to the object model. Not sure it is granular enough, or if what you're actually looking for has been exposed.

**Comment by dbrennand** [comment]
I tried the solution [here](https://stackoverflow.com/questions/9464047/how-to-set-pivot-table-report-layout-to-tabular-in-epplus) but I couldn't get it working.

```pwsh
"PivotTable:"
$ExcelPackage.$WorkSheetName.PivotTables.Compact
$ExcelPackage.$WorkSheetName.PivotTables.CompactData
$ExcelPackage.$WorkSheetName.PivotTables.Indent
$ExcelPackage.$WorkSheetName.PivotTables.RowGrandTotals
$ExcelPackage.$WorkSheetName.PivotTables.UseAutoFormatting
$ExcelPackage.$WorkSheetName.PivotTables.ShowMemberPropertyTips
$ExcelPackage.$WorkSheetName.PivotTables.DataOnRows

"Fields:"
$ExcelPackage.$WorkSheetName.PivotTables.Fields.Outline
$ExcelPackage.$WorkSheetName.PivotTables.Fields.Compact
$ExcelPackage.$WorkSheetName.PivotTables.Fields.ShowAll
$ExcelPackage.$WorkSheetName.PivotTables.Fields.SubtotalTop

PivotTable:
False
False
0
False
True
False
False

Fields:
False
False
...
False
```

My PivotTable is still not in Tabular form 😞

**Comment by dbrennand** [comment]
Hmmm. I'm also reading about someone trying to get a tabular layout using [Closed XML](https://stackoverflow.com/questions/51192967/closed-xml-setting-pivot-table-report-layout-to-tabular) by setting `ClassicPivotTableLayout` to true. Looking a bit deeper `ClassicPivotTableLayout` sets the `GridDropZones` value: https://github.com/ClosedXML/ClosedXML/pull/199/files

However, my PivotTable already has the `GridDropZones` set to true 😞

**Comment by dbrennand** [comment]
Hi @daviscraigs 

You may find my latest comment in #1196 useful 🙂
