### ISSUE TITLE
Formula not calculated when opening Sheet after creation of the file.

### ISSUE THREAD

**Issue by MartinParis** [dfinke/ImportExcel#1183]
Using one of the pre-made examples with an extra row.

`Remove-Item ".\Data\functions.xlsx" -ErrorAction SilentlyContinue

$(
    New-PSItem 12001 Nails  37  3.99 =C2*D2 @("ID", "Product", "Quantity", "Price", "Total")
    New-PSItem 12002 Hammer  5 12.10 =C3*D3
    New-PSItem 12003 Saw    12 15.37 =C4*D4
    New-PSItem 12010 Drill  20  8    =C5*D5
    New-PSItem 12011 Crowbar 7 23.48 =C6*D6
    New-PSItem 12011 TestCount 1 1 "=COUNTA(UNIQUE(B2:B6))"
) | Export-Excel ".\Data\functions.xlsx"-AutoSize`

The counta formula shows 1 when opening the sheet. The cells above are calculated.
When doing F2 and Enter it calculates the correct number.
What should I do to make sure the formula is calculated when opening the Excel file?
Or is this a bug?

Above is the simplified version of this actual code.
`$excelPackage.Workbook.Worksheets['Report'].Cells['A16'].Formula = "=IF(Delta8!A2=""No Delta"",0,COUNTA(UNIQUE(RemovedPolicies[assignmentName]&RemovedPolicies[assignmentScope]&RemovedPolicies[policyName])))"`
which has the same behaviour.

**Comment by dfinke** [comment]
On the `Export-Excel` try the `-Calculate` switch.

**Comment by MartinParis** [comment]
Hi, I forgot to mention I did try that, it did not make a difference.

**Comment by dfinke** [comment]
Ok, not sure, `calculate` is a best effort. Not much control over that. I will try to take a look at it.

**Comment by MartinParis** [comment]
This is now solved as well. Solution is the prefix of the Formula with `_xlfn.`
First row below does not get calculated when opening the sheet, the second row does get calculated.
`New-PSItem 12011 TestCount 1 1 "=COUNTA(UNIQUE(B2:B6))"`
`New-PSItem 12011 TestCountAuto 2 2 "=COUNTA(_xlfn.UNIQUE(B2:B6))"`
    
Also see #1154
