### ISSUE TITLE
Workbook damaged by adding Worksheets after adding Pivot Table

### ISSUE THREAD

**Issue by markdowd** [dfinke/ImportExcel#1185]
$data = ConvertFrom-Csv @"
Region,Date,Fruit,Sold
North,1/1/2017,Pears,50
South,1/1/2017,Pears,150
East,4/1/2017,Grapes,100
West,7/1/2017,Bananas,150
South,10/1/2017,Apples,200
North,1/1/2018,Pears,100
East,4/1/2018,Grapes,200
West,7/1/2018,Bananas,300
South,10/1/2018,Apples,400
"@ | Select-Object -Property Region, @{n = "Date"; e = {[datetime]::ParseExact($_.Date, "M/d/yyyy", (Get-Culture))}}, Fruit, Sold

$xlfile = "$env:temp\pivoterror.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$excel = $data | Export-Excel $xlfile -PassThru -AutoSize -TableName FruitData

$pivotTableParams = @{
    PivotTableName  = "ByRegion"
    SourceWorkSheet = $excel.Sheet1
    PivotRows       = @("Region", "Fruit", "Date")
    PivotData       = @{'sold' = 'sum'}
    PivotTableStyle = 'Light21'
    GroupDateRow    = "Date"
    GroupDatePart   = @("Years", "Quarters")
}

$pt = Add-PivotTable @pivotTableParams -ExcelPackage $excel -PassThru
#$pt.RowHeaderCaption ="By Region,Fruit,Date"
$pt.RowHeaderCaption = "By " + ($pivotTableParams.PivotRows -join ",")

Close-ExcelPackage $excel -Show

1..10 | Export-Excel  $xlfile -WorksheetName 'Log' -Show

\# This final step doesn't issue a warning, but opening the workbook throws an error
\# 'We found a problem with some content in...'
\# If we answer 'yes' to recovery it makes the followiing repairs, emptying the pivot table worksheet
\# - Removed Feature: PivotTable report from /xl/pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)
\# - Removed Feature: PivotTable report from /xl/pivotTables/pivotTable1.xml part (PivotTable view)
\# - Removed Records: Workbook properties from /xl/workbook.xml part (Workbook)

\# Adding the extra sheets before 'Add-PivotTable' works fine, but is aesthetically not pleasing

**Comment by dfinke** [comment]
Thanks for the detail. Yeah, the pivot creation, I believe it is using the same code path in the PS (need to double check). So if use the export, export -passthru, open/close and then do "pivot table work", it'll have issues. Have never tested that scenario, I think it may be something with the pivot cache, at the DLL level. Need to dig deeper to see if it is the PS or DLL.

**Comment by dfinke** [comment]
@markdowd could I ask a favor to test something. Create the new pivot table in a second xlsx, then use `Copy-ExcelWorksheet` to copy it to the first. Curious if that corrupts things. 

To make it a more "accurate" test. copy the first xlsx, without the pivot (or delete the pivot sheet), create the pivot table amd use `Copy-ExcelWorksheet` to copy the pivot sheet the first.

**Comment by dfinke** [comment]
@markdowd I removed the `-TableName FruitData` and don't get the corruption.

Can you confirm?

**Comment by markdowd** [comment]
> @markdowd I removed the `-TableName FruitData` and don't get the corruption.
> 
> Can you confirm?

Confirmed. Doesn't like that source as a table. Excel itself doesn't mind when I do it manually, so must be.

**Comment by dfinke** [comment]
Thanks for confirming. Good news is after more testing it looks like it is *not* the DLL. Bad news is, went to a slightly older version of ImportExcel and what corrupts the xlsx in v7.5 works there. Need to do more tests, then isolate when and what broke, and build tests to guard against it.

**Comment by dfinke** [comment]
Looks like there was a regression in the DLL. Moved to EPPlus v4.5 for ImportExcel v6.5. 

No good solutions for this. I was able to test downgrading to EPPlus v4.0 and the tests passed for ImportExcel, but I'm not comfortable with doing that either.

**Comment by markdowd** [comment]
Who authors the DLL? Maybe raise it with them for a fix in a future build? In the meantime, I'll continue to use the workaround.

Thanks.

**Comment by dfinke** [comment]
@markdowd They have moved to a paid license and do not support the old version. Plus, they fixed many things which meant they had to introduce a lot of breaking changes.

I have no plans to move to that version or figure out/pay for the license.

https://github.com/EPPlusSoftware/EPPlus

**Comment by markdowd** [comment]
Fair enough :)
