### ISSUE TITLE
Suggestion: Remove unnecessary files when publishing to the gallery

### ISSUE THREAD

**Issue by ThePoShWolf** [dfinke/ImportExcel#1187]
I was packaging ImportExcel for use in a pipeline and I found that out of the total size of 26MB installed, 22.5MB are images.

I can understand the usefulness of having the README with all of the referenced images, but it seems wasteful considering how easy it is to find the GitHub repository. I would consider removing all unnecessary files when publishing the package.

It looks like it might be as easy as updating the FileList in the `.psd1` [here](https://github.com/dfinke/ImportExcel/blob/e2053e499821771a937571fe009a8105ba8714f4/ImportExcel.psd1#L118). However, I have additional files in the installed module beyond what are listed in the FileList of the `.psd1`. So maybe not, but either way I'd be happy to be the one to dig into this more if this was of interest.

As a workaround for my use case, I'm just manually deleting the files and re-packaging it. Works just fine for me.

**Comment by dfinke** [comment]
Thanks @ThePoShWolf good point, early on it made sense, not it should be pruned. I'll take a look. I think it is my side when I prep it to be published to the gallery, need to strip that beforehand.

**Comment by ThePoShWolf** [comment]
Awesome! I'm looking forward to the new version getting published. Thank you! 😄

**Comment by dfinke** [comment]
I will publish it soon. After, let me know if additional things ought to be excluded.

**Comment by dfinke** [comment]
Published - https://github.com/dfinke/ImportExcel/releases/tag/v7.5.3
