### ISSUE TITLE
Feature Discussion: Write-Clipboard as opposite to Read-Clipboard

### ISSUE THREAD

**Issue by Callidus2000** [dfinke/ImportExcel#1189]
Hi,
reading Data from the clipboard copied from Excel is great, but what about a function reverse?

For example I'm using code like this
```Powershell
Get-Process | ConvertTo-Csv -Delimiter `t -NoTypeInformation | Set-Clipboard
```
if I just want to copy something quickly to an already open Excel Worksheet.
```Powershell
Get-Process | Write-Clipboard
```
would be a nice shortcut, maybe combined with the Power of Export-Excel.

Above manual way is only ok for simple datatypes, for getting useful output from e.g. arrays additional steps are needed....

**Comment by dfinke** [comment]
Thanks. The idea is interesting. What format would the `Write-Clipboard` default to? Would it need to handle other formats? 

As you show, this is probably good enough to start with.
`ConvertTo-Csv -Delimiter `t -NoTypeInformation | Set-Clipboard`

**Comment by Callidus2000** [comment]
Hi,
sorry for the late answer, was quite busy...
What Do you mean by "format"?

What I'm missing "The manual Way" is the option -NoNumberConversion from Export-Excel. That's mainly because I'm currently working on some firewall stuff where IP addresses sometimes are interpreted as numbers....

-Sascha
