### ISSUE TITLE
Export-Excel does not overwrites all the data

### ISSUE THREAD

**Issue by greatwallx2** [dfinke/ImportExcel#119]
When exporting data to an existing Excel file the command overwrites only the number of rows matching the number of items in the input.
For example: 1) The first time the input data consists in 100 rows. Excel file is created with 100 rows.
2) The second time the input data consists in 20 rows. When exporting this to the same file as before only the first 20 rows are overwritten with the new data. The other 80 rows remain there.

**Comment by greatwallx2** [comment]
The problem is that this excel file has other sheets that compliment the information exported from PS.
Any way I can delete just a sheet or wipe the data from it?

**Comment by dfinke** [comment]
Got it. It sounds like a switch would be useful for Export-Excel.

**Comment by greatwallx2** [comment]
to work around this I create an object with the same columns as the excel file and fill an array with the number of rows currently in the excel file, then export the array

$CurrentData = Import-Excel Report.xlsx -WorkSheetname "Sheet1"
if ($CurrentData.count -gt 0){
    $BlankItem = New-Object -TypeName psobject -Property @{"Column1"=$null;'Column2'=$null;'Column3'=$nul}
    $Blank=@()
    1..$CurrentData.count | %{$Blank+=$BlankItem}
    $Blank | Export-Excel Report.xlsx -WorkSheetname "Sheet1"
}

Somewhat related to this, if I use the -IncludePivotTable switch when there is already a pivot table from a previous run it breaks the pivot table.
I know that I should remove the includepivottable on subsecuent runs, but it would be great if the module either overwrites the current table or throws a warninig when there already one.

BTW thanks for this great module and keep up the good work :)

**Comment by dfinke** [comment]
Thanks!

Yup, unfortunately that is a limitation in the C# DLL. I don't own that code and have not debugged it enough to see if that can be fixed.
