### ISSUE TITLE
SharePoint files

### ISSUE THREAD

**Issue by esbranson** [dfinke/ImportExcel#1193]
It would be useful to be able to open SharePoint and other files served over HTTP.

**Comment by dfinke** [comment]
Yes. I believe the target endpoint needs to serve the xlsx. For example, GitHub doesn't, or it does, and I have not figured out how. The xlsx is a zip, and the libraries the crack it open need to do so it can process the xml.

If that can be figured out with the constraints of EPPlus. Happy to implement.

I have a `Read-Csv` function that knows how to read a string, file, or url https://github.com/dfinke/PSKit/blob/master/ReadCsv.ps1

Would love to add that to this module.
