### ISSUE TITLE
Set color on only cells with values

### ISSUE THREAD

**Issue by owilkins1** [dfinke/ImportExcel#1199]
Hi,

I am currently using this code to produce the below image - 

         
          ` $ws = $excel.Workbook.Worksheets["Sheet1"]
            $totalRows = $ws.Dimension.Rows

            Set-ExcelRange -Worksheet $ws -Range "A1:P1" -BackgroundColor LightBlue -Bold
            Set-ExcelRange -Range $ws.Cells["G2:G$($totalRows)"] -Bold
            Set-ExcelRange -Range $ws.Cells["H2:H$($totalRows)"] -BackgroundColor Maroon -Bold
            Set-ExcelRange -Range $ws.Cells["I2:I$($totalRows)"] -BackgroundColor IndianRed -Bold
            Set-ExcelRange -Range $ws.Cells["J2:J$($totalRows)"] -BackgroundColor LightGoldenrodYellow -Bold
            Set-ExcelRange -Range $ws.Cells["K2:K$($totalRows)"] -BackgroundColor LightYellow -Bold`

![image](https://user-images.githubusercontent.com/88395013/173817689-0c59e741-04c0-4c16-a7c5-7568766efc34.png)

I cannot figure a way of leaving the cells with no data as white/not colored. Could you advise on how you would accomplish this?

Thanks

**Comment by owilkins1** [comment]
Please let me know if it's possible to find a solution in this case or whether I need to rethink the design of the sheet.

Thanks

**Comment by owilkins1** [comment]
Well your link managed to jog an idea in my brain and ended up with a solution that works exactly as I need, ended up being fairly simple!

`Export-Excel -ExcelPackage $excel -AutoSize -ConditionalText $(
                New-ConditionalText -ConditionalType ContainsBlanks -PatternType None
 )`

**Comment by dfinke** [comment]
Thanks for the question, and the follow up.
