### ISSUE TITLE
I'm getting an error with AutoFitColumns=$true

### ISSUE THREAD

**Issue by marthektheman** [dfinke/ImportExcel#12]
Export-Excel : A parameter cannot be found that matches parameter name 'AutoFitColumns'.
At line:1 char:24
+ $vmlist | Export-Excel @p -IncludePivotTable
+                        ~~
    + CategoryInfo          : InvalidArgument: (:) [Export-Excel], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Export-Excel

**Comment by marthektheman** [comment]
forget it I found it in the ImportExcel.psm1:  It should be AutoSize :)

[Switch]$AutoSize
New hash for splat:

$p = @{    
       Path = $OUTFILE
       #doesn't work with Excel 2007
       NoClobber = $true
       AutoSize = $true
       Show = $true
      }

**Comment by dfinke** [comment]
Love it when issues get opened an closed and I didn't see any of it till it was over :)

**Comment by marthektheman** [comment]
Thanks for the cool PSM.  I’m working through it J

**Comment by dfinke** [comment]
Much appreciated. The feedback is awesome. Looking forward to more.
