### ISSUE TITLE
Compare two column values based on column pattern

### ISSUE THREAD

**Issue by sheldonhull** [dfinke/ImportExcel#120]
The examples section didn't seem to have something for what I was trying to accomplish. 
I want to compare ColumnName_t to ColumnName_s but all the conditional patterns seem to require more generic formula options. Is there a way to accomplish a column to column comparison based on a pattern?

**Comment by dfinke** [comment]
Great question. Can it be done in Excel proper?

**Comment by sheldonhull** [comment]
Yes. You place the compare formula I believe as $B2 <> $C2
Then you apply that down column. The relative row and column applies then
per row.

Would be pretty cool to do a pattern match or some basic mapping to do
this. Haven't seen anything else that handled this elegantly
