### ISSUE TITLE
Conditional Formatting: Use a formula to determine which cells to format

### ISSUE THREAD

**Issue by kkazala** [dfinke/ImportExcel#1201]
Hi 

Is it possible to add a conditional formatting that is using a formula? 
In the screenshot below I created a rule that compares values in two columns:
![image](https://user-images.githubusercontent.com/22429087/174292364-93fccfc9-4acc-4e99-875c-4ef2ec81298e.png)

But I had no luck configuring it with `Add-ConditionalFormatting`
Should I use `-RuleType  Expression`? 

If this is supported, could you share an example? 
Thank you in advance!
Kinga

**Comment by dfinke** [comment]
Here is a start. I have not played with that feature in either Excel or with the module

The code below does set the conditional formatting, you can see and edit it in Excel. 

Not sure how the `formula` needs to be set up. I tried it manually different ways, it colored cells, but not what I expected.

![image](https://user-images.githubusercontent.com/67258/174305226-c9f425e4-4e8a-4636-9980-749ca597ae17.png)

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfilename = "test.xlsx"
Remove-Item $xlfilename -ErrorAction SilentlyContinue

$excel = $data | Export-Excel $xlfilename -AutoSize -PassThru

Add-ConditionalFormatting -Worksheet $excel.sheet1 -Range "A1:D10" -ConditionValue '=A3="North"' -RuleType Expression -BackgroundColor Cyan

Close-ExcelPackage $excel -Show
```

**Comment by kkazala** [comment]
Thank you @dfinke  for your answer. 
Your code is currently selecting wrong cells, because of the `=A3="North"` rule for the range starting at `A1`
Correcting it to ` `=A1="North"`` generates correct results. Not that it matters so much.
And indeed, it set me in the right direction =)

A summary for anyone looking for the same answer:

To create a formula that compares two cells in the spreadsheet, using Excel UI:
1. select range (column or a table) which should be formatted
![image](https://user-images.githubusercontent.com/22429087/174531215-2102c8b7-4b44-4c26-9114-6592227a8715.png)
2. Select **Conditional Formatting > New Rule**
3. Choose **Use a formula to determine which cells to format** and type `=A2=B2` to compare cells in columns A and B and define formatting
 ![image](https://user-images.githubusercontent.com/22429087/174530797-0e02cf21-7cc1-40ce-af61-aaa3ded56344.png)
_The formula starts at row 2 because the range selected in step 1 start at row 2._

And to do the same (reusing the code above) change the `Add-ConditionalFormatting` command to:
```
Add-ConditionalFormatting -Worksheet $excel.sheet1 -Range "A1:A10" -ConditionValue '=A1=B1' -RuleType Expression -BackgroundColor Cyan`
```

When the excel is generated, it's not yet formatted because the values is columns A and B differ for the selected range (A1:A10).
But change the data to the same values and the cells in column A are formatted:
![image](https://user-images.githubusercontent.com/22429087/174532460-c76bef85-9a56-496e-894a-684bf01597b2.png)

Thanks once again!

**Comment by dfinke** [comment]
@kkazala Great! Would you be up to doing a PR and adding this as an example in this directory? https://github.com/dfinke/ImportExcel/tree/master/Examples/ConditionalFormatting
