### ISSUE TITLE
Copy PivotTable as final report Retaining Formatting (no data linked)

### ISSUE THREAD

**Issue by dokado** [dfinke/ImportExcel#1203]
I'm trying to do a pivot table summary report, but don't want to include the original data. In other words, I want to "unlink" the pivot table from its data source. 

As we know it Excel doesn't have a command to unlink a pivot table, but it does have a flexible Paste Special command.
Problem with that approach if you paste the copy with the Values and Source Formatting command, the pivot table's PivotTable Style formatting is not pasted.

Instead of using Excel's paste special commands, we can use the Office Clipboard to paste the copy of a pivot table values and style formatting. Now we looking to get to Office Clipboard functionality.

Does ImportExcel has an functionality to Copy PivotTable  without hidden data cache  and Retaining Formatting ?

Cheers.

**Comment by dfinke** [comment]
Interesting question, I have not come across that and ImportExcel only works with the xlsx file to read/write. It does not have any UI access features. I suspect this is not doable, and if I come across something, I will post it here.

**Comment by dokado** [comment]
Thank you, Doug, I much appreciate your hard work.

As ImportExcel  can create PivotTables and do formatting/filtering   (FormatCellStyles,PivotTableFilters,PivotTable)
It's might be good to address  Cons of handing over PivotTables : 

1. Security reasons as if we may not want to share the raw data, if it contains sensitive or private information.
2. Size of PivotTables with data linked can be enormous for emailing and should be monitored before hand.
3. PivotTables  doesn’t include calculation options in many instances. That means the collected data must be manually calculated or equations must be manually inputted.

Possible ImportExcel features might be : 
- apart from PivotTables formatting/filtering extend ImportExcel  to include calculation options 
- convert PivotTable to simple list 
- copy PivotTable as final report  without the source data, while preserving all formatting.

Cheers.

**Comment by dfinke** [comment]
Off the top of my head. One thing to consider is, once the Pivot table is created, you should be able to use the Excel programmatic model and copy the resulting Pivot table data to another sheet, then you can delete the sheet with original data, and then delete the sheet with the Pivot table, leaving only "Paste Special Values Only" data.

**Comment by dokado** [comment]
Thank you, Doug.
