### ISSUE TITLE
-UnderLineType parameter is ignored in Set-ExcelColumn

### ISSUE THREAD

**Issue by arychagov4** [dfinke/ImportExcel#1204]
`-UnderLineType` parameter is totally ignored in `Set-ExcelColumn` because it never makes it to the pararmter list for `Set-ExcelRange` consiquent call. It seems adding 'UnderLineType' in array at line 113  would be the fix.

https://github.com/dfinke/ImportExcel/blob/45449650c7f1d6b7fdc2979f883f5d0897a35874/Public/Set-ExcelColumn.ps1#L112-L121

**Comment by dfinke** [comment]
@arychagov4 could you post a simple script how your using it, and repros the issue?

**Comment by dfinke** [comment]
Thanks @arychagov4 for logging this. Will be published shortly.
