### ISSUE TITLE
Hide a worksheet

### ISSUE THREAD

**Issue by WinOpsEngineer** [dfinke/ImportExcel#1205]
How does one hide a worksheet in a work book or a range of cells on a work sheet?

**Comment by WinOpsEngineer** [comment]
Thank worked like a charm!!

**Comment by dfinke** [comment]
@WinOpsEngineer I tried `Set-ExcelColumn -Worksheet $excel.Sheet1 -Column 1 -Hide`. It hides the column, but it then doesn't display in the graph.

**Comment by WinOpsEngineer** [comment]
ok I'm all set with the hide sheet Thanks Doug!

**Comment by dfinke** [comment]
You're welcome, and thank @stahler for answering it.
