### ISSUE TITLE
File name with Wildcards in Open-ExcelPackage

### ISSUE THREAD

**Issue by Alphagorn** [dfinke/ImportExcel#1209]
The problem arises with files that contain, for example, [Test][First]File123.xlsx. Especialy with the brackets.
In your Open-ExcelPackage you use a test-path -Path, which prevents opening these files. 
It would be a good idea to use a test-path -LiteralPath 
I modified the function and I included it in one of my modules which allowed me to troubleshoot.

**Comment by Alphagorn** [comment]
Hello Doug,

I'm using your module and the Open-Excelpackage function with the Power BI API.

I save Power BI spaces and some file names are of the type "[PriorIT][POGS] Solicitations Infogérant.pbix".
However the [] are seen by the Test-Path function as wildcards and returns false with the -Path parameter.
If you use the -LiteralPath parameter the file name is interpreted as it is written and detected.

In your Open-ExcelPackage function, you use the Test-Path with -Path and not with the -LiteralPath parameter.
The error results in the fact that the Export-Excel function correctly created the file of type [xxx][xxx] xxx.pbix
but it cannot be opened by Open-ExcelPackage because it's not detected by the Test-Path.

I changed the function for my needs, but I think it is better to give the possibility 
of having the parameter -Path or -LiteralPath, although in the opening of a specific file we never use wildcards normally

So I changed your function like this:

2 lines from you :
if ($Create -and -not (Test-Path **-Path** $path)) {
        #Create the directory if required.
by:
if ($Create -and -not (Test-Path **-LiteralPath** $path)) {
        #Create the directory if required.

AND

elseif (Test-Path **-Path** $path) {
        if ($Password) { $pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path , $Password }

by:
elseif (Test-Path **-LiteralPath** $path) {
        if ($Password) { $pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path , $Password }


#---------------------------------------------------------
function **Open-ExcelPackage2** {
    [CmdLetBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingPlainTextForPassword", "")]
    [OutputType([OfficeOpenXml.ExcelPackage])]
    param(
        #The path to the file to open.
        [Parameter(Mandatory = $true)]$Path,
        #If specified, any running instances of Excel will be terminated before opening the file.
        [switch]$KillExcel,
        #The password for a protected worksheet, as a [normal] string (not a secure string).
        [String]$Password,
        #By default Open-ExcelPackage will only opens an existing file; -Create instructs it to create a new file if required.
        [switch]$Create
    )
    if ($KillExcel) {
        Get-Process -Name "excel" -ErrorAction Ignore | Stop-Process
        while (Get-Process -Name "excel" -ErrorAction Ignore) {}
    }
    $Path = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
    #If -Create was not specified only open the file if it exists already (send a warning if it doesn't exist).
    if ($Create -and -not (Test-Path **-LiteralPath** $path)) {
        #Create the directory if required.
        $targetPath = Split-Path -Parent -Path $Path
        if (!(Test-Path -Path $targetPath)) {
            Write-Debug "Base path $($targetPath) does not exist, creating"
            $null = New-item -ItemType Directory -Path $targetPath -ErrorAction Ignore
        }
        New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path
    }
    elseif (Test-Path **-LiteralPath** $path) {
        if ($Password) { $pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path , $Password }
        else { $pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path }
        if ($pkgobj) {
            foreach ($w in $pkgobj.Workbook.Worksheets) {
                $sb = [scriptblock]::Create(('$this.workbook.Worksheets["{0}"]' -f $w.name))
                try {
                    Add-Member -InputObject $pkgobj -MemberType ScriptProperty -Name $w.name -Value $sb -ErrorAction Stop
                }
                catch {
                    Write-Warning "Could not add sheet $($w.name) as 'short cut', you need to access it via `$wb.Worksheets['$($w.name)'] "
                }
            }
            return $pkgobj
        }
    }
    else { Write-Warning "Could not find $path" }
}
#---------------------------------------------------------

**Comment by ericfran** [comment]
Hi,
I try to open a Excel file as the Excel file is open ... and receive the following message:
Exception calling ".ctor" with "1" argument(s): "The process cannot access the file 'xxxxxxxx\file.xlsx' because it is being used by another process."

is it not possible to have a -Readonly flag ?

Regards,

**Comment by dfinke** [comment]
@Alphagorn Not going to merge. This "breaks" `Import-Excel da*.xlsx`. Most likely all functions using `Test-Path`, those functions would need to handle both `Path` and `LiteralPath` to get it right.
