### ISSUE TITLE
New-ConditionalText - Find Blank or Null

### ISSUE THREAD

**Issue by amaralma** [dfinke/ImportExcel#121]
First of  all, thanks for your excelent job!
I need to know how to use New-ConditionalText to highlight blank cells inside exported XLSX file, Is it possible?
I've already tryed to use "NotEqual" and "Equal" but, it didn't come the necessary result...

**Comment by dfinke** [comment]
Thanks for logging this. The ability to highlight this is in Conditional Formatting and I have not surfaced it there. I'll take a look.

**Comment by dfinke** [comment]
I'll check this in later. You can enable this by add `,"ContainsBlanks"` at the end of

https://github.com/dfinke/ImportExcel/blob/master/New-ConditionalText.ps1#L18

![image](https://cloud.githubusercontent.com/assets/67258/18450823/92592d2e-7902-11e6-8d87-ad79b462616b.png)

**Comment by amaralma** [comment]
``Thank you so much!
This has solved my issue !
