### ISSUE TITLE
How to read specific cell from Excel file?

### ISSUE THREAD

**Issue by cobalt2727** [dfinke/ImportExcel#1210]
I'm working on an assignment that involves sanitizing and formatting automated output from a very disorganized .XLSX file into something more sane and readable. The problem is, there's no column names at the top (or even conventionally arranged columns), so it's hard to extract data from it.

![image](https://user-images.githubusercontent.com/60624944/177615638-92f15f33-5892-49ed-8847-4e9c8a077c27.png)

How can I return the command of a specific cell? Like, say, I set up a command that determines the word "companies" is on cell (X,Y) - how would I then declare a variable identified as the value of cell (X-1,Y)?

**Comment by cobalt2727** [comment]
Thank you! What's the difference between `Import-Excel` and `Open-ExcelPackage`? Is one just an alias for the other?

**Comment by dfinke** [comment]
Another great question! `Import-Excel` uses 'Open-ExcelPackage`. `Import-Excel` reads a "just the data". `Open-ExcelPackage` gives you access to the "object model" over the Excel file. Functions like `Set-ExcelRange` are PS functions that use that object model to manipulate data, sheets, meta data etc.

Using 'Open-ExcelPackage` you can go as deep as you need to tweak the Excel.

**Comment by cobalt2727** [comment]
Coming back to this, I should probably add (for anyone else trying to figure this out) I ended up accidentally finding another way to output this:
If you have the misfortune of needing to work with a document like I did that has no column headers, you can find specific cells as follows:

First, let's write up a for loop to return each row of the file.
```powershell
$File = "C:\Users\DavidBaszucki\Documents\Report.xlsx"
$ReportSheet = Import-Excel $File -NoHeader

for ($Row = 1; $Row -lt (($FileName | Measure-Object).Count); $Row += 1) {
    Write-Output $FileName[$Row]
}
```
![image](https://user-images.githubusercontent.com/60624944/178538803-40ef68fe-89b2-4443-be91-5d9864e981ce.png)

Interesting.
What if I make it print out Px as a parameter...?

```powershell
for ($Row = 1; $Row -lt (($FileName | Measure-Object).Count); $Row += 1) {
    Write-Output $FileName[$Row].Px #where Px is the column (P1 for A, P2 for B, etc)
 }
 ```
 ![image](https://user-images.githubusercontent.com/60624944/178539655-d1a1eec0-b526-48fa-a91c-9dae6ee472d5.png)

Looks like that actually works!
