### ISSUE TITLE
Adding in formatting to existing file

### ISSUE THREAD

**Issue by LittleMissDBA** [dfinke/ImportExcel#1211]
I fully except this may be a user error.  
[SimplifiedIssueFormattingFiles.txt](https://github.com/dfinke/ImportExcel/files/9072354/SimplifiedIssueFormattingFiles.txt)
I've been using the ImportExcel module to combine results from several files into one.  I have this working, but spotted that the formatting for a couple of columns has gone, and I'm trying to add it back in.  I've managed to find code online, but when I've added it in, it's stopping the first run saving the file, and I don't understand it enough to figure it out.
I've also tried to keep my code as is, and write something else to open the file, loop around all the spreadsheets and format the columns, but again i can't get this to work, appreciate help on either option.
First code block is my original script.
` 
#Loop through each file 
foreach ($file in $files){
                            #Create a filename for the combined result
                            $CombinedFileName = $folderPath + "\All.xlsx" 

                            #Create format for new worksheet -AutoSize -FreezeTopRow -AutoFilter -BoldTopRow
                            $p = @{AutoSize = $true; FreezeTopRow = $true;  AutoFilter = $true; BoldTopRow = $true}
                            $worksheetName = $file.Name

                            #import data from the file 
                            $data = import-excel -path $file -WorksheetName $worksheetToImport 
                            
                            # If the combinedFile doesn't exists, create it
                            if (-not(test-path -path $CombinedFileName)) {
                                                                            write-host "file does not exist"
                                                                            $data |export-excel $CombinedFileName -WorksheetName $worksheetName   @p
                                                                           }
                            
                                #If File Exists add to it 
                                else {

      
                               $data |export-excel $CombinedFileName -WorksheetName $worksheetName -Append @p                           
                                      }

                         }  `
This is my amended script with the formatting added. The "File Does not exist" is causing the error as it cannot save. I've tried a couple of ways to resolve, but with no luck
`
#Loop through each file 
foreach ($file in $files){
                            #Create a filename for the combined result
                            $CombinedFileName = $folderPath + "\All.xlsx" 

                            #Create format for new worksheet -AutoSize -FreezeTopRow -AutoFilter -BoldTopRow
                            $p = @{AutoSize = $true; FreezeTopRow = $true;  AutoFilter = $true; BoldTopRow = $true}
                            $worksheetName = $file.Name

                            #import data from the file 
                            $data = import-excel -path $file -WorksheetName $worksheetToImport 
                            
                            # If the combinedFile doesn't exists, create it
                            if (-not(test-path -path $CombinedFileName)) {
                                                                            write-host "file does not exist"
                                                                            $excel = $data |export-excel $CombinedFileName -WorksheetName $worksheetName   @p -PassThru 

                                                                            $ws = $excel.Workbook.Worksheets[$worksheetName]
                                                                            Set-Excelrange -Worksheet $ws -range "D:D" -NumberFormat 'Short Date' 
                                                                            Set-Excelrange -Worksheet $ws -range "J:J" -NumberFormat 'Short Date' 
                                                                            Close-ExcelPackage $excel -Show
                                                                           }
                            
                                #If File Exists add to it 
                                else {

                                         $excel = $data |export-excel $CombinedFileName -WorksheetName $worksheetName -Append  @p -PassThru 

                                                                            $ws = $excel.Workbook.Worksheets[$worksheetName]
                                                                            Set-Excelrange -Worksheet $ws -range "D:D" -NumberFormat 'Short Date' 
                                                                            Set-Excelrange -Worksheet $ws -range "J:J" -NumberFormat 'Short Date' 
                                                                            Close-ExcelPackage $excel -Show                           
                                      }

                         } `

I'm not sure if it's an issue as such, or just a case of me not understanding how to use it properly.  I've spent a couple of days trying to figure it out, and have tried different approaches.
In its simplest form I want to open an excel file, take each sheet in turn and format a couple of columns.
I could not do this, so I tried adding the format to my script that combines data from multiple excel files into one.  It works but drops the first file.

**Comment by dfinke** [comment]
Thanks. Please could you also post some sample input files and the `All.xlsx` file showing the issue, plus an xlsx showing what you expect.

**Comment by LittleMissDBA** [comment]
I've added some test files, although when i run my original script on the test files the formatting of the dates is kept.  I'm wondering if the action of me opening the excel file to edit the data is clearing the issue.
Normally my files are saved direct from access, and i run the script without opening them.  
This causes the date columns to display as integer fields, rather than dates.

I've tried opening my files and then running the script, and in my real example i still get integer dates.  I'll see if i can generate some test data via access.
[FileB.xlsx](https://github.com/dfinke/ImportExcel/files/9111213/FileB.xlsx)
[FileC.xlsx](https://github.com/dfinke/ImportExcel/files/9111214/FileC.xlsx)
[FileD.xlsx](https://github.com/dfinke/ImportExcel/files/9111216/FileD.xlsx)
[FileE.xlsx](https://github.com/dfinke/ImportExcel/files/9111217/FileE.xlsx)
[AllFormatAdded.xlsx](https://github.com/dfinke/ImportExcel/files/9111218/AllFormatAdded.xlsx)
[AllOriginalScript.xlsx](https://github.com/dfinke/ImportExcel/files/9111219/AllOriginalScript.xlsx)
[FileA.xlsx](https://github.com/dfinke/ImportExcel/files/9111220/FileA.xlsx)
.

**Comment by dfinke** [comment]
Not sure what may be going on. Excel does store dates as "ints". Not sure if when it is generated from Access, Access is doing something to the dates. Does the `Set-Excelrange -Worksheet $ws -range "D:D" -NumberFormat 'Short Date' ` work? Then you're saying after doing that the first sheet is removed?
