### ISSUE TITLE
Set filters for a column

### ISSUE THREAD

**Issue by WinOpsEngineer** [dfinke/ImportExcel#1217]
Is there a way to set filters in a column - see pic
![filters](https://user-images.githubusercontent.com/40338530/178853611-b1412068-dd08-44a2-bf81-b895c7750405.png)
?

**Comment by jhoneill** [comment]
Sadly the filter information doesn't exist until the file is opened in Excel.  It's a contender for most annoying missing feature.

**Comment by WinOpsEngineer** [comment]
OK thanks for the info
