### ISSUE TITLE
doubt about Export-Excel, NumberFormat and Column Width 

### ISSUE THREAD

**Issue by amaralma** [dfinke/ImportExcel#122]
Hi !
My doubt is to know how to use NumberFormat in a specific cell range and also how to set widht of an specific Colum. Both using Export-Excel.

Some Columns has more than 255 characters and others we need to set datetime format!

Thank you so much !

**Comment by dfinke** [comment]
Thank you for the question. 

You need to use `-PassThru` and then the EPPlus object model to set these properties on ranges and columns.

**Comment by amaralma** [comment]
Perfect.
It works fine!

**Comment by stephenmbell** [comment]
Could you elaborate a little on the above response please?  EPPlus object model?  

Thanks

**Comment by dfinke** [comment]
Could you say more about what you are looking for? EPPlus is the DLL that is used in creating the xlsx. You can manipulate the workbook, sheets, cells using it's object model.

**Comment by stephenmbell** [comment]
I am taking a workbook with 26 sheets and splitting it into 26 individual files.  Each sheet in this workbook contains a field "Amount" that is numeric and formatted as a float in the original file.  When I export using the module it exports "3.30" as 3.3.  I am looking for this to export as it is shown in the original file.

I have done this same process using a COM object in the past - but the powershell module is exciting and I love not having the requirement of an excel installation :)
Thanks
steve
