### ISSUE TITLE
Set a value of xlTickMarkNone for MinorTickMark 

### ISSUE THREAD

**Issue by benbozso** [dfinke/ImportExcel#1222]
I have an issue. I import a CSV file and I insert a new chart based from the values. But i don't find a way to set the MinorTickMark to  xlTickMarkNone. It has the value of  xlTickMarkCross by default for MajorTick and for MinorTickMark as well.
I see parameter "XMajorUnit" and "XMinorUnit" but this not for this feature.

the script:
```
# Import CSV to Excel
$xl = Import-csv "$path.csv" -Delimiter "," | Export-Excel "$path.xlsx" -WorkSheetname Data -PassThru

# Sheet
$DataSheet = $xl.Workbook.Worksheets["Data"]
$lastRow = $DataSheet.Dimension.Rows
$lastCol = $DataSheet.Dimension.Columns

$seriesNames = @()
$yrange = @()
For($i=2; $i -le $lastCol; $i++)
{
	$seriesNames += $DataSheet.Cells[1,$i].Value
	$yrange += "Data!" + $DataSheet.Cells[2,$i].Address + ":" + $DataSheet.Cells[$lastRow,$i].Address
}
$xrange = "Data!A2:A$lastRow"

# Chart
$ChartSheet = Add-Worksheet -ExcelPackage $xl -WorkSheetname "Chart"
Add-ExcelChart -Worksheet $ChartSheet -SeriesHeader $seriesNames -XRange $xrange -YRange $yrange -ChartType LineMarkers -LegendPosition Top -Row 0 -Column 0 -Height 700 -Width 1850 
```

**Comment by dfinke** [comment]
You can add `-PassThru` on the `Add-ExcelChart` and the access the properties to set what you need.

![image](https://user-images.githubusercontent.com/67258/180605797-48001c7f-3e10-4b55-9b2c-3faa3f31b503.png)

**Comment by benbozso** [comment]
Great, Thank you.
