### ISSUE TITLE
Reading cell comments as well as contents

### ISSUE THREAD

**Issue by MarkJEverest** [dfinke/ImportExcel#1223]
This isn't an issue but more of a feature request!
It would be great to be able to read in the comments of a cell as well as the contents.

**Comment by dfinke** [comment]
Need to think about a generalized approach. This is a start at extracting all the comments, but don't "align" them to the data.

```powershell
$xlFilename = ".\Book1.xlsx"
$excel = Open-ExcelPackage $xlFilename

foreach ($Item in $excel.Sheet1.Cells) {
    $comment = $Item.Comment

    if ($comment) {
        [PSCustomObject][Ordered]@{
            Address = $Item.Address
            Author  = $comment.Author
            Text    = $comment.Text.Replace("`n", "")
        }        
    }
}

Close-ExcelPackage $excel -NoSave
```
[Book1.xlsx](https://github.com/dfinke/ImportExcel/files/9273887/Book1.xlsx)
