### ISSUE TITLE
Export a worksheet from existing xlsx to other xlsx

### ISSUE THREAD

**Issue by Gtoml** [dfinke/ImportExcel#1225]
I am exporting a worksheet from an existing package to a final package.  It works great except for columns with formulas.  For those, it is blank.  Here is the command I am using.  

`Export-Excel -InputObject (Import-Excel -Path $tmpXslx -WorksheetName "EntitledUsers") -Path $FinalXlsx -WorksheetName "EntitledUsersRaw" -TableName Users -autosize `

What would I use to export the values for those columns?

**Comment by dfinke** [comment]
Please post a repro xlsx, script, and what you expect the result should be.

**Comment by Gtoml** [comment]
Doug, I meant to reach back.  The initial I had was that I was doing an export from a DB and importing into Excel using the -TableName  property (for the zebra look).  The I ran into was that after the import, I would add additional columns with formulas to the package.  Therefore, the columns outside the original import was not formatted.  My solution was to modify my export from the SQL DB to include the number of blank columns to account for my additional data.  That has worked for me.
