### ISSUE TITLE
Resize an existing table

### ISSUE THREAD

**Issue by MarkJEverest** [dfinke/ImportExcel#1228]
Hi,

I have seen there is a way to create a table, but is there a way to change the size of an existing table?
I tried changing the table's Address properties, but all of these are read-only.
The other option is to remove and re-add the table, but I cannot see a way to convert an existing table to a range.

Is there another way?

Thanks

**Comment by dfinke** [comment]
You can use `Open-ExcelPackage` to open the file, and then use `Set-ExcelRange` to change the size of the table.

**Comment by MarkJEverest** [comment]
Hi - thanks for the reply, but can you provide a bit more info please?

I cannot see on the "Set-ExcelRange" any parameters to do with tables or setting a name for the range. All the parameters seem to be about applying formatting.

**Comment by dfinke** [comment]
Sorry, for size, you are saying increase the size as in `rows\columns`? Not the width and height of the cells?

**Comment by MarkJEverest** [comment]
Yes, I want to expand the range of cells that the table is made up of.
In Excel the dialogue is called "Resize Table"
![resizetable](https://user-images.githubusercontent.com/20557892/184838460-8fb3dc90-0685-4235-8c2b-ce65206f9e3f.png)
[tables.xlsx](https://github.com/dfinke/ImportExcel/files/9349216/tables.xlsx)

**Comment by MarkJEverest** [comment]
This issue is now that I can easily add new rows to the bottom of an existing table, but those new rows are not part of the named table. They are just under it.

**Comment by dfinke** [comment]
## Try this

```powershell
$data = ConvertFrom-Csv @"
Name,Age
Jane,25
John,30
Bill,40
"@

$xlfile = "./test.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data | Export-Excel $xlfile -AutoSize -AutoFilter -TableName People

$moreData = ConvertFrom-Csv @"
Name,Age
Mary,22
Jill,26
"@

$moreData | Export-Excel $xlfile -AutoSize -AutoFilter -TableName People -Append -Show
```

![image](https://user-images.githubusercontent.com/67258/184975760-123a18ac-9054-4b26-a4a8-8d202cc5220d.png)

**Comment by MarkJEverest** [comment]
Ok sadly deleting the file and recreating is not an option. The example I uploaded is not real world but explaining the problem. I can't share the real file as it is my company's IP.
There are about 30 sheets with complex formulas and graphs in that will be almost impossible to recreate in code. These graphs use the tables as input sources, hence my need to expand the boundaries of the existing tables.
Why this has been done is Excel is beyond reasoning, but it is what I have to work with for now.

I need to be able to increase the row count of an exciting table.

**Comment by dfinke** [comment]
the deletion is just for my example, you can remove that.

**Comment by MarkJEverest** [comment]
OK, that worked for writing rows to a new sheet, but when writing to an existing sheet the file get corrupted and has to be recovered by Excel on opening.
I think I will have to leave this and try something else. :-(

**Comment by dfinke** [comment]
If you could, please post an xlsx that repros the issue.

**Comment by MarkJEverest** [comment]
I can't share it sorry as it has so much company IP in :-(

I did managed to change the table size though eventually!
Using the "InsertRow" method on a sheet inside the bounds of a table add tables to the table.

**Comment by dfinke** [comment]
@MarkJEverest understood, lots of scrubbing to post something like that. Could you post a scaled down version with fake data that demos this? Or, even better, if you're up for it, do a PR and add an example showing "How To"? 

If you want to do the PR and need assistance, let me know.
