### ISSUE TITLE
Is it possible to refresh External Data using ImportExcel ?

### ISSUE THREAD

**Issue by dhirajdharankar** [dfinke/ImportExcel#1229]
The task is basically to refresh External data in an Excel file. I have no Excel application installed in the machine so I have to use importExcel. The workbook has just one sheet in which new data gets updated once we hit the refresh option. Can we do that with writing a Powershell script ?

**Comment by dfinke** [comment]
The `ImportExcel` is not able to do that. It only works at the file level. The Excel book needs to be opened for external data refreshing to work.

I'd suggest you look into using the built-in COM capability, and you may need a VBA macro to achieve this task. Check Stackoverflow, someone may have solved this.
