### ISSUE TITLE
"AutoSize" the hight of cells?

### ISSUE THREAD

**Issue by theheatDK** [dfinke/ImportExcel#1232]
Hi,
I have a column that contains phone numbers.

If there is more than one phone number I add CRLF.

The result looks like this:
+4512345678+4587654321

If I click a cell it displays it correctly on multiple lines:
+4512345678
+4587654321

Is there a way to get Excel to always expand the cells instead of only doing it on click?

Regards Peter

**Comment by dfinke** [comment]
After the sheet is created, you need to use `Set-ExcelRange` with the `-WrapText` switch on the cells you want to display this way.

https://github.com/dfinke/ImportExcel/issues/1170#issuecomment-1114098736

**Comment by theheatDK** [comment]
Super. Thanks for your time!
