### ISSUE TITLE
Export excel - missing decimals

### ISSUE THREAD

**Issue by prodtech22** [dfinke/ImportExcel#1239]
Hello,
I would like some help with a simple conversion. I have an excel file and I would like to remove the 1st row. When I do that, the output file does not show the decimals in column 3. Is there a way to keep the decimals? Using the -nonumberconversion doesn't seem to work as expected.
Import-Module importExcel
sl C:\test
Import-Excel test.xlsx -NoHeader -StartRow 2 | 
Export-Excel test11.xlsx -NoHeader -NoNumberConversion *

**Comment by dfinke** [comment]
please post the excel file you are working with

**Comment by prodtech22** [comment]
[testxx.xlsx](https://github.com/dfinke/ImportExcel/files/9471656/testxx.xlsx)

**Comment by prodtech22** [comment]
As output I get this 
[test11.xlsx](https://github.com/dfinke/ImportExcel/files/9471667/test11.xlsx)

**Comment by dfinke** [comment]
That data is formatted in Excel, the `Import-Excel` pulls only the value.

Try this:

```powershell
$excel = import-excel testxx.xlsx -StartRow 2 | Export-Excel ./test11.xlsx -AutoSize -PassThru

Set-ExcelRange -Worksheet $excel.Sheet1 -Range "C:C" -NumberFormat "#,##0.00"
Close-ExcelPackage $excel -Show
```

**Comment by prodtech22** [comment]
Thank you so much! I knew you were my only hope. I really appreciate your help!!!
