### ISSUE TITLE
Wiki - Replace With dotnet Interactive Notebook

### ISSUE THREAD

**Issue by D1g1talCav3Man** [dfinke/ImportExcel#1245]
I see there are lots of examples in the repo, but for learning the basics I don't see a lot in the landing page or the wiki.  I see you have done very well with giving lectures using dotnet Interactive Notebooks.  Looks like a lot of thought was put into creating those.  Would it be possible to pipe those refined notebooks into the Wiki and let it take roots there?

Feedback from the community would then pay into the notebook sort of like a living FAQ.

**Comment by dfinke** [comment]
Interesting. Not sure which repo you mean. I do demos about things like ImportExcel and use notebooks to do that. I don't think I have and demos etc on learning the basics.

I have thought about doing that.
