### ISSUE TITLE
Export-Excel using both -Title and -Tablestyle to separate worksheets creates a corrupt xlsx file.

### ISSUE THREAD

**Issue by Martijn74** [dfinke/ImportExcel#1248]
Like the title says :) nothing more to it than that :)

Data is appended through a script to the file. It also happens when i export all data at once doing the same (title and Tablestyle)

It works fine when you only use 1 worksheet.

**Comment by dfinke** [comment]
Please post a repro.

**Comment by Martijn74** [comment]
I was working on this but i found what was the problem so i can prevent it from happening.

What i am doing is get tables from SQL with a query (using powershell) and then export that to an excel worksheet using an foreach (some conditions) loop. I did not check if the result was empty or not - i simple did the export-excel with the append switch. That all worked fine, but as soon as i started to use a tablestyle i got a corrupt xlsx as a result.

Now i check if the variable has any info in it and then i use export-excel, and just do nothing when it doesnt have any data. This fixed the problem for me.

**Comment by Martijn74** [comment]
sorry for the late reply ;)

**Comment by dfinke** [comment]
No problem. Thanks for reporting it and the update.
