### ISSUE TITLE
Set TabColor in Constrained Language Mode

### ISSUE THREAD

**Issue by ben-5555** [dfinke/ImportExcel#1249]
Hello,

I use PowerShell in Version 7.2.6 in Constrained Language Mode. In the Constrained Language Mode I cannot set the TabColor and I get this error message:

![image](https://user-images.githubusercontent.com/84332967/189909163-6d657dc0-d779-455b-a3c4-feef0373f42e.png)

Is there a workaround for this problem?

Thanks,
Ben

**Comment by dfinke** [comment]
Your the first to report something like this. Don't know, this module has not been tested in that mode.

I ran a simple `Export-Excel` in constrained mode, got the below.

WARNING: System.Drawing could not be loaded. Color and font look-ups may not be available.

**Comment by dfinke** [comment]
Thanks. Yes, I was able to see the issue. If I come a solution, I will post it.
