### ISSUE TITLE
How to clone a record that can be appended to an existing excel worksheet?

### ISSUE THREAD

**Issue by ccna2ccda** [dfinke/ImportExcel#1250]
Hi everyone,

I load table into an exist $rows variable using "Import-Excel" and would like to add one row, and then write(append) back to the original table to the worksheet. I receive the following error message when using "export-excel -append" command.

So my question is: how do I clone an existing row of psobject[] returned by Import-Excel? Thanks.

Failed exporting data to worksheet 'Receipt' to 'F:\Ps_Project\Student\bin\Students.xlsx': Key cannot be null.
Parameter name: key
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.4.1\Public\Export-Excel.ps1:366 char:21
+ ...     catch { throw "Failed exporting data to worksheet '$WorksheetName ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed exportin...meter name: key:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed exporting data to worksheet 'Receipt' to 'F:\Ps_Project\Student\bin\Students.xlsx': Key cannot be null.

== My code to clone a row and then init the value from $record.
function cloneTableRowWithHashRecord {
    [CmdletBinding()]
    Param($table, $record)     
    if ($null -eq $table -or $table.count -eq 0) {
        return $null
    }

    if ($null -eq $record -or $record.keys.count -eq 0) {
        return $null
    }

    $row = $table[0].psobject.copy()
    foreach ($pname in $row.psobject.properties.name) {
        $row.$pname = ""
    }

    foreach ($key in $record.keys) {
        foreach ($pname in $row.psobject.properties.name) {
            if ($pname -eq $key) {
                $row.$pname = $record.$key
            }
        }
    }
    return $row
}

**Comment by ccna2ccda** [comment]
I examine the $row | gm output and find "clone()" is capable of cloning a record. But is there a method to initialize each field? Essentially, it contains a hash table, so if i iterate thru each key and assign it with "", it probably will work. 

any feedback is appreciated. Thanks.

**Comment by dfinke** [comment]
Not really sure what you are trying to do

**Comment by ccna2ccda** [comment]
Thanks for the feedback, Doug. Is this the only place I can raise the question and get some feedback?

I wanted to close a record loaded by Input-Excel module, so the list can be appended with new data. The following code seems to do the work, but their might be easier way..

function cloneTableRow {
    [CmdletBinding()]
    Param($row)     
    if ($null -eq $row) {
        return $null
    }

    $new_row = $row.psobject.copy()   
    foreach ($pname in $row.psobject.properties.name) {        
        $new_row.$pname = $null        
    }
    return $new_row
}

function cloneTableRowWithRecord {
    [CmdletBinding()]
    Param($row, $hash)     
    if ($null -eq $row) {
        return $null
    }

    if ($null -eq $hash) {
        return $null
    }

    $new_row = cloneTableRow $row
   
    # assume $hash is HASH
    foreach ($k in $hash.keys) {
        foreach ($pname in @($new_row.psobject.properties.Name)) {          
            if ($k.trim() -ieq $pname.trim()) {          
                $new_row.$pname = $hash[$k]          
            }
        }       
    }
    return $new_row
}

**Comment by dfinke** [comment]
You can try Stackoverflow
