### ISSUE TITLE
How to format columns?

### ISSUE THREAD

**Issue by gmjulian** [dfinke/ImportExcel#1252]
I have a need to send data into an excel file but one of the columns needs to be formatted as 'Number' with no decimal point placing. Is there an easy way to do this via the code as opposed to doing it after the file has been created? I have about 10 separate tabs that would need to manually be updated and just want to automate it.

**Comment by dfinke** [comment]
On the `Export-Excel` you can use the `-PassThru` switch and store it in a variable `$excel`. Then use `Set-ExcelRange` on the sheet that just got exported, and you can target a range of cells using `-Range` and `-NumberFormat`. Use `Close-ExcelPackage $excel` when finished.

**Comment by gmjulian** [comment]
Sweet, that gets me closer, thanks for the tip.. but I don't want the decimal places. Here is some sample output and the code. The globalUID is a number, but with the set-excel range showing as a 'number', I get a result of 12345.00 and I only want 12345. I tried using 'text' but that comes in as the 1E+11 format that Excel throws. I'm super close, any idea?

Output is:
samaccountname | globalUID
User 1 | 100000265603.00
User 2 | 100000892820.00
User 3 | 100003007726.00

Code snipet:

$results = get-adgroupmember "Group1" | get-aduser -Properties * | select samaccountname,globalUID,displayname   
    $excel = $results | Export-Excel $outputfile -AutoSize -AutoFilter -WorksheetName "users1" -FreezeTopRow -ConditionalFormat $CondFormat -PassThru 
    Set-excelrange -range "B1:B1000" -WorkSheet $excel.'Users1' -NumberFormat 'Number'
    Close-ExcelPackage $excel

**Comment by gmjulian** [comment]
I figured it out. To get all the numbers to the left of the decimal, specify it as '0'

Set-excelrange -range "B1:B1000" -WorkSheet $excel.'Users1' -NumberFormat '0'
