### ISSUE TITLE
Question regarding -AutoNameRange with "Append"?

### ISSUE THREAD

**Issue by ccna2ccda** [dfinke/ImportExcel#1259]
When using "-append", the autoNameRange defines the Named Range of the whole column, not just the "appended" rows. Is this the expected behavior? Thanks.

Sample command as below:

 $excelPackage = export-excel -append -Path $output_file -worksheet $SHEET_STUDENT_RECEIPT -InputObject $new_records `
                -autoNameRange -activate -PassThru  -WarningAction:SilentlyContinue

**Comment by dfinke** [comment]
Off the top of my head `-AutoNameRange` looks at the size of the incoming data (may look at the data after it is inserted) and maps each property as a column. I have not tried it with `-Append`, plus, would need to test and see what that combination would do on an existing sheet with named ranges already set.

Please post an xlsx and script that repros the issue.
