### ISSUE TITLE
Using Set-ExcelRange to add MAXIFS formula to cell does not work as expected.

### ISSUE THREAD

**Issue by steve-daedilus** [dfinke/ImportExcel#1261]
I'm attempting to do add a MAXIFS formula to assess data in a table.  I am looking to filter that table based on a Date column and also a name column.

The applicable snippet of code:

``` powershell
$daysInMonth = [datetime]::DaysInMonth($yesterday.Year,$yesterday.Month)
    $summaryData = @"
Date,AB - Average,CD - Average,AB - Max,CD - Max
"@
    for ($i = 1; $i -le $daysInMonth; $i++){
        $dateStr = "$i/"+$yesterday.Month+"/"+$yesterday.Year
        $DateVal = Get-Date $dateStr -Format 'dd/MM/yyyy'
        $summaryData = $summaryData + "`n$DateVal"
    }
    $summaryData | ConvertFrom-Csv | Export-Excel -ExcelPackage $excel -WorksheetName "Summary" -StartRow 2 -StartColumn 2 -AutoSize -AutoNameRange
    #Close-ExcelPackage $excel
    # Setup Table Data
    $excel = Open-ExcelPackage -Path $monthOutFile
    $xlSummary = $excel.Workbook.Worksheets['Summary']
    $upperRange = $daysInMonth + 2
    3..$upperRange | ForEach-Object {
        $AvFormulaAB = '=IFERROR(AVERAGEIFS(RawData!$I:$I,RawData!$K:$K,"AB*",RawData!$H:$H,@Date),"N/A")'
        Set-ExcelRange -Worksheet $xlSummary -Range "C$_" -Formula $AvFormulaAB

        $AvFormulaRL = '=IFERROR(AVERAGEIFS(RawData!$I:$I,RawData!$K:$K,"CD*",RawData!$H:$H,@Date),"N/A")'
        Set-ExcelRange -Worksheet $xlSummary -Range "D$_" -Formula $AvFormulaCD

        $MaxFormulaBD = '=IFERROR(MAXIFS(RawData!$I:$I,RawData!$K:$K,"AB*",RawData!$H:$H,@Date),"N/A")'
        Set-ExcelRange -Worksheet $xlSummary -Range "E$_" -Formula $MaxFormulaAB

        $MaxFormulaRL = '=IFERROR(MAXIFS(RawData!$I:$I,RawData!$K:$K,"CD*",RawData!$H:$H,@Date),"N/A")'
        Set-ExcelRange -Worksheet $xlSummary -Range "F$_" -Formula $MaxFormulaCD
    }
```
When I do this, the MAXIFS formulae are presented starting like this:

```
=IFERROR(@MAXIFS(RawData!$I:$I,RawData!$K:$K,"CD*",RawData!$H:$H,@Date),"N/A")
```
Note the addition of the "@" before the MAXIFS.

I've thus far attempted:
- Using -TableName to convert to a table during Export-Excel.
- Using -ArrayFormula
- Setting the range for the whole range not looping.
- Setting the reference of @Date to the actual cell reference.

None of this works.  AVERAGE however on several of these, works as expected.

I've also tried to build a PivotTable to generate this data, however that's a separate issue I'm having, and I'll raise it separately.

**Comment by dfinke** [comment]
Not sure of this may be a clue:

https://stackoverflow.com/questions/62543947/adding-to-formula-after

**Comment by steve-daedilus** [comment]
Thanks, had a quick scan and may be able to work with that. I'll try and get a bit of time to prod it ASAP and report back.

**Comment by steve-daedilus** [comment]
So I updated to the following:

``` powershell
 $MaxFormulaRL = '=IFERROR(_xlfn.SINGLE(_xlfn.MAXIFS(RawData!$I:$I,RawData!$K:$K,"CD*",RawData!$H:$H,@Date)),"N/A")'
 ```

I also used an Ordered Hashtable to make the columns predictable.

This appears to have fixed it and delivered what I wanted to achieve.

**Comment by dfinke** [comment]
Excellent! I had used the `_xlfn` before, but could not find my examples to test it out.

Thanks for the update
