### ISSUE TITLE
Cannot add multiple values from same field using Add-PivotTable

### ISSUE THREAD

**Issue by steve-daedilus** [dfinke/ImportExcel#1262]
I am trying to create a Pivottable, with different metrics extracted from the same column.

The requirements are as follows:
- Set Pivot Filter to a name field and apply setting to select multiple and use a text criteria of (eg) "AB*"
- Set Pivot Rows to Date field.
- Set Pivot Values to contain data for times averaged, max, min and count.

I can do this manually in excel by placing the same field in the values section 4 times, and changing the calculation to the appropriate setting.  The outcome is I get 4 columns, named
- Average of Time
- Max of Time
- Min of Time
- Count of Time

The appropriate values are then presented for each date found (listed in first column of the pivot table).

Is there a means to achieve this with Add-PivotTable?

**Comment by steve-daedilus** [comment]
Hi,

Sample attached.

[Sample.xlsx](https://github.com/dfinke/ImportExcel/files/9717404/Sample.xlsx)

Code below is extracted from attempts to do this inline whilst building the .ps1.  The original data set as supplied by ```$dataArray``` is columns A:N, I've just trimmed the fat for the sample.

``` powershell
$excel = $dataArray | Export-Excel -Path $monthOutFile -WorksheetName "RawData" -AutoSize -Append -FreezeTopRow -AutoNameRange
$excel = Open-ExcelPackage -Path $monthOutFile
$ptsheet = Add-Worksheet -ExcelPackage $excel -WorksheetName "PivotData" -MoveBefore "RawData"
$pt = Add-PivotTable -PivotTableName "AB_Stats" `
-Address $excel.PivotData.Cells["B4"] `
-ExcelPackage $excel `
-SourceWorksheet $excel.RawData `
-SourceRange ["A:N"] `
-PivotRows "Logon Duration","Logon Duration","Logon Duration","Logon Duration" `
-PivotColumns "Logon Date" `
-PivotData @{"Logon Duration"="Average";"Logon Duration"="Max";"Logon Duration"="Min";"Logon Duration"="Count"}
```

Error encountered here about duplicate key in the Hashtable, which makes sense.

**Comment by dfinke** [comment]
Yeah, not a scenario that was looked at.

I removed the spaces from the property names, remove the warnings to work on debugging the issue.

The hashtable is a map of the fields/dimensions and measures average, min, max.

The hashtable is a blocker, the keys need to be unique.

I don't have a workaround at the moment.

```powershell
$pivotData = @{
    "LogonDuration" = "Average"
    #"LogonDuration" = "Max"
    # "Min Logon Duration"     = "Min"
    # "Number of Logons" = "Count" 
    "LogonsDate"    = "Count" 
}

$pt = Add-PivotTable -PivotTableName "AB_Stats" `
    -Address $excel.PivotData.Cells["B4"] `
    -ExcelPackage $excel `
    -SourceWorksheet $excel.RawData `
    -SourceRange $excel.Workbook.Worksheets['RawData'].Tables[0].Address `
    -PivotRows "LogonDuration" -PivotColumns "LogonDate" `
    -PivotData $pivotData

Close-ExcelPackage $excel -Show
```

**Comment by steve-daedilus** [comment]
Thanks for looking.  This was my second means to try and achieve what I struggled with around the formula autocorrection in other issue I raised. I'll see if that approach will resolve, however this would still be useful for future use cases.

**Comment by dfinke** [comment]
Agreed. It's strange that I have not needed that since the beginning, and you are the first person to ask.
