### ISSUE TITLE
Negative values mix up currency conversion format (de-de)?

### ISSUE THREAD

**Issue by caratage** [dfinke/ImportExcel#1269]
Thanks for this module, it made my life a lot easier. It is working great so far. However, I am running into an small issue where I need some advice.

I am creating an Excel from an SQL Table with a currency column that is set by `Set-ExcelRange -NumberFormat 'Currency'`.

While for positive numbers, the expected format in Excel is as expected, negative values are formatted differently. No matter if the source column has a data type of `DECIMAL(19,2)` or `MONEY`.

Input decimal:
<img width="200" alt="decimal" src="https://user-images.githubusercontent.com/341799/195325242-19c1fd73-ae3c-4b99-85ff-d41e4b21d05d.png">

Input money:
<img width="200" alt="money" src="https://user-images.githubusercontent.com/341799/195324964-b2c35533-8800-44a6-bf5b-7799bda4bfac.png">

Produce same output in Excel that is differently formatted for positive and negative values:
<img width="200" alt="excel" src="https://user-images.githubusercontent.com/341799/195326002-ec60babb-0a10-4e7f-a879-54988ad24144.png">

Expected output (after manually setting column to currency in Excel):
<img width="200" alt="excel-excpected" src="https://user-images.githubusercontent.com/341799/195325941-79b84b1c-fa6c-4f75-a5c9-eaeec2edbcb2.png">

My/the users locale is de-de. Am I missing something?

**Comment by dfinke** [comment]
Yes, could be the users locale. Please could you post a simple script and set of data the repros the issue.

**Comment by caratage** [comment]
### Simple script with German style CSV delimiter and number format

```
$data = ConvertFrom-Csv @"
Region;State;Price
West;Texas;-923,71
North;Tennessee;1770,67
East;Florida;-458,68
East;Maine;661,24
West;Virginia;-053,58
North;Missouri;2235,67
South;Kansas;-992,47
North;North Dakota;640,72
South;Delaware;-5508,55
"@ -Delimiter ";"

$filename = "test"
$extension = ".xlsx"
$exportpath = ".\" + $filename + $extension
$tablename	= "table"
$tablestyle = "Medium4" 

$xl = $data | Export-Excel -Path $exportpath -KillExcel -ClearSheet -BoldTopRow -FreezeTopRow -AutoFilter -AutoSize -TableName $tablename -TableStyle $tablestyle -WorkSheetName $filename -PassThru

$ws = $xl.Workbook.Worksheets[$filename]

$ws.Column(3) | Set-ExcelRange -NumberFormat "Currency"

Export-Excel -ExcelPackage $xl -WorkSheetname $filename -Show
```

### Excel output with mixed up currency format:
![image](https://user-images.githubusercontent.com/341799/196114612-44c9afd3-3e0f-4de0-97cf-08aa347be0f2.png)

**Comment by caratage** [comment]
So this is now marked `wontfix`?

**Comment by ninmonkey** [comment]
Is your `Get-Culture` set to `en` ? It might be implicit even in under different locales.

- This preserves the original numeric string
- It needs the actual transform to numeric 
```ps1
$Config = @{
    GlobalImportExcelVerbose = $true
    AlwaysOpen               = $true
    AlwaysKill               = $false
    IncludeCultureDump =  $false
}
if ($Config.GlobalImportExcelVerbose) { $global:PSDefaultParameterValues['ImportExcel*:Verbose'] = $true }
$Paths = @{
    Export  = Join-Path $PSScriptRoot '.export' 'test-culture.xlsx'
}

$data = @'
Region;State;Price
West;Texas;-923,71
North;Tennessee;1770,67
East;Florida;-458,68
East;Maine;661,24
West;Virginia;-053,58
North;Missouri;2235,67
South;Kansas;-992,47
North;North Dakota;640,72
South;Delaware;-5508,55
'@ | ConvertFrom-Csv -Delimiter ';'

$exportExcelSplat = @{
    AutoFilter    = $true
    AutoSize      = $true
    BoldTopRow    = $true
    ClearSheet    = $true
    FreezeTopRow  = $true
    KillExcel     = $Config.AlwaysKill
    Show          = $Config.AlwaysOpen
    TableName     = 'name_table'
    TableStyle    = 'Medium4'
    WorksheetName = 'name_sheet'
}

[OfficeOpenXml.ExcelPackage]$pkg = $data
| Export-Excel @exportExcelSplat -Path $Paths.Export -PassThru -NoNumberConversion 'Price'

$sheet = $pkg.Workbook.Worksheets[1]
($ws = $pkg.Workbook.Worksheets[1])
$ws.Cells| select -first 5 | Ft


# $sheet.Column(3) | Set-ExcelRange -NumberFormat 'Currency'
# Expand-NumberFormat 'Currency'
# Expand-NumberFormat 'Number'

# # one way
# $ErrorActionPreference = 'break'
Set-ExcelRange -Worksheet $ws -Range 'C2:C10' -NumberFormat 'Number'
# or
Set-ExcelRange -Address $ws.Tables[0].Columns['Price'] -NumberFormat 'Currency'
# $ErrorActionPreference = 'continue'

Close-ExcelPackage $Pkg -Show
```

**Comment by dfinke** [comment]
@caratage does the approach @ninmonkey suggested work for you?

**Comment by caratage** [comment]
Thanks for the suggestion! I don't have access to the system in question at the moment but will check and report back asap.

**Comment by caratage** [comment]
@dfinke I think there is a error in the 2nd switch condition of [Public/Expand-NumberFormat.ps1](https://github.com/dfinke/ImportExcel/blob/master/Public/Expand-NumberFormat.ps1) at line 18. It should be `switch ([cultureinfo]::CurrentCulture.NumberFormat.CurrencyNegativePattern) { ... }`

**Comment by dfinke** [comment]
I will review

**Comment by caratage** [comment]
Thanks! Here my output for `NumberFormat`, where I found that my `CurrencyNegativePattern` equals 8. That would be the right one.

```
PS> $Culture = Get-Culture
PS> $Culture.NumberFormat

CurrencyDecimalDigits    : 2
CurrencyDecimalSeparator : ,
IsReadOnly               : False
CurrencyGroupSizes       : {3}
NumberGroupSizes         : {3}
PercentGroupSizes        : {3}
CurrencyGroupSeparator   : .
CurrencySymbol           : €
NaNSymbol                : NaN
CurrencyNegativePattern  : 8
NumberNegativePattern    : 1
PercentPositivePattern   : 0
PercentNegativePattern   : 0
NegativeInfinitySymbol   : -∞
NegativeSign             : -
NumberDecimalDigits      : 2
NumberDecimalSeparator   : ,
NumberGroupSeparator     : .
CurrencyPositivePattern  : 3
PositiveInfinitySymbol   : ∞
PositiveSign             : +
PercentDecimalDigits     : 2
PercentDecimalSeparator  : ,
PercentGroupSeparator    : .
PercentSymbol            : %
PerMilleSymbol           : ‰
NativeDigits             : {0, 1, 2, 3...}
DigitSubstitution        : None
```

**Comment by caratage** [comment]
bump

**Comment by dfinke** [comment]
Not going to have time to work with this. Need to revisit.

If you can, happy to take a PR with appropriate tests applied for backwards compatibility and the fix.
