### ISSUE TITLE
Disk error occurred during write operation

### ISSUE THREAD

**Issue by nullifi** [dfinke/ImportExcel#127]
I just installed on Win10 via Install-Module and tried to open an XLS file via Import-Excel, and I get a plethora of errors, first one being:

> New-Object : Exception calling ".ctor" with "1" argument(s): "A disk error occurred during a write
> operation. (Exception from HRESULT: 0x8003001D (STG_E_WRITEFAULT))"
> At C:\Users\jtaylor\Documents\WindowsPowerShell\Modules\ImportExcel\2.2.8\ImportExcel.psm1:57 char:15
> + ...       $xl = New-Object -TypeName OfficeOpenXml.ExcelPackage -Argument ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
>     + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCo
>    mmand

It then follows with a bunch of 'cannot index into a null array' errors. Any idea what may be going wrong?

**Comment by nullifi** [comment]
I just realized, if I save it as an XLSX it loads it, it can't seem to do XLS, unless I am missing something.

**Comment by dfinke** [comment]
That's right.

**Comment by nullifi** [comment]
That's most unfortunate.

**Comment by dfinke** [comment]
Yes, only the newer format is supported.
