### ISSUE TITLE
Identify last row in a worksheet and retrieve just that row

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#1272]
### Discussed in https://github.com/dfinke/ImportExcel/discussions/1271

<div type='discussions-op-text'>

<sup>Originally posted by **steve-daedilus** October 14, 2022</sup>
Hi,

Is there an easier / more efficient way to identify the last row with data in a sheet and retrieve that last row (or even cell) without retrieving the rest of the data?

Currently doing the following, however with over 100k rows, this is pretty slow.  Changed identifiable variables / names etc, otherwise the same.

``` powershell
$lastRow = Import-Excel -Path $xlFile -WorksheetName "Sheet1" | Sort-Object -Property "DateTime" -Descending | Select-Object -First 1
```

I found I could catch the number of rows by the following:

``` powershell
$excel = Open-ExcelPackage -Path $xlFile
$excel.Sheet1.Dimension.Rows
```

I'm clearly overlooking how I can leverage this to avoid reading everything out of the sheet.  Any pointers?</div>

**Comment by dfinke** [comment]
@steve-daedilus 

I use:

```powershell
Get-ExcelFileSummary .\test.xlsx
```

```
ExcelFile     : test.xlsx
WorksheetName : Sheet1
Rows          : 10
Columns       : 4
Address       : A1:D10
Path          : .
```

**Comment by steve-daedilus** [comment]
Hi Doug,

I added this to the Q&A:

----

``` powershell
$lastRow = Import-Excel `
    -Path $xlFile `
    -WorksheetName "Sheet1" `
    -StartRow $xlFile.Sheet1.Dimension.Rows `
    -EndRow $xlFile.Sheet1.Dimension.Rows `
    -NoHeader
```
Found arbitrary limit of 9999. This limit is set in Public\Import-Excel.ps1 at Line 26.
Locally I've added some extra 9's to the upper range, and this then works instantly.

----

I can use Get-ExcelFileSummary to obtain the value for StartRow and EndRow, however I still can't get the data unless I change the limit imposed by the import-excel function code, or else bring everything in.

Example of using this, and the row count issue I'm hitting:

``` powershell
Get-ExcelFileSummary -Path .\test.xlsx | Where-Object {$_.WorksheetName -eq "Sheet1"} | Select-Object Rows

  Rows
  ----
133436

```

Unless there's a better way to retrieve just a single row / value, this was the best I could come up with.

**Comment by steve-daedilus** [comment]
In Import-Excel.ps1, I changed the $StartRow Validate Range to change the upper value from "9999" to "9999999":
``` powershell
function Import-Excel {
    [CmdLetBinding()]
    ...
    param (
        ...
        [Alias('HeaderRow', 'TopRow')]
        [ValidateRange(1, 9999999)]
        [Int]$StartRow = 1
        ...
````

**Comment by dfinke** [comment]
Good point. I will add a todo to up that.

**Comment by steve-daedilus** [comment]
I've forked the repo, made update to actual max number of rows and placed a pull request. Hope that helps.

**Comment by dfinke** [comment]
Would you consider writing a Pester test for that? :)

**Comment by steve-daedilus** [comment]
Ha! Well, given I'm pretty novice on the whole code front, I'd probably need some pointers on getting started!! It'd be a good learning opportunity though.

**Comment by steve-daedilus** [comment]
I've started linking an Pester, and I'm trying out an amendment to the tests already there for reading partial data.  I'm probably being massively overkill, but seem to have a working (albeit slow and verbatim) test.

**Comment by steve-daedilus** [comment]
I've got a test that's randomly picking 10 rows to read from, across the whole range of rows permissible. Going to target it a bit better to make sure we capture max and min in that.

**Comment by steve-daedilus** [comment]
Full suite test run:

``` powershell
Tests completed in 201.68s
Tests Passed: 264, Failed: 0, Skipped: 7 NotRun: 3
```

**Comment by steve-daedilus** [comment]
PR has picked up my published test info, and your Azure Pipeline process appears to have completed successfully.  @dfinke I think this should hopefully be good, if you could review when you get a chance?
