### ISSUE TITLE
How to read the outline (indentation) information in a cell 

### ISSUE THREAD

**Issue by haschdl** [dfinke/ImportExcel#1280]
In Excel it is possible to increase the indentation of a cell value (via Increase/Decrease Indent buttons).
Is it possible to read that information using the library?
<img width="233" alt="image" src="https://user-images.githubusercontent.com/9550197/196764626-204dd719-db25-4c3e-afa9-5105b3b44877.png">

**Comment by haschdl** [comment]
I checked the code base and it seems there is no way to get the indent value for a cell. However it did seem possible to make a few changes here and there to make it happen? For example `Import-Excel.ps1` could refer to a new switch  `-Indent` and prepend a new string with  as a many spaces as the value of `Style.Indent`. Is that reasonable?

https://github.com/dfinke/ImportExcel/blob/201b9cd98461f0ac01cfe35d7ca1aefc643a159e/Public/Import-Excel.ps1#L232-L237

**Comment by dfinke** [comment]
Seems like it would be less risky to extend `Set-ExcelRange` or maybe introduce a `Set-Indentation` function.

**Comment by haschdl** [comment]
@dfinke  aren't the `Set-` functions for exporting data to an Excel? Could you elaborate?

**Comment by dfinke** [comment]
`Set-ExcelRange` lets you target a range of cells in a sheet and you do things like make the font bold, change the format for numbers, change the width of the cells etc.

**Comment by dfinke** [comment]
Sorry. Misread :) 

Could you post an example of what you are trying to do?

You want to add the `Indentation` that was set in Excel as a pad as the data is read from the sheet?

**Comment by haschdl** [comment]
hi @dfinke !
I'm trying to read the indentation value that was placed in the Excel as a way to build a hierarchical view of the the data.

In Excel, one can use indentation to make a tree-like structure. It creates a visual structure of "which item is a parent of another". While that information is available under `Style.Indent` it has more uses than just visuals (like computing sub-totals), however in my case it is the relationship between cells. Think a "manager to subordinate" relationship. 
![image](https://user-images.githubusercontent.com/9550197/196898500-ae833168-e284-4344-871b-75f90fa2dce3.png)

In order to capture that data while running `Import-Excel`, I need to read the value of `Style.Indent`. 
The way I initially propose is a bit hacky - ideally the  `Indent` value could come as another attribute . 

Does it make sense? :D

**Comment by msftrncs** [comment]
You could read the `Open-ExcelPackage` results directly to find this information, making your own implementation of Import-Excel, producing whatever result you want with the information.  This is probably the best for this special case use.

**Comment by ninmonkey** [comment]
Another way to debug, is create a minimal test case sample file -- then save it with and without the styles set.
Then you can outside of powershell, right click to unzip the `xlsx` files to a folder. Which contains a lot of text files. 

Then you can literally text-diff the two directories. 

That method was helpful when I was debugging a corrupted file. In that case, I accidentally wrote to the same sheet name twice.
