### ISSUE TITLE
Help for Export-Excel -InputObject grammar error

### ISSUE THREAD

**Issue by msftrncs** [dfinke/ImportExcel#1281]
The help for `Export-Excel` `-InputObject` parameter starts the description off with __Date__ when it was probably meant to be __Data__.

![image](https://user-images.githubusercontent.com/26179051/196832310-8c0954d8-9c47-4209-b3b8-a0f493b5d733.png)

**Comment by steve-daedilus** [comment]
I'll have a quick pop at this.

**Comment by msftrncs** [comment]
Is this similar to #1282, that the error is really in the XML help file?   I find 3 occurrences of the pattern `Date is usually` contained in the XML help file.

**Comment by steve-daedilus** [comment]
Yes the issues are similar, which is why I said I'd take a look at both. I'll take a look at help XML generation this week, if I get a chance.
