### ISSUE TITLE
Help for Open-ExcelPackage example typo

### ISSUE THREAD

**Issue by msftrncs** [dfinke/ImportExcel#1282]
The help for `Open-ExcelPackage` example 2 appears to have an `a` where there was probably meant to be a `.`, between `Worksheets` and `"sheet1"`.

![image](https://user-images.githubusercontent.com/26179051/196836930-e31c6bbd-654d-4b57-976f-c4c8a5c50c70.png)

**Comment by steve-daedilus** [comment]
I'll have a pop at this.

**Comment by steve-daedilus** [comment]
Looks like this has been fixed already in the repo?

**Comment by dfinke** [comment]
Looks like it is in the `https://github.com/dfinke/ImportExcel/blob/master/en/ImportExcel-help.xml`. There is no automated way in the repo to re-generate the help though

**Comment by steve-daedilus** [comment]
I'll take a look at PlatyPS (I think that's what it was called) within the code tree to generate the help. I'll also look to see if there's a simple way of updating the help XML data when the MD files are changed. Have some ideas for this, but not sure how best to integrate with the automation.
