### ISSUE TITLE
Export-Excel: autofilter behaviour

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#1286]
line 424:
Subexpression `$null -ne $TableName` in expression `if ($null -ne $TableName -or $PSBoundParameters.ContainsKey('TableStyle'))` forces autofilter ON.

### Work around
If I explicitly set `-TableName $null` parameter or replace subexpression `$null -ne $TableName` with just `$TableName` autofilter will not be activated.

I think expression `($TableName -or $PSBoundParameters.ContainsKey('TableStyle'))` is more right.

**Comment by scriptingstudio** [comment]
I am confused.
If I apply parameter `-now` data will be converted to a table with autofilter activated. And only `-TableName $null` resets autofilter activation.
Without `-now` autofilter and table conversion are not activated.
I use your test script:
```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@
$data | Export-Excel .\salesData.xlsx
```

**Comment by scriptingstudio** [comment]
line 108
> #"Now" option will create a table, unless something passed in TableName/Table Style. False in TableName will block autocreation

Strange condition.

Well then explicit  `-AutoFilter:$false` should override table autocreation

**Comment by scriptingstudio** [comment]
From doc:
> The -Now switch is a shortcut that automatically creates a temporary file, enables "AutoSize", "TableName" and "Show", and opens the file immediately.

I got it at last. But `-Now` has an unexpected side effect which I have to overcome somehow. This looks like an algorithm issue.

**Comment by scriptingstudio** [comment]
`-Now` is ambiguous. It should be refactored. This is algorithmic issue.

**Comment by dfinke** [comment]
Thanks for the drill down. Since that grew organically, side effects were probably not handled. The `-Now` was an "idea" if you do:

```powershell
$data | Export-Excel
```

That is similar, it creates a temporary file though. 

So you still can't get the result you want by specifying the parameters and switches yourself?

**Comment by scriptingstudio** [comment]
Thanks for reply.
I have found a workaround and made peace with it :-)
I use `-Show` or `-Now -TableName $false`.

**Comment by dfinke** [comment]
Nice. Did you try `-TableName $null`? Curious if it worked
