### ISSUE TITLE
Export-Excel Multiple Worksheets

### ISSUE THREAD

**Issue by ErvM** [dfinke/ImportExcel#1289]
Hello!

I either don't know how to do this, or well IDK lol. I am importing multiple excel workbooks that have multiple worksheets (I can import them successfully) (example either importing multiple spreadsheets into one array with or without "-worksheet * -Raw). But when I export it to an excel spreadsheet I can't export the tabs/worksheets. I have tried to find anything about this but I haven't been successful.

**Comment by dfinke** [comment]
Yes, that reads all the sheets into a single array. Use `$data = Import-Excel .\test.xlsx -WorksheetName *`. That returns a hashtable, each key/value pair is the name of the sheet and the data.

You then need to loop through the hashtable and use Export-Excel to output the data to the sheet and use the key for the name of the worksheet.

**Comment by msftrncs** [comment]
I export each sheet one at a time (separate executions of Export-Excel), to the same file.  And if you use the Excel Package method, then you have to use `-PassThrough` on Export-Excel, or it will close the ExcelPackage.

**Comment by dfinke** [comment]
@msftrncs This may be a simpler way to do it:

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = ".\data.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data | Export-Excel $xlfile -WorksheetName Sheet1 -AutoSize
$data | Export-Excel $xlfile -WorksheetName Sheet2 -AutoSize
$data | Export-Excel $xlfile -WorksheetName Sheet3 -AutoSize
$data | Export-Excel $xlfile -WorksheetName Sheet4 -AutoSize

$ImportedData = Import-Excel $xlfile -WorksheetName * -Raw

$ImportedData | Export-Csv -Path .\data.csv
```
