### ISSUE TITLE
"Import-module importexcel" gives version warning if started inside background job

### ISSUE THREAD

**Issue by xelsirko** [dfinke/ImportExcel#129]
Not a huge problem of course, but could be confusing.
$host.version.Major doesn't show proper powershell version inside background jobs. 
$PSVersionTable.PSVersion.Major - works fine, probably makes sense to use it instead.

PS C:\temp> import-module importexcel
PS C:\temp> $host.version.Major
5
PS C:\temp> start-job -ScriptBlock { import-module importexcel } | wait-job | Receive-Job
WARNING: PowerShell 5 is required for plot.ps1
WARNING: PowerShell Excel is ready, except for that functionality
PS C:\temp> start-job -ScriptBlock {$host.version.Major} | wait-job | Receive-Job
1
PS C:\temp> start-job -ScriptBlock {$PSVersionTable.PSVersion.Major} | wait-job | Receive-Job
5

**Comment by dfinke** [comment]
Thanks for logging.

**Comment by xelsirko** [comment]
Sure @dfinke , going to submit PR with the fix later this week.
