### ISSUE TITLE
Property value evaluated as invalid formula requires repair

### ISSUE THREAD

**Issue by msftrncs** [dfinke/ImportExcel#1292]
This creates a damanged xlsx file.

```PowerShell
[pscustomobject]@{Description = '=====TEST===='} | export-excel .\test.xlsx -WorksheetName 'test' -ClearSheet
```
![image](https://user-images.githubusercontent.com/26179051/197648681-da104e81-57bc-45ec-a521-b67d7cae63ca.png)

![image](https://user-images.githubusercontent.com/26179051/197648758-e5de5d9f-dd45-43a1-9542-3f53c3639f0d.png)

![image](https://user-images.githubusercontent.com/26179051/197648790-638eff01-ee51-4ffc-8f09-8d88a6dd88b7.png)

Is there a method/parameter to indicate that a property is strictly text and not to even be interpreted as a formula?  `-NoNumberConversion` handles only strictly the case when the value could be interpreted as a number.

Reading the file back in with `Open-ExcelPackage` I can confirm the value was taken as a formula:
```
Style                 : OfficeOpenXml.Style.ExcelStyle
StyleName             : Normal
StyleID               : 0
Value                 : 
Text                  : 
Formula               : ====TEST====
FormulaR1C1           : 
Hyperlink             : 
Merge                 : False
AutoFilter            : False
IsRichText            : False
IsArrayFormula        : False
RichText              : {}
Comment               : 
Worksheet             : test
FullAddress           : 'test'!A2
FullAddressAbsolute   : 'test'!$A$2
ConditionalFormatting : OfficeOpenXml.ConditionalFormatting.RangeConditionalFormatting
DataValidation        : OfficeOpenXml.DataValidation.RangeDataValidation
Current               : 
Address               : A2
Start                 : OfficeOpenXml.ExcelCellAddress
End                   : OfficeOpenXml.ExcelCellAddress
Table                 : 
IsName                : False
Rows                  : 1
Columns               : 1
```

**Comment by dfinke** [comment]
No, there is no way for designate as text vs formula.

You can add a single quote at the start.

```powershell
[pscustomobject]@{Description = "'=====TEST====" } | export-excel .\test.xlsx -WorksheetName 'test' -ClearSheet -Show
```

**Comment by msftrncs** [comment]
> You would have a similar issue if you did this directly in Excel.

If you mean entering `====TEST====` would be evaluated as a formula, YES, except I know to use `'====TEST====` and Excel will treat it as text, and it does NOT show the quote, if it even stores it.  When I Import-Excel with such an input, the quote is not returned.  If I put a single quote in front of the value when using Export-Excel, it is NOT the same as doing it in Excel, as now Excel displays the quote, and Import-Excel returns it.

I would think that there should be a means to signal that a column/property is strictly text (at least if it is `string` type), not to be interpreted as a formula, and also set the `QuotePrefix` style property where required to emulate the same behavior experienced within Excel.  This would be better than `-NoNumberConversion` as that still leaves the cell value in a way it could be reevaluated, if the `NumberFormat` style is not set to _Text_.

Alternately the automatic formula assumption could be disabled if the `NumberFormat` style is set to _Text_.  While Excel will accept switching the format to _Text_ after the formula is entered, you cannot enter a formula afterwards.

**Comment by dfinke** [comment]
This is an edge case. Need to think about it more.
