### ISSUE TITLE
-AutoNameRange or Set-ExcelName defaults to worksheet scope - Need to set to Global workbook scope

### ISSUE THREAD

**Issue by OldTimerJB** [dfinke/ImportExcel#1293]
I have not found a setting\switch that will allow me to set the defined named ranges to workbook scope from a worksheet scope.  
By default the functions are setting it to a worksheet and limiting where I can place my =INDIRECT() functions in Excel.  I need them on a central worksheet for drop downs in a form.  

I hope there is an easy fix for this but I am not finding it googling for it.

**Comment by dfinke** [comment]
Need to review this in detail and assess the impact. https://github.com/dfinke/ImportExcel/pull/988
