### ISSUE TITLE
[bug] Missing one Relationship tag in _rels\.rels

### ISSUE THREAD

**Issue by igordata** [dfinke/ImportExcel#1296]
Hello,

Thank you, guys, for that library. It's really useful.

I think I've met a rare bug and I don't really understand the conditions when it occurs. Let me describe how I have it as is.

I have a script. I have a csv file. I have a code to convert this csv file to xlsx. Here is the code:
```PowerShell
CsvToExcel($InFIle, $OutFile) {
    Import-Csv $InFile | Export-Excel -Path $OutFile
}
```
And it works fine if I run it standalone. It creates a good xlsx file.

If I run this code inside my script - I receive a bad xlsx file that cannot be opened in Excel.

After some debugging, I didn't find any factors that may impact the conversion. I renamed them to .zip, extracted and compared two files and the difference is that in the bad xlsx archive in the file `_rels\.rels` is missing some information.

Good `_rels\.rels`:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>
```

Bad `_rels\.rels`:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>
```

When I copied missing information to the bad file and re-zipped it and renamed it back to xlsx - Excel did finally open it correctly and there were no errors inside.

If you have any ideas about what causes that behavior and what can I do to force the creation of proper xlsx files - I'd appreciate it if you could share.

**Comment by dfinke** [comment]
Not sure. If you could post a script with more context to see what the issue is, that'd be good.

**Comment by igordata** [comment]
OK, after a profound investigation I found out the next.

1. If the target out excel file doesn't exist - the new excel file is created correctly.
2. If the out file already exists and is empty - the excel file is created incorrectly and my Excel app can't open it. The size differs, XML lacks one tag, see above.
3. if the out file already exists and is correctly formed - the out excel file is also created correctly and can be opened in the Excel app.
4. If the out file already exists and is a malformed version - the out excel file inherits the bug and can't be opened in the Excel app.

**Comment by igordata** [comment]
`Import-Csv 'some.csv' | Export-Excel -Path 'out.xlsx'`
This code is enough to reproduce the bug. You just need to create an empty file `out.xlsx` beforehand.
