### ISSUE TITLE
NoClobber throws a worksheet already exists error

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#13]
Sheet1 already exists.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:155 char:17

throw "$WorkSheetname already exists."

**Comment by schneider-netservices** [comment]
Isn't that by design? I mean, you test if the worksheet exists and then throw the exception yourself at line 131...

**Comment by dfinke** [comment]
Correct. I saw this posted on Facebook and put it here as a reminder to doubled check. 

Thank you.

**Comment by marthektheman** [comment]
thanks guys.  I was a little confused from the video because it said use the Force option to overwrite.  Then someone said use the noblobber option.  No biggie.   I just create a new spreadsheet every time  now with a date/time object.

**Comment by dfinke** [comment]
Good point. The video needs to be updated

**Comment by marthektheman** [comment]
All good.  It's good for going through the module and learning how it works.  So far everything looks good.  Thanks for the code!
