### ISSUE TITLE
"IBM437 is not supported encoding name" exception when saving Excel workbook on daily PS 7.3 build

### ISSUE THREAD

**Issue by kborowinski** [dfinke/ImportExcel#1309]
*"IBM437 is not supported encoding name"* exception is thrown when saving Excel workbook on daily PowerShell 7.3 build ([link to full issue on PowerShell repository](https://github.com/PowerShell/PowerShell/issues/18537))

**Comment by xtqqczze** [comment]
EPPlus attempts to call `System.Text.Encoding.GetEncoding("IBM437")`, but this fails due to changes in PowerShell internals.

**Comment by xtqqczze** [comment]
The ideal solution would be for ImportExcel to distribute a version of EPPlus targeting .NET Standard, but we can work around the issue in the module.
