### ISSUE TITLE
Add support for password protecting excel files

### ISSUE THREAD

**Issue by abajaj07** [dfinke/ImportExcel#1314]
Please add support for password protecting an excel file when run via Azure automation PowerShell runbook (or any non-excel installed environment).

For example: ability to do the below without invoking COM objects.

**$exportlocation = $env:TEMP
$date = Get-Date -Format 'yyyyMMdd'
$Exportfile=$exportlocation\SQLqueryresults-$date.xlsx**

**$ExcelObject=New-Object -ComObject excel.application
$ExcelObject.visible=$true
$ExcelObject.DisplayAlerts = $false**

**_#Open Excel file_**
**$Workbook = $ExcelObject.Workbooks.Open($Exportfile)**

**_#Save Excel with password_**
**$Workbook.SaveAs($Exportfile,51,"password",$null,$False,$False,1,2)**

**Comment by dfinke** [comment]
Does this work for your scenario? `Export-Excel -Password`

**Comment by abajaj07** [comment]
Thanks Doug. I have tested with Export-Excel -Password and it works perfectly for scripts run via Azure automation PowerShell runbook. Sorry I didn't see this switch earlier.
