### ISSUE TITLE
Import-Excel not working with basic Json file

### ISSUE THREAD

**Issue by PhilAlain** [dfinke/ImportExcel#1315]
Hello,

I am running a very basic powershell script with Import-Excel and it creates a corrupted Excel file.

Powershell script:
$test = @()
$test = (Get-Content .\Test.txt | Out-String | ConvertFrom-Json)    
$test | Export-Excel Test.xlsx -Show

Excel Error:
We found a problem with some content in 'Test.xlsx'. Do you want to recover as much as we can? If you trust the source of this workbook, click Yes.
Recovery works, but this error remains problematic.

Tests done:
Checked the Json validity of Test.json file against RFC checkers => Ok
ImportExcel version: 7.4.1
Powershell version 7.2.7

Sample json file is attached as Test.txt (json extension not supported in github)
[Test.txt](https://github.com/dfinke/ImportExcel/files/10033516/Test.txt)

**Comment by dfinke** [comment]
The `=>` is causing Excel the issue. I believe it is trying to interpret it as an `operator`.

You can strip it out, or add a `'` before it, or if you control how it is generated use different charaters.

```powershell
$test = Get-Content .\Test.txt  | ConvertFrom-Json | Where-Object { $_.log -notmatch '^=>' }
$test | Export-Excel .\Test.xlsx -AutoSize -Show
```

**Comment by PhilAlain** [comment]
Excellent explanation that fixes the issue perfectly!
We will manage the `=>` specifically.
