### ISSUE TITLE
Export Excel - Parameter NoHyperLinkConversion to avoid a String with a Colon causes the cell to be created with a hyperlink

### ISSUE THREAD

**Issue by vpaesa** [dfinke/ImportExcel#1316]
[See parent issue 1116:](https://github.com/dfinke/ImportExcel/issues/1116)

There are a lot of non-URL strings that IsWellFormedUriString is tagging as well formed URLs.
Example, this snippet returns True:

```
$v = 'aa:a'
[System.Uri]::IsWellFormedUriString($v , [System.UriKind]::Absolute)
```

May I ask to reconsider adding the -NoHyperLinkConversion parameter suggested in 1116?

**Comment by vpaesa** [comment]
Since [thkn-hofa](https://github.com/thkn-hofa)'s fix is merged into code, I guess it does not really matter the bot marking this issue as stale, right?

**Comment by dfinke** [comment]
I didn't close it. Does the fix work for you? If so, please close.
