### ISSUE TITLE
Writing multiple values to a range

### ISSUE THREAD

**Issue by nicolasr75** [dfinke/ImportExcel#1317]
First of all: what a great package and what flexibility it gives us, especially as it works on Linux too!

How can I write multiple value from an (in-memory) array to a 1D named range? F.e.

    $consumptions = @(1.234, 2.345, 3.45 etc.)   #Actually coming from a database

    $range = $excel.Workbook.Names["Consumptions"]

    Set-ExcelRange -Range $range -Value $consumptions

but this only writes the first value to all cells. I tried to loop on the range with index but
I don't understand what property to use.

Any short example or link to an example?

**Comment by stahler** [comment]
You can try converting the array to a string.
```powershell
$data = @(1.123, 2.234, 3.456) -join ', '
```
![image](https://user-images.githubusercontent.com/1991193/202924821-1622281a-839b-4f1f-8d77-f5b683be2683.png)

**Comment by dfinke** [comment]
@nicolasr75 Thanks! Would love to hear how you use it on Linux, https://github.com/dfinke/ImportExcel/discussions/categories/show-and-tell

**Comment by nicolasr75** [comment]
@stahler thanks for the quick response. Maybe I was not really clear but I want each value to fill one cell in the range. See here:
![ImportExcel](https://user-images.githubusercontent.com/3595142/202926241-33b89ceb-0700-4131-81ce-846c82db5412.png)

**Comment by nicolasr75** [comment]
@dfinke Done :-)

**Comment by dfinke** [comment]
You would need to shape the array first before exporting it. `Export-Excel` doesn't unroll properties.

**Comment by nicolasr75** [comment]
Well, if I'm correct, Export-Excel is for specifying a file. But in my case I usually have the file already opened because I have to write a dozen other things to it (copying an array to a range is just one thing). Let me show you how we do it in C# with Excel Interop:

        private void CopyArrayToExcel(Range r, object[,] values)
        {
            r = r.get_Resize(values.GetUpperBound(0) + 1, values.GetUpperBound(1) + 1);
            r.set_Value(Microsoft.Office.Interop.Excel.XlRangeValueDataType.xlRangeValueDefault, values);
        }

In this case it even supports a 2D array. You see that `set_Value` method on the Excel Range object? That is what
I am actually looking for in ImportExcel. Now, since there doesn't seem to exist an equivalent, I came up with this helper method in my class which accomplishes the task for a 1D array (I will try the 2D case later):

    [void] CopyArrayToRange($r, $arr) {

        $start = $r.Start
        $ws = $r.Worksheet

        for($i=0; $i -lt $arr.length; $i++) {
            $ws.Cells[$($start.Row + $i), $start.Column].Value = $arr[$i];
        }
    }

I'm  not sure if this is the most performant way, though.

**Comment by nicolasr75** [comment]
OK, I'll keep that in mind.

Well, most of the time I do C#. That's why I felt comfortable when PS introduced classes. Actually we have a class "ReportGenerator" that encapsulates diverse functionality for filling out Excel templates. Other people create/design these templates and my job is to fill in the data of the previous month. That's where my need to copy data to named ranges comes from.

From my side you can close the issue. Thanks for your help.
