### ISSUE TITLE
unable to use add-worksheet

### ISSUE THREAD

**Issue by tallyn** [dfinke/ImportExcel#132]
can't find any help or use examples for add-worksheet.

trying to import a csv file, and add it to an existing xlsx file as an additional worksheet.

pretty sure it is related to the excelpackage parameter, but I can't determine what is expected to be passed here.

any help or documentation would be appreciated

**Comment by dfinke** [comment]
Does this work?

`Import-Csv c:\temp\test.csv | Export-Excel c:\temp\existing.xlsx -WorkSheetName NewSheet`

**Comment by tallyn** [comment]
yup that does.

i was just trying to use the add-worksheet function directly.  thanks for the assistance
