### ISSUE TITLE
Compare workbook sheet column cell value against another workbook sheet cell value and parse information in row if =

### ISSUE THREAD

**Issue by royalkaige** [dfinke/ImportExcel#1323]
This module is insane with its capabilities. I am young in coding and am having some trouble figuring out how to accomplish the following. Any insight would be greatly appreciated.

What im trying to do:

I have two workbooks with different data - one contains machine names and last reboot time + extra data in columns. The other workbook has machine names, Execution date, execution output, etc etc in columns. 

Create new column in workbook1 (or pull all data into powershell and export all data to new workbook after manipulation)

Foreach (cell in Workbook1 column C = cell in Workbook2 column A){
                             #machine name                       #machine name
  IF (cell in Workbook1 = cell in Workbook2){

                            #copy the last reboot time cell to workbook1
    add cell in workbook2 column D to Workbook1 $NEWCOLUMN 
}

The reason for this approach is because Workbook1 has several entries of the same machine name based on how many times the action was executed. -- This brings up another aspect - 

I am also trying to filter by last execution date on any given machine name in Table format

$Range1 = workbook1 column C range

             #machine name
If (Workbook1 Column C Cell 1 <# + 1 each cycle#> =  any in $range1){   
 
 Compare Workbook1 Column A cell 1 against $range.value - If equal do nothing - If different Look at time/ date and place most recent date / time for machine at the top of table (Or hide the older value) (dont need to delete the others that match machine name - just need to filter) 
    }
    
Having issues filtering current Dates/times due to it being in HH:MM:SS AM\PM MM/DD/YYYY format all in one column and the need for the filtering to be at a machine basis not overall dates (Reason being some machines have several "executions" while others only have one and may be from over a month ago but still need to see the one entry for the one machine ran against on that date)

Please let me know if theres any pointers on how I can accomplish this. I have attached 2 example files as reference for what im trying to do. Sadly I wasnt able to make the Join-worksheet / Merge-multiple sheets work due to (I think) the reference file having several entries of the same machine. (when exported the new workbook / sheet had all of the difference file information missing)
    

    
[WorkBook1.xlsx](https://github.com/dfinke/ImportExcel/files/10063776/WorkBook1.xlsx)

 
[WorkBook2.xlsx](https://github.com/dfinke/ImportExcel/files/10063774/WorkBook2.xlsx)

**Comment by dfinke** [comment]
Thanks for the kind words. Yeah, this seems to be more of a "data processing" PowerShell question, not a PS+Excel question.

Off the top of my head, I would read the data from both sheets `Import-Excel`. Then do all my comparison work in PS, create another array of records in the shape I want, and then Export-Excel that.
