### ISSUE TITLE
Adding Formulas to Worksheet

### ISSUE THREAD

**Issue by Shooting300FPS** [dfinke/ImportExcel#1326]
I'm working on combining data from multiple CSV files into 1 XLSX file.  This is going good.  I'm having problems adding formulas to several of the columns.  I have the problem narrowed down to any equation that has "" in it.  For example, this command works without any problem and the formula is added to all of the needed rows:
Set-Column -Worksheet $ws -Heading $Header -Value {"=ISNUMBER(MATCH(G$row,SCCM!A:A,0))"}

However, when I have a formula that utilizes "" anywhere in it, the equation isn't added to the Worksheet
Set-Column -Worksheet $ws -Heading $Header -Value {"=IF(C$row<>"",YEAR(C$row))"}
Set-Column -Worksheet $ws -Heading $Header -Value {"=L$row& " " &M$row"}
or
Set-Column -Worksheet $ws -Heading $Header -Value {"=IF(F$row="Value1","Result1","Result2")"}

I have tried using single quotes, but I get the same result
Set-Column -Worksheet $ws -Heading $Header -Value {'=L$row& " " &M$row'}

**Comment by dfinke** [comment]
Excellent!

Instead of:
```powershell
Set-Column -Worksheet $ws -Heading $Header -Value {"=IF(C$row<>"",YEAR(C$row))"}
```
See if this works:
```powershell
$formula = '=IF(C{0}<>"",YEAR(C{0}))' -f $row
Set-Column -Worksheet $ws -Heading $Header -Value $formula
```

**Comment by Shooting300FPS** [comment]
Thanks for the suggestion.  It got me closer and no longer have an XM  The equation is now being added to the worksheet, but the row isn't incrementing as it is added to the entire column, i.e,  all 16,758 cells have the same equation:
=IF(C2<>"",YEAR(C2))
or what ever value $row currently holds.

**Comment by dfinke** [comment]
You need to increment the row if you approach it this way.
