### ISSUE TITLE
Import-Excel error: Exception calling "Load" with "1" argument(s): "  Bad signature (0x0000041D)

### ISSUE THREAD

**Issue by loicyannou** [dfinke/ImportExcel#1329]
Hello
I'm using this module (7.8.3) to import data of XLSX files.
For a couple of days, I'm meeting this error:
```
Exception calling "Load" with "1" argument(s): "  Bad signature (0x0000041D) at position  0x0000017C"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.8.3\Public\Import-Excel.ps1:125 char:24
+                 else { $ExcelPackage.Load($stream) }
```
When it happens, I have to open the XLSX file with Excel and save it. Then, import-excel command runs with no error.
It's like if the file was corrupted (or not using the right format). Yet, Excel is able to open it.
I contacted the company providing those XLSX files to know whether it recently changed the export process, because my script is still able to open XLSX files created before november the 28th.
Also, I compared the files created 11/27 (working) and 11/28 (not working) and I can't see no difference (data is exactly the same).
Any idea, please ?
Best

**Comment by dfinke** [comment]
Can you open a simple xlsx you create with Excel to get a sanity check that the module is not working?

Maybe re-install? Install an older version of ImportExcel to see if that causes the same issue?

**Comment by loicyannou** [comment]
Hello
The company providing those XLSX files confirmed that they changed the way those XLSX files are built:
> Indeed we made some updates to our reports infrastructure on that date that might have effected the PS module you are 
using. The main change was updating our Java libraries and mitigating some security issue. So it is logical that other, non excel, modules might were effected. As such files should be open in Excel, there is nothing much we can do about external modules that are not Excel.
Best

**Comment by thkn-hofa** [comment]
Maybe this would be fixed with a newer EPPlus DLL but I think there's a reason why @dfinke is on the second to last version under LGPL. Maybe a license issue because the new license is non-commercial or because version 5 introduced a breaking change that makes row and column numbers zero-based in stead of one-based. 

Dropping in the newer DLL probably isn't an easy option to test it out.

**Comment by dfinke** [comment]
@thkn-hofa yes. A number of the unit tests fail amongst other things. It could open a whole new set of problems, and they moved onto a completely new offering, requiring a paid license.

**Comment by tamahau30494** [comment]
I am having the same issue. Have any solutions have been found?

**Comment by dfinke** [comment]
no, there has been no resolution.

**Comment by prodtech22** [comment]
I am having the same issue with files created by PeopleSoft 8.58 - this was working fine before the upgrade. If I open and save the file and then use again import-excel on the new saved file, it works.

**Comment by dfinke** [comment]
@prodtech22 The upgrade was on the PeopleSoft side?

**Comment by prodtech22** [comment]
Yes. One thing I just discovered, and just tested it, is that by removing the signature on the file and saving it, the conversion works.

**Comment by prodtech22** [comment]
So now I have to figure out how to script removing the signature so I can automate it

**Comment by dfinke** [comment]
Not familiar with that, "signature". They sign the xlsx?

**Comment by prodtech22** [comment]
It's the 'author', the user who created the file

**Comment by prodtech22** [comment]
[cid:940bcedd-4b63-4371-b1fd-06d538215521]
________________________________

**Comment by prodtech22** [comment]
If I remove that, import-excel works. Well, until now I tested it by manually removing the signature and saving the file. I hope it still works works if I figure out how to do via script.
[cid:a753a782-8b8e-4bcb-91d0-aaf3ff5c4c67]
________________________________

**Comment by dfinke** [comment]
Nothing in the module accesses "author". Not sure if can be done. Please post if you find a way.

**Comment by prodtech22** [comment]
I will, thank you!
________________________________

**Comment by prodtech22** [comment]
We discovered an encoding issue on the Excel files coming from Peoplesoft after upgrade. We were looking at 2 different solutions - open and save the file OR remove the 'author' from the file (in this case Apache POI); they both work but they require Excel installed on the server and we were not willing to do that. My co-worker tried a different approach that seems to work - created a .bat file running 7zip, which runs ahead of the import-excel in the PowerShell script, that will decompress and recompress the file then run the normal import-excel module.

________________________________

**Comment by dfinke** [comment]
FWIW there is:

 https://github.com/dfinke/ImportExcel/blob/24e5fccafe774bf14444728492813711e4a889f0/Private/Invoke-ExcelReZipFile.ps1#L1

Plus there is a `-ReZip` switch on `Export-Excel`

But, `bat` FTW!

**Comment by tamahau30494** [comment]
Here is the function I am using to workaround the issue.

As someone stated above, This solution requires Excel to be installed on the system the script is running on.

`Function FixExcelFile
{
    param
    (
        [Parameter(Mandatory=$true)] [string] $filePath
    )

    $xl=New-Object -ComObject "Excel.Application"

    $wb=$xl.Workbooks.Open($filePath)
    $xl.DisplayAlerts = $FALSE

    $wb.Save()

    $wb.Close()
    $xl.Quit()

    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($wb)
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($xl)

    Remove-Variable wb
    Remove-Variable xl
}
`

It would be great to have a fix made to the PS module in the future!

**Comment by dfinke** [comment]
@tamahau30494 do you know what the fix would be?

**Comment by scriptkiddy666** [comment]
@dfinke I've just implemented it like the following in my script:

```
[System.String]$Path7Zip = "$($Env:ProgramFiles)\7-Zip\7z.exe"
[System.String]$File = "$($Env:Temp)\File.xlsx"
[System.String]$PathTemp = "$($Env:Temp)\Folder"
[System.String]$PathXml = "$($PathTemp)\docProps\core.xml"
[System.Xml.XmlDocument]$Xml = $null
[System.Object]$Content = $null
[System.Object]$Result = $null

$Result = Start-Process -FilePath $Path7Zip -ArgumentList @('x', "`"$File`"", "-o$($PathTemp)") -Wait -PassThru -WindowStyle 'Hidden'

if ($Result.ExitCode -eq 0) {
    $Xml = Get-Content -Path $PathXml
    $Xml.coreProperties.creator = ''
    $Xml.Save($PathXml)
    
    $Result = Start-Process -FilePath $Path7Zip -ArgumentList @('a', '-tzip', "`"$File`"", "$($PathTemp)\*") -Wait -PassThru -WindowStyle 'Hidden'
    
    if ($Result.ExitCode -eq 0) {
        if (Test-Path $PathTemp) {
            Remove-Item -Path $PathTemp -Recurse -Force
        }
    
        $Content = Import-Excel -Path $File -WorksheetName $WorksheetName
    } else {
        throw "Couldn't remove creator property of Excel file, can't fix Excel file"
    }
} else {
    throw "Extraction of file $($File) failed, can't fix Excel file"
}
```

("Apache POI" was the creator as well and files started to break a few weeks ago.)

**Comment by dfinke** [comment]
@scriptkiddy666 can you say a bit more about this and what it addresses?

**Comment by scriptkiddy666** [comment]
It's my "batch file" version of what @prodtech22 wrote about in this comment:
https://github.com/dfinke/ImportExcel/issues/1329#issuecomment-1450595220

Because I got the same error message from the title of the issue and with the code I posted earlier I was able to import my affected (externally created) Excel files again without the need to open and save them manually with Excel.
