### ISSUE TITLE
windows 2012 R2 server install

### ISSUE THREAD

**Issue by sigmondfroid01** [dfinke/ImportExcel#133]
I installed the code on my win 2012 R2 server and everything installed correctly, however when I try to run the export-excel with the -show command when it comes back it opens up the xlsx file as a text file that looks like garbage.  I can copy it to my workstation that has excel installed and it opens and looks fine.  Is there something that I am missing on the server that is not allowing it to open the worksheet?

**Comment by dfinke** [comment]
When you say you "copy it to my workstation", you mean you copy the newly created Excel file?

Do you have Excel installed on the server?

**Comment by sigmondfroid01** [comment]
I figured out the issue, excel is not installed on the server so I won't be able to view it there.  I get it now it allows you to run the code for excel on the servers where I am running the powershell which before I could not because excel is not installed there, but it won't let you view it unless you have excel on the server.  So it is a matter of moving that created xlsx file over to where I have excel installed to view the results, correct?

**Comment by dfinke** [comment]
That's right. Some folks access the created xlsx from a share or use PowerShell to email the file.
