### ISSUE TITLE
Compare a date field

### ISSUE THREAD

**Issue by sturag** [dfinke/ImportExcel#1330]
Hey!
First, thanks for one of the best cmdlets out there :)
Im generating an excel file that has a cloumn for a date.
I want to do a conditional formating on that column, if the date is between today and in 2 years, i want to mark that row red.
How can i do that?
Thanks

**Comment by dfinke** [comment]
Check out the Example in general https://github.com/dfinke/ImportExcel/tree/master/Examples and specifically 
https://github.com/dfinke/ImportExcel/tree/master/Examples/ConditionalFormatting
