### ISSUE TITLE
detected Heur.BZC.ZFV.Boxter.851.9302B93B in the latest version

### ISSUE THREAD

**Issue by MoniBon** [dfinke/ImportExcel#1335]
I've installed the latest version of the module and when importing/loading it... BitDefender antivirus keeps shouting "PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.851.9302B93B and was blocked. Your device is safe."  Anyone else had similar issues?  Thanks.

**Comment by dfinke** [comment]
Have not seen or heard. Still an issue?

**Comment by MoniBon** [comment]
Unfortunately, yes. I even installed older versions going back 2 years and still get it. I submitted it as a possible false positive 6 days ago ( knowing that they/Bitdefender reviews issues in 72h max) but it looks like they dont consider it a false positive yet. I'm supposed to install it on client site and I literally dont know what to do... many thanks
