### ISSUE TITLE
How to identify column/row numbers based on name?

### ISSUE THREAD

**Issue by teknowledgist** [dfinke/ImportExcel#1337]
Noob question...

Some features (like `-TableTotalSettings`) can use column name references which is great when I don't know the order of the input data.  However, many other features (like `set-column` and `set-format`) appear to require column letters.  

How do I discover the column letter based on the column name?

thanks

**Comment by dfinke** [comment]
There is `Get-ExcelColumnName` but thatis based on a number. You could use psobject.properties.name, loop thru, get the # and pass that to get the column letter.

**Comment by teknowledgist** [comment]
Hrmm... I'm not sure what you mean.  I have:

```PowerShell
$inputFile = '.\email_Fund Ledger.xlsx'
$outputFile = '.\test.xlsx'
Remove-Item $outputFile -Force

$Fund = Import-Excel $inputFile
$Fund | Export-Excel $outputFile -AutoSize -WorksheetName 'Raw Data'

$Special = $Fund | Where-Object {($_.'fund type' -eq 'Allocated fund') -and 
                                 ($_.'Fund External Id' -ne '123456-78')}

$TotalSettings = @{ 
   'Fund Ledger name' = '="Total"'
   'Transaction Expenditure Amount' = "=SUM([Transaction Expenditure Amount])"
}

$excel = $Special | Export-Excel -Path $outputFile  -WorksheetName 'Special Funds' -TableName 'Special' -TableTotalSettings $TotalSettings -PassThru

$ws = $excel.Workbook.Worksheets['Special Funds']
```

If the next line is:

`Set-ExcelColumn -Worksheet $ws -Column 8 -Width 20 -NumberFormat 'Currency'`

that works, but:

`Set-ExcelColumn -Worksheet $ws -Column '[Transaction Expenditure Amount]' -Width 20 -NumberFormat 'Currency'`

or 

`Set-ExcelRange -Worksheet $ws -Range '[Transaction Expenditure Amount]:[Transaction Expenditure Amount]' -NumberFormat 'Currency'`

does not.  I'm not sure how to use `Get-ExcelColumnName`.  For my example above, it just gives me:

```
> get-excelcolumnname

ColumnNumber ColumnName
------------ ----------
           1 A
```

What might be helpful is a function to build a hashtable of column letter/number and name.  Maybe allow the user to select which row the name comes from (defaulting to 1)?

Thanks.

**Comment by dfinke** [comment]
Didn't test this. It's how I'd start. Not sure I'll add it to the module.

```powershell
function Find-PropertyNameIndex {
    param(
        $target,
        $propertyName
    )
        
    $names = $target[0].psobject.properties.Name
    for ($idx = 0; $idx -lt $names.Count; $idx++) {
        if ($names[$idx] -eq $propertyName) {
            return $idx
        }

        -1
    }
}

$idx = Find-PropertyNameIndex $Fund 'Transaction Expenditure Amount'
Get-ExcelColumnName $idx
```

**Comment by teknowledgist** [comment]
Very good.  (The `-1` is a typo, I think.  Also, it should return `$idx + 1`, right?)

I wasn't sure it was as simple as that because I didn't know the properties order was the same as the columns.  The custom objects I've built don't seem to have an order for the properties.

This is more what I was thinking:

```powershell
function Get-ColumnNameIndex {
   param(
      $Sheet
   )

   $names = $Sheet[0].psobject.properties.Name
   $ColumnNames = @{}
   for ($idx = 0; $idx -lt $names.Count; $idx++) {
      $ColumnNames.Add($names[$idx],$idx + 1)
   }
   return $ColumnNames
}

$ColumnNames = Get-ColumnNameIndex $fund
```

Then, I can just get whatever column index I want. E.G. `$ColumnNames.'Transaction Expenditure Amount'`.

Thanks!

**Comment by dfinke** [comment]
The -1 was to indicate not found. The idx offset is right, and yes `Get-ExcelCollumnName` starts at 1.  I tend to keep my "functions" separate, and it would've been more accurate to do `Get-ExcelColumnName ($idx+1)`.

Yep, returning a hash is a way to go.
