### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by teknowledgist** [dfinke/ImportExcel#1338]
I'm really struggling without even rudimentary documentation.  Examples are OK for some things, but require a lot of random browsing and piecing together of disparate pieces.  

I can see that this is incredibly complete and useful, but the inefficient way I have to learn it is weighing on me.  Any chance for at least a basic index in [the wiki](https://github.com/dfinke/ImportExcel/wiki) with simple descriptions so we can search.  

For an example of which I am familiar, [Chocolatey has a categorized reference](https://docs.chocolatey.org/en-us/create/functions/) for all the included functions, and it mostly just presents the output of the help with a "friendlier" display than the command line.

Thanks!

**Comment by teknowledgist** [comment]
It's a bit old, but this ostensibly describes how to automatically convert comment-based help to markdown.

https://get-powershellblog.blogspot.com/2017/03/write-faq-n-manual-part1.html

**Comment by dfinke** [comment]
There was an attempt by someone to build this out. It is tough to maintain and a lot of effort to create.

May get back to it at some point.

https://github.com/dfinke/ImportExcel/blob/c848497f53ca811ba8910382f982e8afdb953248/CI/PS-CI.ps1#L168
https://github.com/dfinke/ImportExcel/tree/c848497f53ca811ba8910382f982e8afdb953248/mdHelp/en

**Comment by teknowledgist** [comment]
It's a start at least.  Having the markdown get-help is better than nothing.  I still feel like I am missing some fundamental concepts, but I definitely appreciate that documentation is  PITA.  

Thanks.

**Comment by dfinke** [comment]
Besides the Chocolatey approach. Can you say a bit more about what helps you to learn this?

I learn best by examples, hence, the examples folder. Helped me capture what I was doing and a place I could come back to so I could remember what I was trying.

**Comment by teknowledgist** [comment]
Heh.  Well, Chocolatey was a ton of trial and error (and other, descriptive documentation), but I was doing it for fun.  

I'm trying to get something set up with ImportExcel for work, so there is a bit of pressure to do it faster.  

I think examples are great when there aren't so may options.  If a user finds an example that closely matches what they are trying to do, it can be extremely helpful, but ImportExcel is so robust with such a vast playground of options, it would take a thousand examples to cover it all.  Few of the examples feel close enough for me to "get it", but with every example, I'm never sure if the next one will be better for my needs.  

Although I've done a fair amount with PowerShell, I don't consider myself a programmer by any stretch.  I am very aware that there (possibly, important) holes in my knowledge.  The same is true with Excel.  Maybe that is where my difficulty stems from, but maybe an introduction to ImportExcel for folks who aren't particularly strong in PowerShell nor particularly strong in Excel would bridge the gap?

Take my other question about identifying columns for example... In Excel, I know how to reference a column, row or cell by letter/number, and (learning only the other day) that they can be referenced by name (or is that for a table?), and I also know how to reference values in an array in PowerShell.   I also know that PowerShell objects (specifically hash tables) don't necessarily return attributes in any particular order.  Thus, how to translate the column that in some cases can be referenced by name into a required reference by letter (and/or array number)?  

Sorry, I'm rambling.  I appreciate the question, and will think about how a good introduction might work.

**Comment by dfinke** [comment]
Thanks for the response. Yes this is a challenge and I wing how I teach this through "documentation".

Check out my playlist I did on ImportExcel. It may help, although it is again talking through examples.

https://www.youtube.com/playlist?list=PL5uoqS92stXioZw-u-ze_NtvSo0k0K0kq

Maybe we can connect outside of GitHub and you can tell me a bit more about what you need to get done, and I can figure out if I can help?

**Comment by teknowledgist** [comment]
@dfinke That is very generous of you.  I hate to take your time with my ignorant questions.  I don't think of myself as a noob with respect to PowerShell (or Excel), but the gap between my skills and any MVP makes it very clear that I'm just a step or two above a script kiddie.  

That sequence of videos was a nice start.  I do think there is room for examples in-between the "Hello World" and "Make Excel Data Pop" and "Slice and Dice Data".  There are a lot of people who use Excel who don't use conditional formatting or even know what a pivot table is.  Maybe you could show how to directly (i.e. not conditionally) format cells/rows/columns, or delete or re-arrange columns or sort rows from an existing set of data, or how to strip some leading characters from all cells in a range?  There are a lot of simple arrangement/display options that folks might want.  I know at least some of those have examples in this repo, but a lot of folks like the video format.

I would also suggest that the text examples here be ordered in complexity sort of how that video series is ordered.  Allowing folks to go through examples in a sequential way that starts simple and builds on previous examples could help new users grow in their knowledge.  Immersion in a foreign language may be the fastest way to learn, but it is very confusing for a while and can lead to significant gaps.  If you lay the ground work of a simple vocabulary and grammar structure, then those more complicated "example" sentences can be broken apart for better understanding.  😄 

Certainly pretty trivial, beginner stuff for Excel use, but that is what I'm being asked to do.  Basically, we are trying to automate some work that a low-level employee can do, but why make them spend those 10 minutes a day when we can automate it?

I've figured out a lot of what I need to do.  Where I'm stuck is that a lot of the formatting I need (like setting a column as "money") is only possible if I know the column letter/number.  I haven't found an example of how to determine that.  At the moment, I know which column is which, but I can't guarantee that in the future there won't be additional columns or the order changes.  I can use column name references for the `-tabletotalsettings` option, but nowhere else.  

I'd actually rather not use those named references at all since (and this is going to sound crazy) I don't actually have Excel on my sysadmin workstation.  I use LibreOffice Calc <ducks> so testing my code requires opening the result on another computer. Although for the last 15+ years I've been using Calc, I haven't encountered an incompatibility that affected my use of an .xls or .xlsx spreadsheet (probably because I work with very simple spreadsheets), named references is one.

If you would rather discuss this or anything else outside of GitHub, my username here is also a gmail account name.

Thanks!

**Comment by dfinke** [comment]
Thanks for the feedback, my offer stands. I learn too, and can make the module/doc better.

I will think through this and see what I can come up with.

**Comment by dfinke** [comment]
@oliwex, @teknowledgist that would be great, it takes effort. This module grew out of how I wanted to use it, so the examples etc are from what I thought was cool and or useful.

Happy to do set up a half hour zoom call with either or both of you and walk through some things.

Could turn into a list of ToDo items for all of us and maybe get some questions answered.

**Comment by oliwex** [comment]
to be honest, i write that because 2 things:
1.I try to learn git -> creating pull request and collaborating
2.Try to learn powershell -> look my repo
3.Make side project which help me in my work and i use that module.

3 -> The problem is that the module is fine, but lack of good docs is big problem, because people want to use it, but cannot, because not so much of good examples.

I think that module is the same as @PrzemyslawKlys and his excel module. It is great, examples a little bit better but no charts and few things.

If i try to help i can code step by step and maybe one example per week, because of time.

**Comment by dfinke** [comment]
Makes sense. To be clear, PrzemyslawKlys was started after mine, and pretty much, based on mine.

His has 80,000 downloads, ImportExcel, over 2 million. Even with "questionable" docs.

I hear and understand the feedback. My skill is more in creating software and I struggle to document it.

**Comment by thkn-hofa** [comment]
> I've figured out a lot of what I need to do. Where I'm stuck is that a lot of the formatting I need (like setting a column as "money") is only possible if I know the column letter/number. I haven't found an example of how to determine that. At the moment, I know which column is which, but I can't guarantee that in the future there won't be additional columns or the order changes. I can use column name references for the `-tabletotalsettings` option, but nowhere else.

<offtopic>
Hey, I wrote that (-TableTotalSettings) a few weeks ago. Glad you like it!
</offtopic>

**Comment by dfinke** [comment]
@thkn-hofa yep, thanks for the addition of `-TableTotalSettings`, cool feature.
