### ISSUE TITLE
Importing Excel workbooks in Strict Open XML Spreadsheet (*.xlsx) format fails

### ISSUE THREAD

**Issue by krusch** [dfinke/ImportExcel#1339]
Importing Excel workbooks in Strict Open XML Spreadsheet (*.xlsx) format fails:

```
WARNING: Selecting columns 1 to 0 might give odd results.
Failed importing the Excel workbook 'excel-import-test.xlsx' with worksheet '':
Failed creating property names: Cannot index into a null array.
At ...\ImportExcel\7.1.1\Public\Import-Excel.ps1:216 char:21
+ ...     catch { throw "Failed importing the Excel workbook '$Path' with w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed importin...o a null array.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook 'excel-import-test.xlsx' with worksheet '': Failed creating property names: Cannot index into a null array.
```

Note that the worksheet name is empty.
[excel-import-test.xlsx](https://github.com/dfinke/ImportExcel/files/10177387/excel-import-test.xlsx)

**Comment by dfinke** [comment]
Need to take a look. The first row which become the headers, Col1 and Col2 are valid columns in Excel. Not sure why, need to look, not sure the effort of changing that behavoir.

Changing the headers lets you read it

```powershell
Import-Excel .\excel-import-test1.xlsx -HeaderName 'Colx1','Colx2'
```

**Comment by krusch** [comment]
Any suggestions how to process files where the headers are not known, short of reading the file twice, once to obtain the header names from the first row, and then again to read the file with specified header names?

**Comment by dfinke** [comment]
Hmm, best if you know your data. There is something off with your xlsx, don't know what.

In my example, I renamed your headers so it could work. I used it on an xlsx I created though.

`Import-Excel excel-import-test.xlsx` is designed to read the sheet and set up the headers from the first row.

**Comment by krusch** [comment]
OfficeOpenXml.ExcelPackage does not support Strict OOXML:
https://github.com/JanKallman/EPPlus/issues/134

**Comment by dfinke** [comment]
That looks like it has been around for a while. It seems to be at the EPPlus layer, don't know if I can resolve that.
