### ISSUE TITLE
ConditionalType of 'Equal' creates invalid rule

### ISSUE THREAD

**Issue by kkalitowski** [dfinke/ImportExcel#134]
Given this code
`-ConditionalText (New-ConditionalText -ConditionalType Equal 'Yes')`

The rule in Excel contains an extra '=' in the typed portion of the rule, causing the rule to not function correctly. If the '=' is manually removed, the rule functions as intended.  Excel 2016.

![image](https://cloud.githubusercontent.com/assets/2752954/19562816/58c3e888-96a3-11e6-86ef-25f3d790b1c3.png)

**Comment by dfinke** [comment]
Wow, not good. I'm not setting that extra `=`, must be the underlying library I'm using (that I don't have ready access to). Also the `NotEqual` has the same issue.

## Workaround
Add double quotes inside the single quotes.

`(New-ConditionalText -ConditionalType Equal '"Yes"')`

I'll investigate further.
