### ISSUE TITLE
FreezeTopRow

### ISSUE THREAD

**Issue by mscreations** [dfinke/ImportExcel#1344]
There is a bug in Export-Excel.ps1 on [Line 497](https://github.com/dfinke/ImportExcel/blob/master/Public/Export-Excel.ps1#L497). It should be `$ws.View.FreezePanes(3, 1)`. I would make a pull request, but I can't on the company computer I'm on and my laptop is broken at the moment.

**Comment by dfinke** [comment]
Thanks! I hope your dog didn't eat your homework too 😆

**Comment by dfinke** [comment]
Could you post a short script that repros this?

**Comment by mscreations** [comment]
I call the function like this. Row 1 has the Title, and row 2 has the headers for the table. Without changing the line above to `3, 1`, only the Title is locked. The header rows disappear when I scroll. 

`Export-Excel -InputObject $Data -Path $OutputFile -TableName $SheetName.Replace(' ', '_') -WorksheetName $SheetName -AutoSize -FreezeTopRow -TableStyle $TableStyle -Title $SheetName -TitleBold -TitleSize 18`

Funny you mention a dog... He's the reason my laptop is broken. He has no boundaries.

**Comment by dfinke** [comment]
Lol, that is hilarious, sorry, and not funny. Those pooches ...
Thanks for the repro, I will take a look.

**Comment by dfinke** [comment]
I'll take a deeper look when I can.

You can use `-FreezePane 3, 1` instead.

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = ".\test.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data | Export-Excel $xlfile -AutoSize -FreezePane 3, 1 -TableName "Test" -Title "Test" -TitleBold -TitleSize 18 -Show
```
