### ISSUE TITLE
Data lost when some column headers are blank

### ISSUE THREAD

**Issue by teknowledgist** [dfinke/ImportExcel#1345]
I must be misunderstanding or not doing something right because I **can't** be the first person to find this.

Importing a spreadsheet of `X` columns of data with `Y` blank column headers (first import row):

```powershell
$inputFile = '.\InputTest.xlsx'
$outputFile = '.\OutputTest.xlsx'
Remove-Item $outputFile -Force

$Fund = Import-Excel $inputFile -startrow 3
$Fund | Export-Excel $outputFile
```

gives me a spreadsheet of `X-Y` columns.  The data in the columns that didn't have headers is entirely missing!  Interestingly, deleting all data from a row in the middle (i.e. leaving the row blank) is still captured and preserved.  

Of course, why would anyone have a spreadsheet of data with some empty column headers?  I dunno, but IMHO the data still shouldn't be ignored!

Thanks!

**Comment by dfinke** [comment]
please post the input file

**Comment by teknowledgist** [comment]
Here is a stripped down, anonymized file I tested against.
[EmptyHeaderTest.xlsx](https://github.com/dfinke/ImportExcel/files/10260767/EmptyHeaderTest.xlsx)

Just to be clear, I don't expect to receive files with missing headers.  I was playing with [the other issue I raised about identifying column names](https://github.com/dfinke/ImportExcel/issues/1337) and just wondered what would happen if a column had an empty column header.  You know, poking at edge cases.  😄 

I have since noticed that in addition to `import-excel`, there is also an `open-excelpackage` function that seems to not "lose" the data, but also seems to require a very different approach than the majority, import/export examples.  Do you have a comparison of functionality for 'open-excelpackage' vs `import-excel`?

Thanks.

**Comment by dfinke** [comment]
`Import-Excel` *defaults* to reading the headings in row 1, similar to how `Import-Csv` expects the headings in the first line.

The first two rows in your xlsx determine how it attempts to process the data.

## Try:

`Import-Excel C:\Users\finke\Downloads\EmptyHeaderTest.xlsx -StartRow 3`

**Comment by teknowledgist** [comment]
Yup.  I did use the `-startrow` switch.  See my example in the original post.  😄 

Also, if I strip the top, empty rows (so that the headings are in row 1) and don't use the `-startrow` switch, the same ignore-the-column/data loss occurs.

**Comment by dfinke** [comment]
It looked like I got all the data. Which data was missing for you?

**Comment by teknowledgist** [comment]
Column "F" in the example file is completely missing (i.e. removed) in the export file.  The dimensions of the data in the input file  are A3:K14 (and we are ignoring the first two rows with `-startrow 3`), but the output file is A1:J12.  I.E. one less column.  The information that was in F:F, is absent from the output.  

I tested this with a table with two blank headers, and the output was missing both of those columns.

**Comment by dfinke** [comment]
It's not missing, it doesn't have a header. Yes, if a column does not have one, it does not import that.

**Comment by teknowledgist** [comment]
Sorry, I'm confused with your answer.  

```powershell
$Fund = import-excel .\EmptyHeaderTest.xlsx -StartRow 3
$Fund | Export-Excel .\Output.xlsx
```

The `Output.xlsx` file will have missing data that was present in the `EmptyHeaderTest.xslx`.  Is that not true?

If that is expected behavior, then it seems like something important to know.  Maybe import-excel should throw a warning that not all data was imported because some columns were missing a header?

**Comment by dfinke** [comment]
Nope, that's not how it works. Doesn't throw. You need to know your data. No having a header for that column, you need to scrub your data

**Comment by scriptingstudio** [comment]
## Enhancement: fill gaps with pattern
line 99
```powershell
# Original
$sheet.Cells[$StartRow, $C] | Where-Object { -not [string]::IsNullOrEmpty($_.Value) } | Select-Object @{N = 'Column'; E = { $C } }, Value

# Refactored
$sheet.Cells[$StartRow, $C] | Foreach-Object -begin {$cc = 1} -process {
	if ([string]::IsNullOrEmpty($_.Value)) {$_.Value = "Column$($cc++)"}
	$_
} | Select-Object @{N = 'Column'; E = { $C } }, Value
```

## Workaround
```powershell
$Fund = Import-Excel $inputFile -startrow 4 -header <your_header>
```

**Comment by dfinke** [comment]
Had considered that early on. Similar to how import-csv works. Opted not to. Not sure how much this would impact as a breaking change. Going to take a look at how python pandas implements this

**Comment by scriptingstudio** [comment]
Such simple cases lead the user to a stalemate.
One of the option is to introduce switch parameter `-fixheader` but I would prefer automatic solution. That is what computers for.

**Comment by dfinke** [comment]
Maybe, first time this has come up, been out for years. Looked at some pandas, and it does things with missing headers. Folks have issues with it creating headers automatically. 🤷‍♂️

**Comment by teknowledgist** [comment]
IMHO, unacknowledged potential data loss is more of a problem than automatic headers.  

The reason I stumbled on this issue in the first place is because I didn't want to trust the order (or count) of the imported columns and was thinking about automated options for column identification.  The `-header` workaround itself isn't automatic.

However, a `-fixheader` switch that doesn't do anything if all the headers are present would be a solution that makes sense to me.  IOW, the current behavior remains unless the `-fixheader` switch is used *and* there are empty headers.  If you can't be automatic in the first place, at least this is less manual than knowing all the column headers.  

Thanks for considering it.
