### ISSUE TITLE
Export-Excel to same file name

### ISSUE THREAD

**Issue by crimsonread** [dfinke/ImportExcel#1348]
Hi,

As I remember, When I run Export-Excel -Path C:\test.xlsx, if test.xlsx is existed in the same path, the file was overwrited.
But, now I found if the same file is existed, it did not overwrite the file. Is it normal behavior?
FYI, I did not specify append switch.

Thanks.

**Comment by dfinke** [comment]
Best to check and remove the xlsx file then export if you want it overwritten.
