### ISSUE TITLE
ConvertFrom-Excelsheet puts values between quotation marks

### ISSUE THREAD

**Issue by VosPvD** [dfinke/ImportExcel#135]
Hello,

When I convert a .xlsx file to .csv using ConvertFrom-Excelsheet (ConvertFrom-ExcelSheet <filename>.xlsx .\csv sheet1 -Delimiter ";") the values are put between quotation marks in the generated .csv:

"Username";"Country";"Cluster";"Company"

[Security.xlsx](https://github.com/dfinke/ImportExcel/files/544500/Security.xlsx)

[Sheet1.csv.txt](https://github.com/dfinke/ImportExcel/files/544501/Sheet1.csv.txt)
(Remove the .txt extension, I had to add this to be able to upload it)

Is there a way to convert without the quotation marks?

**Comment by dfinke** [comment]
The function uses PowerShell's `Export-Csv` function to generate the end result, and I believe as a rule it puts text in quotes. I'm not aware of a way to bypass that.

You could do this after the `ConvertFrom-ExcelSheet`
```powershell
$fn="C:\Sheet1.csv.txt"
(Get-Content -Raw $fn) -replace '"',"" | Set-Content $fn
```

**Comment by VosPvD** [comment]
Thanks, that works!

I have another issue, when Converting an .xlsx to a .csv it only converts the first two columns. Am I missing something or are there functions that the command cannot translate?

[Test.xlsx](https://github.com/dfinke/ImportExcel/files/547197/Test.xlsx)

[Sheet1.csv.txt](https://github.com/dfinke/ImportExcel/files/547199/Sheet1.csv.txt)
(Again, remove the .txt extension, I had to add this to be able to upload it)
