### ISSUE TITLE
How to export with some columns with System.Collections.ArrayList to Excel?

### ISSUE THREAD

**Issue by doggy8088** [dfinke/ImportExcel#1359]
There are some columns in my PSObject container a list. How to convert `System.Collections.ArrayList` column to a Text? Is there any built-in command argument for this?

![image](https://user-images.githubusercontent.com/88981/209793310-a96d76d2-cb8c-452c-94b3-cc7bbbf3e6de.png)

**Comment by dfinke** [comment]
Export-Excel does not unroll lists in properties. You need to "shape" your data and then export.

**Comment by thkn-hofa** [comment]
Before Export-Excel, do smth like this:

```powershell
Foreach ($o in $objects) {
    $o.HeaderContainswords = $o.HeaderContainswords -join ", "
}
```

**Comment by dfinke** [comment]
Yes, that's one way. All depends on what "shape" you are looking for to be represented in Excel.

**Comment by doggy8088** [comment]
@dfinke Are you considering add "unroll lists in properties" feature to your cmdlet? That will be very handy! 👍

**Comment by dfinke** [comment]
Not at this time. I don't need them. Plus feels like there may be lots of options for how someone would want then unrolled.

Happy to hear ideas and see more use cases on the data before and after in Excel to get a sense of the effort.

**Comment by deadlydog** [comment]
I too would like this functionality. I often dump the results of API requests that return many records into excel to make the data easier to visualize and ingest, so the JSON is converted to a [PSCustomObject[]]. It works very nicely for the top level attributes (they get converted to columns in the spreadsheet), but nested [PSCustomObject] objects just show up as blank. If I instead use `Format-List` to dump the info to the console or a text file, I get the nested info.

Here's an example of what gets exported to Excel. Notice the `createdBy` and `modifiedBy` objects just show up as blank in Excel:

![image](https://user-images.githubusercontent.com/1187140/216097736-8e6da0f6-fbe4-42fa-9353-bcf3718539f2.png)

Format-List unrolls the nested object properties though.
```
consumerId             : workplaceMessagingApps
consumerActionId       : httpRequest
actionDescription      : To host azdevchatops.dev.azure.com
createdBy              : @{displayName=Some User; id=azazazzzazazaazazaza; uniqueName=SomeUser@somewhere.com; descriptor=aad.azazazazazazazazazazazaz}
createdDate            : 7/23/2020 4:38:45 PM
modifiedBy             : @{displayName=Someone Else; id=azazazazazazaz; uniqueName=SomeoneElse@somewhere.com; descriptor=aad.azazazazazazazazazaz}
modifiedDate           : 10/1/2021 9:14:33 PM
```

**Comment by dfinke** [comment]
@deadlydog You need to shape your data before exporting. `Export-Csv` does not unroll your data either, you need to shape your data before exporting.

**Comment by deadlydog** [comment]
Thanks @dfinke , I was just hoping for a `-DoAllTheUnrollingForMe` switch because I'm lazy 😅. I totally understand though. Thanks for the response 🙂

**Comment by dfinke** [comment]
Haha, yeah, been looking for the PowerShell one-liner `Today | Do-MayWork -GoToBeach`
