### ISSUE TITLE
can't get powershell script to run correctly from application

### ISSUE THREAD

**Issue by sigmondfroid01** [dfinke/ImportExcel#136]
I have an application that allows me to add a run command and execute for automation.  I can run my ps script manually on the server through powershell ise or from a command prompt, with both my ID and the service account ID on my server.  In my application I can manually execute the command that runs the command line ps script and it works fine.  When I automate to have the application run the same run command it does nothing.  It shows it was successfule but never actually creates my file.  When looking in event viewer I don't see any errors and the only difference I see is when I manually run it from the application it does Add-Type -Path "$($PSScriptRoot)\EPPlus.dll" in the event rule whereas when the application automatically does it I never see that come through event rules.  If is like for some reason it is not executing that piece with the ImportExcel section?  Any ideas? The configuration for the run command is C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "D:\Reports\Scripts\AuditPassReport.ps1"

**Comment by dfinke** [comment]
No idea at the moment
