### ISSUE TITLE
Export-Excel not correctly evaluating formulas containing table references

### ISSUE THREAD

**Issue by zuntua** [dfinke/ImportExcel#1360]
When exporting data that contains formulas with table references with Export-Excel, the cells containing formulas with table references don't evaluate correctly.

For example,
```
$xlFile = "C:\Test\Excel Test.xlsx"
$xlSheet = "TestSheet"
$Data = [PSCustomObject]@{
    "Col1" = 10
    "Col2" = 100
    "Col3" = '=[@Col2]*2'
    "Col4" = '=B11*2'
}
$Data | Export-Excel $xlFile -WorksheetName $xlSheet -Append
```
Output with the above code
```
Col 1   Col 2   Col 3   Col 4
-----   -----   -----   -----
10      100     #REF!   200

```
The example code saves the data to the end of the existing Table but the value in Column C shows **#REF!** (the formula for the cell is **=#REF!\*2**)
The value in Column C should be **200**.

**Comment by dfinke** [comment]
Please post an xlsx with the data and tables

**Comment by stahler** [comment]
replace Col3 = '=[@Col2]*2'
with Col3 = '=[Col2]*2'

**Comment by dfinke** [comment]
Thanks @stahler I was looking for in the examples for how to get this right, couldn't find it.

@zuntua I would need to look at `Export-Excel` for these specifics, there are places where `=[Name]` may be detected and transformed or it may be in the DLL.

**Comment by oliwex** [comment]
TIPS from me: Try to pass object only with data(no formulas,no formatting,only data) into export-excel and then format file. It works better

**Comment by stahler** [comment]
As @oliwex stated, a better way to do this is to generate the file, then adjust.
```PowerShell
$data = ConvertFrom-Csv @"
COL1,COL2
20,200
30,300
40,400
50,500
"@

$path = 'C:\TEMP\example1.xlsx'
Remove-Item -Path $path -ErrorAction SilentlyContinue

$excel = $data | Export-Excel -Path $path -PassThru
$sheet = $excel.Workbook.Worksheets["Sheet1"]

Set-ExcelColumn -Worksheet $sheet -Heading "COL3" -Value {"=B$row*2"}
Close-ExcelPackage -ExcelPackage $excel -Show
````
![image](https://user-images.githubusercontent.com/1991193/210155388-3dc4008c-23a2-4cff-a5da-f6a5169c9ca0.png)

**Comment by oliwex** [comment]
@dfinke I think the code from @stahler is good for docs for that module as: Get-Help Set-ExcelColumn.
