### ISSUE TITLE
Old command now failing

### ISSUE THREAD

**Issue by PSRookietjh2021** [dfinke/ImportExcel#1364]
Hello,

I use the following command to remove processed data from a worksheet:

$data | Export-Excel -Path "[Path]\New User.xlsm" -WorkSheetname "NewVFUser" -ClearSheet

It recently started presenting an error:
Exception: C:\Users\hillt\Documents\PowerShell\Modules\ImportExcel\7.8.0\Public\Export-Excel.ps1:135:17
Line |
 135 |          catch { throw "Could not get worksheet $WorksheetName" }
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not get worksheet NewVFUser

The worksheet name is the same used to gather and process the data, which all still works.

Please let me know if you need more information.

**Comment by dfinke** [comment]
Will take a look. What version did you upgrade from?

**Comment by PSRookietjh2021** [comment]
I'm sorry, I don't track that.  However, I have tried to keep current, so it should have been the immediately previous version.

Best Regards,
Thomas Hill

**Comment by dfinke** [comment]
Seems to work with the current version 7.8.4 on the gallery.

**Comment by PSRookietjh2021** [comment]
OK.  I will update.

I found the version info.  I was on 7.8.0.

Best Regards,
Thomas Hill
