### ISSUE TITLE
`-TableTotalSettings` should add table name

### ISSUE THREAD

**Issue by teknowledgist** [dfinke/ImportExcel#1366]
I create several worksheets each with a table that has a total using the `-TableTotalSettings` parameter.  The references in the totals row aren't consistent and "skip" sometimes/often the table name.

Using [the given example](https://github.com/dfinke/ImportExcel/blob/master/Examples/Tables/TotalsRow.ps1):

* The "Name" column total of the "system32files" table is `=SUBTOTAL(103,system32files[Name])` (i.e. the reference includes the table name)
* The "Length" column total is `=SUMIF([extension],".exe",[length])` (i.e. references without the table name)
* The "Extension" column total is `=COUNTIF([extension],".exe")` (i.e. also without the table name)

It is my belief that the table name is in the "Name" column entry because the `$TotalSettings` doesn't use a formula (i.e. `=...`) but has some "code words" for types of totals.  (Side note: Is that syntax defined anywhere?) 

If the workbook is opened in Excel and then saved regardless of making any explicit changes, all the references pick up the table name and the cells are "proper".  For example:

* `=SUMIF(system32files[extension],".exe",[length])`
* `=COUNTIF(system32files[extension],".exe")`

If the workbook is instead opened in another product that is compatible with .xlsx, the references without the table name generate an error.  We could blame the other product, but I would argue that if Excel itself wants the table name, then export-excel should be making sure it is "correct".  Of course, the table name could be explicitly added to the formula, however given that I have multiple tables for which I want totals of the same columns, that means changing the settings for each table creation.   I don't think we should need to define the table name in the formulas since the settings are being used explicitly in the creation of the table.  

Is it possible for the `-TableTotalSettings` to fill-in the table name in references that don't have it so the resultant workbook is more "proper" and compatible? 

Thanks.

**Comment by dfinke** [comment]
@thkn-hofa?

**Comment by thkn-hofa** [comment]
Yeah I'll check it out.

The 'code words' are documented in the help (Get-Help Export-Excel -Full). You can also find the help file [here](https://github.com/dfinke/ImportExcel/blob/master/mdHelp/en/export-excel.md#-tabletotalsettings).

**Comment by thkn-hofa** [comment]
@dfinke seems like you closed this Issue. Was that intentional? 

@teknowledgist I couldn't see it in the GUI but when I took a closer look to the defining XML file, I saw what you were talking about. I updated the script with some regex magic. Tests are running fine but I'd like you to test it out with the 'other product that is compatible with xlsx'. 

You can [pull/download and load my fork](https://github.com/thkn-hofa/ImportExcel/tree/Issue1366_TotalSettings-Table-Name) or drop in the replacement file in \<ModuleRoot\>\\Public\\:
[add-exceltable.md](https://github.com/dfinke/ImportExcel/files/10366874/add-exceltable.md)

**Comment by teknowledgist** [comment]
The modified `Add-ExcelTable.ps1` does work in my simple case, thanks!  

I should correct one thing I said...  With the old code, the displayed formula with references appears the same in Excel before and after saving.  E.G. `=SUMIF([extension],".exe",[length])`  However, the displayed formula in LibreOffice Calc (the "other product") is `=SUMIF([extension],".exe",[length])` before opening/saving in Excel and `=SUMIF(system32files[extension],".exe",system32files[length])` after.  

Clearly, in the later case (i.e. after Excel has saved it), Calc is recognizing the reference is for the current table and visually inserting the table name.  Before Excel touches it, Calc does not recognize that the reference is for the same table.  That means there must be a non-visual difference between the just-exported(-pre-Excel) file and the just-saved(-post-Excel) file.  

The updated `Add-ExcelTable.ps1` does work in my simple case, thanks!  

Funnily enough, despite your changed code explicitly adding the table name in totals fomulas, Excel still doesn't display the table name in the cell formula.  Calc of course still does and seems happy with it.

All that said, I can easily imagine situations in which the fix will be a problem, but I also am having difficulty imagining how it could be further fixed.  For example, if a total settings equation references a value from another table, the update will break the formula.  Assuming that the range of possibilities for a table name is pretty wide, that could be difficult to account for, and that is made additionally complex since negative lookbehinds use text and not sub-regexes.  

Let me know if I can help test any additional changes.

Thanks.

**Comment by thkn-hofa** [comment]
That's a fair point you make about the other tables. I can probably list all the tables in a workbook/worksheet and check if any of these prepend the column name. If none do, prepend the column name with the name of the current table.

**Comment by teknowledgist** [comment]
That would be better, but there would still be the possibility that the formula references a table that hasn't been created yet.  That may be a backward way to create a workbook, but it's not disallowed.

**Comment by thkn-hofa** [comment]
OK, attempt three: now I'm just testing for a valid tablename in front of the column name ([Reference](https://support.microsoft.com/en-us/office/rename-an-excel-table-fbf49a4f-82a3-43eb-8ba2-44d21233b114#:~:text=Maximum%20255%20characters%20%E2%80%94%20A%20table,Duplicate%20names%20aren't%20allowed.)). If there's nothing there, add the current table in front of it.

Then test all of the tablenames to see if they exist in the current workbook and if not: throw a warning but continue

**Comment by dfinke** [comment]
@thkn-hofa, thanks for the PR.  I need to make time to a look at this in detail. Not sure I'll merge. 

Is this a general issue using the feature or an edge case?

**Comment by thkn-hofa** [comment]
@dfinke this is a general issue for LibreOffice/OpenOffice users: totals row just doesn't work. MS Excel users aren't affected. The extra work I put in (after the first two commits) is for edge cases where someone would reference another table in a totals row formula.

Now it's up to you to decide whether LibreOffice users are an edge case 😁

**Comment by teknowledgist** [comment]
I think the fact that Excel changes (fixes might be a better, although judgemental, word) the workbook without the user making any explicit changes indicates that the current feature is *incomplete*.  

The PR aims to make the output of `export-excel` more explicit with its table references.  It's not a new, bloated feature.
