### ISSUE TITLE
How to split a each sheet into a separate workbook.

### ISSUE THREAD

**Issue by jasonmcboyd** [dfinke/ImportExcel#1368]
Hi, thanks for the work you are doing here. This looks like a great project.

I am trying to do something that looks like it should be pretty simple with your PowerShell module but I am struggling. I have read through your examples and the FAQ and the solution is escaping me.

I have a workbook with dozens of sheets in it, I would like to extract each sheet into a separate workbook with all formatting and everything else unchanged. The new file would take the name of the sheet. I have tried various combinations of `Import-Excel` and `Export-ExcelSheet` with different parameters but I am not getting the results I expect; I end up losing formatting and what were empty rows in the original document that delineated the start of a new region end up getting removed.

Thanks for your help.

**Comment by dfinke** [comment]
Sounds like you're on the right track. Extracting the data is, straightforward as you've seen. Formatting etc, you would need to handle. May need to use `Set-ExcelRange`. I have not tried that and there may be gaps.
