### ISSUE TITLE
Cannot install PSExcel on Powershell version 4

### ISSUE THREAD

**Issue by nwinkel651** [dfinke/ImportExcel#137]
I have tried to install the PSExcel on PowerShell version 4. I'm trying to install this on Windows Server 2012 in IIS1. I ran this command to install the module to my personal folder which was successful.
iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfinke/ImportExcel/master/Install.ps1') 

But when I try the next step in the instructions of importing the module I get two warnings:
WARNING: PowerShell 5 is required for plot.ps1
WARNING: PowerShell Excel is ready, except for that functionality

Can anyone assist?

**Comment by megamorf** [comment]
What happens when you run `Get-Module ImportExcel` after the import?
And don't confuse warnings with errors.

**Comment by nwinkel651** [comment]
I get a new line, no errors or warnings

**Comment by dfinke** [comment]
Those warnings are expected if you use this on PowerShell earlier than 5.0. The core functionality should work.

**Comment by nwinkel651** [comment]
I have noticed that as I've tried different syntax and I can see it is
working. I apologize for my novice abilities with PowerShell. Thank you for
taking the time to respond to my issue.

**Comment by dfinke** [comment]
No problem. It's good to ask and post these questions. It helps everyone.
