### ISSUE TITLE
Export-Excel is writing <t xml:space="preserve"> on some fields, causing Excel to complain

### ISSUE THREAD

**Issue by mark-simonton** [dfinke/ImportExcel#1371]
Is there any way to suppress this behavior?  also it is writing <t></t> and Excel is complaining about that and replacing it with <t/>

I assume I am using the latest version, since I did the import module 3 weeks ago.

here is the error text from Excel
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error311720_01.xml</logFileName><summary>Errors were detected in file 'D:\etc\SecurityBaseline\Policy to Excel\Windows Package\Spreadsheet Builder\V2\src\Final.xlsx'</summary><repairedRecords><repairedRecord>Repaired Records: String properties from /xl/sharedStrings.xml part (Strings)</repairedRecord></repairedRecords></recoveryLog>

here are lines:
from un-fixed XLSX file
<si><t **xml:space="preserve"**>Disables the lock screen camera toggle switch in PC Settings and prevents a camera from being invoked on the lock screen. \n  \n  \n By default, users can enable invocation of an available camera on the lock screen. \n  \n  \n If you enable this setting, users will no longer be able to enable or disable lock screen camera access in PC Settings, and the camera cannot be invoked on the lock screen.</t></si>

from "fixed" XLSX file
<si><t>Disables the lock screen camera toggle switch in PC Settings and prevents a camera from being invoked on the lock screen. \n  \n  \n By default, users can enable invocation of an available camera on the lock screen. \n  \n  \n If you enable this setting, users will no longer be able to enable or disable lock screen camera access in PC Settings, and the camera cannot be invoked on the lock screen.</t></si>

**Comment by dfinke** [comment]
Please post a simple repro of the issue

**Comment by mark-simonton** [comment]
Ok, I found my issue; my problem is that I inherited a series of scripts from at least 1 predecessor.  they reads some files, turn them into a CSV file which is consumed by the script I am attempting to finish.  My first issue was that the CSV file my script consumes had LF or  CR LF characters embedded in quoted text that caused many problems when using ConvertFrom-CSV I "fixed" that issue by making sure each line contained matching quote (") marks, by joining lines, inserting " \n " to potentially keep formatting for later.  that worked but produced the new error; the cell with greater than 32768 characters; found this while  attempting to produce a minimal example.  I have it now, a CSV with 2 rows, row 1 labels, row 2 data, where column 2F exceeds Excel's text limit.

thank you for the tool; please be patient with a new-bee to Excel (66 years old and I am still ignorant)

**Comment by dfinke** [comment]
@mark-simonton No worries, glad you found the issue.
