### ISSUE TITLE
Install offline without PSGallery

### ISSUE THREAD

**Issue by braggpeaks** [dfinke/ImportExcel#1374]
Installation with PSGallery works fine, but when trying to run InstallModule.ps1, the module is copied, but not imported. When trying to import I get this error:

Import-Module ImportExcel
Import-Module : Die Datei oder Assembly "file:///C:\Program Files\WindowsPowerShell\Modules\ImportExcel\EPPlus.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)

If that helps, DependencyWalker says about EPPlus.dll "Errors were detected when processing ..." 

Error: At least one required implicit or forwarded dependency was not found.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

Separate question: Is there a way to run Import-Excel script without installation of the whole module? I just need the reading part.

Thank you,
Daniel

**Comment by dfinke** [comment]
Don't know. Have not tested those scenarios.

**Comment by braggpeaks** [comment]
I did not manage to install offline, but I managed to use Import-Excel.ps1 (i.e. the reading part) without installation:

Place EPPlus.dll in same folder as Import-Excel.ps1, add this to script before first usage of OfficeOpenXml.ExcelPackage:
```
$dll = Join-Path $PSScriptRoot "EPPlus.dll";
[Reflection.Assembly]::LoadFile($dll) | Out-Null;
```

Btw, I noticed that when parameter WorksheetName is not provided, the script checks for the second element with index [1] instead of the first worksheet, which has index [0].

`elseif (-not  $WorksheetName) { $Worksheet = $ExcelPackage.Workbook.Worksheets[1] }`

**Comment by dfinke** [comment]
That is correct, the EPPlus DLL does not use a zero-based array. Does that change when you co-locate it?

**Comment by braggpeaks** [comment]
Oh holy grail, I just recognized that some Excel documents do index their first worksheet at 0, others at 1 and the square bracket [0] does not index the array but uses the Index property of the object. So a fix could look like this:

`elseif (-not  $WorksheetName) { $Worksheet = $ExcelPackage.Workbook.Worksheets[$ExcelPackage.Workbook.Worksheets.Index[0]] }
`

**Comment by dfinke** [comment]
Not sure it is broken. Need a repro of this, against the module as installed from the gallery

**Comment by braggpeaks** [comment]
Created a new .xlsx from scratch with Office 365, single worksheet and got this

```
$ExcelPackage.Workbook.Worksheets

Index                 : 0
AutoFilterAddress     :
AutoFilter            :
SortState             :
View                  : OfficeOpenXml.ExcelWorksheetView
...
```

while my other Excel documents start with Index 1. The above fix would work for both scenarios.

**Comment by dfinke** [comment]
Does the desktop Excel app do the same thing?

**Comment by braggpeaks** [comment]
For the above test I was using Excel from Office 365 on a noteook (i.e. desktop version of it), not online based.

**Comment by dfinke** [comment]
I tried it on my desktop and it pulls the correct first sheet. I'm confused.

**Comment by braggpeaks** [comment]
I am confused as well!

I initially had Worksheets.Index starting with 0 as well. Presumably for all, because your script was working.
Now I tested several Excel documents authored in several years and all (sic!) of them are starting with Index 1. I use this for testing:

```
$Path = "document.xlsx";
$dll = "C:\temp\EPPlus.dll";
[Reflection.Assembly]::UnsafeLoadFrom($dll) | Out-Null;
$stream = New-Object -TypeName System.IO.FileStream -ArgumentList $Path, 'Open', 'Read', 'ReadWrite'
$ExcelPackage = New-Object -TypeName OfficeOpenXml.ExcelPackage
$ExcelPackage.Load($stream)
$ExcelPackage.Workbook.Worksheets
```

Even if not understood, I recommend to apply the above patch, as it will work with either starting Index:

`elseif (-not  $WorksheetName) { $Worksheet = $ExcelPackage.Workbook.Worksheets[$ExcelPackage.Workbook.Worksheets.Index[0]] } `

**Comment by dfinke** [comment]
Not going to apply a patch where I can't really test it validity
