### ISSUE TITLE
Suggestion - option to trim and remove special characters and spaces from column headings

### ISSUE THREAD

**Issue by jdenicola-pa** [dfinke/ImportExcel#1376]
For the scripts I've written, it would be convenient if there were options in Import-Excel to try to "normalize" column headings which become properties of the row.

For example, I've had to deal with spreadsheets where someone unexpectedly added a space at the end of a column heading... not obvious by sight, until you try to use it. Or the multi-line column heading where they press Alt-Enter in a cell.  I end up with things like:

$row."Column Name "   # Extra space at the end.. until someone decides remove it!
$row."Column`n Name"   # Embedded newline in cell heading (and space!)

Additionally, if there were an option to remove embedded spaces altogether, then this:

$row."Some Column Name"

could become

$row.SomeColumnName

No quotes necessary.

Such as:

-HeaderTrim  - trims spaces from the beginning and end of cell header, leaves embedded spaces
-HeaderDeline - removes newline characters from cell header
-HeaderDespace  - removes all whitespace from cell header (spaces, newlines)

**Comment by dfinke** [comment]
Data scrubbing. I lean toward that be an exercise for the user of the module. Yeah, that is more work.

**Comment by dfinke** [comment]
Also asked for here: https://github.com/dfinke/ImportExcel/issues/1258

**Comment by jdenicola-pa** [comment]
Thanks - I did do a search before I posted, but did not come up with those two - sorry, didn't mean to duplicate.

I'm not looking to scrub the actual data, only the names of the properties that get created.

I agree about data scrubbing being my responsibility, but in this special case, since Import-Excel creates the row object array with the header cell values as the properties, how could I scrub it (before or after) the properties are created?

For example, if I use Import-Excel and it creates the row object array with the property $row."Some`nStrange`nColumn ", how could I scrub that after it is created (or before)?

Based on my research, the only way to do this afterward results in making a copy of the entire object array. Powershell doesn't  provide a way to rename a property.

**Comment by dfinke** [comment]
Good that you asked the question. I added them here for tracking and note how many times it is requested.

If you want, you can review the `Import-Excel` function map out the change, implement the tests, ensure the code is still backward compatible.

Maybe something like this:
You could read the first row of data in the sheet (headers). `$headers=Import-Excel test.xlsx -startrow 1 -endrow 1`
Scrub them like you suggest
Then `Import-Excel test.xlsx -startrow 2 -HeaderName $headers`
