### ISSUE TITLE
Formulas not applied after excel file is manipulated with Open-ExcelPackage

### ISSUE THREAD

**Issue by mezamoe** [dfinke/ImportExcel#1379]
Hello, I have this strange issue where after I have manipulated (successfully) an excel file, when I open it with Excel all is in order, but if I perform an Import-Excel the formulas in column C are not applied. Here a sample excel file:

[mail1.xlsx](https://github.com/dfinke/ImportExcel/files/10420033/mail1.xlsx)

and here the code I use. Basically, the script ensures that column D is emptied before fresh data is injected in it. Then the formulas in column C should apply and cells should match/be filled with a code in column A based on a matching (or not) between cells in D and B. As anticipated, if I open the file with excel all good. But if I import-excel the file in PowerShell the formulas are not applied. It seems that the file state is not saved in the file context in Powershell.

$servers = "item20","item22","item25"
$excelSapSidWork = Open-ExcelPackage -Path 'path\to\mail1.xlsx'
$worksheet = $excelSapSidWork.Workbook.Worksheets['sapsid']
foreach ($cell in ($worksheet.SelectedRange["D2:D"])){
    $cell.Clear()
}
foreach ($cell in ($worksheet.SelectedRange["C2:C"])){ #even if I remove this foreach that cleans up the column C, the result is the same
    $formula = $cell.Formula
    $cell.Value = ''
    $cell.Formula = $formula
}
$count = 1
foreach($item in $servers){
    $count +=1
    $worksheet.Cells["D$count"].Value = $item
} 

Close-ExcelPackage $excelSapSidWork 
# import data 
[array]$excelImport = Import-Excel -Path  'path\to\mail1.xlsx' -ImportColumns @(3,4) #even if I remove the ImportColumns, result is the same

**Comment by dfinke** [comment]
I'm not sure. Before you close it try `[OfficeOpenXml.CalculationExtension]::Calculate($ExcelPackage.Workbook)` and see if the `Import-Excel` works.

**Comment by mezamoe** [comment]
thanks! It throws:

```
Multiple ambiguous overloads found for "Calculate" and the argument count: "1".
At line:17 char:1
+ [OfficeOpenXml.CalculationExtension]::Calculate($ExcelPackage.Workboo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

**Comment by mezamoe** [comment]
many thanks Doug! That works! The file is ok when opened in Excel and also from powershell. One thing though... cells that match the formula are ok, but the ones that not, in powershell show #VALUE! instead of being empty. When open in Excel all good. I can work it through a foreach and clean it I guess, just wanted to check if there is any switch that you remember on the tip of your mind.

**Comment by mezamoe** [comment]
else this will do...and thanks again!!

```
foreach ($cell in ($worksheet.SelectedRange["C2:C"])){
    $formula = $cell.Formula
    if($cell.Value -like "#V*"){
        $cell.Value = ''
        $cell.Formula = $formula
    }
}
```

**Comment by dfinke** [comment]
Don't know of a way to handle it. I think the `foreach` is the way to go.
