### ISSUE TITLE
Multiple conditional format comparison

### ISSUE THREAD

**Issue by sigmondfroid01** [dfinke/ImportExcel#138]
I don't see an example that would allow me to:
 $Files = Import-Csv -Path $csv | Export-Excel $xls -AutoSize -show -ConditionalText $(

   New-ConditionalText -Range "C:C" -ConditionalType NotEqual 'PROFILE ONLY' 
New-ConditionalText -Range "B:B" -ConditionalType BeginsWith '0' black cyan

Look at column C and if it did not contain PROFILE ONLY highlight column B if it  begins with 0 only then highlight it in cyan, if it is not true do nothing.  Not sure how to do IF/And elseif statement with the conditional text with export excel

**Comment by dfinke** [comment]
Interesting. Investigate if you can do it with the Excel directly, then we can see if it can be surfaced via PowerShell
