### ISSUE TITLE
Export-Excel doesn't like null values

### ISSUE THREAD

**Issue by pumaro1208** [dfinke/ImportExcel#1383]
Export-Excel doesn't like null values. I had to add "" to fields that were empty to avoid random data in the export to xlsx files.

$Result = @()
$AllUsers = Get-AzureADUser -All $true | Where-Object {$_.AccountEnabled -eq $true} | Select-Object -Property Displayname, UserPrincipalName, CompanyName, JobTitle, Department, TelephoneNumber, city, AccountEnabled
$TotalUsers = $AllUsers.Count
$i = 1 

foreach ($User in $AllUsers) {
    Write-Progress -Activity "Fetching manager of $($_.Displayname)" -Status "$i out of $TotalUsers users completed"
    $managerObj = Get-AzureADUserManager -ObjectId $User.UserPrincipalName
    $Result += New-Object PSObject -property $([ordered]@{ 
            UserName          = $User.DisplayName
            UserPrincipalName = $User.UserPrincipalName
            CompanyName       = if ($User.CompanyName -ne $null) { "$($User.CompanyName)" } else { ""}
            JobTitle          = if ($User.JobTitle -ne $null) { "$($User.JobTitle)" } else { ""}
            Department        = if ($User.Department -ne $null) { "$($User.Department)" } else { ""}
            TelephoneNumber   = if ($User.TelephoneNumber -ne $null) { "$($User.TelephoneNumber)" } else { ""}
            City              = if ($User.City -ne $null) { "$($User.City)" } else { ""}
            AccountStatus     = if ($User.AccountEnabled -eq $true) { "Enabled" } else { "Disabled" }
            ManagerName       = if ($managerObj -ne $null) { $managerObj.DisplayName } else { "" }
            ManagerMail       = if ($managerObj -ne $null) { $managerObj.Mail } else { "" }
        })
    #remove-variable user
    $i++
}
#edit path below to capture file...
$Result | Export-Excel "C:\Temp\M365UsersManagerInfo.xlsx"
$Result | Export-Csv "C:\Temp\m365UsersManagerInfo.csv"

**Comment by dfinke** [comment]
Could you possible post a small repro of the issue including data and script that shows the issue?
