### ISSUE TITLE
Refresh Queries and Connections

### ISSUE THREAD

**Issue by CraigChamberlain** [dfinke/ImportExcel#1387]
This is a great app and I could probably export a new excel sheet every time I need to run a refresh, but is there a Cmndlet or Method on an object to achieve this.  For example, to import an existing formatted Excel sheet with data connections and refresh this data from PowerShell so I can get various sheets refreshing on a Scheduled Task?

**Comment by CraigChamberlain** [comment]
Here is a VB approach:
https://stackoverflow.com/questions/47159268/powershell-script-open-excel-update-external-data-save-as

**Comment by dfinke** [comment]
Thanks!

The -ComObject approach instantiates Excel which renders the entire XLSX. 

The ImportExcel module only works on the data. You can format it etc. I don't have helper functions that copy styles, formulas etc.  

ImportExcel does work with connections. 

Unfortunately can't be done.

**Comment by CraigChamberlain** [comment]
Thanks for looking. I had a look at the APIs and concluded the same.  Will
use PowerBI instead, that supports user triggerd and scheduled updates even
in the browser.
