### ISSUE TITLE
Is there a file size limit for import?

### ISSUE THREAD

**Issue by teknowledgist** [dfinke/ImportExcel#1388]
I have a fairly large spreadsheet to process.  256k rows, about 60 columns, 84MB in size.  It takes about 30 seconds to open in Excel which uses about 400MB RAM before any work/changes are done.  

When I try to use import-excel, I let it go for close to an hour with the PowerShell instance using about 3.5GB RAM and it never finished.

Any ideas how to manage this?

**Comment by dfinke** [comment]
Yes, discussed here. You'll need to use v7.4.2. No ETA yet for improving the performance back to what it was.

https://github.com/dfinke/ImportExcel/discussions/1279
