### ISSUE TITLE
Getting error with Range parameter while using Export-Excel cmdlet.

### ISSUE THREAD

**Issue by ashisharya65** [dfinke/ImportExcel#1389]
Hi,

I am trying to export Azure AD group member details to a single excel workbook where every group member details should be mentioned in a separate worksheet. For example, group1 worksheet should contains members of one AAD group and group2 worksheet contains members of another AAD group and so on so forth.

For this I am using two PowerShell modules: Microsoft.Graph and ImportExcel.

The issue is that once 34 worksheets are added to the excel workbook, I get this error :
Cannot bind argument to parameter 'Range' because it is null.

Then I checked the $error variable and got this error details 

InvocationInfo    : 
  MyCommand    : Add-ExcelTable
  ScriptLineNumber : 428
  OffsetInLine   : 39
  HistoryId    : 122
  ScriptName    : C:\Users\ashish\Documents\PowerShell\Modules\ImportExcel\7.8.4\Public\Export-Excel.ps1
  Line       : Add-ExcelTable -Range $ws.Cells[$dataRange] -TableName $TableName -TableStyle $TableStyle -TableTotalSettings $TableTotalSettings
            
  PositionMessage : At C:\Users\ashish\Documents\PowerShell\Modules\ImportExcel\7.8.4\Public\Export-Excel.ps1:428 char:39
            +         Add-ExcelTable -Range $ws.Cells[$dataRange] -TableNam …
            +                    ~~~~~~~~~~~~~~~~~~~~~

**Comment by dfinke** [comment]
Need to see a repro, data, scripts etc
