### ISSUE TITLE
Excel remains open after import

### ISSUE THREAD

**Issue by bernardw1** [dfinke/ImportExcel#139]
When importing excel documents into PowerShell it seems like the last open excel document remains open until either the PowerShell window is closed or a new Excel document is opened (but this is not always consistent). 

Is there a way to either close the current excel document (force it to close) or should the excel document be closed after the import happens?

**Comment by dfinke** [comment]
No, there's no way to force a close. It should close the doc after each invocation. There is no testing for errors. Maybe it is getting an error when it imports, errors out and never closes?

**Comment by bernardw1** [comment]
Interesting. I do not see any errors from the import of the Excel files. The command I use to import the files is `Import-excel -path $FileName -WorkSheetname 'Office Timesheet' | Select-Object -First 50` (I have chosen to do the select-object because the creator of the spreadsheet has put a LOT of extra info at the end of the sheet - 200+ lines - that is not really needed). 

Hum. Now that I tried it with out the  "| Select-Object -First 50" it works correctly. I guess I will have to keep that part commented out so that I can move the spreadsheets once they have been processed.

**Comment by dfinke** [comment]
Try wrapping the left hand side of the pipe in parens and see if that helps.

`(Import-excel -path $FileName -WorkSheetname 'Office Timesheet') | Select-Object -First 50`

**Comment by bernardw1** [comment]
Sorry for not coming back and reporting on the results. Wrapping the left hand of the pipe worked perfectly! Thank you very much for the suggestion.
