### ISSUE TITLE
More than 1 Excel Chart Displays Blank

### ISSUE THREAD

**Issue by nathanlbell** [dfinke/ImportExcel#1395]
I am running a reporting PShell that pulls some data from a REST API and I am trying to graph 90 days of trending data into excel. Ideally I am writing all of my datasets per server object into a different worksheet and I would like to create a graph of each data set by objects into a "graphs" sheet.  This is where I run into issues.  Additionally chart datasets are on table named ranges.

Every time I run export excel in a loop of the objects I get charts with no displayed ranges, the chart is blank on everything is blank, additionally the datasets are blank for each chart but the chart objects exist.  I can email code samples if needed, but essentially each object (server data in this case about a storage container) is show two sets of data over a 90 day time series (total number of files and total size at time of sample)  From there I am attempting to chart both on the same graph per server) and repeat across ~20 or so servers.  I was set on getting all charts into a single sheet so that I can export via HTML and attach to an email body.

The only way I can get everything to function is by having each dataset and graph on the same sheet on a different sheet. But that isn’t what I am looking to do.

Looking for some help and perhaps I am doing something way wrong.

**Comment by nathanlbell** [comment]
To add to more weirdness, the charts actually display properly in the chart design preview ribbon.  Additionally opening the workbook in PS ad browsing into the objects the series data is correct in every chart but they are blank....not sure what is going on.

**Comment by dfinke** [comment]
need to see data, scripts and xlsx files

**Comment by nathanlbell** [comment]
I think I found what is going on... chart definition has worksheet of the graphs worksheet from the worksheet object, however the data series is pointing to the graphs worksheet even though the data table columns in excel got defined as the 'SERVERNAME'!SERVERNAME[ActiveGB] and 'SERVERNAME'!SERVERNAME[ActiveFiles] for the columns.  The object shows the below for the series when I debug the chart objects:

PS D:\psrepos> $xl.Graphs.Drawings[1].Series


DataLabel       : OfficeOpenXml.Drawing.Chart.ExcelChartSerieDataLabel
Marker          : None
Smooth          : False
LineColor       : Color [Black]
MarkerSize      : 5
LineWidth       : 2.25
MarkerLineColor : Color [Black]
Header          : ActiveFiles
HeaderAddress   :
Series          : 'graphs'!SERVERNAME[ActiveFiles]
XSeries         : 'graphs'!SERVERNAME[Date]
TrendLines      : {}
Fill            : OfficeOpenXml.Drawing.ExcelDrawingFill
Border          : OfficeOpenXml.Drawing.ExcelDrawingBorder

DataLabel       : OfficeOpenXml.Drawing.Chart.ExcelChartSerieDataLabel
Marker          : None
Smooth          : False
LineColor       : Color [Black]
MarkerSize      : 5
LineWidth       : 2.25
MarkerLineColor : Color [Black]
Header          : ActiveGB
HeaderAddress   :
Series          : 'graphs'!SERVERNAME[ActiveGB]
XSeries         : 'graphs'!SERVERNAME[Date]
TrendLines      : {}
Fill            : OfficeOpenXml.Drawing.ExcelDrawingFill
Border          : OfficeOpenXml.Drawing.ExcelDrawingBorder

Still working to reduce code using a smaller repro issue.

**Comment by nathanlbell** [comment]
S D:\psrepos> $PSVERSIONTABLE 

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS D:\psrepos> Get-InstalledModule ImportExcel

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
7.8.0      ImportExcel                         PSGallery            PowerShell module to import/export Excel spreadsheets, without Excel....

**Comment by nathanlbell** [comment]
[Chart.xlsx](https://github.com/dfinke/ImportExcel/files/10716351/Chart.xlsx)
[graph_repro.ps1.txt](https://github.com/dfinke/ImportExcel/files/10716353/graph_repro.ps1.txt)


Attached repro of issue that I am experiencing.  I am assuming I am using the function improperly by using data tables in the excel sheet (I originally had generated these when importing the data from the rest function.)  At this point just looking to make multiple graphs all on the same sheet ultimately so I could eventually save as and email off.

**Comment by nathanlbell** [comment]
[Chart_ManuallyFixedCharts.xlsx](https://github.com/dfinke/ImportExcel/files/10716403/Chart_ManuallyFixedCharts.xlsx)

I went into the excel workbook and manually fixed the 2 charts that the repro creates.  When I did it through excel it manually changes the structured references to fully qualified references. 

Here is the result of browsing the chart series info:

PS D:\psrepos> $xls.Workbook.Worksheets['graphs'].Drawings[0].Series|Select-Object Series,XSeries
$xls.Workbook.Worksheets['graphs'].Drawings[1].Series|Select-Object Series,XSeries

Series                        XSeries
------                        -------
server1!$B$2:$B$122           server1!$D$2:$D$122
'graphs'!server1[ActiveFiles] server1!$D$2:$D$122
'graphs'!server1[ActiveGB]    server1!$D$2:$D$122
server1!$C$2:$C$122           server1!$D$2:$D$122
'graphs'!server2[ActiveFiles] server2!$D$2:$D$122
'graphs'!server2[ActiveGB]    server2!$D$2:$D$122
server2!$B$2:$B$122           server2!$D$2:$D$122
server2!$C$2:$C$122           server2!$D$2:$D$122

**Comment by dfinke** [comment]
Will review. Not sure that is possible.
