### ISSUE TITLE
Question on New-PivotTableDefinition -PivotFilter options

### ISSUE THREAD

**Issue by jdwalker519** [dfinke/ImportExcel#1399]
Is there a way, using the -PivotFilter option, to automatically have the Excel sheet filtered on the maximum value that it could be?

**Comment by dfinke** [comment]
Interesting. Could you post an example of what you want to do? Do you want `-PivotFilter` to figure out the max value?

**Comment by jdwalker519** [comment]
Yes, that's exactly what I want to do.  Right now, I have -PivotFilter
'Date', and my choices are any one of three dates possible in the
report....and I want it to figure out the latest date and select that.

**Comment by dfinke** [comment]
Sorry, not going to implement that. Will leave that to folks using the module.

Could you post some data and PowerShell you used to create this. I can think about it an maybe post an example

**Comment by jdwalker519** [comment]
I actually figured out how to do this already, using a COM object.  I'll post the code on Tuesday morning as it's on my work laptop.  Basically, I set the CurrentPage() to 3, because for this report filter, I already knew there were only going to be 3 choices.  More to follow.....
