### ISSUE TITLE
Pivot table: is it possible to apply a filter value?

### ISSUE THREAD

**Issue by vendangh** [dfinke/ImportExcel#1402]
In the example below (Linux) I created a pivot table with a PivotFilter on the field 'City'. Can I instruct ImportExcel to apply the filter value 'Dallas' on startup of Excel?

```
$data = ConvertFrom-Csv @"
Region,State,Units,Price,City
West,Texas,927,923.71,Dallas
West,Texas,927,923.71,Dallas
West,Texas,927,923.71,Houston
North,Tennessee,466,770.67,Nashville
East,Florida,520,458.68,Miami
East,Maine,828,661.24,Bangor
West,Virginia,465,053.58,Richmond
North,Missouri,436,235.67,St Louis
South,Kansas,214,992.47,Wichita
North,North Dakota,789,640.72,Bismarck
South,Delaware,712,508.55,Georgetown
"@

if (Test-Path ~/salesData.xlsx) {
    Remove-Item ~/salesData.xlsx
}

$data | Export-Excel ~/salesData.xlsx -Autosize -AutoNameRange -PivotRows State -PivotColumns Region -PivotData @{'Units'='sum'} -PivotFilter City -Activate -Show
```
My dev environment:
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Linux 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

ImportExcel version:  7.8.4 (Linux)

Regards,
Daniel

**Comment by dfinke** [comment]
No. That is only doable after Excel opens the doc. Some have gone the lengths of creating VBA and enabling that to run when Excel opens. I don't have examples of that.
