### ISSUE TITLE
Import_Excel returns weird value for DateTime from excel column

### ISSUE THREAD

**Issue by Md-Rafiqul** [dfinke/ImportExcel#1403]
`$reminders = Import-Excel -Path $remindersFilePath -HeaderName "Created Date"  -StartRow 2`
This code return something like a1G5g100001CyvmEAC. It changed the actual datetime.
If I want to specify header name and convert to datetime, what can I do?

**Comment by dfinke** [comment]
Please post a reprint, including sample script and data
