### ISSUE TITLE
Could not get Worksheet for Export-Excel even though the worksheet is created in the Excel workbook.

### ISSUE THREAD

**Issue by RebelloPrinston** [dfinke/ImportExcel#1404]
Add-Worksheet : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not 
match any of the parameters that take pipeline input.
At C:\Users\prinston.rebello\Documents\WindowsPowerShell\Modules\ImportExcel\7.8.4\Public\Export-Excel.ps1:130 char:26
+             $ws = $pkg | Add-Worksheet @params
+                          ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (OfficeOpenXml.ExcelPackage:PSObject) [Add-Worksheet], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Add-Worksheet
 
Could not get worksheet Databases
At C:\Users\prinston.rebello\Documents\WindowsPowerShell\Modules\ImportExcel\7.8.4\Public\Export-Excel.ps1:136 char:17
+         catch { throw "Could not get worksheet $WorksheetName" }
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not get worksheet Databases:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not get worksheet Databases

**Comment by dfinke** [comment]
Please sad a simple repro with data and a script
