### ISSUE TITLE
Close-ExcelPackage : Cannot process argument transformation on parameter 'ExcelPackage'. Cannot convert the "OfficeOpenXml.ExcelPackage" value of type  "OfficeOpenXml.ExcelPackage" to type "OfficeOpenXml.ExcelPackage".

### ISSUE THREAD

**Issue by RebelloPrinston** [dfinke/ImportExcel#1407]
I am trying to merge a range of cells in a two columns separately if it's respective column values are same. I am facing two issues here basically, firstly the merge is not working and secondly Close-ExcelPackage is giving this below mentioned error:
Close-ExcelPackage : Cannot process argument transformation on parameter 'ExcelPackage'. Cannot convert the "OfficeOpenXml.ExcelPackage" value of type 
"OfficeOpenXml.ExcelPackage" to type "OfficeOpenXml.ExcelPackage".
At line:34 char:26
+ Close-ExcelPackage -show $objExcel
+                          ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Close-ExcelPackage], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Close-ExcelPackage

**Comment by RebelloPrinston** [comment]
$oldname = 'C:\Users\prinston.rebello\Downloads\Workbook1.0.xlsx'  

$objExcel = Open-ExcelPackage -Path $oldname
$worksheet = $objExcel.Workbook.Worksheets["Sheet1"]
$totalNoOfRecords = $worksheet.Dimension.Rows
$totalNoOfRecords

$colDb = 1
$cellColumn1 = 'A'
$cellColumn2 ='B'
$startAdd1 = $cellColumn1 + 2
$startAdd2 = $cellColumn2 + 2


for ($i = 3; $i -le $totalNoOfRecords; $i++) {
    if($worksheet.Cells.Item($i, $colDb).text -eq $worksheet.Cells.Item($i-1, $colDb).text) {
       $mergeAdd1 = $cellColumn1 + $i
       $mergeAdd2 = $cellColumn2 + $i 
    }
    else {
        $worksheet.Cells["$startAdd1 : $mergeAdd"].Merge = $true
        $worksheet.Cells["$startAdd2 : $mergeAdd2"].Merge = $true
        $startAdd1 = $cellColumn1 + $i
        $startAdd2 = $cellColumn2 + $i
    }
}


Close-ExcelPackage -show $objExcel

**Comment by RebelloPrinston** [comment]
The previous comment is my code snippet with which I am trying to achieve my target

**Comment by dfinke** [comment]
Could you also post the xlsx? Or a repro of this with similar data?

**Comment by RebelloPrinston** [comment]
[Workbook1.0.xlsx](https://github.com/dfinke/ImportExcel/files/10853854/Workbook1.0.xlsx)

**Comment by RebelloPrinston** [comment]
I have attached the xlsx with sample data. Any kind of help or a hint is highly appreciable :)

**Comment by dfinke** [comment]
## Sad

I have a viewer for VS Code by GrapeCity. It looks like it displays correctly.

I don't get that error, but Excel does not like to display it. What version of the module do you have and what version of PS are you running.

Not sure this is solvable. 

![image](https://user-images.githubusercontent.com/67258/222005074-ddf74eec-ef40-44ba-b415-117a6158b9e4.png)

**Comment by RebelloPrinston** [comment]
ImportExcel version 7.8.4
Powershell version 5.1

**Comment by scriptingstudio** [comment]
- right expression is: (no spaces around ":")
```powershell
$worksheet.Cells["${startAdd1}:$mergeAdd1"].Merge = $true
$worksheet.Cells["${startAdd2}:$mergeAdd2"].Merge = $true
```

- second 
I did not go deeper but if I fully remove formatting (just copy data to new file), no errors

**Comment by scriptingstudio** [comment]
this file created by my test script
[Workbook1.0.xlsx](https://github.com/dfinke/ImportExcel/files/10862652/Workbook1.0.xlsx)

**Comment by dfinke** [comment]
Yup works. May be the formatting. I thought the table, filtering could be an issue.

Thanks!

**Comment by RebelloPrinston** [comment]
Hi, thanks for the help, I modified my script and it looks like it's able to achieve the goal, but I am facing a runtime issue and hoping if you can help me with this

This is my modified script:
$oldname = 'C:\Users\prinstonrebello\Downloads\Workbook1.0.xlsx'

$objExcel = Open-ExcelPackage -Path $oldname
$worksheet = $objExcel.Workbook.Worksheets["Sheet1"]
$totalNoOfRecords = $worksheet.Dimension.Rows
$totalNoOfRecords

$colDb = 1
$cellColumn1 = 'A'
$cellColumn2 ='B'
$startAdd1 = $cellColumn1 + 2
$startAdd2 = $cellColumn2 + 2
$mergeAdd1 = $cellColumn1 + 2
$mergeAdd2 = $cellColumn2 + 2

for ($i = 3; $i -le $totalNoOfRecords; $i++) {
    if($worksheet.Cells.Item($i, $colDb).text -eq $worksheet.Cells.Item($i-1, $colDb).text) {
        $mergeAdd1 = $cellColumn1 + $i
        $mergeAdd2 = $cellColumn2 + $i
    }
    else {
        $worksheet.Cells["${startAdd1}:$mergeAdd1"].Merge = $true
        $worksheet.Cells["${startAdd2}:$mergeAdd2"].Merge = $true
        $startAdd1 = $cellColumn1 + $i
        $startAdd2 = $cellColumn2 + $i
    }
    $worksheet.Cells["${startAdd1}:$mergeAdd1"].Merge = $true
    $worksheet.Cells["${startAdd2}:$mergeAdd2"].Merge = $true
}

Close-ExcelPackage $objExcel -show

**Comment by RebelloPrinston** [comment]
Here's the runtime error:
The property 'Merge' cannot be found on this object. Verify that the property exists and can be set.
At line:27 char:5
+     $worksheet.Cells["${startAdd1}:$mergeAdd1"].Merge = $true
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Merge' cannot be found on this object. Verify that the property exists and can be set.
At line:28 char:5
+     $worksheet.Cells["${startAdd2}:$mergeAdd2"].Merge = $true
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

**Comment by scriptingstudio** [comment]
I did not test it but at first sight the last block
```powershell
$worksheet["${startAdd1}:$mergeAdd1"].Merge = $true
$worksheet["${startAdd2}:$mergeAdd2"].Merge = $true
```
should be out of the cycle

**Comment by scriptingstudio** [comment]
got it
a cycle range should be `$totalNoOfRecords+1`

```powershell
$objExcel = Open-ExcelPackage -Path $oldname
$worksheet = $objExcel.Workbook.Worksheets["Sheet1"]
$totalNoOfRecords = $worksheet.Dimension.Rows
write-host $totalNoOfRecords
$totalNoOfRecords++

$colDb = 1
$cellColumn1 = 'A'
$cellColumn2 = 'B'
$startAdd1 = $cellColumn1 + 2
$startAdd2 = $cellColumn2 + 2

for ($i = 3; $i -le $totalNoOfRecords; $i++) {
	if ($worksheet.Cells.Item($i, $colDb).text -eq $worksheet.Cells.Item($i-1, $colDb).text) {
		$mergeAdd1 = $cellColumn1 + $i
		$mergeAdd2 = $cellColumn2 + $i
	}
	else {
		write-host ('cells - {0} / {1}' -f "${startAdd1}:$mergeAdd1","${startAdd2}:$mergeAdd2")
		$worksheet.Cells["${startAdd1}:$mergeAdd1"].Merge = $true
		$worksheet.Cells["${startAdd2}:$mergeAdd2"].Merge = $true
		$startAdd1 = $cellColumn1 + $i
		$startAdd2 = $cellColumn2 + $i
	}
}

Close-ExcelPackage $objExcel -show
```

**Comment by dfinke** [comment]
Code works, I can see the xlsx in VS code with the extension.

Excel can't display. Hmm, interesting.

**Comment by scriptingstudio** [comment]
my test xlsx is without original formatting, pure data

**Comment by scriptingstudio** [comment]
I am not an expert in Excel but after recovering I have something to think of.
![image](https://user-images.githubusercontent.com/17237559/222496880-04a25b32-92c3-47ae-8ab8-780e1b0bec53.png)
and recovery log
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error015280_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\adm_motienko\Downloads\Workbook1.0.xlsx'</summary><removedFeatures><removedFeature>Removed Feature: AutoFilter from /xl/tables/table1.xml part (Table)</removedFeature><removedFeature>Removed Feature: Table from /xl/tables/table1.xml part (Table)</removedFeature></removedFeatures></recoveryLog>
```

I am inclined to believe that this is a corrupted file
