### ISSUE TITLE
Set a Filter with the AutoFilter Switch

### ISSUE THREAD

**Issue by Kerryoaks** [dfinke/ImportExcel#1408]
Not really an issue at all...
Just seeing if this is possible as part of the PS code using the -autofilter switch??

I want to set a filter on the spreadsheet to only show anything with data.  Omitting blank cells for a column with the filter (blanks unticked).  

Hope that makes sense?
Thanks, 
Kerry

**Comment by dfinke** [comment]
Makes sense. There is nothing specific to do that. You can use `=PassThru` on `Export-Excel` or `Open-ExcelPackage` and the returned object has all the propertie and methods that you can manipulate the Workbook, Worksheet and Cells. You can inspect those, there may be a way. You can also google for this and then try to port the solutionm, if you find one.

**Comment by Kerryoaks** [comment]
Thanks Doug, appreciate the reply and suggestion
