### ISSUE TITLE
Excel file not show map pivot table content

### ISSUE THREAD

**Issue by ibran1910** [dfinke/ImportExcel#1409]
i am uploaded excel file then not showing in content map pivot table and its show me my excel version is  not supported but my excel version is also update. what i am doing pleaz suggest any idea and help me 
check my file : 
![image](https://user-images.githubusercontent.com/125349150/222744181-4af27890-f590-44c0-9ac3-a6ad467c7363.png)
![Screenshot 2023-03-03 194838](https://user-images.githubusercontent.com/125349150/222744726-86afba5c-2665-4609-8811-91817ab1d17a.png)
[Call-Center-Deshbord.xlsx](https://github.com/dfinke/ImportExcel/files/10882815/Call-Center-Deshbord.xlsx)

**Comment by dfinke** [comment]
I need more information on the issue you are having. Please post messages and/or screenshots.

**Comment by ibran1910** [comment]
i work in my excel file there is all show map-pivot table content is all right but than Sem file i uploaded hear so not showing my data in map-pivot table 
i attach my original file and screenshots both file plz
[Call-Center-Deshbord.xlsx](https://github.com/dfinke/ImportExcel/files/10883262/Call-Center-Deshbord.xlsx)
![Screenshot 2023-03-03 194838](https://user-images.githubusercontent.com/125349150/222755905-795200a2-e06b-4805-941f-0bac57f5f5de.png)
![Screenshot 2023-03-03 203806](https://user-images.githubusercontent.com/125349150/222755945-4554ff24-34a6-4204-8399-7c1fdebef4d8.png)
![Screenshot 2023-03-03 203830](https://user-images.githubusercontent.com/125349150/222755984-59b40b86-9efc-45ef-96f1-8fa3a30ba5b7.png)
 check

**Comment by dfinke** [comment]
Sorry, I am still not understanding if you are using PowerShell and ImportExcel and what the issue may be
