### ISSUE TITLE
Question: Auto-Collapsed Pivot Table(s)

### ISSUE THREAD

**Issue by forensicsguy20012004** [dfinke/ImportExcel#141]
Good Sir,

Was there ever a resolution/solution for an auto-collapsed pivot table? I gave an example...normally when an individual looks at a doc for the first time...the pivot tables is un-collapsed.

Let me know,
Matt

![image](https://cloud.githubusercontent.com/assets/12624999/20137910/616b8b14-a64b-11e6-981d-63051aa4e82c.png)

**Comment by dfinke** [comment]
Yes, I did investigate and found many property settings that could be tweaked and none worked to get this to work.

That was a while ago and new versions of the underlying DLL have been released, probably worth looking into.

Plus, I could have used this in the last couple weeks.

**Comment by forensicsguy20012004** [comment]
@dfinke....if you want you can close this. It was purely a reminder...that if possible...I would love to test this functionality for you. Either way, your call...keep it open or close it..I am good with whatever...Matt

**Comment by dfinke** [comment]
Thanks Matt. Always good to circle back on these.
