### ISSUE TITLE
Space after URL corrupts output

### ISSUE THREAD

**Issue by PowershellDASified** [dfinke/ImportExcel#1413]
$data = ConvertFrom-Csv @"
Region,State,Units,Website
West,Texas,927,"https://google.com"
North,Tennessee,466,"https://youtube.com"
East,Florida,520,"https://gmail.com"
 South,Delaware,712,"http://google.com "
"@

 $data | Export-Excel C:\temp\temp.xlsx

When opening in Excel, it displays error:
"Errors were detected in file 'C:\temp\temp.xlsx' Removed Records: Hyperlinks from /xl/worksheets/sheet1.xml part"

Removing the trailing space in the last line will fix the issue.

**Comment by dfinke** [comment]
Thank you! Good to know. May update in a future update.
