### ISSUE TITLE
Add-ConditionalFormatting missing the "parameters" for  configuring threecolorscale with midpoint, number and color setttings

### ISSUE THREAD

**Issue by 2source4-DevAdmin** [dfinke/ImportExcel#1414]
The Add-ConditionalFormatting works fine if you use the default settings for the threecolorscale, being "midpoint" 50 precent, and not using number but percentage. With the option reverse you can  change the min and max value color, but  what i am missing is to set the  midpoint as a number. OR do i need to do this with multiple conditional formattings based on an expression.

**Comment by 2source4-DevAdmin** [comment]
I used your own  example and changed the parameter to “ThreeColorScale” and reverse the min and max value colors. But I cannot set the midpoint value.

#Get rid of pre-exisiting sheet
$xlSourcefile = "$env:TEMP\ImportExcelExample.xlsx"
Write-Verbose -Verbose -Message  "Save location: $xlSourcefile"
Remove-Item $xlSourcefile -ErrorAction Ignore

$data = ConvertFrom-csv @"
Store,January,February,March,April,May,June
store27,99511,64582,45216,48690,64921,54066
store82,22275,23708,28223,26699,41388,31648
store41,24683,22583,97947,31999,39092,41201
store16,16568,48040,68589,20394,63202,26197
store21,99353,23470,28398,21788,94101,88608
store86,66662,83321,27489,92627,54084,24278
store07,92692,53300,29284,39643,33556,53885
store58,68875,83705,66635,81025,30207,75570
store01,21292,82341,81339,12505,29516,41634
store82,74047,93325,25002,40113,76278,45707
"@

Export-Excel -InputObject $data -Path $xlSourcefile -TableName RawData -WorksheetName RawData
Export-Excel -InputObject $data -Path $xlSourcefile -TableName TopData -WorksheetName StoresTop10Sales
Export-Excel -InputObject $data -Path $xlSourcefile -TableName Databar -WorksheetName StoresSalesDataBar
Export-Excel -InputObject $data -Path $xlSourcefile -TableName TwoColorScale -WorksheetName StoresSalesTwoColorScale -ConditionalFormat

$xl = Open-ExcelPackage -Path $xlSourcefile

#Set-ExcelRange -Worksheet $xl.StoresTop10Sales -Range $xl.StoresTop10Sales.dimension.address -NumberFormat 'Currency' -AutoSize
#Set-ExcelRange -Worksheet $xl.StoresSalesDataBar -Range $xl.StoresSalesDataBar.dimension.address -NumberFormat 'Currency' -AutoSize
Set-ExcelRange -Worksheet $xl.StoresSalesTwoColorScale -Range $xl.StoresSalesDataBar.dimension.address -NumberFormat 'Currency' -AutoSize


# Apply conditional formatting to the range with the calculated midpoint value
$midpoint = 5000


$conditionalFormatting = @{
    Range        = "B:B"
    Type         = "ThreeColorScale"
    MidpointType = "Number"
    Midpoint     = $midpoint
}

Add-ConditionalFormatting -Worksheet $xl.StoresTop10Sales -Address $xl.StoresTop10Sales.dimension.address -RuleType Top -ForegroundColor white -BackgroundColor green -ConditionValue 10
Add-ConditionalFormatting -Worksheet $xl.StoresSalesDataBar -Address $xl.StoresSalesDataBar.dimension.address -DataBarColor Red
Add-ConditionalFormatting -Worksheet $xl.StoresSalesTwoColorScale -Address $xl.StoresSalesDataBar.dimension.address -RuleType ThreeColorScale -Reverse

Close-ExcelPackage $xl -Show


Met vriendelijke groet / Best regards,​​​​
Bart

Abels
+31332998151
[Klik om het Whitepaper te lezen!]<https://ed3523ccc21242f09cf0b6e13a217dee.svc.dynamics.com/t/r/nEBMz2tNMyz1oTg9yfpUXpgSIo43QxwSnO3uN9lmCPY>
This email is confidential and intended solely for the use of the individual to whom it is addressed.
​Any views or opinions presented are solely those of the author and do not necessarily represent those of 2source4 b.v.
​All e‑mails are subject to change. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited.
​If you have received this email in error please delete it from your system and notify 2source4 at +31 33 299 0994 . All emailed quotes are valid for 7 days and subject to change unless otherwise stated.
​All emailed quotes are subject to 2source4 standard Terms and Conditions which are available upon request and are also available on our website.

**Comment by 2source4-DevAdmin** [comment]
Hi Doug,

I tried to see if I could use the standard excel components, but yes I forgot to remove them from the example.

Maybe a combination of  conditional formatting usen the expression component could deliver the same solution, but I am not sure if I can combine an expression formula with a threecolor scale ( Sort of AND) condition.




Met vriendelijke groet / Best regards,​​​​
Bart

Abels
+31332998151<tel:+31332998151>
[Klik om het Whitepaper te lezen!]<https://ed3523ccc21242f09cf0b6e13a217dee.svc.dynamics.com/t/r/nEBMz2tNMyz1oTg9yfpUXpgSIo43QxwSnO3uN9lmCPY>
This email is confidential and intended solely for the use of the individual to whom it is addressed.
​Any views or opinions presented are solely those of the author and do not necessarily represent those of 2source4 b.v.
​All e‑mails are subject to change. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited.
​If you have received this email in error please delete it from your system and notify 2source4 at +31 33 299 0994 . All emailed quotes are valid for 7 days and subject to change unless otherwise stated.
​All emailed quotes are subject to 2source4 standard Terms and Conditions which are available upon request and are also available on our website.

**Comment by dfinke** [comment]
Did you post it? Or do you mean it is working locally for you and everything is good?

**Comment by 2source4-DevAdmin** [comment]
sorry about the confusion, i just meant i fixed the parameter so the example works but with the default midpoint value of percent end value of 50. What i need is a solution to set the midpoint value to number based on a variable ( or formula)

**Comment by 2source4-DevAdmin** [comment]
No  I removed the “incorrect” parameter, you mentioned, the issue is still  pending, sorry about the confusion


Met vriendelijke groet / Best regards,​​​​
Bart

Abels
+31332998151<tel:+31332998151>
[Klik om het Whitepaper te lezen!]<https://ed3523ccc21242f09cf0b6e13a217dee.svc.dynamics.com/t/r/nEBMz2tNMyz1oTg9yfpUXpgSIo43QxwSnO3uN9lmCPY>
This email is confidential and intended solely for the use of the individual to whom it is addressed.
​Any views or opinions presented are solely those of the author and do not necessarily represent those of 2source4 b.v.
​All e‑mails are subject to change. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited.
​If you have received this email in error please delete it from your system and notify 2source4 at +31 33 299 0994 . All emailed quotes are valid for 7 days and subject to change unless otherwise stated.
​All emailed quotes are subject to 2source4 standard Terms and Conditions which are available upon request and are also available on our website.

**Comment by 2source4-DevAdmin** [comment]
Hello Doug, i receveid a message that this issue will not be fixed. Is it too complex to add this feature?

**Comment by dfinke** [comment]
I took a quick look at the details and did not see a quick solution. I don't have time right now to dig deeper.
