### ISSUE TITLE
Import-Excel chunking

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#1417]
In this [issue ](https://github.com/dfinke/ImportExcel/issues/1053), @delcorral proposed making a change that would allow `-StartRow` & `-EndRow` to handle values greater than 10,000.  The issue was closed without action.
I too could use this functionality.  I have a file with 450k lines of data that I need to read in and filter.  It is currently long-running and requires a ton of resources on the machine running it.  
Any chance to revisit this? 
As always - thanks for the module and the support!

**Comment by uSlackr** [comment]
Looking at the code, ` StartRow` is defined as an [int] which has a max value of  `2147483647`. That doesn't explain why it was failing for @delcorral.  I think I'll take a look at an implementation.

**Comment by dfinke** [comment]
Yeah, let me know. Seems like you could apply chunking without a change.
Seems like it wouldn't be performant.

```powershell
[ValidateRange(1, 1048576)]
[Int]$StartRow = 1,
[Alias('StopRow', 'BottomRow')]
[Int]$EndRow,
```

**Comment by uSlackr** [comment]
I tried using 10000 row chunks and get this error:
````Line |
  46 |              $hold = import-excel $file -startrow $startrow -endrow $e …
     |                                                   ~~~~~~~~~
     | Cannot validate argument on parameter 'StartRow'. The 20002 argument is greater than the maximum allowed range of 9999. Supply an
     | argument that is less than or equal to 9999 and then try the command again.
````

**Comment by uSlackr** [comment]
FYI - my non-chunking version has been running 6 hours on a two yr old i7 with 32GB ram.
