### ISSUE TITLE
Support for Threaded Comments

### ISSUE THREAD

**Issue by Zamrod** [dfinke/ImportExcel#1419]
When you use Set-CellComment it created a note rather than a threaded comment. I've looked through the documentation but I can't seem to find a reason for this. Is it just that there is no support for threaded comments currently?

It looks like EPPlus has this functionality: https://github.com/EPPlusSoftware/EPPlus/wiki/Threaded-comments

**Comment by dfinke** [comment]
Thank you for the issue. The link is for the EPPlus which I don’t support. It requires a paid license. The version I do use may not support this feature.

**Comment by dfinke** [comment]
Those methods were not fixed in the version used in ImportExcel.

You're free to use VBA. I believe Excel has to be running to execute it. ImportExcel works only on creating/reading the xlsx.

I have some examples of creating VBA with the model, but I did not got down that rabbit hole too far.
