### ISSUE TITLE
Enhancement - sort option for columns

### ISSUE THREAD

**Issue by DewArmy** [dfinke/ImportExcel#142]
Unless I've missed it, there doesn't seem to be a way to auto-sort a particular column.  This would be a great addition.

**Comment by dfinke** [comment]
That's right. Sorting has been left to doing it before exporting to Excel. Could you say more about what you're looking for?

**Comment by DewArmy** [comment]
I've had issues with "preformatting" my tables, where the Export-Excel shows unintelligible-to-me data strings and not the output I'm looking for.  I should double check if it's on my end, which may be likely.

What I was looking for was a switch that would sort `[ascending|descending]` using `-sort` and `-sortby` for a specific named column in the header/top row of the worksheet.

I would see it added to a line like so:

`$list | Export-Excel -Path "$Env:USERPROFILE\Desktop\DiskSpace.xlsx" -Show -WorkSheetname DiskSpace -BoldTopRow -AutoFilter -FreezeTopRow -AutoSize` with `-sort descending -sortcolumn XX` where `XX` could be the column letters like A, B, or YZ, **or** a column named in row A that's found in the output of what someone would be using `Export-Excel` for.   For example,  I have columns listed Projects, Dates, Donors etc but not necessarily always in the same columns.   Specifying `-sortcolumn Donors`, regardless of which column it was, would sort that column automatically on export.

I'm not certain if that was explained very well, please let me know if it needs more.

**Comment by dfinke** [comment]
Thanks for writing that up. I had looked at adding that early on. I'll investigate to see what is possible. If you  want, feel free to try to implement and make a PR.

**Comment by DewArmy** [comment]
I should have some time to look into adding it this weekend.  If I come up with anything I will definitely let you know.

**Comment by dfinke** [comment]
I looked EPPlus, it's the library I wrap with PS to generate the xlsx. They don't support sorting.
https://epplus.codeplex.com/workitem/14791

**Comment by kiquenet** [comment]
https://github.com/JanKallman/EPPlus/issues/78

**Comment by dfinke** [comment]
Thanks @kiquenet. Once the dll fully works on dotnet core, the PS module can be tested with it.
