### ISSUE TITLE
ConvertFrom-ExcelToSqlInsert: returns error with empty values when using SingleQuoteStyle parameter

### ISSUE THREAD

**Issue by sannae** [dfinke/ImportExcel#1421]
Linked to the "single quotes" problem already mentioned in #512, #525, #732, #920 and #1412.

It seems that the `-SingleQuoteStyle` parameter can only be used together with the `-ConvertEmptyStringsToNull`.

Using something like:

| FirstName 	| LastName 	| Age 	|
|---------------|---------------|-------|
| John      	| D'Avorio 	|     	|

Then:

* This works:
```powershell
ConvertFrom-ExcelToSqlInsert -Path names.xlsx sheet1 -Singlequotestyle "''" -ConvertEmptyStringsToNull
```
* This returns "You cannot call a method on a null-valued expression."
```powershell
ConvertFrom-ExcelToSqlInsert -Path names.xlsx sheet1 -Singlequotestyle "''"
```

Probably due to the `ToString()` method applied to an empty value (see [here](https://github.com/dfinke/ImportExcel/blob/ab4d03c984fc7a8b129c8fe03af02b1f29f743e5/Public/ConvertFrom-ExcelToSQLInsert.ps1#L45)).

**Comment by dfinke** [comment]
Need to carve out time to look at and verify that
