### ISSUE TITLE
change the first sheet's name

### ISSUE THREAD

**Issue by ericxin1982** [dfinke/ImportExcel#1423]
Hi @dfinke 

Thanks for creating the great tool.
Just wondering whether there is a function to set the sheet name by sheet id.

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
Hi @dfinke 

thanks for quick response.
If I want to change the existing excel file the name of the first worksheet, I just import-excel then do

# rename the sheet
$excel.Workbook.Worksheets[1].Name = "TheNewName"

And save like
Close-ExcelPackage $excel -Show

That is, right?

Thanks
Eric Xin

**Comment by dfinke** [comment]
```
$excel = Open-ExcelPackage c:\test.xlsx
```

**Comment by ericxin1982** [comment]
Thank you very much!
