### ISSUE TITLE
Error with formula INDEX and MATCH

### ISSUE THREAD

**Issue by aszhitarev** [dfinke/ImportExcel#1427]
Hello!
I'm use formula with varibles like
`
$fTargetPath = "Q:\work\target.xlsx"
$xl = Open-ExcelPackage -Path $fTargetPath
$ws = $xl.Workbook.Worksheets['rep']
$j = $xl.Workbook.Worksheets['Journal']
$reps.Count
for ($i=2; $i -le $reps.Count+1; $i++)
{
#$strFinish = "=ИНДЕКС($j!A2:G33; ПОИСКПОЗ(A$i;$j!A2:A33;0); ПОИСКПОЗ(A1;$j!A1:G1;0))"

$strFinish
$ws.Cells[$i,2].Formula = "=INDEX("+$j+"!A2:G33; MATCH(A"+$i+";"+$j+"!A2:A33;0); MATCH(A1;"+$j+"!A1:G1;0))"

$ws.Cells[$i, 10].Formula = "="+$j+"!A"+$i+"+100"
$ws.Cells['K2'].Formula = "=SUM("+$j+"!A2:A23)"
$ws.Cells[10,10].Formula = "=SUM("+$j+"!A2:A23)"

}
Close-ExcelPackage $xl -Show
`
When excel open he says error in first formula
other formulas are work
if i copypaste first formula from output in excel she works
where i'm wrong?

sorry for english

**Comment by dfinke** [comment]
Please could you post the xlsx so I can run the script against and see the issue.

**Comment by aszhitarev** [comment]
Thank you for fast answer!
[target.xlsx](https://github.com/dfinke/ImportExcel/files/11082488/target.xlsx)
here xlsx filew

**Comment by aszhitarev** [comment]
@scriptingstudio , Thank you very much!
Just one small hitch
Your script fills all cells correctly - no complaints here
But the error #NAME hangs in the cells upon opening, and it disappears if you press ENTER in the cell
I tried to open with -Calculate but the error does not go away
Do you have any idea how to fix it?

**Comment by scriptingstudio** [comment]
I did not have any errors.
Test your code on clean data. Or your xlsx may be corrupted.
Cannot say any more.

**Comment by scriptingstudio** [comment]
[assumption] If you see `#NAME` in cells it can probably relate to #1425

**Comment by dfinke** [comment]
Thank you @scriptingstudio for answering that!

**Comment by aszhitarev** [comment]
Thanks again!
I'm change formula on english naming and in works!
have a nice day!
