### ISSUE TITLE
Formula with braces

### ISSUE THREAD

**Issue by aszhitarev** [dfinke/ImportExcel#1428]
Hello!
How i can use formula contains braces in cells?

**Comment by dfinke** [comment]
Please post an example of what you are trying to do.

**Comment by scriptingstudio** [comment]
In my understanding curly braces are applied interactively pressing `Ctrl+Shift+Enter`. Some hints can be found here https://stackoverflow.com/questions/51288271/excel-vba-formula-string-array-formula-how-to-simulate-ctrlshiftenter-press

It says to use the `FormulaArray` property but I get the error 
```
The property 'FormulaArray' cannot be found on this object. Verify that the property exists and can be set.
```
So it's impossible to check this suggestion. I did not explore `ImportExcel` object whether it has the `FormulaArray` property.

The reference https://learn.microsoft.com/en-us/office/vba/api/Excel.Range.FormulaArray

**Comment by dfinke** [comment]
Hit this issue. Don't remember the solution. There may be something in the https://github.com/dfinke/ImportExcel/tree/master/Examples folder. Need to take a look.

**Comment by aszhitarev** [comment]
It is done!
Correct spell
` $wsTokens.Cells[$i,2].CreateArrayFormula("=INDEX(TableWorks[№ п/п], MAX(IF(TableWorks[ID Токена]=A4,ROW(TableWorks[№ п/п])-1)))")`

Thanks again!

**Comment by dfinke** [comment]
Looks like this could be a good candidate for Examples
