### ISSUE TITLE
How do I use Add-ExcelTable with an existing file?

### ISSUE THREAD

**Issue by ToddKlindt** [dfinke/ImportExcel#1433]
I have an XLSX file that is created by some software as a log file. Before I can get into that log and get any information I always insert a table. I'm trying to do that with Add-ExcelTable but I can't figure out the syntax. I'm looking to do something like this:
`Add-ExcelTable -Range $ws.cells[$($ws.Dimension.address)] -TableStyle Light1 -TableName Musictable`
But I don't know what kind of object $ws is. It's not what's created by Import-Excel. I tried Open-ExcelPackage but I couldn't figure out how to do it with that either. 

Can anyone help?
Thanks.

**Comment by dfinke** [comment]
Not sure exactly if this is what you're looking for.

Let's start here:

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = "spike.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue
$data | Export-Excel -Path $xlfile

$excel = Open-ExcelPackage $xlfile

$ws = $excel.Workbook.Worksheets[1]

Add-ExcelTable -Range $ws.cells[$($ws.Dimension.address)] -TableStyle Light1 -TableName Musictable

Close-ExcelPackage $excel -Show
```

**Comment by ToddKlindt** [comment]
That worked perfectly. Thanks. Would you consider adding that to the examples for Add-ExcelTable?

**Comment by dfinke** [comment]
Thanks! Will do.
