### ISSUE TITLE
WARNING autosize

### ISSUE THREAD

**Issue by kymcha** [dfinke/ImportExcel#1438]
I have the following code

$excel = $myData | Export-Excel /tmp/test.xlsx -WorksheetName "test" -TableStyle Light21 -NumberFormat '000000000000' -FreezeTopRow -Append -PassThru
$excel.Save()
$excel.Dispose()

I get the following in the output
WARNING: ImportExcel Module Cannot Autosize. Please run the following command to install dependencies:
apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev

I am not worried by Autosize. I don't want the WARNING. I have tried -WarningAction:SilentlyContinue but the warning still presents.

**Comment by danubie** [comment]
This message is shown during startup of the module. At the first usage of Export-Excel the module is implicitly loaded.

It should not be shown when you explicitly load the module by this
```powershell
$saveWarningPreference = $Global:WarningPreference
$Global:WarningPreference='SilentlyContinue'
Import-Module ImportExcel
$Global:WarningPreference=$saveWarningPreference

# now the warning should not be shown
Get-Module -ListAvailable | Export-Excel -Path ./x.xlsx
```
BTW: I guess you could enclose your Export-Excel with the "Global:WarningPreference" code too. But then you would loose meaningfull warnings as well.

**Comment by kymcha** [comment]
Thank you for that information.
