### ISSUE TITLE
convertfrom-exceltosqlinsert longest characters is 255, can be more?

### ISSUE THREAD

**Issue by ericxin1982** [dfinke/ImportExcel#1439]
Hi @dfinke 

Just wondering, I try to generate a sheet sql insert code from convertfrom-exceltosqlinsert, but since the columns are a bit more, the output are split to 3 rows per each excel row, how come it become this, and I measure each convertfrom-exceltosqlinsert generated row, it is 255 characters,  is there a switch to unlimited this?

Thanks
Eric Xin

**Comment by dfinke** [comment]
Please provide a small repro of the problem. xlsx and scrpit.

**Comment by ericxin1982** [comment]
I have bypassed this issue, thanks for helping me.
