### ISSUE TITLE
-Show from does not work when "Ignore other applications that use Dynamic Data Exchange (DDE)" is enabled

### ISSUE THREAD

**Issue by ShemGyll** [dfinke/ImportExcel#144]
If you have "Ignore other applications that use Dynamic Data Exchange (DDE)" turned on in Excel 2010 (**File > Options > Advanced > General**), using the -Show parameter causes an error on line 417 in Export-Excel.ps1. The actual sheet is exported successfully, but the file itself will not be opened.

Full error:
```
Invoke-Item : An error occurred in sending the command to the application
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\2.2.9\Export-Excel.ps1:417 
char:24
+             if($Show) {Invoke-Item $Path}
+                        ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerSh 
   ell.Commands.InvokeItemCommand
```

**Comment by dfinke** [comment]
Hmm, interesting. You can open the file directly from Excel though?

**Comment by ShinPKSK** [comment]
Yes, absolutely. Actually, Excel **does** still open, but just a blank window with no file.
