### ISSUE TITLE
get excel sheet header array

### ISSUE THREAD

**Issue by ericxin1982** [dfinke/ImportExcel#1440]
Hi @dfinke 

Is there a function I can use to get the excel sheet first row header array?

Thanks
Eric Xin

**Comment by dfinke** [comment]
## No Function 

Here are a couple ways that may help, off the top of my head:

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = "./data.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue
$data  | Export-Excel $xlfile

function usePkg {
    $xl = Open-ExcelPackage $xlfile
    $Columns = $xl.Workbook.Worksheets[1].Dimension.Columns

    $header = for ($column = 1; $column -le $columns; $column++) {
        $xl.Workbook.Worksheets[1].Cells[1, $column].Text    
    }

    $header

    Close-ExcelPackage $xl -NoSave
}

function useImport {
    $r = Import-Excel $xlfile -StartRow 1 -EndRow 1 -NoHeader
    $r.psobject.properties.name | ForEach-Object { $r.$_ }
}

# usePkg
# useImport
```

**Comment by ericxin1982** [comment]
Thanks @dfinke 

usePkg this way works,  useimport this way I tried, it does not work, not sure. But one of them works to me is perfect already.

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
function usePkg {
    $xl = Open-ExcelPackage $xlfile
    $Columns = $xl.Workbook.Worksheets[1].Dimension.Columns

    $header = for ($column = 1; $column -le $columns; $column++) {
        $xl.Workbook.Worksheets[1].Cells[1, $column].Text    
    }

    $header

    Close-ExcelPackage $xl -NoSave
}


Hi @dfinke 

Like this case, my header is start from row2, and I'd like to use open-excelpackage this way, how I can start the row from second.
$Columns = $xl.Workbook.Worksheets[1].Dimension.Columns
I think the statement above is start from row 1.

Thanks
Eric Xin

**Comment by dfinke** [comment]
`Cells[1, $column]`  the #`1` is the row number.

**Comment by ericxin1982** [comment]
Oh, right. Thanks for your advise.
