### ISSUE TITLE
ConvertFrom-ExcelToSQLInsert get pipeline from excel variable

### ISSUE THREAD

**Issue by ericxin1982** [dfinke/ImportExcel#1442]
Hi @dfinke 

$data = Import-Excel 'xxxx.xlsx' -StartRow 2
$data | ConvertFrom-ExcelToSQLInsert -UseMSSQLSyntax -TableName "#dbset" -ConvertEmptyStringsToNull

I am looking for this way, since the header is starting from row 2.
But it does not work as expected.

Thanks
Eric Xin

**Comment by dfinke** [comment]
Please provide a repro example, with data, script and xlsx

**Comment by ericxin1982** [comment]
$data = Import-Excel 'C:\apps\Add-Picture-test.xlsx' -StartRow 2
$data | ConvertFrom-ExcelToSQLInsert -UseMSSQLSyntax -TableName "#dbset" -ConvertEmptyStringsToNull

[Add-Picture-test.xlsx](https://github.com/dfinke/ImportExcel/files/11278500/Add-Picture-test.xlsx)

What I meant is, I targeted this exel file, and I want to skip the first row, but my purpose is to convertfrom excel to sql insert.
Is there any way I can use them together?

Thanks
Eric Xin

**Comment by dfinke** [comment]
Your xlsx does not have that table name. I added one. Looks like the `-StartRow` on `ConvertFrom-ExcelToSQLInsert` is causing an issue:

```powershell
ConvertFrom-ExcelToSQLInsert 'C:\Users\finke\Downloads\Add-Picture-test.xlsx'  -TableName Table1 -StartRow 2 -UseMSSQLSyntax -ConvertEmptyStringsToNull
````

but throws.

no ETA on fixing

**Comment by ericxin1982** [comment]
ConvertFrom-ExcelToSQLInsert has the startrow switch?

**Comment by ericxin1982** [comment]
Ok.

**Comment by ericxin1982** [comment]
Hi @dfinke 

I looked into the code.
![image](https://user-images.githubusercontent.com/9047436/233521578-15a8e4a4-db96-4b00-9675-2062bf5f24c3.png)

I fixed the problem, maybe you can adjust it the code a littie bit, this bug can be fixed.

Thanks
Eric Xin
