### ISSUE TITLE
Export-Excel generated file does not include docProps

### ISSUE THREAD

**Issue by asciiota** [dfinke/ImportExcel#1446]
Hi

I have been using Export-Excel for several years to produce a wide variety of reports.

My workplace recently migrated to Exchange Online and since doing so we have found the any email that includes an excel file generated by Export-Excel was getting stripped from the email.

Upon investigation I discovered the reason was due to the docProps missing from the file it generates.  Here is an example of what I mean.  Take the Excel file and unzip it you can see there is no docProps folder or xml contained within.
![No_docProps](https://user-images.githubusercontent.com/48511146/233964689-cabe5601-cabb-4c4f-8f33-2c26e6930709.jpg)
If I take this file and do nothing more than open it in Excel and Save it in Excel, then the docProps are added even if there were no docProps actually set.
![With_docProps](https://user-images.githubusercontent.com/48511146/233965155-ef0007ec-26a6-4c4f-b823-622899b24e1c.jpg)

As a lot of the reports I created are on servers it is not desirable to have to install Excel everywhere to resolve this problem although I have done so on a couple of servers.

I have not found anyone else raise this issue.

I could not find any command line option to add this through the documentation or examples.

Is there a known workaround to this?
Has adding this ever been suggested?

Look forward to your response.

Regards

Mark

**Comment by dfinke** [comment]
I believe this the first time for all of this!

Off the top of my head:

First - EPPlus does not default to setting this, may not have the ability at all.
Second - using `-PassThru` on `Export-Excel` or `Open-ExcelPackage` you may be a property setting on the Excel Object Model
Third - update the xlsx [xml] "directly". Don't have a write up, I'd have to look at the code to see where that was done

**Comment by scriptingstudio** [comment]
In my experience, no generated (by any app) xlsx included the `docProps` folder ever.

**Comment by dfinke** [comment]
Thanks @scriptingstudio. Have not encountered that.

So cracking the xlsx? Or ?

**Comment by scriptingstudio** [comment]
> So cracking the xlsx? Or ?

I send such files via two external on-premise Exchange systems and have never had any problem. I have no any chance to use Exchange Online. I am not sure but think the issue is specific case.

If anybody experienced a similar scenario...

**Comment by asciiota** [comment]
Thanks for the feedback.
When we were using on premises exchange we never had this issue either so I am not surprised if other have not seen this.

Following the feedback I had a go at the following post export-excel processing of the file.

1. unzipping the xlsx file the export-excel created to a directory (c:\temp\unzipped)
2. creating a docProps (C:\temp\unzipped\docProps) directory
3. added two files, app.xml and core.xml, in the docProps folder
4. deleted the original xlsx file that export-excel had created
5. zipped the directory (C:\temp\unzipped) back into a file with the name of the original file

I had low expectations of this working but was surprised to see that it did work. 
Powershell was able to send the file via Exchange Online and it was not stripped out.
As a result I do have a way forward as it is possible to do this programmatically.

Given that no one has seen or heard of this issue before maybe it is something unique to our environment that I am not aware of.

**Comment by scriptingstudio** [comment]
Exchange Online antivirus issue? Can you tune it setting exclusions?
