### ISSUE TITLE
Can I fork Copy-ExcelWorksheet into an import object?

### ISSUE THREAD

**Issue by teknowledgist** [dfinke/ImportExcel#1447]
This is probably a dumb question, sorry.

When I do `$Fund = import-excel $inputFile`, I get a simple array of objects representing the rows of the spreadsheet.  When I use `Copy-ExcelWorksheet`, I populate a worksheet with all its complexity, and I find it difficult to iterate through it to filter, sort and calculate properties of the cell contents.

What is the best way to both copy a worksheet into a workbook and get the array object that would come from using `import-excel`?  Am I stuck doing both actions?

Alternatively, how can I iterate through a copied worksheet object?  

If I import and then export to a worksheet, I get a very different worksheet than the original (with merged cells, etc.).

Thanks!

**Comment by dfinke** [comment]
There is no `-PassThru` on `Copy-ExcelWorksheet`. You'll need to do a two-step process. Copy then Import
