### ISSUE TITLE
Unable to open file with Import-Excel

### ISSUE THREAD

**Issue by GamerClassN7** [dfinke/ImportExcel#1449]
HI latelly i have a problem using the import-excell function:

i am getting this wierd error, even on newly created file.

![image](https://user-images.githubusercontent.com/22167469/236179584-aa3049bb-5278-42e7-ab7d-e925ac7643a2.png)

**Comment by dfinke** [comment]
Could you say a bit more about “newly created”

**Comment by GamerClassN7** [comment]
> Could you say a bit more about “newly created”

I ment it the way that i am unable to open new empty excel created and saved from withinn the excel not the excel whitch was prewiouselly opened by your awasome lib in past :(

**Comment by GamerClassN7** [comment]
unforchunatelly i canot it is in high secure enviroment and i am unable to get file from there :( could this have something to do with AIP to DLP ?

**Comment by dfinke** [comment]
ok, if you can make a repro of the issue with a sheet that does not have sensitive data I can better troubleshoot.
