### ISSUE TITLE
DataValidation does not copy

### ISSUE THREAD

**Issue by jgreenephd** [dfinke/ImportExcel#145]
When copying cells that use data validation the data validation piece does not copy correctly.
Is there another way to enter data validation for a cell?

`$report = Import-Excel .\$file | Export-Excel $file -PassThru `
`$ws=$report.Workbook.Worksheets[1]`
`$ws.Cells[7,3].Copy(($ws.cells[8,3]))`
`$ws.Cells[8,3].DataValidation  -eq $ws.Cells[7,3].DataValidation` 
The last statement equates to false

**Comment by dfinke** [comment]
I don't know. I have never worked with that aspect of Excel. The underlying library seems to have support but I don't know how much or if it is robust.

http://epplus.codeplex.com/workitem/list/basic?field=CreationDate&direction=Descending&issuesToDisplay=Open&keywords=DataValidation&emailSubscribedItemsOnly=false

**Comment by jgreenephd** [comment]
I was unable to resolve the copy issue but I was able to setup Data Validation on a per cell basis with following Powershell:
`$validation=$ws.DataValidations.AddListValidation("C7")`
`$validation.Formula.ExcelFormula="='Data Validation'!`$A`$1:`$A`$2"`
