### ISSUE TITLE
50mb XLSX files require 90 to 200 minutes to Import-Excel

### ISSUE THREAD

**Issue by RaysCars** [dfinke/ImportExcel#1453]
Import-Excel is the best powershell module EVER! 

Any ideas why Import-Excel requires hours to read large(?) excel files?

Working with XLSX files that are 50mb to 60mb, 30 to 40 worksheets. Large worksheets may have 100k+ rows. These XLSX files are, typically created with Export-Excel which take minutes to write but when reading them Import-excel takes 90 to 200 minutes.

Import-Excel Version 7.8.4 
PsEdition Core
PsVersion  7.3.0 
OS Microsoft Windows 10.0.19045

Example syntax:
`Import-Excel R:\file.xlsx  -WorksheetName *`

**Comment by dfinke** [comment]
@RaysCars Thank you!

There is a significant performance hit I introduced a while back when implementing that feature and have not had time to work through fixing.

I can't find in the issues the version you need to revert to for the perf to be back to reasonable.

**Comment by RaysCars** [comment]
Thanks the rapid response. If you want to point me to the applicable
module, maybe I could poke around at it?

**Comment by dfinke** [comment]
Yeah, in the issues here I was searching for the version before the perf hit.

It was identified but I can't find that issue with the version that is faster.

After that version I added the `Import-Excel ./data.xlsx *` feature to read all the sheets, and that caused the perf issue for large 
xlsx.
