### ISSUE TITLE
[proposal] Update-FirstObjectProperties optimizations

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#1455]
Would it better?

```powershell
function Update-FirstObjectProperties {
    [CmdletBinding()]
    param (
        [Parameter(ValueFromPipeline)]
        $InputObject,
	[switch]$Noempty
    )
    begin {
	$union = [System.Collections.Generic.List[object]]::new()
	$property = [System.Collections.Generic.List[object]]::new()
    }
    process {
	$pset = $InputObject.psobject.properties.name
	if ($pset) {
	    $property.AddRange(@($pset))
	    $union.Add($InputObject)
	} elseif (-not $noempty) {$union.Add($InputObject)}
    }
    end {
	$Union | Select-Object -Property ($property | Select-Object -Unique)
    }
}
```

**Comment by dfinke** [comment]
Wow the way back machine. I see @jhoneill was in there. I had a version early on, not sure if this is pure James or re-work of what I did.

I was a complete experiment. I wasn't lazy, I probably would have removed it.

What are you proposing is better? Less logic? The last line of your approach, the piping jumps out for performance. That shouldn't matter. Not going to do this on lots of objects and thousands of properties

**Comment by scriptingstudio** [comment]
Collecting and analyzing data I have to deal with data aligning. It can look like jhoneill's or iron7's `join-object` but a bit different. Your approach is in my collection too. It caught my eye and I decided to improve it a bit. It gets rid of slow ops in cycle like `add-member`, `get-member`, rebuilding array.

> The last line of your approach, the piping jumps out for performance.

Not so much. And `$property | Select-Object -Unique` can be replaced with `[System.Collections.Generic.HashSet[object]]@($property)` for speed.

> I was a complete experiment. I wasn't lazy, I probably would have removed it.

OK. Close it.

**Comment by dfinke** [comment]
Thanks! It was good to look at again.
