### ISSUE TITLE
Import-excel and export-excel required?

### ISSUE THREAD

**Issue by DarenDaigle** [dfinke/ImportExcel#146]
I have an existing spreadsheet that I wish to edit.

If I run **$test=import-excel -Path c:\scripts\file.xlsx**. Then I get an object that I may run a foreach on and apparently change the data.  However it does not save.  There are no rows collection or anything other than a count (which I assume is an overload).

However, to gain access to the Cells collection I run the following.

**$test=import-excel -path c:\scripts\file.xlsx | export-excel c:\scripts\file.xlsx -passthru**

To me, the act of importing the files should give me the same thing as what the second command does.

Without an object model for this, it becomes difficult to determine what commands create what objects.

Daren

**Comment by dfinke** [comment]
This follows the PowerShell model of `Import-Csv` and `Export-Csv`. `-PassThru` could be implemented in `Import-Excel` like is it in `Export-Excel`.
