### ISSUE TITLE
How to deal with numbers when using Export-Excel

### ISSUE THREAD

**Issue by jp-villette** [dfinke/ImportExcel#1460]
Hello,

Got the usual number Excel problem.

I am currently working on Excel files and I want to make the repetitive operations a little bit more automatic. One of the excel file is more difficult than the others.

There is a single column with serial number, mostly in Hexadecimal format. But some of them are pure numericals and others, not all of them, are only with an E somewhere in the 12 digits. That's the problem.

I am trying to impose a format to those cells : $format = New-excelStyle -Range "A:A" -NumberFormat "<value>" and a -Style $format in the Export-Excel.

For example, when i open the Excel file at the end, i have for example  300826651386 becoming 3,00827E+11, 40072666E124 becoming 4,0072666E+131. When i set the format in the export-excel as "Number" or "0" or "Text", i have a part of the solution but with exceptions and errors changing without any recovery of the original value. 

The only solutions I found were to play with CSV files only and load them manually in Excel using the Transform Data option  or change these values by adding a prefix in letters to stop this reformat of cells.

Any idea how to solve this using Export-Excel ?

JPV

**Comment by dfinke** [comment]
Please could you post an example, data, script, xlsx

**Comment by jp-villette** [comment]
Sure. Of course i can't communicate directly the data and the script i am working on but i did reproduce the same problem using an example. I can summerize it but i think it's only an "auto format" problem in Excel.

[Examples.xlsx](https://github.com/dfinke/ImportExcel/files/11632637/Examples.xlsx)
and the script:

[CmdletBinding()]
Param
(
    [Parameter(Mandatory=$true)]
	[String]
    $SourceExcelFile = $null,
    
    [Parameter(Mandatory=$true)]
    [String] 
    $SourceTabName = $null,

    [Parameter(Mandatory=$true)]
    [String]
    $TargetExcelFile = $null,

    [Parameter(Mandatory=$true)]
    [String]
    $TargetTabName = $null
)

$ImportData = Import-Excel -Path $SourceExcelFile -WorksheetName $SourceTabName

$format = New-excelStyle -Range "A:A" -NumberFormat "Text"
$ImportData | Export-Excel -Path $TargetExcelFile -WorksheetName $TargetTabName -Style $format

I run the script to create the results:
.\jpv-test-numberproblem.ps1 -SourceExcelFile .\Examples.xlsx -SourceTabName "Examples" -TargetExcelFile "Results.xlsx" -TargetTabName "Results"    

![Results](https://github.com/dfinke/ImportExcel/assets/105923867/2ad12143-07ed-4f3c-81e6-9ea1837f2668)

NOTA : i put a JPG file of the results, The upload of the results.xlsx failed.

For the first three rows, it's only a format problem. But for the other, the original value are lost. I was expecting a results like

SN examples	Should Be
3,51565E+11	351564856482
5,64565E+11	564564800000
8,34685E+11	834684684321
3,21321E+18	3213210313E9
3,2103E+106	321032101E98
3,2107E+207	32106854E200
#NUM!	32103210E350
#NUM!	3210654E3210
3,213E+18	321300000E10

I tried "Text", "Number" and "@", the results may not be the same but there are always errors. It's like the "auto-format" of Excel is applied before the modification of the cells' format.

the orignal file "Examples.xlsx" is correct as i created it from a CSV file, doing in Excel Data->From Text/CSV

![image](https://github.com/dfinke/ImportExcel/assets/105923867/2e106352-a676-4373-876e-c70f80d6778c)

then doing TransformData changing the parameter from:
= Table.TransformColumnTypes(#"Promoted Headers",{{"SN examples", type number}, {"Should Be", type number}, {"", type text}})
to:
= Table.TransformColumnTypes(#"Promoted Headers",{{"SN examples", type text}, {"Should Be", type text}, {"", type text}})

![image](https://github.com/dfinke/ImportExcel/assets/105923867/d75a5f98-86ac-4046-8c8e-85c4dd10aafd)


it created a correct table.

I am trying to obtain the same results but using Export-Excel but i don't know how.

thanks in advance for your help.
JPV

**Comment by dfinke** [comment]
### Try

```powershell
$ImportData | Export-Excel -Path $TargetExcelFile -WorksheetName $TargetTabName -NoNumberConversion 'SN examples','Should Be'
```

**Comment by jp-villette** [comment]
perfect. 
![image](https://github.com/dfinke/ImportExcel/assets/105923867/ce2e4f9a-8210-46be-8c3c-de9ccb67bbb7)

It's working as needed. thanks for your help.
