### ISSUE TITLE
Import-Excel performance

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#1466]
It is probably related to #1299 and #1279

line 148
`$xlBook["$targetSheetname"] = @()`
line 238
`$xlBook["$targetSheetname"] += [PSCustomObject]$NewRow` - This is array operation performance issue.

Should be:
`$xlBook["$targetSheetname"] = [System.Collections.Generic.List[object]]::new()`
`$xlBook["$targetSheetname"].Add([PSCustomObject]$NewRow)`

It will address memory leaking as well.

**Comment by dfinke** [comment]
Thanks. Let me dig down on that. I did go lazy on the array and it bit me hard

**Comment by scriptingstudio** [comment]
Have tested the case. Maximum boost is 80% or so.
Came to understanding that all the time is taken by cell array indexing. If the API had a cursor like in databases, extracting cell data would be faster.
But anyways, `list` is better way.

**Comment by dfinke** [comment]
Great! Yes, in the early days I was disappointed there wasn’t a cursor like approach.
