### ISSUE TITLE
Copy-ExcelWorkSheet Loses Column

### ISSUE THREAD

**Issue by rdcpro** [dfinke/ImportExcel#147]
When I use the Copy-ExcelWorkSheet cmdlet, the destination worksheet is missing a column.  Oddly, it's not consistent in which column is lost.

Steps to repro:

1. Given a source workbook with two worksheets, Data and ListLookup
2. Given a destination workbook with one worksheet, Data
3. Execute the following command, and note that the Destination ListLookup worksheet is missing a column

`Copy-ExcelWorkSheet "SheetCopyTest-Source.xlsx" "ListLookup" "SheetCopyTest-Destination.xlsx" "ListLookup"`

In my test workbooks, the data in Column B is missing in the destination (see SheetCopyTest-Destination-Failed).  

Note: I'm running this from the PowerShell ISE PSVersion:
5.0.10586.494    

[SheetCopyTest-Destination-Failed.xlsx](https://github.com/dfinke/ImportExcel/files/634331/SheetCopyTest-Destination-Failed.xlsx)
[SheetCopyTest-Source.xlsx](https://github.com/dfinke/ImportExcel/files/634330/SheetCopyTest-Source.xlsx)
[SheetCopyTest-Destination.xlsx](https://github.com/dfinke/ImportExcel/files/634332/SheetCopyTest-Destination.xlsx)

**Comment by dfinke** [comment]
Yes, `Column B` will also be missing doing an `Import-Excel`. This module depends on data having the first row as headers (or no headers). Currently there is no support for mixing the two.

![image](https://cloud.githubusercontent.com/assets/67258/20992271/f1374320-bcb0-11e6-845d-e93fa1d57073.png)
