### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by Friends4U** [dfinke/ImportExcel#1477]
Hi,

I have the following code to generate my xlsx files:

```
$params = @{
    AutoSize      = $true
    AutoFilter    = $true
    TableName     = 'AllUsers'
    TableStyle    = 'Medium7'
    BoldTopRow    = $true
    WorksheetName = 'AllUsers'
    PassThru      = $true
    Path          = 'C:\AllUsers.xlsx'
}
$xlsx = Import-Csv C:\AllUsers.csv -Delimiter ";" | Export-Excel @params
$ws = $xlsx.Workbook.Worksheets[$params.Worksheetname]
$ws.Cells.Style.HorizontalAlignment="Left"
$ws.View.ShowGridLines = $false
Close-ExcelPackage $xlsx
```

This works great! But my table stops at line 650 while there is content until line 655. Is this a bug?

**Comment by Friends4U** [comment]
Perhaps it is another problem. As the lines that are below the table are on another position in my CSV. So something is going wrong while converting to xlsx. Only problem is that I cannot share the CSV (privacy) :(
So I will close this question.

**Comment by dfinke** [comment]
Ok. When posting in the future, would need to see the data or subset that causes the issue so it can be debugged.
