### ISSUE TITLE
Accessing Objects Returned in invoke-excelquery

### ISSUE THREAD

**Issue by stewart-anderson** [dfinke/ImportExcel#1478]
I don't think this is an issue with ImportExcel,  more likely an issue with me!!

Queries work great and I can see results.  However I'm having some trouble actually accessing the values.   I'm looking at usign an excel sheet to store properties and valeus I want to use in a script to control some configuration script.  So I want to be able to capture values form the sheet and use them.

It seems the result of the query is an array of PSCustomObject,  but I don't seem to be able to access the object properties in teh way I expect from reading PsCustom object docs as MS. 

The initial query result says its a System.Object[]
Each item in the list says its a ystem.Management.Automation.PSCustomObject 

I can then use get-member to see the members but don't seem to be able capture the actual members properties

Do you have examples of processing a query and assigning the values?  I know I'm missing something basic,  but can't see what.

**Comment by stewart-anderson** [comment]
Turns Out I had quoted the  select as as "x " in the query and it was producing quoted  keys which I cold not access with what I thought was the key name!

I'd seen the quotes, but never having use PS for this,  thought it was normal or jut a variation in how it was displaying on my screen. 

Left the question,  in case there is someone else like me!

**Comment by dfinke** [comment]
Glad it worked out. Wished all issues started out with the sentenced the used 🙂
