### ISSUE TITLE
IPv4 addresses are not handled correctly

### ISSUE THREAD

**Issue by SebastianMeisel** [dfinke/ImportExcel#1486]
When trying to import data containing IPv4 addresses, these are considered numbers, making them unreadable. 
Example:
Get-NetTCPConnection -State Established | Export-Excel
Get-NetIPAddress | Export-Excel

It would be great if they could be imported as text.

**Comment by dfinke** [comment]
## Try

```powershell
Get-NetIPAddress | Export-Excel -NoNumberConversion <property name>
```

**Comment by SebastianMeisel** [comment]
This works perfectly. Thanks!
