### ISSUE TITLE
Close-ExcelPackage throws error in debug mode on windows server 2022

### ISSUE THREAD

**Issue by Reiner2010** [dfinke/ImportExcel#1489]
I run a PowerShell script as scheduled task on a Windows Server 2022. The script is running fine, if it is running from PowerShell command line.
But from time to time it's necessary to do some debugging with Visual Studio Code and I noticed that then the command Close-ExcelPackage is throwing an error. Either this one:
MethodInvocationException: %UserProfile%\Powershell\Modules\ImportExcel\7.8.4\Public\Close-ExcelPackage.ps1:29:20

Line 29		else { $Excelpackage.Save() }

Exception calling "Save" with "0" argument(s): "Error saving file \\UNC\SHARE\Path\ExcelDocument1.xlsx

or that one:
MethodInvocationException: %UserProfile%\Powershell\Modules\ImportExcel\7.8.4\Public\Close-ExcelPackage.ps1:680:20

Line 680		else { $pkg.Save() }

Exception calling "Save" with "0" argument(s): "Error saving file \\UNC\SHARE\Path\ExcelDocument2.xlsx

The script creates round about 80 Excel files and so the most of them are created, even in debug mode. But I have no idea why this happen. I have changed the path to anonymize it and saw that the path in the error message is wrong:
%UserProfile%\Powershell\Modules\ImportExcel\7.8.4\Public\Close-ExcelPackage.ps1
it should be:
%UserProfile%\**Documents**\Powershell\Modules\ImportExcel\7.8.4\Public\Close-ExcelPackage.ps1

**Comment by dfinke** [comment]
Don't know. Need some more details. First time this has been reported.

**Comment by Reiner2010** [comment]
Hello Doug,

what do you need?

Grüße, regards
Reiner



Internal: All rights reserved. Distribution within the company, customer and partners

Von: Doug Finke ***@***.***>
Gesendet: Dienstag, 1. August 2023 17:25
An: dfinke/ImportExcel ***@***.***>
Cc: Foerg Reiner IM2 ***@***.***>; Author ***@***.***>
Betreff: Re: [dfinke/ImportExcel] Close-ExcelPackage throws error in debug mode on windows server 2022 (Issue #1489)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>
Caution: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Don't know. Need some more details. First time this has been reported.

**Comment by dfinke** [comment]
Good question. Can't really help if I don't have a simple repro.

**Comment by Reiner2010** [comment]
I fixed this issue with a function that is checking if the xlsx file was created, if not, it tries it again with a maximum of three tries. Since then, no errors occurred.
