### ISSUE TITLE
Enhancement - Choose colour for Row headings

### ISSUE THREAD

**Issue by spamtomas** [dfinke/ImportExcel#149]
Maybe i have missed the option but would be good to choose a color for the heading row and maybe a color for the rest of the data

**Comment by dfinke** [comment]
Yes, there is this but I don't think it fits the bill `TitleBackgroundColor `TableStyle`

**Comment by spamtomas** [comment]
Yeah unfortunately that wont do the column headers, which is what i'm looking for. If there is an enhancement list, would love to see it added!

**Comment by dfinke** [comment]
If you use the `-PassThru` on the `Export-Excel`, you have access to the worksheet etc. You could look in there and see if you can colorize it that way.

I had wanted to add this, I didn't work out the best way to generalize though.

**Comment by dfinke** [comment]
First pass. I think it has teeth. Need to work out Ranges etc.

``` powershell
$cellStyles =$(    
    New-CellStyle 1 1
    New-CellStyle 1 2     
)

$EvenStyles=$(
    New-CellStyle 2 1 -BackgroundColor Red
)

$OddStyles=$(
    New-CellStyle 3 1 -BackgroundColor Green
)

$data | 
    Export-Excel $xlfile -show -CellStyle ($cellStyles+$EvenStyles+$OddStyles)
```

![image](https://cloud.githubusercontent.com/assets/67258/21294908/bbc45cbe-c516-11e6-9c42-3afae93cbc75.png)

**Comment by dfinke** [comment]
I think this approach, while a bit more work for users, gives a nice balance to flexibility.

```powershell
Get-Process |
    Select Company,Handles,PM, NPM| 
    Export-Excel $xlfile -Show  -AutoSize -CellStyleSB {
        param(
            $workSheet,
            $totalRows,
            $lastColumn
        )
                
        Set-CellStyle $workSheet 1 $LastColumn Solid Cyan

        foreach($row in (2..$totalRows | Where {$_ % 2 -eq 0})) {
            Set-CellStyle $workSheet $row $LastColumn Solid Gray
        }

        foreach($row in (2..$totalRows | Where {$_ % 2 -eq 1})) {
            Set-CellStyle $workSheet $row $LastColumn Solid LightGray
        }
    }
```

![image](https://cloud.githubusercontent.com/assets/67258/21297491/7b75535a-c54f-11e6-8ce4-605aef2c5687.png)

**Comment by spamtomas** [comment]
Thats looking really good! perfect for my needs!

**Comment by dfinke** [comment]
Added the feature https://github.com/dfinke/ImportExcel/commit/6c8ddf6e1b5b6f6c952d1780327abb12f3a0ef24

**Comment by spamtomas** [comment]
Amazing. Thanks so much!!!!!

**Comment by dfinke** [comment]
You're welcome. Thanks for requesting the feature.
