### ISSUE TITLE
Export a string of numeric data as string field into Excel file

### ISSUE THREAD

**Issue by wyatt-wong** [dfinke/ImportExcel#1499]
I imported an Excel file with a Serial No. column that may contains all numeric value (e.g. 0012345678) into an array variable. When I export the array variable into an Excel file, I found the Serial No. column shows the same numeric value (e.g. 0012345678). How do I force the Serial No. column to export as a string field ?

`$Data File = "Test.xlsx"
$MyFile= Import-Excel $Data_File

    $ExportFile = 
        foreach ($row in $MyFile)
        {
            [PSCustomObject]@{
                "No." = [String]$row.field1
                "Description" = [String]$row.field2
                "Serial No." = [String]$row.field3 # May contains all numeric such as 0012345678
                "Location" = [String]$row.field4
            }
        }
$ExportFile | Export-Excel "Output.xlsx"`

**Comment by stahler** [comment]
Try using the -NoNumberConversion parameter

```powershell
[PSCustomObject]@{
    "No." = '0001'
    "Description" = "Martin E15"
    "Serial No." = "01500000002526"
    "Location" = "New York"
} | Export-Excel -NoNumberConversion 'Serial No.', 'No.'
```
![image](https://github.com/dfinke/ImportExcel/assets/1991193/ff871c24-3e32-44a5-93a3-cb4d4a2e77eb)

**Comment by stahler** [comment]
Yes.  
```PowerShell
Get-Help Export-Excel -Parameter NoNumberConversion
```
![image](https://github.com/dfinke/ImportExcel/assets/1991193/f9232fbb-55fb-4cb3-a007-0f158d0bb85d)
You can also use -NoNumberConversion * to indicate no conversion for all fields.

**Comment by wyatt-wong** [comment]
Thank you.
