### ISSUE TITLE
Enhancement-Add powershell core support

### ISSUE THREAD

**Issue by chuanjiao10** [dfinke/ImportExcel#150]
Add powershell core support.

an unofficial port of the EPPlus library to .NET Core
https://github.com/VahidN/EPPlus.Core

some .psm1 code:
if ($PSEdition -eq 'linux')
{
    add-tpye EPPlus.core.dll 
}

if ($PSEdition -eq 'Desktop')
{
    add-tpye EPPlus.dll 
}

**Comment by dfinke** [comment]
Thanks for the link, I'll take a look.

**Comment by ncmpuolitaival** [comment]
Another vote for this feature.

PS6 beta on Mac reports $PSEdition as Core.

**Comment by datenschieber** [comment]
Another vote from me!

**Comment by dfinke** [comment]
Yup. I pulled down the latest EPPlus DLL from their repo. It doesn't work on dotnet core still. They have a dependency on `System.Drawing` and are looking to use another library to solve that.

I'm excited to get this to work too, need to wait and see though.

**Comment by ncmpuolitaival** [comment]
It seems that there is now "official" beta version available with .net core support.

https://www.nuget.org/packages/EPPlus/4.5.0-beta

**Comment by dfinke** [comment]
Thanks, I can double check. I pulled an earlier version of it, but they still had not reworked the dependency on the above namespace

**Comment by dfinke** [comment]
Thanks, I can double check. I pulled an earlier version of it, but they still had not reworked the dependency on the above namespace

**Comment by jasonchester** [comment]
Any updates on powershell core support?

**Comment by dfinke** [comment]
Checked the other day, still not yet

**Comment by dfinke** [comment]
Some activity for EPPLus and PS Core https://github.com/JanKallman/EPPlus/issues/224

**Comment by mi-hol** [comment]
in issue #365 you wrote:
'I was able to run the module on my Linux VM in Azure and on my local machine PS Core 6.

Until PS Core is GA and it can run in Appveyor with continuous integration and more tests. Use it at your own risk.

https://ci.appveyor.com/project/dfinke/importexcel/build/1.0.171'

when I follow the link I'm getting error: Build not found or access denied.

Is a grant permission required?
![build](https://user-images.githubusercontent.com/22799428/43886789-29b0d49a-9bbd-11e8-9e77-67c8dfdd7306.PNG)

**Comment by mi-hol** [comment]
the second topic 'Until PS Core is GA and it can run in Appveyor with continuous integration' throws me because PS Core 6.0 is GA for Ubuntu 16.04 since a long time. Is there anything preventing Appveyor from running with this version?
Note: I'm using PS Core 6.1 Beta on WSL- Ubuntu 18.04 for unrelated reasons. Modules working on the GA release should run unmodified on the Beta

**Comment by dfinke** [comment]
Will revisit later

**Comment by mi-hol** [comment]
did you intentionally close it?
