### ISSUE TITLE
GetExcelTable.ps1 not seeing any tables

### ISSUE THREAD

**Issue by mcqueene** [dfinke/ImportExcel#1502]
Not sure what I'm doing wrong but GetExcelTable isn't returning any table names for me. This is the code:

`if($TableName) {
        $Table = $Worksheet.Tables[$TableName]
    } else {
        $Table = $Worksheet.Tables | Select-Object -First 1
    }`

I tried to see if the file was working and I can see the worksheets but nothing for tables when debugging:

`    Write-Host '$Excel.Workbook.Worksheets' $Excel.Workbook.Worksheets
    Write-Host '$Worksheet.Tables ' $Worksheet.Tables  
`

`Get-ExcelTable .\samplefile.xlsx MySheet MyTable`

**Comment by dfinke** [comment]
Please couldl you post some PS and and xlsx that repros this.

Unfortunately, GetExcelTable.ps1 was a bit of an experiment. So ...

Post that and I'll take a look and see what is what.

**Comment by mcqueene** [comment]
Actually it looks like I wasn't using the proper version. I found one that is pending as part of #1470. I think this version works with my spreadsheet. It appears to grab the table in one of my sheets but it does not find the named range. I incorrectly assumed named ranges and tables were the same. So I think this is really a non issue and I need to look for something that works with named ranges. Sorry for the confusion.

**Comment by mcqueene** [comment]
Closing due to misunderstanding what version to use.
