### ISSUE TITLE
Sorting Row Labels in Pivot Table

### ISSUE THREAD

**Issue by Shooting300FPS** [dfinke/ImportExcel#1506]
I've added a Pivot Table to my spreadsheet.  I'm wondering if there is a way to have the Row Labels sorted.  By default the Row Label entries look like this:
![image](https://github.com/dfinke/ImportExcel/assets/119536933/a3036dde-4cad-4007-82d8-5128185ebebf)

I want them to look like this:
![image](https://github.com/dfinke/ImportExcel/assets/119536933/61c7aa78-6040-413e-9a5d-752add8650c0)

I can manually do the sorting.  However, other people will be running the script and will have to work with the resulting Pivot Table.  They are not familiar with Pivot Tables or comfortable manipulating them.  I'm trying to make the file has hands off as possible.  I also realize this may not be possible, but thought it was worth the ask.

**Comment by dfinke** [comment]
I don't remember if those are sortable via code. The Pivot table is rendered when Excel is visible and that is when sorting can be done. I beleive it needs to be manual.

**Comment by ninmonkey** [comment]
What if you use "add pivot table to the datamodel", could that help access data pre-render?

**Comment by dfinke** [comment]
How do you ` "add pivot table to the datamodel"`?

**Comment by Shooting300FPS** [comment]
There were similar questions/asks posed on the site about modifying pivot tables using the Add Pivot Table.  I figured minewas a longshot, but thought I would ask in case I missed something.  Other people that need to interact with Pivot Tables, don't know how to create them, but they certainly can figure out how to sort them. If I'm able to create an unsorted Pivot table, then I can that part of process from a couple pages to a couple lines,  The Add Pivot Table is still a win for everybody.   

I have other data validation, configuration, and manipulation that needs to be done, so two manual steps aren't a big deal.  I was thrilled that I could get the Add Pivot Table to work.
Thanks again for creating and supporting this great module.  It has saved me hours and hours of work every month.
