### ISSUE TITLE
Sort Column Remove Duplicates

### ISSUE THREAD

**Issue by Shooting300FPS** [dfinke/ImportExcel#1507]
I'm working on creating an inventory report for my manager.  I'm combining data from multiple CSV files.  I'm able to put them all together with no problems.  Every time I generate this report, I need to sort the worksheet based on device serial number and then by user role.  After the sort, I need to remove all of the duplicate values.  Is there a way to do either or both of these actions?

**Comment by dfinke** [comment]
you need to do that before it is exported to excel. PowerShell should be able to handle it.

**Comment by ninmonkey** [comment]
> Remove duplicates

`Sort-Object` can handle that. You can either

- use a list of properties that are your distinctness test
- or use the ScriptBlock parameter for custom logic

Here I use a triplet to determine uniques

```ps1
$all_records = @(
    Import-Csv -Path $csv1 
    Import-Csv -Path $csv2
)

$uniques = $all_records | Sort-Object -Unique {@(
    $_.SerialNumber
    $_.Date.Year
    $_.Date.Month
)}

## followed by a regular sort . you could do it in one pass
## I split it up to display a script block
$uniques
    | Sort-Object SerialNumber, UserRole 
    | Export-Excel ...
```

**Comment by Shooting300FPS** [comment]
Thanks for the direction.  Import-Excel is a great module that I for hyper-focused on using it for all Excel and Powershell functionality.  I overlooked using basic powershell scripting to do the sorting and removing dupes.

**Comment by Shooting300FPS** [comment]
Thanks for the direction.  Import-Excel is a great module that I got hyper-focused on using it for all Excel and Powershell functionality.  I overlooked using basic powershell scripting to do the sorting and removing dupes.
