### ISSUE TITLE
Add-ConditionalFormatting -Address parameter is NOT mandatory

### ISSUE THREAD

**Issue by wyatt-wong** [dfinke/ImportExcel#1508]
The Add-ConditionalFormatting Help message indicate -Address <Object> parameter is mandatory. However refer to case #1503 and #1505, I found that NOT only the -Range parameter is missing in the SYNTAX of Add-ConditionalFormatting Help message, but also that the -Address parameter is OPTIONAL.

So I wonder if -Address and -Range parameter have the SAME meaning in the Add-ConditionalFormatting ? Or else they are DIFFERENT ?

````
PARAMETERS
    -Address <Object>
        A block of cells to format - you can use a named range with -Address $ws.names[1] or $ws.cells["RangeName"]
        
        Required?                    true
        Position?                    1
        Default value                None
        Accept pipeline input?       False
        Accept wildcard characters?  false

**Comment by dfinke** [comment]
`So I wonder if -Address and -Range parameter have the SAME meaning`

I didn't look. Likely similar. Address may be able to take a full sheetname and sheet range where as the -Range can only take "A1:C3". Or vis a versa.

Not complicated to experiment with.

**Comment by wyatt-wong** [comment]
> `So I wonder if -Address and -Range parameter have the SAME meaning`
> 
> 
> 
> I didn't look. Likely similar. Address may be able to take a full sheetname and sheet range where as the -Range can only take "A1:C3". Or vis a versa.
> 
> 
> 
> Not complicated to experiment with.

I thought you wrote this Powershell Module but you didn't know that either ? If -Address and -Range are different, examples should be given to show their differences. Furthermore -Range should be added to the SYNTAX section followed by a short description of -Range.

**Comment by dfinke** [comment]
If you continue with the attitude, I'll block from repo.

**Comment by dfinke** [comment]
Okay, so you did what you're suppose to, dig deeper and you found the answer.

But first, you had to spew nonsense at me about some imagined scenarios and insult me.

Due diligence on your end. Embrace that concept.
