### ISSUE TITLE
Is it possible to create several pivot charts on one excel file?

### ISSUE THREAD

**Issue by Stephanevg** [dfinke/ImportExcel#151]
First of all, I love this tool. huge kudos to all of the people that contributed to this project, and big high five for @dfinke which made this tool possible.

The use case I have is that I want to create a dashboard, using information from various sources. 
I can create 1 pivot table, but I couldn't find either with google, nor in the help a way to do this. I also tried adding using several hashtables  to the InputRows, which didn't work.

Thanks

**Comment by dfinke** [comment]
Thank you!

I have not investigated creating more than one pivot table. I'm not sure if EPPlus supports that.
