### ISSUE TITLE
Copy-ExcelWorkSheet used multible times into one excel file corrupts centent

### ISSUE THREAD

**Issue by jhejgard** [dfinke/ImportExcel#1515]
First thanks for importExcel Powerhell module, it is a fantastic peace of work you have made.

Step 1 :  $GLOBAL:ResultSet = Invoke-Sqlcmd -ServerInstance "$SQLServer" -Database "$SQLDatabase" -Username $sqluser -Password $sqlpw -Query $TabSQL

Step 2: I execute a Copy-ExcelWorkSheet txlsx template to a new xlsx file, to get a logo in left corner 

Step 3: $GLOBAL:ResultSet | Export-Excel $xlsx_Tab -AutoSize  -StartRow 10 -WorksheetName $Current_Tabname -AutoFilter -BoldTopRow -TableStyle Medium3  -FreezePane 11,2  -KillExcel  
 $xlsx_Tab is an perfect excel file, I can open it and it is fine.

Step 4: Copy-ExcelWorkSheet -SourceWorkbook $xlsx_Tab -sourceWorksheet "$Current_Tabname" -DestinationWorksheet "$Current_Tabname" -DestinationWorkbook "$xlsx_Report"

Problem: I have in $xlsx_Report is the final result xlsx file with multible tabs as step 1 to 4 is repeated a number of times. When I open the final result xlsx I get this prompt "We found a problem with some content in 'xxxxxxxxx.xlsx'. Do you want us to try to recover as much we can ? I reply Yes and next it shows 'Repaired Records: Table from /xl/tables/table2.xml part (table) ... repeats for table3 and table 4

No data is removed from the tabs and after repair is seems ok.

I have troubleshooted and when there are two or more tabs I get the error. Each tab is an independent correct excel file, but copying them into the target excel file creates some kind of corruption I cannot find out why, hope you have some ideas to work around this issue. Initially I did not save each tab on the way, but added that to see which one where corrupted and non of them are corrupted, only the final result excel file. I am using importExcel 7.4.1

**Comment by dfinke** [comment]
Thank you and thank you for using ImportExcel.

Don't know. Would need a small repro of this to see. Possible `Copy-ExcelWorkSheet` could corrupt.

`Table from /xl/tables/table2.xml` seems to indicate that there are tables being copied, maybe.

An additional trouble shooting idea. 
- Do the `Copy-ExcelWorkSheet` that causes the corruption. 
- Copy it, rename it to corrupt.
- open the original and recover
- the xlsx are zip files of xml
- unzip both, look at the xml and compare the diff
- should be some clues

May not be solvable via ImportExcel

**Comment by jhejgard** [comment]
I have created a powershell script that re-produce the error and also solve the issue using export-excel in stead. (Excel-Report-Export-Excel-not-corrupted.xlsx)
It creates 4 excel files using export-excel and also one final excel file using export-excel that works. Finally to use Copy-ExcelWorksheet to copy the 4 excel files into one excel that now becomes corrupted.  (Excel-Report-Copy-ExcelWorksheet-is-corrupted.xlsx)
As I have found a work around I have closed the issue. Thanks for the help and support.



--- script start
$Path = (Get-Location).Path
$ExcelReport = "$path\Excel-Report-Copy-ExcelWorksheet-is-corrupted.xlsx"
$ExcelReport2 = "$path\Excel-Report-Export-Excel-not-corrupted.xlsx"


$Excel_1 = "$path\Excel_1_not_Corrupted.xlsx"
$WSName_1 = "Excel-1" 
$TabName_1 = "MyTable1" 

$Excel_2 = "$path\Excel_2_not_Corrupted.xlsx"
$WSName_2 = "Excel-2" 
$TabName_2 = "MyTable2" 

$Excel_3 = "$path\Excel_3_not_Corrupted.xlsx"
$WSName_3 = "Excel-3"
$TabName_3 = "MyTable3" 
 
$Excel_4 = "$path\Excel_4_not_Corrupted.xlsx"
$WSName_4 = "Excel-4"
$TabName_4 = "MyTable4" 

If(Test-Path -Path $Excel_1){remove-Item -Path $Excel_1} 
If(Test-Path -Path $Excel_2){remove-Item -Path $Excel_2} 
If(Test-Path -Path $Excel_3){remove-Item -Path $Excel_3} 
If(Test-Path -Path $Excel_4){remove-Item -Path $Excel_4} 
If(Test-Path -Path $ExcelReport){remove-Item -Path $ExcelReport} 
If(Test-Path -Path $ExcelReport2){remove-Item -Path $ExcelReport2} 




Function Fill_Array($Max){
  $i = 0
  $Array = @()
  Do {
    $i++
    $Row = "" | Select 'Date','Name','Value'
    $Row.Date = Get-Date
    $Row.Name = -join (((48..57)+(65..90)+(97..122)) * 80 |Get-Random -Count 12 |%{[char]$_})
    $Row.Value = Get-Random -Maximum 1000
    $Array +=  $Row
  } Until ($i -gt $Max)
  Return $Array
}

$Excel_1_Data = Fill_Array -Max 10   
$Excel_1_Data   | Export-Excel $Excel_1 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_1 -TableName $TabName_1 -TableStyle Medium3  -StartRow 10
$Excel_1_Data   | Export-Excel -Path $ExcelReport2 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_1 -TableName $TabName_1 -TableStyle Medium3 -StartRow 10
 

$Excel_2_Data = Fill_Array -Max 11
$Excel_2_Data | Export-Excel $Excel_2 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_2 -TableName $TabName_2 -TableStyle Medium3   -StartRow 10
$Excel_2_Data  | Export-Excel -Path  $ExcelReport2 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_2 -TableName $TabName_2 -TableStyle Medium3   -StartRow 10


$ExcelReport3 = Fill_Array -Max 12
$ExcelReport3 | Export-Excel $Excel_3 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_3 -TableName $TabName_3 -TableStyle Medium3   -StartRow 10
$ExcelReport3 | Export-Excel  -Path $ExcelReport2 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_3 -TableName $TabName_3 -TableStyle Medium3   -StartRow 10

$ExcelReport4 = Fill_Array -Max 13  
$ExcelReport4 | Export-Excel $Excel_4 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_4 -TableName $TabName_4 -TableStyle Medium3   -StartRow 10
$ExcelReport4 | Export-Excel  -Path $ExcelReport2 -AutoSize -AutoFilter -BoldTopRow -WorksheetName $WSName_4 -TableName $TabName_4 -TableStyle Medium3   -StartRow 10


Copy-ExcelWorksheet -SourceObject  $Excel_1  -SourceWorksheet $WSName_1 -DestinationWorkbook $ExcelReport -DestinationWorksheet $WSName_1  
Copy-ExcelWorksheet -SourceObject  $Excel_2  -SourceWorksheet $WSName_2 -DestinationWorkbook $ExcelReport -DestinationWorksheet $WSName_2  
Copy-ExcelWorksheet -SourceObject  $Excel_3  -SourceWorksheet $WSName_3 -DestinationWorkbook $ExcelReport -DestinationWorksheet $WSName_3  
Copy-ExcelWorksheet -SourceObject  $Excel_4  -SourceWorksheet $WSName_4 -DestinationWorkbook $ExcelReport -DestinationWorksheet $WSName_4  


--- script end

**Comment by dfinke** [comment]
Thank you for working throught that. Do you know why this works and the orignal way corrupts the xlsx?
