### ISSUE TITLE
New to Powershell, need help

### ISSUE THREAD

**Issue by docwobster** [dfinke/ImportExcel#152]
Hello all,

I'm new to powershell and to programming in general but I'm trying to learn.  This seems like a great module but I'm not understanding where to start.

I have a csv file that I want to convert to an xlsx file, and then create a pivot table and do a bunch of formatting (cell coloring, sorting, rearrange worksheets, etc).

Anyone have a simple script that I can start out with to learn all of this better (specifically the first steps of converting csv to xlsx and then creating a pivot table) and be able to utilize this module which sounds amazing.

Thanks,

-Dustin

**Comment by dfinke** [comment]
A quick start would be `Import-Csv target.csv | Export-Excel c:\temp\target.xlsx -Show`

Then check to see if these my be helpful.
https://github.com/dfinke/ImportExcel/tree/master/Examples
