### ISSUE TITLE
Pivot Table Running total

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#1523]
I am trying to change a pivot table from showing the sum of a daily cost to a running total.  I can accomplish this within excel by following the below steps.

Within a pivot table rightclick --> value field Settings --> Show Values As Tab

Then change the show values as to "Running total in"

Is there a way todo this within ImportExcel.  I understand that some portions of excel are not exposed by EPPlus so if this is not possible I understand why.

This is the code that I am using to generate a base pivot table .

I was wondering if the "PivotData" parameter is what needs to be changed but I am not sure what to the function to.

```
Remove-Item D:\temp\example.xlsx -force
$xl_package = ConvertFrom-Csv @"
DateTime,Cost_Currency
2023-09-01T00:00:00Z,3055.45
2023-09-02T00:00:00Z,2658.33
2023-09-03T00:00:00Z,2565.02
2023-09-04T00:00:00Z,2982.84
2023-09-05T00:00:00Z,3163.03
2023-09-06T00:00:00Z,3198.42
2023-09-07T00:00:00Z,3237.81
2023-09-08T00:00:00Z,3229.08
2023-09-09T00:00:00Z,2734.59
2023-09-10T00:00:00Z,2624.09
2023-09-11T00:00:00Z,3199.68
2023-09-12T00:00:00Z,3298.55
2023-09-13T00:00:00Z,3220.39
2023-09-14T00:00:00Z,3150.38
2023-09-15T00:00:00Z,3193.71
2023-09-16T00:00:00Z,2890.10
2023-09-17T00:00:00Z,2686.03
2023-09-18T00:00:00Z,3264.13
2023-09-19T00:00:00Z,3354.55
2023-09-20T00:00:00Z,3385.49
2023-09-21T00:00:00Z,3389.46
2023-09-22T00:00:00Z,3369.50
2023-09-23T00:00:00Z,2853.90
2023-09-24T00:00:00Z,2737.41
2023-09-25T00:00:00Z,3374.69
2023-09-26T00:00:00Z,3466.35
2023-09-27T00:00:00Z,3503.20
2023-09-28T00:00:00Z,3393.33
2023-09-29T00:00:00Z,3332.84
2023-09-30T00:00:00Z,2912.69
"@ | Export-Excel -PassThru -Path D:\temp\example.xlsx -TableStyle Medium13 -tablename "Monthly_Costs" -AutoSize -WorksheetName Total_Costs

add-Worksheet -ExcelPackage $xl_package -WorksheetName "Charts"

$pivotTableParams_Daily_Costs = @{
    PivotTableName  = "Cost Per Day"
    Address         = $xl_package."Charts".cells["A7"]
    SourceWorkSheet = $xl_package."Total_Costs"
    PivotRows       = "DateTime"
    PivotData       = @{"Cost_Currency" ="Sum"}
    PivotTableStyle = 'Light21'
    IncludePivotChart= $true
    ChartTitle="Cost Per Day"
    ChartHeight="360"
    ChartWidth="500"
    ChartType="Line"
    Nolegend=$true
    ChartRow=6
    Chartcolumn=4
}

Add-PivotTable @pivotTableParams_Daily_Costs -PassThru | Out-Null

$xl_package.Workbook.Worksheets['Charts'].pivotTables[0].DataFields[0].Format="$#,##0.00" #this is how you set number format of pivot table

Close-ExcelPackage $xl_package -Show
```

Thanks for any help

**Comment by dfinke** [comment]
please post a pic of both.

**Comment by g-pearl** [comment]
The per day Cost.
![image](https://github.com/dfinke/ImportExcel/assets/15739535/8ea3bd43-6c84-4e29-b381-b56eb1bd27b5)


The running Total 
![image](https://github.com/dfinke/ImportExcel/assets/15739535/6e1d6a16-dd2b-44f5-ad0a-d0c0ba4050b2)


I am then using this to create a trend graph of the spend.

Thanks

**Comment by dfinke** [comment]
Looks like a no go. The version of the EPPlus library I use to create the xlsx does not support the `ShowDataAs` property.

The new version does but they broke many things to fix many things and they charge a license fee for each user.

There is probably a way to update the XML in the xlsx to do this.

I'll leave that as an exercise to the reader.

**Comment by g-pearl** [comment]
Thanks that is what I figured would be the case.  I will see if I can update the xml.  I did not know that was possible.  Hopefully the web has some examples.  Appreciate the review.
