### ISSUE TITLE
Problems creating multiple charts using ImportExcel PowerShell module, in the same tab with different sources

### ISSUE THREAD

**Issue by newbie987664** [dfinke/ImportExcel#1525]
I have a number arrays (of objects) that I want export to an Excel file using the ImportExcel module, showing them on a summary tab at the start of the Excel document but the two charts created so far, only appear to (both) show the data and legend of the last array not the data of each array in a separate charts as expected. <br>

**Comment by dfinke** [comment]
Please provide a repro of data, script and resulting xlsx.

**Comment by newbie987664** [comment]
$TargetExcelFileLocation2` = "c:\temp\test_CAPoliciesForApps.xlsx"
if (Test-Path $TargetExcelFileLocation2) 
{
  Remove-Item $TargetExcelFileLocation2
}

$allPolicies = Get-AzureADMSConditionalAccessPolicy
$allOauthApplications = Get-AzureADApplication -All $true

$cAPolicyUsage_ChartData = @()
$applicationUsage_ChartData = @()
$allEnterpriseApplications = Get-AzureADServicePrincipal -All $true | ? {$_.Tags -eq "WindowsAzureActiveDirectoryIntegratedApp"}

`#` Create CA Policy usage array
$tempChartCustomObject = [pscustomobject][ordered]@{
    "Description" = "Used"
    "Value" = ($allPolicies.count)
}
$cAPolicyUsage_ChartData += $tempChartCustomObject

$tempChartCustomObject = [pscustomobject][ordered]@{
    "Description" = "Available"
    "Value" = (195-($allPolicies.count))
}
$cAPolicyUsage_ChartData += $tempChartCustomObject


`#` Create App Usage array

$tempChartCustomObject = [pscustomobject][ordered]@{
    "Description" = "Application Registration (OAuth)"
    "Value" = ($allOauthApplications.Count)
}
$applicationUsage_ChartData += $tempChartCustomObject

$tempChartCustomObject = [pscustomobject][ordered]@{
    "Description" = "Enterprise Application (SAML)"
    "Value" = ($allEnterpriseApplications.Count)
}
$applicationUsage_ChartData += $tempChartCustomObject

`#` Create CA Policy Usage chart definition
$tempTitle = "CA Policy Usage `n(195 max) " 

$chartDef1 = New-ExcelChartDefinition -Title $tempTitle `
    -ChartType Pie `
    -XRange Description `
    -YRange Value `
    -Column 0 `
    -Row 0 `
    -RowOffSetPixels 0 `
    -ColumnOffSetPixels 0 `
    -ShowPercent


`#` Create CA Policy Usage chart definition
$tempTitle = "Number of Applications Authenticating`n(Enterprise Apps "+($allEnterpriseApplications.Count)+" / App Registrations "+($allOauthApplications.Count)+")"

$chartDef2 = New-ExcelChartDefinition -Title $tempTitle `
    -ChartType Pie `
    -XRange Description `
    -YRange Value `
    -Column 8 `
    -Row 0 `
    -RowOffSetPixels 0 `
    -ColumnOffSetPixels 0 


$cAPolicyUsage_ChartData | 
    Export-Excel -Path $TargetExcelFileLocation2 -WorksheetName Summary -ExcelChartDefinition $chartDef1 -AutoNameRange 

$applicationUsage_ChartData | 
    Export-Excel -Path $TargetExcelFileLocation2 -WorksheetName Summary -ExcelChartDefinition $chartDef2 -Show -AutoNameRange -AutoSize


[test_CAPoliciesForApps.xlsx](https://github.com/dfinke/ImportExcel/files/13052872/test_CAPoliciesForApps.xlsx)

**Comment by newbie987664** [comment]
The data in the arrays is:-

PS C:\WINDOWS\system32> $cAPolicyUsage_ChartData

Description Value
----------- -----
Used          183
Available      12



PS C:\WINDOWS\system32> $applicationUsage_ChartData

Description                      Value
-----------                      -----
Application Registration (OAuth)  1795
Enterprise Application (SAML)     2216



PS C:\WINDOWS\system32> 

<img width="408" alt="ArrayData" src="https://github.com/dfinke/ImportExcel/assets/148478540/0ab50a50-138b-4ac6-ae26-e9188b23ff8c">

**Comment by newbie987664** [comment]
Closing issue as workaround has been found

**Comment by dfinke** [comment]
What was the workaround?
