### ISSUE TITLE
Import a html table into an Excel sheet

### ISSUE THREAD

**Issue by anthony46292** [dfinke/ImportExcel#154]
In order to import some betting odds to an Excel sheets automatically, I tried to use Powershell 5.0 and the command Import-html from the ImportExcel module. The table I tried to import is avaible in the following web page :

    http://www.bet365.com/#/AC/B1/C1/D13/E29631468/F2/R1/

But the problem is : it creates a blank Excel sheet, because it doesn't find any html table in the page. So, my question is : how to know if what looks like a table in a html file is a html table? And if it isn't, how import such a table in a Excel file?

Thanks,

Anthony

**Comment by dfinke** [comment]
Looks like that page is generated with JavaScript and not an Html Table. In your browser, right mouse click the page and select `view page source`

**Comment by anthony46292** [comment]
Thanks dfinke, and in the case where it is generated with JavaScript, it's not possible to import into a Excel file?

**Comment by dfinke** [comment]
A mechanism would need to be created to scrap what the JavaScript generates. I believe I've seen those built in python and node.js. I have not looked at porting it to PS. Once you have the data, it can be munged into PowerShell object arrays which can be piped into the "Export-Excel"
