### ISSUE TITLE
Import-Excel reads null values with PowerShell 7.4.0

### ISSUE THREAD

**Issue by mcqueene** [dfinke/ImportExcel#1540]
Has anyone tested Import-Excel with the latest version of PowerShell 7.4.0? I just updated and when working with existing scripts every value returned is null. I tested using the example located here and it returns a measure count of zero. Can anyone try the example and see if they get different results? Here's the code I used (Excel file is located in Github examples). 

```powershell
$xlfile = "C:\no_backup\yearlySales.xlsx"
$result = Import-Excel -Path $xlfile -WorksheetName * -Raw
Write-Host $result.Count
$result | Measure-Object
```

**Comment by dfinke** [comment]
I have 7.4 preview at the moment. Looks ok. Maybe 7.4 GA has an issue

![image](https://github.com/dfinke/ImportExcel/assets/67258/b2bc393d-c3a6-4c8c-ab73-89d99c18a8cf)

**Comment by mcqueene** [comment]
FYI - rebooting didn't fix the issue, not that I expected it would. Also note that my `$r.count` command does show 1200 records, but the `Measure-Object` command shows zero because each row is null/empty.

**Comment by dfinke** [comment]
I can’t repro. So don’t know

**Comment by mcqueene** [comment]
Working on some other code I bet it is related to this issue [https://github.com/PowerShell/PowerShell/issues/20757](url) which I will try to test.

**Comment by mcqueene** [comment]
I did a test and if I insert `$ExecutionContext.SessionState.LanguageMode = 'FullLanguage'` into the top of the function it works again. I assume this is a setting change from my organization and not a result of the new version of PowerShell so I will close the issue.
