### ISSUE TITLE
Issue Pulling From File With Fancy Headers

### ISSUE THREAD

**Issue by isuwill** [dfinke/ImportExcel#155]
Hello Doug,

Thanks for your work on this module.  I used it successfully to pull information from a planning worksheet for a project this fall.  I created the document so the formatting was very basic.  For some projects coming up early next year, I wanted to start using the module with more documents formatted like the ones my customers love.

Today, I created a complex document from an excel template.  I've attached the document and provided my command line and a few of the errors I received.  I was't sure if I was doing it wrong or if there was a bug.  Please advise.  Thanks

PS C:\VPSA_Support\Scripts> **Import-Excel '.\Warehouse inventory1.xlsx' -WorkSheetname 'Bin Lookup' -HeaderRow 4**
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\2.2.10\ImportExcel.psm1:62 char:9
+         $worksheet=$workbook.Worksheets[$WorkSheetname]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 

[Warehouse inventory1.xlsx](https://github.com/dfinke/ImportExcel/files/671070/Warehouse.inventory1.xlsx)

**Comment by dfinke** [comment]
There is something going on in your xlsx. don't know what it is. I created a new xlsx, copied and pasted your 'bin lookup' sheet data to the new one and it worked.

Unfortunately, my guess is, the excel template (or something) is introducing something that is causing EPPlus to complain. I'm not going to have time to dig into this.

**Comment by isuwill** [comment]
I should have thought of that.  I copied the content of all three worksheets to a new spreadsheet, and it worked just fine.  So nothing wrong with the fancy headers.  Thanks!
