### ISSUE TITLE
Feature request: Create Slicers

### ISSUE THREAD

**Issue by Stephanevg** [dfinke/ImportExcel#156]
Hi Doug,

I was wondering if it was possible to create 'slicers' for the pivot tables? If not, this could be a nice feature to add.
The feature in excel allows to filter the data, and the graph updates accordingly (see image below), it would defenitley help the community a lot!
![image](https://cloud.githubusercontent.com/assets/6302961/21607882/693b6456-d1b9-11e6-8683-70eef9057e8a.png)

Regards

**Comment by dfinke** [comment]
I looked at slicers at one point. They are definitely cool. I'll dig a bit and see how effort it is. I suspect if it's not already there in EPPlus, it'll be a challenge.

**Comment by dfinke** [comment]
Did a little digging, looks like the underlying library does not expose SlicerCaches to interact with.

**Comment by Stephanevg** [comment]
Ha, that is too bad :(
Any other way we could to get that in?

**Comment by dfinke** [comment]
I think it may be doable via COM. That means Excel needs to be installed so it can be launched.

**Comment by cloudanimal** [comment]
Doug, would there be any way to resurrect this? or create a new request?
https://www.epplussoftware.com/en/Developers/Slicers

I cannot tell you how much time this module is saving me.
Where is your coffee/tea/beer fund located? :)

**Comment by dfinke** [comment]
@cloudanimal Thank you! Glad it is helpful. On the this main repo page in the rendered README, above Overview, last button on the right is a donate.

Unfortunately, the new version of the EPPlus library requires a purchased license by each user. Plus, it has been updated and introduced numerous breaking changes.

Would love to have slicers and the new features.
