### ISSUE TITLE
Feature Request: Set the default worksheet when the workbook is opened

### ISSUE THREAD

**Issue by merill** [dfinke/ImportExcel#1561]
There doesn't seem to be a way to configure the active worksheet when a workbook is opened.

It looks like EPPlus seems to support an API. 

Would be neat if we can have this as a cmdlet. 

https://stackoverflow.com/questions/59308799/epplus-set-default-worksheet

**Comment by dfinke** [comment]
@merill Thanks for trying ImportExcel and the request. That can be done in a couple ways. Let me know how it goes. I'll add this to the examples folder.

```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfile = "$PSScriptRoot\spike.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

function UseActivate {
    $data | Export-Excel -Path $xlfile -WorksheetName Tab1
    $data | Export-Excel -Path $xlfile -WorksheetName Tab2 -Activate
    $data | Export-Excel -Path $xlfile -WorksheetName Tab3 -Show
}

function UseSelectWorksheet {
    $data | Export-Excel -Path $xlfile -WorksheetName Tab1
    $data | Export-Excel -Path $xlfile -WorksheetName Tab2 
    $data | Export-Excel -Path $xlfile -WorksheetName Tab3

    $xlpkg = Open-ExcelPackage $xlfile

    Select-Worksheet -ExcelPackage $xlpkg -WorksheetName Tab3
    Close-ExcelPackage $xlpkg -Show
}

UseSelectWorksheet
```

**Comment by merill** [comment]
Amazing. That worked perfectly @dfinke thanks a lot.

Interestingly, I was trying to figure it out yesterday and copilot was totally hallucinating. It did get very close with Set-ActiveSheet instead of Select-Worksheet. Even the parameter names were correct.

![CleanShot 2024-02-04 at 12 46 41@2x](https://github.com/dfinke/ImportExcel/assets/1288081/42ab41db-9bd8-40de-9b31-865be9f85b9c)

**Comment by dfinke** [comment]
Cool. When copilot first came out I was promoting it about PowerShell and Excel.  Didn’t know about my module. Took a few months is additional training. Then it knew some things and started hallucinating function names. I was like hmm, those are better ones than I came up with.
