### ISSUE TITLE
export-excel produces an invalid format for use as a data source

### ISSUE THREAD

**Issue by Hutoa** [dfinke/ImportExcel#157]
Microsoft Excel will produce the following error when attempting to add the workbook produced by export-excel as an external data source.  "External table is not in the expected format".  If you open the generated workbook and save it the data source works fine.  If you look at the file size post save it is over twice the size suggesting Excel is maybe altering the format at save.

To reproduce this problem, create a workbook with any data in it using the module export-excel.  Open a blank excel workbook, attempt to create a data source from the file (Data tab/Existing Connections/Browse for More , select your export-excel generated workbook, Test Connection).

I'm attempting to use the module to generate reference data in one workbook which is that referenced from other workbooks.

![issue with file format](https://cloud.githubusercontent.com/assets/23084924/22284460/5a560f36-e2df-11e6-917a-d3847b567f6e.PNG)

I've recreated the problem on the following Excel versions 

2013 (15.0.4885.1000) MSO (15.0.4893.1000) 32-bit
2016 MSO (16.0.4456.1003) 32-Bit

Thanks for your help in advance.

**Comment by Hutoa** [comment]
Hi Doug, any ideas on this issue?  I'm keen to use the excel import module in many more areas of automation.  

Thanks,

Rob.

**Comment by dfinke** [comment]
Tried it with this version of Excel and the `ImportExcel` and it was able to import the newly created sheet from the other xlsx.

I won't be able to test it on different versions of Excel.

![image](https://cloud.githubusercontent.com/assets/67258/26330443/eb75957c-3f19-11e7-8543-bc6a4a7dc5f8.png)

```
ModuleType Version    Name
---------- -------    ----
Script     2.4.0      ImportExcel
```
