### ISSUE TITLE
Order in -PivotData is not maintained

### ISSUE THREAD

**Issue by CraigI** [dfinke/ImportExcel#158]
I am setting up a pivot table and need to have the columns in a specific order. I was expecting that the order would be maintained based on how you input it. However when viewing the created pivot table the order is not maintained.

-PivotData @{ActiveUnits='sum';ConsumedUnits='sum';TotalCost='sum'} `

and on the Pivot Chart I get ConsumedUnits, TotalCost, ActiveUnits.

Here is the overall command I'm using (Attached)

[Code.txt](https://github.com/dfinke/ImportExcel/files/735975/Code.txt)

**Comment by dfinke** [comment]
try `[ordered]@{ActiveUnits='sum';ConsumedUnits='sum';TotalCost='sum'}`

**Comment by jbarrar** [comment]
I am experiencing the same issue with Pivot Table column order. Using [ordered] caused me to see a huge spike in CPU and a ton of binding errors. I'm only looking at a couple thousand rows and just basic sums. If I leave off [ordered], the sheet generates in 20 seconds, albeit with unusually ordered columns in the pivot.

**Comment by dfinke** [comment]
Could you post a sample of the data you are seeing this happen on?
