### ISSUE TITLE
Conditional Formatting (Date)

### ISSUE THREAD

**Issue by montanaprogrammer** [dfinke/ImportExcel#1592]
I have the following script:

```
$data = Import-Csv -Path $csvFilePath
$p=@{
    ConditionalType='Expression'    
    Range="C2:C$($data.Length + 1)"
}
$todayPlusSixty='C2 < today() + 720'
$ct2 = New-ConditionalText -Text $todayPlusSixty  @p -BackgroundColor yellow -ConditionalTextColor white 
$xl = Export-Excel -InputObject $data -Path $xlfile -AutoSize -ConditionalFormat $ct2 -PassThru
Set-Format -Worksheet $xl.Sheet1 -Range "C:C" -NumberFormat 'MM/dd/yyyy HH:mm:ss'
Close-ExcelPackage $xl -Show
```

($data is an existing CSV file)

Column C has a date formatted as -Format "MM/dd/yyyy HH:mm:ss", however I cannot get the cell to have a background color of Yellow even though there are cells with data such as:

05/12/2024 10:01:42
05/19/2024 10:07:38
05/26/2024 10:09:24

Any ideas what I am doing wrong?

(If this is not the place to ask this, please let me know where I should :))

**Comment by montanaprogrammer** [comment]
I was able to get it working.

**Comment by dfinke** [comment]
how did you solve it? did the data in the CSV need to be converted from a string?

**Comment by montanaprogrammer** [comment]
Yes, I used your example in another issue thread and was able to get the
dates converted. Thank you for the work you did on this! Two thumbs UP!!
