### ISSUE TITLE
ImportExcel 7.8.7 cannot be imported, fails with loading of EPPlus.dll assembly

### ISSUE THREAD

**Issue by FH-Inway** [dfinke/ImportExcel#1597]
When importing the 7.8.7 version of ImportExcel, an error occurs:

> Import-Module : Could not load file or assembly 'file:///C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\ImportExcel\7.8.7\EPPlus.dll' or one of its 
dependencies. The system cannot find the file specified.

Tested with the following commands on Windows 11 (locally) and Windows Server 2022 (Azure DevOps pipeline running on windows-latest agent).

``` pwsh
Install-Module ImportExcel
Import-Module ImportExcel
```

Installing and importing version 7.8.6 works.

Not sure which [change since 7.8.6](https://github.com/dfinke/ImportExcel/compare/v7.8.6...master) caused that error.

**Comment by scm7ak** [comment]
go the same issue to. I've reverted back to 7.8.6 also.

**Comment by vandanchev** [comment]
We are hitting the same as we always use the latest available version.

**Comment by ildjarnisdead** [comment]
If you compare the file list of [https://www.powershellgallery.com/packages/ImportExcel/7.8.7](https://www.powershellgallery.com/packages/ImportExcel/7.8.7) with [https://www.powershellgallery.com/packages/ImportExcel/7.8.6](https://www.powershellgallery.com/packages/ImportExcel/7.8.6) you see that almost all files are missing. Something seems to have gone wrong with publishing 7.8.7 to PSGallery.

**Comment by claytonsaliba** [comment]
Do you have any ETA when this issue is going to be fixed? As this is breaking automations which requires a module and this module as a submodule.

**Comment by dfinke** [comment]
Looking at it now

**Comment by dfinke** [comment]
I bumped the version to 7.8.8. Re-published. 
The file list looks good now.

Please check.

**Comment by claytonsaliba** [comment]
Confirmed - new version has fixed this issue in our automations. Thanks!

**Comment by dfinke** [comment]
Strange, I published the 7.8.7

I go thru a process of:
- Removing ImportExcel locally 
- Installing from the PowerShell Gallery
- Do a smoke test

It all worked.

**Comment by FH-Inway** [comment]
Thanks for the quick fix, can confirm, it is working again.
