### ISSUE TITLE
Unable to create pivot table using below

### ISSUE THREAD

**Issue by nannnu** [dfinke/ImportExcel#16]
some how this is not working, i cant see to figure out why --------------------------------------------------------------------------------------------
$hotfixdetails = get-hotfix

$hotfixdetails |
Export-Excel .\mycomputer.xlsx -WorkSheetname PatchingData `
-IncludePivotTable -PivotRows installedby -PivotData 'hotfixid' `
-IncludePivotChart -ChartType PieExploded3D

---------------------------------------------------------------------------------
![error](https://cloud.githubusercontent.com/assets/12285001/7506796/e6a4baf2-f432-11e4-9377-84cb3f470231.png)
-----------

**Comment by dfinke** [comment]
Thanks for the issue. I'm guessing you want this?

![image](https://cloud.githubusercontent.com/assets/67258/7506818/4e57c32e-f433-11e4-9133-9b2fa8a1da36.png)

**Comment by nannnu** [comment]
Yes Doug :-)..i think i must have done something really stupid...

**Comment by nannnu** [comment]
how did you do that

**Comment by dfinke** [comment]
Nope, did it manually. I have not figured out how to do that through PowerShell yet. It is on the list.

The HotFixID is a `Count` and there is no way to do that in the PowerShell approach

**Comment by nannnu** [comment]
oh ok ..got you..thanks Doug for the info
