### ISSUE TITLE
Older Than

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#160]
trying to get conditionaltext to work for things older than x period.  I see the last7days but that highlight the text within the last 7 days.  I need to highlight just the stuff older than 7 days.  Also is it possible to pass in a custom date AKA (get-date).adddays(-45)

$G_Range = New-ConditionalText -ConditionalType Last7Days -range "G:G" -ConditionalTextColor blue
$N_Range = New-ConditionalText -ConditionalType Last7Days -range "N:N" -ConditionalTextColor red

$results | export-excel -ConditionalText $N_Range,$G_Range `
                 -boldtoprow -FreezeTopRow -autofilter -AutoSize  $PHYREPORTLOC

**Comment by dfinke** [comment]
Take a look at https://github.com/dfinke/ImportExcel/tree/master/Examples/FormatCellStyles, gives control to apply custom formats

**Comment by g-pearl** [comment]
$data = import-csv "C:\dates.csv"

$data | Export-Excel -now -show -CellStyleSB {
        param(
            $workSheet,
            $totalRows,
            $lastColumn
        )
        Set-CellStyle $workSheet 1 $LastColumn Solid Cyan

        2..$totalRows | ForEach-Object{
                Set-CellStyle $workSheet $_ $LastColumn Solid (Write-Output LightGreen Gray Red|Get-Random)
            }
        }

So This highlights all the rows with random color.  I want to highlight and individual cell in a column


$data (csv) is something like this.
letter,date
a,2/8/2017
b,2/6/2017
c,2/4/2017
d,2/2/2017
e,1/31/2017

I want to highlight if letter column is c or date is older than 2-5-2017.  Trying to learn - I am just missing the connection.

Thanks

**Comment by dfinke** [comment]
A bit more involved. Here are the chewy details. I think it can be generalized. There are some challenges though.

```
$data = @"
letter,date
a,2/8/2017
b,2/6/2017
c,2/4/2017
d,2/2/2017
e,1/31/2017
"@ | ConvertFrom-Csv

$data | Export-Excel -now -CellStyleSB {
    param(
        $workSheet,
        $totalRows,
        $lastColumn
)
 
    [datetime]$result  = [datetime]::MinValue
    $theDate= Get-Date "2-5-2017"

    1..$totalRows | % {
        $value = $workSheet.Cells[$_, 2].value
        
        $Test=[datetime]::TryParse($value, [ref]$result)
        if($test) {
            if($result -ge $theDate) {
                $t=$WorkSheet.Cells[$_,2]
                $t.Style.Fill.PatternType="Solid"
                $t.Style.Fill.BackgroundColor.SetColor('Gray')
            }
        }

        $value = $workSheet.Cells[$_, 1].value
        if($value -eq 'c') {
            $t=$WorkSheet.Cells[$_,1]
            $t.Style.Fill.PatternType="Solid"
            $t.Style.Fill.BackgroundColor.SetColor('Cyan')
        }
    }
}
```
