### ISSUE TITLE
Embed HTML image in a chart piviot table worksheetsheet

### ISSUE THREAD

**Issue by imessage357** [dfinke/ImportExcel#161]
Using ImportExcell  can you embed an html image in a chart piviot table worksheetsheet?

**Comment by dfinke** [comment]
Am I reading this right? You want to programmatically place an image in a chart created by a pivot table?

**Comment by imessage357** [comment]
Yes that and It would be great if we can INSERT a .jpeg or .png file to a designated cell like A1
