### ISSUE TITLE
Is there a way to freeze top rows and/or column after a bunch of Set-ExcelRange calls?

### ISSUE THREAD

**Issue by kwein123** [dfinke/ImportExcel#1614]
Pardon me if my code style is backwards from Doug's examples. In my work, I create a custom spreadsheet from various data.
After all that formatting, I would like to freeze the top two rows and first column. But if I try something like this, it errors out:
```
Set-ExcelRange -Worksheet $Worksheet -Address $Range -FreezeTopRow
```
If I try something like this at the end of my script, it doesn't error, but doesn't do anything helpful, either:
```
Export-Excel -ExcelPackage $Excel -FreezeTopRow
```

**Comment by dfinke** [comment]
@kwein123 thanks for using ImportExcel.

Not backwards at all. That would be a good guess and I didn't implement it that way, (unfortunately?)

You need to grab the the worksheet and then: `$ws.View.FreezePanes(3, 2)`
