### ISSUE TITLE
Install-Package: Package 'ImportExcel' failed to be installed because: End of Central Directory record could not be found.

### ISSUE THREAD

**Issue by Rowdy** [dfinke/ImportExcel#1617]
Unfortunately I'm not able to install this module. I always get this error message:
`Install-Package: Package 'ImportExcel' failed to be installed because: End of Central Directory record could not be found.`

I'm on the most recent version of **Powershell. 7.4.3**

I've also tried to debug it, but IMHO there is no real information in there, at least nothing that can I use to solve it...
`install-module -Name ImportExcel
DEBUG: 00:00:00.0000070 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0000389 Name: ImportExcel
DEBUG: 00:00:00.0017697 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0027912 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0043515 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0086158 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0086430 Name: ImportExcel
DEBUG: 00:00:00.0093440 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0100306 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0113276 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0151138 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0151472 Name: ImportExcel
DEBUG: 00:00:00.0158883 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0164729 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0185387 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0240050 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0240474 Name: ImportExcel
DEBUG: 00:00:00.0247909 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0253495 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0272555 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0437529 Calling SearchForPackages. Name='ImportExcel'
DEBUG: 00:00:00.0446171 PackageProvider::FindPackage with name ImportExcel
DEBUG: 00:00:00.0456920 Calling SearchForPackages After Select 1
DEBUG: 00:00:00.0472302 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:00.0475883 ProviderName: PowerShellGet
DEBUG: 00:00:00.0482891 Type: Module
DEBUG: 00:00:00.0487743 Scope: CurrentUser
DEBUG: 00:00:00.0495550 Name: ImportExcel
DEBUG: 00:00:00.0624417 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:00.0647815 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:00.0669308 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:00.0675396 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:00.0681418 OPTION: Type => Module
DEBUG: 00:00:00.0688654 OPTION: Scope => CurrentUser
DEBUG: 00:00:00.0696338 OPTION: Name => ImportExcel
DEBUG: 00:00:00.0704472 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:00.0757905 PackageProvider::FindPackage with name ImportExcel
DEBUG: 00:00:00.0792401 Calling 'NuGet'::'FindPackage' - name='ImportExcel', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:00.0796188 Iterating 'ImportExcel'.
DEBUG: 00:00:00.0808291 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:00.0882228 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:00.0889432 Source 'https://www.powershellgallery.com/api/v2' is validated.
DEBUG: 00:00:00.0896670 Calling 'NuGetRequest'::'GetPackageById', 'ImportExcel'.
DEBUG: 00:00:00.0904890 Calling 'NuGetPackageRepository'::'FindPackagesById', 'ImportExcel'.
DEBUG: 00:00:00.0910140 Calling 'NuGetPackageFeed2'::'FindPackage', 'ImportExcel'.
DEBUG: 00:00:00.0916928 Calling 'NuGetClient'::'FindPackage'.
DEBUG: 00:00:00.0930949 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=0&$top=40'.
DEBUG: 00:00:00.4720304 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=0&$top=40'.
DEBUG: 00:00:00.4778694 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=0&$top=40'.
DEBUG: 00:00:00.6139792 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=0&$top=40'.
DEBUG: 00:00:00.6229115 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=40&$top=40'.
DEBUG: 00:00:00.6230248 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=120&$top=40'.
DEBUG: 00:00:00.6231525 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=80&$top=40'.
DEBUG: 00:00:00.6261297 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=160&$top=40'.
DEBUG: 00:00:00.7782372 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=80&$top=40'.
DEBUG: 00:00:00.7823926 '30' packages received in the last request.
DEBUG: 00:00:00.7935352 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=160&$top=40'.
DEBUG: 00:00:00.7946341 '0' packages received in the last request.
DEBUG: 00:00:00.8360744 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=40&$top=40'.
DEBUG: 00:00:01.1408116 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=120&$top=40'.
DEBUG: 00:00:01.1419834 '0' packages received in the last request.
DEBUG: 00:00:01.1481649 Completed iterating for 'ImportExcel'.
DEBUG: 00:00:01.1538944 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:01.1615983 Calling New() : MethodName = 'GetInstalledPackages'
DEBUG: 00:00:01.1631275 ProviderName: PowerShellGet
DEBUG: 00:00:01.1640502 Type: Module
DEBUG: 00:00:01.1648097 Scope: CurrentUser
DEBUG: 00:00:01.1655699 Name: ImportExcel
DEBUG: 00:00:01.1663060 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.1680504 INVOKING PowerShell Fn Get-InstalledPackage with args ImportExcel, 7.8.9, ,  that has length 4
DEBUG: 00:00:01.1692649 In PowerShellGet Provider - 'Get-InstalledPackage'.
DEBUG: 00:00:01.1695625 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:01.1701730 OPTION: Type => Module
DEBUG: 00:00:01.1711915 OPTION: Scope => CurrentUser
DEBUG: 00:00:01.1716912 OPTION: Name => ImportExcel
DEBUG: 00:00:01.1723567 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.4541526 PowerShell Script 'PSModule' Function 'Get-InstalledPackage' returns null.
DEBUG: 00:00:02.4586425 Done calling powershell «Get-InstalledPackage» «PSModule»

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy
value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
DEBUG: 00:00:08.3065996 Calling New() : MethodName = 'InstallPackage'
DEBUG: 00:00:08.3074418 ProviderName: PowerShellGet
DEBUG: 00:00:08.3088203 Type: Module
DEBUG: 00:00:08.3100224 Scope: CurrentUser
DEBUG: 00:00:08.3113664 Name: ImportExcel
DEBUG: 00:00:08.3126185 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:08.3154431 INVOKING PowerShell Fn Install-Package with args NuGet|ImportExcel|7.8.9|https://www.powershellgallery.com/api/v2|Module that has length 1
DEBUG: 00:00:08.3226961 In PowerShellGet Provider - 'Install-Package'.
DEBUG: 00:00:08.3236862 In PowerShellGet Provider - 'Install-PackageUtility'.
DEBUG: 00:00:08.3251657 The FastPackageReference is 'NuGet|ImportExcel|7.8.9|https://www.powershellgallery.com/api/v2|Module'.
DEBUG: 00:00:08.3266854 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:08.3272706 OPTION: Type => Module
DEBUG: 00:00:08.3288592 OPTION: Scope => CurrentUser
DEBUG: 00:00:08.3303579 OPTION: Name => ImportExcel
DEBUG: 00:00:08.3371081 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:08.3386198 ArtifactType is Module
DEBUG: 00:00:08.5217356 Calling 'NuGet'::'InstallPackage', '$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\SW1wb3J0RXhjZWw=\Ny44Ljk=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:08.5245723 Calling 'NuGetRequest'::'GetPackageByFastpath', '$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\SW1wb3J0RXhjZWw=\Ny44Ljk=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:08.5273674 Calling 'NuGetRequest'::'ResolvePackageSource', 'https://www.powershellgallery.com/api/v2'.
DEBUG: 00:00:08.5283946 Calling 'NuGetRequest'::'FindRegisteredSource', 'https://www.powershellgallery.com/api/v2'.
DEBUG: 00:00:08.5295929 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:08.7019742 Calling 'NuGetPackageRepository'::'FindPackage', 'ImportExcel'.
DEBUG: 00:00:08.7029628 Calling 'NuGetPackageFeed2'::'FindPackage', 'ImportExcel'.
DEBUG: 00:00:08.7068838 Calling 'NuGetClient'::'FindPackage'.
DEBUG: 00:00:08.7088062 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=0&$top=40'.
DEBUG: 00:00:08.9433332 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=0&$top=40'.
DEBUG: 00:00:08.9480098 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=80&$top=40'.
DEBUG: 00:00:08.9482101 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=160&$top=40'.
DEBUG: 00:00:08.9481587 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=40&$top=40'.
DEBUG: 00:00:08.9483052 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=120&$top=40'.
DEBUG: 00:00:09.0838923 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=40&$top=40'.
DEBUG: 00:00:09.0945915 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=200&$top=40'.
DEBUG: 00:00:09.1110028 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=160&$top=40'.
DEBUG: 00:00:09.1117882 '0' packages received in the last request.
DEBUG: 00:00:09.1119266 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=120&$top=40'.
DEBUG: 00:00:09.1165281 '0' packages received in the last request.
DEBUG: 00:00:09.2252302 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=200&$top=40'.
DEBUG: 00:00:09.2262096 '0' packages received in the last request.
DEBUG: 00:00:09.5502382 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'&$skip=80&$top=40'.
DEBUG: 00:00:09.5584529 '30' packages received in the last request.
DEBUG: 00:00:09.5611547 'Package version' is '7.8.9'.
DEBUG: 00:00:09.5617540 'Request's Destination' is 'C:\Users\t.steibl.adm\AppData\Local\Temp\321169538'.
DEBUG: 00:00:09.5626460 Calling 'NuGetPackageRepository'::'InstallPackage'.
DEBUG: 00:00:09.5633258 Calling 'NuGetFilesFeed2'::'InstallPackage'.
DEBUG: 00:00:09.5646127 Calling 'NuGetFilesFeed2'::'InstallPackage', '$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\SW1wb3J0RXhjZWw=\Ny44Ljk=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdldA=='.
DEBUG: 00:00:09.5658392 Calling 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:09.5706777 Returning the call 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:09.5734963 Calling 'NuGetClient'::'InstallPackage'.
DEBUG: 00:00:19.7257332    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadDataToFileAsync(String fileName, String query, NuGetRequest request, NetworkCredential networkCredential, ProgressTracker progressTracker)
DEBUG: 00:00:37.6473696    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadDataToFileAsync(String fileName, String query, NuGetRequest request, NetworkCredential networkCredential, ProgressTracker progressTracker)
DEBUG: 00:00:38.8162416    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadDataToFileAsync(String fileName, String query, NuGetRequest request, NetworkCredential networkCredential, ProgressTracker progressTracker)
DEBUG: 00:00:38.8511199 Calling 'NuGetClient'::'InstallPackageLocal'.
DEBUG: 00:00:38.8544460 C:\Users\t.steibl.adm\AppData\Local\Temp\321169538\ImportExcel.7.8.9\ImportExcel.7.8.9.nupkg
DEBUG: 00:00:38.9156842 System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at Microsoft.PackageManagement.NuGetProvider.PackageUtility.DecompressFile(String fullZipPath)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.InstallPackageLocal(String packageName, String version, NuGetRequest request, PackageSource source, String sourceFilePath, ProgressTracker progressTracker)
Install-Package: Package 'ImportExcel' failed to be installed because: End of Central Directory record could not be found.`

Any help would be very much appreciated.
Thanks in advance.

**Comment by dfinke** [comment]
Sorry, have never seen that and at the moment no one else is reportting this issue.

**Comment by Rowdy** [comment]
Actually a long time ago a use had also some problems with "end of central"... https://github.com/dfinke/ImportExcel/issues/116

Is there any chance for a workaround to get it to work?

**Comment by dfinke** [comment]
Sorry 🤷🏼‍♂️

**Comment by Interweave1** [comment]
I am seeing the same problem on Win 11 box.

**Comment by JordiTornos** [comment]
I'm having the same problem:

PS C:\Program Files\PowerShell\7> install-module msidentitytools -Scope currentuser -Verbose
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='msidentitytools'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'msidentitytools'.
VERBOSE: Performing the operation "Install-Module" on target "Version '2.0.68' of module 'MSIdentityTools'".

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
VERBOSE: The installation scope is specified to be 'currentuser'.
VERBOSE: The specified module will be installed in 'C:\Users\JORDITORNOSPALOS\OneDrive - kyndryl\Documents\PowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'MSIdentityTools' with version '2.0.68' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='MSIdentityTools'' for ''.
VERBOSE: Package 'Microsoft.Graph.Authentication' is already installed.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'' for ''.
VERBOSE: Package 'Microsoft.Graph.Authentication' is already installed.
VERBOSE: InstallPackage' - name='ImportExcel', version='7.8.9',destination='C:\Users\JORDITORNOSPALOS\AppData\Local\Temp\124565913'
VERBOSE: DownloadPackage' - name='ImportExcel', version='7.8.9',destination='C:\Users\JORDITORNOSPALOS\AppData\Local\Temp\124565913\ImportExcel.7.8.9\ImportExcel.7.8.9.nupkg', uri='https://www.powershellgallery.com/api/v2/package/ImportExcel/7.8.9'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/ImportExcel/7.8.9'.
VERBOSE: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/ImportExcel/7.8.9' for '2' more times
VERBOSE: Download is incomplete. Downloaded '540667' out of '540667' bytes.
VERBOSE: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/ImportExcel/7.8.9' for '1' more times
VERBOSE: Download is incomplete. Downloaded '540671' out of '540671' bytes.
VERBOSE: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/ImportExcel/7.8.9' for '0' more times
VERBOSE: Download is incomplete. Downloaded '540671' out of '540671' bytes.
VERBOSE: Completed downloading 'ImportExcel'.
VERBOSE: Hash for package 'ImportExcel' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='ImportExcel', version='7.8.9',destination='C:\Users\JORDITORNOSPALOS\AppData\Local\Temp\124565913'
Install-Package: Package 'ImportExcel' failed to be installed because: End of Central Directory record could not be found.

**Comment by kennethdm** [comment]
> Sorry 🤷🏼‍♂️

lol, ok, I have the same issue, but after seeing this reply... I'll fix my scripting issue some other way

**Comment by dfinke** [comment]
This is the first time this issue has been posted, in 10 years, by 3 people.

Don't have an answer or a way to try that 🤷🏼‍♂️

Let me know what you find.
