### ISSUE TITLE
Import-Excel taking ages due to empty fields

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#162]
UPDATE: Only read my last comment. it's faster then this stuff

We're having a specific xlsx file with a sheet called 'Permissions' that takes ages to read. We're still using an older version (v 1.97) of the Import-Excel module. So I did the same test with the newest version of your module to see if it fixes the problem, but the output is different..

**The test:**

`$F = 'C:\Temp\BEL MTX-STAFF-SCM.xlsx'`
`Import-Excel $F -Sheet 'Settings' -NoHeader`

> OUTPUT (Current version):

> 
>     P1 : Status
>     P2 : SiteName
>     P3 : SiteCode
>     P4 : ComputerName
>     P5 : Path
>     P6 : GroupName
>     P7 : Action
> 
>     P1 : Enabled
>     P2 : Supply Chain Management
>     P3 : SCM
>     P4 : DEUSFHEID0005
>     P5 : E:\DEPARTMENTS\SCM
>     P6 : BEL ROL-STAFF-SCM
>     P7 : Fix
> 
>     P1 : 
>     P2 : 
>     P3 : 
>     P4 : 
>     P5 : 
>     P6 : 
>     P7 : 
> 
>     P1 : 
>     P2 : 
>     P3 : 
>     P4 : 
>     P5 : 
>     P6 : 
>     P7 : 
> 
> OUTPUT (Old version):
> 
>     P1 : Status
>     P2 : SiteName
>     P3 : SiteCode
>     P4 : ComputerName
>     P5 : Path
>     P6 : GroupName
>     P7 : Action
> 
>     P1 : Enabled
>     P2 : Supply Chain Management
>     P3 : SCM
>     P4 : DEUSFHEID0005
>     P5 : E:\DEPARTMENTS\SCM
>     P6 : BEL ROL-STAFF-SCM
>     P7 : Fix

`Import-Excel $F -Sheet 'Permissions' -NoHeader`

> OUTPUT (Current version):
>     P1  : 
>       
>       
>           Matrix SCM 
>           R: Read
>           W: Write
>     P2  : Management
>     P3  : BPM logistics
>     P4  : Master data officer
>     P5  : RMC BE OID manager
>     P6  : RMC BE Team Coordinator
>     P7  : RMC BE Order intake
>     P8  : RMC BE Dispatch
>     P9  : RMC NL OID manager
>     P10 : RMC NL Team Coordinator
>     P11 : RMC NL Order intake
>     P12 : RMC NL Dispatch
>     P13 : CEMAGG BE manager
>     P14 : CEM BE OID
>     ...
> 
>     P1  : 
>     P2  : 
>     P3  : 
>     P4  : 
>     P5  : 
>     P6  : 
>     P7  : 
>     P8  : 
>     P9  : 
>     P10 : 
>     P11 : 
>     P12 : 
>     P13 : 
>     P14 : 
>     ...
> 
> OUTPUT (Old version):
> 
>     No output, keeps on running, waiting for ages..
> 

[BEL MTX-STAFF-SCM.xlsx](https://github.com/dfinke/ImportExcel/files/756963/BEL.MTX-STAFF-SCM.xlsx)

What happens is that in the older version there is no output during a long time for the sheet 'Permissions'. In the newest module there is output but also a lot of empty rows that keep coming through. 

The behavior between both versions is different. This can be seen when only importing the 'Settings' sheet, which generates only the filled rows in the old version and in the new version it comes with the filled rows and a bunch of unfilled rows.

Is there a way to only have it output the rows that have data in them? And maybe that way speed up the reading of the 'Permissions' sheet? As it takes a really long time now to get the data, if it comes through at all....

See attachment for the file.

**Comment by DarkLite1** [comment]
It appears that the difference in output is my own doing because I added the following code to Import-Excel:

```
        Function Remove-EmptyRowsColumns {
            # Remove empty columns
            $Result | Get-Member | where MemberType -EQ NoteProperty | Select -ExpandProperty Name | % {
                if (($Result.($_) | Measure-Object).Count -eq 0) {
                    Write-Debug "Remove empty column '$_'"
                    $Result = $Result | Select -Property * -ExcludeProperty $_
                }
            }

            if ($NoHeader) {
                # Rename propterties
                $Props = $Result | Get-Member | where MemberType -EQ NoteProperty
                $i = 1
                foreach ($P in ($Props.Name | Sort-Object -Property {[INT]($_.replace('P',  ''))})) {
                    if ($P -ne "P$i") {
                        Write-Debug "Change prop '$P' to 'P$i'"
                        $Result | % {
                            $_ | Add-Member "P$i" -NotePropertyValue $_.$P
                            $_.psobject.properties.remove($P)
                        }
                    }
                    $i++
                }
            }

            # Remove empty rows
            $Result | where {$_.PSObject.Properties.Value -ne $null}
        }
    }
```

Let's see if I can fix my own problem by using the new EPPLUS.dll and your new module.

**Comment by DarkLite1** [comment]
It would have been better if I filed this as a feature request to remove empty columns and empty rows from the output. I'm sure your code would be ten times faster then by clumsy solution.

**Comment by DarkLite1** [comment]
I fixed it by adding a switch to 'Import-Excel' called '$OnlyData'. I wanted to upload this to GitHub but I'm not so experienced in using it. Feel free to add if you like. The functionality can be described as: Import only data fields and disregard all formatting and other stuff.

            if ($OnlyData) {
                $CellsWithValues = $worksheet.Cells | where Value

                $i = 0
                $ColumnReference = $CellsWithValues | Select-Object -ExpandProperty End | Group-Object Column | Sort-Object Name | 
                    Select-Object @{L='Column';E={$_.Name}}, @{L='NewColumn';E={$Script:i++; $Script:i}}
                
                $CellsWithValues | Select-Object -ExpandProperty End | Group-Object Row | ForEach-Object {    
                    $RowNr = $_.Name

                    $newRow = [Ordered]@{}
                    
                    foreach ($C in $ColumnReference) {
                        $newRow."P$($C.NewColumn)" = $worksheet.Cells[($RowNr),($C.Column)].Value
                    }

                    [PSCustomObject]$newRow
                }
            }

**Comment by dfinke** [comment]
Thanks for working that out. Want to do a PR for that?  :)

**Comment by DarkLite1** [comment]
Done! Took me a while to figure it out but I finally pushed some PR's to your branch. I think they will serve everyone, we have them running in production for over a couple of months now. Feel free to test it, in case I missed something.

**Comment by DarkLite1** [comment]
Fixed in the meantime.
