### ISSUE TITLE
Import-Excel with -HeaderName shifts cells to the left

### ISSUE THREAD

**Issue by gh-ttgo** [dfinke/ImportExcel#1630]
I have the following Excel file with two sheets. Sheet1 contains the following data (note the column "Sheet" is in fact a literal column for orientation...)
```
import-excel test.xlsx
ColA ColB Sheet ColC ColD
---- ---- ----- ---- ----
   1 X        1 Y    Z   
   2 A        1      C   
   3 G        1      C   
   4 G        1 A    H   
   5 B        1      A   
```

Sheet2 contains the following data:
```
import-excel -WorksheetName Sheet2 test.xlsx
ColA ColB Sheet ColC ColD
---- ---- ----- ---- ----
   1 X        2      Z   
   2 A        2      C   
   3 G        2      C   
   4 G        2      H   
   5 B        2      A   
```

As you can see, the column "ColC" is completly empty in Sheet2, wheras in Sheet1, some cells contain data.

The output given by "plain" `Import-Excel` is correct.

However, when I use `Import-Excel` together with `-HeaderName`, the columns in sheet two following the empty column, are shifted to the left.
```
$headerValues = @("CollA","CollB","SheetName","CollC","CollD")
Import-Excel -Path "test.xlsx" -WorksheetName "Sheet2" -HeaderName $headerValues -DataOnly | ft

CollA CollB SheetName CollC CollD
----- ----- --------- ----- -----
    1 X             2 Z          
    2 A             2 C          
    3 G             2 C          
    4 G             2 H          
    5 B             2 A          
``` 

The expected output would be:
``` 
CollA CollB SheetName CollC CollD
----- ----- --------- ----- -----
    1 X             2       Z          
    2 A             2       C          
    3 G             2       C          
    4 G             2       H          
    5 B             2       A          
``` 

For Sheet1, the output is correct:
```
$headerValues = @("CollA","CollB","SheetName","CollC","CollD")
Import-Excel -Path "test.xlsx" -WorksheetName "Sheet1" -HeaderName $headerValues -DataOnly | ft

CollA CollB SheetName CollC CollD
----- ----- --------- ----- -----
    1 X             1 Y     Z    
    2 A             1       C    
    3 G             1       C    
    4 G             1 A     H    
    5 B             1       A    
```

**Comment by dfinke** [comment]
pls post the xlsx and the script you use to import the data. what version of the module are you using?

**Comment by gh-ttgo** [comment]
Version 7.8.9
[test.xlsx](https://github.com/user-attachments/files/16839974/test.xlsx)

I am using exactly what I posted above to import the data.

**Comment by scriptingstudio** [comment]
Could reproduce. `-DataOnly` parameter produces the issue.
The problem is that how to determine "data". Line 165 tells that `null` is not data, but such cell is within the table.
Doug, correct me if I am wrong.

**Comment by scriptingstudio** [comment]
if line 168 is used without filter, just `$columns = $StartColumn..$EndColumn`, it will work fine

**Comment by dfinke** [comment]
@gh-ttgo 

Yup. Not going to look to fix that at the moment.

### Workaround

```powershell
$headerValues = @("CollA", "CollB", "SheetName", "CollC", "CollD")

$(
    Import-Excel D:\Users\finke\Downloads\test.xlsx -WorksheetName 'Sheet1' -HeaderName $headerValues -StartRow 2
    Import-Excel D:\Users\finke\Downloads\test.xlsx -WorksheetName 'Sheet2' -HeaderName $headerValues -StartRow 2
) | Format-Table
```

**Comment by scriptingstudio** [comment]
`-dataonly` is contradictory parameter. It ignores empty row/column but leaves the header intact. `-HeaderName` and `-DataOnly` should be used carefully together.
The issue demonstrated such "dangerous" use case.
