### ISSUE TITLE
Rows.Count returns 0 when the sheet has only 1 data row

### ISSUE THREAD

**Issue by fabienarnaud** [dfinke/ImportExcel#1643]
Hi,

I have an Excel with multiple sheets, some of which may have only 1 header row and 1 data row.
In such cases, the Import-Excel "Rows.Count" function returns 0:

![image](https://github.com/user-attachments/assets/d3b87dc3-fc5f-414d-a8c4-4e0a686f5105)

although the data row is correctly imported and printable:

The count is correct as soon as more than 2+ data rows are present.
I use version 7.8.9

Any idea why that is?

**Comment by fabienarnaud** [comment]
After some research, a colleague of mine found a thread indicating a similar problem with the Import-CSV module.
We changed our code to this:

```
$Excel = Import-Excel -Path $FilePath -Sheet $ControlSheet
$count = @($Excel).Count
```
It now returns the correct count even when there is only 1 row:

![image](https://github.com/user-attachments/assets/86c80681-dbb8-4851-ae54-a1ee5e07c928)

**Comment by dfinke** [comment]
Thanks for trying the module and reporting. That is not a bug - It is the way PowerShell works.

**Comment by fabienarnaud** [comment]
I don't know Powershell that much obviously so didn't realize that this is expected behavior. Thanks anyway for the answer and thanks for the module! It's very useful

**Comment by dfinke** [comment]
Yes, all programming languages have non-intuitive constructs. Glad it helped.
