### ISSUE TITLE
Pester.png URL is flagged as suspicious in Trend Micro

### ISSUE THREAD

**Issue by evenmartinsen** [dfinke/ImportExcel#1647]
Hi!

The URL that is referenced in ImportExcel.psd1 line 153 is flagged in Trend Micro, even though it is formatted out.
The publisher of Pester have issued a new URL for this png, so this should be used instead of the old one which is now referencing to their old domain which has lapsed and been bought by someone else.

https://github.com/pester/Pester/issues/1455

The new url is: https://raw.githubusercontent.com/pester/Pester/main/images/pester.PNG

**Comment by evenmartinsen** [comment]
submitted pull-request ( #1648 ) quick fix.

**Comment by dfinke** [comment]
Thank you @evenmartinsen. Merged and published.
