### ISSUE TITLE
Export-Excel: Numeric values not correct

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#168]
Consider the following code:

```
if (!($TempFolder = $env:TEMP + '\TestFolder')) {
    New-Item -Path $TempFolder -ItemType Directory
}

$F = New-Object System.IO.FileStream ($TempFolder + '\File1.txt'), Create, ReadWrite
$F.SetLength(763905024)
$F.Close()

$F = New-Object System.IO.FileStream ($TempFolder + '\File2.txt'), Create, ReadWrite
$F.SetLength(1631405056)
$F.Close()

$F = New-Object System.IO.FileStream ($TempFolder + '\File3.txt'), Create, ReadWrite
$F.SetLength(271360)
$F.Close()

$F = New-Object System.IO.FileStream ($TempFolder + '\File4.txt'), Create, ReadWrite
$F.SetLength(417006592)
$F.Close()

$ExcelFile = $env:TEMP + '\Excel.xlsx'
if (Test-Path -Path $ExcelFile) {
    Remove-Item -Path $ExcelFile -Force
}

Get-ChildItem -Path $TempFolder | 
    Select-Object Name, Length, @{Name="Mb";Expression={'{0:N2}' -f ($_.Length/1Mb)}} |
        Export-Excel $ExcelFile -Show
```

This results in:
![image](https://cloud.githubusercontent.com/assets/10828570/23161503/b1656406-f82a-11e6-94d4-4897f0443a22.png)

As you can see, the values behind the comma are discarded. 
Example: 0,26 becomes 26 in the Excel file.

Also, some cells are stored as text rather then number. see C3.

**Comment by DarkLite1** [comment]
I think the problem is located in this piece of code:
```
if ($cellValue -is [string] -and $cellValue.StartsWith('=')) {
    $targetCell.Formula = $cellValue
} else {
    $r=$null
    if ([Double]::TryParse([string]$cellValue,[System.Globalization.NumberStyles]::Any,[System.Globalization.NumberFormatInfo]::InvariantInfo, [ref]$r)) {
        $targetCell.Value = $r
        $targetCell.Style.Numberformat.Format=$Numberformat
        Write-Verbose "Add cell value '$r' in Numberformat '$Numberformat'"
    } else {
        $targetCell.Value = $cellValue
        Write-Verbose "Add cell value '$cellValue'"
    }
}
```

It says:

> VERBOSE: Add cell value '1.555,83'

Which is not handled as a number format although it is.

**Comment by DarkLite1** [comment]
In issue #64 we did some tests which fixed some issues we had. However, when I do the same test for the value '1.555,83' it doesn't recognize it as a number but it does for value '0,26':

```
echo "0,26" "1.555,83" "1.2" "1" "a" "-31" "+32 44" '+32 4 4444 444' | % { 
    $result=[Double]::TryParse(
        [Convert]::ToString($_), 
        [System.Globalization.NumberStyles]::Any,
        [System.Globalization.NumberFormatInfo]::InvariantInfo, 
        [ref]$null
    )

    [pscustomobject][ordered]@{
        Value=$_
        Result=$result
    }
}
```

**Comment by DarkLite1** [comment]
Maybe we can change:

```
if ($cellValue -is [string] -and $cellValue.StartsWith('=')) {
    $targetCell.Formula = $cellValue
} else {
    $r=$null
    if ([Double]::TryParse([string]$cellValue,[System.Globalization.NumberStyles]::Any,[System.Globalization.NumberFormatInfo]::InvariantInfo, [ref]$r)) {
        $targetCell.Value = $r
        $targetCell.Style.Numberformat.Format=$Numberformat
        Write-Verbose "Add cell value '$r' in Numberformat '$Numberformat'"
    } else {
        $targetCell.Value = $cellValue
        Write-Verbose "Add cell value '$cellValue'"
    }
}
```

To:

```
if ($cellValue -is [string] -and $cellValue.StartsWith('=')) {
    $targetCell.Formula = $cellValue
} else {
    $r=$null
    if ([Double]::TryParse([string]$cellValue,[System.Globalization.NumberStyles]::Any,[System.Globalization.NumberFormatInfo]::InvariantInfo, [ref]$r)) {
        $targetCell.Value = **$cellValue**
        $targetCell.Style.Numberformat.Format=$Numberformat
        Write-Verbose "Add cell value '$r' in Numberformat '$Numberformat'"
    } else {
        $targetCell.Value = $cellValue
        Write-Verbose "Add cell value '$cellValue'"
    }
}
```

**Comment by dfinke** [comment]
I'll review

**Comment by DarkLite1** [comment]
Hi Doug, that is correct, the leading zero would be stripped because it means nothing and is handled as a number in Excel. This is actually default behavior of Excel, you can see this when you open a new Excel worksheet and type in a cell for examle `015` it will result in `15`, because it's treated as a number. 

So, in short. to have a US ZIP code like `07670` being shown with a leading zeros, these are the options:
- Handle it as a String instead of a Numeric value
(I don't know if you can do this with your module already)
- Handle it as a Numeric value (as it is now) and format in Excel with leading zero's
(Maybe this type of formatting is supported in your module? Or can be?)

In any case, what we see is default Excel behavior. I'm open for other suggestions, but I don't think `CurrentInfo` is wrong. Please let me know what you think.

**Comment by dfinke** [comment]
Thanks!

I need to do more investigation. This looks to be on the right track. I'll get back to you and we can discuss further.

**Comment by Apanoiu** [comment]
Same issue here, I need to make a report based on db data, and one column contains numbers with leading zeros which needs to be stored as text. 
I have tried to add a "'" prefix but excel is displaying it. 
I am looking forward for this feature to be implemented.

**Comment by DarkLite1** [comment]
Took me more than a week to reorganize the code, add some better verbose and stuff. Anyhow, it's now possible to have numbers the way you want them by using '-NoNumberConversion *' as added in PS #187 . Waiting for approval/review from the boss to make sure I didn't miss anything ;)

**Comment by pezmannen** [comment]
So, I'm having problems with numbers showing up like this: 1,49545E+14 instead of this: 149544511912832. Will this latest fix resolve this?

**Comment by DarkLite1** [comment]
If the pull request gets accepted then you can use the parameter '-NoNumberConversion' to send your data to Excel. By using this parameter you bypass the conversion from a value to a number, that is built in to the function.

So in theory, if you do:
`Export-Excel -Path File.xlsx -NoNumberConversion *`

The it will export all data 'as is' and it doesn't convert anything. So this should avoid Excel from truncating the number from '149544511912832' to '1,49545E+14', because it's passed as a string and not as a number and is shown as plain text.

**Comment by dfinke** [comment]
@pezmannen These changes are going to take a while to test. Let me know if you want try out an early version? Plus, if you run into issues, you can report back.

**Comment by pezmannen** [comment]
@dfinke I'd love to test, and I'll report any issues. Thanks!

**Comment by lw-schick** [comment]
I have the same problem with numbers - 0,04 is converted to 4.00.

Is there any plan to merge this? I would like to install a new version instead of using the forked version DarkLite1....

**Comment by dfinke** [comment]
It's been merged and published to the PowerShell gallery
