### ISSUE TITLE
Cannot import-module in PowerShell 2.0

### ISSUE THREAD

**Issue by stukey** [dfinke/ImportExcel#17]
I was able to import the module from PowerShell 2.0 previously (once you made the changes in 8ca024999fbc426f6285e1dd150b41fc40f3230c to Add =$true to Parameters to support downlevel versions). However now with the latest commit of the module I am no longer able to import the module under PowerShell 2.0. Here's the error:

>Import-Module : The 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psd1' module cannot be imported because its manifest contains one or more members that are not valid. The valid manifest members are ('ModuleToProcess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVersion', 'PowerShellHostName', 'PowerShell
HostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'RequiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'FunctionsToExport', 'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the members that are not valid ('RootModule'), then try to import the module again.
At line:1 char:14
+ Import-Module <<<<  "ImportExcel"
    + CategoryInfo          : InvalidData: (C:\Windows\syst...mportExcel.psd1:String) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_InvalidManifestMember,Microsoft.PowerShell.Commands.ImportModuleCommand

This is occurring on a Windows 2008 R2 SP1 server running PowerShell 2.0. I can import and use the module without issue on another server which is running PowerShell 3.0 but unfortunately we can't upgrade all of our servers to 3.0 at the current time. Any chance you can support 2.0?

**Comment by dfinke** [comment]
Thanks for posting the issue. The only recommendation I have is to rename (or delete) the psd1. The psd1 one is needed so this can be published to the PowerShell Gallery. Let me know if you have issues,

**Comment by stukey** [comment]
Thanks. Removing the PSD1 resolved that issue. But now there's a new issue in the module:

> The "=" operator is missing after a named argument.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:300 char:30
+         [Parameter(Mandatory) <<<< ]
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEqualsInNamedArgument
Import-Module : The specified module 'ImportExcel' was not loaded because no valid module file was found in any module directory.
At line:1 char:14
+ Import-Module <<<<  "ImportExcel"
    + CategoryInfo          : ResourceUnavailable: (ImportExcel:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

I think this is related to the previous reported issue related to adding =$true to Parameters to support downlevel versions of PowerShell. In this case it appears there are two mandatory parameters in the Export-MultipleExcelSheets function (lines 300 and 302) which don't contain **Mandatory = $true**. Once I added $true to the two Param statements the module loaded. 

However the module doesn't function correctly under PowerShell 2.0. I tried the following:

`Get-item *.ps1 | Export-Excel -Path test.xlsx `

>Property 'Value' cannot be found on this object; make sure it exists and is settable.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:172 char:47
+                 $ws.Cells[$Row, $ColumnIndex]. <<<< Value = $name
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
Property 'Value' cannot be found on this object; make sure it exists and is settable.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:183 char:25
+             $targetCell. <<<< Value = $TargetData.$Name
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
Property 'Value' cannot be found on this object; make sure it exists and is settable.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:172 char:47
+                 $ws.Cells[$Row, $ColumnIndex]. <<<< Value = $name
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
Property 'Value' cannot be found on this object; make sure it exists and is settable.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:183 char:25
+             $targetCell. <<<< Value = $TargetData.$Name
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

I did mention this issue on your blog comments but thought I'd put it here on Github incase there's any chance you can support PowerShell 2.0!

**Comment by dfinke** [comment]
Thanks for trying that. I'll take a look. I'm probably not going to solve this for v2. That technique is used in a few places and makes maintaining the scripts far easier. I know it's a challenge to migrate to new versions. There are many, many advantages (as you probably know) in the latest releases.
