### ISSUE TITLE
Export-Excel slow when run in an Azure Automation runbook

### ISSUE THREAD

**Issue by janegilring** [dfinke/ImportExcel#170]
When  I run the following in a local PowerShell session (Windows 10, PS 5.1), it executes within seconds:
_$AllUserLicenses = Get-MsolUser -All -PipelineVariable MsolUser | Where-Object isLicensed 
$AllUserLicenses | Export-Excel -Path $XlsxPath -WorkSheetname Licenses -AutoSize -TableName Licenses_

When the same code is running inside an Azure Automation runbook which is executed on a Windows Server 2016 Hybrid Runbook Worker, the runbook uses 21 minutes from start to finish and Export-Excel seems to be the slowness based on Write-Output commands inside the runbook.

Any thoughts on why? And how to troubleshoot?

**Comment by dfinke** [comment]
Wow, off the top of my head, I'm not sure. The Hybrid Worker? Are you running the Get-MsolUser in Azure and saving to an on premise file?

**Comment by janegilring** [comment]
Correct. Does Export-Excel write to the verbose stream by default? It might be that the Hybrid Runbook Worker is streaming data back to Azure, including the verbose stream. I`ll try with -Verbose:$false to see if it makes a difference.

**Comment by dfinke** [comment]
Wow. Glad you found it. Good to know. Sounds like a good blog post. :)
