### ISSUE TITLE
Feature request: Piviot Table Filters

### ISSUE THREAD

**Issue by Jackson-Miller** [dfinke/ImportExcel#173]
When using the -IncluePibiotTable parameter it would be nice to be able to specify a parameter to configure the filter of the pivot table.

**Comment by LoTheGeek** [comment]
Hi,
I'm interested too by this option. 
It could be nice to be able to define filter values.

**Comment by scottone** [comment]
$null = $CompanyPivotTable.**PageFields**.Add($CompanyPivotTable.Fields["Environment"])
$null = $CompanyPivotTable.**PageFields**.Add($CompanyPivotTable.Fields["Device Status"])
**This only works if:**
$wsPivot.Cells['A1']
is replaced with 
$wsPivot.Cells['A3']
in Export-Excel.ps1

**Comment by dfinke** [comment]
@scottone Thanks for the code snippet. I'll take a look.

**Comment by dfinke** [comment]
OK, added a parameter `PivotFilter `. The `A3` was a great clue!

Needs more testing. Please provide feedback, name of param etc.


```powershell
$data =@"
Region,Area,Product,Units,Cost
North,A1,Apple,100,.5
South,A2,Pear,120,1.5
East,A3,Grape,140,2.5
West,A4,Banana,160,3.5
North,A1,Pear,120,1.5
North,A1,Grape,140,2.5
"@ | ConvertFrom-Csv

$data | 
    Export-Excel $xlFile `
        -IncludePivotTable `
        -PivotRows Product `
        -PivotData @{"Units"="sum"} `
        -PivotFilter Region, Area `
        -Show 
```


![image](https://user-images.githubusercontent.com/67258/38038193-77809ea2-3278-11e8-917b-cdc215707dce.png)

**Comment by scottone** [comment]
Thanks for quick response!  That looks good.
I think PivotFilter is fine for the parameter name also.
