### ISSUE TITLE
To update powershell output to a specific column of a exisiting excel

### ISSUE THREAD

**Issue by Murali25d** [dfinke/ImportExcel#175]
Hi,

I already got an excel with data filled in all columns except Column "B"
I have to paste the Get-Childitem output of the below command to Column B of the excel and enable autofill based on Column B
I used this cmdlet to output only the directory names of a folder with sort case sensitive
Get-childItem | Sort-Object -casesensitive | ?{$_.PSIsContainer} | Format-Table -Property Name

Can someone please help me in this

**Comment by dfinke** [comment]
Currently there is no support to insert data into a a specific column. The data needs to be in the format and order you need prior to using `Export-Excel`
