### ISSUE TITLE
Export-Excel will never throw "$WorkSheetname already exists." 

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#179]
The variable $AlreadyExists is not set:
so the Export-Excel function 
will never
throw "$WorkSheetname already exists." 

       Catch {
            if ($AlreadyExists) {
                throw "$WorkSheetname already exists."
            } else {
                throw $Error[0].Exception.Message
            }
        }

**Comment by dfinke** [comment]
Hmm, wonder if it's even needed
