### ISSUE TITLE
Additional features for Excel reporting - freeze top row/ data filter

### ISSUE THREAD

**Issue by stukey** [dfinke/ImportExcel#18]
Your module will be really useful for streamlining and improving our reporting. Being able to export data from different cmdlets to different worksheets within the same workbook is amazing. It would be really great if we could make a few other changes to the way the data is displayed to make the reports easier to use/read. For example is there any way that the following features could be implemented in the module:

Ability to set the **View \ Freeze Panes \ Freeze Top Row** function?
Ability to **bold** the text of the first row on each worksheet (the column headers)?
Ability to enable **Data \ Filter** to automatically enabling filtering in each worksheet?

Many thanks,

Stuart

**Comment by dfinke** [comment]
Great ideas. I'll look into this. Thank you.

**Comment by dfinke** [comment]
Implemented

**Comment by stukey** [comment]
Wow thanks Doug. These new additions are fantastic! Thanks for adding them so quickly. Just a quick thought. Shouldn't **-BoldFirstRow** be renamed to **-BoldTopRow** to make it consistent with **-FreezeTopRow**?

**Comment by dfinke** [comment]
Thanks @stukey good catch on consistency. Hey, just a suggestion here, you could fork the repo, make the and try the code and then do a pull request. Great skill building exercise.

Thanks again for the great suggestions.
