### ISSUE TITLE
Using -Title switch results in -AutoFilter and -BoldTopRow switches not applying properly to the actual column header row which is now on line 2.

### ISSUE THREAD

**Issue by jeremytbrun** [dfinke/ImportExcel#182]
`$groupedUsers | Select-Object Name, Count | Export-Excel "<pathToXlsx>" -WorkSheetname "Agency Overview" -Title "Agency Overview" -TitleBold -AutoSize -AutoFilter -BoldTopRow`

![image](https://cloud.githubusercontent.com/assets/28311946/25632445/9cb610ac-2f41-11e7-8107-56044083e7e0.png)

**Comment by dfinke** [comment]
If you want a quick fix, add the below after this line.

https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L272

```powershell
    if($Title) {
        $startAddress="A2"
    }
```

This is not a complete fix and I'll need to do tests and it will be a bit before I can publish and update.

**Comment by y-master** [comment]
I have the same issue with TableStyle, the table should start on line 2.
![image](https://user-images.githubusercontent.com/23241737/27726792-1b9aa46a-5d7c-11e7-93bf-37440d1bde55.png)
