### ISSUE TITLE
Saving multiple worksheets to the same workbook fails with "Line 465: Failed exporting the worksheet: Exception calling "Save" with "0" argument(s):"

### ISSUE THREAD

**Issue by mcgoo49** [dfinke/ImportExcel#185]
I am attempting to write multiple worksheets into the same workbook (first export-excel will create workbook and corresponding exports will create new worksheets in the same workbook).  Exporting to the new workbook is very inconsistent.  For some worksheets it works, then it fails on others.  It is not specific to the data being written, since one run the data will write, the next it won't.  

Does the Export place a lock on the file that may not be releasing it fast enough to write the next worksheet?  In doing some searching, it seems PSExcel may have a known issue, reported [here](https://github.com/RamblingCookieMonster/PSExcel/issues/18).

I would appreciate any guidance/input.  I am attempting to move away from using COM objects for Excel, and hoping I don't have to go back!

**Comment by dfinke** [comment]
Yeah, PSExcel is a fork of my project. The underlying code that creates the xlsx is done by EPPlus.

Can you post the lines code that export to excel/

**Comment by lw-schick** [comment]
Seems to be duplicated. Take a look at #180

**Comment by mcgoo49** [comment]
Sorry for the slow reply, I was out on vacation (rare occasion).

I am importing multiple excel files, and copying the worksheets into a new one.  If a specific worksheet doesn't exist yet, it adds a new one.  If it does exist, I have it start at row # (# of records +2 to account for header).  It is failing when trying to create a NEW worksheet:

$inWSContent = Import-Excel -Path $inFile -WorkSheetname $inWSName
$inWSContent | Export-Excel -Path $outFile -WorkSheetname $inWSName

At first I thought it was 1) If a particular column was empty, or had empty cells 2) If a worksheet had a header, but no records/rows.  It is sporadic though, and sometimes the particular worksheet would fail, and sometimes it would Export properly.  

I did a try/catch when it failed, and then tried a "NoClobber" option on error, and it works ~99% of the time after that.  I had also tried waiting 5-10 seconds and retrying the same commandabove, but that did NOT work.  Is it possible that it was the prior worksheet, and maybe there was a lock on the Workbook?  

Thanks, and please let me know if I can provide any information
