### ISSUE TITLE
Exporting to an existing Worksheet with a large amount of records takes a long time and uses a lot of memory 

### ISSUE THREAD

**Issue by mcgoo49** [dfinke/ImportExcel#186]
This may be more ignorance on my part, but I am trying to combine a number of smaller individual workbooks into one workbook with multiple worksheets.  There may be 100k rows or more in the existing Worksheet, and when I export the new rows in, the larger the destination worksheet, the longer it is taking.  I ran a test and had it capture the elapsed time, and compared it to the same operation using Excel COM object.  I also included the associated code from each type.

If there is a better way that I can be doing this?  I don't know if there is a "UsedRange" style option similar to Excel Com that would accomplish the same thing as my code below [-StartRow ((Import-Excel -Path $outFile -WorkSheetname $inWSName).Count + 2)]

Any help would be appreciated.  I'm hoping I can stick with Import-Excel/Export-Excel as the syntax and code is so much simpler.  Unfortunately, the time it takes using my current code makes the process take over 24 hours to run.  

# of rows imported: 23k
# of rows in existing destination spreadsheet: 246k
Using Export-Excel
     Elapsed: 90 seconds
     Memory usage: ~500 MB
Using Excel COM
     Elapsed: 16 seconds
     Memory usage: ~100 MB

##Code using Export-Excel
Import-Excel -Path $inFile -WorkSheetname $inWSName | Export-Excel -Path $outFile -WorkSheetname $outWSName -StartRow ((Import-Excel -Path $outFile -WorkSheetname $inWSName).Count + 2) -NoHeader

##code using Excel COM
$Excel = New-Object -ComObject Excel.Application
$Excel.Visible = $True
$Excel.DisplayAlerts = $False
$sourceWB = $Excel.Workbooks.Open($inFile, $true, $true)
$sourceWS = $sourceWB.Worksheets.Item($wsIn)
$sourceRange = $sourceWS.UsedRange

$destWB = $Excel.Workbooks.Open($outFile, $true, $false)
$destWS = $destWB.Worksheets.Item($wsOut)
$destRows = $destWS.UsedRange.Rows.Count
$destRange = $destWS.Range("A$($destRows + 1)")

$sourceRange.Copy()
[void]$destRange.PasteSpecial([Microsoft.Office.Interop.Excel.XlPasteType]::xlPasteValues)
$sourceWB.Close($false)
$destWB.SaveAs($outFile, 51)
$excel.quit()

**Comment by dfinke** [comment]
Yes, Export-Excel will be slower. There is logic that happens for each cell that is added so the appropriate `type` of data is formatted for that cell, Date Time, Integer. So the COM approach is faster.

**Comment by DarkLite1** [comment]
I have to agree with @dfinke , it's not possible to speed up the process as there is indeed a lot of logic present on how to export a specific cell depending on its type. I'm afraid this one has to be closed as unsolved.
