### ISSUE TITLE
Export-Excel IPAddress string

### ISSUE THREAD

**Issue by pejub** [dfinke/ImportExcel#188]
Hi, 

I have a custom object with a number of noteproperties, ints, bools and strings
One string contains an IPV4 address, and when exporting that it gets converted to a number, what basically is happens is that the dots are removed.

It turns out that the (Get-Culture).NumberFormat.CurrencyGroupSeparator is considered because when I set that equal to '' that field is exported as a string.

/Per

**Comment by dalmat89** [comment]
I have the same issue, is there a sort of workaround to resolve it ? I'm pretty new on Powershell  :)

**Comment by dalmat89** [comment]
I had the same issue, but using the parameter NoNumberConversion seems to work fine.

Below my examples :

 $objServers | Export-Excel -path $file_xls -AutoSize -NoNumberConversion 'IP Address'

**Comment by pejub** [comment]
Hi,

Cool, haven't seen that switch, thanks 👍 

I used a bit more complicated method that does not require the need to know field names.

$OldCurrencyGroupSeparator = (Get-Culture).NumberFormat.CurrencyGroupSeparator
(Get-Culture).NumberFormat.CurrencyGroupSeparator = ''
$ServerList | Export-Excel -Path "Inventory-$(Get-Date -Format "yyyyMMdd-HHmm").xlsx"
(Get-Culture).NumberFormat.CurrencyGroupSeparator = $OldCurrencyGroupSeparator

/Per

**Comment by DarkLite1** [comment]
The proper way to do it is indeed what @dalmat89  suggested:

`$objServers | Export-Excel -path $file_xls -AutoSize -NoNumberConversion 'IP Address'`

This question can be closed then I believe.
