### ISSUE TITLE
Who wants to try the new version?

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#189]
@DarkLite1 has done a great job refactoring, adding features and more. Plus, @DarkLite1 is running it in production and no issues so far.

It be great if more folks would take the new module and try it out and report back issues. Let me know you're interested, and I'll get you the new bits.

Thanks
Doug

@0xbrock
@0xfeeddeadbeef
@1RedOne
@3gstudent
@741zxc606
@aaronscientiae
@ab310
@adriandeller
@adumont
@agentidea
@agrezende
@aireyna
@AjayKMehta
@ajvol
@albertosesena
@alexinslc
@alinardus
@alulsh
@amirtal
@Anderath
@andreajeka
@AndrewGaspar
@andybaran
@andyrobbins
@AnneTheAgile
@anub82
@arothstein
@arthurfm
@ashdar
@atse
@aurbjo
@avinashkoyyana
@awais9981
@aznthanh23
@bahhhhh
@BClev
@bekoons
@belowyn
@BenRussert
@beppler
@Bigj8705
@billpieper
@blakejakopovic
@bluekeys
@Blueseth
@brianbolger
@brianbunke
@briantist
@Brizio
@Bubbassauro
@bundyfx
@Caelier
@calebbaker
@camilohe
@cdhunt
@cdituri
@chadc
@chantisnake
@christophekumor
@chrizmo
@chuckarama
@ciberesponce
@cincypiper
@cjstaples
@Clarkey
@clintsimmons
@cnavarro86
@cobaltjacket
@cocana
@Cpillot
@craibuc
@craigforr
@craiglandis
@crexin
@csdibiase
@csmiddy
@csuciava
@ctolkien
@curilla
@cuzza0
@cwegener
@DamianReeves
@danaickin
@danielbmeireles
@DaniSQL
@dantheother
@davidphayanouvong
@daviwil
@ddneves
@Decicus
@defaultmagi
@DeliriumNocturnum
@DennisTheBald
@devblackops
@DewArmy
@DextraKelvin
@DigitalCog
@DillyBabu
@dmissp
@dodgeman9
@donoho
@doogieconsulting
@drbothen
@drizer
@drmohundro
@duanshuaimin
@duncanawerbuck
@dustinsharp
@dvjz
@edepree
@edm00se
@eFiggy
@egomesbrandao
@ellingor
@elpablos
@Endraal
@energetic-it
@enu235
@essaydave
@eweilnau
@exactmike
@EZarnosky
@fabiendibot
@fattung79
@FGSHadden
@Fleisch
@Flueworks
@fmichaleczek
@fnolasco
@forbesmyester
@forensicsguy20012004
@foresightyj
@ForNeVeR
@fr0zenone
@frank3nst3in
@frizb
@fryguy451
@fusconed
@gangstanthony
@geek-ragazza
@GeeksRock
@gerane
@Gianlu
@glaisne
@GlennFaustino
@GongJunior
@gordonbondon
@Gorrock
@greekit
@greising
@grephappiness
@Grim-GH
@guidooliveira
@guygregory
@heidarj
@Hoorge
@hpmmatuska
@iamww
@Ichigo49
@Iczer1
@iiunknown
@ikehoff
@ionut-maxim
@irwins
@isuwill
@jacobboykin
@jakebarry
@jalliot
@James-Maginn
@jamiewitter
@janegilring
@jangins101
@Jay-Armstrong
@Jaykul
@jdkang
@JDogHerman
@JefTek
@jfrmilner
@jgdaqs
@jgreenephd
@jj1985
@jkirch01
@jkorell
@jlevy1126
@jmbarnes1987
@JoePlant
@johndonnelly
@jonathancounihan
@jonmarksearle
@josheinstein
@joshuamhanley
@jpomfret
@jpvantuyl
@jrthoms
@jsk01
@jtomasz
@jtuttas
@jupe76
@JustinGrote
@jvaldezjr1
@jvbond
@jzrobbie
@kaiPushOrigin
@katie05
@kbkaehn
@kelvinhk3345
@kenrachynski
@kensel
@kfinny
@khoaho
@Kingu75
@Kittzus
@koogle
@korzynski
@kspringer
@ktaranov
@kukisama
@KurtDeGreeff
@lanwench
@LawrenceHwang
@lazywinadmin
@lboening
@leebivip
@loi219
@lordhelmut
@lucdekens
@LukeBG
@lwalthert
@ma
@magicedy
@marcher233
@marclile
@martin9700
@MathieuBuisson
@matthewtckr
@mattmhersh
@mattparkes
@mckibbinusa
@megamorf
@mgohmann
@micmaher
@mikefrobbins
@mikejanus
@MikeShepard
@misterGF
@mitrov
@mjohnste
@mkol5222
@mmirchev
@modulexcite
@molotovpenguin
@mortenya
@mouse-man
@mryanmurphy
@msenturk
@mvandriessen
@mwmarkland
@n3l5
@napalmpiri
@nappingdingo
@nathanm412
@Nevyn357
@nichtdu
@no-flo
@NonSecwitter
@nycdotnet
@nylyst
@OldCole
@oliverqt
@onyxhat
@opexxx
@oshit
@panpetedextra
@pauldalewilliams
@peachsnap
@penguin2708
@PerOve
@Persistent13
@PeterGeelen
@PeterMTaylor
@PetterBomban
@PeyTy
@pezmannen
@phaufe
@philbritton
@philiplavoie
@philippw
@phoemke
@pmd006
@pminnebach
@portaljacker
@PoshBarry
@primeinc
@proxb
@Proxx
@psott
@pwconsultant
@quonic
@rafaeltejero
@Rai-Ka
@RamblingCookieMonster
@randomizedthinking
@rdybro
@Rebenton
@redshiftltd
@rgel
@Riddickulus
@rirl
@RobCannon
@RobDesideri
@robertdyjas
@robinmalik
@roeintense
@roheve
@RowdyVinson
@rrremedio
@rtd
@Rukas
@russellds
@rysstad
@salbeck
@Sam-Martin
@sandravlado
@santifdezmunoz
@savestheday
@sbarnesisrael
@schwartzmx
@schwin97
@scottofrivia
@secretGeek
@sgwise
@sheldonhull
@shnups
@simonbyles
@siolarah
@skest3qc
@slyfur
@smccutchen
@smitpi
@smwk
@Sonihal
@sp00nhead
@spaminator
@SpeedyConsolas
@spences10
@srtucker
@stahler
@stcbus
@stephan765
@stephenwilliams
@stoinov
@stukey
@sullivanaz
@SuperFlue
@supermamon
@SuperMarioo
@taalmahret
@Tack122
@taheito
@tdeheurles
@teachMeCode
@tehmiller
@teodimache
@thatgeek
@theaquamarine
@theonlyway
@theotolias
@thuld
@ThunderFrame
@TiagoSoczek
@tklein
@tobias111
@todorm85
@tommy123ng
@tonidy
@Treasure-Blister
@tsugliani
@tvmani
@twitch-yarby
@twwilliams
@tyconsulting
@tysonflint
@tysonjhayes
@urasandesu
@valounet
@vanR
@victorvogelpoel
@vScripter
@W1M0R
@wangzq
@webmastir
@whaletail
@WilliamBrown42
@Windos
@wpx7
@wymmek
@wynnb
@xelsirko
@xfirebg
@yamahigashi
@zachpetersen
@ZacMillionaire
@Zolta
@Zuldan

**Comment by christophekumor** [comment]
Hello,
Sure, I want to test it.
Thx

**Comment by DarkLite1** [comment]
Great idea @dfinke! The more the merrier. This way we'll get valuable feedback from the people interested. One thing is for sure, it's working great here :) So common guys, start testing with all the bells and whistles. :D

**Comment by JustRiedy** [comment]
I just stumbled across this thanks to a [BlogPost](https://blogs.technet.microsoft.com/heyscriptingguy/2015/11/25/introducing-the-powershell-excel-module-2/)

I'll jump in and try the latest version.

**Comment by PeterMTaylor** [comment]
Oh another thought, could someone fill me in where this version (as in the direction of Import Excel goes) sits between https://chocolatey.org vs Powershell script gallery thanks.

**Comment by dfinke** [comment]
Haven't posted the beta version yet, stay tuned.

**Comment by JustRiedy** [comment]
I was just going to steal DarkLite1's branch, but if your posting a more "official" test copy I'll wait. Just so we're all on the same page.

**Comment by dfinke** [comment]
You can grab that branch for now. Working out where to set up a central place

**Comment by dfinke** [comment]
You can grab that branch for now. Working out where to set up a central place

**Comment by pezmannen** [comment]
Sign me up!

How do I find the branch you're talking about?

**Comment by BClev** [comment]
Is there a list of changes/updates?

**Comment by BClev** [comment]
I'm in to try it.

**Comment by DarkLite1** [comment]
Did someone already give it a test spin? Would be nice to have your feedback so we can merge this into the stable branch.

**Comment by dfinke** [comment]
I didn't package it. No feedback on it yet. I haven't had time to test it. Not sure when I will.
