### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by dtravisc** [dfinke/ImportExcel#19]
PS C:\Windows\system32> install-module -name importexcel
install-module : The term 'install-module' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ install-module -name importexcel
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-module:String
   ) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> $psversiontable.psversion

Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      -1     -1

PS C:\Windows\system32>

**Comment by dfinke** [comment]
Thanks for logging the issue. Install-Module is part of PowerShell v5 preview. So you can either install the preview to get that cmdlet or you can click the download zip, unblock the zip, unzip it and then copy/move all the files to a sub folder in the modules directory called ImportExcel.

Install-Module does all that. Let me know if you run into issues.

**Comment by dtravisc** [comment]
Downloaded the v5 preview and system claims it's already installed.

**Comment by dfinke** [comment]
Claims 5.0 is installed or the ImportExcel? The Apr 2015 preview should have install-module. You can do `Install-Module ImportExcel -Force`.

**Comment by dtravisc** [comment]
Claims v5 is installed

**Comment by dfinke** [comment]
And when you run PowerShell, the `$PSVersionTable` show 3.0? Hmm, not sure what is going on.

**Comment by dtravisc** [comment]
Correct

PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18444
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2


PS C:\Windows\system32>

Date: Wed, 13 May 2015 09:49:00 -0700

**Comment by dfinke** [comment]
I'm planning in adding a way to install this without needing Install-Module. Thanks to @Claustn  for the suggestion

**Comment by dfinke** [comment]
Added an install.ps1 that can be used instead of PowerShell v5.0 Install-Module.

```powershell
iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfinke/ImportExcel/master/Install.ps1')
```
