### ISSUE TITLE
How to middle align specific columns (enhancement)

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#194]
Is it possible to middle align specific columns? e.g. columns 1-3

Please add a switch like -Center "1-3". 
Would be a very helpful new feature. Safes time formatting an outputted Excel sheet. 

Thank you!

**Comment by dfinke** [comment]
@DarkLite1 Thoughts?

**Comment by DarkLite1** [comment]
Lots of ideas but not enough time for the moment. When I have some time I try to look at it in detail.

**Comment by dfinke** [comment]
@evild3ad  try this. 

You can pass a PowerShell ScriptBlock in `-CellStyleSB`. `Export-Excel` calls it after all the data is processed, passing it the worksheet that was populated. You can then format any range of cell styles.

```powershell
$xlsx="c:\testalign.xlsx"
rm $xlsx -ErrorAction Ignore

$(
    New-PSItem John Doe
    New-PSItem Jane Doe
    New-PSItem Harry Doe
    New-PSItem Tom Doe
) | Export-Excel $xlsx -show -CellStyleSB {
        param($workSheet)
        
        #$WorkSheet.Cells["A:B"].Style.HorizontalAlignment="Center"        
        $WorkSheet.Cells["A2:B5"].Style.HorizontalAlignment="Right"

}
```

**Comment by evild3ad** [comment]
@dfinke Works! Thank you!
