### ISSUE TITLE
How to change font color of top row

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#196]
I changed the fill color of my top row:
Set-CellStyle $WorkSheet 1 $LastColumn Solid Red

To finalyze my color-scheme I would like to change the font color of my top row.

Thank you!

**Comment by evild3ad** [comment]
-TitleForegroundColor parameter? My goal is to create Excel sheets in corporate-design. 

That would be awesome!

**Comment by FSGHWA** [comment]
Seeing that this is an old one, is there an option for this now? I searched through the readme but could not find it.

**Comment by uSlackr** [comment]
After export, you re-open to file as an excel package and set the color using Set-Format

$ExPkg =  Open-ExcelPackage $file
$sheet1 = $expkg.Workbook.Worksheets["Sheet1"]
Set-Format -Address $sheet1.Cells["A1"] -FontColor Red
Close-excelpackage $Expkg

Not sure how to address a whole row, sorry

\\Greg

________________________________

**Comment by dfinke** [comment]
## Another way

Shows how to select a row.

```powershell
$xlfile = "$env:TEMP\highlightrow.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$xl = ConvertFrom-Csv @"
Region,Item,TotalSold
South,melon,24
South,banana,43
North,saw,56
North,lime,27
East,saw,61
West,hammer,68
North,pear,45
East,lemon,77
West,nail,66
East,pear,79
"@ | Export-Excel $xlfile -PassThru

Set-Format -WorkSheet $xl.Sheet1 -Range "1:1" -FontColor Red

Close-ExcelPackage $xl  -Show
```
