### ISSUE TITLE
Looking for help with import-csv - export-excel

### ISSUE THREAD

**Issue by chrisduda** [dfinke/ImportExcel#197]
I'm trying to import a csv file and then export it to an xlsx file.  The simple job of import-csv file1.csv | export-excel file2.xlsx seems to work fine.  What I noticed is when someone else tried to create a pivot table from one of the columns that either has a value of TRUE or BLANK, the cells that were blank in the csv file are not null in the output excel file.  When we create the pivot table from one of the rows, we see a value of "TRUE" and "BLANK" when doing this on the csv file.  However, when using the converted xlsx file, it comes up with "TRUE" and then a column with no name.   If I go into that column and select the blank cells and then clear the contents, the pivot table refreshes and will show TRUE, BLANK and the no name field.  If I open the csv file in excel and then convert it to an excel spreadsheet, it works fine on the pivot table (same as the csv file).  Is there something to add to the powershell job to have the blank cells in the outputed xlsx file be cleared versus containing some info but showing as blank?

**Comment by dfinke** [comment]
Please post an example file and script
