### ISSUE TITLE
Position affect on the summation column

### ISSUE THREAD

**Issue by sanky555** [dfinke/ImportExcel#199]
Summation column ['Values'] always gets generated as the last element in the columns section. How can we move it up and give more priority?
![image](https://user-images.githubusercontent.com/12253641/27927603-f7a4e4de-62a9-11e7-9d7b-af0dab025043.png)

Below is the code which is used as of now:
`$Imported| Export-Excel -Path "path\to\excel\file.xlsx" -IncludePivotTable  -PivotDataToColumn -PivotData @{"Used Capacity(GB)"="Sum";"Free Space(GB)"="Sum"}  -PivotRows "Farms/Classification" -PivotColumns "Environment"   -AutoSize -BoldTopRow   -Show` 

How can we move the value column to the top of the column section?

**Comment by dfinke** [comment]
Very interesting challenge. This module is dependent on EPPlus, a C# DLL that manipulates the underlying XLSX. My instincts tell me that they did not make that available. I'll need to investigate.

**Comment by sanky555** [comment]
Ok please let us know if there is a work around this...it will be very grateful
