### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by KirkMunro** [dfinke/ImportExcel#2]
Hey Doug,

Cool stuff!  I had a few suggestions/questions I wanted to share:
1. Instead of -AutoFitColumns, how about using -AutoSize (like Format-Table) for consistency?
2. Are -IncludePivotTable/Chart parameters necessary? Because it seems like they could be inferred by the use of -Pivot\* parameters and -ChartType parameters, respectively.

Just some food for thought.

Kirk out.

**Comment by dfinke** [comment]
Thanks Kirk.

Too funny, when I looked at AutoFitColumns, I thought I should stay consistent, got lazy and said to myself, Kirk would go consistent.

Interesting suggestion on the pivot*. Sounds probable. Need to think it through.

Thanks for the great suggestions.

**Comment by KirkMunro** [comment]
Wait, are you insinuating that I'm predictable? :)

**Comment by dfinke** [comment]
No so much predictable as consistent =)

**Comment by irwins** [comment]
Hi Doug,

Great Module!

I was thinking: wouldn't it be cool to import multiple csv files to different worksheets in a single Excel workbook? This would make generating Excel reports a breeze! That way I can still export to csv (If necessary) and import to a different worksheet depending on what I'm working on.

For Active Directory reporting purposes I could have different worksheets:

-Default Domain Policy
-FSMO roles
-OU Structure
-Global Catalogs
-DomainControllers
-Sites
-Subnets
-SiteLinks

Having the worksheet name default to a topic would be great!

So what do you think?  Is that an option?

Keep up the good work!!! :-)

Regards,

Irwin

**Comment by dfinke** [comment]
Thanks Irwin. Great idea. Looking into it.

**Comment by mrdoff** [comment]
Hi Doug,

Great work!

Im trying to use export-xlsx within a Orchestrator runbook but I cant get it to work. When running it in ISE it works just fine.

This is what I run within a .Net Script in Orchestrator.

$result = Powershell {
Import-Module PSExcel

Get-ADGroup 'O365 Admin - E1 Licens' | Get-ADGroupMember | Where-Object {$_.objectClass -eq "user"} | Get-ADUser -Properties * | Select-Object SN,GivenName,sAMAccountName,Mail,canonicalname,extensionAttribute1 | Export-XLSX "E:\Runbook files\2. AD\2.3 Get Group Members\2.3.1\Export\O365 Admin - E1 Licens.xlsx" -AutoFit
}


BR
Ola

**Comment by dfinke** [comment]
Thanks Ola, PSExcel is https://github.com/RamblingCookieMonster/PSExcel

You can try the one I wrote and see if you get different results.

**Comment by josheinstein** [comment]
On the subject of parameter consistency, I wonder if -NoClobber would be more consistent than -Force? Seems like most of the Out-* and Export-* cmdlets use -NoClobber and overwrite by default, which I've sort of come to expect. The -Force parameter has typically been used to ignore a read-only bit.

**Comment by KirkMunro** [comment]
I agree, and had thought of suggesting that myself.  That way the script dictates what it does by default regardless of existing files, and if you want it to be considerate to not overwrite, you specify it.  NoClobber for overwrite vs. not overwrite, Force for read-only overwrite seems to be the model in other comparable cmdlets.

**Comment by dfinke** [comment]
Agree. I moved to a different approach and think `force` needs to come out.

**Comment by marthektheman** [comment]
NoClobber throws a worksheet already exists error.  No biggie I just delete the spreadsheet and all is well.  :)

Sheet1 already exists.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ImportExcel\ImportExcel.psm1:155 char:17
+                 throw "$WorkSheetname already exists."

**Comment by marthektheman** [comment]
Working great so far!  Small suggestion or maybe this is already available and I'm doing something wrong.  Is it possible to adjust the code so that only one set of data appears.  When I dump a table of data multiple times the data appears each time before the pivottable tabs.  I don't see where I can post an image as an example so I will post it on facebook as an example.
