### ISSUE TITLE
Can't use Export-Excel

### ISSUE THREAD

**Issue by mattmcnabb** [dfinke/ImportExcel#20]
When I try some of the examples from you video demonstration, the excel workbook that is created will not open and I get the error "There was a problem sending the command to the program." This is on Windows 8.1 x64 and I grabbed the latest version of your module from the PSGallery.

**Comment by dfinke** [comment]
Thanks for the issue. I need to update the video, there are parameters etc that have changed since I made it,

Could you post the cmd line you are trying? Plus the $error.

One thought, if you are trying to do a PivotTable and then rerun the on the same file and trying to get that pivottable generated again there is an issue that I am working to resolve

**Comment by mattmcnabb** [comment]
![exportexcel](https://cloud.githubusercontent.com/assets/6998507/7615149/933278d2-f969-11e4-9769-077c3b13b445.png)
I did initially try to run commands twice with the same file name, but overcame that. This particular issue occurs with a filename that does not already exist.

I should mention that I'm on a workstation that actually has Office 2013 Pro Plus installed. Will this make a difference?

**Comment by dfinke** [comment]
I'm in Europe. I be able to look at this when I return.

Does it create Procs.xlsx in that directory?

If so, can you double click on it and does it have data?

**Comment by mattmcnabb** [comment]
Yes it does. I get the same error if I try to launch the file directly.
              
 
Date: Wed, 13 May 2015 09:30:57 -0700

**Comment by dfinke** [comment]
Good point about Office Pro. Try renaming the extension from xlsx to xls. Just a thought.

**Comment by mattmcnabb** [comment]
Sorry for the delayed response!

It seems that after I initially got an error when I tried this the first time, it completely hosed Excel for me. I wasn't just having problems opening the workbooks created by ImportExcel, I couldn't launch Excel at all! I repaired Office and rebooted and everything is now fine. 

I'm still not sure what steps actually caused this issue, though, so it may be something to watch out for. Hopefully it was just my blundering attempt at using the module that caused the problem but I suppose that indicates that this could be destructive.

**Comment by dfinke** [comment]
Sorry to hear that.

That sounds very odd though, Export-Excel will work on a machine without having Excel installed.
It is C# code + PowerShell that does not depend on or use anything in Excel at all. 

Export-Excel creates an XML file inside a zip file, which is what all modern Office Applications create for Word, Excel, PowerPoint etc.

**Comment by mattmcnabb** [comment]
Yup, very odd. I suppose it could have just been a freak occurrence - it is Office after all!

**Comment by dfinke** [comment]
Sounds like the office install is suspect. This module works without it being installed, so it seems very unlikely it can corrupt that. Let me know if you run into it again and we can troubleshoot.
