### ISSUE TITLE
Export-Excel: Title becomes header of table

### ISSUE THREAD

**Issue by johnny5a** [dfinke/ImportExcel#207]
I'd like to have a sheet with a table and a title but they don't play well together.
Adding this line fixes the issue:
 if (-not [String]::IsNullOrEmpty($Title)) {$csr++}

LN 468
`
            if (-not [String]::IsNullOrEmpty($TableName)) {
                $csr = $StartRow
                $csc = $StartColumn
                $cer = $ws.Dimension.End.Row
                $cec = $script:Header.Count

                $targetRange = $ws.Cells[$csr, $csc, $cer,$cec]
                $tbl = $ws.Tables.Add($targetRange, $TableName)
                $tbl.Table            if (-not [String]::IsNullOrEmpty($TableName)) {Style = $TableStyle
}`

**Comment by dfinke** [comment]
Would you like to fork the repo and try to do a PR?

**Comment by johnny5a** [comment]
Sure... I'm new to github, still figuring things out.

**Comment by DarkLite1** [comment]
I'll have a look at this when I have some time. Just rewrote `Import-Excel`, so bare with me.

**Comment by johnny5a** [comment]
No worries, I just made the change to the code I'm running and wanted to get it changed here. 

These tools have been invaluable to me so thanks to everyone for working on these.

**Comment by dfinke** [comment]
@johnny5a Glad you find them useful
