### ISSUE TITLE
Export-Excel: If Title defined and background/fill not entered error is given

### ISSUE THREAD

**Issue by johnny5a** [dfinke/ImportExcel#208]
This catches the problem of a color defined but a bad FillPattern but also errors if the background color isn't set.

Under the else the warning needs an if statement: if ($TitleBackgroundColor) {}

LN 304
`            if ($TitleBackgroundColor -and $TitleFillPattern -ne 'None') {
                $ws.Cells[$Row, $StartColumn].Style.Fill.BackgroundColor.SetColor($TitleBackgroundColor)
            }
            else {
                Write-Warning "Title Background Color ignored. You must set the TitleFillPattern parameter to a value other than 'None'. Try 'Solid'."}
            }`

**Comment by dfinke** [comment]
Could you post a snippet of code that repros the issue?

**Comment by johnny5a** [comment]
>@(1,2,3,4)|Export-Excel -Path c:\temp\test -WorkSheetname "test" -Title "testing Title"
WARNING: Title Background Color ignored. You must set the TitleFillPattern parameter to a value other than 'None'. Try 'Solid'.
