### ISSUE TITLE
DateTime convertion .ToShortDateString()

### ISSUE THREAD

**Issue by JulienFloris** [dfinke/ImportExcel#209]
When I convert a DateTime Object .ToShortDateString() Excel those not recognize it as DateTime. And when I change the cell property by hand to date Value in Excel it still those not recognize it. 
Only when I change the content and change it back in Excel it is recognized as short date time. 

This is crucial to filter the data otherwise you’d Filter Strings. 

ImportExcel Module version 3.0.1
Tried MS Excel 2010 and 2016 with latest updates

**Comment by dfinke** [comment]
Please could you post a small sample

**Comment by JulienFloris** [comment]
**Example Code**
`
1 .. 100 | ForEach-Object {
	New-Object -TypeName psobject -Property @{
		Int		    = $_
		string	    = 'Abc'
		DateString  = (get-date).adddays($_).ToShortDateString()
	}
} | Export-Excel -Path C:\temp\temp.xlsx -FreezeTopRow -BoldTopRow -AutoFilter

& C:\temp\temp.xlsx
`

When you look at the DateString Colom in Excel you see that you cannot filter on date time object only stings value’s. And even if you set the value as ‘ShortDate’ notation it those not work. 
Only is you change the content for every cell is changes to real date time value.

**Comment by dfinke** [comment]
Yes, using `ToShortDateString` converts the date to a string. `Export-Excel` infers data types so it stores that as a string. If you `ToShortDateString`, you can then use the Excel date format.

**Comment by JulienFloris** [comment]
Only Excel 'Breaks' and can't format it to data value anymore. 
Office 2016 and Office 2010 ( Dutch Edition)

**Comment by DarkLite1** [comment]
`ToShortDateString` literally means to convert it to a `String`. Only real `DateTime` objects are exported by `Export-Excel` as dates that are recognized by Excel. It's then up to the user to format the date in Excel to the desired format.

If you run `Export-Excel -Verbose` you can see it stores `Strings` as `Strings` and `DateTime` objects as `Dates`.

**Comment by JulienFloris** [comment]
`
1 .. 50 | ForEach-Object {
    New-Object -TypeName psobject -Property @{
        Int = $_
        string = 'Abc'
        DateString = [datetime]::Parse('01-02-2017')
    }
} | Export-Excel -Path C:\temp\temp.xlsx -FreezeTopRow -BoldTopRow -AutoFilter
& C:\temp\temp.xlsx
`
DateTime Object gives me this output: 20-9-2017  00:00:00
Desired output is 20-09-2017 (Excel Short Time notation)
If export-excel could tell the difference between ShotTime Notation and a long time notation based upon the object that would be great.
Example
20-9-2017  00:00:00 # Should be default Short Time Notation
20-9-2017  00:00:00 # Should be default long time notation

**Comment by DarkLite1** [comment]
I understand your request, but for now we only deliver the `DateTime` object formatted in Excel as a `DateTime` field. No extra formatting. like `ShortTimeNotation` or `LongTimeNotation` is happening.

@dfinke . is it possible to format this by using `-CellStyleSB`?

**Comment by DarkLite1** [comment]
Played a bit more with this:

$Params = @{
    Path     = '.\test.xlsx'
    AutoSize = $true
}

Remove-Item  $Params.Path -EA Ignore

# Get-Service | Select-Object -Property Status, Name, DisplayName, StartType | Export-Excel @Params -WorkSheetname Sheet2
# Get-Process | Select-Object -Property Name, Company, Handles, CPU, VM | Export-Excel @Params -WorkSheetname Sheet3

# '=HYPERLINK("#Sheet2!A1";"Go to second sheet cell A1")' | Export-Excel @Params -WorkSheetname Sheet1 -Verbose

# 'Navigation', '=HYPERLINK("#Sheet2!A1";"Go to second sheet cell A1")', '=HYPERLINK("#Sheet3!B7";"Go to third sheet cell B7")' | Export-Excel @Params -WorkSheetname Sheet1 -Verbose



#  [PSCustOmobject]@{
#         Link1  = '=HYPERLINK("#Sheet2!A1";"Go to second sheet cell A1")'
#         Link2   = '=HYPERLINK("#Sheet3!B7";"Go to third sheet cell B7")'
#     } | Export-Excel @Params 

#  [PSCustOmobject]@{
#         Formula1  = '=SUM(B2:C2)'
#         Number1   = '15'
#         Number2   = '85'
#     } | Export-Excel @Params 

```
$Params = @{
    Path       = 'Test.xlsx'
    AutoFilter = $true
    AutoSize   = $true
}

Remove-Item  $Params.Path -EA Ignore

$Result = Get-ChildItem | Select-Object -First 2 -Property Name, 
@{N = 'ToShortDateString'; E = {$_.LastWriteTime.ToShortDateString() }},
@{N = 'ToLongDateString'; E = {$_.LastWriteTime.ToLongDateString() }},
@{N = 'DateTimeParsedLong'; E = {[DateTime]::Parse($_.LastWriteTime) }},
@{N = 'DateTimeParsedShort'; E = {[DateTime]::Parse($_.LastWriteTime.ToShortDateString()) }},
LastWriteTime

$Result | Export-Excel @Params -Verbose
```
This gives me:
```
VERBOSE: Add worksheet 'Sheet1'
VERBOSE: Cell '1:1' add header 'Name'
VERBOSE: Cell '1:2' add header 'ToShortDateString'
VERBOSE: Cell '1:3' add header 'ToLongDateString'
VERBOSE: Cell '1:4' add header 'DateTimeParsedLong'
VERBOSE: Cell '1:5' add header 'DateTimeParsedShort'
VERBOSE: Cell '1:6' add header 'LastWriteTime'
VERBOSE: Cell '2:1' header 'Name' add value '.vscode' as string
VERBOSE: Cell '2:2' header 'ToShortDateString' add value '11/07/2017' as string
VERBOSE: Cell '2:3' header 'ToLongDateString' add value 'dinsdag 11 juli 2017' as string
VERBOSE: Cell '2:4' header 'DateTimeParsedLong' add value '11/07/2017 09:42:52' as date
VERBOSE: Cell '2:5' header 'DateTimeParsedShort' add value '07/11/2017 00:00:00' as date
VERBOSE: Cell '2:6' header 'LastWriteTime' add value '07/11/2017 09:42:52' as date
VERBOSE: Cell '3:1' header 'Name' add value 'AD Incon' as string
VERBOSE: Cell '3:2' header 'ToShortDateString' add value '5/10/2017' as string
VERBOSE: Cell '3:3' header 'ToLongDateString' add value 'donderdag 5 oktober 2017' as string
VERBOSE: Cell '3:4' header 'DateTimeParsedLong' add value '05/10/2017 09:46:07' as date
VERBOSE: Cell '3:5' header 'DateTimeParsedShort' add value '10/05/2017 00:00:00' as date
VERBOSE: Cell '3:6' header 'LastWriteTime' add value '10/05/2017 09:46:07' as date
```

When parsing takes place the month and the day field are switched. My system is set to `English` but somehow there is some `Dutch` sneaking in there.
