### ISSUE TITLE
PS Version 4.0 install not working

### ISSUE THREAD

**Issue by ww40** [dfinke/ImportExcel#213]
Had some trouble trying to install this to a PS version 4.0 2012 R2 server.

$PSVersionTable Result: 

> Name                           Value                                                                                                
> ----                           -----                                                                                                
> PSVersion                      4.0                                                                                                  
> WSManStackVersion              3.0                                                                                                  
> SerializationVersion           1.1.0.1                                                                                              
> CLRVersion                     4.0.30319.42000                                                                                      
> BuildVersion                   6.3.9600.18728                                                                                       
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                 
> PSRemotingProtocolVersion      2.2  

**Attempt** (taken from your install recommendations for V4.0 and earlier)**:**
`iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfinke/ImportExcel/master/Install.ps1')`

**Result:**

> iex : The script block cannot be invoked because it contains more than one clause. The Invoke() method can only be used on script 
> blocks that contain a single clause.
> At line:1 char:1
> + iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfi ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], PSInvalidOperationException
>     + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by rhoffman303** [comment]
I am getting the same error as ww40

**Comment by dfinke** [comment]
Can you pull it from the gallery, or is that not an option? Another way, you can clone the repo and run `.\InstallModule.ps1`

**Comment by rhoffman303** [comment]
That seems to have worked. Thanks.
