### ISSUE TITLE
Example gif needs updating

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#215]
Import-Excel 3.0 imported the first sheet by default, so the Example GIF at 
https://github.com/dfinke/ImportExcel#importing-data-from-an-excel-spreadsheet
was showing correct usage.
Import-Excel 4.0 no longer imports the first sheet by default, but rather prompts if WorkSheetName is not provided.
Need to allow first sheet to be default or update the GIF.

**Comment by dfinke** [comment]
@scottone Thanks for heads up on that.

@DarkLite1 Let's discuss. I prefer that the fewer parameters needed the better. On that note, I'm thinking that the `-Now` parameter on `Export-Excel` be removed and all the default values it sets are set if you do `Export-Excel c:\temp\test.xslx`.

**Comment by DarkLite1** [comment]
Yes, we can enhance `Import-Excel` so it will import by default the first sheet only. So the question is, how do we determine the name of the first sheet? In English it would be `Sheet1` and in other languages it might differ. I'll have a look at the code when I have some time to see if we can determine what the first sheet is and import only that one by default.

Regarding `Export-Excel`, I would really like to rewrite that function completely. To make it more readable and future proof. For the moment it allows you to generate corrupt Excel files which should not be possible (Ex. combining -TableName, -FreezeTopRow  and -AutoFilter). We should at least review the `ParameterSets` but at the moment I don't have the time for that I'm afraid.

**Comment by dfinke** [comment]
Need to look at how Import-Excel read the first sheet before the re-write. It may have assumed Sheet1.

**Comment by DarkLite1** [comment]
You are correct, it did assume `Sheet1`. But we can do better, I'll have a look at it when I have some time and come up with a PR for multi language environments.

**Comment by DarkLite1** [comment]
Fixed in #216

**Comment by DarkLite1** [comment]
@dfinke  can be closed because `Import-Excel` is fixed now. I suggest starting another `Issue` for `Export-Excel` changes.
