### ISSUE TITLE
Combine `Install.ps1` and `InstallModule.ps1`

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#218]
We should try to combine `Install.ps1` and `InstallModule.ps1` into one script file. 

Adavantages:

- Get rid of the duplicate file list `$Files`
- Fix outstanding bugs #213 #211

**Comment by dfinke** [comment]
Need to review. Might be able to delete both.

**Comment by ili101** [comment]
You can copy the version from my repository, it do both.
https://github.com/ili101/Join-Object/blob/master/Install.ps1
`$Uri = 'https://raw.githubusercontent.com/ili101/Join-Object/master/Install.ps1'; & ([Scriptblock]::Create((irm $Uri))) -FromGitHub $Uri`
Just set the $Files and $ExcludeFiles as needed.
