### ISSUE TITLE
Possible to install without Internet access?

### ISSUE THREAD

**Issue by gdbarber** [dfinke/ImportExcel#219]
Is there a way to install ImportExcel on a 2012 R2 server without Internet Access and PowerShell version 4? I copied the ImportExcel folder over and tried running the InstallModule.ps1 file which moved the modules but must not have registered them.

Here is the results of $psversiontable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.36366
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

and gmo -list importexcel

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.0.0      ImportExcel                         {New-Plot, Import-Excel, Add-WorkSheet, ConvertFrom-ExcelS...

Thanks

**Comment by dfinke** [comment]
So, it looks like it is installed and recognized.

What output do you get from `ipmo importexcel -force -verbose`?

Does a file created with this? Can you open it?
```powershell
"hello world" | Export-Excel c:\temp\test.xlsx
```

**Comment by gdbarber** [comment]
This is what I get from each command. Thanks.
PS C:\Users> ipmo importexcel -force -verbose
ipmo : The specified module 'importexcel' was not loaded because no valid module file was found in any module
directory.
At line:1 char:1
+ ipmo importexcel -force -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (importexcel:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
	
==========================================================	
PS C:\Users> "hello world" | Export-Excel c:\temp\test.xlsx
Export-Excel : The term 'Export-Excel' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:17
+ "hello world" | Export-Excel c:\temp\test.xlsx
+                 ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Export-Excel:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by gdbarber** [comment]
Great that part worked. Thanks.

On my script, when executing this: 
                     $xl = new-object -comobject excel.application

I get the error:
      new-object : Retrieving the COM class factory for component with CLSID 
{00000000-0000-0000-0000-000000000000} failed due to the following error: 80040154 Class not registered 
(Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
At E:\Public\ProcessData\test.ps1:16 char:11
+     $xl = new-object -comobject excel.application
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by dfinke** [comment]
So using `comobject`, that requires Excel to be installed.

So the module works now that you did the `Import-module`?

**Comment by gdbarber** [comment]
Hmm. I tested on my own machine and it had Excel installed. I will have to look at examples that do not require Excel. 
The module does seem to work ok.
Thanks!

**Comment by dfinke** [comment]
Ok, I'll close this and we can reopen it.
