### ISSUE TITLE
Investigate adding

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#22]
![image](https://cloud.githubusercontent.com/assets/67258/7672243/efd7a2f4-fcb8-11e4-83e0-a2dca665aa59.png)

**Comment by chrisk59** [comment]
thx for adding this ! 8-)

**Comment by chrisk59** [comment]
hello, any news about this feature ? 
do you think it's possible ? or it seem too hard ?
take care
chris

**Comment by dfinke** [comment]
I looked at it and could not find an easy way to expose this feature. I'm still looking into it.

**Comment by chrisk59** [comment]
ah ok thx for the effort.

**Comment by chrisk59** [comment]
oh no dfinke !!! was so simple ! i did it.. ;-)
