### ISSUE TITLE
Distinct Count function for pivot table

### ISSUE THREAD

**Issue by JonHayesLU** [dfinke/ImportExcel#220]
Is there any way to use "Distinct Count" when creating a pivot table ?

In Excel through the GUI when creating a pivot table, if the data range is added to the Data Model, it becomes possible to summarize values by Distinct Count.

I can't see any way of achieving this currently. I imagine it as something like below

`Export-Excel -IncludePivotTable -PivotRows row1 -PivotData @{column1="DistinctCount"}`

Currently trying this gives the following error

> Failed exporting the worksheet: Exception setting "Function": "Cannot convert value "DistinctCount" to type "OfficeOpenXml.Table.PivotTable.DataFieldFunctions". Error: "Unable to match the identifier name DistinctCount to a valid enumerator name.  Specify 
> one of the following enumerator names and try again: Average, Count, CountNums, Max, Min, Product, None, StdDev, StdDevP, Sum, Var, VarP""

Thanks

**Comment by dfinke** [comment]
Looks like EPPlus library that this PS wraps does not have a `DistinctCount`. Next step is to post a question to the authors of that library.
