### ISSUE TITLE
0 gets exported as a string by default

### ISSUE THREAD

**Issue by unit41** [dfinke/ImportExcel#222]
In Export-Excel.ps1, on line 310 of build 4.0.0, the check for whether a number conversion is possible is:
`if ($Number = ConvertTo-Number $_) {`

It should be
`if (($Number = ConvertTo-Number $_) -ne $null) {`

**Comment by DarkLite1** [comment]
Thanks for the heads up! Can you provide some example code of what you expect to be exported and what isn't the case? It makes it more clear for me what you exactly want to achieve and why it's not delivering the result you expect.

**Comment by unit41** [comment]
Sorry, I'm unlikely to write an example because I've moved on to other
things.  But it should be very easy to reproduce.  Just import anything
that includes the number zero into Excel.  Notice that zero gets imported
as a string and all other numbers get imported as numbers.  Obviously
that's not intended and it causes problems when you later go to do math on
the data or make charts from it.
