### ISSUE TITLE
How to export the values in a particular column in a table?

### ISSUE THREAD

**Issue by psyapathy** [dfinke/ImportExcel#225]
How to export the values in a particular column in a table? I have a table in .xlsx. It already has column "processes". 
I need to export the values of the processes in this table in column "processes"

Thank you!

**Comment by DarkLite1** [comment]
Can you post a code example of what you mean? It's not really clear to me if you try to import an Excel sheet with a table in it or if you would like to export objects to an Excel sheet.

Thank you for clarifying with some code.

**Comment by slestak** [comment]
I think I see what he is asking.  If you are using the ConvertFrom-ExcelToSQLInsert function, and the worksheed has 5 columns, how can you specify just one column, i.e. processes.  I am trying to do something similar, and will likely provide a pull request for mapping column names.  Consider this use case. I want to export a column names processes in the source table, but I want it named foo in the output.
