### ISSUE TITLE
Help with changing background color of row based on data presence

### ISSUE THREAD

**Issue by danman5713** [dfinke/ImportExcel#229]
Hi, all! I am trying to have powershell parse through an excel file looking for data in the "Status" column, and based on the data there, apply a background color for that row. So here's my code, basically I'm trying to make the rows background color blue if the string "OoO" appears in the status column of that row.

`$SetCellStylesOpen = Import-Excel "$ScriptPath\Threat-Analysis.xlsx" -WorksheetName "Active-Hold"

Foreach ($Row in $SetCellStylesOpen)
{
    If ($Row.Status -eq "OoO")
    {
       #The next 2 lines are to make sure the correct row number is selected for this entry
        $RowNumber = [array]::IndexOf($SetCellStylesOpen, $Row)
        $RowNumber = $RowNumber + 2
        Set-CellStyle -Color Blue -Pattern Solid -LastColumn "J" -WorkSheet "$SetCellStylesOpen"  -Row $RowNumber 
    }
}`

For the worksheet variable I have also tried just using the name of the worksheet "Active-Hold" but that yields the same results. The following are the errors I get...

PS C:\Windows\system32> Path\Scripts\Excel sheet combine.ps1
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\4.0.0\Set-CellStyle.ps1:10 char:51
+     $t=$WorkSheet.Cells["A$($Row):$($LastColumn)$($Row)"]
+                                                                                      ~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
The property 'PatternType' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\4.0.0\Set-CellStyle.ps1:11 char:5
+     $t.Style.Fill.PatternType=$Pattern
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\4.0.0\Set-CellStyle.ps1:12 char:5
+     $t.Style.Fill.BackgroundColor.SetColor($Color)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Thanks in advance for any help you can offer!

**Comment by dfinke** [comment]
The `Import-Excel` function returns only the data in the Excel worksheet, as an array of objects with properties.

**Comment by danman5713** [comment]
Thanks for the reply! So then how do I use the Set-CellStyle function? It doesn't appear to have a way to specify the file to edit.

**Comment by dfinke** [comment]
`Set-CellStyle` is intended to work when you are create the Excel file.

https://github.com/dfinke/ImportExcel/blob/master/Examples/FormatCellStyles/ApplyFormatInScriptBlock.ps1

Also, maybe ConditionalFormatting may help. https://github.com/dfinke/ImportExcel/tree/master/Examples/ConditionalFormatting

These module features work only when creating the Excel file.
