### ISSUE TITLE
Error while exporting to an existing spreadsheet with existing pivot tables

### ISSUE THREAD

**Issue by pezhore** [dfinke/ImportExcel#23]
I have an existing xlsx file that contains various pivot tables and charts based on data that I would like to update using `Export-Excel`. The various tables are on a worksheet labeled "Tables" and the charts are on a "Charts" worksheet. I'm using this file as a template file of sorts; it contains the complex tables/charts based off of data in the Chassis worksheet and I don't have to try and recreate/organize the tables/charts every time - only refresh the data.

While trying to export an array of chassis information to this xlsx file, I receive the following error:

```
$chassisArray  | Export-Excel -Path $existingFile -worksheetname Chassis -BoldTopRow -AutoSize -Debug
Exception calling "Save" with "0" argument(s): "Error saving file C:\temp\test.xlsx"
At line:120 char:13
+             $pkg.Save()
+             ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```
 If I remove the worksheet that contains the pivot tables, the export is successful, however this defeats the purpose of leveraging a template file.

**Comment by dfinke** [comment]
Thanks for reporting the issue. The underlying library that supports exporting to the xlsx has options for working with templates. I have not looked at how to expose that through the PowerShell interface. Could you post that and I can investigate the level of effort (and viability) to make that work.

**Comment by pezhore** [comment]
Can you clarify what you'd like posted?

**Comment by dfinke** [comment]
Optimally, the xlsx you use as a template, plus the data and how you want to export.
