### ISSUE TITLE
can someone help me to fix this?

### ISSUE THREAD

**Issue by kap260** [dfinke/ImportExcel#235]
hello - 
I have imported your module from the Gallery, but I am getting this error.

Export-Excel : Unable to find type [OfficeOpenXml.Style.ExcelFillStyle].
At C:\Users\kapeterson\Documents\WindowsPowerShell\Excel2.ps1:873 char:5
+     Export-Excel $PWDocuments  .\Test.xlsx -show
+     ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (OfficeOpenXml.Style.ExcelFillStyle:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
[Excel2.zip](https://github.com/dfinke/ImportExcel/files/1395505/Excel2.zip)

**Comment by dfinke** [comment]
try

`Get-Process | select company, handles | export-excel .\test.xlsx -show`

**Comment by azj100** [comment]
I've got the same issue, on two separate installations (office 2016).
`Get-Process | select company, handles | export-excel .\test.xlsx -show`
`Unable to find type [OfficeOpenXml.Style.ExcelFillStyle].`
`At Export-Excel.ps1:167 char:9`
`+         [OfficeOpenXml.Style.ExcelFillStyle]$TitleFillPattern = 'None ...`
`+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (OfficeOpenXml.Style.ExcelFillStyle:TypeName) [], R 
   untimeException`
`    + FullyQualifiedErrorId : TypeNotFound`
