### ISSUE TITLE
TimeLine Exports & Buttons

### ISSUE THREAD

**Issue by greekit** [dfinke/ImportExcel#24]
Very good job !!!
I am wondering if I can export something like intranet timeline chart
see here: http://www.zakon.org/robert/internet/timeline/Count_Network.gif 
something like the above. maybe with lines to connect each tick group!

Is there any way , also, to set button with functionality in the cells?
something like a button to make visible and not visible some cells.
or a button to make visible or not visible some charts.

thank you very much in advance!!

**Comment by dfinke** [comment]
Thank you. You can use the below to create the initial sheet and experiment with the different Excel chart types. Perhaps there is a chart type that is not exposed that can be.

Currently there is nothing in the PowerShell module that lets you create buttons. It's a great idea and I'll look into if it can be done and how much work it will take.

```powershell

$data = @"
Type,Date,Countries
Internet,7/91,25
BitNet,7/91,45
UUCP,7/91,65
FIDONET,7/91,85
OSI,7/91,95
Internet,11/91,35
BitNet,11/91,55
UUCP,11/91,75
FIDONET,11/91,95
OSI,11/91,105
"@ | ConvertFrom-Csv 

$data |Export-Excel c:\temp\timeline.xlsx -Show -IncludePivotTable -IncludePivotChart -PivotRows Date -PivotColumns Type -PivotData Countries -ChartType LineMarkers
```

**Comment by greekit** [comment]
OOhhh Thank you very much ! ! 
I agree it's a very good idea it will offer some interactiveness to the user I guess.
To have buttons to show you some different things in a worksheet.
Obviously this can be done by exporting separate files to show the data but it would be good idea to have all the data you like to show in a unique xlsx file!!

In any case thank you very much for helping me ! :)
I'm looking forward to see anything new on module updates :) :) :+1: 
again thank you very very much!!
