### ISSUE TITLE
Exported Excel doesn't import into PowerBI Online

### ISSUE THREAD

**Issue by JustinGrote** [dfinke/ImportExcel#240]
When trying to import via the onedrive for business method, it returns "error 400" on the file. If I take the file, open it in excel, and save it, then it works fine. It also imports into PowerBI Desktop Fine without having to open it in excel first.

I wanted to use this in an Azure Function to batch export data from a proprietary system into a format I can use with PowerBI and automatically refresh hourly, and one excel with multiple worksheets is ideal so I can create relationships. I may be able to make this work with CSVs or an Azure SQL database I dump and rebuild periodicall but that is cumbersome.

Here is an example of "before" and "after" opening in excel and saving, maybe you can diff for what it's looking for. The excel file is significantly larger.

[testexport.xlsx](https://github.com/dfinke/ImportExcel/files/1419914/testexport.xlsx)
[testexport-saveinexcel.xlsx](https://github.com/dfinke/ImportExcel/files/1419915/testexport-saveinexcel.xlsx)

**Comment by dfinke** [comment]
Very cool. Will dig deeper.

I think this module in Azure functions will be very powerful.

I wired up the module here in an Azure function. Give it try.

```
https://getstockquoteinexcel.azurewebsites.net/api/RequestExcelStockInfo?symbol=msft,xom,ge,ibm,jpm,fb&email="<<your email address>>"
```

**Comment by JustinGrote** [comment]
It's not the Azure functions part, that works great, it's that the file
generated doesn't import into power BI, regardless of if it was made in
functions or locally.

I'm guessing though I'm going to have to go to the EPPlus library people
about it as it seems to do with the internal format missing something
that's in a "Normal" excel save that PowerBI is erroring out on.

**Comment by CrashM** [comment]
There appears to be an issue logged with EPPlus [https://github.com/JanKallman/EPPlus/issues/168](https://github.com/JanKallman/EPPlus/issues/168)  where they even propose a fix.  Related to #254

**Comment by JustinGrote** [comment]
As a workaround sounds like we can unzip/rezip the file with the. Net
compression library till the fix is implemented upstream. I'll give this a
try.

**Comment by CrashM** [comment]
@JustinGrote Sounds great.  Hope you can figure a minimalist set of commands.  Can you post your attempt please?

**Comment by JustinGrote** [comment]
I've submitted #312 for a workaround for now until upstream EPPlus gets fixed

**Comment by CrashM** [comment]
@JustinGrote Patch confirmed working with -ReZip parameter
