### ISSUE TITLE
Invalid Argument: [Export-Excel]

### ISSUE THREAD

**Issue by colin715** [dfinke/ImportExcel#241]
I am attempting to export a bunch of SQL queries from SQL Server and have them put into one Excel file with multiple sheets.  I have successfully done this numerous times on my work computer, but am getting a strange error when I am trying the same exact thing at my house.  I have installed the module and have updated the database info and file paths to reflect my home computer, but I am still getting the same error:
```

Export-Excel : A positional parameter cannot be found that accepts argument 'C:\Users\Colin\Desktop\OpsCostAccountTab2.xlsx'.
At C:\Users\Colin\OneDrive - MediaMind365\SQL\Untitled2.ps1:30 char:98
+ ... HasErrors | Export-Excel 'C:\Users\Colin\Desktop\OpsCostAccountTab2.x ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-Excel], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Export-Excel
```

Here is a sample of what I'm trying:

```
$SQLServer = 'DESKTOP-7EVPOVV\SQLEXPRESS';
$Database = 'Reports';

$ConnectionString = "Data Source={0};Initial Catalog={1};Integrated Security=SSPI" -f $SQLServer, $Database;
$CommandText = @'


SELECT * FROM region;


'@;

$SqlConnection = New-Object System.Data.SqlClient.SqlConnection;
$SqlConnection.ConnectionString = $ConnectionString;

$SqlCommand = New-Object System.Data.SqlClient.SqlCommand;
$SqlCommand.CommandText = $CommandText;
$SqlCommand.Connection = $SqlConnection;

$SqlDataAdapter = New-Object System.Data.SqlClient.SqlDataAdapter;
$SqlDataAdapter.SelectCommand = $SqlCommand;

$DataSet = New-Object System.Data.DataSet;

$SqlConnection.Open();
$SqlDataAdapter.Fill($DataSet) | Out-Null;
$SqlConnection.Close();
$SqlConnection.Dispose();

$DataSet.Tables[0] | Select * -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel 'C:\Users\Colin\Desktop\OpsCostAccountTab2.xlsx' -worksheetname "Main Dashboard";
```

Once again, this works flawlessly on my work computer and I have never seen this error until now.

**Comment by t-0-m-1-3** [comment]
I am running into a similar issue running through the examples. 

`PS C:\Users\Tom> $file = "C:\Temp\ps.xlsx"
rm $file -ErrorAction Ignore

ps |
    where company |
    select Company,PagedMemorySize,PeakPagedMemorySize |
    Export-Excel $file -Show -AutoSize `
        -IncludePivotTable `
        -IncludePivotChart `
        -ChartType ColumnClustered `
        -PivotRows Company `
        -PivotData @{PagedMemorySize='sum';PeakPagedMemorySize='sum'}
Export-Excel : A positional parameter cannot be found that accepts argument 'C:\Temp\ps.xlsx'.
At line:7 char:5
+     Export-Excel $file -Show -AutoSize `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-Excel], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Export-Excel`

`PS C:\Users\Tom> Get-Process |
    Select-Object Company,Handles,PM, NPM|
    Export-Excel $xlfile -Show  -AutoSize -CellStyleSB {
        param(
            $workSheet,
            $totalRows,
            $lastColumn
        )

        Set-CellStyle $workSheet 1 $LastColumn Solid Cyan

        foreach($row in (2..$totalRows | Where-Object {$_ % 2 -eq 0})) {
            Set-CellStyle $workSheet $row $LastColumn Solid Gray
        }

        foreach($row in (2..$totalRows | Where-Object {$_ % 2 -eq 1})) {
            Set-CellStyle $workSheet $row $LastColumn Solid LightGray
        }
    }
Export-Excel : A positional parameter cannot be found that accepts argument '$null'.
At line:3 char:5
+     Export-Excel $xlfile -Show  -AutoSize -CellStyleSB {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-Excel], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Export-Excel`

**Comment by dfinke** [comment]
```
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                     
---------- -------    ----                                ----------------                                                                                     
Script     4.0.4      ImportExcel                         {Get-XYRange, New-PivotTableDefinition, Test-Number, Add-WorkSheet...}                               
```

```powershell
$file = "C:\Temp\ps.xlsx"
rm $file -ErrorAction Ignore

ps | where company | select Company,PagedMemorySize,PeakPagedMemorySize |
    Export-Excel $file -Show -AutoSize -IncludePivotTable -IncludePivotChart -ChartType ColumnClustered -PivotRows Company -PivotData @{PagedMemorySize='sum';PeakPagedMemorySize='sum'}
```

![image](https://user-images.githubusercontent.com/67258/32249343-18c995ea-be5f-11e7-89e3-36ab05a75309.png)
