### ISSUE TITLE
ImportExcel and SHiPS

### ISSUE THREAD

**Issue by MMitsialis** [dfinke/ImportExcel#242]
Hi,

The release of SHiPS opens a world of possibilities for this module. @dfinke has posted some demos of his playing with SHiPS and Excel. Is there any ideas whether this may be incorporated into this module or where it will be a seperate project/repo?

**Comment by dfinke** [comment]
It's very early in the release for SHiPS. They've only got the basics implemented. I had planned it to be of this module once it got some legs.
