### ISSUE TITLE
Import from URL (Sharepoint or Onedrive)

### ISSUE THREAD

**Issue by docthomas** [dfinke/ImportExcel#244]
Is it possible to Import xls from a Sharepoint site?  The -Path statement does not seem to allow a direct url to an xls stored on Sharepoint.   I am not sure if there is a different formatting I need to use for the path statement.

**Comment by dfinke** [comment]
I don't know SharePoint. So I'm not sure. I think if you can open it from the file manager, this ought to work but I've never tried it.

**Comment by eskoviak** [comment]
I'm interested in going the other way:  Using Excel Services on SP, use PS to assemble the data and update one or more sheets in a workbook.  There will also be analysis and other macros, which I want to persevere in the workbook.  I can provide a public sharepoint site for testing.
