### ISSUE TITLE
BoldTopRow, AutoFilter & FreezeTopRow not working on Export-MultiExportsheets

### ISSUE THREAD

**Issue by jaydeepjc** [dfinke/ImportExcel#246]
First of all that you very much for this plugin.

I have created powershell script to get various output and export it on multiple worksheet under single excel without any issues.
 below is the script 
       
    $all = @{
      VPN_Sales = {Get-ADGroupMember -identity "VPN_Sales" | select name,   samaccountname, distinguishedname}
      VPN_log   = {Get-ADGroupMember -identity "VPN_log" | select name, samaccountname, distinguishedname}
      VPN_Audit = {Get-ADGroupMember -identity "VPN_Audit" | select name, samaccountname, distinguishedname}
      VPN_Tax   = {Get-ADGroupMember -identity "VPN_Tax" | select name, samaccountname, distinguishedname}
    }
     Export-MultipleExcelSheets -AutoFilter .\List.XLSX $all 

However When I tried to add 

`Export-MultipleExcelSheets -BoldTopRow -AutoFilter -FreezeTopRow -AutoFilter .\List.XLSX $all`

It gives error
    `Export-MultipleExcelSheets : A parameter cannot be found that matches parameter name  'BoldTopRow'.
    At C:\JD\test.ps1:27 char:32
    +     Export-MultipleExcelSheets -BoldTopRow -AutoSize .\List.XLSX $all
    +                                ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-MultipleExcelSheets], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Export-MultipleExcelSheets`

Am i missing something? How to fix this?

**Comment by DarkLite1** [comment]
When I check `Get-Help` it shows me the following:

```
Get-Help Export-MultipleExcelSheets

NAME
    Export-MultipleExcelSheets
    
SYNTAX
    Export-MultipleExcelSheets [-Path] <Object> [-InfoMap] <hashtable> [[-Password] <string>] [-Show] [-AutoSize]  [<Commo
    nParameters>]
```

There's no mention of '-BoldTopRow' or any other that u tried to use.  With `Export-Excel` these parameters are available, but not with `Export-MultipleExcelSheets` apparently.
