### ISSUE TITLE
SQL not recognising "column names" from ConvertFromExcelToSQLInsert.ps1

### ISSUE THREAD

**Issue by MMitsialis** [dfinke/ImportExcel#247]
I have a simple statement that reads a spreadsheet using the ConvertFrom-ExcelToSQLInsert and pipes to Set-Content to create the T-SQL. 

SQL does not interpret the Column names as they are delimited using single apostrophes, whish SQL is then interpreting as escaped literal strings, not column names.  

I have change the below, SQL now works. I am not sure if this is a code or system issue and whether I should submit as a pull request? 

Original: 
        $ColumnNames = "'" + ($PropertyNames -join "', '") + "'"
Modified: 
        $ColumnNames = "[" + ($PropertyNames -join "], [") + "]"

**Comment by dfinke** [comment]
Thanks. Could you please post a sample xlsx and the what the correct SQL output that is needed.

**Comment by fredagstaco** [comment]
I'm having the same issue.

The queries I'm getting look like this:
INSERT INTO Table ('Field1','Field2') Values('val1','val2');

but need to be formatted like this for SQL Server 2016:

INSERT INTO Table ([Field1],[Field2]) Values('val1','val2');

**Comment by fredagstaco** [comment]
Changing line 117 to: $ColumnNames = "[" + ($PropertyNames -join "], [") + "]"

gives the correct syntax for MS SQL server.

**Comment by dfinke** [comment]
@MMitsialis, @fredagstaco 

If a switch is added `-UseMSSQLSyntax`, is that name accurate so either format for the `$ColumnNames` can be applied?

**Comment by dfinke** [comment]
Added switch https://github.com/dfinke/ImportExcel/commit/b2a884e7f1ab78acd2bd18a2b33e57fc1489ae89
