### ISSUE TITLE
Pivot Table Corrupts Excel File

### ISSUE THREAD

**Issue by SapsHaven** [dfinke/ImportExcel#249]
Hello,
I have a simple excel file named t.xsls, which I've attached.  It has just two columns, A and B, in a single sheet named NSD.

I am using importexcel version 4.0.4 and Excel 2013.

I attempt to create a pivot table using:
Export-Excel -path .\t.xlsx -WorkSheetname NSD -IncludePivotTable -PivotRows A -PivotData B

The command completes with no error.  However, when I open t.xslx with Excel I get:

![image](https://user-images.githubusercontent.com/12617722/32812188-d02c2564-c971-11e7-8446-4c915d848a20.png)

Screen snip transcribed:
We found a problem with some content in 't.xlsx'.  Do you want to try to recover as much as we can? ...

When I click yes I get:

![image](https://user-images.githubusercontent.com/12617722/32812275-2963c218-c972-11e7-98dd-548b3b8a043e.png)

The workbook cannot be opened or repaired by Microsoft Excel because it is corrupt.

What is in t.xlsx is the result of me whittling down the original data and making column names simpler.  The error occurs on two computers, Windows Server 2012 and Windows 7.

Kind of stuck...  Any assistance much appreciated!

[t.xlsx](https://github.com/dfinke/ImportExcel/files/1472972/t.xlsx)

**Comment by SapsHaven** [comment]
Let me add some more detail.  I accept a user created spreadsheet that contains some raw data in a sheet, lets call it "Raw Data".  My script reads the raw data in and uses it to create a new column.  The new column and the raw data is written out as a new sheet named "New Raw Data", in the same excel spreadsheet file.  This all works.

When I go to use Export-Excel to create a pivot table in a third tab, based on "New Raw Data", that is where I get the data corruption.

Just found out, though, that if I create the "New Raw Data" tab in a new spreadsheet file I can also create the pivot table, in the new file.

So a partial solution, and a clue.  I'd rather work within one spreadsheet file, but I can keep moving based on creating a new file.  

Please keep this issue open.

Regards....

**Comment by dfinke** [comment]
Could you post a sample set of code and xlsx?

**Comment by SapsHaven** [comment]
I posted an xlsx named "t" in my original post.  I also specified an export-excel command that will "corrupt" the xlsx file, which I'll copy here:

Export-Excel -path .\t.xlsx -WorkSheetname NSD -IncludePivotTable -PivotRows A -PivotData B

I just downloaded t.xlsx and ran the Export-Excel and it corrupts the file.

Regards...

**Comment by dfinke** [comment]
```powershell
$f = "C:\Temp\t.xlsx"
rm $f -ErrorAction Ignore

@"
Bronx	105
Bronx	10
Bronx	1
Bronx	103
Bronx	14
Bronx	4
Bronx	102
Bronx	2
Bronx	3
Bronx	6
WNY	757
WNY	10
WNY	11
WNY	726
WNY	12
WNY	11
WNY	14481
WNY	96
WNY	1
WNY	284
WNY	112
WNY	4
WNY	2
WNY	1595
WNY	9
WNY	28
Canandaigua	549
Canandaigua	7
"@ | 
    ConvertFrom-csv -Delimiter "`t" -Header "A", "B" | 
    Export-Excel $f -ClearSheet -Show -PivotRows A -PivotData B -IncludePivotChart -ChartType PieExploded3D
```

![image](https://user-images.githubusercontent.com/67258/32920049-dea446d2-caf5-11e7-8395-72cac6c95126.png)

**Comment by dfinke** [comment]
Yeah, `Export-Excel` doesn't work on data already stored in an xlsx file. You can read an existing sheet with `Import-Excel`

**Comment by SapsHaven** [comment]
Do you mean Export-Excel doesn't work on data already stored *if used to make a pivot table*?

That could be the case.  I have been for weeks able to import data from an existing xlsx file (created by a human using Excel), process it, and export it back into the same file in a new worksheet.  The file then has two tabs for two worksheets, so my user can refer back to the first tab if need be.  This is the command I used to do that:

$stationDetail | Export-Excel -AutoSize -FreezeTopRow -BoldTopRow -WorkSheetname $newTabName -Path $fileData

$fileData is the name of the excel file from which I imported data.

It is when I added pivot parameters that I received the corrupted file error:

$stationDetail | Export-Excel -AutoSize -FreezeTopRow -BoldTopRow -WorkSheetname $newTabName -Path $fileData -IncludePivotTable -PivotRows 'Parent Facility Name' -PivotData 'Piece Count'

If I change -path to reference a new file (notice the underscore):

$stationDetail | Export-Excel -AutoSize -FreezeTopRow -BoldTopRow -WorkSheetname $newTabName -Path "_"$fileData"" -IncludePivotTable -PivotRows 'Parent Facility Name' -PivotData 'Piece Count'

Then the export command works!

**Comment by dfinke** [comment]
Yes that's what I mean. 

I believe that the underlying DLL used, corrupts the xlsx if you add a pivot table to an existing xlsx.

I tried unsuccessfully to track it down. So I typically create a new file when I include pivot tables.
