### ISSUE TITLE
Feature Request - Pivot Tables - Count of...

### ISSUE THREAD

**Issue by Zuldan** [dfinke/ImportExcel#25]
Doug,  thank you for a wonderful module. I've got it working perfectly in our environment. Automated Excel reports with pivot tables are being email to the boss everyday :) I have 1 small feature request 
though. 

Add -PivotDataCount

For example...

Get-Process | Export-Excel .\Test.xlsx -WorkSheetname ProcessList -IncludePivotTable -PivotRows ProcessName -PivotDataCount ProcessName 

This parameter should count the values in ProcessName which would give you a broken down view of how many times a process is running.

In Excel, by default, when you drag a column down into the "Values" area, it does the count automatically.

I thought of using a Group-Object before passing the object to Export-Excel but then all the raw data is stripped out and I can't manipulate the pivot table nicely in Excel.

**Comment by dfinke** [comment]
Great feature request! I've got the following which is working. One concern is discoverability for the type of calculation for each field in PivotData.

```powershell
$p=@{
    Path="c:\temp\TestExport.xlsx"
    WorkSheetname='ProcessList'
    PivotRows='Company'
    PivotData='Name' # Defaults to Count
    #PivotData=@{Handles='Sum'} # Does a Sum
    #PivotData=@{Name='Count'; Handles='Sum'} # Does both
    IncludePivotTable=$true
    IncludePivotChart=$true
}

Get-Process | Export-Excel -Show @p 
```

**Comment by Zuldan** [comment]
Fantastic! Can't wait to get the new version. 

Hash tables might be the only way to go to give you that flexability or you could do something like...

Add-ExcelPivotData -Row Company -Data Name -Action Count -List $MyPivotData

$p={
    Path="C:\temp\TestExport.xlsx
    WorksheetName='ProcessList'
    PivotList=$MyPivotData
    IncludePivotTable=$true
}

Get-Process | Export-Excel -Show @p

**Comment by dfinke** [comment]
Yes, I like that. I've work up a couple of those variations. Then this starts to become a domain specific vocabulary/language (DSV/DSL). Which I totally like. Just haven't thought through how much this module would need to change if that direction takes hold.

**Comment by zippy1981** [comment]
Doug, do you think an Enum in EPPlus for all the Pivot values would make sense? If you can propose an enum and new overloads for the Pivot API that benefit your module, I'll see about getting them merged in.

**Comment by dfinke** [comment]
Thanks Justin, I think I saw an Enum for these in EPPlus.

**Comment by Zuldan** [comment]
-> "Great feature request! I've been working on the following (which is generating good results)."

Doug is there any chance you could push that working version you have to a "dev" branch? Any sort of working version would be great for the reports we're generating.

**Comment by dfinke** [comment]
Thanks for the nudge. Let me see what I can do over the next few days.

**Comment by Zuldan** [comment]
Fantastic!

**Comment by dfinke** [comment]
Check in the update. Let me know how it goes.

**Comment by Zuldan** [comment]
Doug it works perfectly! Mega reports here we come! You are brilliant.
