### ISSUE TITLE
Is it Possible to Add a Filter for a Pivot Table?

### ISSUE THREAD

**Issue by mrentropy** [dfinke/ImportExcel#251]
Hi Doug, is there any way to create a a filter for a pivot table? If not, this would be a wonderful feature to add.

Get-Process | Export-Excel .\test.xlsx -WorkSheetname Processes -IncludePivotTable -Show  -PivotRows Company -PivotData PM

![pivotquestion](https://user-images.githubusercontent.com/940688/32852823-01f5bf5c-c9ee-11e7-9cde-2e4392354a16.jpg)

Thank you for creating this amazing utility!

Cheers, Carl

**Comment by dfinke** [comment]
Looks like this version of EPPlus does not support that. I'm looking to move to a new version of EPPlus and will investigate this when I do.
