### ISSUE TITLE
How to color exact cell, row or column?

### ISSUE THREAD

**Issue by Genrymoney** [dfinke/ImportExcel#252]
This works only for top row.. 

```
Get-Process | Select-Object Company,Handles,PM, NPM| Export-Excel -now -BoldTopRow -AutoSize -CellStyleSB {
        param(
            $workSheet,
            $totalRows,
            $lastColumn
        )
       Set-CellStyle $workSheet 1 $LastColumn Solid Green
}

```

**Comment by dfinke** [comment]
`Set-CellStyle` is not designed for that, yet.

Have a look at this, let me know if it helps.

https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L301

**Comment by dfinke** [comment]
Check out the new `Set-Format` https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L301
