### ISSUE TITLE
Unreadable content when formulas are imported

### ISSUE THREAD

**Issue by urbantom** [dfinke/ImportExcel#253]
I'd like to thank you for the module development at the first place.
It's a grate and day saving solution.

Now, let's try to modify the ExcelFunctions.ps1 example that is distributed with ImportExcel module.

```
. .\New-PSItem.ps1

rm *.xlsx

$(
    New-PSItem abc rara "Mad Max" "m.max@acme.com" (echo app dmn am e-mail)
    New-PSItem def ghrr "Forest Gump" "f.gump@acme.com" 
    New-PSItem ghi rara "Baby Boss" "b.boss@acme.com" 
    New-PSItem jkl hello "Power Tower" "p.tower@acme.com" 
    New-PSItem mno ghrr "Iron Man" "i.man@acme.com" 
    New-PSItem pqr hello "Master O'Disaster" "m.odisaster@acme.com" 
) | Export-Excel functions.xlsx -AutoSize -WorkSheetname 'LookUp' -TableName 'LookUpTbl'


$(
    New-PSItem ghi `
               "=VLOOKUP([@[app]];LookUpTbl[[app]:[e-mail]];2;FALSE)" `
               High `
               '=IFNA(IF([@[cs]]="High";3;IF([@[cs]]="Medium";2;IF([@[cs]]="Low";1;0)));#N/A)' `
               Live `
               '=IFNA(IF([@[us]]="Live";3;IF([@[us]]="On-demand";2;IF([@[us]]="Archive";1;0)));#N/A)' `
               '=IFNA(IF(SUM([@[csv]];[@[usv]])>0;SUM([@[csv]];[@[usv]])-1;"");5)' `
               (echo app dmn cs csv us usv cqc)
    New-PSItem def `
               "=VLOOKUP([@[app]];LookUpTbl[[app]:[e-mail]];2;FALSE)" `
               High `
               '=IFNA(IF([@[cs]]="High";3;IF([@[cs]]="Medium";2;IF([@[cs]]="Low";1;0)));#N/A)' `
               Archive `
               '=IFNA(IF([@[us]]="Live";3;IF([@[us]]="On-demand";2;IF([@[us]]="Archive";1;0)));#N/A)' `
               '=IFNA(IF(SUM([@[csv]];[@[usv]])>0;SUM([@[csv]];[@[usv]])-1;"");5)' `
               (echo app dmn cs csv us usv cqc) 
    New-PSItem abc `
               "=VLOOKUP([@[app]];LookUpTbl[[app]:[e-mail]];2;FALSE)" `
               Low `
               '=IFNA(IF([@[cs]]="High";3;IF([@[cs]]="Medium";2;IF([@[cs]]="Low";1;0)));#N/A)' `
               Live `
               '=IFNA(IF([@[us]]="Live";3;IF([@[us]]="On-demand";2;IF([@[us]]="Archive";1;0)));#N/A)' `
               '=IFNA(IF(SUM([@[csv]];[@[usv]])>0;SUM([@[csv]];[@[usv]])-1;"");5)' `
               (echo app dmn cs csv us usv cqc) 
    New-PSItem pqr `
               "=VLOOKUP([@[app]];LookUpTbl[[app]:[e-mail]];2;FALSE)" `
               Medium `
               '=IFNA(IF([@[cs]]="High";3;IF([@[cs]]="Medium";2;IF([@[cs]]="Low";1;0)));#N/A)' `
               On-demand `
               '=IFNA(IF([@[us]]="Live";3;IF([@[us]]="On-demand";2;IF([@[us]]="Archive";1;0)));#N/A)' `
               '=IFNA(IF(SUM([@[csv]];[@[usv]])>0;SUM([@[csv]];[@[usv]])-1;"");5)' `
               (echo app dmn cs csv us usv cqc) 
    New-PSItem mno `
               "=VLOOKUP([@[app]];LookUpTbl[[app]:[e-mail]];2;FALSE)" `
               High `
               '=IFNA(IF([@[cs]]="High";3;IF([@[cs]]="Medium";2;IF([@[cs]]="Low";1;0)));#N/A)' `
               On-demand `
               '=IFNA(IF([@[us]]="Live";3;IF([@[us]]="On-demand";2;IF([@[us]]="Archive";1;0)));#N/A)' `
               '=IFNA(IF(SUM([@[csv]];[@[usv]])>0;SUM([@[csv]];[@[usv]])-1;"");5)' `
               (echo app dmn cs csv us usv cqc) 
    New-PSItem ghi `
               "=VLOOKUP([@[app]];LookUpTbl[[app]:[e-mail]];2;FALSE)" `
               Medium `
               '=IFNA(IF([@[cs]]="High";3;IF([@[cs]]="Medium";2;IF([@[cs]]="Low";1;0)));#N/A)' `
               Live `
               '=IFNA(IF([@[us]]="Live";3;IF([@[us]]="On-demand";2;IF([@[us]]="Archive";1;0)));#N/A)' `
               '=IFNA(IF(SUM([@[csv]];[@[usv]])>0;SUM([@[csv]];[@[usv]])-1;"");5)' `
               (echo app dmn cs csv us usv cqc) 
) | Export-Excel functions.xlsx -WorkSheetname 'Src' -TableName 'SrcTbl' -AutoSize -Show
```

When we run this script it produces _functions.xlsx_ file.
When we try to open the file three unexpected issues appear:
1. Message is displayed
![image](https://user-images.githubusercontent.com/22394408/33010497-00947b76-cddb-11e7-88af-ae97a6b5625a.png)
2. Message is displayed
![image](https://user-images.githubusercontent.com/22394408/33010585-4a4efc78-cddb-11e7-83a9-c5ae735533de.png)
3. All the columns that are expected to contain formulas have empty content

**Comment by dfinke** [comment]
Ok, I'm not an expert in Excel formulas :)

I created the attached, the `LookUp` sheet `LookUpTbl` from PS. 

Then created the `Src` sheet manually and pasted in the formula. It did not error but it did not do the lookup.

[functions.xlsx](https://github.com/dfinke/ImportExcel/files/1488269/functions.xlsx)

**Comment by urbantom** [comment]
Thanks for your prompt help.

I'm not going to pretend I'm an Excel formula expert, but I think that it is required to create a table 'SrcTbl' for structured references to work properly.

On the other hand 'my' script creates an Excel file in any case.

One may copy/paste formulas from the script in the created Excel file.

**Comment by dfinke** [comment]
I guess my point is, let's make this a simple working example.

Can you use the xlsx I sent and create a formula manually in the src sheet that returns data?

If so, post that and then I can look at the formula and work towards an automated solution.

**Comment by urbantom** [comment]
NP.
Here is a procedure I've followed:
1. Your Excel file downloaded and renamed
2. Command 'Format as Table' run for the 'Src' worksheet w/ the option 'My table has headers' checked
3. Content of the cell A2 cut
4. Cell A2 filled w/ 'ghi' value (accordingly to the script line 16)
5. Previous content of the A2 cell pasted into B2
Attached result:  
[functions_DFN.xlsx](https://github.com/dfinke/ImportExcel/files/1488395/functions_DFN.xlsx)

**Comment by dfinke** [comment]
Thanks, I'll take a look

**Comment by urbantom** [comment]
Thank you so much. :-)
