### ISSUE TITLE
Revisit Copy-ExcelWorkSheet

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#255]
`Copy-ExcelWorkSheet` makes the incorrect assumption about the layout of the data. Needs to copy all cells.

**Comment by JediBrown** [comment]
Any suggested work around until resolved?

**Comment by dfinke** [comment]
Copy Excel worksheet works with tabular data. Off the top of my head, you'd need to start with -passthru and handle all cells that way.
