### ISSUE TITLE
[Question] Creating Combo-Drop Down Boxes

### ISSUE THREAD

**Issue by forensicsguy20012004** [dfinke/ImportExcel#256]
It seems like a long time since I have been to this project :)

Wondering if there is anyway currently to generate a combo-drop down box based on data in another worksheet? If that is possible I could go about driving conditional logic off the selection? Maybe, maybe not either way, thought I would ask.

**Comment by dfinke** [comment]
Good question, I have not done any investigation into exposing UI controls. The first place to look to see if this is a non-starter is in the EPPlus library to see if it is supported

**Comment by jgreenephd** [comment]
Here's an example:
`$report = Import-Excel .\$file | Export-Excel $file -PassThru`
`$ws=$report.Workbook.Worksheets["Sheet1"]`
`$ws.cells["A1"].value=""`
`$dv=$ws.DataValidations.AddListValidation("A1")`
$dv.Formula.ExcelFormula="='Data Validation'!`$A`$1:`$A`$3"

**Comment by forensicsguy20012004** [comment]
Excellent.. @jgreenephd  let me play around.
