### ISSUE TITLE
EPPlus Add Worksheet with Latest Version of Office Losses All Macros

### ISSUE THREAD

**Issue by jgreenephd** [dfinke/ImportExcel#257]
Hello, can you update import-excel to utilize the EPPlus fix by Jan Kallman in release [4.1.1](https://github.com/JanKallman/EPPlus/blob/master/EPPlus/readme.txt)? 

[Here's the problem link](https://stackoverflow.com/questions/46353473/epplus-add-worksheet-with-latest-version-of-office-losses-all-macros?noredirect=1#comment79667137_46353473)

**Comment by dfinke** [comment]
While I research, if you want, you can replace the dll where `ImportExcel` is installed and give it a try.

**Comment by jgreenephd** [comment]
I replaced the EPPlus.dll in the ImportExcel directory and that did the trick.  Thanks.
