### ISSUE TITLE
Is it possible to apply conditional formatting for columns greater than or equal to another columns value?﻿

### ISSUE THREAD

**Issue by aleoyakas** [dfinke/ImportExcel#259]
I have an excel with a "Used" column and a "Total" column. Ideally, I would like to apply conditional formatting (Turning the row red) whenever the value in the "Used" column reaches 90% of the value of the "Total" column. For now, I would be happy with having the row turn red when the value in the "Used" column is greater than or equal to the value in the "Total" column. Is this possible?

**Comment by dfinke** [comment]
@aleoyakas Do you know if this can be done in Excel itself with conditional formatting?

**Comment by aleoyakas** [comment]
@dfinke It is possible. By applying a formula, for example: $A1:$A1000 > ($B1:$B1000) * 0.9

**Comment by Poolshark314** [comment]
Add-ConditionalFormatting -WorkSheet $Excel.Workbook.Worksheets[1] -Range "B2:B500" -BackgroundColor "Red" -RuleType GreaterThan -ConditionValue "A2"

**Comment by aleoyakas** [comment]
@Poolshark314 this will add conditional formatting to the B column, and it will only highlight cells in column B if the condition is met.

Also, if any of column B are greater than the A2 cell, then the condition will be met - if B56 is less than A56, but greater than A2, the cell will still be highlighted red.

**Comment by Poolshark314** [comment]
Sorry didn't see you wanted the full row highlighted.  How about:

Add-ConditionalFormatting -WorkSheet $excel.Workbook.worksheets[1] -Range "`$A2:`$C16" -BackgroundColor "Red" -RuleType Expression -ConditionValue "=`$C2>`$B2"

My sheet then looks like this: 
![image](https://user-images.githubusercontent.com/39172225/39899523-76f741b4-548a-11e8-98a6-80142e3e4ec5.png)

and the rule:
![image](https://user-images.githubusercontent.com/39172225/39899537-8abaf876-548a-11e8-95d4-e24b2d7575a5.png)

**Comment by Poolshark314** [comment]
Also for your 90% condition:

Add-ConditionalFormatting -WorkSheet $excel.Workbook.worksheets[1] -Range "`$A2:`$C16" -BackgroundColor "Yellow" -RuleType Expression -ConditionValue "=`$C2>(`$B2*.9)"

![image](https://user-images.githubusercontent.com/39172225/39899705-7021b67a-548b-11e8-92f9-2767438998a9.png)

![image](https://user-images.githubusercontent.com/39172225/39899713-7b3d9538-548b-11e8-8362-7c359d38c797.png)
