### ISSUE TITLE
Fontsize parameter in Set-Format function is not used to set the font size

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#260]
I am liking all of the updates! Thanks!
However, there is a small problem with the new Set-Format function:
The 'Fontsize' parameter is not used to set the font size!  :)
Also, typo on this line:
$Address.Style.Font.Strike = $falsee

**Comment by dfinke** [comment]
Just a thought, do you want to do a PR to fix this? :)

**Comment by scottone** [comment]
Fixed in version 4.0.9
