### ISSUE TITLE
Typographical bugs in Set-Format function

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#262]
There are a couple of typographical bugs in Set-Format:
Line 90:     $Address.Style.Font.Strike = $falsee
Line 101:   if ($BorderRound) {$Address.Style.Border.BorderAround( $BorderAround   )    }

**Comment by robby03** [comment]
Nice find! That's why the BorderAround parameter wasn't working for me!!

**Comment by jhoneill** [comment]
"Falsee" at  line 90 in Set-format, seems to have been copied from line 163 in  formatting.ps1  

and "borderRound" seems to come from line 173  in formatting.ps1 and has been copied to 
Set-Column.ps1 - line 128 and 
Set-Row.ps1 - line 133  

I think I was the one who copied them :-(  but I'm going to let who ever is fixing this in one place make this a single fix

**Comment by dfinke** [comment]
Fixed https://github.com/dfinke/ImportExcel/commit/a5b9ddc257386924a2faa27e40fb50e79d304ad9
