### ISSUE TITLE
Formatting gets lost

### ISSUE THREAD

**Issue by bleddy3** [dfinke/ImportExcel#265]
I'm trying to simply combine the contents of several spreadsheets.  Using import-excel | export-excel gets me 90% of the way, but the formatting from the original spreadsheets is lost (fonts, borders, conditional coloring, etc.)

I've tried using the -append option to add to an existing spreadsheet that is already formatted, but the formatting does not automatically carry down.   If the existing spreadsheet has a table, the formatting get carried down if you resize the table, but I haven't discovered how to do that without resorting to COM.

Is there a way to just pull the formatting from the original spreadsheets with resorting to code to format the exported document?

**Comment by dfinke** [comment]
This only works with data.

**Comment by bleddy3** [comment]
Doug, thanks for the quick reply.
