### ISSUE TITLE
Importing enormous xlsx files

### ISSUE THREAD

**Issue by SilentBob999** [dfinke/ImportExcel#266]
Hi,
I am sorry; I do not know exactly where I should write this.

I have a file of 283000+ row that this module cannot import no matter what.
I need a way to limit the range and filter the data on the fly otherwise the memory usage is to the roof and I cannot do anything with that file within PowerShell.

Is there any way to filter the data for the Import-Excel, or pipe each row out to let PowerShell handle the filtering? The out buffer seems to have no effect. 
 The “startrow” is limited to 9999 so even if I would like only the end of the file (which I am not) it will not work.
Whatever I try, it look like it is trying to read the entire file and for some reason the memory grow over the limit of what my pc have.
The file is 40mb, excel is taking 150mb when this file is open.
Something like this that should be as small as it can be, will take 10GB+ of memory without any output (I always end up closing PowerShell because it does seem like there is light at the end of the tunnel…
$result = $files  | Import-Excel -DataOnly -OutBuffer 1 -StartRow 9999  | Select-Object -First 5  

The desired utilization would be:
$result = $files  | Import-Excel -DataOnly | where ReportDate -GT "*a specific date*" 

Thanks

**Comment by dfinke** [comment]
Not sure this module and approach can handle this.

**Comment by fumannychu** [comment]
Related question to this thread: Has anyone determined the maximum size the Import-Excel cmdlet can handle? I tried with a ~16MB XLSX file and it seems like it's never going to complete. I can import a CSV with the same data (but increases the size to ~241MB file) using Import-CSV and that is much faster. Takes less than 20 seconds. The row count in both files is ~204,000. My PC has 64GB of RAM and an 8-core i7 processor. The memory usage when using Import-Excel is about 3.5GB while the Import-CSV method uses about 1GB.
