### ISSUE TITLE
Importing two or more Excel sheets and summing data from corresponding cells

### ISSUE THREAD

**Issue by tehfonz** [dfinke/ImportExcel#267]
Trying to find the most efficient way to import multiple excel documents and have the corresponding cells from each sheet totaled per cell per device (row)

[Report-20171214080000.xlsx](https://github.com/dfinke/ImportExcel/files/1570349/Report-20171214080000.xlsx)
[Report-20171215080000.xlsx](https://github.com/dfinke/ImportExcel/files/1570350/Report-20171215080000.xlsx)
[Report-20171218080016.xlsx](https://github.com/dfinke/ImportExcel/files/1570351/Report-20171218080016.xlsx)

From each of the attached, I am looking at totaling the B/W Pages cell from each Device from each sheet.

So Device1's B/W Cells should total 568
Device2's B/W? Cells should total 604
and so on for each column and each device, obviously only adding cells where the 'Device - name' match.

Hopefully, this makes sense.

Cheers!

**Comment by dfinke** [comment]
Here's a way to put all the data into a single PowerShell array. From there, you can operate on it in many ways.


```powershell
$(foreach($file in (echo .\Report-20171214080000.xlsx .\Report-20171215080000.xlsx .\Report-20171218080016.xlsx)) {        
        Import-Excel -WorksheetName 'YSoft SafeQ Report' $file -StartRow 4 | 
            ? {$_.'Device - name'} |
            Add-Member -PassThru -MemberType NoteProperty -Name FileName -Value $File
    }) | ogv
```

**Comment by tehfonz** [comment]
Awesome got that working with a few tweaks to suit my environment. Thanks for that!
