### ISSUE TITLE
Can't Add Fields With A Space In The Name To Pivot Table

### ISSUE THREAD

**Issue by JoshuaBarnette** [dfinke/ImportExcel#268]
I have tried using -PivotRows and -PivotColumns.

Also -PivotDataToColumns changes the column order, it would be nice if this would stay.

Other Features that would be helpful, configuring pivot filters, grouping for pivot rows/columns and pivot sorting.

The function is awesome without this, but this could be a huge improvement.

**Comment by dfinke** [comment]
Please post an example
