### ISSUE TITLE
export-excel [float issue] - 5,05 = 5,050000191

### ISSUE THREAD

**Issue by chada090** [dfinke/ImportExcel#272]
Hello, can someone explain this?
Thank you.
$array = @()
$a = New-Object -TypeName PSObject -Property @{a=1;b=2;c=3}
$array += $a
[float]$lol = "5.05"
$a = New-Object -TypeName PSObject -Property @{a=4;b=5.05;c=$lol}
$array += $a
$array
$array | Export-Excel -now

**Comment by dfinke** [comment]
I have Excel 2016, where do you see the extras decimals?

![image](https://user-images.githubusercontent.com/67258/34323736-812236b6-e825-11e7-8990-357a1a86472f.png)

**Comment by chada090** [comment]
thanks for reply.
Can you please make "c" column wider?
Number is show up correctly, when opened, but you cant see it in low above.
![image](https://user-images.githubusercontent.com/34800973/34325644-cffdbad6-e897-11e7-8a64-7dfa2b9c3204.png)

**Comment by dfinke** [comment]
Hmm, wondering if it is the culture setting on your machine.

![image](https://user-images.githubusercontent.com/67258/34327337-856f8830-e88f-11e7-993f-f652fe2f85f0.png)

**Comment by chada090** [comment]
I will try ti change my cunture settings, nice guess. I will let you know the result.
Anyway merry Christmass!

**Comment by dfinke** [comment]
cool, let me know. Merry Christmas

**Comment by chada090** [comment]
I tried to change culture settings to "english (U.S), relust the same .. :(
![image](https://user-images.githubusercontent.com/34800973/34338691-8dece34a-e96b-11e7-9b97-4fbcc6b5d335.png)

**Comment by dfinke** [comment]
Hmm, what version of Excel?

**Comment by chada090** [comment]
Version 16, I didn't reach my desktop yet. It's the same in libre office. I would understand another rounding, but there are extra decimal values, somehow. I tried to set export only on 2 decimals, but it did things like 1,00, but 5.05 by var $lol was still on 6 decimal places. Sorry for my english.

**Comment by dfinke** [comment]
No problem, your English is good. What if you do this, remove the quotes.

`[float]$lol=5.05`

**Comment by chada090** [comment]
same result :( 
btw this is how this code looks like : 
$array = @()
$a = New-Object -TypeName PSObject -Property @{a=1;b=2;c=3}
$array += $a
[float]$lol = 5.05
$a = New-Object -TypeName PSObject -Property @{a=4;b=5.05;c=$lol}
$array += $a
$array
$array | Export-Excel **-numberformat "0.00"** -now

![image](https://user-images.githubusercontent.com/34800973/34341455-3f4fbc80-e998-11e7-85b5-7b18ab1d4eb6.png)

**Comment by dfinke** [comment]
Thanks for trying these, what if you cast it to `[double]`?

**Comment by chada090** [comment]
Nice, it works this way... it should work for my case ( this was just an easy example how to describe my issue). I just wonder why float makes this issue 😕 and only for me ( still have no luck to reach desktop in home)
Thank you very much for your help. Enjoy holidalys! :) 👍 
![image](https://user-images.githubusercontent.com/34800973/34341705-56534050-e99d-11e7-920a-f8f568efd2b7.png)

**Comment by dfinke** [comment]
Good question, may be tough to track down because I cannot reproduce that with my setup.

**Comment by chada090** [comment]
Sure, I have problem with subtraction some numbers with double/single, but [decimal] works great for me.
Thank you one more time, happy new year!
