### ISSUE TITLE
Option to hide PivotTable Grand Total row

### ISSUE THREAD

**Issue by jameseholt** [dfinke/ImportExcel#273]
At times the Grand Total row of a PivotTable is downright misleading - if you've set the Value Field Settings to "Average" (in Export-Excel you'd do this using -PivotData @{MyCol='average'}) Excel shows the Average of all your values in the Grand Total row - so not a grand total at all!  

So I often like to hide this row entirely.  If you're doing excel automation in PowerShell without good old Export-Excel you do it this way:
$WS1.PivotTables("Tables1").ColumnGrand = $false

Would be great if a switch could be provided to do the same via Export-Excel

**Comment by dfinke** [comment]
It looks possible `$pivotTable.RowGrandTotals = $false`.

Question, what would the name the switch be, `$NoTotalsInPivot`?

**Comment by jameseholt** [comment]
$NoTotalsInPivot would be perfect!
