### ISSUE TITLE
Set-format BorderAround 

### ISSUE THREAD

**Issue by robby03** [dfinke/ImportExcel#276]
Can you provide an example on how to user set-format -BorderAround? I'm not able to make it work.

**Comment by dfinke** [comment]
@jhoneill Is there an example for this in the help or somewhere?

**Comment by robby03** [comment]
I tried to look through the help files and also your youtube videos. BTW great job on the videos and the PS module! Unfortunately, I was not able to find an example with the parameter BorderAround. Basically, nothing happens when the parameter is set let's say to: -BorderAround Thick 
With Set-Format i can change the width, font color etc but -BorderAround parameter doesn't seem to have any effect.

**Comment by robby03** [comment]
Please see post #262 regarding the typo
Line 90: $Address.Style.Font.Strike = **$falsee**   -extra "e"
Line 101: if ($**BorderRound**) {$Address.Style.Border.BorderAround( $BorderAround )    } -missing "A"
Once I updated the Set-Format function the -BorderAround parameter works. Could you please update the next version of the module?

**Comment by dfinke** [comment]
Thanks for tracking that down. Let me know if you'd like to try and do a pull request with that fix.

**Comment by jhoneill** [comment]
This error has been propagated to multiple files. I think it was in formatting.ps1 originally, and I duplicated it into set-format , set-row and Set-Column. 

I'm assuming someone else is fixing it, so please fix in all places but if you'd like me to fix, and do the  pull request, just say. (All I'll update the  examples to show a working version!) 

J

**Comment by dfinke** [comment]
Fixed https://github.com/dfinke/ImportExcel/commit/a5b9ddc257386924a2faa27e40fb50e79d304ad9
