### ISSUE TITLE
Is it possible to read the formulas instead of cells values ?

### ISSUE THREAD

**Issue by LoTheGeek** [dfinke/ImportExcel#277]
Hi 

Thanks for  your job. 

I would like to know if it is possible to read formulas inside cells instead of their values ? 
My goal is to create a new excel file reading another one as a template, but I don't want to lose the formulas. 

Best Regards

**Comment by dfinke** [comment]
Could you post an Excel sheet of before and after for what you're thinking.

Thanks

**Comment by LoTheGeek** [comment]
Please find below an exemple of the behaviour : 
I try to copy a worksheet from on excel document (source.xlsx) to a new document (target.xlsx)
In the source document the cell in the column D contains a formula 

Titre | Value1| Value2 | Total
A      | 50       | 1          | =C2+B2
B      | 30       | 2          | =C3+B3

the command to generate the new file is : 
`Copy-ExcelWorkSheet -SourceWorkbook "C:\test\Source.xlsx" -SourceWorkSheet "Donnees" -DestinationWorkSheet "Donnees" -DestinationWorkbook 'C:\test\target.xlsx'`
the result is 
Titre | Value1| Value2 | Total
A      | 50       | 1          | 51
B      | 30       | 2          | 52

as you see formulas are not present in the excel file

Both files are included 

[target.xlsx](https://github.com/dfinke/ImportExcel/files/1656164/target.xlsx)
[Source.xlsx](https://github.com/dfinke/ImportExcel/files/1656165/Source.xlsx)
