### ISSUE TITLE
Conditional Date Formatting  

### ISSUE THREAD

**Issue by PoshCodeMan** [dfinke/ImportExcel#278]
Hi 

I am trying to format dates older than  5 years:

$max_age = "-60" #months
$curr_date = Get-Date
$Max_date = $curr_date.AddMonths($max_age)

$Condtion1 = (New-ConditionalText  AMD  -Range C:C -ConditionalTextColor Black Green)
$Condtion2 = (New-ConditionalText  Intel -Range  C:C -ConditionalTextColor White Black)
$Condtion3 = (New-ConditionalText  Intel -Range  D:D -ConditionalType LessThan $Max_date)

$HardwareReport.CPU | `
  Export-Excel $xlfile  -WorkSheetname 'CPU-BiosDates'  `
    -ConditionalText $Condtion1 , $Condtion2 , $Condtion3 

when I execute the above i get this error

New-ConditionalText : Cannot process argument transformation on parameter 'ConditionalTextColor'. Cannot convert value "1/22/2013 10:12:47 AM" to type "System.Drawing.Color". Error: "Invalid cast 
from 'System.DateTime' to 'System.Drawing.Color'."
At line:21 char:80
+ ... nditionalText  Intel -Range  D:D -ConditionalType LessThan $Max_date)
+                                                                ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-ConditionalText], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-ConditionalText

**Comment by PoshCodeMan** [comment]
I removed Intel from $Condtion3 and now it is not formatting any of the fields in the worksheet

**Comment by ili101** [comment]
This works
``` PowerShell
$max_age = "-60" #months
$curr_date = Get-Date
$Max_date = $curr_date.AddMonths($max_age)
$Epoch_Date = ($Max_date - (Get-Date -Date '1/1/1900')).Days+2

$Condtion1 = (New-ConditionalText -Text AMD -Range C:C -ConditionalTextColor Black Green)
$Condtion2 = (New-ConditionalText -Text Intel -Range C:C -ConditionalTextColor White Black)
$Condtion3 = (New-ConditionalText -Text $Epoch_Date -Range D:D -ConditionalType LessThan)

$fakeData | Export-Excel $xlfile -WorkSheetname 'CPU-BiosDates' -ConditionalText $Condtion1,$Condtion2,$Condtion3
```
