### ISSUE TITLE
AutoSize not working on dates

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#28]
Thank you Doug, this is really a wonderfull function!

```
$File = 'C:\test.xlsx' 
1..10 | ForEach-Object {
    [PSCustomObject]@{
        Name = "John $_"
        FamilyName = 'Looooooooooooooooooooooooooooooooooooooooooooooooooong name'
        Date = Get-Date
    }
} | Export-Excel -Path $File -WorkSheetname 'My sheet' -AutoSize
```

If you try this you'll see that the date is shown as '##########', all other fields are properly fitted.

**Comment by dfinke** [comment]
Thank you. I've seen that and have not come up with a workable answer yet.

**Comment by DarkLite1** [comment]
No problem, thank you for the hard work already. Really love this function! :)
