### ISSUE TITLE
Bigger xlsx sizes means slower returns on Updated Modules

### ISSUE THREAD

**Issue by prisoner107** [dfinke/ImportExcel#280]
Currently still using Module v. 3.0.1 since updating to any higher version seems to slow down the "Import-Excel" function. 
I use several Large files (local stored on C:\drive), at least over 28,000 rows each. If I try to Import the data on  .xlsx sheet, using the newer 4.0.9 Module, if I use Import-Excel to return data it takes at least 1 min and 35 sec. Compared with Module version 3.0.1, using Import-Excel takes less than 5 sec.
Any idea why?
Again, not trying to single out 4.0.9, have seen this on any higher than 3.0

**Comment by dfinke** [comment]
Thanks for posting the issue. Yes, there were changes to `Import-Excel` to do additional checks which impacted performance. I'm still reviewing how best to fix this.

Thank you
Doug

**Comment by DarkLite1** [comment]
I'm sorry about this speed drop, but it's like Doug said, a lot of things are happening in the background. From version 3.0 onwards we don't just pipe data through the function. It's collected first. If we can find a way to do it all in the pipeline, that would be great... Still thinking about this...

**Comment by prisoner107** [comment]
That makes sense. I appreciate your efforts.

Thanks,
Erick Lopez

**Comment by prisoner107** [comment]
Performance is back on Import-excel with v5.0. I can safely update the module now. Yeah!! Thanks.
