### ISSUE TITLE
Export-Excel Transpose data on export

### ISSUE THREAD

**Issue by sonnyjrob** [dfinke/ImportExcel#282]
Hello,

I'm working with a simple export that consists of a small amount of data.  In Excel, I can take the row headers and the rows and transpose them.  Is it possible to do this programmatically when I send the data to Export-Excel?

Thanks,
Sonny

**Comment by dfinke** [comment]
Could you please post a the data, and an Excel file showing what you'd like to see it as?

**Comment by sonnyjrob** [comment]
Sure thing.  In the example provided I have a data set with values in each column under the headers.  After transposing the data I have the headers in Column A and the values (records) are arranged column by column.

I hope that makes sense.  Here is a site that discusses the transpose process https://support.office.com/en-us/article/transpose-rotate-data-from-rows-to-columns-or-vice-versa-3419f2e3-beab-4318-aae5-d0f862209744

Thanks,
Sonny
[Export-Execl-Transpose.xlsx](https://github.com/dfinke/ImportExcel/files/1697234/Export-Execl-Transpose.xlsx)

**Comment by PrzemyslawKlys** [comment]
Following code does this:

```
function Format-TransposeTable {
    [CmdletBinding()]
    param (
        [Parameter(
            Position = 0,
            Mandatory = $true,
            ValueFromPipeline = $true,
            ValueFromPipelineByPropertyName = $true
        )] [object[]]$Object
    )
    begin { $i = 0; }

    process {
        foreach ($myObject in $Object) {
            if ($myObject.GetType().Name -eq 'hashtable' -or $myObject.GetType().Name -eq 'OrderedDictionary') {
                Write-Verbose "Format-TransposeTable - Converting HashTable/OrderedDictionary to PSCustomObject - $($myObject.GetType().Name)"
                $output = New-Object -TypeName PsObject;
                Add-Member -InputObject $output -MemberType ScriptMethod -Name AddNote -Value {
                    Add-Member -InputObject $this -MemberType NoteProperty -Name $args[0] -Value $args[1];
                };
                $myObject.Keys | Sort-Object | % {
                    $output.AddNote($_, $myObject.$_);
                }
                $output;
            } else {
                Write-Verbose "Format-TransposeTable - Converting PSCustomObject to HashTable/OrderedDictionary - $($myObject.GetType().Name)"
                # Write-Warning "Index $i is not of type [hashtable]";
                $output = [ordered] @{};
                $myObject | Get-Member -MemberType *Property | % {
                    $output.($_.name) = $myObject.($_.name);
                }
                $output

            }
            $i += 1;
        }
    }
}
```

You can apply it before you put it to Export-Excel. I've put that function in https://github.com/dfinke/ImportExcel/pull/412 and if time will allow (and @dfinke will approve) it would be possible to add switch -TransposeTable and it would automatically do that lifting for you.

**Comment by PrzemyslawKlys** [comment]
I've actually added that in my last commit.
