### ISSUE TITLE
Spelling error Export-Excel -ExcelPackage description

### ISSUE THREAD

**Issue by hmiller10** [dfinke/ImportExcel#285]
An object representing an Excel Package - usually this is returned by specifying -Passthru alllowing multiple commands to work on the same Workbook without saving and reloading each time.

The word allowing has one to many 'L's in it.

**Comment by dfinke** [comment]
Thanks. Would you like to try and do a pull request and fix that?

**Comment by hmiller10** [comment]
Hi,

 

I am not that familiar with how to use Github and actually work on issues reported. 

 

With some guidance I would be willing to learn.  Do you happen to have any instructions I could follow? If not, it’s such a minor thing that it could potentially wait until someone with more experience has some time to fix it.
