### ISSUE TITLE
How do I find the list of worksheet names that is in an excel document?

### ISSUE THREAD

**Issue by hou8182** [dfinke/ImportExcel#287]
I'm working on a script to search through each excel file on our network drive and parse the contents to see if it contains a social security number pattern. I am having difficulty figuring out how to discover the worksheet names that an excel document has without manually opening it up. 

Also, is there already a way to perform a keyword or pattern match search throughout all sheets in an excel workbook? I found a few regex expressions that I am using for now.  Here is a snippet of my code if anyone can tell me how to find the sheet names so I can loop through them:

```
$PIIfolder = "C:\Users\Office\Desktop\PII Searcher"
(Import-Excel "$PIIfolder\Excel.xlsx" -NoHeader ) | Select-String "\b(?!000)(?!666)(?!9)[0-9]{3}[ -]?(?!00)[0-9]{2}[ -]?(?!0000)[0-9]{4}\b"
```

**Comment by dfinke** [comment]
There is `Get-ExcelSheetInfo '.\test xlsx'`  which returns the sheets in the workbook.
```
Name Index  Hidden Path
---- -----  ------ ----
test     1 Visible C:\Temp\test xlsx
```
For the match, that ought to be PowerShell native, try a simpler pattern first to make sure it works.

```powershell
$(
[pscustomobject]@{A=1;B=2}
[pscustomobject]@{A=3;B=4}
) | sls 4

@{A=3; B=4}
```
