### ISSUE TITLE
The example code for setting a title is generating an error

### ISSUE THREAD

**Issue by bigoals365** [dfinke/ImportExcel#29]
$p=@{       
    Title = "Process Report as of $(Get-Date)" 
    TitleFillPattern = "LightTrellis"
    TitleSize = 18
    TitleBold = $true

    Path  = "$pwd\testExport.xlsx"
    Show = $true
    AutoSize = $true
}

Get-Process |
    Where Company | Select Company, PM |
    Export-Excel @p

When I run this, I get this error:

ScriptHalted
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\ImportExcel.psm1:186 char:17
+                 throw $Error[0].Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

Other examples **without** titles work fine for me.

Win 8.1 Pro PS ISE 5.0.10018.0 and loaded importexcel module 1.5

**Comment by wendefeuer** [comment]
Add this to your code:in Line 1

$pwd = 'C:\<Path>'

Work fine.
.
Regards 
wolfgang

**Comment by bigoals365** [comment]
I added:

$pwd = 'C:\Dev_Local'

And it still errors.

I even changed the line

From
Path  = "$pwd\testExport.xlsx"
To
Path  = ".\testExport.xlsx"

Still gives me an error.

**Comment by wendefeuer** [comment]
upps.
I add this --- $pwd = 'C:\temp' --- in Line 1 and your code runs perfect.

**Comment by bigoals365** [comment]
Hmmm that did work !

Why did the temp directory work and not my source code directory?

**Comment by bigoals365** [comment]
Thank you Wolfgang !!!!

Could someone update the doc example?

**Comment by wendefeuer** [comment]
Did your Directory exist?

**Comment by dfinke** [comment]
This is what I get if the directory does not exist. Not sure what may have been the issue here.

![image](https://cloud.githubusercontent.com/assets/67258/8634428/0f035bae-27c6-11e5-9776-b883166ed2d2.png)

**Comment by bigoals365** [comment]
My directory did exist.

**Comment by jdhitsolutions** [comment]
There is something still wrong here. This code works just fine:
$d = 1..10
$path = "$env:temp\foo.xlsx"
if (test-path $path ) { del $path}
$d | Export-Excel -Title Test -TitleSize 14 -Show -Path $path

But as soon as I add the -TitleBackgroundcolor, I get the script halted error.

$d | Export-Excel -Title Test -TitleSize 14 -TitleBackgroundColor "Red" -Show -Path $path

ScriptHalted
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\2.2.1\Export-Excel.ps1:106 char:17
+                 throw $Error[0].Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Comment by jdhitsolutions** [comment]
I figured out the cause. If you don't set a TitleBackgroundPattern you can't set a BackgroundColor. The default value for the background pattern is None. If you change the value to something else, then it will work without error.

$d = 1..10
$path = "$env:temp\foo.xlsx"
if (test-path $path ) { del $path}
$d | Export-Excel -Title Test -TitleSize 14 -TitleBackgroundColor "Aqua" -TitleFillPattern Solid -Show -Path $path -Verbose


Perhaps some form for parameter validation would help.

**Comment by dfinke** [comment]
Yeah, the function suffers from the lack of parameter validation in a few places
