### ISSUE TITLE
export-excel cannot save on PS 5.0.10586.117 

### ISSUE THREAD

**Issue by turbomcp** [dfinke/ImportExcel#290]
when trying something like this on windows 7 with ps 5.0.10586.117 
get-services|export-excel -show
i get this:
Failed exporting worksheet 'Sheet1' to 'C:\WINDOWS\system32': Exception calling "Save" with "0" argument(s): "Error saving file C:\WINDOWS\system32"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\4.0.9\Export-Excel.ps1:1000 char:13
+             throw "Failed exporting worksheet '$WorkSheetname' to '$P ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed exportin...NDOWS\system32":String) [], RuntimeException
    + FullyQualifiedErrorId : Failed exporting worksheet 'Sheet1' to 'C:\WINDOWS\system32': Exception calling "Save" with "0" argument(s): "Error saving file C:\WINDOWS\system32"

i noticed this only happens when i use -show without it its fine.
im using office proplus build 1712
any idea why?

**Comment by dfinke** [comment]
Try this 
`get-services|export-excel`

`get-services|export-excel c:\temp\ps.xlsx -show`  should work

Looks like that parametersets need to be tweaked

**Comment by turbomcp** [comment]
Thanks
without -show everything works fine(including other parameters)
with -show it blows up:)
