### ISSUE TITLE
How do I specify cells and columns?

### ISSUE THREAD

**Issue by DanteNahuel** [dfinke/ImportExcel#291]
Hi all,
I was working on a script to get a lot of remote information on servers creating several custom objects with note properties and arrays.
After I finished the script, I discovered Export to CSV didn't work because all the information would be in one column, making it impossible to use as a presentation.
I started investigating and I started using $excel = New-Object -ComObject excel.application
This worked and I got a nice excel sheet with separate tabs and colors but the main issue is that I need Excel installed and that sucked.
So I continued looking and I found this module.
It looks amazing and simple. However, I'm struggling to understand how to convert all my previous work into this.
I can't find any guide or documentation about it and right now i'm struggling to understand how can I add sheets to the same workbook or not, and how to specify where (which cells, which columns or rows) do I want specific variables or object properties values to be added in a sheet.

As an example:
In my previous script

`$excel = New-Object -ComObject excel.application <#Starts Excel#>
<#$excel.visible = $true #This shows the excel being populated on the fly. It should be activated only for debugging purpose#>
$workbook = $excel.Workbooks.Add() <#Creates a workbook#>

<#Creating and formatting first Tab#>
$diskSpacewksht= $workbook.Worksheets.Item(1) <#selects which tab to use#>
$diskSpacewksht.Name = "Disk" <#names the tab#>
$diskSpacewksht.Columns.Item("A:H").EntireColumn.Autofit() | out-null <#set columns width to be autosized#>
$diskSpacewksht.Cells.Item(1,1) = "Name" <#Property text printed on first row, first column (1,1) #>
$diskSpacewksht.Cells.Item(1,2) = "Volumne Name" <#Value text printed on the first row, second column (1,2) #>
$diskSpacewksht.Cells.Item(1,3) = "File System" <#Value text printed on the first row, second column (1,3) #>
$diskSpacewksht.Cells.Item(1,4) = "Description" <#Value text printed on the first row, second column (1,4) #>
$diskSpacewksht.Cells.Item(1,5) = "Disk Size (GB)" <#Value text printed on the first row, second column (1,5) #>
$diskSpacewksht.Cells.Item(1,6) = "Free Space (GB)" <#Value text printed on the first row, second column (1,6) #>
$diskSpacewksht.Cells.Item(1,7) = "Free %" <#Value text printed on the first row, second column (1,7) #>
$diskSpacewksht.Cells.Item(1,8) = "S/N" <#Value text printed on the first row, second column (1,8) #>
$diskSpacewksht= $workbook.Worksheets.Item(2)
write-host = "Populating Disks Sheet"
$DisksRow = 2
$DisksColumn = 1
$disk | ForEach-Object { <# Because Disk is an object with multiple noteproperties inside, I had to manually go through each noteproperty value #>
$diskpropertyName = $_.Name
$diskpropertyVolumeName = $_.volumename
$diskpropertyFileSystem = $_.filesystem
$diskpropertyDescription = $_.description
$diskpropertySize = $_."disksize(gb)"
$diskpropertyFreeSpace = $_."freespace(gb)"
$diskpropertyFreePorcentage = $_."%free"
$diskpropertySN = $_."S/N"
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertyName
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertyVolumeName
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertyFileSystem
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertyDescription
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertySize
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertyFreeSpace
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertyFreePorcentage
$DisksColumn++
$diskSpacewksht.Cells.Item($DisksRow,$DisksColumn) = $diskpropertySN
$DisksRow++
$DisksColumn = 1
}`

I can't find any way to do this in this script and i'm sure that's my ignorance.

Can you help me?

Thanks in advance.

**Comment by DanteNahuel** [comment]
Sure.
Here's a spreadsheet of that:
[Inventory_test.zip](https://github.com/dfinke/ImportExcel/files/1785699/Inventory_test.zip)

**Comment by dfinke** [comment]
Export Excel is tuned to export an object as tabular data like this. 

For the other sheet, you need to use the `-PassThru` swtich and then you can work with Cells like you do with the COM approach.

```powershell
[pscustomobject]@{
    'Name'            = 'C:'
    'Volumne Name'    = 'OSDisk'
    'File System'     = 'NTFS'
    'Description'     = 'Local Fixed Disk'
    'Disk Size (GB)'  = 165.729995727539
    'Free Space (GB)' = 80.1800003051758
    'Free %'          = 48.3800010681152
    'S/N'             = 'test'

} | Export-Excel
```

**Comment by jhoneill** [comment]
Here's how I do it : already have a PS session $s to a remote machine and I run a script block which returns an object with a lot of properties - each being an inventory attribute - the property names can have spaces in them although I don't put any in ... 

` $computerInfo = invoke-command -Session $s -HideComputerName -ScriptBlock {
    $computerInfo  =  Get-WmiObject -Class win32_computersystem  | 
            Select-Object @{n="RunAt"; e={[datetime]::now}}, Manufacturer,Model , PrimaryownerName, Domain  , 
                          @{n="NodeName";e={$_.Caption}} , 
                          @{n="Memory";e={""+[math]::Round(($_.Totalphysicalmemory/1gb),1) +"GB"}},
                          NumberOfProcessors       
    Add-Member -InputObject $computerInfo -MemberType NoteProperty -Name "NumberOfCores"  -value  (
            Get-CimInstance win32_processor | Measure-Object -Property NUMBEROFCORES -Sum  ).Sum
    Add-Member -InputObject $computerInfo -MemberType NoteProperty -Name "PSVersion"      -value  (
            "V" + $PSVersionTable.PSVersion.Major + "." + $PSVersionTable.PSVersion.Minor  
    )
    Add-Member -InputObject $computerInfo -MemberType NoteProperty -Name "OS"             -value  (
            Get-WmiObject -Class win32_operatingsystem).caption
    Add-Member -InputObject $computerInfo -MemberType NoteProperty -Name "Timezone"       -value  (tzutil.exe /g )
    Add-Member -InputObject $computerInfo -MemberType NoteProperty -Name "LocaleID"       -value  (Get-WinSystemLocale).lcid 
    Add-Member -InputObject $computerInfo -MemberType NoteProperty -Name "LocaleName"     -value  (Get-WinSystemLocale).name 
    ## etc 
    $computerInfo
} | Select-Object -Property * -ExcludeProperty PSComputerName,RunspaceId,PSShowComputerName
$excel = $computerInfo.psobject.Properties | Select-Object -Property Name,Value | Export-Excel -Path $filePath -WorkSheetname General -ClearSheet -NoHeader -Title "$name : General Settings" -FreezeTopRow -PassThru
$ws    = $Excel.Workbook.Worksheets["General"] 
$ws.Column(1).Width   = 64
$ws.Column(1).style.VerticalAlignment = "Center"
$ws.Column(2).Width   = 128
$ws.Column(2).Style.HorizontalAlignment = "left"
$ws.Column(2).Style.WrapText = $true
$Excel.save()`

The key thing is accessing  $computerInfo.psobject.Properties

**Comment by Deepaklohar275** [comment]
$excel = $computerInfo.psobject.Properties | Select-Object -Property Name,Value | Export-Excel -Path 
..... on the above line of code what i need to give inthe place of property name, value.

**Comment by Deepaklohar275** [comment]
Sorry, 
if the first comment was improper, I am new to power-shell scripting.
I want to develop a script, for copy all the data from 1st excel should be pasted on another excel. for this I am using below code.

$file1 = 'C:\Users\PC\Desktop\PowerShell\LiveAudit.xlsx' # source's fullpath 
$file2 = 'C:\Users\PC\Desktop\PowerShell\Book2.xlsx' # destination's fullpath
 
$xl = new-object -c excel.application 
$xl.displayAlerts = $false # don't prompt the user 

$wb2 = $xl.workbooks.open($file1, $null, $true) # open source, readonly 
$wb1 = $xl.workbooks.open($file2) # open target 

$sh1_wb1 = $wb1.sheets.item(1) # first sheet in destination workbook 

$sheetToCopy = $wb2.sheets.item('Computers') # source sheet to copy 


$sheetToCopy.copy($sh1_wb1) # copy source sheet to destination workbook 

$wb2.close($false) # close source workbook w/o saving 
$wb1.close($true) # close and save destination workbook 

$xl.quit() 


#Now I want to paste the data of a row into the coloum of excel sheet, so can you help me on this 
Stuck :P

**Comment by jhoneill** [comment]
Hi , I've posted a new blog post which includes how to copy a sheet from one workbook to another, and how to take and an object instead of exporting
```
Property1 | Property2 | Property3 
Value1    | Value2    | Value3 
```
It outputs
```
Property1 | Value1 
Property2 | Value2
Property3 | Value3 
```

https://jamesone111.wordpress.com/2018/05/31/more-tricks-with-powershell-and-excel/


Are you saying you want to transpose and copy - like this 
```
Name    | Property1 | Property2 | Property3 
Server1 | S1Value1  | S1Value2  | S1Value3 
Server2 | S2Value1  | S2Value2  | S2Value3 
Server3 | S1Value1  | S3Value2  | S3Value3 

```
to 
```
          | Server1   | Server2  | Server3 
Property1 | s1Value1  | s2Value1 | s3Value1  
Property2 | s1Value2  | s2Value2 | s3Value2  
Property3 | s1Value3  | s2Value3 | s3Value3  
```
That means looping _something like_ 
```
foreach ($A in 1..$old_Sheet.dimension.rows) {
     foreach ($B in 1..$old_Sheet.dimension.Columns) {
        $old_Address = [OfficeOpenXML.ExcelAddress]::translateFromR1C1("R[$A]C[$B]" 
        $new_Address = [OfficeOpenXML.ExcelAddress]::translateFromR1C1("R[$B]C[$A]"
        $new_Sheet.cells[$new_address].value =  $old_Sheet.cells[$old_address].value  
    }
}
```
_This is just a rough sample - I haven't tested it!!_
