### ISSUE TITLE
How to rename an existing worksheet?

### ISSUE THREAD

**Issue by DanteNahuel** [dfinke/ImportExcel#292]
Hi, I want to know how to rename an existing worksheet. For now I can only do this by $excel.workbook.worksheet.add("name")
But I want to rename this worksheet later on the script instead of adding a new one.

**Comment by dfinke** [comment]
This should work.

```
$xl= Open-ExcelPackage C:\testrename.xlsx
$sheet1 = $xl.Workbook.Worksheets["Sheet1"]
$sheet1.Name ="TestXL"
Close-ExcelPackage $xl
```
