### ISSUE TITLE
Send-SQLDataToExcel -Database parameter not implemented correctly?

### ISSUE THREAD

**Issue by MKPhil** [dfinke/ImportExcel#294]
Looking in Send-SQLDataToExcel.ps1 there is a section:
```powershell
#Switches to a specific database on a SQL server
[Parameter(ParameterSetName="SQLConnection")]
[switch]$DataBase,
```
and further on:
```powershell
if ($DataBase) {$Session.ChangeDatabase($DataBase) }
```

To my eyes this seems to be incorrect.  The Parameter give `$Database` a `switch` datatype (i.e. `$true`/`$false`) but subsequent code (and the comment) suggests it should reference a Database name.  

As such,neither of the below code samples work:
```powershell
Send-SQLDataToExcel -MsSQLserver -Connection "dbserver" -Database -SQL "SELECT * from tblname" -Path C:\temp\Report.xlsx

Send-SQLDataToExcel -MsSQLserver -Connection "dbserver" -Database "database" -SQL "SELECT * from tblname" -Path C:\temp\Report.xlsx
```

To resolve this I had to change the parameter definition to:
``` powershell
#Switches to a specific database on a SQL server
[Parameter(ParameterSetName="SQLConnection")]
[string]$DataBase,
```
and also add the "Database" parameter to:
````powershell
#Call export-excel with any parameters which don't relate to the SQL query
"Connection", "Session", "MsSQLserver", "Destination" , "sql" ,"Path", "Database" | foreach-object {$null = $PSBoundParameters.Remove($_) }
````

I also had to add an extra line before `ChangeDatabase` but I'm not sure if that is necessary - it could have been my environment:
```powershell
if ($Session.State -eq "Closed") {$Session.Open()}
if ($DataBase) {$Session.ChangeDatabase($DataBase) }
```

**Comment by dfinke** [comment]
@jhoneill would it be possible for you to confirm this?

**Comment by jhoneill** [comment]
I've checked this and I think changing the database on SQL server must have been added at the very last minute - it can't work as [switch] it needs to be [String] as stated above, and if it is not removed from the psBoundParameters Export-Excel will throw an error.  Sometime over this weekend I'll fire up a SQL server VM, apply the changes and test them properly. 

There's an assumption that the session is open, and if passed a closed session the code will fail. Whether the right thing to do is stick with that assumption, or catch closed sessions and either warn and return or re-open the session is something I don't have a strong view on..

**Comment by jhoneill** [comment]
Ignore the second paragraph of what I just wrote. For reasons I'm not quite clear about the first connection to SQL is open automatically but the second connection needs to be explicitly opened. That's
 why @MKPhil needed the explicit open. 
I've put all three updates into the code, done a quick check and sent a pull request 
James

**Comment by dfinke** [comment]
Thanks James, much appreciated. I'll merge those changes.

**Comment by dfinke** [comment]
fixed
