### ISSUE TITLE
How to Autosize the columns?

### ISSUE THREAD

**Issue by DanteNahuel** [dfinke/ImportExcel#295]
Hi!
Still learning about this awesome module.
I need to know how to format all the columns in a sheet to be sized according to the text inside them.
Any way to do that?

**Comment by DanteNahuel** [comment]
No :( the columns are still not autofitting

**Comment by dfinke** [comment]
Can you please post the Powershell you are using and the xlsx file. Thank you

**Comment by DanteNahuel** [comment]
Sure,
although I've checked and it seems the -autosize you share with me works only for the first tab.

**Comment by dfinke** [comment]
`-Autosize` works on the sheet being export to

**Comment by hossamaladdin** [comment]
I also tried this parameter and it doesn't resize the columns
