### ISSUE TITLE
new feature: Export ALL Excel worksheets to CSV file at once

### ISSUE THREAD

**Issue by DaniSQL** [dfinke/ImportExcel#297]
Currently Import-Excel has the option to read data from specific worksheet. It would be useful if there is an option to get the data from all worksheets at once (may be using -ALL switch or ALL parameter name??). One scenario I have is exporting all worksheets to CSV file (Here is my current implementation ... [https://gist.github.com/DaniSQL/3c6f0baab62c83256a8c89a1013beb6c](https://gist.github.com/DaniSQL/3c6f0baab62c83256a8c89a1013beb6c) )

If this functionality existed in Import-Excel, then it would have be possible to pipe it to Export-Csv and no need to write the above code linked in the gist(looping through each worksheet and then piping).

Or may be we it is better to consider a separate command to export ALL excel worksheets to CSV files in a single folder? Thanks!

**Comment by dfinke** [comment]
Thanks for setting this up
