### ISSUE TITLE
Extract Specific Sheet into a New Spreadsheet

### ISSUE THREAD

**Issue by mmoo9154** [dfinke/ImportExcel#299]
I'm sure this is stupid simple, but I do not see how to do it from the help or the web page.  D'oh!

What is the proper incantation to extract a particular sheet named "My Special Sheet" from xxx.xlsx to a new yyy.xlsx?

Ideally would extract the values and formatting (not the formulas) because the formulas will reference other sheets internal to xxx.xlsx.

**Comment by dfinke** [comment]
This module is designed to work with tabular data. You can work with other shapes, but that requires more work from you. It does not preserve formatting. 

[testItems.xlsx](https://github.com/dfinke/ImportExcel/files/1813239/testItems.xlsx)

```powershell
Import-Excel C:\Temp\testItems.xlsx -WorksheetName Sheet1| Export-Excel c:\temp\abc.xlsx -show
```

**Comment by mmoo9154** [comment]
That was what I needed.  I hadn't grasped that form the docs.  I added a -NoHeader to both sides and it's working like a charm.  Thanks!
