### ISSUE TITLE
Unresolved Paths

### ISSUE THREAD

**Issue by josheinstein** [dfinke/ImportExcel#3]
Looks great. I've taken several cheap shots at this over the years and every one of them felt hacky. (My favorite hack was using ConvertTo-Html and making Excel open it as a spreadsheet!). Happy to have something that reads/writes .xlsx natively.

Noticed right off the bat though that it doesn't like unresolved PS paths like ~\Desktop\Spreadsheet.xlsx as it's passing it to the managed code directly. If I figure out how to contribute (I am a Git noob) I can fix and do a pull request.

**Comment by dfinke** [comment]
Thanks for the PR. Where have you been? Did you write a book?

**Comment by josheinstein** [comment]
No problem. Glad I could figure it out. :)

I did write a book, yeah. @dultery. It's a memoir about a pretty
life-changing situation. I wound up dumping my personal social network
accounts because I was getting a lot of requests from
well-meaning strangers that feel like they've known me forever.

How have you been?

**Comment by dfinke** [comment]
Thought that was your book, but wasn't 100%. Yeah, the internet is an interesting place.

I'm doing OK.

Looking forward to see you back what you come up with :)

**Comment by josheinstein** [comment]
Oh crap... I was replying to these via email and had no idea they were going into the issue system! Is there any way to delete my comments?
