### ISSUE TITLE
Cells or texts Colors

### ISSUE THREAD

**Issue by chrisk59** [dfinke/ImportExcel#30]
hello,
do you think it'll be possible to make a cell or a text cell different color if there is something in the text that set the color.

i mean it'll be really great that some some defined reason, one cell will be in a different color.

exemple : Normal text will produce 
![2015-07-31-screenshot 1](https://cloud.githubusercontent.com/assets/3678343/9006344/a6c978ea-3786-11e5-94c1-ca83ec144404.jpg)

Red text : 
![2015-07-31-screenshot 2](https://cloud.githubusercontent.com/assets/3678343/9006347/b151bfde-3786-11e5-9220-b747d3233e7a.jpg)

or Red Cell : 
![2015-07-31-screenshot 3](https://cloud.githubusercontent.com/assets/3678343/9006353/ba954692-3786-11e5-860b-4e5dc3c294af.jpg)

i though for example if there is a tag in text like : "RED::my text" will produce a red "my text" for the cell.

it'll be usefull for testing repport. to see what is good or not

i hope you understand what i mean .. 
best regards
Chris

**Comment by dfinke** [comment]
Conditional formatting would be nice. I'll take a look and see if it is possible.

**Comment by chrisk59** [comment]
ok, i did it.. perhaps not a proper way but it work.. for moment i have only Cell color, i'll look at Text color ..

**Comment by dfinke** [comment]
Sounds great. Please share when you can.

**Comment by chrisk59** [comment]
ok no prob, i fixed all, now i can set foreground color or background+foreground. how do you want i share it ?

**Comment by chrisk59** [comment]
i did a Fork of your project, hope i did it good, first time for me ..

**Comment by dfinke** [comment]
Excellent! I'm sure you did. You do a pull request. Let me know if you help with that or email me. 
Your question got me thinking about conditional formatting. I have this. Working at adding it to the module.

![image](https://cloud.githubusercontent.com/assets/67258/9018579/22ef9932-37ae-11e5-82f0-65fa223f3db9.png)

**Comment by chrisk59** [comment]
oh this is cool too, i like the litle flag ! 8-)
i did a pull request, hope it's the way ..

**Comment by dfinke** [comment]
I like the creative approach you did.  I did a little digging and I think I'm going to work this in to parameters for the `export-excel`. The amount of control over the cell seems less than what you implemented. I think this is more flexible provides more control.

![image](https://cloud.githubusercontent.com/assets/67258/9022415/76dddca4-3842-11e5-817e-14210e66e3c3.png)

**Comment by chrisk59** [comment]
ok, but my need if to format my results in a powershell script before send it to export. i mean if i want to check if a name match something if not mark it red.. and it need to do this for a lot of différents contitions.. 
is it possible with your way ?

**Comment by dfinke** [comment]
Can you provide an example of what you're trying to do?

This approach is using the Excel builtin conditional formatting. There are several types of conditional formats and you can combine theme.

For example you can color a cell red if it does not contain 'New'

```powershell
$rule = $ws.ConditionalFormatting.AddNotContainsText("B2:B5")
$rule.Style.Fill.BackgroundColor.Color = "red"
$rule.Text = 'New'
```
Your approach has direct control, I'm not sure yet how general purpose it is. Perhaps rather than setting the formatting info in the the data, providing access to the worksheet before it is saved is a way to do the formatting.

Meanwhile, your PR should work for your situation.

**Comment by chrisk59** [comment]
hello,
i thought about your way, i think i can use it in some case, not sure for all case but in some yep, but i have a question, this code is done in the module, how you'll make user choose the cells and the Condition from their script ? in my case i can have up to 10 differents Conditions for differents cells.

Else an example of what i do, is for example check if a part of a path is matching another value (the path and the value are in 2 differents Cells). I can have a False value Ok for a cell and same False value KO for another, so no way to do a general condition for all my row Cells.

Else i think i can use this conditional approach for what i wanted to do with $rule.Text = '[red]::New' but i need to find a way to remove the [red]:: from eyes, perhaps a formula can do this, i don't know yet..

best regards !
you do a great job !!

**Comment by dfinke** [comment]
That's right. Excel can have many many **conditional formatters** applied to the whole sheet, a row, a column. They conditions can be applied both as values or formulas.

**Comment by chrisk59** [comment]
you have an idea for :  " how you'll make user choose the cells and the Condition from their script ? "
