### ISSUE TITLE
Export-Excel - macro-enabled spreadsheet .xlsm

### ISSUE THREAD

**Issue by datascience-ninja** [dfinke/ImportExcel#300]
hi, I've been using the export-excel for reporting and it's been great! there's a new requirement where I need to pull data from another source. 

is it possible to add the ability to export to a macro-enabled spreadsheet? **.xlsm**!

**Comment by dfinke** [comment]
Just had a quick look at the EPPlus library I use to create the Excel file. It looks like the support xlsm files. Please could you say a bit more about what you are looking to do. For bonus points could you post a sample xlsm of what you'd export and how it might look.

**Comment by siopow** [comment]
i'm just hoping to slap on an existing macro to the macro enabled spreadsheet!

**Comment by markus-maximus** [comment]
I'm using Export-Excel and it's a lifesaver!  However, I've been trying to get it to insert into XLSM files and it works fine, EXCEPT it seems to corrupt my VBA macros.. putting in "ttrbute VB_Name "XXXX" at the top of every module!  Any ideas?

**Comment by markus-maximus** [comment]
Example:

ttribute VB_Name = "Module1"

**Comment by dfinke** [comment]
Does saving the `xlsm` as an `xlsx` and then exporting it make a difference?

**Comment by dfinke** [comment]
Can you say a bit more about that? After using the `Export-Excel` you can use `Open-ExcelPackage` and `Close-ExcelPackage`. That gives you deeper access to the more features in the Excel workbook.

**Comment by markus-maximus** [comment]
I think I’ve managed to get away from XLSM sheets now and done everything I need with formulas.  

However, now I’m having a problem that I’ve got three “report sheets” that point to a data sheet retrieved with the Export-Excel function and now none of the formulas will recalculate when I refresh the data.  Does the “—ClearSheet” option do something that’s preventing formula recalculating?

(btw - I use the INDEX( ) function extensively in Excel workbook.

**Comment by dfinke** [comment]
hmm, I don't believe it does. If you don't use that switch does it work? Export-Excel works only on the file structure. The formulas are only calculated when the workbook is opened in Excel.

```powershell
 "c1,c2`r`ntest,=10*3" | convertfrom-csv | export-excel c:\temp\testformula.xlsx -show -ClearSheet
```

**Comment by markus-maximus** [comment]
Taking out the ClearSheet option to test.  (not ideal in case rows are deleted in my input data, but I'll try it).

Incidentally, one thing I noticed, if I open the sheet, simply changing one data value manually on the data sheet retrieved by Export-Excel caused the entire workbook to recalculate as I needed.

For your reference, this is all my powershell script does: (p1 = query, p2 = excel file)

Invoke-Sqlcmd -Query $p1`
              -Database (db) `
              -ServerInstance (server) `
              -Username (user) `
              -Password (pwd) |
Export-Excel $p2 -WorksheetName RegData

**Comment by dfinke** [comment]
Yeah, taking out the ClearSheet was just for a sanity check. Getting this down to a simple repro case is what is needed to track this down. Could be a range of things including the EPPlus dll that may be setting up re-calc to not work

**Comment by Smickevicius** [comment]
Hi Doug,

First of all, thanks for sharing such time saving project!. Im having issues with saving the generated worksheet as *.xlsm file. Will try to explain the issue : 

Im reading file entries from SP site, then assigning entries to a colleague in script. Then i export everything to xlsm file. which has enabled macro, which copies the column, to colleagues sheet based on assigned name. and after exporting the output from PS script i get error:

![image](https://user-images.githubusercontent.com/39517872/40354368-5f3873a0-5dbc-11e8-89a7-3280b7317fc2.png)

If i export the script output to normal xlsx file, and then import it to xlsm file, it works OK. But i would like to import it directly to xlsm file without extra step. Maybe you know what could the the issue ?.  Looks like the file export automatically as xls, and format can't be changed to xlsm. Maybe there's a way to do that?.

**Comment by BenClarke** [comment]
This would be incredibly useful for what I'm working on as well, there's a lot of legacy business logic captured in VBA, would be great to import data directly into an xlsm to leverage the VBA without additional steps.

**Comment by dfinke** [comment]
So being able to also create an `xlsm` is what you're looking for?

**Comment by BenClarke** [comment]
Ideally what I’d be looking for is the ability to load data into an existing xlsm.

**Comment by jhoneill** [comment]
So I can create an xlsm like this. 

```
$path = "$Env:TEMP\test.xlsm"
$excel = $stuff | Export-Excel -Path $path -PassThru
$m = $excel.Workbook.VbaProject.Modules.AddModule("Module1")
$m.Code = @"
xxxx
"@

Close-ExcelPackage $excel
```
What I noticed is if I try to import a .BAS file which I exported from Excel there is a spurious extra line at the top `Attribute VB_Name = "Module1`  I suspect @markus-maximus may be having a problem because of the way the files are read ? 

When I open the file in Excel I need to enable macros; I'm guessing this is by design so that something doesn't create something evil 
I can re-open the excel package, do things, close and save it or Export to another sheet and the macros are there but need to be enabled which is what @BenClarke  wanted , so I can't see what isn't working there.

**Comment by harman-travelopia** [comment]
Hi, 
The export-excel is brilliant option and addition to Azure Powershell Runbook. However, I have a different scenario. I want to trigger (or) run my existing macros through powershell runbook command. 
till - $excel.Workbook.VbaProject.Modules is fine. After that I can see my code under 'Module1' but unable to trigger it. 

Any suggestions on this would be greatly appreciated on how to trigger existing macros. 
Thanks in advance..

**Comment by dfinke** [comment]
This module leverages EPPlus, and EPPlus supports Creating, Reading and Writing VBA. Execution/Interpretation of VBA code is not supported.

https://stackoverflow.com/questions/37989611/call-vba-macro-by-epplus

Also, my suspicion is the macro needs to be executed in a running instance of Excel. Which means Excel needs to be installed.

**Comment by harman-travelopia** [comment]
hi.. thanks for quick response. Let me elaborate the issue. I have a blob storage where I had my excel (xlsm) with associate macros. With the help of Azure Runbook - PS script I am pumping some data into it. After getting that data, there is a small macro which churns out the data and prepares a report. So, this PS script should trigger that macro so that report is generated and automatically sends mail to recipients. While I wonder, ImportExcel has option of adding modules and associated code, don't we have the option of running (or) call the current modules to execute the macro? 
Really thanks for the support

**Comment by danubie** [comment]
When I do understand your prolbem correct and presuming you have
- Excel-Application installed
- an xla containing a macro named "Hello"
- your security-settings allow macro execution 
the following should work
```
$excel = New-Object -ComObject Excel.Application
$excel.Visible = $true
$workbook = $excel.Workbooks.Add()
$sheet = $workbook.ActiveSheet
$excel.Run('.\Documents\ExcelWithMacro.xla!Hello')
```

**Comment by harman-travelopia** [comment]
Hi.. greetings... thanks for reply.. 
I realized Azure back end wont support Excel functionality. While my excel is in Blob storage, it should have supported platform to run. Unfortunately, MS official blog clearly mentioned, currently they are not supporting this feature. 
-comobject wont work in Azure runbook nor in Azure functions as Excel is not installed on base platform. 
By importExcel add-on, adding or removing modules may be easy as we are trying to access xml object.workbooks.vbaproject but, triggering (call/run) modules won't be possible. 

Now that realizing the fact Excel macros can't be triggered, I am exploring using either HTML or Power BI to generate report directly from CSV. 

Pls let me know if my understanding is right or any other alternative we have. 
Really appreciate taking your time to help me out. 
Cheers.. 
Chiru
