### ISSUE TITLE
Compound Conditional text

### ISSUE THREAD

**Issue by deckerjohn** [dfinke/ImportExcel#302]
This may be simply lack of knowledge, but I could not find an example anywhere.  Is it possible to have a compound conditional text statement on the same column.  If it is how would that be set up?

I have an issue where I'm trying to highlight a notcontainstext but ignore blanks in a column.  Thank you so much for any help!

**Comment by dfinke** [comment]
Can you do than directly in Excel?

**Comment by deckerjohn** [comment]
hmmm....guess not.  Sorry perhaps I was overthinking on the capabilities of whats actually possible in Excel versus common use of compound matching.  Very sorry to bug you

**Comment by dfinke** [comment]
No problem.
