### ISSUE TITLE
xls Excel Import Failed - 0x8003001D (STG_E_WRITEFAULT)

### ISSUE THREAD

**Issue by TomAusL** [dfinke/ImportExcel#306]
I get an error while importing a xls file. 

ImportExcel.psm1 (433, 13): ERROR: At Line: 433 char: 13
HRESULT: 0x8003001D (STG_E_WRITEFAULT)

If I save it as xlsx and remove the vb code in it I can import it without problems

Unfortunately I cannot attach the file so here is the direct link:
[http://www.era.europa.eu/Document-Register/Documents/IU-VKM-publiclist-96.xls](url)

Is this a problem with epplus.dll?

**Comment by dfinke** [comment]
Try saving it as an xlsx first. Leave the VBA. EPPlus only works with xlsx files

**Comment by TomAusL** [comment]
Thanks for the info. Then perhaps the parameter validation for the import-excel function should be changed and / or an appropiate message should be output that a wrong file format is used.

>         [Parameter(ValueFromPipelineByPropertyName, ValueFromPipeline, Position=0, Mandatory)]
>         [ValidateScript( {(Test-Path -Path $_ -PathType Leaf) -and ($_ -match '**.xls$**|.xlsx$|.xlsm$')})]
