### ISSUE TITLE
When using "-HeaderName" is orginal head row imported as data-row

### ISSUE THREAD

**Issue by thuld** [dfinke/ImportExcel#307]
Since version 4.0.10 is the orginal header row imported as data-row when using `-HeaderName`. Take the following example:  I have an .xlsx file with the following content
````
1 | Display Name  | First Name  | Last Name
2 | Daniel M.     | Daniel      | Meier
3 | Martin M.     | Martin      | Meier
````

This is the result when using version 4.0.10:
````
$header = $("dname", "fname", "lname")
Import-Excel -Path (Join-Path 'C:\temp' 'importThis.xlsx') -HeaderName $header | FT

dname        fname      lname
-----        -----      -----
Display Name First Name Last Name
Daniel M.    Daniel     Meier
Martin M.    Martin     Meier
````

The expected result would be the following (this is the result when using version 3.x of this module):
````
dname        fname      lname
-----        -----      -----
Daniel M.    Daniel     Meier
Martin M.    Martin     Meier
````

Is this new behaviour (original header row is imported as data-row) by design or is this a bug?

**Comment by kasautiii** [comment]
Yeah, the same is re-producible on my machine too.

**Comment by thuld** [comment]
Are we the only one that are facing this issue?

**Comment by jhoneill** [comment]
Have you tried -StartRow 2  ?

**Comment by jhoneill** [comment]
Thinking about it some more, 
- Using alternate headers should not change behaviour. 
- The first row should be assumed to be header (not data) unless -NoHeader is specified. 
- Start row should be the first row (header if there is one)  _not_ the first _data_ row

Using -StartRow as I described above contradicts this... 

I've only got builds back to 4.0.3 on my machine and (as far as I can see) nothing which controls the behaviour of the headers has changed in that time frame.

**Comment by jhoneill** [comment]
I'm having a quiet day  so ... 
It looks like line 361
`if (((-not ($NoHeader -or $HeaderName)) -and ($StartRow -eq 0))) `
Should lose the -or $headerName. 

and if line 366 is changed from `where {($_.Start.Row -ge $StartRow)})` 
to **-GT**  lines 403 to 407 can go -  I don't think the header row is needed in between, and I think the check at 366/7 doesn't catch the case of a sheet which has headers but no data.  

Anyone who put in  `-StartRow` to work round the current behaviour will need to take it out again if behaviour is fixed but I doubt that will be enough of a problem to keep doing it the wrong way.
