### ISSUE TITLE
Example for Conditional Formatting for RuleType - Expression

### ISSUE THREAD

**Issue by amon09** [dfinke/ImportExcel#309]
For the cmdlet `Add-ConditionalFormatting`, could you please add an example for the `RuleType` `Expression`? 

For instance, I would like to highlight any rows that matches a string that begins with `Reads: [some-integer] (` where integer value less than or equal to 1000.

**Comment by dfinke** [comment]
This module uses EPPlus under the covers. You can try and google that plus the piece you're looking, could get a quick hit.

**Comment by jhoneill** [comment]
If I want to format column B then if I write the expression using B1 this will read as B<<current row>> so can use something like this for something where the first 2 characters are a number greater than 10 and the last 2 are "GB" 
Add-ConditionalFormatting -RuleType Expression -ConditionValue '=AND(NUMBERVALUE(LEFT(B1,2)) > 10,(RIGHT(B1,2)="GB"))'  .... etc 

You can put that expression in cell (or range of cells) and it should give true for those which will be formatted and false for those which won't.  Parsing text in Excel can be painful of course
