### ISSUE TITLE
Set-Format bug:  -Height causes 'null-valued expression' (v 4.0.11)

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#310]
#$ws.Column($_).Width = $Width
was correctly replaced with 
$Address.Worksheet.Column($_).Width = $Width
in v4.0.11
but 
$ws.Row($_).Height = $Height
did not get the similar fix to use 
$Address.Worksheet 
instead of $ws

**Comment by dfinke** [comment]
Want to try and do a PR?
