### ISSUE TITLE
Install script on PS4 fails

### ISSUE THREAD

**Issue by supersjimmie** [dfinke/ImportExcel#314]
$PSVersionTable

Name                           Value                                                                                                                                   
----                           -----                                                                                                                                   
PSVersion                      4.0                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                         
BuildVersion                   6.3.9600.18773                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                    
PSRemotingProtocolVersion      2.2                                                                                                                                     

When I copy/paste the installation into the ISE, I get:

```iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfinke/ImportExcel/master/Install.ps1')```
```
iex : The script block cannot be invoked because it contains more than one clause. The Invoke() method can only be used on script blocks that contain a single clause.
At line:1 char:1
+ iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

When I copy/paste the content of the install.ps1 into a new file and execute that:
```
Failed installing the module in the install directory 'C:\Users\me\Documents\WindowsPowerShell\Modules\ImportExcel': Exception calling "DownloadFile" with "2" 
argument(s): "The remote server returned an error: (404) Not Found."
```

**Comment by dfinke** [comment]
Can you install it from the Powershell gallery?

**Comment by supersjimmie** [comment]
I sure would love to give that a try, but... Can you give me a hint on how to start with that?

**Comment by dfinke** [comment]
https://www.powershellgallery.com/packages/ImportExcel
`Install-Module -Name ImportExcel`

**Comment by supersjimmie** [comment]
```Install-Module -Name ImportExcel```  asks permission to install from untrusted repo, when I agree (yes to all)  it just finished without any work.

**Comment by supersjimmie** [comment]
My bad, I thought that it failed because nothing happens, but the machine now has  e.g."Import-Excel".
