### ISSUE TITLE
Question: Set AutoFilter criteria

### ISSUE THREAD

**Issue by svhadar** [dfinke/ImportExcel#315]
Hi,
first of all like to thank you for your fantastic work on ImportExcel.
I am using it quite a lot and till now I could achieve everything I ever dreamed of.

The only thing I can't figure out is, if there is a way to add a filter criteria for the autofilter. Like the Range.AutoFilter method from the Microsoft.Office.Interop.Excel.
I would like to hide certain rows matching a criteria in a column (e.g hide all cars which are blue), so that the user only sees a subset of all rows when he opens the excel file, but can still show all rows is he wants to.

Is there a way to achieve this?

Many thanks

Sven

**Comment by dfinke** [comment]
Thank you Sven. I don't believe the is available. I need to look into if that is possible. Thank you for the suggestion.
