### ISSUE TITLE
Can add row/column but not remove?

### ISSUE THREAD

**Issue by supersjimmie** [dfinke/ImportExcel#319]
I'm thinking about building an Excel file with "rolling" data.
So when adding a row at the end of a range, the row first in that range has to be removed.
Eg.:
```
Data    text
10        bla1
20        bla2
30        bla3
40        bla4
```
After adding 50 to the end and remove the first one:
```
Data     text
20        bla2
30        bla3
40        bla4
50        bla5
```

Am I not searching properly or is there ony a function ```Set-Row()``` to add a row, but no function to remove a row?  Since I am new to ImportExcel, is there a preferred way to do such thing?

**Comment by dfinke** [comment]
Check out https://github.com/dfinke/ImportExcel/blob/master/Examples/CustomReporting/CustomReport.ps1

Currently you'll need to work against the Excel model directly after doing an `Open-ExcelPackage` which is a direct interface to the EPPlus library under the covers. You can find out the dimensions of your data and, target the Cell and I'm guessing there is a Remove() method. Don't know off the top of my head.

**Comment by supersjimmie** [comment]
For some reason I was already using ```Open-ExcelPackage```, so I guess I should continue to do so. 😃 
I found ```$sheet1.DeleteRow(2)``` which does what I want.

**Comment by dfinke** [comment]
`Export-Excel` and `Import-Excel` were intended to work with table shaped data. The `Open-ExcelPackage` was implemented to handle cases outside of that. You could also use the `-PassThru` switch on `Export-Excel` which saves the step of opening it.

**Comment by dfinke** [comment]
You'll have to handle of that. Rather than adding and removing data to the sheet. If possible, you could read the existing one, `Import-Excel`, processes the data in PowerShell and then `Export-Excel` what you need, setting up charts etc

**Comment by supersjimmie** [comment]
So I cannot use ```Import-Excel```, handle the data with ```$sheet1.DeleteRow(2)``` and then do an ```Export-Excel```  + add the chart?
That means I have to delete the row manually by manipulating the data by own code?

**Comment by supersjimmie** [comment]
When using ```Open-ExcelPackage```  I can use ```$Sheet1.DeleteRow(4)```, and then use things like ```$Chart1 = $Sheet1.Drawings.AddChart("Chart" + [Guid]::NewGuid().ToString('n'), $Chart1Type)``` to add a chart.
Happy because I can now continue what I started and also add the chart. 😃

**Comment by dfinke** [comment]
Yes, great.
