### ISSUE TITLE
Export-Excel should overwrite exisitng XLSX-File when using switch '-Force'

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#32]
It would be nice if Export-Excel could delete and create a new file when it already exists when using the '-Force' switch. For the moment the '-Force' switch is not recognized and doesn't do anything.

When using 'Export-Excel' without the '-Force' switch, it just overwrites the existing worksheets but not the whole workbook. This default behavior is logical to me, but it should be possible to also overwrite the whole workbook, that's where the '-Force' switch could come into play.

**Comment by dfinke** [comment]
Great suggestion. Could you say some more about the expected result? Deleting the xlsx file when `-force` is  specified? Deleting all the worksheets?

**Comment by DarkLite1** [comment]
Thank you for the reply dfinke. Yes, that's exactly what I mean. It's like other CmdLets, when you use '-Force' it deletes the original file and puts the new one in place. 

So in our case, delete the workbook and all its worksheets and create a new workbook with the desired worksheets.

**Comment by josheinstein** [comment]
I think this was addressed in a previous issue. https://github.com/dfinke/ImportExcel/issues/2#issuecomment-91623293

Typically, -Force is not used to overwrite, as overwriting is done by default. -NoClobber is used to prevent an overwrite. The normal behavior of -Force is to ignore a readonly bit.

**Comment by DarkLite1** [comment]
Josheinstein, I agree with your remark. But then the default behavior of  'Export-Excel' should be corrected. Because now it only overwrites worksheets that are present and not the whole workbook. Meaning, that if old worksheets with other names are present in the file they will not be deleted in the Workbook.
