### ISSUE TITLE
ImportExcel doesn't work for .xls

### ISSUE THREAD

**Issue by Frederic04510** [dfinke/ImportExcel#323]
Hi,
I need to search a particular text into every excel files (.xls, .xlsx) contained in a directory (and subdirectories).
Function Import-Excel from module ImportExcel works fine for .xlsx but doesn't work for .xls.
I don't want to use COM objects, neither convert .xls to .xlsx (using function ConvertTo-ExcelXlsx of the same module).
What solution do I have ?

Rgds,,

Frederic

**Comment by dfinke** [comment]
Sorry, this module only works with xlsx

**Comment by wsuhoey** [comment]
For posterity, you can use the `ImportExcel` module's `ConvertTo-ExcelXlsx` cmdlet to convert .xls files to .xlsx files, then you can work with the rest of the commands in the module.
