### ISSUE TITLE
Feature request:  Import Excel rows & columns as array of array

### ISSUE THREAD

**Issue by HerbM** [dfinke/ImportExcel#324]
Add Feature to:  Import Excel rows & columns as array of array

Ideally with at least max row, max column, or perhaps any (rectangular area).

Return results (optionally) as arrays instead of Objects with properties.

Perhaps an option to get "active area" (which I believe is something Excel tracks (greatest column and row in use.)

Reasons:  
`

1. We experience slow loading with widely populated sheet even though we knew that only a moderate number of columns were actually populated.
2. Using dataonly made the positions inconsistent from workbook to similar workbook.
3. Object properties were inconvience when all we neede was to "join" the fields to create a SQL statement VALUES string.

**Comment by jhoneill** [comment]
How about 
`$xl = Open-ExcelPackage -path 'C:\Users\joneill4\Desktop\Halewood Preprod\HAJ0GBMV4052.xlsx'                                                                                                                                                                
$ws = $xl.Workbook.Worksheets["Services"]                                                                                                                                                                                                                   

$Rows = foreach ($row in ($ws.Dimension.Start.row    .. $ws.Dimension.end.row   )) {
       $Cells = , $( foreach ($col in( $ws.Dimension.Start.column .. $ws.Dimension.end.column))  {
            $addr = [char](64+$col) + $row
            $ws.Cells[$addr].value
        })
        $cells
}
Close-ExcelPackage $xl


>$Rows[0]

Name
DisplayName
StartMode

>$Rows[1] 

AeLookupSvc
Application Experience
Manual

>$rows[1][2] 

Manual
`

**Comment by jhoneill** [comment]
@dfinke  - I've been looking at perf improvements , and I'll mail you the results.
