### ISSUE TITLE
How to free memory of output of Import-Excel ?

### ISSUE THREAD

**Issue by titours13770** [dfinke/ImportExcel#325]
Hi,
I'm using the following code (below simplified) :
foreach($excel_file in $excel_file_list)
{
$object = Import-Excel -Path $excel_file.Fullname –NoHeader -DataOnly   
... perform operations on $object
}
I see that it consumes lots of memory
I would like to free the memory occupied by $object at the end of each loop : how can I do that ?

Rgds,

Frederic

**Comment by jhoneill** [comment]
Add the following after you have finished with the object
`$object.clear()
[gc]::collect()`

The first line empties the array which contains the imported data, and the second tells powershell's garbage collector to reclaim unused memory.

**Comment by titours13770** [comment]
Hi,
Thanks for your help.
That doesn't seem to work better : 
1) I've got the following error when calling clear on the object created by Import-Excel : Method invocation failed because [System.Management.Automation.PSCustomObject]
does not contain a method named 'clear'.
2) The memory consumption always grows (to 1,6 Gb) during script execution

Rgds,

Frederic

**Comment by jhoneill** [comment]
That error suggests you only have one cell returned by Import-excel - you have a Single PSCustomObject which doesn't have "clear", instead of an array (which does have clear). 
Could you check if your memory consumption jumps when you run 
$object = Import-Excel <params> 
on its own, or if it is something in the processing.  

Using a spreadsheet which is 100,000 rows x 8 columns I can only get memory usage up to 350MB and I get ~200MB back with clear and collect.

**Comment by titours13770** [comment]
Hi,
I'm not dealing with huge files but looping on numerous files (excel files in a folder and subfolders)
Each time Import-Excel is called, it stores the object in memory.

**Comment by jhoneill** [comment]
OK.  But if you run 
```
foreach($excel_file in $excel_file_list)
{
$object = Import-Excel -Path $excel_file.Fullname –NoHeader -DataOnly
}
```
 Without doing your processing.  What  happens then ? 
and if you have
```
foreach($excel_file in $excel_file_list)
{
$object = Import-Excel -Path $excel_file.Fullname –NoHeader -DataOnly
if ($object.count -ge 1) {
  $object.clear()
  [gc]::collect()
}
}  
```
Does the memory stay in sensible limits ?

**Comment by titours13770** [comment]
Hi,
I'm not dealing with huge files but looping on numerous files (excel files in a folder and subfolders)
Each time Import-Excel is called, it stores the object in memory.

**Comment by titours13770** [comment]
Hi,

1) I tried :

$liste_fichiers_excel = Get-Childitem -Path $SEARCH_PATH -Include *.xlsx -Recurse -ErrorAction SilentlyContinue

foreach($fichier_excel in $liste_fichiers_excel)
{
    $object = Import-Excel -Path $fichier_excel.Fullname –NoHeader -DataOnly
}

In task manager, memory for powershell.exe grows from 37 Mb to 1,3 Gb

2) Then I ran : 
$liste_fichiers_excel = Get-Childitem -Path $SEARCH_PATH -Include *.xlsx -Recurse -ErrorAction SilentlyContinue

foreach($fichier_excel in $liste_fichiers_excel)
{
    $object = Import-Excel -Path $fichier_excel.Fullname –NoHeader -DataOnly
    if ($object.count -ge 1) 
    {
        $object.clear()
        [gc]::collect()
    }
}

In task manager, memory for powershell.exe grows from 37 Mb to 1,3 Gb

**Comment by DarkLite1** [comment]
Even without the `clear()` and `collect()` methods the memory should be freed after each iteration because it's writing data to the same object `$object` if I'm correct. I can only see the memory go up significantly when you do this:

```powershell
$result = foreach ($excel_file in $excel_file_list) {
    $object = Import-Excel -Path $excel_file.Fullname –NoHeader -DataOnly
    # ... perform operations on $object
    $object
}
```

instead of this:

```powershell
foreach ($excel_file in $excel_file_list) {
    $object = Import-Excel -Path $excel_file.Fullname –NoHeader -DataOnly
    # ... perform operations on $object
}
```
Because in the first case the variable `$Result` is populated with all the objects, as such, the memory grows. Are you absolutely certain it's not something else in the code that is consuming the memory?

**Comment by guillermocastro** [comment]
This works for me:
$objExcel = New-Object -ComObject Excel.Application
...
try
{
    $objExcel.Application.Quit()
    Start-Process -Wait 1
    $objExcel=$null
}
catch
{
}

**Comment by dfinke** [comment]
@guillermocastro How does `-ComObject` and launching Excel relate to the ImportExcel module?

The PowerShell ImportExcel module works `without` having to Excel installed.

Please make more informed posts in the future. - Thank you
