### ISSUE TITLE
AutoSize?

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#326]
I am exporting data to an excel spreadsheet using a script like below.  When I do that and open in excel the data column is showing the hash symbols.

`$obj_hash = [ordered]@{            
		"Date"							= "N/A"
        "Name"             			    = "N/A"
        "Random1" 	      				= "N/A"
        "Random2"  	     				= "N/A"
	}

$final_results =@()

$files = gci D:\ | sort lastwritetime -Descending 

Foreach ($File in $files)
	{
        $Results=$null
		$Results = New-Object PSobject -Property $obj_hash

        $Results.Date = $($file.LastWriteTime)
        $Results.Name = $($file.FullName)
        $Results.Random1 = "Random Text"
        $Results.Random2 = "Random Text"
        

        $final_results += $Results
    }

$final_results | Export-Excel -path D:\test3.xlsx -WorkSheetname Test3 -AutoSize -ClearSheet -TableName Test3
`

I assuming that this is something that I have caused but I am not sure how to fix.  Any suggestions?

**Comment by dfinke** [comment]
Yeah `-Autosize` tries it's best. When Excel renders the data when launched sometimes the content is still too wide to display.

**Comment by g-pearl** [comment]
I was able to "tweak" the process slightly as a way to get the date column to not show the HASHes.

`$final_results | ConvertTo-Csv -NoTypeInformation | ConvertFrom-Csv | Export-Excel -path D:\test3.xlsx -WorkSheetname Test3 -AutoSize -ClearSheet -TableName Test3`

Doing the little flip to csv then from csv make the date column appear better.

**Comment by dfinke** [comment]
Cool, interesting.
