### ISSUE TITLE
Numbers with leading zeros treated as numbers, not text

### ISSUE THREAD

**Issue by alevyinroc** [dfinke/ImportExcel#33]
When numbers with leading zeros (for example, 0123) are written to an Excel file, Excel treats them as numbers & the leading zeros are dropped (0123 becomes 123). This may present problems in situations where leading zeros are truly part of the data, such as US ZIP (postal) codes for parts of New York, New Jersey & Massachusetts.

Example to reproduce the issue:

`"a,b,c\`r`n01,002,3`r`n00u812,05150,abc,`r`n123,456,098`r`n0123,456,098"|ConvertFrom-Csv|Export-Excel .\test.xlsx -Show`

This was originally observed in an export of SQL Server data (via `Invoke-SQLCmd`) where the fields were otherwise identified as strings.

**Comment by dfinke** [comment]
Thanks for opening the issue. I'll investigating a solution

**Comment by W1M0R** [comment]
Thanks for reporting this. I am also experiencing the same difficulty. Export-Excel does a TryParse that always checks if it can convert a cell value to a number. Perhaps Export-Excel can take a parameter that forces the type for a particular column? Or a parameter that allows the user to bypass the TryParse for certain cells, columns or property names. Alternatively, $TargetData.GetType() could be used to TryParse only truly numeric types.

**Comment by juancrl** [comment]
I'm facing the same issue, Spanish ZIP codes starting with zero get converted and lose the leading zeroes.
Which is the right syntax to force a single column to be considered as TEXT and keep the zeroes ? I'm using 2.2.9 (Dec 2016)

**Comment by dfinke** [comment]
@juancrl I have not come up with a good solution for this. You you prepend a single quote `'` to the the zip before you export it, Excel should represent it as text.

**Comment by juancrl** [comment]
Thanks Doug for your quick response,

I’ve tried to prepend the single quote, and that of course treats the value as Text… but the quote then becomes a part of the string.

"'00001","'00002","'50000" | export-excel 1.xlsx –Show
[cid:image001.png@01D24E1B.E7BE0800]

Maybe I could insert a formula with the value in each field ?


jc

**Comment by dfinke** [comment]
So, I only did a little digging, I'm not sure how viable this is. Certainly not automatable at this point.Excel by default removes leading zeros. You can add a `custom type`.. 

![image](https://cloud.githubusercontent.com/assets/67258/20867082/48862528-ba0a-11e6-8745-45e3c5a99961.png)

**Comment by juancrl** [comment]
I’ve found what it seems a valid workaround, at least in my case :

Function GenerateZipForExcel ($zip)
{

   if ($Zip -eq "28xxx") { return $Zip }                          # Exceptions, some ZIPs which are not totally defined


   if ([string]::IsNullOrWhiteSpace($zip)) { return "    " }      # Empty ZIP means 5 spaces


   return '=TEXT('     +    [int]$Zip    +     ',"00000")'        # return the Excel =TEXT( function


}

HTH,
jc
