### ISSUE TITLE
Set-Column not working 

### ISSUE THREAD

**Issue by tehfonz** [dfinke/ImportExcel#333]
I am trying to set the contents of a column and have tried the following:

```
$Excel = (Open-ExcelPackage -Path 'C:\Temp\Book1.xlsx')
$ws = $excel.Workbook.Worksheets[1]
Set-Column -Worksheet $ws -Heading 'Review' -Value 'test' -Column 0
```

```
$Excel = (Open-ExcelPackage -Path 'C:\Temp\Book1.xlsx')
Set-Column -ExcelPackage $Excel -Worksheetname 'Sheet1' -Heading 'Review' -Value 'test' -Column 0
```

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2189
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2189
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
PS C:\> Get-Module importexcel

ModuleType Version    Name                               
---------- -------    ----    
Script     4.0.12     ImportExcel
```

I am sure I'm using the cmdlet correctly and have followed the example as best I can.
If I run the cmdlet with the worksheet open I do not get any error that the file is open. Closing the document does not make any difference.

Cheers

**Comment by tehfonz** [comment]
OK, After some searching around the repo, I found I need to then Export-Excel and use the original package & WorkSheetname. Perhaps the example needs to inlclude:
`Export-Excel -ExcelPackage $Excel -WorkSheetname 'Sheet1'`

Cheers!

**Comment by dfinke** [comment]
I believe `Close-Package` should work.
https://github.com/dfinke/ImportExcel/blob/master/Examples/CustomReporting/CustomReport.ps1#L72

**Comment by tehfonz** [comment]
Ah, I had no idea. Cheers
