### ISSUE TITLE
Exporting a system.data.datatable to excel has extra columns exported

### ISSUE THREAD

**Issue by wgshef** [dfinke/ImportExcel#334]
When populating a System.Data.DataTable and then passing it to be exported to excel with Export-Excel, extra columns end up in the worksheet. The extra columns are:
RowError, RowState, Table, ItemArray, HasErrors.
See attached file showing extra columns.

How do we prevent these extra columns from being exported?
[ExportExcelIssue.xlsx](https://github.com/dfinke/ImportExcel/files/2029251/ExportExcelIssue.xlsx)

**Comment by dfinke** [comment]
You could do 

`$data  |  select * -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel`

**Comment by ili101** [comment]
I also had this problem, it effects other Cmdlets to like ConvertTo-Html for example.
You can use my forked version of the Export-Excel.ps1 file from https://github.com/ili101/ImportExcel
It uses the native EPPlus DataTable method so it doesn't have this problem and works much faster, (You need to use -TargetData) :
```powershell
Export-Excel -TargetData $DataTable -Now
```
Or as a workaround you can filter it with Select-Object
```powershell
$DataTable | Select-Object -Property  * -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel -Now
```

**Comment by jhoneill** [comment]
If you are getting a table just to send it to excel (and not using it for anything else) then a lot of the work is done for you in Send-SqlDataToExcel  - for large data sets it is more efficient because the EPPlus library has a "LoadFromDataTable" method so we don't have to create the sheet cell-by-cell

**Comment by wgshef** [comment]
Thanks, using -ExcludeProperty worked perfectly.
