### ISSUE TITLE
Question: Is there a way to create multiple line charts on a single worksheet?

### ISSUE THREAD

**Issue by wgshef** [dfinke/ImportExcel#338]
I have a worksheet that has 3 columns of data: ServerName, Date, Count. This has per server/date, the number of times a certain event occurs.
Due to the wide spread of values (from 0, <10, ~25, and ~500), I'd like to have a separate line chart for each server.
I'd like to be able to specify the column / row that each line chart starts at, and the # of columns / rows that it spans (35 rows from Columns E: -> Z: work perfectly).
Each chart would specify the data range for that server.

I see how I can create a single line chart, but is it possible to create multiple as I have specified? Is any of this possible?
Thanks!

**Comment by jhoneill** [comment]
Yes. 
I import performance logs into Excel and do charts which each show one column 

It looks like this 
```

$blgPath   = Get-childitem -Path $env:TEMP -Filter "Server*.blg" | Select-Object -ExpandProperty fullName 
$csvpath   = $blgPath -replace "blg$","csv"
relog.exe    $blgPath -f csv -o $csvpath -y | Out-Null 
$LogData   = Import-Csv   -Path     $csvpath 
$startTime = [datetime]($LogData[ 0].'(PDH-CSV 4.0) (GMT Daylight Time)(-60)')
$endTime   = [datetime]($LogData[-1].'(PDH-CSV 4.0) (GMT Daylight Time)(-60)')



$xrange    = "Time"
$YRange1   = "NetworkBytesPerSec"
$YRange2   = "PercentDiskActive"
$YRange4   = "TotalCPUPercent"
$chart1    = New-ExcelChart -YRange $YRange2 -XRange $xrange -Title "Network"   -SeriesHeader $YRange2 -ChartType Line -Height 500 -width 1200 -Column 14 -Row 30 
$chart2    = New-ExcelChart -YRange $YRange3 -XRange $xrange -Title "Disk"      -SeriesHeader $YRange3 -ChartType Line -Height 500 -width 1200 -Column 14 -Row 60 
$chart3    = New-ExcelChart -YRange $YRange4 -XRange $xrange -Title "Total CPU" -SeriesHeader $YRange4 -ChartType Line -Height 500 -width 1200 -Column 14 -Row 90 



0..($LogData.Count -1)   | 
    Select-Object -Property @{n='Time'                  ; e={ ([DateTime]($LogData[$_].'(PDH-CSV 4.0) (GMT Daylight Time)(-60)')).ToString("HH:mm:ss")}} ,    
                            @{n='TotalCPUPercent'       ; e={      [float]$LogData[$_].'\\Server\Processor Information(_Total)\% Processor Time'}} ,
                            @{n='AvailableMB'           ; e={      [float]$LogData[$_].'\\Server\Memory\Available MBytes'}} ,
                            @{n='PagesPerSec'           ; e={      [float]$LogData[$_].'\\Server\\Memory\Pages/sec'}} , 
                            @{n='NetworkBytesPerSec'    ; e={      [float]$LogData[$_].'\\Server\Network Interface(Red Hat VirtIO Ethernet Adapter)\Bytes Total/sec'}}, 
                            @{n='PercentDiskActive'     ; e={100 - [float]$LogData[$_].'\\Server\PhysicalDisk(_Total)\% Idle Time'}} |                    
                                 Export-Excel -Path "$env:temp\stats.xlsx" -WorkSheetname "Server"  -AutoFilter -AutoNameRange -AutoSize -ExcelChartDefinition $chart1 ,$chart2,$chart3

```

**Comment by wgshef** [comment]
This looks like exactly what I need. Thanks.

A related question: 
I'll be running this script at multiple clients - different number of servers. For some, I might have $chart1,$chart2. Others will go to $chart5 and beyond.
In Example 11 (Get-Help Export-Excel -Examples), it shows setting up multiple pivot tables into an array (@{}). I assume that the same can be done for these line charts?

**Comment by wgshef** [comment]
It seems straight-forward, but I keep throwing an error...
#Add line chart for each server. 
$charts = [ordered]@{};
foreach ($Server in $Servers)
{
    $LineChartRow = $ConditionValues.Rows.Count + $RowStart + 1;
    $LineChartSize = 35;
    $XRange = "B$RowStart" + ":B$($RowStart + $RowCount - 1)";
    $YRange = "C$RowStart" + ":C$($RowStart + $RowCount - 1)";
    $Title = $Param.Value.Split('.')[0];
    $charts[$Title] = [ordered]@{Title        = "$Title";
                                 ChartType    = 'Line';
                                 SeriesHeader = "$Title";
                                 XRange       = "$XRange";
                                 YRange       = "$YRange";
                                 Column       = 5;
                                 Row          = "$LineChartRow";
                                 Height       = 500;
                                 Width        = 1200;
                                };
}
$Excel = $DataTable | select * -ExcludeProperty RowError, RowState, Table, ItemArray, HasErrors | Export-Excel -Path $ExcelFile -WorkSheetname 'Sheet1' -AutoSize -PassThru -FreezeTopRow -ExcelChartDefinition $charts;

$charts is being populated as I expect it to be.

When running the Export-Excel, I get the error:
Failed exporting worksheet 'Sheet1' to 'Excel.xlsx': Cannot find an overload for "AddChart" and the argument count: "2".
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\4.0.13\Export-Excel.ps1:1032 char:13
+             throw "Failed exporting worksheet '$WorkSheetname' to '$P ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed exportin...ent count: "2".:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed exporting worksheet 'Sheet1' to 'Excel.xlsx': Cannot find an overload for "AddChart" and the argument count: "2".

It's bound to be something simple, but I've reached the limits of my PowerShell capabilities. Your assistance is deeply appreciated!

**Comment by jhoneill** [comment]
I think $charts needs to be an array of hashtables, not a hashtable of hashtables.

**Comment by wgshef** [comment]
That did it. Thanks for your assistance.
