### ISSUE TITLE
Copy-ExcelWorkSheet makes the incorrect assumption about the layout of the data. Needs to copy all cells. it asks for append -Noheader

### ISSUE THREAD

**Issue by berincdhas** [dfinke/ImportExcel#339]
Copy-ExcelWorkSheet makes the incorrect assumption about the layout of the data. Needs to copy all cells. it asks for append -Noheader
Can you provide an example to use this

**Comment by dfinke** [comment]
Please could you provide an example of what is happening, thank you

**Comment by jhoneill** [comment]
@dfinke  I am also looking at this. EEplus has "Add Worksheet using a pre-existing worksheet" (which doesn't work if there is conditional formatting !) but it also might be good to have Copy sheet X and then sheet Y  into sheet Z. (And don't create the header, or add autofilter, or add a title or anything else you might do when creating a new sheet) . 

 I wonder if we have a translation issue … 
@berincdhas   when you say _"it asks for"_ do you mean  "It prompts me to input"  or do you mean "it needs to have"

**Comment by dfinke** [comment]
@jhoneill I'm watching the EPPlus work progress. Only concern is what will break when they are done porting it to dotnet. Not sure how long or how far they'll take it either.
