### ISSUE TITLE
Add-worksheet

### ISSUE THREAD

**Issue by berincdhas** [dfinke/ImportExcel#340]
Can you give an example for Add-worksheet

**Comment by jhoneill** [comment]
```
$xl  = Open-ExcelPackage -path "James.xlsx" 
Add-worksheet -ExcelPackage $xl -WorkSheetname "Hello" 
```
Returns the worksheet object representing the Sheet "hello" in the file "james.xlsx" - if the sheet does not exist it will be created. If` -clearsheet` is specified any existing sheet of this name will be deleted first. If it is not specified and the sheet exists then the pre-existing sheet is returned as found in the file.

**Comment by berincdhas** [comment]
Thank you
