### ISSUE TITLE
Can this be used for inline objects rather than files?

### ISSUE THREAD

**Issue by DougChandler** [dfinke/ImportExcel#341]
Can this be used for converting inline objects rather than dumping to file system?
I am looking for guidance to use like the corresponding ConvertFrom-Csv / ConvertTo-Csv?
I am interacting with SharePoint using the CSOM so have an object containing the Excel file, I need to then manipulate this inline just as I can with the corresponding Csv commands.
Can this be done?
Many thanks,
Doug

**Comment by dfinke** [comment]
Great question! I don't believe so but have not investigated it from that point of view. Let me see what I can do
