### ISSUE TITLE
Enhancement Request: StopRow parameter

### ISSUE THREAD

**Issue by WK3** [dfinke/ImportExcel#343]
I'm a big fan of this project. Any chance you could add a parameter for StopRow? This would help with only importing a certain range of rows (especially when combined with StartRow). It could also be useful for sample testing prior to very large imports (e.g.: test several questionable rows of data quickly to determine if they would impact an import, before actually importing hundreds of thousands of rows). Thanks in advance!

**Comment by jhoneill** [comment]
It needs one extra line 
If (-not $StopRow) {$StopRow = $Worksheet.Dimension.End.Row} 
and 3 replacements of` $Worksheet.Dimension.End.Row` with `$stopRow `

**Comment by jhoneill** [comment]
I've added -EndRow (alias StopRow, BottomRow) and -StartColumn (alias LeftColumn) & -EndColumn (alias RightColumn)  so you can specify 
`import-excel -noHeader - top 5 -bottom 10 -left 2 -right 3  
`
https://github.com/jhoneill/ImportExcel/blob/master/ImportExcel.psm1

**Comment by WK3** [comment]
I have tested this and it does exactly what I need it to now. Thank you very much for the work you have put into this project, and the time you have taken to include the change I requested. I sincerely appreciate it.
