### ISSUE TITLE
Move/Sort A Worksheet

### ISSUE THREAD

**Issue by lilsi1** [dfinke/ImportExcel#344]
If you use -ClearSheet, it will put that worksheet at the end of your Workbook. Is there a way to Move that back to the top?

**Comment by jhoneill** [comment]
There is a way. 
If you do 
`$xl = export-excel -passthru <<other parameters:>>`

You can then use `$xl.workbooks.moveafter() $xl.workbooks.movebefore() $xl.workbooks.moveToStart() or $xl.workbooks.moveToEnd() ` and provide either numbers or names of sheets (first to take source and target, last two just source).  
then call` $xl.save()`


These could be added to the export command :-)
