### ISSUE TITLE
PivotTable - SourceWorkSheet

### ISSUE THREAD

**Issue by FetFlex** [dfinke/ImportExcel#345]
Hi,

First of i want to say i LOVE this module. It saved me many headaches :)

Now to my question. I have some information on different customers that i export to a sheet pr customer. Every sheet has the same columns.

I would like to take data from all of these sheets and put it in to a pivot an a sheet for itself. I cannot find out if that's possible somehow.

I found that i can use the PivotTableDefinition. Here i can define SourceWorkSheet. But this only takes one sheet?

Also had a little issue with SourceWorkSheet. It does not like special characters because of the -match used in 
```
function Find-WorkSheet {
    param (
        $WorkSheetName
    )

    $pkg.Workbook.Worksheets | Where-Object {$_.name -match $WorkSheetName}
}
```
I had () in the Sheet name. I had to escape those.

**Comment by dfinke** [comment]
Cool. The question then is, can this be done in Excel manually? I don't think so, needs investigation. If it can be done manually, it may be doable with PowerShell.

**Comment by FetFlex** [comment]
That's a really good point :)

It seems that it's possible. But the procedure is a bit complex:
https://exceldashboardschool.com/consolidate-multiple-worksheets/

Is it possible for importexcel to insert a PivotTable on a already created Sheet? I seems when i try it recreates the sheet? This means that it will be put as the last Shett. Or is it possible to move the order of the Sheets with ImportExcel?

**Comment by jhoneill** [comment]
@FetFlex  - a pivot table can only take one source for its data.  But you could get all the data into one sheet like this . 



If instead of close you do `Export-Excel -ExcelPackage $excel -PivotTableDefinition <<definition including combined sheet>>
`

**Comment by jhoneill** [comment]
@FetFlex - yes, that's a downside, the only way round __that one__

**Comment by FetFlex** [comment]
@jhoneill - Ohh im so sorry. I missed that post.

I will try it. Thanks anyway :)

**Comment by dfinke** [comment]
@jhoneill `ps | export-excel .\t.xlsx -MoveToStart -WorkSheetname Test1` ?

**Comment by FetFlex** [comment]
@dfinke - I'm running version 4.0.13. I cannot seem to find a paramter called "MoveToStart" on Export-Excel:
```
PS C:\WINDOWS\system32> Export-Excel .\test.xlsx -
TargetData               PivotTableDefinition     RangeName                ReturnRange
Password                 IncludePivotChart        TableName                NoTotalsInPivot
WorkSheetname            ChartType                TableStyle               ReZip
ClearSheet               NoLegend                 ExcelChartDefinition     Verbose
Append                   ShowCategory             HideSheet                Debug
Title                    ShowPercent              KillExcel                ErrorAction
TitleFillPattern         AutoSize                 AutoNameRange            WarningAction
TitleBold                Show                     StartRow                 InformationAction
TitleSize                NoClobber                StartColumn              ErrorVariable
TitleBackgroundColor     FreezeTopRow             PassThru                 WarningVariable
IncludePivotTable        FreezeFirstColumn        Numberformat             InformationVariable
PivotRows                FreezeTopRowFirstColumn  ExcludeProperty          OutVariable
PivotColumns             FreezePane               NoNumberConversion       OutBuffer
PivotData                AutoFilter               ConditionalFormat        PipelineVariable
PivotFilter              BoldTopRow               ConditionalText
PivotDataToColumn        NoHeader                 CellStyleSB
```

What am i doing wrong?

**Comment by dfinke** [comment]
@FetFlex sorry, that's not implemented yet :)

Was leaving that there for @jhoneill to comment on the params and see if he had any thoughts.

**Comment by jhoneill** [comment]
@dfinke  Yes -MoveToStart as a switch and -MoveBefore as a string / int would seem ideal.  Sheets are added at the end, so there would be no need for moveToEnd . For the same reason you can move the new sheet before something else to get anywhere but someone is bound  to want -MoveAfter .  Because Export-Excel will process requested changes even when there is no data to export, I'd use "MoveTo" as the verb rather than "CreateAtStart"

**Comment by FetFlex** [comment]
@dfinke I can see that now :) Sorry 🤐

**Comment by FetFlex** [comment]
Worked with the movetostart :)

Was wondering, is this the right place to ask usage questions? Or is there some kind of forum or channel to post that kind of questions?

**Comment by FetFlex** [comment]
Hi Again,

One more question :)

I want to filter out the results in my PivotTable. But i am unsure (if possible) with ImportExcel:
![image](https://user-images.githubusercontent.com/24461360/41243465-815d3b3c-6da2-11e8-988b-750ef2fb416b.png)

![image](https://user-images.githubusercontent.com/24461360/41243481-8c07a25c-6da2-11e8-94ff-17ebb87b7dfd.png)

**Comment by dfinke** [comment]
This may work
https://github.com/dfinke/ImportExcel/blob/master/Examples/PivotTableFilters/testPivotFilter.ps1

**Comment by FetFlex** [comment]
Ahh yes. I did not see that in the version installed on this laptop. After i upgraded it was there.

I could not get it working when i specified it in the PivotTableDefinition. But if i specified it as a extra parameter it worked :)
```
$excel = Export-Excel -Path $outputLocationFull -PassThru
    $pt = [ordered]@{}
    $pt.Overblik=@{ SourceWorkSheet   = 'AllData';
               PivotRows         = 'organization-name'
               PivotColumns      = 'Type'
               PivotData         = @{'Type'='Count'}
               PivotFilter       = 'Status'
               PivotDataToColumn = $true
               TableStyle = "Medium6"
               ColumnHeaderCaption = "Typer"
               #IncludePivotChart = $false
               #ChartType         = 'BarClustered3D'
    }
    $excel = $alldata | Export-Excel -ExcelPackage $excel -WorkSheetname "AllData" -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -PassThru #-HideSheet "AllData" 
    $excel = Export-Excel -ExcelPackage $excel -PivotTableDefinition $pt -PassThru -HideSheet "AllData"  -PivotFilter 'Status'
```

Is it possible to set the filter? So it starts filtered like "status -eq 'Active'" ?

**Comment by dfinke** [comment]
Good question, please post that as an issue so it can be tracked for investigation. Thanks!

**Comment by FetFlex** [comment]
Sure thing 😄 
#349
