### ISSUE TITLE
Pulling O365 licenses only pulls one license

### ISSUE THREAD

**Issue by bonksnp** [dfinke/ImportExcel#346]
Hello!  First of all, I love this module!  I watched all of your tutorials and I wish there were more so I can bedazzle everything I export, but I will keep practicing.  Second, this is my very first post anywhere on Github so I hope I'm not out of line here but I may have come across a bug that you may or may not already know about (sorry I'm not completely sure how to search for known issues in GitHub yet).

When exporting licenses from Office 365 I've always exported to a csv which would show me any blocked users that still have licenses assigned to them.  The basic code is
`Get-MsolUser -All | Where-Object {$_.BlockCredential -eq $true} | select UserPrincipalName,Department,{$_.Licenses.AccountSkuID} | Export-csv C:\Users\etc...\users.csv`

When I tried with export-excel I didn't change anything other than export-excel
`Get-MsolUser -All | Where-Object {$_.BlockCredential -eq $true} | select UserPrincipalName,Department,{$_.Licenses.AccountSkuID} | Export-Excel -Path C:\Users\etc...\usersExcel.xlsx`

When I export-csv, a few of the users have multiple licenses which all show up.  Unfortunately when I export-excel I only see one license listed for users (appears to be the first license listed).  Am I maybe doing something wrong or missing a parameter that would get all of the licenses?

Thanks!

**Comment by dfinke** [comment]
@bonksnp Thanks for the issue. Congrats on your first post. Good work. I'm going to lift your `bedazzle` verb. Off the top of my head, I believe in `Export-Excel` I don't detect and drill into a property if it is an object. I'll check that out.

**Comment by PrzemyslawKlys** [comment]
Potentially solved by https://github.com/dfinke/ImportExcel/pull/412

**Comment by PrzemyslawKlys** [comment]
On another hand. I've same result with Master version and the one from pull request;

![image](https://user-images.githubusercontent.com/15063294/43717185-026fdd96-9987-11e8-938f-aba8877273a8.png)

For both CSV and XLSX. I would say query may be problematic here.

**Comment by jhoneill** [comment]
Would
`Get-MsolUser -All | Where-Object {$_.BlockCredential -eq $true} | select UserPrincipalName,Department,{$_.Licenses.AccountSkuID -join ", " } | Export-Excel -Path C:\Users\etc...\usersExcel.xlsx`
give you what you want ?

**Comment by KonTheCat** [comment]
My apologies on the shameless self-promotion, but this may be a prettier approach. The first function in the script I wrote for O365 reporting linked below will turn the SKUs into human-readable names, if that is something you are interested in.

https://github.com/KonTheCat/GetOffice365PerUserReport/blob/master/GetOffice365PerUserReport.ps1

**Comment by dfinke** [comment]
@KonTheCat that link gets a 404

**Comment by KonTheCat** [comment]
@dfinke thank you, I guess I should not have tried to edit it...I am somewhat new to this too!
