### ISSUE TITLE
Merge Cells in worksheet

### ISSUE THREAD

**Issue by helmutsreinis** [dfinke/ImportExcel#347]
Hello,

I haven't been able to figure out how to merge specific range of cells.

My suspicioun is that it should look similar to this, but it does not.

any feedback will be greatly appreciated.

![image](https://user-images.githubusercontent.com/34469685/41188413-40374442-6bc5-11e8-8723-31fa370371dd.png)

**Comment by dfinke** [comment]
@helmutsreinis please post the code, rather than an image. That way it can be copied and pasted to try.

**Comment by dfinke** [comment]
Looks like this is how to use it, not sure it'll give you the results you want.

```powershell
$f='C:\temp\test.xlsx'
C:\temp\test.xlsx -ErrorAction Ignore

$xl = import-csv .\Examples\PassThru\sales.csv | Export-Excel $f -PassThru 
$sheet1 = $xl.Workbook.Worksheets['Sheet1']
$sheet1.Cells["A1:C1"].merge = $true

Close-ExcelPackage $xl -Show
```

**Comment by helmutsreinis** [comment]
$sheet1.Cells["A1:C1"].merge = $true was what I was after. didn't notice that merge required Boolean as parameter.
