### ISSUE TITLE
PivotTable - ability to Name the PT Sheet

### ISSUE THREAD

**Issue by Penkethboy** [dfinke/ImportExcel#352]
Is it possible to name the "Pivotsheet" created using -IncludePivotTable

Rather than the autogenerated one

e.g. -worksheetname "My Name" becomes "My NamePivotTable"
A work around is "My Name " becomes "My Name PivotTable" which is a bit better but not ideal

Ideally want to have "PT-My Name" or whatever i want to call it

Can't see any option to do this unless i missed it

**Comment by jhoneill** [comment]
If you use the pivot table definition option , the name of the pivot table(s) in the definition becomes the name of the tab. There isn't a parameter for it in export-excel but it would be fairly easy to add one.

**Comment by Penkethboy** [comment]
Thanks - will have a look at PT definition

And adding to Export-excel would be a nice addition :)

**Comment by dfinke** [comment]
* Supports naming the PivotTable sheet create https://github.com/dfinke/ImportExcel/commit/8052b56387c1525cd8c1e52adf813ab77fdb59f0
* Demos the -PivotTableName param https://github.com/dfinke/ImportExcel/commit/28129172281011ea141f67f4713319bb8a0f2c8a

**Comment by mi-hol** [comment]
"Demos the -PivotTableName param 2812917" results in error with version 5.0.0
```
Export-Excel : A parameter cannot be found that matches parameter name 'PivotTableName'.
At line:2 char:18
+     Export-Excel @ExcelParams
+                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-Excel], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Export-Excel
```

Get-InstalledModule ImportExcel

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
5.0.0      ImportExcel                         PSGallery            PowerShell module to import/export Excel

and manually commented out 
'#   . $PSScriptRoot\Merge-Worksheet.ps1" as in https://github.com/dfinke/ImportExcel/issues/363

**Comment by dfinke** [comment]
@mi-hol I haven't published this. Did fix the the PivotTableName. Prepping to release 5.0.1
