### ISSUE TITLE
Failed import in Azure Automation

### ISSUE THREAD

**Issue by Matiszak** [dfinke/ImportExcel#356]
I tried to import the module from gallery(v 5.x) into Azure automation but it failed with error indicating that there is something wrong with package. 

Importing latest 4.x suceeded.

**Comment by dfinke** [comment]
Do you have the text of the error?

**Comment by Matiszak** [comment]
Freshly reproduced:

Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

**Comment by dfinke** [comment]
I'm guessing it may be related to this https://github.com/dfinke/ImportExcel/issues/354

Can you try and grab that ps1 from the repo, I'm working on fixing it.
