### ISSUE TITLE
PowerShell Excel Sub-Filter

### ISSUE THREAD

**Issue by raghavjagan** [dfinke/ImportExcel#357]
Hi PowerShell Techies,

I'am not able find how to do excel sub-filter using PowerShell, usualy $exl.selection.autofilter will filter the selected one.
Sub-Filter means, as per the Image attached I would like to filter a specific month from specific year. 
How do I achive it through PowerShell.
![image](https://user-images.githubusercontent.com/35920832/41604420-d6b024e0-73fc-11e8-98bb-33cf6ee01b5f.png)
Please help me on this.

**Comment by dfinke** [comment]
@jhoneill Is this doable?

**Comment by jhoneill** [comment]
Possibly through COM, but the list to select from isn't there while the file is being built, only when Excel opens it. Sadly.

**Comment by dfinke** [comment]
Yeah, thought only through COM. Too bad.
