### ISSUE TITLE
Error in Worksheet Naming - But character is valid in Excel

### ISSUE THREAD

**Issue by Penkethboy** [dfinke/ImportExcel#362]
When running my script i had the following error

Failed exporting worksheet 'Hvs-Home videos & photos' to 'Z:\software\Reports-2018-06-23-11-51-22.xlsx': Exception calling "Add" with "2" argument(s): "'"' is an 
unexpected token. The expected token is ';'. Line 1, position 164."
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.0.0\Export-Excel.ps1:1034 char:13
             throw "Failed exporting worksheet '$WorkSheetname' to '$P ...
             ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed exportin... position 164.":String) [], RuntimeException
    + FullyQualifiedErrorId : Failed exporting worksheet **'Hvs-Home videos & photos'** to 'Z:\software\Reports-2018-06-23-11-51-22.xlsx': Exception calling "Add" wit 
   h "2" argument(s): "'"' is an unexpected token. The expected token is ';'. Line 1, position 164."

The issue i believe is that the name of the worksheet contains a "&". This is easy enough to fix as a temp workaround.

However "&" is a valid worksheet naming character - so wondering why the script raises an error?

It appears that these 7 chars are not allowed in worksheet names in Excel (via google foo)
\
/
*
[
]
:
?
 
But virtually anything else is e.g.
Any letter from A to Z
Any number from 0 to 9
| (pipe symbol)
- (dash)
+ (plus)
@
#
$
$
^
&
(
)
_ (underscore)
, (comma)
. (period)
!

So what can and cannot be used with the module for Naming Worksheets?

Ps: Happens on 4.0.13 and 5.0.0

**Comment by jhoneill** [comment]
I've just tried it and I can create worksheets with & in their name. 
This message looks like originates in EPPlus.dll  the module just calls the ADD() method of the Worksheets collection, and passes whatever string you give as the name. 
We're a little behind on versions, but the current version of EPPlus (https://github.com/JanKallman/EPPlus/blob/master/EPPlus/ExcelWorksheets.cs )  catches : ? / \ [ ] , and replaces them with spaces. 
It's possible there is something else about the name which causes EPPlus a problem - possibly when builds the XML which with the worksheet name in it.

**Comment by dfinke** [comment]
nuget installed the latest EPPlus, `netstandard20` throws the below. Throws a different error for PS Core.
The 35 and 40 versions pass a quick simple sniff test.

Thinking of upgrading and pushing ImportExcel to v6.0.0. Risky for sure, and it answers issues like this and the dll now supports things like sparklines which I wanted to put in a while back.

I haven't drilled down on the `netstandard20` errors. Would love to see this work on core and linux. It seems the EPPlus team talks about this working with ASP.NET and macOS. I'm not currently in a position to go down this rabbit hole.

Thoughts?

```
Failed exporting worksheet 'Sheet1' to 'C:\Users\Douglas\AppData\Local\Temp\tmpDB13.xlsx': Exception calling ".ctor" with "1" argument(s): "Could
not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its
dependencies. The system cannot find the file specified."
At C:\Users\Douglas\Documents\GitHub\ImportExcel\Export-Excel.ps1:606 char:17
+ ...             throw "Failed exporting worksheet '$WorkSheetname' to '$P ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed exportin...ile specified.":String) [], RuntimeException
    + FullyQualifiedErrorId : Failed exporting worksheet 'Sheet1' to 'C:\Users\Douglas\AppData\Local\Temp\tmpDB13.xlsx': Exception calling ".ctor" w
   ith "1" argument(s): "Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f
  11d50a3a' or one of its dependencies. The system cannot find the file specified."
```

**Comment by Penkethboy** [comment]
Hi

From a bit more testing although the error implies that its related to the worksheet name - it turns out it actually the Tablename as i use the "same" string but with any spaces removed

So WorksheetName = "Hvs-Home Movies & No Photos" is fine as a Name - no errors thrown as @jhoneill pointed out
**but** a TableName = "Hvs-HomeMovies&NoPhotos" throws the error

As excel Tablenames - only support letters,numbers,period or underscore - from a bit more research 

Looking at the Excelworksheets.cs linked above it appears the Tablename is not subject to the same validation unless i missed it?

**Comment by jhoneill** [comment]
I'll see if can see anything on EPPlus, , but it would be 5 minutes work to add something to the module which strips invalid chars from table names (I should probably check range names, chart names, Pivottable names too).

**Comment by jhoneill** [comment]
It looks like 
Pivot tables allow anything that is allowed in worksheet names 
BUT tables and ranges are letters, digits, and underscores only (no spaces Punctuation etc. I'll put something is so table names get forbidden chard replaced with _ and I will send a warning when I do it.

**Comment by Penkethboy** [comment]
Thanks - i have done this in my script for now
