### ISSUE TITLE
import-module syntax error in 3 examples

### ISSUE THREAD

**Issue by mi-hol** [dfinke/ImportExcel#365]
After I did
`Install-Module ImportExcel` as administrator the code in sample: https://github.com/dfinke/ImportExcel/blob/master/Examples/PivotTable/PivotTableWithName.ps1 gives error:

```
Import-Module ..\..\ImportExcel.psd1 -Force
Import-Module : The specified module '..\..\ImportExcel.psd1' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module ..\..\ImportExcel.psd1 -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (..\..\ImportExcel.psd1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

changing it to 
```
Import-Module ImportExcel.psd1
``` 
works as expected :)

**Comment by mi-hol** [comment]
same issue is present in 3 more files:

Examples/CustomReporting/CustomReport.ps1
Examples/PivotTable/PivotTableWithName.ps1
Examples/ExcelToSQLInsert/DemoSQLInsert.ps1

**Comment by dfinke** [comment]
Did you try to run those examples from where they were installed? Or you copy and pasted it to the console?

**Comment by mi-hol** [comment]
I've copy and pasted it to the console

**Comment by dfinke** [comment]
Yeah, those examples are intended to be run from that location. I use it for testing. Let me think through a better approach so they can be used in both scenarios.

**Comment by mi-hol** [comment]
@dfinke did you get a chance to try my proposed solution?

**Comment by dfinke** [comment]
Check out the examples, I went with a different approach

**Comment by mi-hol** [comment]
@dfinke  thanks for fixing.
The example worked after I installed LibreOffice.

Due to '$ExcelParams = @{ ... Show = $false' there is a dependency on having Excel or a compatible program installed to run the examples successfully.
For a beginner this is somehow counter intuitive as the purpose is  'This PowerShell Module allows you to read and write Excel files without installing Microsoft Excel on your system'.
Maybe this fact should be noted in the example or changed?

**Comment by mi-hol** [comment]
the simple code that also works on non-Windows OS using PowerShell Core 6.0 and later:
$outputFile = "test1.xlsx"
Remove-Item $outputFile -ErrorAction Ignore

$ExcelParams = @{
    Path              = $outputFile
    IncludePivotTable = $true
    PivotRows         = 'Company'
    PivotTableName    = 'MyTable'
    PivotData         = @{'Handles' = 'sum'}
    Show              = $false
}

Get-Process | Select-Object Company, Handles |
    Export-Excel @ExcelParams 
Get-ChildItem $outputFile

**Comment by dfinke** [comment]
Yup, the `-Show` requires Excel. This module generates an xlsx when it runs on PS Core?

**Comment by mi-hol** [comment]
Using PS core 6.0.3 on Windows it does work :) 
Will try on Linux RHEL 7.x later this week.
With PS core 6.1 preview 4 running on WindowsSubsystem for Linux (WSL) on Ubuntu 18.04 it failed so far

**Comment by mi-hol** [comment]
https://github.com/PowerShell/PowerShell/issues/7451

**Comment by mi-hol** [comment]
@dfinke are you considering to deal with my comment :
"having Excel.. installed to run the examples successfully ... is somehow counter intuitive "?

**Comment by dfinke** [comment]
When EPPlus is fully xplat, these will be addressed

**Comment by mi-hol** [comment]
not sure to understand what is the meaning of "When EPPlus is fully xplat,".
Would you mind to elaborate?

**Comment by mi-hol** [comment]
@dfinke  EPPlus.Core works under WSL already.
nuget install EPPlus.Core did the trick
Guess the missing piece is adding this as a dependency to the ImportExcel package

**Comment by dfinke** [comment]
I tried the 4.5.x dll nuget with import Excel. Did the import-module and it failed on System.Drawing

**Comment by mi-hol** [comment]
I understand you are en expert but with the very brief comments I fail to understand the difference between your failing and my working approach.
I'd love to help and move this forward, but that requres more detailed information and maybe even a shared 'workspace' to collaborate.
As I understand it before a simple 'Import-Module -Name importexcel' can actually work, changes to the module definition are required.

**Comment by mi-hol** [comment]
I got it work following the fix in https://github.com/JanKallman/EPPlus/issues/224#issuecomment-411125654

**Comment by dfinke** [comment]
I was able to run the module on my Linux VM in Azure and on my local machine PS Core 6.

Until PS Core is GA and it can run in Appveyor with continuous integration and more tests. Use it at your own risk.

https://ci.appveyor.com/project/dfinke/importexcel/build/1.0.171
