### ISSUE TITLE
Unable to import excel thru web share link

### ISSUE THREAD

**Issue by Ayanmullick** [dfinke/ImportExcel#369]
I'm unable to import an excel sheet thru it's Share link. 

`Import-Excel -Path https://1drv.ms/x/s!Ak67VsqlkjC1j7Yq3tQ869fj_w1Ehw -WorkSheetname Sheet1`

Error:  `Import-Excel : Cannot validate argument on parameter 'Path'. The "(Test-Path -Path $_ -PathType Leaf) -and ($_ -match '.xls$|.xlsx$|.xlsm$')" validation script for the argument with value "https://1drv.ms/x/s!Ak67VsqlkjC1j7Yq3tQ869fj_w1Ehw" did not return a result of True. Determine 
why the validation script failed, and then try the command again.`

Is there a workaround to accomplish this ? End goal is to import it into an Azure Automation Runbook.

NB: OneDrive won't enable FTP access anytime soon.

**Comment by dfinke** [comment]
The target Excel file needs to be an xlsx. Can you download it from the link first and then rename it?

**Comment by Ayanmullick** [comment]
The target Excel file is 'Book1.xlsx'. 
It is downloadable with the link above. Is there any further reason to rename it? I created the link with 'View' rights.

**Comment by dfinke** [comment]
I've tested `Import-Excel` with local and UNC files. The path `https://1drv.ms/x/s!Ak67VsqlkjC1j7Yq3tQ869fj_w1Ehw` needs to point to `Book1.xlsx`. I have not tried `Import-Excel` with that form of shared link.

The workaround could be download it from the link first.

**Comment by Ayanmullick** [comment]
The path does point to the file. You can open it in any browser. Downloading is inconvenient when I'm trying to import the sheet in an Azure Automation runbook.

**Comment by dfinke** [comment]
Import-excel needs a file with the proper ext. In don't know how to get the UNC for that.

**Comment by Ayanmullick** [comment]
Could the module be enhanced to also accept Onedrive http WebShare Links for excel files?

**Comment by dfinke** [comment]
It could if you can figure out how to represent that link and pass it from PS to the EPPlus library

**Comment by Ayanmullick** [comment]
After implementing an app to access one's OneDrive per below url the below cmdlet will download the file.

https://www.sepago.de/en/

`$Auth= Get-ODAuthentication -ClientID <>
Get-ODItem -AccessToken $Auth.access_token -Path "/<>/<>/Book1.xlsx" -LocalPath c:\ -LocalFileName Book1.xlsx `

**Comment by Ayanmullick** [comment]
Using [PSKit](https://github.com/dfinke/PSKit)'s [Read-Csv](https://github.com/dfinke/PSKit/blob/master/ReadCsv.ps1) as a workaround. 👍 

`Read-Csv -target https://raw.githubusercontent.com/dfinke/PSKit/master/sampleCsv/aapl.csv|ft`

**Comment by dfinke** [comment]
Nice, would like to hear a bit more about how this worked an not the other approaches.

**Comment by Ayanmullick** [comment]
`Import-Excel` or `Import-Csv` couldn't read directly from OneDrive or GitHub. `Read-Csv` could.

`Import-Excel -Path https://raw.githubusercontent.com/dfinke/PSKit/master/sampleCsv/aapl.csv`
**Error**: `Import-Excel does not support reading this extension type .csv`

`Import-Csv -Path https://raw.githubusercontent.com/dfinke/PSKit/master/sampleCsv/aapl.csv`
**Error**: `Import-Csv : Cannot find drive. A drive with the name 'https' does not exist.`

**Comment by dfinke** [comment]
Ah, yes, that's why I build `Read-Csv`. `Import-Csv` only reads files. If you look at the `Read-Csv` function, it figures out if what is passed is a string, url, or file name and then calls the appropriate function to do the work.
