### ISSUE TITLE
IP Addresses not formated as text

### ISSUE THREAD

**Issue by stolaf** [dfinke/ImportExcel#37]
Get-NetIPAddress -AddressFamily IPv4 | Select-Object IPAddress,InterfaceAlias,ifIndex,PrefixLength| Export-Excel -Path 'C:\Temp\IPAddresses.xlsx' -WorkSheetname 'IPAddresses' -Show

If you try this you'll see that the ip-address is shown as number

**Comment by dfinke** [comment]
I'm not positive if I'm seeing what you're getting. It may have been fixed recently.

![image](https://cloud.githubusercontent.com/assets/67258/9999920/04ce0e8e-6067-11e5-88b1-0fa675000d11.png)

**Comment by stolaf** [comment]
![unbenanntes bild](https://cloud.githubusercontent.com/assets/2017141/10013846/4c7fb170-6115-11e5-9cf0-142400a0adf8.png)

I use the lastet Module Version (Excel is in German!?)

**Comment by Claustn** [comment]
I think it is related to the difference in the number separator character, I am seeing the same as solaf in a Danish version of Excel.

**Comment by stolaf** [comment]
prima that works well

**Comment by dfinke** [comment]
Thanks @Claustn. Nice workaround.
