### ISSUE TITLE
Two failing asserts for compare-worksheet

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#375]
Commented out for now. Needs to be checked.

https://github.com/dfinke/ImportExcel/blob/master/__tests__/Compare-WorkSheet.tests.ps1#L89
https://github.com/dfinke/ImportExcel/blob/master/__tests__/Compare-WorkSheet.tests.ps1#L165

**Comment by jhoneill** [comment]
I'll check this.

**Comment by jhoneill** [comment]
I also need to make a small change to the tests. It turns out the order of things returned in a diff operation changes when you move between the plain shell and the ISE. So I need to insert a sort operation or two :-(

**Comment by dfinke** [comment]
yeah, was re-running the tests locally and they failed in on other asserts, but it worked with Appveyor. This is unfortunate.
