### ISSUE TITLE
TableRanges - with Multiple Tables per worksheet

### ISSUE THREAD

**Issue by Penkethboy** [dfinke/ImportExcel#376]
I have been experimenting with putting multiple tables on the same worksheet using your MultipleTables example.

The issue i have is that if the tables have varying ranges. The subsequent tables have a range equal to the largest table range set to date and the visual presentation looks a bit odd.

Example 1 - Increasing Table size
![capture1a](https://user-images.githubusercontent.com/21155304/42282955-fbee79ec-7f9f-11e8-951f-aec22d9a251c.JPG)

Example 2 - Decreasing Table size
![capture2](https://user-images.githubusercontent.com/21155304/42282990-13c51a44-7fa0-11e8-80eb-f6b70c9c17eb.JPG)

As you can see in the second example the second table has a range equal to the first of 12 rather than 10.

Its appears that possibly a variable is not reset for each new table and just increased if it's smaller than the new table range. 

So not sure if this is a Export-Excel or Epplus or Excel issue.

Modified code below in case i am missing something

$xlfile = "testMultTables.xlsx"
rm *.xlsx

$r = Get-ChildItem C:\WINDOWS\system32 

$BySize=@{}
$r | ForEach{ $BySize.($_.extension)+=$_.length }

$top10BySize = $BySize.GetEnumerator() | 
    ForEach{ [PSCustomObject]@{Name=$_.key;Size=[double]$_.value} } | 
    Sort size -Descending | 
    Select -First 10

$top12ByCount = $r.extension | 
    Group | 
    Sort count -Descending | 
    Select -First 12 Name, count

$top14ByFileSize = $r | 
    Sort length -Descending | 
    Select -First 14 Name, @{n="Size";e={$_.Length}} #,Extension,Path

#$r | Export-Excel $xlfile -WorkSheetname FullData
$test = "balh blah"
$Test | Export-Excel $xlfile -WorkSheetname FileInfo -StartRow 1 -StartColumn 1
$top10BySize     | Export-Excel $xlfile -WorkSheetname FileInfo -TableName ExtSize -StartRow 2
$test = "balh blah2"
$Test | Export-Excel $xlfile -WorkSheetname FileInfo -StartRow 1 -StartColumn 4
$top12ByCount    | Export-Excel $xlfile -WorkSheetname FileInfo -TableName ExtCount -StartRow 2 -StartColumn 4
$test = "balh blah3"
$Test | Export-Excel $xlfile -WorkSheetname FileInfo -StartRow 1 -StartColumn 7
$top14ByFileSize | Export-Excel $xlfile -WorkSheetname FileInfo -AutoSize -TableName FileSize -StartRow 2 -StartColumn 7

$ps = Get-Process | Where-Object Company
#$PS | Export-Excel $xlfile -WorkSheetname PSData

$test = "balh blah4"
$Test | Export-Excel $xlfile -WorkSheetname Handles -StartRow 1 -StartColumn 1
$ps | 
    sort handles -Descending | 
    select -First 12 company, handles | 
    Export-Excel $xlfile -WorkSheetname Handles -AutoSize -TableName Handles -StartRow 2

$test = "balh blah5"
$Test | Export-Excel $xlfile -WorkSheetname Handles -StartRow 1 -StartColumn 4
$ps | 
    sort PM -Descending | 
    select -First 10 company, PM | 
    Export-Excel $xlfile -WorkSheetname Handles -AutoSize -TableName PM -StartRow 2 -StartColumn 4 -Show

**Comment by jhoneill** [comment]
I'll check properly but IIRC when a table is setup it goes to the last row of the sheet so growing tables look fine and shrinking ones give the effect you describe.  If I got that right I'll see how easy or difficult it is to change it.

**Comment by jhoneill** [comment]
Quicker than I thought Round about line 700 in export-Excel.ps1 you have this 
```
                $csr = $StartRow

                $csc = $StartColumn
                $cer = $ws.Dimension.End.Row
                $cec = $ws.Dimension.End.Column 
```
So that's where you started inserting down to the bottom right corner of the sheet

Can you try changing the last two lines to 

```
$cer = $row 
$cec = $columnIndex
```

That should be the last cell inserted.  Easy to see why it was assumed that the last cell and bottom right corner would be the same

 If that works I'll add it to the changes I'm doing for the next version - I'll need to look at other places where "bottom right corner" is present and needs changing :-)

**Comment by Penkethboy** [comment]
Tried your suggested changes and although the range is "better" in some respects the output is a bit funky now.
have an extra column in each table range
![capture1a](https://user-images.githubusercontent.com/21155304/42296322-5fa0d6dc-7fec-11e8-8886-4b37a147eb5a.JPG)
and
![capture2](https://user-images.githubusercontent.com/21155304/42296323-657a9ba6-7fec-11e8-8230-4036f19657c1.JPG)

**Comment by Penkethboy** [comment]
Ok not sure what happened with the above but working ok now

I shutdown the ise i was using between changes i made to the export-excel file and that appears to have cleared the issue above - something hanging around i guess

Thanks look forward to the changes coming through on the next release etc

**Comment by Penkethboy** [comment]
Just tested this against on a much larger dataset with $cec = ColumnIndex-1 and it generated 38 two column tables all with varying numbers of rows on the same sheet with no issues

**Comment by jhoneill** [comment]
Yes it does need to be columnindex -1    (column index gets incremented after each column is processed inserting cells so when the last cell is processed it is has got the extra 1 on it.)  
 
I'll test doing this more widely.

**Comment by jhoneill** [comment]
I've checked in code to do all of this now, and your example has become one of the standard tests.

**Comment by Penkethboy** [comment]
Cool - Thanks
