### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#379]
@jhoneill moved and commented out tests, only a few.

I'm thinking I need to work on feature branches and then do a PR to merge back to master. Might reduce the conflicts, maybe.

https://ci.appveyor.com/project/dfinke/importexcel/build/1.0.73
https://ci.appveyor.com/project/dfinke/importexcel/build/1.0.74
https://ci.appveyor.com/project/dfinke/importexcel/build/1.0.75

**Comment by jhoneill** [comment]
I can spot what those are 
First one in .73 is there is no Excel on the server to start. 
The others are basically a very short list of processes the tests are written to use 50 and get 31 when they ask for the first or last 50. The number of processes can be reduced ...
