### ISSUE TITLE
export from Gui

### ISSUE THREAD

**Issue by chrisk59** [dfinke/ImportExcel#38]
hello, i have an issue (or not, you'll tell me). i have a gui with a button to export something, the name of the file is define with a date.
 So each time you click on the button the name should change.. but in real, the name (the variable) change but it still write to the first file. i'm not able to write to a new named file.
i hope it's clear.. 8-(

**Comment by dfinke** [comment]
Please could you show the code that is doing this. That  way it can be better diagnosed.

Thanks

**Comment by chrisk59** [comment]
hmm hard to show, it's a long code .. 
i just tested a normal gui script (one button), with 2 exports with 2 differents date, it's working .. so i think it's about my gui environnement .. i'll dig into this problem ..

**Comment by dfinke** [comment]
Great, post questions if you need help
