### ISSUE TITLE
Missing check whether $WorksheetName is longer than 31 characters

### ISSUE THREAD

**Issue by grassynull** [dfinke/ImportExcel#384]
Hi, Doug. I've been working with ImportExcel for a few days. This is a great module. 👍 

I found an oversight in validation of `$WorksheetName`. If it is longer than 31 characters, it will be truncated (I think) during the `$pkg.Save()` call inside `Export-Excel.ps1`. I haven't looked much into the EPPlus library to see how it works, but the maximum legal length for any worksheet name in Excel is 31 characters.

If you try to export two worksheets whose names begin with the same 31 characters into the same workbook, an exception will be thrown (because either `$pkg.Save()` or ` $ws = $ExcelWorkbook.Worksheets.Add($WorkSheetname)` will fail). Further, if the second worksheet's name is exactly 31 characters, then it will replace the first worksheet if `ClearSheet = $True`.

I cloned the repo and tested the following:

```
$ModulePath = $env:USERPROFILE + "\Documents\GitHub\importexcel\ImportExcel.psm1"

Import-Module -Name $ModulePath

$Path = $env:USERPROFILE + "\Documents\GitHub\importexcel\__tests__"
$Path += '\LongWorksheetNames.xlsx'

$LongName1 = "ThisWorksheetNameIs31CharactersAndThenSome"
$LongName2 = "ThisWorksheetNameIs31Characters"

$ExcelParams1 = @{
    Path = $Path;
    WorksheetName = $LongName1;
    ClearSheet = $True
}

$ExcelParams2 = @{
    Path = $Path;
    WorksheetName = $LongName2;
    ClearSheet = $True
}

$LongName1 | Export-Excel @ExcelParams1
$LongName2 | Export-Excel @ExcelParams2
```

This block will run without errors if the workbook at `$Path` does not exist. But the workbook will contain a single worksheet containing `$LongName2`. Run the block again, and the exception in the `else` block (line 576) is thrown: 

```
Catch {
	if ($AlreadyExists) {
		#Is this set anywhere ?
		throw "Failed exporting worksheet '$WorkSheetname' to '$Path': The worksheet '$WorkSheetname' already exists."
	}
	else {
		throw "Failed preparing to export to worksheet '$WorkSheetname' to '$Path': $_"
	}
```
(I do not see any place where `$AlreadyExists` is set. I think the `if` block is unused.)

If you delete the workbook and swap the values of `$LongName1` and `$LongName2`, then an exception is thrown when exporting `$LongName2`, since its worksheet name gets truncated to 31 characters and collides with the first worksheet. The same occurs if you comment out `$LongName2` and try to re-export of `$LongName1`. That is how I originally ran into this problem.

I don't know what the best solution is. I suspect most users would prefer to let the export to Excel continue with the truncated worksheet name (and perhaps with a warning written to the console) as they probably won't have several worksheet names beginning with the same 31 characters. Truncating the worksheet names to 31 characters (and modifying characters at the end to make each worksheet name unique) would work, but is this a solution best left to the user? For example, this module doesn't stop you from trying to name a worksheet with forbidden characters

**Comment by Penkethboy** [comment]
FYI - i already do this in my code rather than relying on Export-excel to do this - if its added fine no problem.

If you are modifying things then add in a check for "History" as that is an invalid worksheet name for excel - its used for some hidden validation by excel - if you manually create a worksheet called History you will get an error shown by excel.

**Comment by jhoneill** [comment]
When a sheet is added the EPPlus library will try to make an illegal name into a legal one.
The latest code I have checked in looks to see if the name of the new sheet is the name which was requested. If it isn't it tries to work with the new name and flags a warning to the user. This is better than before and avoids losing the data if the worksheet name is wrong; but it the test for legal names could be more complete.
