### ISSUE TITLE
Keep PowerShell Gallery up to date

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#386]
@dfinke would be great if publishing in the PowerShell Gallery could be done simultaneously and automatically when updating code on GitHub. This way they would always be in sync.

Especially for people running `Update-Module` on test or production systems.

**Comment by dfinke** [comment]
That would be good, not enough tests or gates in place to make sure the release is a good one.

It is a goal.

**Comment by jhoneill** [comment]
I have to echo @dfinke  here. What is committed to GitHub is ready to test, what goes onto PSGallery has an implication of being ready for production (not in the sense of a legal warranty) .  
Speaking for myself I wouldn't see "the developer has committed it"  as meaning "it is ready for production"

**Comment by DarkLite1** [comment]
I see what you mean, never looked at it this way. I'll close the issue then until there are more tests to guarantee a solid release schedule. An other option would be to have dev branch and a stable branch. But I leave that open.

**Comment by dfinke** [comment]
More interesting would be to "package" passing builds out of appveyor and eventually travis-ci.  Not in the gallery, but the community could grab a latest build before it is promoted to "production".
