### ISSUE TITLE
Delete text from Excel worksheet using Export-Excel

### ISSUE THREAD

**Issue by sighmonsays** [dfinke/ImportExcel#387]
Hello! 

Is it possible to actually delete text from a worksheet using Export-Excel? 
I've been trying to figure out if it's possible to use New-ConditionalText or Add-Conditional Formatting but I'm having no luck. Do you have any insight?

Thanks!

**Comment by dfinke** [comment]
You can manipulate cell content with Set-Format.

Export-Excel works with arrays of objects. You could read the data with Import-Excel. modify it in PowerShell and then export it

**Comment by jhoneill** [comment]
Set format, set row and set column can all set the content of a cell to an empty string; at the moment they don't allow NULL as a parameter. 
The worksheet object's CELL collection has a .clear() method , and the worksheet has insert/Delete row/column methods. If there is a need PowerShell functions could be added to wrap any or all of these.
