### ISSUE TITLE
Hide Tab/Worsksheet

### ISSUE THREAD

**Issue by forensicsguy20012004** [dfinke/ImportExcel#39]
I am doing everything in Posh, systematically.

Below is my example; the "usage" and "domain" tabs are the raw data sets or the "-IncludePivotTable." However both of those two tabs/worksheets are the same data, the two pivot tables are different. One pivot table is a count of usage and the other pivot table is counts based on domain assets. I would like to "hide" the domain tab as it is just a duplication of the usage tab.
![image](https://cloud.githubusercontent.com/assets/12624999/10103673/34088d3c-6373-11e5-9327-d9e7e8d9ac58.png)

**Comment by dfinke** [comment]
I'll look into seeinf if that is possible

**Comment by dfinke** [comment]
Thanks for the question.

I checked in a new version that supports -HideSheet. There's a bug in the underlying DLL, EPPlus. It does not let you hide the first sheet. I'm working on a repro that I can get so it can be fixed

**Comment by forensicsguy20012004** [comment]
Great work everyone.

**Comment by forensicsguy20012004** [comment]
I have done some preliminary testing with the revised function [Export-Excel.ps1]; and everything seems to be operating as expected. I will continue to test and evaluated, if any issues arise I will report them to the team. Again great work and thank you everyone for the hard work. 

If I wanted to post a potential idea, a new functionality per say, should I open another "issue" or is there  a designated board for ideas?

Thank you again,
Forensicsguy20012004

**Comment by dfinke** [comment]
Posting here on github works best. 

Thanks
Doug

**Comment by forensicsguy20012004** [comment]
I think we can close this. I am good with this issue being resolved.
