### ISSUE TITLE
Trouble Getting a Specific Range

### ISSUE THREAD

**Issue by jubejube56** [dfinke/ImportExcel#391]
Hello! I'm having trouble understanding the syntax for XRange and YRange in the New-ExcelChartDefinition HashTable. Specifically I am wanting to create a XYScatterLines chart with a lot of series (eventually looping through every row to create a scatter line for each) , but I do not know how to specify a pair of cells for either XRange or YRange to create coordinates in the first place. I tried to read through the documentation for Get-XYRanges but I just started doing PowerShell-related work on Tuesday so it is kind of going over my head right now.

This is an example what what I'm trying to accomplish minus the loop.
New-ExcelChartDefinition -Title "Avg CPU Time Spent Per Query" -ChartType XYScatterLines -XRange "{=Data!O$3,Data!P$3}" -YRange "{=Data!D$3,Data!I$3}"  -SeriesHeader "Query 1" -Row ($RowCount."RowCount" + 20) -Column 0

Thank you in advance.

**Comment by dfinke** [comment]
This may help
https://github.com/dfinke/ImportExcel/blob/master/Examples/Charts/MultiSeries.ps1

**Comment by jhoneill** [comment]
Normally the labels and series are in neighbouring columns, which these aren't but you can just specify them as follows :  
`$def = New-ExcelChartDefinition -Title "Avg CPU Time Spent Per Query" -ChartType XYScatterLines -XRange "B3:E3}" -YRange "B4:E4","B5:E5" -SeriesHeader "Query 1","Query2"
`
You can use that in 
`export-excel -ExcelChartDefinition $def <<other parameters>>`

If the data is already in an xlsx file you can do 
```
$excel = Open-ExcelPackage -Path "C:\Users\mcp\AppData\Local\Temp\myTest.xlsx"
Add-ExcelChart -Worksheet $excel.Workbook.Worksheets["sheet1"] -Title "Avg CPU Time Spent Per Query" -ChartType XYScatterLines -XRange "B3:E3}" -YRange "B4:E4","B5:E5" -SeriesHeader "Query 1","Query2"
Close-ExcelPackage $excel -Show
```
(-show is optional at the end)


if you are going to write it as a loop then you just need to build up an array which contains the ranges you want...

**Comment by jubejube56** [comment]
Thank you for the quick responses. The first part of the second solution is working just like I needed it to.
