### ISSUE TITLE
Export-Excel Move* unexpected results

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#392]
```powershell
$xlfile = "$env:TEMP\testThis.xlsx"
rm $xlfile -ErrorAction Ignore

1..10  | Export-Excel $xlfile -WorkSheetname First
11..20 | Export-Excel $xlfile -WorkSheetname Second -MoveToStart
21..30 | Export-Excel $xlfile -WorkSheetname Third  -MoveBefore First
31..40 | Export-Excel $xlfile -WorkSheetname Fourth -MoveAfter Third -Show
```

Expected  the worksheet order to be `Second|Fourth|Third|First`

![image](https://user-images.githubusercontent.com/67258/42734687-46eb21b0-8816-11e8-8967-d8e3f380e43c.png)

**Comment by jhoneill** [comment]
I'll check. I had to fix something which was wrong with move before and I may have not got move after correct. 
The order should go 
first
Second First
Second third first
Second third fourth First.

**Comment by jhoneill** [comment]
Committed the fix.

**Comment by dfinke** [comment]
Do you have an example you could post?

**Comment by jhoneill** [comment]
I get that behaviour even without the move.  What I notice in excel is if I enter a range name excel translates it to an address 
Examples where it works and where it fails would be really helpful

**Comment by jhoneill** [comment]
I tried this 
```
$data = @"
A,B,C,Date
2,1,1,2016-03-29
5,10,1,2016-03-29
"@

$c = New-ExcelChartDefinition -ChartType Line  -Title Impressions   -Row 0 -Column 0`
    -XRange "Impressions[Date]" `
    -YRange @("Impressions[B]","Impressions[A]") `
    -SeriesHeader 'B data','A data' `

$data | ConvertFrom-Csv |   Export-Excel -path temp.xlsx -AutoSize -TableName Impressions
```

If I follow it with
 `
Export-Excel -path temp.xlsx -worksheetName chartPage -ExcelChartDefinition $c  -show `

All is good. If I close Excel and run 
```
Export-Excel -path temp.xlsx -WorkSheetname sheet1 -MoveToEnd  -Show
```
The chart breaks.  But I get the same if I place the chart page before the data page like this
```
Export-Excel -path temp.xlsx -WorkSheetname chartPage
$data | ConvertFrom-Csv |   Export-Excel -path temp.xlsx -AutoSize -TableName Impressions
Export-Excel -path temp.xlsx -worksheetName chartPage -ExcelChartDefinition $c  -show
```

It looks like a bug in EPPlus which says a table can only be the source of a chart if the chart comes on a later page

**Comment by jubejube56** [comment]
Sorry I was away on the weekend but what you described is exactly what I had (just with a different move statement). Sounds like it is out of your control though which sucks, but ranges still work so it isn't a big deal.
