### ISSUE TITLE
Investigate enabling this syntax for Add-WorkSheet

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#393]
```powersherll
Add-WorkSheet -ExcelPackage $excel -CopySource Sheet1
```

**Comment by dfinke** [comment]
Yeah, just a short form to copy `sheet1` to the target package, and if a destination sheet was not specified it create a new one.

**Comment by jhoneill** [comment]
OK changed the way Add-Worksheet works. 
- If worksheetname and clearsheet specified, delete the worksheet if it exists. 
- If worksheetname not specified and copying and sheet name does not already exists, use the copied sheet name as the destination name
- else if WorkSheetName not specified use sheetX where X is number of existing sheets +1 
[Change - if whatever calls Add-Worksheet wants "Sheet1" it must say so explicitly, Add-worksheet won't return _existing_ sheet1 when nothing is specified - it will _add_ sheet2 - I've fixed this in Export-Excel and it doesn't cause any other tests to fail] 

Just check this in :-)
