### ISSUE TITLE
Copy-ExcelWorkSheet Only copy the firtst Colum of the Worksheet 

### ISSUE THREAD

**Issue by NoeB** [dfinke/ImportExcel#395]

**Comment by dfinke** [comment]
@NoeB please could you provide the sheet that has the issue (or a representative sample)

**Comment by NoeB** [comment]
Copy-ExcelWorkSheet -DestinationWorkbook $Pfadsollexcel -SourceWorkbook $xlsx -SourceWorkSheet "Tabelle1" -DestinationWorkSheet "Differenzen"
[xlsx.xlsx](https://github.com/dfinke/ImportExcel/files/2201709/xlsx.xlsx)
[Pfadsollexcel.xlsx](https://github.com/dfinke/ImportExcel/files/2201710/Pfadsollexcel.xlsx)

**Comment by jhoneill** [comment]
xlsx.xslx is was a csv file which has been converted to XLSX. The first row is the object type, and there is only an entry in A1 and the rest of row 1 is empty. The current copy does import | export, and the import sees it the source data as one column 

@dfinke  I will re-write copy to use the new copy functionality on add worksheet.

**Comment by dfinke** [comment]
@jhoneill Cool, was wondering if the `Copy-ExcelWorkSheet` ought to be deprecated in lieu of the new copy.  Having `Copy-ExcelWorkSheet` use it directly makes sense.

**Comment by jhoneill** [comment]
Done, and checked in. It's a lot more complicated than the old one. And EPPlus copies formatting but not hyperlinks. I've included a couple of tests :-)  but they're little more than kicking the tyres. :-(
