### ISSUE TITLE
Customizing IconSets

### ISSUE THREAD

**Issue by jubejube56** [dfinke/ImportExcel#396]
Hello again,
 
I am wanting to format some columns using ThreeIconsSets based on parameters I specify as well as reversing the order of icons and changing the "type" of condition from the default of percent to number. New-ConditionalFormattingIconSet has the reverse option but no way to specify conditions and Add-ConditionalFormatting has conditions but no reverse option. Specifying conditions also seems to have no effect on the values of the icon set though it is very likely I am just messing up syntax or something like that. If it is possible to specify an IconSet in the module like this, what would the syntax be?

Thank you in advance

**Comment by jhoneill** [comment]
OK. Some background. 
When @dfinke  first wrote Export-Excel he gave it some conditional formatting parameters the idea was that you could use a simple command New-ConditionalText or  New-ConditionalFormattingIconSet hand the results onto export-excel and cover more than half of all conditional format requirements. 
When I first got involved I wrote Add-ConditionalFormatting  which is more complicated and supports more options. 
I don't know why but I never put "reverse" in but that would be quick. 

There are 40-something different kinds of conditional formatting rule and each one has different 
properties which can be set, but I didn't write add-conditionalFormatting to support every property on every rule.  I can add more things of course. 

What you can do is set the rule to roughly what you want with export-excel and then change it to fit exactly like this. 
```
$XL = Export-excel <<Parameters>> -Passthru
$cf = $xl.Workbook.Worksheets["<<Worksheet Name>>"].ConditionalFormatting
```
This will get the data into the sheet and give you an easy way to work with conditional formatting.  Note that the first ConditionalFormatting rule is number 0, the second is 1 
```
$cf[0].icon1.type = [OfficeOpenXml.ConditionalFormatting.eExcelConditionalFormattingValueObjectType]::num 
$cf[0].icon1.Value= 0
$cf[0].icon2.type = [OfficeOpenXml.ConditionalFormatting.eExcelConditionalFormattingValueObjectType]::num 
$cf[0].icon2.Value= 70
$cf[0].icon3.type = [OfficeOpenXml.ConditionalFormatting.eExcelConditionalFormattingValueObjectType]::num 
$cf[0].icon3.Value= 100
```
then you can do. 

`Close-ExcelPackage $xl  [-show] 
`
to commit the changes.  This moves the work onto you, but it does mean you can exactly what you want :-)

**Comment by dfinke** [comment]
Boom. Revisiting this is in order. My approach was a minimal viable product.

**Comment by jubejube56** [comment]
That solution works like a charm, thank you again.

**Comment by jhoneill** [comment]
I've added one thing to my latest commit , now `add-conditionalformatting` has a `-passthru `swtich to make the method above a little easier
Start with either
`$excel = Open-ExcelPackage  <<path>> 
` or 
`$excel = Export-Excel -PassThru <<parameters>>  
`
Then do the rule 
```
$r = Add-ConditionalFormatting -WorkSheet $excel.Workbook.Worksheets[2] -Range "B51:B100" -ThreeIconsSet Flags -Passthru
$r.Reverse = $true
$r.Icon1.Type = "Num"
$r.Icon2.Type = "Num"
$r.Icon2.value = 100
$r.Icon3.type = "Num"
$r.Icon3.value = 1000
```
And finish with
`
Close-ExcelPackage -ExcelPackage $excel -Show`
