### ISSUE TITLE
Formating TextRotation only possible from 0 to 90 degrees anti-clockwise

### ISSUE THREAD

**Issue by CamFlyerCH** [dfinke/ImportExcel#397]
I tried to rotate the contents of a cell clockwise. Against this modules parameter description an constraints the values accepted and used by EPPlus are not -90 to 90. They seam to be 0 to 90 for anti-clockwise, 91 to 180 for clockwise. (It contains 255 for vertical text, but it's "out of range" if I try to set that.

Modification proposal for the functions to format cells

            if ($TextRotation) {
                if ($TextRotation -lt 0) {
                    $Address.Style.TextRotation = 90 - $TextRotation
                } else {
                    $Address.Style.TextRotation = $TextRotation
                }
            }

**Comment by dfinke** [comment]
Thanks! Would you want to try and do a pull request on that? Then it can be merged
