### ISSUE TITLE
Pass VBA Code as a Parameter off Export-Excel

### ISSUE THREAD

**Issue by forensicsguy20012004** [dfinke/ImportExcel#40]
This is not an issue by and far. I wanted to post something about a potential new feature request. So, I was thinking if possible, there could be a parameter that would except some form of VBA . I can understand the perils that could be involved with this; as a VBA module would have to be created and then exported with the Excel document. Just something to think about, I would completely understand if this would be "down the road" idea. Again keep of the great work, the team is awesome.

Thanks,
Forensicsguy20012004

**Comment by dfinke** [comment]
Thanks for the suggestion, the team is a team of one, me :-)

Interesting idea, so you'd want to include a block of VBA, that gets injected into the Excel. How would you use it? I haven't explicitly enabled the PS Excel module to accept formulas.

**Comment by forensicsguy20012004** [comment]
Well, here is my thought. Say when an end user opens the spreadsheet/Excel; the VBA would fire off and perform whatever action; maybe say change a color based on the removal or additional of a row of  data. Another instance, say on the exploded PieChart then when a user would click on the fragment of the PieChart it would "take" them directly to those items or perform another action. I understand VBA is old and "clunky," but there are still some general uses for VBA. Fully interactive spreadsheets is kind of what I was going for. Could have a "tab" with some data that would allow the user to use a drop down box to select something which in turn would generate an output of some sort. Just something I was thinking about; your module is hands down AWESOME. 

Again..thank you,
Forensicsguy20012004

**Comment by dfinke** [comment]
I like the idea. I investigate, injected the VBA sounds doable. Wiring it up to sheets and components on sheets sounds like a maybe.

**Comment by forensicsguy20012004** [comment]
Completely understandable; you do good work Sir. Keep it up; you have a committed user here.
