### ISSUE TITLE
Cell value isnt calculating the formula

### ISSUE THREAD

**Issue by CelianB** [dfinke/ImportExcel#401]
```powershell
$Excel = [PSCustomObject]@{
    Date = (Get-Date).ToString('dd/MM/yyyy')
    Data1 = 12
    Data2 = 12
} | Export-excel -Path "./file.xlsx" -Append -WorkSheetname "Data" -PassThru

$maxRow =  $Excel.Workbook.Worksheets["Data"].Dimension.End.Row
$Excel.Workbook.Worksheets["data"].Cells[$maxRow,4].Formula = "SOMME(B$maxRow : C$maxRow)"

$Excel.Save()
$Excel.Dispose()
```

The cell stays as "#NAME?" until I press Enter in the cell to validate it.
Maybe it is caused by my Excel configuration (Excel 2016).

**Comment by dfinke** [comment]
I changed `"SOMME(B$maxRow : C$maxRow)"` to `"SUM(B$maxRow : C$maxRow)"` and it worked

**Comment by CelianB** [comment]
My excel is in french but I have also tried with an another formula : a simple division and I have the same result : the formula isnt "interpreted".

**Comment by CelianB** [comment]
Ok, it is working, I did : 
- Changed to "SUM" (not a translation)
- Added a "=" before my formula
