### ISSUE TITLE
Cannot Set-Format on Pivot table

### ISSUE THREAD

**Issue by DarrellTang** [dfinke/ImportExcel#402]
Hello, I'm trying to set a number format on some columns in a generated pivot table. The set-format cmdlet works fine when changing columns on the source worksheet but doesn't apply on the pivot table.

Apologies if this was answered previously, I couldn't find anything the issues. This is what I have so far:

`$report = $inventory | Export-Excel -ClearSheet -Path c:\temp\inventory.xlsx -WorkSheetname Inventory -TableName inventory -TableStyle Medium6 -FreezeTopRow -AutoSize -IncludePivotTable -PivotRows "Folder","Name" -PivotData @{"Name"="Count";"NumCpu"="Sum";"MemoryGB"="Sum";"ProvisionedSpaceGB"="Sum"} -NoTotalsInPivot -PivotDataToColumn -PassThru

$inventorysheet = $report.Workbook.Worksheets["Inventory"]
$pivotsheet = $report.Workbook.Worksheets["InventoryPivotTable"]
Set-Format -WorkSheet $inventorysheet -Range "d:e" -NumberFormat "#" -AutoFit
Set-Format -WorkSheet $pivotsheet -Range "b:d" -NumberFormat "#" -AutoFit
Export-Excel -ExcelPackage $report`

**Comment by jhoneill** [comment]
I get the same behaviour, and don't worry I don't think this has been asked before. 
It appears that Excel re-writes the pivot table format when it loads, so if I 

1. Create the worksheet & Pivot table
2. Apply Formatting _in Excel_ (e.g. set data in column A to Italic)  & Save
3. Open the worksheet _from PowerShell_ 
I can see the cells have the format I set in Excel. 
If I change the format on one cell (e.g. add  bold and Strike through to cell A5) save and re-open in Excel, I briefly see the new format before excel sets the cell back to just italic.

I can not find where Excel stores the format information which is reapplying.  So I think this is a limitation (bug) outside our control :-(

**Comment by jhoneill** [comment]
I have found that you can set the number format (only) on PivotTable data.  
In Excel itself you can go to field value settings and set the number format for a (or _the_) data series. We can set that within the module, and I'll add that (and setting the name of the data series) at some point in the future. (Around line 1305 in Export-Excel) 

For now you can do ` $pivotsheet.pivotTables[0].DataFields[0].Format="#" 

`
