### ISSUE TITLE
Set specific cell to have Focus in Worksheet

### ISSUE THREAD

**Issue by Penkethboy** [dfinke/ImportExcel#407]
Can you set the cell that has focus or the selected cell in a sheet?

By default it will be A1 when opened

if you save an excel file - the last cell selected/focus is remembered when you reopen it so excel supports it

**Comment by jubejube56** [comment]
$worksheet.Select("B5")

This will only work on the first open though, the last selected cell overrides it afterwards. If you wanted it to work each time you'd probably have to make a macro.

**Comment by Penkethboy** [comment]
Thanks
