### ISSUE TITLE
Only length in the Excel sheet, not the string

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#41]
I'm trying to pipe an array to Export-Excel, but the strings are not available in the worksheet. Only a number indicating the length of the string/

```
"test", "E:\HOME\creissfe\Backup 27.5.2015\Docs\K LAUFWERK\Praktikum HC 2011\1_Data Internship Christoph Reissfelder\1_Data Internship Christoph Reissfelder\CSR\EU CSR\EU Documents" | Export-Excel -Path $ExcelFile -WorkSheetname 'Paths' -Title 'Paths'
```

I tried by converting it first to a string with the help of 'Out-String', but no success. Maybe I'm missing something obvious here...

**Comment by dfinke** [comment]
Yeah, the PowerShell script that processes the input needs to be improved.

Here is a possible workaround, taking the data, making  an object.

Unfortunately whatever property you name it will show up in the sheet.

```powershell
$data = "test", "E:\HOME\creissfe\Backup 27.5.2015\Docs\K LAUFWERK\Praktikum HC 2011\1_Data Internship Christoph Reissfelder\1_Data Internship Christoph Reissfelder\CSR\EU CSR\EU Documents" 

$data | 
    ForEach{ [PSCustomObject]@{name=$_}} | 
    Export-Excel -Path $ExcelFile -WorkSheetname 'Paths' -Title 'Paths' -Show
```

**Comment by DarkLite1** [comment]
Thank you Doug, I'm now using the following construction::

    $Result.PathTooLong | ForEach {
        if ($_) {
            [PSCustomObject]@{PathTooLong=$_}
        }
    } | Export-Excel -Path 'S:\Test\Brecht\Out_Test\Test.xlsx' -WorkSheetname 'Paths' -AutoSize -TableName 'Paths'

It would be great if these kind of things could be handled within the function. Takes a bit of hassle out of the preformatting in the scripts.

**Comment by dfinke** [comment]
Thanks for reporting this. Let me know if you have issues.

**Comment by DarkLite1** [comment]
Thank you Doug for fixing this, however I still run into trouble:

    $Result.PathTooLong | Export-Excel -Path $ExcelFile -WorkSheetname 'PathTooLong' -TableName 'PathTooLong' -AutoSize -FreezeTopRow

    You cannot call a method on a null-valued expression.

The code in the script I use to find these long paths is:


                        if ($e) {
                            # Report all paths that are too long
                            $e | where {$_.Exception -like 'System.IO.PathTooLongException*'} | foreach {
                                $PathTooLong += $_.TargetObject
                            }
                            New-Object PSObject -Property @{
                                PathTooLong = $PathTooLong
                            }
                        }

This is a piece of a workflow and is catched in the variable $Result. Visible when doing $Result.PathTooLong. Maybe I'm still doing something wrong? I tried this with the updated function.

**Comment by dfinke** [comment]
Interesting, I'll take a look.

Wow, you're using almost all of the parameters in this function, that's great

**Comment by chreestopher** [comment]
@DarkLite1 , dont export the expanded property, just export the array of objects itself, so in your example: 

instead of 

`$Result.PathTooLong | Export-Excel -Path $ExcelFile -WorkSheetname 'PathTooLong' -TableName 'PathTooLong' -AutoSize -FreezeTopRow`

just do:

$Result | Export-Excel -Path $ExcelFile -WorkSheetname 'PathTooLong' -TableName 'PathTooLong' -AutoSize -FreezeTopRow

and it should work as expected

**Comment by DarkLite1** [comment]
Thanks for the feedback chreestopher, but the array is one of the properties of the object; So in case I only want that property (PathTooLong) your workaround doesn't really work as it gives me too much information. Anyhow, not a show stopper, so thx again for your help.

**Comment by chreestopher** [comment]
if $results has too many other things you arent interested in, then make
$results.pathtoolong to be an array of objects, with property path and the
actual path as the value, instead of it being an array of strings... then
when you export $results.pathtoolong, all will work as intended ....

**Comment by DarkLite1** [comment]
This is fixed, just tested it with the latest `Export-Excel`.

```
$Params = @{
    Path          = $env:TEMP + '\test.xlsx'
    WorkSheetname = 'Result'
}

"test", "E:\HOME\creissfe\Backup 27.5.2015\Docs\K LAUFWERK\Praktikum HC 2011\1_Data Internship Christoph Reissfelder\1_Data Internship Christoph Reissfelder\CSR\EU CSR\EU Documents" | 
    Export-Excel @Params -Title 'Paths' -now
```
