### ISSUE TITLE
 Cannot find an overload for "TryParce" and the argument count: "4"

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#410]
After upgrading from `5.0.0` to `5.1.0` the following code is failing, and wasn't failing before:

```powershell
$Error.Clear()

Workflow Test-HomeDriveAvailableHC {
    Param (
        [String[]]$ComputerName
    )
    Foreach -parallel($C in $ComputerName) {
        InlineScript { 
            $Result = Invoke-Command -ComputerName $Using:C -ScriptBlock {
                Test-Path -Path E:/*HOME* -PathType Container
            } -EA Stop
        }
    }
}

Test-HomeDriveAvailableHC -ComputerName NotExisting

$Error.Exception | Export-Excel -Path "$env:TEMP.xlsx"
```

> Failed exporting data to worksheet 'Sheet1' to 'C:\Temp\3.xlsx': Cannot find an overload for "TryParse" and the argument count: "4".

However, when changing it too `$Error.Exception.Message | Export-Excel -Path "$env:TEMP.xlsx"` the problem is fixed.

**Comment by jhoneill** [comment]
Hi I've just tried
 ```
1/0                                                                                                                                                                   del  notthere                                                            
Invoke-Command -ComputerName "Notexisiting" -Credential (get-credential) -ScriptBlock {Test-Path "E:\" }
$error.exception  | Export-Excel       
```                                 
And that processes as expected. 



Can you try this with the error you're trying to export ; All one line, if it works, export should also work. 
`$number = $null ; foreach ($e in $Error.exception)  {"------" ; foreach ($p in $e.psobject.properties.name) {if ( $e.$P -is [system.valueType] -and $e.$p -is [System.DateTime])    {"Property  $p is a value or date"} else   {"Property $p becomes number: " +  [Double]::TryParse($e.$p, [System.Globalization.NumberStyles]::Any, [System.Globalization.NumberFormatInfo]::CurrentInfo, [Ref]$number)}  }}`

**Comment by DarkLite1** [comment]
I tried `Invoke-Command` on its own, and that isn't a problem. It only happens whit that specific `Workflow` and the error it generates.

**Comment by jhoneill** [comment]
If there is only one error record you're trying to process, can you put this in before the if 
$p ; $e.$p.getType().fullname. 

That should show what in that error record which causes tryparse to throw.  It might be as simple as doing $error.exception | export-excel -excludeProperty <<that property>>

**Comment by DarkLite1** [comment]
Thanks for the help. When I try this:

```
$Error.Clear()
Test-HomeDriveAvailableHC -ComputerName NotExisting


$number = $null
foreach ($e in $Error[0].exception) {
    "------"
    foreach ($p in $e.psobject.properties.name) {
        $p
        $e.$p.getType().fullname
        if ($e.$P -is [system.valueType] -and $e.$p -is [System.DateTime]) {
            "Property $p is a value or date"
        }
        else {
            "Property $p becomes number: " + [Double]::TryParse($e.$p, [System.Globalization.NumberStyles]::Any, [System.Globalization.NumberFormatInfo]::CurrentInfo, [Ref]$number)
        }
    }
}
```

**Comment by jhoneill** [comment]
It looks the problem is not in error[0] when you did that last one.  Can you just try with $error.Exception

**Comment by jhoneill** [comment]
The problem is with the SerializedRemoteException   and SerializedRemoteInvocationInfo properties so for now run Export-excel with 
`-ExcludeProperty "SerializedRemoteInvocationInfo", "SerializedRemoteException"`

I've added a trap properties which cause errors and rather than throwing an error (and potentially losing data) it now sends the user a warning and tries to carry on.  It's my latest PR and on my branch if you want to see if it works  (without excludeProperty)

**Comment by DarkLite1** [comment]
That seems logical. Thanks for sharing the problem and a workaround. It would be great if you could submit your PR to @dfinke his repo. For now, as a workaround, I just use `$Error.Exception.Message`.

**Comment by jhoneill** [comment]
That commit goes into an existing PR :-)
