### ISSUE TITLE
ConvertFrom-ExcelToSQLInsert Errors when StartRow parameter is supplied

### ISSUE THREAD

**Issue by hlampert** [dfinke/ImportExcel#413]
The function ConvertFrom-ExcelToSQLInsert takes an optional StartRow parameter, which indicates the row on which data begins or column headers appear in the Excel Spreadsheet to be converted.   This function calls ConvertFrom-ExcelData which takes an optional HeaderRow parameter which defaults to 1.  When the ConvertFrom-ExcelToSQLInsert function is called without the optional StartRow parameter the default works.  When the function is called with StartRow supplied, there is no matching StartRow parameter in ConvertFrom-ExcelData, so a "A parameter cannot be found that matches parameter name 'StartRow'" error occurs.

I believe renaming $StartRow to $HeaderRow in ConvertFrom-ExcelToSQLInsert should solve this issue.

**Comment by jhoneill** [comment]
In ConvertFrom_ExcelToSQLInsert it is 

```
[Alias('HeaderRow', 'TopRow')]
        [ValidateRange(1, 9999)]
        [Int]$StartRow
```
In Import-Excel it is almost the same (a default has been added) 
```
        [Alias('HeaderRow','TopRow')]
        [ValidateRange(1, 9999)]
        [Int]$StartRow = 1
```

convertFromExcel data calls Import-Excel, so it is should match but it has 
`  [int]$HeaderRow = 1,`


The two "Converts" should fall into line with Import
