### ISSUE TITLE
NoTotalsInPivot Does not disable grand totals

### ISSUE THREAD

**Issue by ACiDGRiM** [dfinke/ImportExcel#415]
Hello, I'm using 5.1.1 and am trying to create a report that outputs totals for various status values into a report.
The pivot table is perfectly readable, however the Grand Totals is confusing because the data should be only considered in the context of each pivot column, rather than as a whole set.

It seems the NoTotalsInPivot switch doesn't actually disable the grand total column

**Comment by jhoneill** [comment]
Yes it only removes the grand totals row at the bottom and _not_ the grand totals column on the right … I'll look into this a bit further.

**Comment by dfinke** [comment]
Agreed. So the dll doesn't support column only?

**Comment by jhoneill** [comment]
The DLL has separate properties for Row and column (or colum as it writes it). What we have at the moment only sets the Row one. It seems you have all for combinations of true/false on each. Which will be in the next PR :-)

**Comment by jhoneill** [comment]
As of the newest merge we have `-PivotTotals` which can be rows, columns both or none. We still have NoTotalsInPivot which is equivalent to` -PivotTotals None`
