### ISSUE TITLE
Using parameter -HeaderName to supply custom headers incorrectly skips first row (data) of sheet

### ISSUE THREAD

**Issue by jram1220b** [dfinke/ImportExcel#417]
# Using parameter -HeaderName to supply custom headers incorrectly skips first row (data) of sheet

This seems to be a pure **BUG** but if it is a feature (and documented) then we need an enhancement to avoid this behavior, e.g., 

  `-StartRow 0`   # (illegal)  or...
  `-StartRow 1`   # (still skips first row)

### Workbook 'SimpleExample.xlsx' contents all on single sheet 'TheSheet'** (except first row isn't special):

| | **A** | **B** | **C** |
| -- | -- | -- | -- |
| **1** | FirstA | FirstB | FirstC |
| **2** | SecondA | SecondB | SecondC |
| **3** | ThirdA | ThirdB | ThirdC |

### **Desired output using Custom header and retraining first row (data) on sheet**
ColumnA|ColumnB|ColumnC
-- | -- | --
FirstA | FirstB | FirstC
SecondA | SecondB | SecondC
ThirdA | ThirdB | ThirdC

### **Illegal -- can't use HeaderName and NoHeader** together (separate Parameter sets):
```powershell
import-excel -path .\SimpleExample.xlsx -Sheet TheSheet -HeaderName @('ColumnA','ColumnB','ColumnC') -noheader
```

### **Legal but loses first row:**

```powershell
import-excel -path .\SimpleExample.xlsx -Sheet TheSheet -HeaderName @('ColumnA','ColumnB','ColumnC') 
```

ColumnA | ColumnB | ColumnC
-- | -- | --
SecondA | SecondB | SecondC
ThirdA | ThirdB | ThirdC

### **Legal but uses generated (not custom) headers**

```powershell
import-excel -path .\SimpleExample.xlsx -Sheet TheSheet -noheader
@('ColumnA','ColumnB','ColumnC') 
```

P1|P2|P3
-- | -- | --
FirstA | FirstB | FirstC
SecondA | SecondB | SecondC
ThirdA | ThirdB | ThirdC

**Comment by dfinke** [comment]
A possible quick solution is to remove the `1 +`  here
https://github.com/dfinke/ImportExcel/blob/master/ImportExcel.psm1#L381

This has not be fully tested. No ETA as to when it will be published or the final answer.
