### ISSUE TITLE
Question: How to extract simple rows and columns from sheet?

### ISSUE THREAD

**Issue by jram1220b** [dfinke/ImportExcel#418]
## Question: How to extract simple rows and columns from sheet?
If this is possible we could not find it in the documentation.

### **Common use cases: ** 

1. Read first row of sheets to discover headers present, adjust headers, then request data supplying the 
customized headers.

2. Read sheet to discover data to determine how it should be processed before requesting the bulk of the data.

**Comment by jhoneill** [comment]
Yes. 
You can do 
```
$xl = Open-ExcelPackage "$env:temp\test.xlsx"
$ws = $xl.Workbook.Worksheets[1]
$ws.cells["1:1"] | ft Address, value
Close-ExcelPackage -NoSave $xl   
```
(note you can use the position ,1 based, or the name of the sheet  - you can use A:A for a column and 1:1 for a row)
If you need to change the headers you can write to one with 
`$ws.cells["J1"].Value="NewHeaderName"`
and the close the package without specifying `-NoSave`

Alternatively you can do 
```
$oneRow =  import-excel -Path "$env:Temp\Test.xlsx" -WorksheetName sheet1 -StartRow 1 -endrow 2 
$onerow.psobject.Properties.name
```
or
`$onerow.psobject.Properties | ft name,typenameOfvalue 
`
To see what are numbers and strings
Or `
import-excel -Path "$env:Temp\Test.xlsx" -WorksheetName sheet1 -StartRow 1 -endrow 10 | Measure-Object -Property PM -Average -Maximum -Minimum`

Does that cover what you are trying to do  ?
