### ISSUE TITLE
Use-case/example of Export-ExcelSheet

### ISSUE THREAD

**Issue by ronanmcallister** [dfinke/ImportExcel#421]
Hello, this is a request for information not to report a defect.

I am attempting to use ImportExcel to the maximum extent I can (avoiding native PowerShell CSV/Excel cmdlets), using Export-ExcelSheet with XLSX input files -- currently my test data has only one Sheet per Workbook with ASCII strings, but I'll need to extend my simple tests to handle any number of Sheets per Workbook.

I'm looking at this: https://github.com/dfinke/ImportExcel/blob/master/Export-ExcelSheet.ps1 

My environment: Windows 10,  ImportExcel v5.1.1, PSVersion 5.1.16299.492

**I'm attempting to do the following:**

Using XLSX-formatted Input file containing one Sheet "Sheet1" (text strings for now):

C:\test\workbook.xlsx

I would like to Export this using Export-ExcelSheet to a new CSV file with the same base filename as the input file, formatted as comma-separated CSV, i.e. in my simple case with a Workbook with just the default Sheet "Sheet1":

C:\test\workbook_Sheet1.csv (or C:\test\workbook.csv).

At this point I don't care if the new workbook's default Sheet is named anything other than "Sheet1".

I'm able to this, it creates a file in the same folder named "Sheet1.csv" with the content I expect:

```powershell 
Export-ExcelSheet -Path c:\test\workbook.xlsx -SheetName "Sheet1"
```

However, though the CSV file has the correct / expected data, the file is always named "Sheet1".

**Question:** How can I invoke this function and create the file named "C:\temp\workbook_Sheet1.csv" or "C:\temp\workbook.csv", without having to rename the file "Sheet1.csv" outside of ImportExcel?

Thank you,
Ronan

**Comment by dfinke** [comment]
Took a quick look, I believe the problem is the `$SheetName` parameter needs be renamed to `$WorksheetName` and then it will splat correctly to the `Import-Excel` function

**Comment by ronanmcallister** [comment]
Thank you for the quick reply Doug,

I attempted to test this by changing c:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.1.1>notepad Export-ExcelSheet.ps1 locally in my 5.1.1 installation, however, I don’t think it’s working, probably my fault.

Not sure the steps I should follow to test your theory locally  – let alone know how to use GitHub basic features (at this point), I’m just beginning to use it.

PFA my changed test code….

Thanks,
Ronan

[8:05:51 AM] ~/PS> Export-ExcelSheet -Path ($Path + "\" + $xlsxFullFileName) -WorksheetName $sheetName -OutputPath $Path
Export-ExcelSheet : A parameter cannot be found that matches parameter name 'WorksheetName'.
At line:1 char:59
+ ... lSheet -Path ($Path + "\" + $xlsxFullFileName) -WorksheetName $sheetN ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-ExcelSheet], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Export-ExcelSheet

I then tried the below again – but same error message as above (same PowerShell ISE session):

try {. $PSScriptRoot\..\..\LoadPSD1.ps1} catch {}
if((Get-Module -list ImportExcel) -eq $null) {
    Import-Module $PSScriptRoot\ImportExcel.psd1 -force
}

**Comment by jubejube56** [comment]
Doesn't seem like that function has any other way to name a file since the name comes directly from the SheetName parameter, and if SheetName is set to anything other than a Sheet in your Excel file no csv is created.

**Comment by dfinke** [comment]
My apologies, my fault. This function only allows the csv file to be the name of the sheet in the workbook.
So, you'll need to rename the files after the export

**Comment by ronanmcallister** [comment]
Thank you kindly for letting me know!  Resolved
