### ISSUE TITLE
Conditional formatting on a table produces a currupted xlsx

### ISSUE THREAD

**Issue by Artanor** [dfinke/ImportExcel#424]
I am trying to add some conditional formatting to a table but it results in a corrupted file.

Using the  MultipleTables.ps1 example if I modify the last table like so.
````
$ps |
Sort-Object PM -Descending |
Select-Object -First 10 company, PM |
Export-Excel $xlfile -WorkSheetname Handles -AutoSize -TableName PM -StartRow 13 -ConditionalText $(
	New-ConditionalText -ConditionalType Equal "Microsoft Corporation" -Range "A:A" -ConditionalTextColor Black -BackgroundColor Coral
	New-ConditionalText -ConditionalType GreaterThan 400 -Range "B:B" -ConditionalTextColor Black -BackgroundColor Coral
)
````
The resultant xlsx has an error that mentions a corrupted Sheet2.xml

**Comment by jhoneill** [comment]
Hi 
`Equal "Microsoft Corporation"`

Needs to be `
Equal '"Microsoft Corporation"'`
I think this applies to any string with the greater than / less than / equals operators. (When I looked in Excel it always puts quotes around strings with these. I'll have a look and see if we can make things more robust.
