### ISSUE TITLE
Multi-line Cell Issue

### ISSUE THREAD

**Issue by mslowikowski** [dfinke/ImportExcel#425]
I have an array that has fields with multi-line values and using Export-Excel to create the xlsx.  When I open up the file the values appear as a single line, ignoring the newline characters until I edit the cell which then displays the value as it should (and resizes the row automatically, which is what I want).

I've tried newlines both with and without carriage returns but neither seem to work.  I also tried creating a workbook in excel with a multi-line value, using Import-Excel to get the value, and finally using Export-Excel to create a second workbook and the issue persists.

Is there something I should be doing differently?  Is this a bug in this project that can be fixed?

**Comment by dfinke** [comment]
Please attach the script and xlsx so it can be reviewed

**Comment by mslowikowski** [comment]
Here is a sample script and excel file to demonstrate the issue.  If you run the powershell script it will read the excel file in which contains a single cell with multiple lines of text and then write that value out to a new excel file which will have the proper value but Excel will not display the newline characters until you edit the cell (F2, enter).

Let me know if that make sense.

[multiline-issue.ps1.txt](https://github.com/dfinke/ImportExcel/files/2311597/multiline-issue.ps1.txt)
[Book1.xlsx](https://github.com/dfinke/ImportExcel/files/2311598/Book1.xlsx)

**Comment by Liturgist** [comment]
Perhaps I am missing it, but I do not see `-WrapText` in the output of `help Set-Format -Full` or as a parameter competed by TAB.

**Comment by dfinke** [comment]
Check to make sure you have the latest version of the module.

**Comment by jhoneill** [comment]
It has been in since at least 5.0.1

**Comment by Liturgist** [comment]
My apologies. I see it now.

I copied the `help Set-Format -Full` output into the editor (Microsoft Code) and searching for `wrap` failed. I also recently discovered that Alt-C and Alt-W turns on case sensitivity and whole word searching. It is likely that I had hit one or both of those, causing the search to not find "wrap."

**Comment by michcleary** [comment]
I realize it's after the fact (a bit), but how would you add wrapping to only one column, and also use a named tab? My tabs aren't always in the same order.  I tried:
Set-format -Address $xlsx.Workbook.Worksheets[$ws].Cells -WrapText #index operation failed; the array index evaluated to null

I would just apply that to one column after fixing it above so I use a named tab.

**Comment by dfinke** [comment]
```powershell
$data = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee has a very long name,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@

$xlfilename = "./testWrap.xlsx"
Remove-Item $xlfilename -ErrorAction SilentlyContinue

$data | Export-Excel $xlfilename -WorksheetName TestWrap1
$xlpkg = $data | Export-Excel $xlfilename -WorksheetName TestWrap2 -PassThru

Set-ExcelRange -Worksheet $xlpkg.TestWrap2 -Range "B:B" -WrapText 

Close-ExcelPackage $xlpkg -Show
```

**Comment by djartistic** [comment]
Nice, thanks!

You helped me a lot :D

  $Output=($Output|Export-Excel $Export -Wo "Info")|Export-Excel $Export -Wo "Info" -AutoS -AutoF -FreezeTopRow -Bo -Ap -passT
  Set-ExcelRange -Wo $Output."Info" -Ra "B:B" -Wr -Ho Left -Vert Center
  Close-ExcelPackage $Output -Sh
