### ISSUE TITLE
Set-CellStyle is getting slow

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#428]
Consider this piece of code:

```powershell
$VerbosePreference = 'Continue'

$Highlight = [Ordered]@{}
$Highlight.Add(70, [System.Drawing.Color]::Orange)
$Highlight.Add(80, [System.Drawing.Color]::Pink)
$Highlight.Add(100, [System.Drawing.Color]::Red)

$ExportParams = @{
    Path          = "$env:TEMP\test.xlsx"
    WorkSheetname = 'Quotas'
    TableName     = 'Quotas'
    AutoSize      = $true
    FreezeTopRow  = $true
}

$ExportParams.Path | Remove-Item -EA Ignore

$testData = @(0..300).ForEach({
    [PSCustomObject]@{
        GroupName       = 'SWE ATT Quota home 12GB'
        ComputerName    = 'Server'
        ComputerPath    = "E:\HOME\user$_"
        Status          = 'Ok'
        Usage           = 74,73
        UsageSize       = 8,97
        LimitNew        = 10
        TypeNew         = 'Hard'
        LimitOld        = 10
        TypeOld         = 'Hard'
        WarningOld      = 80, 90, 100
        WarningNew      = 80, 90, 100
        Template        = 'HOME - 10 GB hard quota'
        MatchesTemplate = $False
        Description     = 'SWE ATT Quota home 10GB'
        SamAccountName  = "user$_"
        HomeDirectory   = "\\contoso.net\Swe\Stockholm\Home\user$_"
        LimitOld_       = 10737418240
        LimitNew_       = 10737418240
        Usage_          = 230594560
    }
})

$testData | Export-Excel @ExportParams -CellStyleSB {
    Param (
        $WorkSheet,
        $TotalRows,
        $LastColumn
    )
    
    #region Format percentage and set row color
    $PctCell = $WorkSheet.Cells['1:1'] | where Text -EQ 'Usage'

    foreach ($R in (2..$TotalRows)) {
        foreach ($H in $Highlight.GetEnumerator()) {
            $WorkSheet.Cells.Item($R, $PctCell.Start.Column).Value | where {$_ -ge $H.Name} | ForEach-Object {
                Write-Verbose "Set style for row $R"
                Set-CellStyle -WorkSheet $WorkSheet -Row $R -LastColumn $LastColumn -Pattern Solid -Color $H.Value
                Write-Verbose "Set style for row $R done"
            }
        }
    }

    $WorkSheet.Column($PctCell.Start.Column) | Set-Format -NumberFormat '?\%'
    #endregion

    #region Fromat GB fields
    $GBcell = $WorkSheet.Cells['1:1'] | 
        where {@('UsageSize', 'LimitOld', 'LimitNew') -Contains $_.Text}
        
    $GBcell | ForEach-Object {
        $WorkSheet.Column($_.Start.Column) | Set-Format -NumberFormat '?\ \G\B'
    }
    #endregion
        
    #region Fromat KB fields
    $KBcell = $WorkSheet.Cells['1:1'] | 
        where {@('LimitOld_', 'LimitNew_', 'Usage_') -Contains $_.Text}
        
    $KBcell | ForEach-Object {
        $WorkSheet.Column($_.Start.Column) | Set-Format -NumberFormat '?\ \K\B'
    }
    #endregion

    $WorkSheet.Cells.Style.HorizontalAlignment = 'Center'
}
```

From 0 to 100 it goes quite fast but from a 100 onwards it gets really slow. We have an array of over a thousand of objects, so it takes quite some time to handle them.

Can `Set-CellStyle` be made faster? Or am I using the wrong way to color a line in the worksheet?

**Comment by jhoneill** [comment]
OK. I've tried to find a way to say this which doesn't sound rude. I'm not trying to be rude … but I think you have found the slowest way of doing the task.  
If you pipe (e.g.) $Worksheet.column(x) to set-format you will send each cell to set-format one by one. Setting a cell style individually is  an expensive operation because each format applied in the sheet is stored, and every time a format is set EPPlus must check to see if that format has been used already.  So

` Set-Format -NumberFormat '?\ \K\B' -address   $WorkSheet.Column($_.Start.Column)  ` 
Should be (number of rows) times faster. What your are doing once per row, this does once. 

Second if you are fishing around inside the worksheet, you can do 
`  $WorkSheet.Column($_.Start.Column).Style.Numberformat.Format = '? KB' `
(I don't think you should need to escape space K or B )  In fact I'd use 
`export-excel -AutoNameRange`
and your regions then become 
```
$WorkSheet.Names['LimitOld_', 'LimitNew_', 'Usage_'].Style | foreach {$_.numberformat.format = "? GB"} 
$WorkSheet.Names['UsageSize', 'LimitOld', 'LimitNew'].Style | foreach {$_.numberformat.format = "? KB"} 
```

Third. Are you **really** iterating through cells looking at their value and setting a format ? Why are you not using a conditional format ? [OK 3 conditional formats, 2 "between" and 1 "greater than"] . Give me a shout if you need help with those.

**Comment by DarkLite1** [comment]
You're not rude, I can take it. It helps to know when you're not the smartest kid on the block ;)  So thank you for your suggestions, as I'm not really familiar with cell formatting.

I tried what you said, add the `-AutoNameRange` parameter and the following faster code with the example data above:

```powershell
@($WorkSheet.Names['LimitOld_', 'LimitNew_', 'Usage_'].Style).ForEach({
    $_.NumberFormat.Format = "?\ \G\B"
})
    
@($WorkSheet.Names['UsageSize', 'LimitOld', 'LimitNew'].Style).ForEach({
    $_.NumberFormat.Format = "? KB"
})
```
This will set a complete column at once, which is indeed better. However, the problem is that the Excel file becomes corrupt and complains about an incorrect number format, while this same number format was not a problem for `Set-Format`. Any clues on how to overcome this?

You're right, I will look at how to use `conditional formatting` on the cells as it seems more logical.

**Comment by DarkLite1** [comment]
There are no examples for the case `Between` values with regards to `Conditional formatting`. In the help of `Export-Excel` the following is found:

```powershell
        .PARAMETER ConditionalFormat
            One or more conditional formatting rules defined with New-ConditionalFormattingIconSet.
        .PARAMETER ConditionalText
            Applies a 'Conditional formatting rule' in Excel on all the cells. When specific conditions are met a rule is triggered.
```

So it seems like the rules need to be created first with `New-ConditionalText` or is it better to use `Add-ConditionalFormatting` with `-PassThru` on the `Export-Excel` CmdLet?

**Comment by DarkLite1** [comment]
Fixed it like this:

```powershell
$WorkSheet = $ExcelWorkbook.Workbook.Worksheets['Quotas']

$LastRow = $WorkSheet.Dimension.Rows

Add-ConditionalFormatting -WorkSheet $WorkSheet -Range "E2:E$LastRow" -BackgroundColor 'Red' -RuleType GreaterThan -ConditionValue 100
Add-ConditionalFormatting -WorkSheet $WorkSheet -Range "E2:E$LastRow" -BackgroundColor 'Orange' -RuleType Between -ConditionValue 90 -ConditionValue2 100
Add-ConditionalFormatting -WorkSheet $WorkSheet -Range "E2:E$LastRow" -BackgroundColor 'Pink' -RuleType Between -ConditionValue 80 -ConditionValue2 90


$ExcelWorkbook.Save()
$ExcelWorkbook.Dispose()
```

Let me know if you see some improvements. It's not the complete row that is colored, but I can live with that. Thanks again for the great help. Much appreciated :)

**Comment by jhoneill** [comment]
You see, thanks, and suggesting that I might be  the smarter kid on the block helps . 
For 100 rows, your original code took 7 seconds to run - end to end on my laptop
I changed this 

```
$Highlight = @{
    "AND(({0}>=70),({0}<80))" = [System.Drawing.Color]::Orange
    "AND(({0}>=80),({0}<90))" = [System.Drawing.Color]::Pink
    "{0}>=90"                 = [System.Drawing.Color]::Red
}

$ExportParams = @{
    AutoNameRange = $true
…

```

The formulas will have {0} replaced with $E2  - 2 will change as it fills down and you say format these cells so if E on their row is …. 

and replaced everything from your export onwards with this 

```
$Excel = $testData | Export-Excel @ExportParams -PassThru 
$worksheet = $excel.Workbook.Worksheets["Quotas"]
    $PctCell = $WorkSheet.Cells['1:1'] | where Text -EQ 'Usage'
    $PctDataAt = "$" + $PctCell.Address -replace "1","2" 
    $range = $worksheet.Dimension.Address -replace "A1","A2"
    Foreach ($item in $Highlight.keys) {
        $formula = $item -f $PctDataAt
        Add-ConditionalFormatting -WorkSheet $worksheet -Range $range -RuleType Expression -ConditionValue $formula -BackgroundColor $highlight[$item] -BackgroundPattern Solid
    }

    $WorkSheet.Names['LimitOld_', 'LimitNew_', 'Usage_'].Style  | foreach {$_.numberformat.format = "\? \G\B"} 
    $WorkSheet.Names['UsageSize', 'LimitOld', 'LimitNew'].Style | foreach {$_.numberformat.format = "\? \K\B"} 
    $WorkSheet.Cells.Style.HorizontalAlignment = 'Center'

    Close-ExcelPackage  $excel

```
For 100 rows its about the 0.3 second mark, for 1000 it was 6.8 which broke down as
6.64473   - creating and exporting the data 
6.6797564 -0.035 sec - applying formatting
6.8162136 - 0.14 - writing file saving. 

I went back to escaping the number format in case that was why the error was happening on opening excel. But I think that's a decent speed boost.

**Comment by DarkLite1** [comment]
It is indeed significantly faster! It's amazing how fast it gets when you take a completely different approach and not iterating every cell. 

Is there also a quick fix to sort the rows from largest to smallest for the field `Usage`? Tried to use `Sort-Object' upfront, but that didn't yield the correct order.

**Comment by jhoneill** [comment]
There isn't a nice quick way to apply a sort - you've done it as a table so it is only one click away when you open excel, but sort object _should_ work . Possibly you need to do something with the property to get it to sort correctly. Is usage a floating point number or is a string which is turned into a number by Export-Excel ? That will bunch 1,11 & 12 before 2. You can use the @{e={expression}}  syntax with Sort-object and put something in there that force it to the right kind of number.

**Comment by DarkLite1** [comment]
Got it working in the meantime. Thanks again for you help James 👍
