### ISSUE TITLE
Scheduled Task running as System won't write to Excel file

### ISSUE THREAD

**Issue by volvo64** [dfinke/ImportExcel#431]
On Server 2012 R2, a scheduled task running a powershell script as system fails to write to the Excel file.

Changing the file path from a UNC (\\server\file) to a local path (c:\file) does not make a difference.

Changing the scheduled task user to Administrator writes the file successfully.

SYSTEM has full access to the file in question.

**Comment by jhoneill** [comment]
Obvious question, if you test the script with <whatever> | export-csv  
and use a file in same place does the data get written ?

**Comment by jhoneill** [comment]
OK. I'll see if I can repro today. There may be something odd about they way the EPPlus dll requests access to the file but I don't think there is anything odd in the module itself.

**Comment by jhoneill** [comment]
On a 2012 R2 server I created this script 
```
$ExcelErr = $null
Import-Module -Name ImportExcel -ErrorVariable ExcelErr
if ($ExcelErr) {$ExcelErr | Out-File -FilePath C:\Users\Public\Documents\ImportExcelLoadErr.txt}
$ExcelErr = $null
1,2,3,4 | export-excel -path C:\Users\Public\documents\test.xlsx -ErrorVariable ExcellErr 
if ($ExcelErr) {$ExcelErr | Out-File -FilePath C:\Users\Public\Documents\ExcelRuntimeErr.txt}
```
I created a scheduled task to run this as `NTAuthority\System` ran it on demand and it created the Excel file normally, and the file is owned by SYSTEM so I'm confident it ran as the system account 

My hunch is there is something else about your script which has a problem when run as System. Would you like to try my script  and see what you get ?
