### ISSUE TITLE
Error trying to get multiple pivots imported and exported

### ISSUE THREAD

**Issue by rvblerk** [dfinke/ImportExcel#433]
Hope this is the right place to post.
So the problem i have is that the export and import of excel works great.
What i am trying to achieve is to get multiple pivots onto multiple worksheets.
I am able to export one worksheet without any issues. I am just stuck on getting it to do multiple things

My script looks is below

Import-Excel 'C:\scripts\MSCR.xlsx' | Export-Excel -Path 'C:\scripts\MSCR1.xlsx' -WorkSheetname "Actual Cost Analysis" -Show -PivotTableDefinition @{
    "Actual Cost Analysis" = @{"SourceWorkSheet" = "Actual Cost Analysis";
             "PivotRows"         = "Service";
             "PivotData"         = @{'Total Cost'=”Sum”};
             "IncludePivotChart" = $true;
             "ChartType"         = "ColumnClustered";
             "NoLegend"          = $true};

   "Actual Cost Over Time" = @{"SourceWorkSheet" = "Actual Cost Over Time"; 
             "PivotRows"         = "Date"; 
             "PivotData"         = @{"Total Cost"="Sum"}; 
             "IncludePivotChart" = $true; 
             "ChartType"         = "ColumnClustered"; 
             "NoLegend"          = $true };

   "Cost Analysis" = @{"SourceWorkSheet" = "Cost Analysis"; 
             "PivotRows"         = "ID"; 
             "PivotData"         = @{"Total Cost"="Sum"}; 
             "IncludePivotChart" = $true            ; 
             "ChartType"         = "ColumnClustered"; 
             "NoLegend"          = $true };

   "Cost Over Time" = @{"SourceWorkSheet" = "Cost Over Time"; 
             "PivotRows"         = "Date"; 
             "PivotData"         = @{"Total Cost"="Sum"}; 
             "IncludePivotChart" = $true ; 
             "ChartType"         = "ColumnClustered"; 
             "NoLegend"          = $true}

   "Instance Cost Allocation" = @{"SourceWorkSheet" = "Instance Cost Allocation"; 
             "PivotRows"         = "Service"; 
             "PivotData"         = @{"Cost"="Sum"}; 
             "IncludePivotChart" = $true ; 
             "ChartType"         = "ColumnClustered"; 
             "NoLegend"          = $true}                 
}

**Comment by jhoneill** [comment]
So - I'm guessing you don't want to write changes to the original file. 
If you do import-excel <file> it will import the first sheet in the file, and then you're writing that to a new file. 
What the pivot definition is then doing is trying to create pivots for multiple sheets, and I am guessing you're hitting a problem that after the first sheet, the source data doesn't exist. 

What I would do is 
copy the original file .
 Don't pipe anything to Export-Excel  instead run 
`Export-Excel <new file Name> -worksheetname <any sheet name in the workbook> -pivotTableDefintion @{ <what you have already> } 
`
Export-Excel  will create pivots as a separate operation from putting data in the file

Does this help ?

**Comment by dfinke** [comment]
Does this help?

```powershell
$xlfile = "$env:TEMP\mpt.xlsx"

rm $xlfile -ErrorAction SilentlyContinue

$workSheet = "psData"

$pt=[ordered]@{}

$baseDefinition = @{
    SourceWorkSheet=$workSheet
    IncludePivotChart = $true
    ChartType = 'ColumnClustered'
    NoLegend = $true
}

$pt.Handles =$baseDefinition + @{    
    PivotRows = 'Company'
    PivotData = @{'Handles'='Sum'}
}

$pt.PM =$baseDefinition + @{    
    PivotRows = 'Company'
    PivotData = @{'PM'='Sum'}
}

$pt.VirtualMemorySize =$baseDefinition + @{    
    PivotRows = 'Company'
    PivotData = @{'VirtualMemorySize'='Sum'}
}

$pt.NonpagedSystemMemorySize =$baseDefinition + @{    
    PivotRows = 'Company'
    PivotData = @{'NonpagedSystemMemorySize'='Sum'}
}

$pt.PagedMemorySize =$baseDefinition + @{    
    PivotRows = 'Company'
    PivotData = @{'PagedMemorySize'='Sum'}
}

ps | 
    select Company, Handles, PM, VirtualMemorySize, NonpagedSystemMemorySize, PagedMemorySize |
    Export-Excel $xlfile -WorksheetName $workSheet -AutoSize -Show -PivotTableDefinition $pt
```

**Comment by rvblerk** [comment]
This one kind of makes sense.
can i upload an example of the excel document that I am working on.
that might then give some insight on what I am trying to achieve.
