### ISSUE TITLE
AutoSize - not quite enough

### ISSUE THREAD

**Issue by Penkethboy** [dfinke/ImportExcel#434]
Not sure if this is a ImportExcel or EPPlus problem

![capture1a](https://user-images.githubusercontent.com/21155304/45305386-13bd1e00-b512-11e8-8561-fce45899aaf1.JPG)
Issue 1 - If the data in a column has a greater width than the title the longest string(s) get the last one or two characters cut off. - e.g. C9 and A5 and A6 and B11
Issue 2 - Having the table/autofilter enabled covers the last characters also of the Title see Column D and E

When open in excel - invoking the column autosize manually works fine to expand the columns so all text is visible.

I don't think i am missing a setting.

Anyway i can increase the "padding"?
Have tried adding spaces to the titles but that does not work.

**Comment by dfinke** [comment]
@Penkethboy I believe the `Autosize` is a best attempt, and doesn't/can't account for the display.

You can use `-PassThru` when you create the xlsx, grab the sheet and the `Set-Format` gives you access to the width of Ranges.

Then `Close-ExcelPackage` with the `-Show` switch.
