### ISSUE TITLE
Import-Module ImportExcel failed : missing PivotTable.ps1

### ISSUE THREAD

**Issue by spiralcb** [dfinke/ImportExcel#437]
Hello, 

I just install module using the Install-Module ImportExcel. 
When I try to import then, it fails with message "PivotTable.ps1» is unknown... " 

I dowload it direcly on Github (just PivotTable.ps1), put it in module install path and now Import-Module ImportExcel works fine. 

Best regards,

**Comment by dfinke** [comment]
Thanks! Will be publishing a new version today.
