### ISSUE TITLE
Get-ExcelColumnName broken for cols > 27

### ISSUE THREAD

**Issue by Verayth** [dfinke/ImportExcel#439]
Get-ExcelColumnName returns column names for columns > 27 in the wrong character order.

It's easy to test:
for ($i = 1; $i -lt 100;$i++) {Get-ExcelColumnName $i}

Column 28 should be "AB", not "BA".

**Comment by jhoneill** [comment]
`[OfficeOpenXml.ExcelAddress]::GetAddress(1,$ColumnNumber) -replace '1',''`


That does look it should be` ColumnName = ColumnName + xxx ` not ` ColumnName = xxx+ ColumnName `

**Comment by dfinke** [comment]
Cool. Maybe "replace" `Get-ExcelColumnName` with that?

**Comment by jhoneill** [comment]
I like because it is just one line - I tried to avoid calls to Get-ExcelColumnName and in some places I replaced them with that.

**Comment by Verayth** [comment]
Thank you @jhoneill  for the GetAddress sample code.  That's actually what I really needed, was some way to get a cell name via X-Y coordinate numbers.  I'd suggest adding a Get-ExcelAddress shortcut function to ImportExcel so others don't have to spend as much time searching for a solution as I did.

**Comment by dfinke** [comment]
@Verayth, feel free to fork the code and make pull request to update this.
