### ISSUE TITLE
Error using Export-Excel since updating to latest release of module

### ISSUE THREAD

**Issue by stukey** [dfinke/ImportExcel#44]
I've been using your module since May and it's been working fine. I noticed that there had been a lot of recent updates so I downloaded and installed the latest version of the module and now Export-Excel is not working at all. Whenever I try to use the module I get the following error. For example:

    PS F:\PowerShellScripts> Get-Service | Export-Excel services.xlsx
    invoke member w/ expression name
    At line:1 char:1
    + Get-Service | Export-Excel services.xlsx
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (:) [], NotImplementedExceptio
        + FullyQualifiedErrorId : System.NotImplementedException

I cannot figure this out and don't understand what is happening. The previous version (from 27th May '15) worked fine. It seems to be an issue with the Export-Excel.ps1 file, which didn't even exist in the previous version. I also noticed that parameter completion is no longer working for the Export-Excel cmdlet.

I am using PowerShell 3.0 on Windows 2008 R2. I also tested on Windows 7 with PowerShell 3 - same issue. Reverting back to the previous version works fine.

Hope you can help!

**Comment by stukey** [comment]
Just to add that I tried downloading a previous version from commit https://github.com/dfinke/ImportExcel/commit/84e273387ca023def5c9541828c96f53caf9de42 on 21st August 2015 and it works fine. So something happened/changed after that date to break the module - at least for me.

**Comment by dfinke** [comment]
Thanks for the clues. I don't have a box with PS 3. It's going to be a challenge.

The error that is shown is this?

`invoke member w/ expression name`

**Comment by stukey** [comment]
Hi Doug. Yes, that's the error:

    invoke member w/ expression name

It doesn't give much away. I tried specify -Debug but that didn't provide any further info. If there's anything I can do to help identify the root cause please let me know. I tried reviewing the Export-Excel.ps1 module but I don't really see where or what line of the script is causing the issue. There's nothing at line 1 char 1.

**Comment by dfinke** [comment]
Unfortunately it all works in v5 including the parameter completion. I do have PSReadline installed though.

Could you try `gsv | select status | export-excel services.xlsx`

**Comment by stukey** [comment]
Hi. Same error as above. No matter what you try to do with the Export-Excel cmdlet, you always get the above error.

**Comment by dfinke** [comment]
Thanks for trying. If you want, create a ps1 file with that line in it, open it in ISE and set a break point and then you can step through into Export-Excel.ps1 and see if that gives more clues.

I need to figure out how to spin up PS V3

**Comment by stukey** [comment]
Hi Doug. Sorry I am not very experienced using Debug. I did as you suggested but the example script just errors-out with the same error again, it does't seem to step-into the actual code in the module, it just errors immediately when calling Export-Excel cmdlet:

    gsv | select status | export-excel services.xlsx
    PS C:\WINDOWS\system32\WindowsPowerShell\v1.0> C:\Users\stu\Desktop\test.ps1
    Hit Line breakpoint on 'C:\Users\Stu\Desktop\test.ps1:1'
    [DBG]: PS C:\WINDOWS\system32\WindowsPowerShell\v1.0>>
    invoke member w/ expression name At C:\Users\Stu\Desktop\test.ps1:1 char:1
    + gsv | select status | export-excel services.xlsx
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotImplementedException
    + FullyQualifiedErrorId : System.NotImplementedException

**Comment by dfinke** [comment]
That's fine. I think the $PSScriptRoot is the problem in the PSM1.  It may work if you replace it and hard code the actual location in the module folder where the export-excel.ps1 is

**Comment by stukey** [comment]
Hi Doug. Unfortunately that wasn't the issue. I believe PowerShell 3.0 and later fully support $PSScriptRoot. Anyway I replaced it with the hard-coded location of the module and I still get exactly the same error. Googling the error a few posts on technet about similar issues in scripts mention `"The ability to store a method name in a variable and invoke it with the dot operator is new to PowerShell 4.0 and later"`. Does that mean anything to you? Could something have changed in the code to do that in the latest version of the module?

Just also FYI - all of the other functions in the module work fine, e.g. Import-Excel works without issue. It's just Export-Excel (which is the only function we really use) that doesn't work.

**Comment by dfinke** [comment]
Thanks for drilling down on this.

This does make sense. I'll take a look at the code. This might have been introduced when I added conditional formatting.

**Comment by stukey** [comment]
Hi Doug,

Have you been able to pinpoint his issue? If there's anything more I can do to help, please let me know. We'd like to be able to update to the latest version.

Stuart

**Comment by dfinke** [comment]
Unfortunately, I have not found what is causing this and I may need to load up v3 of PowerShell to figure it out.

**Comment by stukey** [comment]
OK. Thanks. Again please let me know if there's anything I can do to assist.

**Comment by dfinke** [comment]
OK, commenting out these lines solves the issue on my PS v3 install.

Next, I need to fix it for v3

```powershell
foreach($format in $ConditionalFormat ) {
    $target = "Add$($format.Formatter)"
    $rule = ($ws.ConditionalFormatting).$target($format.Address, $format.IconType)
    $rule.Reverse = $format.Reverse
}
```

Can you upgrade to v4? :-D

**Comment by stukey** [comment]
Hi Doug. Yes changing that line in Export-Excel.ps1 fixes the issue. I wish I understood why it fixes the problem!

Many thanks for looking into this.

**Comment by dfinke** [comment]
I checked in the change and will push it the gallery soon.

I don't know the explanation as to why this changed in v4.

```powershell
$Method = "SubString"

"Hello".$Method.Invoke(2,1) # => Needed for -lt v4
"Hello".$Method(2,1)        # => Less noise for -ge v4
```

**Comment by stukey** [comment]
Thanks Doug!

**Comment by marinkovicpetar** [comment]
Hi Doug,

Many thanks on your great module, which now I use for quite some time. I have one server with PowerShell 3.0, which because of some dependencies, I cannot upgrade to PowerShell 4. I've tried the fix you suggested here, but adding Invoke to Export-Excel cmdlet won't help me. Is there any other solution to this one? I'm using the latest version, just added this here because of the same issue stukey had.

Thanks!

**Comment by dfinke** [comment]
Thanks for the comment @marinkovicpetar. There might be one more way. I need to check some older code. If I don't respond in the next couple days, please remind me.

**Comment by marinkovicpetar** [comment]
Thanks a lot Doug, looking forward to it

**Comment by dfinke** [comment]
@marinkovicpetar Sorry, that was the trick I used to solve it. Could you post the error and what version of PowerShell, `$PSVersionTable`

**Comment by marinkovicpetar** [comment]
Here it is Doug:

$PSVersionTable

Name                           Value                                                                                                                                                                                                     
----                           -----                                                                                                                                                                                                     
PSVersion                      3.0                                                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                                                                                   
CLRVersion                     4.0.30319.18444                                                                                                                                                                                           
BuildVersion                   6.2.9200.16398                                                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0}                                                                                                                                                                                           
PSRemotingProtocolVersion      2.2 

Get-Service | Export-Excel test.xls
invoke member w/ expression name
At line:1 char:1
+ Get-Service | Export-Excel test.xls
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotImplementedException
    + FullyQualifiedErrorId : System.NotImplementedException

I've changed the following on line 81. in Export-Excel.ps1 per instructions from above:

 $rule = ($ws.ConditionalFormatting).$target.Invoke($format.Address, $format.IconType)

Thanks for your help in advance!

**Comment by dfinke** [comment]
Ok, let's try those :)

`$rule = ($ws.ConditionalFormatting).PSObject.Methods[$target].Invoke($format.Address, $format.IconType)`

**Comment by marinkovicpetar** [comment]
Unfortunately, it's the same

```
PS C:\Users\administrator\Desktop> Import-Module ImportExcel
WARNING: PowerShell 5 is required for plot.ps1
WARNING: PowerShell Excel is ready, except for that functionality

```
```
PS C:\Users\administrator\Desktop> get-service | Export-Excel test.xlsx
invoke member w/ expression name
At line:1 char:1
+ get-service | Export-Excel test.xlsx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotImplementedException
    + FullyQualifiedErrorId : System.NotImplementedException
```

**Comment by dfinke** [comment]
Wow. This is a mystery. Do you get the same error for this?

```powershell
$m="substring"
"hello".psobject.methods[$m].invoke(2,3)
```

**Comment by marinkovicpetar** [comment]
No, that one completes without any errors

```
PS C:\Users\administrator\Desktop> $m="substring"
"hello".psobject.methods[$m].invoke(2,3)
llo
```

**Comment by dfinke** [comment]
Ok, that indicates issue is probably elsewhere. Were you able to run earlier versions of  PS Excel on PowerShell 3.0?

**Comment by marinkovicpetar** [comment]
Haven't tried. I've used your module on dozen of servers and client OS, but always with PS 4.0. Would upgrade this server as well, but it's some PBX which has module that is compatible only up to 3.0 per documentation and I wouldn't like to break them, since I heavily rely on them

Do you  maybe know the version that I can give a go, I saw that at the beginning of this thread stukey is mentioning previous release that worked fine for him. I only need Export-Excel.ps1 from the module anyway (exporting CSVs to one Excel with multiple sheets)

**Comment by dfinke** [comment]
Sorry, I don't remember what got introduced and when caused issues for 3.0.

**Comment by marinkovicpetar** [comment]
Not a problem, I've fixed it somehow :)
I've took a commit from 10/20/2015 (I needed-HeaderRow in Import-Excel) and then I've applied the change with `$rule = ($ws.ConditionalFormatting).PSObject.Methods[$target].Invoke($format.Address, $format.IconType)` you mentioned and both cmdlets work great.

Once again, thanks a lot for your help and your great module, it really saves me a lot of time other than dealing with COM

**Comment by headsphere** [comment]
Hi @dfinke  - Sorry to revive an old thread but sadly I'm getting exactly the same problem as @marinkovicpetar . My $PSVersionTable and error output are identical to his. 

I installed using:
iex (new-object System.Net.WebClient).DownloadString('https://raw.github.com/dfinke/ImportExcel/master/Install.ps1')

Did anyone come up with a fix or workaround for this by any chance? Upgrading to PS4 is a non-starter for us unfortunately

Thanks

**Comment by dfinke** [comment]
Hey @headsphere, no workarounds. Taking the commit from 10/20/15 seemed to work for @marinkovicpetar.

**Comment by headsphere** [comment]
FYI - I've submitted a pull request that seems to fix this issue on my machines with PS3: #126

**Comment by dfinke** [comment]
Thanks for the PRs. They look good. I'll kick the tires on them. I'll only be able to confirm they run on 5.0. The unit tests are severely lacking for this.

**Comment by turbomcp** [comment]
any news about this?
im running it in ps 5.0.10586.117 
and i get this when exporting:
Failed exporting worksheet 'Sheet1' to 'C:\WINDOWS\system32': Exception calling "Save" with "0" argument(s): "Error saving file C:\WINDOWS\system32"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\4.0.9\Export-Excel.ps1:1000 char:13
+             throw "Failed exporting worksheet '$WorkSheetname' to '$P ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed exportin...NDOWS\system32":String) [], RuntimeException
    + FullyQualifiedErrorId : Failed exporting worksheet 'Sheet1' to 'C:\WINDOWS\system32': Exception calling "Save" with "0" argument(s): "Error saving file C:\WINDOWS\system32"


thanks

**Comment by dfinke** [comment]
Please post the PowerShell that you are using that causes this error
