### ISSUE TITLE
Chart is not based on ‘Grand Total’ column when using pivot table with ‘Pivotcolumns’

### ISSUE THREAD

**Issue by tysonflint** [dfinke/ImportExcel#440]
I can create a chart based off of a pivot table correctly.  However, when I add PivotColumns to the pivot table, the chart's series is no longer based off of the "Grand Total" column, but is rather based off of the second column in the pivot table (or rather the first column of the detailed state section of the pivot table).

In this example:

Import-Module ImportExcel
rm -Force .\demo.xlsx -ErrorAction Ignore
$data = Get-Service | Select-Object Status, Name, DisplayName, StartType | Sort-Object StartType
$p = @{Show = $true; AutoSize = $true; AutoFilter = $true; IncludePivotTable = $true;}
$p.PivotRows = 'StartType'
#Commenting out the next line fixes the series in the pie chart, but eliminates the pivot table detail
$p.PivotColumns = 'Status'
$p.PivotData = 'StartType'
$data | Export-Excel .\demo.xlsx @p -IncludePivotChart -ChartType PieExploded3D -Activate

The chart is created, but if you hover over the pie chart, you will see that the values for Series 1 are obtained from column B (the number of services running), rather than column D (the Grand Total).

Commenting out the following line fixes the graph, but eliminates the desired detail from the pivot table:
$p.PivotColumns = 'Status'

I'm not sure if this is a bug, or if I need to specify additional parameters for the chart to use the 'Grand Total' column when using the PivotColumns feature of the pivot table.

**Comment by jhoneill** [comment]
I've been looking at this in Excel and it looks like , if the data is not split into columns you have one series to graph. When you split it into columns total isn't a series; you get "Running" and "Stopped" as series instead -if you chart it with Pie it can only show one series, but with column (etc) you can chart all of them
I couldn't find a way to get Excel to chart just the totals. If you can ,could you post a file with what you want and I'll see if I can get EPPlus to make it :-)

**Comment by tysonflint** [comment]
Originally I was after a pie chart based just off of the far right "Grand Total" column in the pivot table.  This appears difficult to accomplish when splitting out the data into different columns.  Thanks to your comment, I've switched my graph from PieExploded3D  to ColumnStacked3D, and it gives the desired results.

Now I'm trying to figure out how to apply a different "Style" to the graph, such as Style 1 - 8, or how to apply a color palette, such as Colorful Palette 1 - 4, or Monochromatic Palette 1 - 13.  If this isn't yet possible, let me know and I'll open up a separate issue.  Thanks again for your reply,

**Comment by dfinke** [comment]
Styles and Palettes not currently supported at the PowerShell level. Don't know if EPPlus exposes that.
