### ISSUE TITLE
New-ExcelChart typo?

### ISSUE THREAD

**Issue by jdustin1** [dfinke/ImportExcel#441]
Greetings -

I've been testing "New-ExcelChart" functionality, and finally realized I found a likely typo:

new-excelchart -LegendPostion Bottom

This is a FANTASTIC module, thanks for all the hard work!

**Comment by dfinke** [comment]
Thanks @jdustin1! 

I did a PR with the fix, will merge after @jhoneill takes a quick scan.

**Comment by jhoneill** [comment]
Oh darn it.  I read @jdustin1 's message about half a dozen times before I saw there is an "I" missing. Well spotted ! 

It's like my mis-spelling of "Multiple" before.   If you're going to put something new on the gallery. l am about to put in a small PR.

**Comment by dfinke** [comment]
I'll merge this PR and wait for yours

**Comment by jhoneill** [comment]
"Incoming !" :-) All minor stuff. But starting to proof read help. Fixed "Position" missing was an "I" in multiple places in the help text.
