### ISSUE TITLE
refresh pivot tables

### ISSUE THREAD

**Issue by Geraldziu** [dfinke/ImportExcel#443]
Hi,

I have this situation: Users have Excel files with pivot tables, which it takes a long time to refresh. In addition, refreshing them kills OLAP cubes. To streamline this process, we have an application that every night updates each file.
We would like to get rid of this application and replace it with something else.

Is it possible to write a script using the ImportExcel module to go through each file in the network location and refresh the pivot tables in it and save the files with new data?

**Comment by Geraldziu** [comment]
Thx for the quick reply.

Is there a way of manipulating COM object model without installing Excel?

**Comment by jhoneill** [comment]
No. You need Excel installed to either 
* Fetch data from an external source defined in sheet (you can write the data to the cells of the sheet from the module).
* Re-calculate the pivoted data. 
And you can control Excel using COM
If it is fetching the data that is slow, and doing the pivot when the file is loaded is fast enough you could update the data using the module. But if the pivot operation is slow then the best you can do is to run a task on a machine with Excel on it to load the file, do the update and save the file. (Which you seem to be doing already). 
Sorry .
James.
