### ISSUE TITLE
Another Potential Enhancement; Charts

### ISSUE THREAD

**Issue by forensicsguy20012004** [dfinke/ImportExcel#45]
This could be another enhancement if not already available and if so, my fault. I was thinking about basic charting. Essentially something along the plotting disk growth over time. Say have a variable that allows a hashtable to be passed; and in that hashtable one could pass the fields for the X and Y coordinates. I might already be there and I have not see it or missed it, totally my fault. As I have said before the module is AWESOME, keep up the good work.

Thanks,
Forensicsguy20012004

**Comment by dfinke** [comment]
The charts in Excel work off the data in a sheet. So, would if you could create a sheet with this data and then tell it to create a chart from it, is that what you're thinking?

**Comment by forensicsguy20012004** [comment]
Yep, that is exactly what I was thinking of. Have the data-sheet produce the chart and then if the end-user wants hide the data-sheet. For the record, I apologize, for the all enhancement requests/ideas. I just love your module.

Forensicsguy20012004

**Comment by dfinke** [comment]
This is great feedback. I haven't exposed charting outside of pivot tables. I need to prioritize this.

**Comment by forensicsguy20012004** [comment]
So, let's say we take this one more step, bear with me. We have all of these tabs/data-sheets that would then be used to generate another tab/data-sheet for the chart/graph; instead of all these individual charts/graphs; let's put them all on one single tab/data-sheet. So essentially we would be creating a dashboard. One more step, there would be some drop-downs and an end-user would select some other way to slide-n-dice the data and the charts/graphs would change. As you probably see, the idea would be to truly create interactive dashboards based on tabs/data-sheets. How I envision using this is pulling data from MSSQL to populate the individual tabs/data-sheets. Now we are leveraging some seriously powerfull stuff here, MSSQL, Powershell, and Excel...it is a winning combination. Either way the module is AWESOME, keep up the great work.

Thanks,
Forensicsguy20012004

**Comment by dfinke** [comment]
I'm playing around with adding this:

![image](https://cloud.githubusercontent.com/assets/67258/10517485/ef2d857e-732a-11e5-9ecb-2b1d04f92740.png)

**Comment by forensicsguy20012004** [comment]
That looks AWESOME. This is fantastic work. You have really done some amazing work here.

**Comment by forensicsguy20012004** [comment]
So, here is kind of a snap-shot of what I was thinking. All of this data is driven off a single spreadsheet and all of these "charts" would be indicators.

Mind you this is all made up data in the screenshot but it would give you an idea of what I mean. Then a "slicer" could be added that would auto-adjust the charts. Let me know what you think.

![image](https://cloud.githubusercontent.com/assets/12624999/10524592/6b1cb1b4-734e-11e5-9a63-a20002f29d9a.png)

**Comment by dfinke** [comment]
Thanks, that's great. Are the **Total Databases** and **Distinct Machines** just cells with different fonts?

**Comment by forensicsguy20012004** [comment]
Yeah, they are just different cells and different fonts. But I think you kind of see where I am going with this? Essentially creating a PowerBI dashboard but all within Powershell code driven off maybe a single or a couple tabs/data-sheets. Seems monumental.

**Comment by dfinke** [comment]
Hi @forensicsguy20012004, I'd like to dive a little deeper. If you ok with it, please email me at finked hotmail.

Thanks
Doug

**Comment by forensicsguy20012004** [comment]
Sent over an email to you from my gmail account. Look forward to chatting with you.
