### ISSUE TITLE
Set-ExcelPrintFormatting ?

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#452]
Thanks to all contributors, the module is continuously improving!

I am thinking that my function Set-ExcelPrintFormatting would be useful to other module users:

   .SYNOPSIS
    Given an Excel workbook, set the print formatting of a given SheetName, or all sheets
   .DESCRIPTION
    Formatting includes (defaults in parens)
    all 3 headers (date/filename/time),
    all 3 footers (userdefined/sheetname/page#),
    all margins (narrow)
    ShowGridlines (true)
    Orientation (Landscape)
    PaperSize (Tabloid)
    FitToPagesWide (1)
    PrintTitleRowCount (1)
    WrapText (false) 

https://gist.github.com/scottone/09f8daf9c5cb26a92d603218edca9d62

**Comment by dfinke** [comment]
Cool! Please consider doing a PR, add tests, and we can better review this as an addition.

Thanks
