### ISSUE TITLE
PivotTable.ps1 parameter PivotTableSyle should be PivotTableStyle

### ISSUE THREAD

**Issue by scottone** [dfinke/ImportExcel#453]
just noticed this today...

**Comment by dfinke** [comment]
Thanks.

**Comment by jhoneill** [comment]
#FacePalm 

Note for @dfinke  when James adds a parameter or function, double and triple check the spelling :-( 

Was that before or after 5.3.3 went up. ?

**Comment by dfinke** [comment]
Yes. The fix is in a PR
