### ISSUE TITLE
Merge-MultipleSheets - Error: System.Drawing.Color

### ISSUE THREAD

**Issue by DomPizzie** [dfinke/ImportExcel#460]
Below error output when running example code from: [Merge_3_Servers_Services.ps1](https://github.com/dfinke/ImportExcel/blob/master/Examples/MergeWorkSheet/Merge_3_Servers_Services.ps1)

``` Powershell
Merge-MultipleSheets : Cannot process argument transformation on parameter 'KeyFontColor'. Cannot convert the "Red" value of type "System.String" to type "System.Drawing.Color".
At C:\Users\example\Documents\Scripts\example.ps1:34 char:1
+ Merge-MultipleSheets -Path "$env:temp\server1.xlsx", "$env:temp\Serve ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Merge-MultipleSheets], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Merge-MultipleSheets
```

Computer  Details
```
Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Potentiality related to #150

**Comment by jhoneill** [comment]
It appears that .net core can't convert a string to `[System.Drawing.Color]`
 
`[System.Drawing.Color]"Red"` works in PS 5 but not PS 6; so any code which uses a string will fail
 I've fixed the parameter defaults in MergeWorksheet and in New-ConditionalText to use `[System.Drawing.Color]::Red`  This will go in the next PR I submit, but it is on my repo now, and the example works with Ps 6. There are a few things in the EPPlus library which fail with .Net core probably more things in the module which will need fixing. PLEASE keep pointing them out.

**Comment by dfinke** [comment]
I added a step to the Appveyor CI to run PS Core v6. Not sure if it will ultimately be helpful. 

It did catch this.

```
  Describing Join Worksheet
    [-] Error occurred in Describe block 116ms
      PSInvalidCastException: Cannot convert the "AliceBlue" value of type "System.String" to type "System.Drawing.Color".
      ArgumentTransformationMetadataException: Cannot convert the "AliceBlue" value of type "System.String" to type "System.Drawing.Color".
```

**Comment by jhoneill** [comment]
Ha. I searched for red , orange, green and pink, but not blue ! Turns out I used a lot of other colours - Beige, black, purple, white.

**Comment by dfinke** [comment]
You are a man of many colors :-)

**Comment by dfinke** [comment]
Hey @jhoneill, were you going to do a PR for this?

**Comment by jhoneill** [comment]
Been testing it today :-) I have to remove [sytem.drawing.color] from all color parameters and then if they strings use a different conversion to turn the strings to Color object. I've changed that everywhere and the existing tests all pass. I want to give it a bit more of a kick before putting the PR in, but expect that soon - with a couple of other minor things and a bunch of changes from having the help proof-read.

**Comment by dfinke** [comment]
Thanks! Sounds good. I've got the Azure DevOps pipeline wired up. It was catching the Color issues, it is throwing elsewhere. I runs on PRs. Probably useful as a smoke test.
