### ISSUE TITLE
want to import an excel spreadsheet and show last logondate in AD

### ISSUE THREAD

**Issue by quezadacruz** [dfinke/ImportExcel#461]
I have an excel spreadsheet where i have a list of users 

i want to be able to import this spreadsheet and add a column that includes that users LastLogonDate

the column which i want to grab information from is titled UserPrincipalName

**Comment by clsmith70** [comment]
My suggestion is to pull the user accounts by SamAccountName as this value is tied to the -Identity parameter of Get-ADUser.  You can populate a new Workbook with the data you want by running the following command (you can change the list of properties for Select-Object to include the values you need to have):

`Get-ADUser -Property LastLogonDate | Select-Object UserPrincipalName,Name,SamAccountName,LastLogonDate | Export-Excel -Path $env:TEMP\LastLogon.xlsx -WorksheetName 'AD User Last Logon' -Show`

**Comment by quezadacruz** [comment]
Thank you that is also very helpful. The problem is i need a script that can check the AD last logon date and also the o365 last log on date as well.  Im having a hard time merging a script that can scan at the AD level then the users who were detected in my query take those results and run the script in 0365.

heres my script


$jqhash=@{
UsersOnly = $True
AccountInactive = $True
TimeSpan = New-Timespan -Days 30
SearchBase = "DC=company,dc=com"

}
 
Search-ADAccount @jqHash | Select Name,UserPrincipalName,LastLogonDate | Export-Excel lastlogon.xlsx -show -AutoSize -AutoFilter


I want to take the results from this script and then be able to import the o365 module and run the script for last logon date pon o365 for those user

**Comment by clsmith70** [comment]
Try running your search and saving it in a variable, then loop through that variable getting the LastLogonTime from Office 365.  Then you can export one file and have the data you're looking for.

`$lastLogonAd = Search-ADAccount @jqhash | Select Name,UserPrincipalName,LastLogonDate`

`$lastLogonAd | Foreach-Object { $upn = $_.UserPrincipalName; Get-MailboxStatistics $upn | Select-Object DisplayName,@{n='UserPrincipalName';e={$upn}},LastLogonTime } | Export-Excel -Path $env:TEMP\LastLogon.xlsx -AutoSize -Show`

**Comment by clsmith70** [comment]
You can actually import the MSOnline module and connect to Office 365 before the first line I posted.  The resulting Excel Workbook will contain the LastLogon data from Office 365.  If you want/need the AD data, you can also pipe the $lastLogonAD variable to Export-Excel to save that data.
