### ISSUE TITLE
ConvertTo-ExcelXlsx pipeline support

### ISSUE THREAD

**Issue by clsmith70** [dfinke/ImportExcel#462]
Can you change the behavior of ConvertTo-ExcelXlsx so that it does not require a filename and allow a user to pipe the output to another command like Tee-Object or Invoke-RestMethod?

**Comment by dfinke** [comment]
Could you say a bit more about this. Also an example of what you're looking to do

**Comment by clsmith70** [comment]
When I try running the following:
$Proc | ConvertTo-ExcelXlsx | Tee-Object -FilePath C:\PSReports\Proc.xlsx

I get this
File not found
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.3.4\ConvertToExcelXlsx.ps1:13 char:13
+             throw "File not found"
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (File not found:String) [], RuntimeException
    + FullyQualifiedErrorId : File not found

Maybe I'm using this cmdlet wrong, but I was under the impression that I could convert data to Excel format on the pipeline.

**Comment by dfinke** [comment]
`ConvertTo-ExcelXlsx` converts older Excel formats to the newer format.

## Try

```powershell
Get-Service | Export-Excel $env:TEMP\gsv.xlsx -show
```

**Comment by clsmith70** [comment]
That makes sense why it wouldn't work like I thought.  I've already created a workbook like that (posted a blog entry on it) and I was trying to figure out how to add a worksheet to an existing workbook.  Is that a supported option?

**Comment by dfinke** [comment]
Please could you post a link to your blog here.

## Try
```powershell
Get-Service | Export-Excel $env:TEMP\data.xlsx
Get-Process | Select Company, Name, Handles | Export-Excel $env:TEMP\data.xlsx -WorksheetName GetProcess  -show
```

**Comment by clsmith70** [comment]
I just started this blog and plan to cover PowerShell, modules and other time-saving tools.

https://www.it-splat.com/2018/10/using-importexcel-module-first-look.html

**Comment by dfinke** [comment]
Great write up @clsmith70, thanks for doing that. 

Saw this needed changing.
`One last thing to so is create` -> `One last thing to do is create`

That's publicly posted? Let me know if you tweet it etc, happy to amplify it.

Thanks again!

**Comment by clsmith70** [comment]
Thanks for catching that, I've updated it.  Yes, this blog is public and I did tweet it out the other day.  I tweeted once publicly with a shortened URL and once as a reply to a message from @jsnover about this module.  In the public post, I used the hashtags #PowerShell and #ImportExcel.

**Comment by clsmith70** [comment]
I'm closing this one out.  I'm posting a new one for you that I want to prep for a new blog post.

**Comment by dfinke** [comment]
@clsmith70 What is your Twitter ID?

**Comment by clsmith70** [comment]
@03HarleyRider
