### ISSUE TITLE
Export-Excel Question about Conditional Formatting when date is > x # of days

### ISSUE THREAD

**Issue by mrpaulwasserman** [dfinke/ImportExcel#463]
Hello.
I looked through the examples (like the one below) which formats rows for the last month.  Is it possible to format if a date is > x # of days?
 
<Export-Excel $f -Show -AutoSize   -ConditionalText $(New-ConditionalText -ConditionalType LastMonth)>
Thank you very much!
Paul

**Comment by jhoneill** [comment]
Like this ? 
`dir -File | select name,LastWriteTime | export-excel -path "$env:TEMP\foo.xlsx" -ClearSheet -AutoNameRange  -ConditionalText (New-ConditionalText -ConditionalType GreaterThan -Text "=Int(Now() - 5)" -BackgroundColor LightBlue -Range Lastwritetime ) -Show`

**Comment by jhoneill** [comment]
Like this ? 
`dir -File | select name,LastWriteTime | export-excel -path "$env:TEMP\foo.xlsx" -ClearSheet -AutoNameRange  -ConditionalText (New-ConditionalText -ConditionalType GreaterThan -Text "=Int(Now() - 5)" -BackgroundColor LightBlue -Range Lastwritetime ) -Show`
