### ISSUE TITLE
Lost formatting adding a sheet to a workbook

### ISSUE THREAD

**Issue by clsmith70** [dfinke/ImportExcel#464]
I wanted to go through the steps to add a worksheet to an existing workbook.  I figured out the best way (at the moment) is to create a new workbook with the data and then copy a worksheet from another workbook.  The steps all worked fine, but when the workbook is opened in Excel, I get errors and all formatting is lost.

Steps to reproduce:

`Get-Process | select Company,Name,Handles | Export-Excel C:\IT-Splat\ddm.xlsx -WorksheetName 'All Processes' -Show -Append -MoveToEnd -ChartType ColumnClustered -ColumnChart -TableName 'All_Procs' -TableStyle Dark4`
`$ExcelPackage = Open-ExcelPackage -Path C:\IT-Splat\procs.xlsx`
`$sourcePackage = Open-ExcelPackage C:\IT-Splat\ddm.xlsx`
`$ws = Add-WorkSheet -ExcelPackage $sourcePackage -WorksheetName 'DDM Data'`
`$ExcelPackage | Add-WorkSheet -WorksheetName 'DDM Data' -MoveToEnd -CopySource $ws -Activate`
`Close-ExcelPackage -ExcelPackage $ExcelPackage -Show`

After opening the workbook, Excel reports that it found a problem
![image](https://user-images.githubusercontent.com/6304269/46805149-674da200-cd32-11e8-85d4-7203ff13bb32.png)

Then I get a "Repairs" dialog
![image](https://user-images.githubusercontent.com/6304269/46805179-76345480-cd32-11e8-84d6-d538b12691ee.png)

All of the data is in the workbook, but the formatting of the two tables is lost.

**Comment by jhoneill** [comment]
This is bug in EEPlus, I can't remember now if it is one which replaced with new bugs in the later version or if I reported it. 
But if you copy a worksheet which contains a table, excel throws this error. 
If you have the option to add the tables at the end (using different names on each sheet) that should work.
