### ISSUE TITLE
Cannot find type [OfficeOpenXml.ExcelPackage]: verify that the assembly containing this type is loaded. 

### ISSUE THREAD

**Issue by cramirezoliveros** [dfinke/ImportExcel#466]
Hello, I´m new with Powershell, I am triying to use ImportExcel, but I get the error:
Cannot find type [OfficeOpenXml.ExcelPackage]: verify that the assembly containing this type is loaded. 
I appreciate your help.
 $DataSetTable | Export-Excel c:\temp\test.xlsx -WorkSheetname test -show

**Comment by dfinke** [comment]
What version of ImportExcel did you install? `gmo -list importexcel`

## Does this work?

```powershell
get-service | export-excel
```

**Comment by cramirezoliveros** [comment]
> gmo -list importexcel

Script     5.3.4      ImportExcel                         {New-Plot, Import-Excel, ConvertFrom-ExcelSheet, Export-MultipleExcelSheets...}

**Comment by dfinke** [comment]
What PS version and what OS?

**Comment by cramirezoliveros** [comment]
Windos 7
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

**Comment by dfinke** [comment]
This module is not tested on older PS versions. Could you do a sanity check and see if you can run it on 5.0 and higher?

**Comment by clsmith70** [comment]
@cramirezoliveros it also works great in PowerShell 6 Core which is available at https://github.com/PowerShell/PowerShell - scroll down to the **Get Powershell** section.

**Comment by cramirezoliveros** [comment]
Hello, thank you, i installed the version 5.1 and Installed again ImportExcel, but conected to other Internet (my cell phone), and this time, work.
Thank you
