### ISSUE TITLE
Date Comparision

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#467]
I am trying to compare the date in column B (SourceDate) to the Date in Column C  (TargetDate) and highlight the date in Column B with a red background if it is greaterthan Column C.  I have this but it is not working.  Any suggestions?

`$Test_Data =@"
Server,SourceDate,TargetDate
SRV1,10/11/2018,10/1/2018
srv2,10/11/2018,10/11/2018
srv3,10/1/2018,10/11/2018
"@ | convertfrom-csv 

$Test_Data | export-excel -path D:\test.xlsx -WorksheetName Test -TableName Test -AutoSize -ClearSheet `
    -ConditionalFormat $(New-ConditionalText -Range B:B -ConditionalType GreaterThan $c$2 -BackgroundColor red) -Show`

**Comment by jhoneill** [comment]
I haven't tested it but try "=C1" 

I think without the = , when you look in Excel you will have  GreaterThan  "$c$2" 
If you put the $C$2 it will  always compare against the same cell . 
If you put C2 for the whole of column b, B1 will be compared with C2, B2 with C3 and so on.

**Comment by g-pearl** [comment]
Thanks that is just want I needed.  

I have one more questions.  If I did not want to compare to another column but the actual date what would I use.  

I tried =now(), =today(), =$(get-date)  I am also tried now()-11 for eleven days old

**Comment by jhoneill** [comment]
A very similar thing was asked in #463 
"=Int(Now() - 5)"  should work - the int makes sure you get the right day - otherwise if it is the wrong time of day it won't match.

**Comment by dfinke** [comment]
Cool, the `=C1` works and I have no idea why.

**Comment by jhoneill** [comment]
I'll add some help examples and tests :-) But the simple version is write what you write in a cell, that you will then fill down.  If you start the format at row 3 it would need to be C3 
Without the = it will be treated as a string literal, i.e. if the text in the Cell softs after "C1"
