### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by bzyg7b** [dfinke/ImportExcel#469]
Stupid question, but is it possible to install InportExcel in an environment where NuGet is blocked?
I was able to download the .nupkg and extract it however am unable to install it.

**Comment by dfinke** [comment]
Use to have a way to grab it from GitHub, but it wasn't really used and didn't maintain it

**Comment by bzyg7b** [comment]
do you think I could still use the old GitHub way to get something?

**Comment by dfinke** [comment]
No. I don't believe the files.txt has been maintained

**Comment by bzyg7b** [comment]
Dam :( Guess I will have to try and get NuGet unblocked unless there is a way to move it after getting it from NuGet?
