### ISSUE TITLE
Allow for import to skip X rows at the top of sheet

### ISSUE THREAD

**Issue by GregGallaway** [dfinke/ImportExcel#47]
I have an application that exports data to an excel workbook. Currently I have to go in and remove the first row of data before importing using ImportExcel. This is because the "header" row is on the 2nd row instead of the first, as expected. Therefore, I think it would be nice, and there may be other uses if we could set a variable that begins importing data at the nth row instead of always starting from the first row,
I have included an example of the export from this application.
<img width="554" alt="capture" src="https://cloud.githubusercontent.com/assets/15203061/10592375/8a98da5c-7670-11e5-9218-088e35827fed.PNG">

**Comment by dfinke** [comment]
Something like `Import-Excel target.xlsx -HeadingStartsAt 2`

**Comment by GregGallaway** [comment]
Yes, that would work or perhaps just Import-Excel target.xlsx -HeaderRow 2
