### ISSUE TITLE
Provide an option to create a Comment in a cell during Export-Excel?

### ISSUE THREAD

**Issue by lucdekens** [dfinke/ImportExcel#472]
Would it technically be possible to implement the creation of a Comment on a cell in a Worksheet created with Export-Excel?

On the Export-Excel we could indicate that 1 column in the PS table is in fact to be exported as Comment fields on data in another column.

I often use comments as a way to keep the worksheets "clean", while still having the info available when needed.

For example, statistical data could have the Unit as a comment, instead of having a separate column for that.
Another example could be a list of API methods and their parameters, and the Comment fields could contain text that describes the method and the parameters.

**Comment by dfinke** [comment]
Thanks @lucdekens I like that. Looks like it'd possible to make that happen. Needs to be experimented with. Could you post a simple xlsx with how you like to lay that  out?
https://github.com/JanKallman/EPPlus/wiki/Adding-a-comment

**Comment by lucdekens** [comment]
Sure, I attach 2 examples XLSX files.
The 1st one (stats.xlsx) contains 2 worksheets, one with the Unit value as a separate column, the other with the Unit value as a Comment on the Value column entries.
The other example (services.xlsx) is an extract from a XRef to a number of services.
The table is not cluttered by the description of each method, since the description is entered as a comment in the corresponding cells.
[stats.xlsx](https://github.com/dfinke/ImportExcel/files/2502555/stats.xlsx)
[Services.xlsx](https://github.com/dfinke/ImportExcel/files/2502557/Services.xlsx)

**Comment by dfinke** [comment]
This should work. Can think through how to make it easier.

```powershell
$path = "$env:TEMP\services.xlsx"
rm $path -ErrorAction SilentlyContinue

$pkg = ConvertFrom-Csv @"
Name,add,create,delete,get,get_0,list,post,put,set,update
com.vmware.vmc.locale,,,,,,,,,x,,
com.vmware.vmc.orgs,,,,x,,x,,,,
com.vmware.vmc.orgs.account_link,,,,x,,,,,,
com.vmware.vmc.orgs.account_link.compatible_subnets,,,,x,,,x,,,
com.vmware.vmc.orgs.account_link.compatible_subnets_async,,,,x,,,x,,,
"@ | Export-Excel -Path $path -WorksheetName Services -PassThru -AutoSize

$ws=$pkg.Workbook.Worksheets["Services"]

$null=$ws.Cells["J2"].AddComment("Sets the locale for the session which is used for translating responses.", "LucD")
$null=$ws.Cells["E3"].AddComment("Sets the locale for the session which is used for translating responses.", "LucD")
$null=$ws.Cells["H6"].AddComment("Sets which subnet to use to link accounts and finishes the linking process via a task.", "LucD")

Close-ExcelPackage $pkg -Show
```

**Comment by jhoneill** [comment]
A quick proposal. 
An Add-ExcelComment function which takes a worksheet, a location and the string to be the comment 

An extra parameter for export-excel -Comments which takes an array of hash tables which are 
@{Location="A1" ;  Text="This is the top left"} 
which are then splatted into Add-ExcelComment.

**Comment by dfinke** [comment]
Great minds think alike. Thought the challenge with that is you need to build the sheet, then look at it and finally work up the `Add-ExcelComment` logic transcribing Excel sheet coordinates. 

Not sure how much that can be improved. So, will build it first, then make it better.
