### ISSUE TITLE
Way to set column with leading zeros?

### ISSUE THREAD

**Issue by Crossbones18** [dfinke/ImportExcel#478]
Hey guys, 

I have an .htm file that I convert to .xlsx. One column in particular, Column E, has a 12-digit number in each cell. Some start with a leading zero, others do not. I thought by setting the format to text, it would keep the zeros, and show the entire number. For some reason, that is not the case. Here is a snippet the script I am working with (P5 is the column in question):

```
## Build custom object which allows for modification of the spreadsheet that will be generated
$xls = ForEach ($item in $spreadsheet | Where-Object {$PSItem.P4 -match '\w+'}) {
    [pscustomobject]@{
        ## Define the colums for the CSV file
        'MnsTransTy'      = $item.P1.TrimStart()
        'Del. Date'       = $item.P2
        'Time'            = $item.P3
        'Name 1'          = $item.P4
        'Purch.Doc.'      = [string]$item.P5
        ## Remove white space
        'Cases'           = $item.P6.TrimStart()
        ## Remove white space
        'line'            = $item.P7.TrimStart()
        'Name'            = $item.P8
        ## Remove white space
        'Tot Pallet'      = $Item.P9.TrimStart()
    }
}

## Create a package and export to XLSX
$xlPkg=$xls | Export-Excel -Path $filelocation\$filename.xlsx -WorkSheetname $worksheetname -PassThru

## Create new directory based on date
New-Item -Path $processedfiles -ItemType Directory

## Move local htm files to processed file on azrscripts1
Move-Item $logicappsfiles $processedfiles

#Create worksheet to be used for modifications
$WorkSheet = $xlPkg.Workbook.WorkSheets[$worksheetname]

#Set row E in the spreadsheet, the Purch Doc row to a number format
Set-Format -WorkSheet $WorkSheet -Range "E:E" -NumberFormat '@'

#close the package
Close-ExcelPackage $xlPkg
```
Here is the column output. This particular number should be one with a leading zero. 
![image of spreadsheet](https://i.imgur.com/hMz9f6v.png)

I hope this is an easy fix, and I'm just missing something. As always, I appreciate the help!

**Comment by jhoneill** [comment]
Export-Excel will convert strings to numbers by default (more often than not that is what is wanted), it sounds like this is the other case, so to keep the string as a string use 
`-NoNumberConversion "Purch.Doc"`
Alternatively if they are numbers and you always want them as 12 digits with leading zeros as required 
`Set-Format -WorkSheet $WorkSheet -Range "E:E" -NumberFormat '000000000000'`

**Comment by Crossbones18** [comment]
@jhoneill Thank you for this. Looks like we're in business now. I appreciate your help.
