### ISSUE TITLE
Clearer error message when user does not have permissions on target path

### ISSUE THREAD

**Issue by janegilring** [dfinke/ImportExcel#480]
I was recently troubleshooting the following error in an Azure Automation runbook which exports some data to an xlsx-file:
Exception calling "Save" with "0" argument(s): "Error saving file C:\temp\report.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.3.4\Export-Excel.ps1:1024 char:30
             else           { $pkg.Save() }
                              ~~~~~~~~~~~
    CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    FullyQualifiedErrorId : InvalidOperationException

When run manually, it worked fine.

It turned out to be lacking NTFS permission for the executing user (Azure Automation runbooks by default runs under the Network Service context).

Would it be possible to catch the lack of necessary permissions and return information about this in the error message?

**Comment by jhoneill** [comment]
The save() method of the ExcelPackage object doesn't return very descriptive errors. We can add a check for a valid path but that won't pick up a lack of write permissions. 
I'd recommend putting these checks in the script that calls Export-excel  - that way catches all the things which can go wrong in a given environment.

**Comment by janegilring** [comment]
That`s a good point - I'll go ahead and close the issue.
