### ISSUE TITLE
How to change cell format to Date category ???

### ISSUE THREAD

**Issue by gintaraskuc** [dfinke/ImportExcel#481]
Hello, 
Is it a way to change cells format to Date category ? 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/44566641/47636929-baad5600-db62-11e8-8ee1-cb05b9acb6fc.png">

**Comment by jhoneill** [comment]
If the data is a dateTime value it should be formatted as a dateTime. 

You can also use  `$XL = $stuff | Export-Excel -PassThru <<other parameters >>`
or `$xl = Open-ExcelPackage <<path.xlsx>>`
followed by 
`Set-ExcelColumn -Worksheet $xl.SheetName  -Column 19 -NumberFormat 'Short Date' `
or  
`Set-ExcelRow -Worksheet $xl.SheetName  -Row 17 -NumberFormat 'Short Time'`
or 
`Set-ExcelRange --WorkSheet $xl.SheetName  Range "P1:R20"  -NumberFormat "yy-MM-dd"`

and finally 
`Close-excelPackage $xl`

To set a different format.  If there are no numbers, only dates, in your sheet you can also use 
`-NumberFormat` with `Export-Excel`.

**Comment by gintaraskuc** [comment]
When I use custom format "mm/dd/yyyy" output result looks good, but when I change cell format later on the file to General value is not changed to number like normal way in excel.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/44566641/47669728-35eb2800-dbb4-11e8-9609-c8cb012b9b4f.png">

Cell changed to General after Export-Excel generate a file.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/44566641/47670077-0ab50880-dbb5-11e8-8560-13f26b217aab.png">

Regular excel behavior when date is changing to number ....
<img width="639" alt="image" src="https://user-images.githubusercontent.com/44566641/47670399-ba8a7600-dbb5-11e8-9eaa-b93054409f8c.png">


Can I solve such date issue on Export-Excel tool ?

**Comment by jhoneill** [comment]
if you explicitly set number, what do you get ? My guess is the data you are sending is not a number or datetime object but a string representation of the date. If the string is in US format you can cast it as a dateTime, otherwise you need to use one of the parse methods to convert it.

**Comment by jhoneill** [comment]
So, I guess you are going 
import-csv  <> | export-excel 

If you do Import-csv | get-member, does the field you want to be a data say "String" or "Datetime" next to it ? I'm betting it says string 
Export-Excel doesn't try to convert strings to dates, so it does into the .xlsx file as text. The things you do in Excel cause Excel to change it from text to date. 


You said  _When I use custom format "mm/dd/yyyy"_    if you use "mm/dd/yyyy HH:mm" do you get a time or do you still get the same thing if there is no time (even if your file has dates, it should show as "00:00" ) you are inserting text, and you need to convert it before passing it into Export-Excel.

**Comment by DarkLite1** [comment]
Just as a side note, it might just be as simple as preformatting your property to a `DateTime` format as suggested by @jhoneill . A small example:

```powershell
@"
    Name, DateOfBirth
    Bob, 02/02/1982
    George, 21/01/1982
    Chuck, 01/21/1982
"@ | ConvertFrom-Csv -Delimiter ',' | 
    Select-Object -Property Name, DateOfBirth, 
        @{Name = 'DateTime'; Expression = {[DateTime]$_.DateOfBirth}} |
    Export-Excel ...
```

**Comment by gintaraskuc** [comment]
Thank you for support. It helped me to convert text as DateTime format.
