### ISSUE TITLE
Could not get worksheet

### ISSUE THREAD

**Issue by mjcreamer** [dfinke/ImportExcel#483]
I would like to load an Excel workbook, freeze the top row, then save it.  I'm using this command:

**Export-Excel -Path $ReportOutput -WorksheetName "FiscalYearCollections" -FreezeTopRow**

But I get the error "Could not get worksheet FiscalYearCollections."

There is only 1 worksheet in the workbook and the name is correct.

**Comment by DarkLite1** [comment]
When I run the following code:

```powershell
$ReportOutput = 'S:\Test\test.xlsx'
Export-Excel -Path $ReportOutput -WorksheetName "FiscalYearCollections" -FreezeTopRow
```
An empty worksheet called 'FiscalYearCollections' is added and the top row is frozen. No data in the worksheet though. 

What are you trying to achieve? Are you trying to export data to the worksheet 'FiscalYearCollections'? Or are you trying to format an existing worksheet?

**Comment by mjcreamer** [comment]
I'm trying to format an existing worksheet.

**Comment by DarkLite1** [comment]
I think this cannot be done with the default CmdLets. It would be great if there was something like `Get-ExcelWorksheet` and then do some manipulations on it.

Please give this a go:

```powershell
$Path = 'File.xlsx'
$WorkSheetName = 'FiscalYearCollections'

$Stream = New-Object -TypeName System.IO.FileStream -ArgumentList $Path, 'Open', 'Read', 'ReadWrite'
$Excel = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Stream
$ws = $Excel.Workbook.Worksheets[$WorkSheetName]

# Freeze the top row
$ws.View.FreezePanes(2, 1)

$Excel.Save()

$Stream.Close()
$Stream.Dispose()
$Excel.Dispose()
```

**Comment by jhoneill** [comment]
```
dir | select name,LastWriteTime | export-excel -Path deleteme.xlsx -WorksheetName "FiscalYearCollections"                                                                                                                          
export-excel deleteme.xlsx -FreezeTopRow -WorksheetName "FiscalYearCollections"                                                                                                        start .\deleteme.xlsx 
```
Works for me.

If the worksheet doesn't exist running the second command creates an empty one frozen at the top row 
Can you give a bit more of the error message ?  
What version of the module do you have ? 
If you copy and paste my trivial example, does it work ?

**Comment by reclaimed** [comment]
Not the same problem, but I'll write it here.

Get-ExcelSheetInfo yields list that needs a bit of unneeded work to get the job done. Not a problem when using in a script, but pretty annoying when used CLI.

```
PS> $sheets = Get-ExcelSheetInfo 'test.xlsx'
PS> $sheets | fl
Name   : coworkers
Index  : 1
Hidden : Visible
Path   : test.xlsx

Name   : presents
Index  : 2
Hidden : Visible
Path   : test.xlsx

PS> $rows = Import-Excel test.xlsx -WorksheetName $sheets[1]
Failed importing the Excel workbook 'test.xslx' with worksheet '@{Name=coworkers; Index=1; Hidden=Visible; Path=test.xlsx}'...
```

Of course, it can't import the worksheet calling it with that kind of a name. And I would call the ToString method of $sheets (yes, its elements do have this method), but it returns zero length strings:
```
PS> $sheets[1].ToString().length
0
```

The only thing that works is ($sheets[1] | select -ExpandProperty name), but it's not the thing you love to type every second time :)

And thanks for the module, Doug!

**Comment by wisemoth** [comment]
This is still happening for me; using the above example:
```
> dir | select name,LastWriteTime | export-excel -Path deleteme.xlsx -WorksheetName "FiscalYearCollections"                                                                          
Could not get worksheet FiscalYearCollections
At C:\Program Files\WindowsPowerShell\Modules\importexcel\7.0.1\Public\Export-Excel.ps1:133 char:16
+         catch {throw "Could not get worksheet $worksheetname"}
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not get w...YearCollections:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not get worksheet FiscalYearCollections
```

**Comment by dfinke** [comment]
Ran this version on PS both v5.1 and v7.0, only two files in the dir tho, no issues.

```
ModuleType Version    PreRelease Name 
---------- -------    ---------- ----              
Script     7.0.1                 ImportExcel
```

**Comment by wisemoth** [comment]
My experiment was also on PS v5.1 and ImportExcel 7.0.1; and I selecting 2 files from the dir:
```
> dir \windows | select -last 2| select name,LastWriteTime | export-excel -Path deleteme.xlsx -WorksheetName "FiscalYearCollections"
Could not get worksheet FiscalYearCollections
At C:\Program Files\WindowsPowerShell\Modules\importexcel\7.0.1\Public\Export-Excel.ps1:133 char:16
+         catch {throw "Could not get worksheet $worksheetname"}
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not get w...YearCollections:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not get worksheet FiscalYearCollections
```

Are there any other experiments/diagnostics that would assist? I can also try to dig into it further.

**Comment by dfinke** [comment]
Does `get-process` work? Can you show a screenshot of the `dir`? What `culture` are you running in? Just guesses.

**Comment by wisemoth** [comment]
`get-process` doesn't work either:
```
> get-process | select name,id | select -first 5 | export-excel -Path deleteme.xlsx -WorksheetName test
Could not get worksheet test
At C:\Program Files\WindowsPowerShell\Modules\importexcel\7.0.1\Public\Export-Excel.ps1:133 char:16
+         catch {throw "Could not get worksheet $worksheetname"}
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not get worksheet test:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not get worksheet test

> Get-Culture

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```

**Comment by dfinke** [comment]
`"hello world" |Export-Excel`

**Comment by wisemoth** [comment]
Oh. Strange. That gave the same error.  I accidentally closed my powershell host, restarted, re-imported `psexcel`, and now the hello-world and get-process experiments are working.

**Comment by dfinke** [comment]
When in doubt, close it out. :)
