### ISSUE TITLE
ConvertFrom-ExcelToSqlInsert - Error: Maximun length is 128

### ISSUE THREAD

**Issue by sedgecameron** [dfinke/ImportExcel#485]
I was wondering if there is a limit on the cell values to be used for the ConvertFrom-ExcelToSqlInsert?
I have successfully imported a spreadsheet into a table for testing purposes, but when I use realistic test data of having multiple columns being over 2000 characters I get the below error in PS.  The data types and sizes are correct in the table.
Error: The identifier that starts with 'This is an example text' is too long. Maximum length is 128.

Is this a restriction that you are aware of and if so is there a way to overwrite this default?

Many thanks

**Comment by jhoneill** [comment]
Is your very long text being treated as a column name. I just tried with data where one column is between 178 and 2160 chars and it appears to be fine with that.

**Comment by sedgecameron** [comment]
Thanks, I think it was a red herring.  there are single quotes in the text which is causing the issue.
Thanks
