### ISSUE TITLE
Where did the Series code go?

### ISSUE THREAD

**Issue by jubejube56** [dfinke/ImportExcel#486]
A while ago I submitted issue #420 which was solved by changing the $Series code slightly inside Export-Excel. A couple months have passed since then and I now get to proceed with what I was working on but more shenanigans mean I do not have the copy I used to have of ImportExcel. I downloaded the newest version but it seems the $Series logic that used to be in Export-Excel has been moved. I checked in the release notes but I didn't see where it went, do we know where it went so I could adjust that value in the latest version? Push comes to shove I can just grab a previous version and do it that way but I'd prefer to use the latest enhancements if possible. Thank you.

**Comment by jhoneill** [comment]
Hi, yes, I suggested a fix and for no obvious reason it never went into the main build.  (I think I intended to do some more testing) . I've moved the function Add-ExcelChart into New-ExcelChart.PS1 , and you can make the same modification, but I've put the code into my working copy and it should go from there into the "live" version soon.

**Comment by dfinke** [comment]
Perfect timing, I was just looking at publishing, I'll look at merging.

Thanks

**Comment by jubejube56** [comment]
Just tested it out and it seems be working just as I need it to. Thank you again.
