### ISSUE TITLE
Pivot Table "Magic" Pivot Date Row

### ISSUE THREAD

**Issue by dprice** [dfinke/ImportExcel#487]
Here's some code that simulates reading a log4net log, adding timestamp 30 second bucket data, and launching Excel with a pivot table on the timestamp bucket count:
```
$results = ConvertFrom-Csv @"
Timestamp,Tenant
10/29/2018 3:00:00.123,1
10/29/2018 3:00:10.456,1
10/29/2018 3:01:20.389,1
10/29/2018 3:00:30.222,1
10/29/2018 3:00:40.143,1
10/29/2018 3:00:50.809,1
10/29/2018 3:01:00.193,1
10/29/2018 3:01:10.555,1
10/29/2018 3:01:20.739,1
10/29/2018 3:01:30.912,1
10/29/2018 3:01:40.989,1
10/29/2018 3:01:50.545,1
10/29/2018 3:02:00.999,1
"@ | % {
    $dt = Get-Date($_.Timestamp)
    $data = [ordered]@{
        Timestamp = $dt
        Tenant = $_.Tenant
        Bucket = $dt.AddSeconds(-$dt.Second % 30)
    }
    New-Object -TypeName psobject -Property $data
}

$excelParams = @{
    Path              = 'd:\temp\pivottest.xlsx'
    WorkSheetname	  = "Log Data"
    IncludePivotTable = $true
    PivotTableName    = 'Timestamp Buckets'
    PivotRows         = @('Timestamp', 'Tenant')
    PivotData         = @{'Bucket' = 'count'}
    Activate          = $true
    AutoSize          = $true
    AutoFilter        = $true
    Show              = $true
}
Remove-Item $excelParams.Path -ErrorAction Ignore
$results | Export-Excel @excelParams
```
It works great:
![image](https://user-images.githubusercontent.com/84499/47938502-a64abf80-deba-11e8-856a-8e9e2b7fc85f.png)

But when you uncheck `Timestamp` and recheck it, Excel magically creates `Hours` and `Minutes` columns, which is what I really want:
![image](https://user-images.githubusercontent.com/84499/47938632-16594580-debb-11e8-9c7f-54f98b3811a4.png)

Any idea on how to get these columns created from the script?

**Comment by jhoneill** [comment]
@dprice  
Support for this was added in this weekend's new release 

```
$pivotDef = New-PivotTableDefinition -PivotTableName 'Timestamp Buckets' -PivotRows @('Timestamp', 'Tenant') -PivotData @{'Bucket' = 'count'} -GroupDateRow TimeStamp -GroupDatePart Hours,Minutes
    

$excelParams = @{
    Path                 = 'd:\temp\pivottest.xlsx'
    WorkSheetname  	     = "Log Data"
    PivotTableDefinition = $pivotDef
    Activate             = $true
    AutoSize             = $true
    AutoFilter           = $true
    Show                 = $true
}
```

**Comment by dprice** [comment]
That's awesome! I can't wait to try this. Excellent work!

**Comment by dfinke** [comment]
Added this to the examples
https://github.com/dfinke/ImportExcel/blob/master/Examples/Grouping/TimestampBucket.ps1

**Comment by jhoneill** [comment]
@dfinke  just be aware that those dates will fail outside the US with that date conversion.

**Comment by dfinke** [comment]
@jhoneill parsing them instead should work?

**Comment by jhoneill** [comment]
Yes - or [datetime]  
[datetime] $x uses invariant format ;  (and now I would always comment "Expects invariant/US date format") 

get-date $x and [convert]::ToDateTime() use local format. 
ParseExact  makes it clear what format is expected.

**Comment by dreasan** [comment]
@dfinke GroupDateRow is great. In relation to that parameter, would there be any chance to extend this to columns as well (e.g, GroupDateColumn)? Or can this be achieved differently?

Al lot of the time for a financial report, you would want to display 12 columns grouped by month, for example. Then the rows can be used for other criteria, making the Pivot more pleasant to look at.

**Comment by jhoneill** [comment]
@dreasan  Yes I've just tested it and it can be done. 

In Add-PivotTable there's a section of code which looks like this
```
            if ($GroupDateRow -and $PSBoundParameters.ContainsKey("GroupDatePart")) {
                $r = $pivotTable.RowFields.Where( {$_.name -eq $GroupDateRow })
                if (-not $r ) {Write-Warning -Message "Could not find a Row field named '$GroupDateRow'; no date grouping will be done."}
                else {$r.AddDateGrouping($GroupDatePart)}
            }
```

If we duplicate that and replace row with column it should work  Just create a `$GroupDateColumn` parameter and find `.ColumnFields` which match it.  

Doing manually in the debugger I got this 
<img width="381" alt="image" src="https://user-images.githubusercontent.com/16209593/178941014-03697d9e-e947-4889-9dfb-48d51728199c.png">

@dfinke I'd guess  we can do this with number intervals as well. If I get a chance I'll do it and send you a PR :-)

**Comment by jhoneill** [comment]
@dreasan  I've sent a PR for it so when Doug has a chance it should get merged in.

**Comment by dfinke** [comment]
@dreasan @jhoneill published
