### ISSUE TITLE
Import Excel -HeaderName incorrect data in output

### ISSUE THREAD

**Issue by pkarunkar** [dfinke/ImportExcel#489]
Get-Process | Export-Excel $env:USERPROFILE\Desktop\Newfolder\prox.xlsx 

Import-Excel -Path $env:USERPROFILE\Desktop\Newfolder\prox.xlsx -HeaderName 'Responding','SessionId','ExitCode','Name' | Export-Excel $env:USERPROFILE\Desktop\Newfolder\prox3.xlsx -Verbose 

Outputs incorrect data in each column under headername parameter..

**Comment by jhoneill** [comment]
When you export processes the first 5 columns are 
Name ,  SI ,  Handles , VM 
If you specify "HeaderName"  you are **renaming** those columns. to 'Responding', 'SessionId', 'ExitCode', 'Name' 
If you want to select those columns, use `Import-excel |  Select-object 
`

**Comment by pkarunkar** [comment]
thank you. I don't know what I was thinking :)
