### ISSUE TITLE
Need Help - Conditional Formatting and Delete Column

### ISSUE THREAD

**Issue by pkarunkar** [dfinke/ImportExcel#490]
Hi, I have an excel with duplicate column header. Import excel doesn't work with duplicate header. 
Hence trying to delete the duplicate column and then import excel. How do I achieve this? 

Secondly, Conditional Text Format. 
have a column with True and False Values. Need Cell Background Green and Red. 
We need better example set in help which is not enough self explanatory since I could not understand $worksheet.Names["FinishPosition"].Address .
Also, Export-Excel -ExcelPackage $excel -ConditionalTest $ct -show  ??? what does $excel contain? and what does excelpackage mean. I did google search, still doesn't make sense.
"FYI, Check the typo in example -Conditional**TEST** which should be -Conditional**Text** if I am not wrong"

Can you post me a Simple Example with Get-process | export-excel <path> -ConditionalText "" -range "C:C"? Where I believe C:C is column C per example in the code.

**Comment by jhoneill** [comment]
First part 
You can use -HeaderName for that   so 
`-headerName  firstCol , secondCol , thirdCol, RenamedDuplicate, fourthCol, Fifthcol. ` 

I'll review the help for the -ExcelPackage parameter. The Excel Package is what you get if you Open an XLSx file using the EPPlus library which does all the hard work for the module. So you can do 
`$excel  = Open-ExcelPackage <<path>>` 
or
 `$excel = export-excel -PassThru  xxxx `

If  you call `Add-ConditionalFormatting `you need to give it something to add the formatting to - that's the package

To explain `$worksheet.Names["FinishPosition"].Address ` 

$worksheet has a collection of named ranges; these live in .Names, the data here is a list of racing car results, so the $worksheet.Names["FinishPosition"] range named "finish postion" - the car's result in the race `$worksheet.Names["FinishPosition"].Address`   is the cells of that range. 
I'll try to make that example clearer and will check for typos (one more time!) 
 
To Set false red and true green 
```

$ruleForFalse = New-ConditionalText -Text $false -BackgroundColor Red   -ConditionalType Equal  -Range "C:C"
$ruleforTrue  = New-ConditionalText -Text $true  -BackgroundColor Green -ConditionalType Equal  -Range "C:C"

export-excel C:\temp\test.xlsx -ConditionalFormat $ruleForFalse,$ruleforTrue -Show

```

(That assumes your data is on sheet1 - otherwise you need to specify the worksheet name

**Comment by pkarunkar** [comment]
Great works perfect. Helps a lot in my daily reporting.

But now having issues with Setting up column Width. Couldnt get the difference between worksheet, worksheetname, workbook , why so many names :( . Not sure how/what to pass with worksheet parameter. 

Get-Process | select 'Responding','SessionId','ExitCode','Name' | Export-Excel $ENV:Userprofile\Desktop\Newfolder\prox4.xlsx 
$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\prox4.xlsx"
$ct = New-ConditionalText -Text  'TRUE' -BackgroundColor yellow -Range "A:A"
$ct2 = New-ConditionalText -Text 'chrome' -BackgroundColor Brown -Range "D:D"
Export-Excel -ExcelPackage $excel -ConditionalText $ct,$ct2 
Set-ExcelColumn -ExcelPackage $excel  -Column 4 -Width 100

**Comment by jhoneill** [comment]
Ok a workbook is an XLSx file; a workbook has 1 or more page(s) in it worksheet(s).
An Excel package is container which holds one workbook and has methods like "save". You get a workbook with Open-ExcelPackage or Export-Excel -passthru
`$excel = get-process | export-excel path.xlsx -passthru`
does the same as `get-process | export-excel path; $excel = Open-ExcelPackage $path `

You can use $ws = $Excel.workbook.worksheets["Sheet1"] and pass $ws as a worksheet (which makes sense if you are doing something else with the sheet) or pass $Excel and "Sheet1" (which makes sense in other cases) 

`Set-ExcelColumn -ExcelPackage $excel -Column 4 -Width 100` doesn't say which worksheet you want to set the column in.  Just add the worksheet name.

**Comment by pkarunkar** [comment]
Get-Process | select 'Responding','SessionId','ExitCode','Name' | Export-Excel $ENV:Userprofile\Desktop\Newfolder\prox4.xlsx 
$excel = Open-ExcelPackage "$env:userprofile\Desktop\Newfolder\prox4.xlsx"

**Set-ExcelColumn -ExcelPackage $excel  -Column 4 -Width 100 -Worksheetname "Sheet 1"**


This throw error:

The variable cannot be validated because the value 0 is not a valid value for the StartRow variable.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.3.4\Set-Column.ps1:118 char:32
+ ... (-not $StartRow)   {$startRow   = $Worksheet.Dimension.Start.Row    }
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
 
WARNING: The range pararameter you have specified also needs a worksheet parameter.
WARNING: Can set the width of a column or a range but not a String object

**Comment by jhoneill** [comment]
`"Sheet 1"`

No space in the default sheet names. Set-ExcelColumn doesn't check that the worksheet name is valid. I'll fix that at some point.

**Comment by pkarunkar** [comment]
Never Mind :)
I just tried $excel.Save() after set-ExcelColumn and it worked. Not deleting\updating the comments so that it may help others as well.

**Comment by pkarunkar** [comment]
Thank you very much once again. That is all I needed for now. You have been a great help. 
Will open new requests if I need anything else. I am closing this request. 
As everyone, I appreciate all the good work. Wish you good luck.
