### ISSUE TITLE
Table corrupts excel 

### ISSUE THREAD

**Issue by pkarunkar** [dfinke/ImportExcel#492]
Why is that I get a table corrupted, repaired records for certain table and not for others when I use the same statement.

I ll post example when I reach home. For now this is an inquiry.

**Comment by jhoneill** [comment]
The cause probably isn't using the table. I find most often if it some data causes it and some doesn't there is something in the data which excel would not let you type into a cell and it says "This is in the file, but it shouldn't be there" and you get things fixed up on load. If you can send a copy of the data somewhere else and see what is being removed the chances are it is something Excel sees as an invalid formula.

**Comment by jhoneill** [comment]
Is it possible that you have duplicate or illegal table names ?

**Comment by pkarunkar** [comment]
I am using simple words like "AMCT RY", "MW030"
There are no duplicates.
I will try few more things today and will let you know.

**Comment by pkarunkar** [comment]
OK. I broke down the code into smaller pieces.

The tables that gets repaired during launch has no Data losses comparing
with export without tables. I m happy there for now :)

Then I made it even simpler by exporting get-process with same tablename
and style. I was able to replicate the issue. I became sad here :(

Then I tried with single quote vs double quote. It didn't help.
Then removed auto size n verbose switch. Didn't help.

Finally removed numbers from tablename and it worked. Shocker brother. :)

But it wasn't number that caused issue.. It is the space in table name...
If I use "MW030" as table name it will work but not "MW 030"............



Not sure if this is a bug or just syntax that table name cannot contain
space. However, I know you will work on throw warning now.. :) thank you
very much Doug..... Keep it up.

Thanks
Sagar.

**Comment by pkarunkar** [comment]
@jhoneill :  illegal table names? I don't know if space is illegal for table name.. :) but you had the clue even without looking at the issue... Thank you once again. It is getting interesting to use more and more of these.

**Comment by jhoneill** [comment]
Excel has rules about what a table name begins with, and how long the name can be and we checked for those. I'll try to find exactly what characters are allowed and what are forbidden. In the meantime I'll add a check for spaces !

**Comment by pkarunkar** [comment]
Actually I think you do have a warning for space already. It doesn't show
up with verbose switch..

**Comment by jhoneill** [comment]
Yes, I've got the check already 
```
if ($TableName -match "\W") {
            Write-Warning -Message "At least one character in $TableName is illegal in a table name and will be replaced with '_' . "
            $TableName = $TableName -replace '\W', '_'
        }
```
The name should change and the you should get a warning unless you deliberately supress warnings. 

I'm curious how the bad table name is getting through … will investigate

**Comment by pkarunkar** [comment]
Sounds good. You want to close this issue or keep it open for
investigation?

**Comment by pkarunkar** [comment]
Also using MW030 considered it as a cell reference and that's illegal table
name too .. Awesome. OK learning :)

**Comment by jhoneill** [comment]
Ah, yes, if you go the box above cell A1 (to the left of the formula bar) you can type the name of a table or a cell in there - so things would break if table names looked like cell addresses. I've put a test in for that, and checked it in. I will add some extra tests to the test suite to ensure bad table names are trapped.

**Comment by pkarunkar** [comment]
Awesome. I actually didn't know you guys took it so seriously on every
small things reported including user errors. Nice. Hats off. I Will play
around more and bring more to the table.

Yesterday, I was measuring import csv Vs import excel and csv was much
faster, may be its designed that way. 50000 rows of data, csv took 50% less
time. Just FYI.

**Comment by jhoneill** [comment]
The support isn't always as fast, it's just when you happen to catch one of us,.

Import and Export CSV will be faster, it's compiled code and it is much simpler. (XLSx you have to start by unzipping the file, then parse XML, and then turn one object model into another). We've found ways to not slow things more than necessary, but any delimited text should always be quicker.

**Comment by pkarunkar** [comment]
Lol. You are being too honest :).
No worries. You are doing a good job with whatever limited resources you
have. And more importantly it's free for us.

Nothing comes free these days.. Thank you. I guessed it with csv but still
we need excel for daily use. I will close this issue when I get back home.

**Comment by jhoneill** [comment]
You're welcome.  It doesn't have to be free, there's always the option to send a donation.

**Comment by pkarunkar** [comment]
Well I just explored Readme file and noticed you accept donation.. That
request is hiding inside the text file of install directory.. You should
ask for it more openly.. I would love to donate for the efforts that you
are putting in and everyone should.

**Comment by pkarunkar** [comment]
Lol I just commented about that.. You kept it a secret. Not my fault :)
