### ISSUE TITLE
Use Add-ConditionalFormatting to find and update rows?

### ISSUE THREAD

**Issue by volvo64** [dfinke/ImportExcel#494]
I don't know if this is the right place to ask for support. If it's not please direct me to the correct forum.

I'd like to use this module to find a row that matches all the specified requirements. In this case, I'm pulling a filename from a directory (Approved) that has all the files that were approved overnight. The files are coded as such:

OO-1234-1115.pdf

The first section is the approval code, the second section is the customer number and the third section is the date the approval was requested (not the date the approval was added).

I've written some code that will scan through all the worksheets in the workbook and return a match if columns in the workbook all match the given file:

```
    $excel = Open-ExcelPackage $returnLog;
    foreach ($w in $excel.Workbook.Worksheets) {
    # from https://github.com/dfinke/ImportExcel/issues/324
    # this section builds an array called $rows that includes all of the rows of the specified worksheet in an array
    $Rows = foreach ($row in ($w.Dimension.Start.row    .. $w.Dimension.end.row   )) {
            $Cells = , $( foreach ($col in( $w.Dimension.Start.column .. $w.Dimension.end.column))  {
            $addr = [char](64+$col) + $row
            $w.Cells[$addr].value
        })
        $cells
        }

        # now that we have the rows in $rows let's start comparing
        $nc = 0
        foreach ($row in $Rows) {
        If (($returnCode -eq $row[0]) -and ($custNumber -eq $row[1]) -and ($fileNameReturnDate -eq $row[2])) {
            Write-host "Cell matched";
            $row;
            foreach ($cell in $($w.Cells | where Address -Match $nc)) {Set-Format -Address $cell -BackgroundColor "Green"}
                }
            Else {Write-Host "File not matched in log"}
            }
```

However my line to update the background color doesn't seem to work:

`            foreach ($cell in $($w.Cells | where Address -Match $nc)) {Set-Format -Address $cell -BackgroundColor "Green"}
`

 I also need to then go on to add another column to that row with a link to the file that was processed if it matches all of the conditions.

I feel like I'm rewriting the wheel here but I can't find a module in this project that simply compares rows against whatever I have and updates them if it all matches. Does that already exist? If not can anyone offer suggestions?

**Comment by jhoneill** [comment]
Hi. 
What you've written looks like it should work, so I'll see if I can find the flaw later. 

Yes, you are re-inventing the wheel. Doug and I are working behind the scenes to produce some worked examples - and there is likely to be an e-book which we can send you to for which there will be a modest charge (less than 1 download in every 5,000 produces a donation, so we're looking at other ways of monetizing things.) 

I do have something which is similar, and I'll share that on this thread and then write it up. 

Generally conditional formatting works when there something where you can say "Is there something in the workbook which... ". So if the you output a link where a condition is met, you can do "format the cell green if the link isn't blank". (I have variations on that) 
I also have variations on 
if column A matches "X" and column C, E, G, I, K, or M contains "Y" change the "Y" to "Z" , 
and 
if neighbouring rows have the same value in column A and C delete the later row. 
etc. 


<<Edit>> Post Script.  You do 
```
   $nc = 0

 foreach ($cell in $($w.Cells | where Address -Match $nc)) 
```

but NC never changes. You won't ever find any cells which match 0 
that the issue.  
I think I can re-write this for you but the day job is calling !

**Comment by jhoneill** [comment]
So I created a 3x3 sheet to your pattern. 
```
NN | 9876 | 1114
oo | 1234 | 1115
pp | 2345 | 1116
```

Then I ran this 
```
$returncode = "OO"
$CustNumber = "1234"
$fileNameReturnDate  = "1115"

$excel = Open-ExcelPackage .\deleteme.xlsx

foreach ($w in $excel.Workbook.Worksheets) {
    foreach ($row in ($w.Dimension.Start.Row .. $w.Dimension.End.Row)) {
        if ($w.cells[$row,1].Value -eq $returncode -and   #,1 = column A
            $w.cells[$row,2].Value -eq $CustNumber -and   #,2 = column B etc
            $w.cells[$row,3].Value -eq $fileNameReturnDate) {
                write-host "Match at row $row" 
                $w.cells[$row,4].Hyperlink = "file://C:/Users/mcp/temp.pdf"
                Set-ExcelRange -Range $w.Cells["A$row`:D$row"] -BackgroundColor Green 
            }
    }
}
Close-ExcelPackage $excel -Show
```

So I'm looking for your 3 values in the first 3 columns, adding a link and colouring the whole lot green where I get a match.  

I've been caught out using [Char]$column - if things are wider than 26 columns, and I don't build the intermediate rows collection. 

I could apply a conditional format rule to the A1:D3 which says if $D1 is not blank, make it green. As the rule works it way down, $D1 changes the row number, but as it works to the right it doesn't change the column. This would probably be fractionally faster in PowerShell and fractionally slower opening in Excel, though you'd need a huge sheet and stopwatch to tell the difference.

**Comment by volvo64** [comment]
Very nice!

I put this in today and barring a few formatting things for me to figure out this code works perfectly. Thanks very much for your help!
