### ISSUE TITLE
Generated chart from table not honoring `-SeriesHeader` parameter value

### ISSUE THREAD

**Issue by ClaudioESSilva** [dfinke/ImportExcel#495]
I'm experience a "problem" with Series names when generating a chart from a table. I have 2 series but the names are not being shown like the ones I set on `-SeriesHeader` parameter.

my data is an output from dbatools (moudule) and if I don't use `Select-Object` I can see the series' names being set right. 
If I use the `Select-Object` to get just 3 columns (total of 9) when I pipe to `Export-Excel` the series become `Series 1` `Series 1`

I can reproduce also when using `Send_SQLDataToExcel`.

Here is an code example you can run against localhost instance:
```powershell
$chartDefinition = New-ExcelChartDefinition -Title "DatabaseSize" `
    -ChartType Line `
    -XRange "DatabaseSize[Date]" `
    -YRange @("DatabaseSize[A]", "DatabaseSize[B]") `
    -SeriesHeader "A Data","B Data" 

Send-SQLDataToExcel -MsSQLserver -DataBase master -Connection localhost -SQL "SELECT '2018-01-01' AS [Date], 10 AS [A], 20 AS B
UNION ALL
SELECT '2018-01-02' AS [Date], 20 AS [A], 30 AS B" -Path Test.xlsx -AutoSize -TableName "DatabaseSize" -ExcelChartDefinition $chartDefinition
```

The output:
![image](https://user-images.githubusercontent.com/19521315/48782422-14262200-ecd6-11e8-9876-e092cfad4625.png)

Note:
If I follow your example that imports from a CSV it works great even if I use the Select-Object to get less columns

**Comment by jhoneill** [comment]
I've tested this with the latest EPPlus.Dll that I have 

```
$chartDefinition = New-ExcelChartDefinition -Title "DatabaseSize"  -ChartType Line  -XRange "A2:A3"     -YRange @("B2:B3", "C2:c3")     -SeriesHeader "A Data","B Data" 

ConvertFrom-Csv @"
Date,A,B
2018-11-1, 10,20
2018-11-8, 30,20
"@ | export-excel -Path c:\temp\wibble2.xlsx -show -ExcelChartDefinition $chartDefinition -TableName test

``` 
Ignores the Series header,  If I remove` -TableName Test ` the header is shown. As I said above the data appears correct when EPPlus re-loads it - so what is going in the XML isn't seen as correctly by Excel. 

I'll file a bug in EPPlus, but , @ClaudioESSilva  , I'm sorry to say you'll need to work around this for now.

**Comment by ClaudioESSilva** [comment]
Thanks for your analysis @jhoneill .
My current workaround is using Set-Format -Hidden for the other columns.

Which, by the way, reminds me another question:
Currently do we have a way to remove/delete columns?

**Comment by dfinke** [comment]
You need to use `-PassThru` and then `DeleteColumn`.

```powershell
$f = "$env:TEMP\test.xlsx"

rm $f -ErrorAction SilentlyContinue

$pkg = gsv | Export-Excel $f -PassThru -AutoSize

$ws=$pkg.Workbook.Worksheets["Sheet1"]
$ws.DeleteColumn(2)

Close-ExcelPackage $pkg -Show
```

**Comment by jhoneill** [comment]
Worksheets have  a .DeleteColumn() method  …. 

Ha @dfinke  beat me to it !

**Comment by ClaudioESSilva** [comment]
HAHA! Thanks to both!
I was looking on for a method on the Columns... that's why I haven't found it.
