### ISSUE TITLE
Help - Insert data into cell based on conditions

### ISSUE THREAD

**Issue by pkarunkar** [dfinke/ImportExcel#497]
Hi, 

I am trying to insert data into the selected cell based on condition matched on another cell. 
Attaching a simple excel for example. 
Conditions like: 
If TargetDate is not null and Task number is empty , then insert comment "Enter Task Number"
If TargetDate is lesser than Last Modified Date, Then insert Comment " Please reschedule"
if TargetDate is between 12/10/2017 and 12/12/2017 , then insert Comment " Take action" 

I don't know where to start. Conditional formatting targets to text. but how to do validation and get the cell index and insert data in different column, row index. 

I guess, I may be able to achieve this using com object. but checking if there is a better method here. 
[Test.xlsx](https://github.com/dfinke/ImportExcel/files/2612019/Test.xlsx)

**Comment by jhoneill** [comment]
It's fairly easy if this is going down a column. 
In one of my scripts I have 

`Set-ExcelColumn -Worksheet $ws -Heading 'ID'       -Width 15 -Value {($WorkSheet.Cells[$Row,5].value -replace '^<.*?;','')-replace ':.*$',''}`


So here I am adding a column on the right, 15 wide - the key thing is that VALUE is a ScriptBlock. 

in the Script block you can refer to $workSheet (and the properties of a work sheet) $Row (which is the row number) and  $column [number], $columnName [letter(s)], $startRow, $startColumn, $endRow, $endColumn.

So you can write a script block 
```
$sb = {
if ("" -eq $worksheet.Cells["A$Row"].value  -and "" -eq -eq $worksheet.Cells["A$Row"].value -eq $worksheet.Cells["A$Row"].value) {"Enter task Number"}  
elseif { <<whatever>>   } 
<<etc>>
}

```

(assuming target date is column A and Task number is in column B)
Then use $sb as the value in a set-ExcelColumn 

If you want comments you need to a for loop down rows and set the comment property. We'll have support for comments at some point in the future.

**Comment by pkarunkar** [comment]
Thanks. I was thinking to convert into datatable and insert it and then export it back.. you saved my time. :)

But seems something I am doing wrong.

**Comment by jhoneill** [comment]
second line sets $sb based on value of A3 
Value in the third line is a constant which is based on that and D3.  Try: 
```
$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\test.xlsx"
Set-ExcelColumn -ExcelPackage $excel -Worksheetname "Sheet1" -Value {(
  if ($null = $excel.Sheet1.Cells["A$Row"].value ) {"Enter Task Number"}
  <<etc.>>
}
```

**Comment by pkarunkar** [comment]
Not working. Something is wrong. 
Why do you reference me A$Row ?? Are you trying to tell me that I will be looping through row by incrementing $row. 
Lets make it simple. if A3 is null, then "Enter Task number" string in D3. 


$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\test.xlsx"
Set-ExcelColumn -ExcelPackage $excel -Worksheetname "Sheet1" -Value {(if ($null = $excel.Sheet1.Cells["A3"].value ) {"Enter Task Number"})}
Close-ExcelPackage -ExcelPackage $excel -Show

The statement above doesn't make any sense to me where to insert D3. 


in comments above, Yes, I need $sb set based on A3, A3 is null, and hence I want to put comments on D3 cell .. however it is choosing some random column I,J,L and fills the string to count of row. looks like a bug to me. :(

**Comment by jhoneill** [comment]
It isn't saying insert into D3. 
It is saying go right until you find an unused column.
Then from the top of that column to the end of the spreadsheet insert "Enter task number" in every cell if A3 is null, and insert nothing in every cell if A3 has contents. 

I told you to write A$Row, because the script block can see variables when it . Really I should have told you to use $workSheet, because that is one of the variables that the script block can see, but $Excel is also accessible in a higher scope so it will still work. 
  
Inside Set-Excel Column it loops through the cells to set in the column and $Row is the index of the row,  $column is the Column number and $columnName is the column as letters; $workSheet is the sheet being worked on, plus $StartRow/Column and $endRow/Column which gives you the corners of the sheet.  

So First write your script block, knowing that those variables are available.  ($sb for **S**cript **B**lock)

```
$MyScriptBlock = {
    if ("" -eq $worksheet.Cells["A$Row"].value  -and 
        "" -eq $worksheet.Cells["B$Row"].value) {"Enter task Number"}  
    elseif ( <<whatever condition>> )  { <<whatever text>>   } 
}

Set-ExcelColumn -Worksheet $ws -Value $MyScriptBlock
```

**Comment by jhoneill** [comment]
BTW, you can create your own loop and set these values directly on the worksheet object. The you have something which steps through 2,3,4 to the end checking the value of A in the current row, and setting the value of D in the current row .

**Comment by pkarunkar** [comment]
I really don't know if you understood what I am trying to do.  
$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\test.xlsx"
$worksheet = $excel.Workbook.Worksheets.Item(1)
$MyScriptBlock = {    if ("" -eq $worksheet.Cells["A3"].value) {"Enter task Number"}  }
Set-ExcelColumn -Worksheet $worksheet -Value $MyScriptBlock
Close-ExcelPackage -ExcelPackage $excel -Show


**Firstly, "" -eq $worksheet.Cells["A3"].value outputs to Falls. 
$null -eq $worksheet.Cells["A3"].value outputs to True.** 
[test.xlsx](https://github.com/dfinke/ImportExcel/files/2613314/test.xlsx)

Ok, considering I put $null and still use your snippet. I am getting the same output as I got before. 
$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\test.xlsx"
$worksheet = $excel.Workbook.Worksheets.Item(1)
$MyScriptBlock = {    if (**$null** -eq $worksheet.Cells["A3"].value) {"Enter task Number"}  }
Set-ExcelColumn -Worksheet $worksheet -Value $MyScriptBlock
Close-ExcelPackage -ExcelPackage $excel -Show

![image](https://user-images.githubusercontent.com/44933985/48982478-1e1e9b00-f0b1-11e8-9ee0-e6f8c259328e.png)



And where are you mentioning cell address of the the string "Enter Task Number" should insert to. ?
Forget multiple conditions for now for my understanding, Please.

**Comment by jhoneill** [comment]
As long as you keep putting 3 every cell  will do what cell A3 says it should do.  Try putting $row where you have 3, and see what happens.

**Comment by pkarunkar** [comment]
:) if i put $Row i get below error message.  I tried passing value $Row =3 with and without it, same error. 

```
Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\Users\PavithrasagarK\Documents\WindowsPowerShell\Modules\ImportExcel\5.4.0\Set-Column.ps1:154 char:46
+                  Write-Verbose  -Message     $cellData
+                                              ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerboseCommand
```

**Comment by pkarunkar** [comment]
```
$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\test.xlsx" -Verbose
$worksheet = $excel.Workbook.Worksheets.Item(1) 

$MyScriptBlock = {
    if ($null -eq $worksheet.Cells.item(3,1).value) {$worksheet.Cells.item(3,4).value = "Enter task Number"}  
} 

Set-ExcelColumn -Worksheet $worksheet -Value $MyScriptBlock 
Close-ExcelPackage -ExcelPackage $excel -Show -Verbose
```

Ok If I use **$worksheet.Cells.item(3,1).value** instead of **Cells["A$Row"]** its working fine. Still I get the error in Set-excel Column as mentioned above.

Output Below:

![image](https://user-images.githubusercontent.com/44933985/48985909-31def700-f0db-11e8-81bb-2389ef5c1672.png)

**Comment by pkarunkar** [comment]
Cannot bind argument to parameter 'Message' because it is null
Something wrong with binding  **Write-Verbose  -Message  $cellData** ... 
Beyond my level of knowledge though :). Or may be its my syntax issues. 

As usual, Glad I reached to a point where I could get the data inserted. I may be able to suppress this error in my script.

**Comment by jhoneill** [comment]
OK. Deep breath. 
1. One of the errors is being caused by something trying to insert null into a cell. I need to look at that. 
2. It is not writing to a random column. When Set-Column is called without a column number it writes to the first unused column. Every time you run against the same sheet it will move one column further to the right. You would be better to specify a column.
3. You want to get some data where column A will be null in some rows, but you don't know which ones.  Saying you want to put something in row 3 only works with your sample data. 
 So you either have to write a loop  
```
for x = 2 to LastRow. 
  if Cell[1, X] isnull then cell [4,x] = "Message"  
Next x 
```
or you can fill in something which says 
`Fill column 4 with ( "message" if cell[A,currentrow] on this row is null ) `

**Comment by pkarunkar** [comment]
Thank you.. I got the loop part covered. Just wanted to make sure the
simplest hard coding, work first and then build loops on top of it..

**Comment by pkarunkar** [comment]
Sorry to keep bothering you.  just FYI,  even when I specify column in Set-ExcelColumn , it still seems to be writing it to unused columns causing the excel size to grow :) However, For now, I was able to bypass the issues and workaround other options.  Below code is working for my needs. 

```
$excel = Open-ExcelPackage "$ENV:Userprofile\Desktop\Newfolder\test33.xlsx" -Verbose
$worksheet = $excel.Workbook.Worksheets["Sheet1"]
$Rows=$worksheet.Dimension.Rows

for($row = 2; $row -lt $Rows; $row++){ 
if ($null -eq $worksheet.Cells.item($row,1).value) {$worksheet.Cells.item($row,4).Value = "Enter task Number"} 
}
    
Set-Format -Range $worksheet.Cells["D2:D$Rows"]  -FontColor 'Red'
Close-ExcelPackage -ExcelPackage $excel -Show 
```

**Comment by jhoneill** [comment]
If I run 
```

del C:\temp\test2611.xlsx 

$excel = @"
Task Number,Last Modified Date
Task1, "11/11/18"
, "10/10/18" 
Task3, "10/10/18" 
Task4, "10/10/18" 
"@ | ConvertFrom-Csv | export-excel -path C:\temp\test2611.xlsx -WorksheetName sheet1  -PassThru 


Set-ExcelColumn -Worksheet $excel.sheet1 -Column 5 -Value {if (-not $worksheet.cells["A$row"].value) {"Enter task no."} else {"-"} } -FontColor Red

Close-ExcelPackage $excel -Show 
```
I get
![image](https://user-images.githubusercontent.com/16209593/49023212-9dce6780-f18e-11e8-9e35-3b005e2e334d.png)

If I close the file and run 
```
$excel = Open-ExcelPackage -path C:\temp\test2611.xlsx 
Set-ExcelColumn -Worksheet $excel.sheet1 -Column 5 -Value {if (-not $worksheet.cells["A$row"].value) {"Please Enter task no."} else {"."} } -FontColor Red
Close-ExcelPackage $excel -Show 
```
It rewrites column 5
![image](https://user-images.githubusercontent.com/16209593/49023331-e9811100-f18e-11e8-94ae-ceb4984b7792.png)

**Comment by pkarunkar** [comment]
OK. I did explore and see set-excelcolumn requires else{''} to avoid Null message at this point of time. 
Anyways, No worries on that, You already mentioned that you will look into it. 
I do not understand how you guys managed to capture $row field without me passing on the information to it. And now I understand by what you meant it's easy looking at your first comment. :) :) 

It wasn't easy for me. Lol. Once Again, Appreciate all your support. 
Will get back for the next help or issue. Closing this issue for now.

**Comment by jhoneill** [comment]
When you pass a script block it can refer to variables which will exist in the context that runs in 
So I can do 
`$MySb = {Write-host $wibble} `

Wibble doesn't exist yet, and if run  `& $sb` there is no output 

but later I can do  
```
$wibble = "Hello world" 
& $sb
```
And it outputs "Hello world". 

So... if you know what variables will exist at the time the Script block is executed, then you can refer to them. And we tell you 
```
>get-help Set-ExcelColumn -Parameter Value

-Value <Object>
    A value, formula or scriptblock to fill in. A script block can use $worksheet, $row, $column [number], $columnName [letter(s)], $startRow, $startColumn, $endRow, $endColumn.
```

**Comment by pkarunkar** [comment]
Thanks for the detailed information.. Yeah, times I see examples but I tend
to not read the descriptions.
