### ISSUE TITLE
Insert a UNC path into a cell

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#498]
I am working on a folder audit of the network and have the information collecting properly but to make the audit easier I would like to insert a hyperlink to the folder on the network.  I do not see how to do that is it possible.

I have tried the =hyperlink formula but that did not work.  I have also tried file:///<unc path>  but that did not work.  

Thanks for any help.

**Comment by dfinke** [comment]
@jhoneill - looks like a `TryCreate` may be needed. Looks pretty permissive from some simple tests. The `[System.Uri]::IsWellFormedUriString` fails.

```
$target = "c:\temp\xx.xlsx"
$tmp = ""
[System.Uri]::TryCreate($target, [System.UriKind]::Absolute, [ref] $tmp)
```

**Comment by jhoneill** [comment]
There seems to be a EPPlus issue here. 
If you create a sheet with a UNC hyperlink in it - I used "\\localhost\C$"  the hyperlink comes back as "file://localhost/c$" 
I then tried appending a cell with a hyperlink of "file://localhost/c$/temp"  - this doesn't work in Excel, which thinks the URL is file:///c:/c$/temp.   Note 3 slashes after file: 
 But the original link is now broken. 
If someone can repro this, we can open a bug with EPPlus.

**Comment by g-pearl** [comment]
This is the code that I have been trying to use.

$Test_data = @"
Servername, Path
Server1,\\server1\c$\share
Server2,\\server2\c$\share
Server3,=hyperlink("file:\\server3\c$\share")
Server4,=hyperlink("\\server4\c$\share")
"@ | ConvertFrom-Csv

$test_data | Export-Excel D:\test_share.xlsx -Show

Server 4 does create a hyperlink in the xlsx but it is not underlined (Just look like plain text).  That is why I thought it was not working.  Is there a better way to convert text to hyper link. So that it does have the proper format.

**Comment by jhoneill** [comment]
I found that to work the hyperlink needs to be \\servername    The following works and applies the formatting but only the 4th one works. 

```
del .\test_share.xlsx
$Test_data = @"
Servername, Path
localhost1,\localhost\C$\users
localhost2,\\localhost\C$\users
localhost3,file://\\localhost\C$\users
localhost4,=hyperlink("file:\localhost\C$\users")
localhost5,=hyperlink("\\localhost\C$\users")
"@ | ConvertFrom-Csv
$excel = $test_data | Export-Excel .\test_share.xlsx -PassThru


Add-ConditionalFormatting -Address "B:B" -WorkSheet $excel.workbook.worksheets["Sheet1"] -Underline -ForegroundColor Blue -RuleType BeginsWith -ConditionValue "\\" 
Close-ExcelPackage $excel -Show
```


@dfinke  if I put in 
```
 $target = "\\localhost\C$\users"
$tmp = ""
if ([System.Uri]::TryCreate($target, [System.UriKind]::Absolute, [ref] $tmp)) {$excel.workbook.worksheets["Sheet1"].Cells["B8"].Hyperlink = $tmp} 
```
before applying the formatting the link LOOKS right but hover over and the link is `file:///c:/c$/users`  which fails when clicked. But it is fine if target is a local path. 
One option would be to use this version which would make _all_ paths links, and format them as such, but then to trap "\\servername\share" and convert it to =hyperlink() to work  round the problem. 
 Thoughts  ?

**Comment by jhoneill** [comment]
I agree. TryCreate won't work with internal links like  xl://sheet!E419. We might need a wider look at file:// urls
