### ISSUE TITLE
Group Data in Pivot

### ISSUE THREAD

**Issue by astapelfeld** [dfinke/ImportExcel#499]
Hello,
is there any way to group data in a pivot table? In Excel -> http://www.exceltoxl.com/index.php?p=264&more=1&c=1&tb=1&pb=1

Thanks!

Al

**Comment by dfinke** [comment]
Thanks for the question. Currently no, need to research how/if that can be exposed.

**Comment by jhoneill** [comment]
Like this ?  
![image](https://user-images.githubusercontent.com/16209593/49433692-7c7f0400-f7aa-11e8-8155-6caea92e0bf5.png)

That's` -PivotDataToColumn`.  :-)

**Comment by dfinke** [comment]
Dude, nice! So that's what `-PivotDataToColumn` is for. I'll try and then try to do a group in date.

**Comment by dfinke** [comment]
# Potentially Cool Feature

![image](https://user-images.githubusercontent.com/67258/49483405-02c63500-f801-11e8-8ed0-2daae5423bdf.png)

@jhoneill  I thought data inference was in play for dates? Had to do the `New-Entry`, otherwise the `orderdate` got inserted as a string.

```powershell
function New-Entry {
    param($location,[datetime]$orderdate,$quantity)

    [PSCustomObject]@{
        location=$location
        orderdate=$orderdate
        quantity=$quantity        
    }
}

$pkg=$(
    New-Entry Boston 1/1/2017 100
    New-Entry Boston 1/21/2017 200
    New-Entry Boston 1/11/2017 300
    New-Entry Boston 1/9/2017 400
    New-Entry Boston 1/18/2017 500
    New-Entry Boston 2/1/2017 600
    New-Entry Boston 2/21/2017 700
    New-Entry Boston 2/11/2017 800
    New-Entry Boston 2/9/2017 900
    New-Entry Boston 2/18/2017 1000
    New-Entry Boston 1/1/2018 100
    New-Entry Boston 1/21/2018 200
    New-Entry Boston 1/11/2018 300
    New-Entry Boston 1/9/2018 400
    New-Entry Boston 1/18/2018 500
    New-Entry Boston 2/1/2018 600
    New-Entry Boston 2/21/2018 700
    New-Entry Boston 2/11/2018 800
    New-Entry Boston 2/9/2018 900
    New-Entry Boston 2/18/2018 1000
) | Export-Excel $xlf -PassThru -IncludePivotTable -PivotRows location,orderdate -PivotData @{'quantity'='sum'} -AutoSize

$pt=$pkg.Workbook.Worksheets["Sheet1PivotTable"]

$pt.PivotTables[0].RowFields[1].AddDateGrouping([OfficeOpenXml.Table.PivotTable.eDateGroupBy]'Months,Years')

Close-ExcelPackage $pkg -Show
```

**Comment by jhoneill** [comment]
No,  we insert datestime fields as numbers with formatted as "local date & time". But we don't infer dates from string fields.  

There is the usual thing with date formatting - do you write least significant first (Most countries), so  2/9/18 is Second day of September 2018.    Least significant last 2/9/18 is 18th  day of September 2002 (Japan) or least significant in the middle 2/9/18 is 9th day of February 2018 (US only). 

`[datetime]<string>` is invariant and uses US format - every computer running the code above will produce the same results - your last 3 rows, 11th, 9th and 18th of Feb come into excel as those dates and display on my machine (with Rest of world date format) as 
![image](https://user-images.githubusercontent.com/16209593/49505010-bd425000-f872-11e8-8d0a-5394cbb2e841.png)

But if that is Boston Lincolnshire, not Boston Mass, that's not how the data would be typed.  But if I export it as a CSV it uses local date format 
![image](https://user-images.githubusercontent.com/16209593/49505159-11e5cb00-f873-11e8-8d08-863c499a93ac.png)

So I read that CSV and try to process it with your script … oh dear … 

`[convert]::toDateTime(<string>) ` will use local culture, so now the script produces different things on your computer and mine, or even on the same sever depending who logs on. But it will correctly import something which was created with local date format outside the US. If US and Europe swap data we can use 
`[convert]::ToDateTime("2/9/18",[cultureinfo]::GetCultureInfo("En-uS"))` or one of the parse methods of date time, to smooth things out. 

The same problem exists on output 
```
>$d = [datetime]"09/02/18"
> $d 
02 September 2018 00:00:00
```

You'd expect `"date is $d "`  and` "date is {0} " -f $d `   To be the same , right ?  Not if the script runs in Europe 

```
>"date is $d "
date is 09/02/2018 00:00:00 

>"date is {0} " -f $d 
date is 02/09/2018 00:00:00 
```

Is `$d.toString()`    local or invariant ?   Whichever conversion one picks, it will be wrong enough of the time to be a problem. So **my view** is whatever feeds the data into Export-Excel needs to be smart about putting passing dates and times as dateTime data types. Hopefully whoever writes / runs the script knows what format the date is in and which conversion to use.

Just for amusement, I've found that that in some places I have to convert dateTime to a string in Excel e.g. to  use dates as chart Axis labels.  But when you split it like your pivot does , you _can_ use 2017 / 2018 and month names in a clustered column chart.

**Comment by jhoneill** [comment]
If I get time I'll try to add options for number grouping and date grouping.  It will be in Add-PivotTable and New-PivotTableDefinition. 
For now  @dfinke 's method is the best option.

**Comment by dfinke** [comment]
@astapelfeld This feature has been published to the gallery `Install-Module -Name ImportExcel -RequiredVersion 5.4.0`
