### ISSUE TITLE
Could not open Excel Package

### ISSUE THREAD

**Issue by ghost** [dfinke/ImportExcel#500]
I've imported an Excel file to the $ExcelFile (Import-Excel), did certain manipulations with the array, and when  I try to write back the $ExcelFile (Export-Excel) I am getting following error. I thought when you do Import-Excel, the Excel file itself remains closed. How to I write back the $ExcelFile to the same file? Replace it?

Could not open Excel Package C:\w\Test\TestCopyToMdrive.xlsx
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.4.0\Export-Excel.ps1:629 char:16
+         catch {throw "Could not open Excel Package $path"}
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not open ...pyToMdrive.xlsx:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not open Excel Package C:\w\Test\TestCopyToMdrive.xlsx

**Comment by jhoneill** [comment]
Hi  
```
$xlf="$env:temp\grouping.xlsx"
Import-Excel -Path $xlf | export-excel -Path $xlf -WorksheetName sheet2
```
Works , so something else has the file open - usually we find it is because it is loaded in Excel itself. 

If you type 
$error[0] 
after the error it will repeat the message you see, and  
$error[1] 
should show you what caused it.

**Comment by jubejube56** [comment]
Just taking a wild guess, are you setting the variable $ExcelFile with the generated output from ImportExcel with the -PassThru option? If you are, you just need to run $ExcelFile.Save() to save any changes to the excel file then I believe $ExcelFile.Dispose() to close the object. If you tried to run ExportExcel while still having an $ExcelFile object open, I believe that is where such an error occurs. Just guessing though.

**Comment by atxoxol** [comment]
Please open C:\Program Files\WindowsPowerShell\Modules\ImportExcel\5.4.20 and find ImportExcel.psm1 and add  to "#region import everything we need"
. $PSScriptRoot\Export-Excel.ps1
Safe. 

Should work after. At least it worked for me.

**Comment by juancrl** [comment]
I was facing a similar issue... but my ImportExcel.psm1 has already the line.
In my case, it is because the original Excel file was still open. Closing or killing the previous Excel process fixed the issue.
Maybe catching this error could provide a better error description (in Export-Excel.ps1 line 629)
