### ISSUE TITLE
Feature request: Pivot Table rows TextRotation

### ISSUE THREAD

**Issue by RobBarake** [dfinke/ImportExcel#502]
Feature request: Possibility to rotate the (header) row(s) of a pivot table  (-TextRotation 90)
In the Pivot table is it now not possible.

**Comment by dfinke** [comment]
@RobBarake Thanks for posting. I talked with @jhoneill and this won't work because even if apply the the formatting, when the xlsx is open, Excel overwrites it.

**Comment by jhoneill** [comment]
@RobBarake  to explain a bit further.  You can apply text rotation - or any other formatting - to the top row . When you open the file the pivot table gets drawn (the file only contains the "specification" of the pivot table, Excel itself has to draw it) and one of the table styles will be applied to its cells. You can select any of the table styles, but whichever table style it is will replace all the options on those cells If you type in one of the other cells of the top row, rotation (etc.) will apply.

**Comment by RobBarake** [comment]
@dfinke Thank you for explaining, but I don`t unsterstand it. Please give an example how I can the TextRotation in powershell for the pivottable. Then I only have to edit this in Excel to have it rotate, if I understand you right?

**Comment by RobBarake** [comment]
Sorry, I need to address it to @jhoneill

**Comment by jhoneill** [comment]
Here's some code 
```
 $excel = Convertfrom-csv @"
Location,OrderDate,quantity
Boston,1/1/2017,100
New York,1/21/2017,200
Boston,1/11/2017,300
New York,1/9/2017,400
Boston,1/18/2017,500
Boston,2/1/2017,600
New York,2/21/2017,700
New York,2/11/2017,800
"@ | Select-Object -Property @{n="OrderDate";e={[datetime]::ParseExact($_.OrderDate,"M/d/yyyy",(Get-Culture))}},
                Location, Quantity |  Export-Excel "test2.xlsx" -PassThru -AutoSize

Set-ExcelColumn -Worksheet $excel.sheet1 -Column 1 -NumberFormat 'Short Date'
$excel.sheet1.cells["1:1"].style.TextRotation = 90

$pt = Add-PivotTable -PassThru -PivotTableName "ByDate" -Address $excel.Sheet1.cells["F1"] -SourceWorkSheet $excel.Sheet1  -PivotRows location,orderdate -PivotData @{'quantity'='sum'} -PivotTableStyle Light17
Close-ExcelPackage $excel -Show

```

It produces this 
![image](https://user-images.githubusercontent.com/16209593/49702900-18b76980-fbf6-11e8-881e-203d78029b22.png)


`Set-ExcelRow    -Worksheet $excel.sheet1 -Row 1 -TextRotation 90`  will only format the data area, (columns a,b and C) so I used  `$excel.sheet1.cells["1:1"].style.TextRotation = 90` which sets all of the top row to be rotated - and after it opened in Excel I could type  in H1 and it was rotated. 
BUT 
When Excel draws the pivot table it removes all the formatting from area the pivot table covers, applies number format to data (if one is specified) and then applies a table style (Medium 6 by default, my example uses Light17). 
The module - or rather the EPPlus library we use -  just creates a .xlsx file which holds the data and the specification of the pivot table, the cells aren't formatted and there is no data in them until Excel opens the file (you can see this with the preview pane in Windows Explorer).  So whatever formatting you try to apply to Pivot table, Excel will undo it when the file is loaded for the first time (except for the   

The only way to format the text differently is to do it after Excel has drawn the pivot table.  

Hope that makes sense.

**Comment by RobBarake** [comment]
Thanks! this explains a lot! 👍

**Comment by dfinke** [comment]
# Grouping Just Works

![image](https://user-images.githubusercontent.com/67258/50056949-f069c680-0131-11e9-8729-8449155f11a3.png)


```powershell
$xlfile = "$env:temp\test2.xlsx" 
rm $xlfile -ErrorAction SilentlyContinue

$excel = Convertfrom-csv @"
Location,OrderDate,quantity
Boston,1/1/2017,100
New York,1/21/2017,200
Boston,1/11/2017,300
New York,1/9/2017,400
Boston,1/18/2017,500
Boston,2/1/2017,600
New York,2/21/2017,700
New York,2/11/2017,800
"@ | 
    Select-Object -Property @{n="OrderDate";e={[datetime]::ParseExact($_.OrderDate,"M/d/yyyy",(Get-Culture))}}, Location, Quantity |  
    Export-Excel $xlfile -PassThru -AutoSize

Set-ExcelColumn -Worksheet $excel.sheet1 -Column 1 -NumberFormat 'Short Date'

$excel.sheet1.cells["1:1"].style.TextRotation = 90

$pivotTableParams = @{
    PivotTableName = "ByDate" 
    Address = $excel.Sheet1.cells["F1"] 
    SourceWorkSheet = $excel.Sheet1  
    PivotRows = echo location orderdate
    PivotData = @{'quantity'='sum'} 
    PivotTableStyle = 'Light17'
}

Add-PivotTable @pivotTableParams

$pivotTableParams.PivotTableName="GroupByMonthDays"
$pivotTableParams.Address = $excel.Sheet1.cells["I1"] 
$pivotTableParams.GroupDateRow = "OrderDate"
$pivotTableParams.GroupDatePart = echo Year Months

Add-PivotTable @pivotTableParams


Close-ExcelPackage $excel -Show
```
