### ISSUE TITLE
Add a parameter to specify the ChartStyle

### ISSUE THREAD

**Issue by lucdekens** [dfinke/ImportExcel#503]
This would replicate the Chart Layouts on the Design tab in Excel.
Not sure if this is possible at all.

**Comment by dfinke** [comment]
Added a chart style in this branch https://github.com/dfinke/ImportExcel/commit/1ef6e66e61307ba3efe3c280295b7a5da4b1e5d5

There are some 48 styles in the enum, named Style1..48. They do change the chart look, Looks like a style # may only apply to a chart type, Needs investigation.

# Gives the chart a 3D type look

![image](https://user-images.githubusercontent.com/67258/49698760-33f28c80-fb96-11e8-8530-dced4b2d6877.png)

![image](https://user-images.githubusercontent.com/67258/49698763-4bca1080-fb96-11e8-8932-5ce8498efd6c.png)

**Comment by lucdekens** [comment]
Yes, that works, thanks Doug.

The information on these Styles is rather scarce it seems.
No enumeration info I can find.

These 2 StackOverflow threads seem to hold some more info.
https://stackoverflow.com/questions/38813522/themed-chart-styles-for-excel-charts-using-vba
https://stackoverflow.com/questions/27889579/what-does-the-number-in-the-addchart2-vba-macro-represents

**Comment by lucdekens** [comment]
This Excel holds a sample of all the styles
https://onedrive.live.com/view.aspx?resid=CC8D18389663F4C7!54425&ithint=file%2cxlsx&app=Excel&authkey=!ADUXdSANPTS1r_Q

**Comment by haydeniv** [comment]
Did this ever get added to a release?

**Comment by dfinke** [comment]
I believe so. Just thinking of the top of my head though.

**Comment by haydeniv** [comment]
I tried to use the -ChartStyle parameter in 7.8.6 and got:
New-ExcelChartDefinition : A parameter cannot be found that matches parameter name 'ChartStyle'.

**Comment by dfinke** [comment]
pls post the repro, script etc
