### ISSUE TITLE
Excel reports problem with output from export-excel

### ISSUE THREAD

**Issue by Razzbiz** [dfinke/ImportExcel#505]
I am trying to produce an excel file from the output of a compare-object between two import-excel objects like so:

$ExcelParams = @{
        Path = $OutputFile
        AutoSize = $true
        #FreezeTopRow = $true
        #TableName = 'Test'
        WorkSheetname = 'Ouput'
        #Title = 'My title'
        }
        $compareResult | Export-Excel @ExcelParams

When trying to open the file with Excel I get a prompt that 
"We found a problem with some content in '[outputfile]'. Do you want us to try and recover...."

When I dig into this repair issue I see this:
"Removed Records: Formula from /xl/worksheets/sheet1.xml part"

So it what is this and how do I fix it?
Thanks

**Comment by dfinke** [comment]
Could you post the compare-object data?  Maybe use export-cli? 

`$compare | export-cli .\compare. xml`

**Comment by Razzbiz** [comment]
Sure here it is:

`<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Management.Automation.PSCustomObject</T>
      <T>System.Object</T>
    </TN>
    <MS>
      <Db N="TRIAL_PK">2052592040</Db>
      <Db N="TRIALCOUNTRY_PK">2054476001</Db>
      <Db N="TRIALSSITE_PK">2054566722</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Changed Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2015-07-16 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">22773526</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="1">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081632832</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Changed lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="2">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081549849</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Changed lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="3">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755349</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:43</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Changed title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="4">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755315</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:42</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Changed title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="5">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755315</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:42</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2088483516</Db>
      <Nil N="TITLE" />
      <S N="LAST_NAME">Extra</S>
      <S N="FIRST_NAME">Extra</S>
      <S N="ORGANIZATION_NAME">Extra</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="6">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2052592040</Db>
      <Db N="TRIALCOUNTRY_PK">2054476001</Db>
      <Db N="TRIALSSITE_PK">2054566722</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2015-07-16 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">22773526</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="7">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081632832</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="8">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081549849</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="9">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755349</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:43</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="10">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755315</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:42</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
</Objs>`

**Comment by Razzbiz** [comment]
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Management.Automation.PSCustomObject</T>
      <T>System.Object</T>
    </TN>
    <MS>
      <Db N="TRIAL_PK">2052592040</Db>
      <Db N="TRIALCOUNTRY_PK">2054476001</Db>
      <Db N="TRIALSSITE_PK">2054566722</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Changed Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2015-07-16 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">22773526</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="1">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081632832</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Changed lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="2">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081549849</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Changed lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="3">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755349</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:43</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Changed title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="4">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755315</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:42</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Changed title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="5">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755315</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:42</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2088483516</Db>
      <Nil N="TITLE" />
      <S N="LAST_NAME">Extra</S>
      <S N="FIRST_NAME">Extra</S>
      <S N="ORGANIZATION_NAME">Extra</S>
      <S N="SideIndicator">=&gt;</S>
    </MS>
  </Obj>
  <Obj RefId="6">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2052592040</Db>
      <Db N="TRIALCOUNTRY_PK">2054476001</Db>
      <Db N="TRIALSSITE_PK">2054566722</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2015-07-16 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">22773526</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="7">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081632832</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="8">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2079004223</Db>
      <Db N="TRIALCOUNTRY_PK">2080890748</Db>
      <Db N="TRIALSSITE_PK">2081549849</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-01 00:00:00</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2086186794</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="9">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755349</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:43</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
  <Obj RefId="10">
    <TNRef RefId="0" />
    <MS>
      <Db N="TRIAL_PK">2096788195</Db>
      <Db N="TRIALCOUNTRY_PK">2097438838</Db>
      <Db N="TRIALSSITE_PK">2098755315</Db>
      <S N="ASSIGNMENT_LVL">TrialSite</S>
      <S N="ROLE">Role</S>
      <S N="INT_EXT">Personnel</S>
      <S N="START_DATA">2018-09-26 13:19:42</S>
      <Nil N="END_DATE" />
      <Db N="PERSONNELL_PK">2084449121</Db>
      <S N="TITLE">Title</S>
      <S N="LAST_NAME">Lastname</S>
      <S N="FIRST_NAME">Firstname</S>
      <S N="ORGANIZATION_NAME">Organization name</S>
      <S N="SideIndicator">&lt;=</S>
    </MS>
  </Obj>
</Objs>

**Comment by Razzbiz** [comment]
Here's a link to the xml file:
https://ufile.io/g2sjx

**Comment by dfinke** [comment]
Looks like `SideIndicator`, I suspected it because it has values like `=>` which export excel the starting `=` and then tries to insert it as a formula, which is not valid.

Here I munged the data.

```powershell
$f = "$env:TEMP\testCompare.xlsx"
rm $f -ErrorAction SilentlyContinue

Import-Clixml .\compare.xml | % {
    if($_.SideIndicator -eq '=>') {
        $_.SideIndicator = "RightSide"
    } else {
        $_.SideIndicator = "LeftSide"
    }

    $_
} | Export-Excel $f -AutoSize -Show
```

**Comment by Razzbiz** [comment]
Excellent work. Thanks for the workaround. I'll try to push it a bit further. Thanks
