### ISSUE TITLE
Errors in ImportExcel.psm1

### ISSUE THREAD

**Issue by mrutgers** [dfinke/ImportExcel#51]
Import-Module fails on the PSM1 file with:
The "=" operator is missing after a named argument.
In the functions Import-Excel and Export-MultipleExcelSheets the parameter list specifies <b>Mandatory</b> instead of <b>Mandatory=$true</b>
I am using PowerShell v2.0

**Comment by dfinke** [comment]
Thanks, I'll update that. Did you make a change and try and use it? I'm not sure if this will run on 2.0

**Comment by dfinke** [comment]
Checked in the updates https://github.com/dfinke/ImportExcel/commit/dc753b67b27efd2ec5511f20ed9459d2ddc606b4

**Comment by mrutgers** [comment]
Wow! I'm not used to instant resolution!
I just wanted to explore the Excel functionality and am not yet familiar with the GIT installs, so I downloaded the ZIP file and unzipped to a temp folder. 
I then used import-module C:\path-to-temp-folder\importexcel until there were no errors.
I made the following changes:
(1) I had to replace RootModule with ModuleToProcess in the PSD1 file
(2) I had to replace Mandatory with Mandatory=$true three times in the PSM1 file.
import-module now succeeds.
No time just now to test the update; will try later in the week. It's really great that this can work in PS v2.0 - impressive

**Comment by dfinke** [comment]
:-)

Cool. I'm not confident this will work in 2.0.

One thing you may hit is you might want to "Unblock" the zip file before you unzip it. 

Also, I checked in the updated Mandatory pieces, not sure if it was three or more.

I forgot about the ModuleToProcess. I'll dig around to see if there is a way to straddle 2.0 and later for that.

Thanks for trying this out and reporting it.

**Comment by mrutgers** [comment]
Hi Doug,
 
Re. "I'm not confident this will work in 2.0" - You are right!
In the PSD1 file, replacing RootModule with ModuleToProcess
should be harmless because the old ModuleToProcess is an alias for the new RootModule.
However 
making Import-Module succeed is all
well and good, but it is not sufficient after all to make the module itself work with
PS v2.0.
 
So far I have found two more issues:
(o) PS v2.0 does not recognise PSCustomObject.
This occurs in ImportExcel.psm1
and New-ConditionalFormattingIconSet.ps1.
(o) PS
v2.0 does not have ordered hashes, as in [ordered]@{}. This
occurs in ImportExcel.psm1
Both
of these can be avoided. The work-round will make the code somewhat less
elegant and that would be a shame. I will continue to try and make the module
work with PS v2.0 in my spare time, but it will take a while.
 
As
it stands, the Excel module definitely requires PS v3.0 or later. I will let you know
how I get on.
Thanks very much for your help so far.
Kind regards,
Maria Rutgers
----Original message----
From : notifications@github.com
Date : 06/12/2015 - 23:06 (GMTST)
To : ImportExcel@noreply.github.com
Cc : maria.rutgers@btinternet.com
Subject : Re: [ImportExcel] Errors in ImportExcel.psm1 (#51)
:-)
Cool. I'm not confident this will work in 2.0.
One thing you may hit is you might want to "Unblock" the zip file before you unzip it. 
Also, I checked in the updated Mandatory pieces, not sure if it was three or more.
I forgot about the ModuleToProcess. I'll dig around to see if there is a way to straddle 2.0 and later for that.
Thanks for trying this out and reporting it.
