### ISSUE TITLE
CodeSigning

### ISSUE THREAD

**Issue by ewhitchu** [dfinke/ImportExcel#510]
We have a large script set that is used to install our product at a customer site.
Many of our customers have set PowerShell Execution Policy to AllSigned, by Group Policy.
We cannot use this module at such sites and have had to resort to home-grown techniques, so that we can codesign our scripts and modules.

Any suggestions?

**Comment by dfinke** [comment]
Can you please say a bit more about what you are looking for?

**Comment by ewhitchu** [comment]
Will you CodeSign the ps1 and psm1 components with a valid CodeSigning Certificate?

If not can you give your users authority to CodeSign them with their Company certificates and then include them in their Packages so that they can use your Module at customer sites?

Eric

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jhoneill** [comment]
@ewhitchu It is possible to sign the code, but your client won't trust the certificate so you will be back a square one.   

Code signing is only worth anything if you know you can trust the person who signed the code. 

What does your client do with scripts they wrote themselves ? Presumably someone other than the developer reviews the code and signs it ... they will need to do that with other scripts they obtain.
One can run powershell.exe -ExecutionPolicy bypass

**Comment by ewhitchu** [comment]
While I agree with your comments, the fact remains that this set of scripts is part of installing our application into the Payroll environment, being the time and attendance collection and reporting pre-cursor to the Payrolls. At many customers It not only has to be run on servers to install server-side code, (where we can get them to remove the GPO, if it is not already removed to allow Admin-written scripts), but on Supervisor workstations scattered all over the nation. These workstations are tied down as tightly as possible by GPO. Getting the Admins to change anything on these workstations is like trying to extract hens’ teeth. The initial installation of the client-side application, might have to hit hundreds of such WorkStations.

When a policy is set to restricted or AllSigned etc by a GPO, it cannot be overwritten by running powershell -ExecutionPolicy Bypass (it also has to RunAs in our case so we can modify registry values). There are upwards of thirty scripts and a dozen Modules used in installing and maintaining the application. This has been done to allow one of our consultants to do the installation without a large amount of manual effort (there is a different topology and environment at every customer, mostly large corporates). The scripts also allow us to have the customer handle its own maintenance without having to investigate every single script ,dll and exe, except with complex breaking change. Since at most sites, the application also has to interface directly with TimeClocks and Access Control mechanisms like gates etc. at sites all over the country, the complete topology can get very complex

We chose to use PowerShell, rather than write complex installers using (say) C#, which then had to be compiled and signed anyway. We also chose not to install the ps1 files and the modules into either the PowerShell environment or the user PS environment, but include them within the controlled footprint of the application.

Anyway, we will continue as we are for now thankyou, without using your excellent module. As an aside, we also use the fabulous dbatools module for those customers with MSSQL databases. That is all code-signed.

Eric

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ewhitchu** [comment]
Hi,

Yes I agree with you as before. The Certificate really does not prove much in security terms.

When the security folk in many an organisation are so anal as to insist on code signing then unfortunately all the logical arguments cannot shift them. The organisation for which I work, feels the same way as you but went ahead anyway, and purchased a Code Signing Certificate which I am now expected to use for both PowerShell, .msi and .exe files that I develop. The organisation  in which I work, is very big in the provision of consulting services for SAP, Oracle, Microsoft, JD Edwards in Australia and New Zealand, and develops some of the most used Payroll and HR software in ANZ. It is trusted implicitly by most of its customers. The software it installs and manages as a partner (SAP etc) is always signed so it just joined in to the mainstream. There is obviously a lot of money rolling around!

Makes it difficult for most of us that just want to use what is best from the communities, whether PowerShell or C# or whatever. (I am a semi-retired consultant, previously self-employed, treated as a casual employee for convenience!)

Eric
