### ISSUE TITLE
Import-Excel isn't outputting as expected

### ISSUE THREAD

**Issue by quonic** [dfinke/ImportExcel#511]
Version: 5.4.2

So I'm trying to get all the sheet names and loop through each of those names, then output each sheet. The problem is that the first sheet outputs as expected, but the second doesn't output any data to the console. Am I doing something wrong?

```
$WorkSheetInfo = Get-ExcelSheetInfo -Path ".\Book1.xlsx"
$WorkSheetInfo.Name | ForEach-Object {
    $Data = Import-Excel -Path ".\Book1.xlsx" -WorksheetName $_
    "----- SheetName: $_ -----"
    $Data
}
"Bob:"
$Data.Bob
"Jim:"
$Data.Jim
$Data
```

Output:

```
----- SheetName: Sheet1 -----

Test Header
---- ------
   3      4
   4      4
   5      6
----- SheetName: Sheet2 -----



Bob:
1
6
8
Jim:
2
7
0





```

The funny thing is that `$Data` contains the data of the second sheet, but it only displays if I run `$Data` in the console alone.

Example:

```
PS > $Data

Bob Jim
--- ---
  1   2
  6   7
  8   0
```

Even stranger is if I call `Import-Excel` back to back it does the same thing.

```
Import-Excel -Path ".\Book1.xlsx" -WorksheetName "Sheet1"
Import-Excel -Path ".\Book1.xlsx" -WorksheetName "Sheet2"
```

Yet calling the second line alone works as expected.

**Comment by dfinke** [comment]
I believe that is the PowerShell engine. Try:

```powershell
Import-Excel -Path ".\Book1.xlsx" -WorksheetName "Sheet1" | Out-String
Import-Excel -Path ".\Book1.xlsx" -WorksheetName "Sheet2"  | Out-String
```

**Comment by quonic** [comment]
That seems to work, but that shouldn't be needed. Should it?

This also works fine:

```
Import-Excel -Path ".\Book1.xlsx" -WorksheetName "Sheet1" | Format-Table
Import-Excel -Path ".\Book1.xlsx" -WorksheetName "Sheet2"  | Format-Table
```

I just really didn't expect it to not output the data to the host. Much like many other modules, cmdlets, and functions.

**Comment by dfinke** [comment]
It's how the `PowerShell` object flow engine works. Swap the lines you see all the properties. Depends on what object is first in the pipeline.

```powershell
[pscustomobject]@{name='Jane';age=10}
[pscustomobject]@{name='Mary';age=10;date=get-date}
```

```
name age
---- ---
Jane  10
Mary  10
```

**Comment by jhoneill** [comment]
The first object to be output sets the properties to be displayed for all the items output in the same operation.  If you change the sequence  you'll see different output . There is a function "Update-FirstItemProperties" , if you pipe output through that, the first object will have missing properties added, and then all the properties will be output for all objets

**Comment by quonic** [comment]
Ah! I understand now. Y'all have been very patience and gracious in answering my questions. Thank you very much. I'll close it the issue.

Thanks!
