### ISSUE TITLE
ConvertFromExcelToSQLInsert dealing with single quotes

### ISSUE THREAD

**Issue by jotaene** [dfinke/ImportExcel#512]
Hi
Congratulations for your excellente job.
I found that ConvertFromExcelToSQLInsert.ps1 script doesn't deal well with words that contain a single quote like «I'm» because it should become «I''m» for SQL purposes.

In my local machine I turned ConvertFromExcelToSQLInsert.ps1 line 111 from ["'" + $record.$propertyName + "'"] into ["'" + (($record.$propertyName.ToString()) -replace "'","''") + "'"] and it seems to work.

Best regards

**Comment by edwardmjackson** [comment]
This commit seems to have been lost in the master branch
