### ISSUE TITLE
ToDo: Fix AutoNameRange. If there is only one property, only the first letter is used

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#515]
# Repro

```powershell
$xlfile = "$env:temp\testauto.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

ConvertFrom-Csv @"
Sold
289
713
354
727
761
626
437
810
458
374
"@  | Export-Excel $xlfile -AutoNameRange -Show
```

![image](https://user-images.githubusercontent.com/67258/50566275-b5f15380-0d05-11e9-99f9-4b7b229de024.png)

**Comment by jhoneill** [comment]
I'll take a look. It's probably getting Name[0] where name is a string, not an array.

**Comment by dfinke** [comment]
Oops, yup, fixed in https://github.com/dfinke/ImportExcel/pull/517
