### ISSUE TITLE
Remove-WorkSheet Exception calling Save

### ISSUE THREAD

**Issue by jkavanagh58** [dfinke/ImportExcel#516]
Receive the error 
Exception calling "Save" with "0" argument(s): "Error saving file C:\temp\GitActivity.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\importexcel\5.4.3\Open-ExcelPackage.ps1:122 char:31
+               else           {$ExcelPackage.Save()          }
+                               ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
 
```
If ((([System.DateTime]::Now) - (Get-Date $sheet.Name)).TotalDays -gt $reportMilestone){
        Copy-ExcelWorkSheet -SourceWorkBook $reportActive -SourceWorkSheet $sheet.Name -DestinationWorkbook $reportArchive $sheet.Name
        Remove-WorkSheet -FullName $sheet.Path -WorksheetName $sheet.Name
}
```
however if I run one loop for the copy and then another loop for the remove the results are as expected.

**Comment by dfinke** [comment]
Curious, if you run `Remove-WorkSheet -FullName $sheet.Path -WorksheetName $sheet.Name` outside the `if` without doing the `Copy-ExcelWorkSheet` does it work? Wondering if the xlsx is open.

If it fails, could you post the xlsx files?

**Comment by jkavanagh58** [comment]
I know this is sloppy but.
`ForEach ($sheet in $activeSheets){
        If ((([System.DateTime]::Now) - (Get-Date $sheet.Name)).TotalDays -gt $reportMilestone){
            Copy-ExcelWorkSheet -SourceWorkBook $reportActive -SourceWorkSheet $sheet.Name -DestinationWorkbook $reportArchive $sheet.Name
            Write-Information -MessageData "$($sheet.Name) written to Archive file" -InformationAction Continue
            #Remove-WorkSheet -FullName $sheet.Path -WorksheetName $sheet.Name
        }
        Remove-WorkSheet -FullName $sheet.Path -WorksheetName $sheet.Name
    }`

Still getting the Exception calling save...

**Comment by dfinke** [comment]
Hmm, yeah, `Remove-WorkSheet` works on the "closed" workbook. Need to think about a parameter where it takes an already opened one.

**Comment by jkavanagh58** [comment]
I added a get-excelworkbook on the active sheet and just tried to add a subject or something but still no joy yet

**Comment by jkavanagh58** [comment]
and just to be clear,,, the copy-excelworksheet is working, the fail is the remove-worksheet.

**Comment by dfinke** [comment]
Yeah, you can do the remove outside of the `foreach`?

**Comment by jkavanagh58** [comment]
Let me write something more simple because
`$workSet = @()
    ForEach ($sheet in $activeSheets){
        If ((([System.DateTime]::Now) - (Get-Date $sheet.Name)).TotalDays -gt $reportMilestone){
            #Copy-ExcelWorkSheet -SourceWorkBook $reportActive -SourceWorkSheet $sheet.Name -DestinationWorkbook $reportArchive $sheet.Name
            #Write-Information -MessageData "$($sheet.Name) written to Archive file" -InformationAction Continue
            $archiveSet = [PSCustomObject]@{
                SheetPath = $sheet.Path
                SheetName = $sheet.Name
            }
            $workset += $archiveSet
        }
    }
    Copy-ExcelWorkSheet -SourceWorkbook $reportActive -SourceWorkSheet $workSet[0].SheetName -DestinationWorkbook $reportArchive
    Remove-WorkSheet -FullName $reportActive -WorksheetName $workset[0].SheetName
`

Isn't helping.

**Comment by dfinke** [comment]
Just an update, I think the `Copy-ExcelWorkSheet` may be the issue.

If I do `Copy-ExcelWorkSheet` in the below, I get the error.

This works on my machine :)

```
$xlfile = "$env:TEMP\reports.xlsx"

rm $xlfile -ErrorAction SilentlyContinue

$sheets= echo 1.1.2019 1.2.2019 1.3.2019 1.4.2019 1.5.2019 

$sheets| % {
    "Hello World" | Export-Excel $xlfile -WorksheetName $_
}

Remove-WorkSheet -FullName $xlfile -WorksheetName '1.1.2019'
Remove-WorkSheet -FullName $xlfile -WorksheetName '1.4.2019'
```

**Comment by dfinke** [comment]
# Error 

@jhoneill : I tried a try/catch there. It doesn't catch an error. 

`Remove-WorkSheet` works as "standalone". Wondering if you have any ideas off the top of your head?

```
Exception calling "Save" with "0" argument(s): "Error saving file C:\Users\Douglas\AppData\Local\Temp\reports.xlsx"
At C:\Users\Douglas\Documents\GitHub\ImportExcel\Open-ExcelPackage.ps1:122 char:31
```

```powershell
$xlfile = "$env:TEMP\reports.xlsx"
$xlfileArchive = "$env:TEMP\reportsArchive.xlsx"

rm $xlfile -ErrorAction SilentlyContinue
rm $xlfileArchive -ErrorAction SilentlyContinue

$sheets= echo 1.1.2019 1.2.2019 1.3.2019 1.4.2019 1.5.2019 

$sheets| % {
    "Hello World" | Export-Excel $xlfile -WorksheetName $_
}

$olderSheets= echo 1.1.2019 1.4.2019

$olderSheets | % {
    Copy-ExcelWorkSheet -SourceWorkbook $xlfile -DestinationWorkbook $xlfileArchive -SourceWorkSheet $_ -DestinationWorkSheet $_
}

Remove-WorkSheet -FullName $xlfile -WorksheetName '1.1.2019'
```

**Comment by jhoneill** [comment]
Just surfacing after a difficult few days, will tell all another time  

A couple of things.
I thought I read this as opening a file to remove a worksheet, while that file is being worked on. If that's so it won't end well, and really the sheet should be deleted from the collection by other means. 
But then I went and looked at the copy operation and this jumped out. 

    ```
$Stream    = New-Object -TypeName System.IO.FileStream -ArgumentList $SourceWorkbook, 'Open', 'Read' ,'ReadWrite'
     $Package1  = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Stream
```

I'd have open-excelPackage there ... and I suspect that that stream is never closed, so the file is locked for for the rest of the powershell session.

**Comment by dfinke** [comment]
Understood, no rush on these things.

Yeah, I tried to be more aggressive in closing things, no luck, 

I'll look at the `stream` too.

**Comment by jkavanagh58** [comment]
Quick test and looks good
