### ISSUE TITLE
Help - Need to create multiple pivot tables in one sheet

### ISSUE THREAD

**Issue by pkarunkar** [dfinke/ImportExcel#519]
Is there a way to create muliple pivot in one sheet using importexcel module. ?
I need to create 4 pivots into 1 pivot sheet from 4 different worksheet datarange or dimension.address. 

I was reading the EPPlus docs and trying to do 

```
Get-Service | Export-Excel C:\Users\PavithrasagarK\Desktop\Newfolder\Service.xlsx -WorksheetName "Service"
Get-Process | Export-Excel C:\Users\PavithrasagarK\Desktop\Newfolder\Service.xlsx -WorksheetName "Process"

$excel = Open-ExcelPackage C:\Users\PavithrasagarK\Desktop\Newfolder\Service.xlsx  
$excel.Workbook.Worksheets.Add("Pivot1")
$pivot = $excel.Workbook.Worksheets["Pivot1"]
$service = $excel.Workbook.Worksheets["Service"]
$process = $excel.Workbook.Worksheets["Process"]
$dataRange = $service.Dimension.Address   
$Pivot.PivotTables.Add($Pivot.Cells["B2"], $dataRange, "table")
```

But I get an error
```
Cannot convert argument "Source", with value: "A1:P278", for "Add" to type "OfficeOpenXml.ExcelRangeBase": "Cannot convert the "A1:P278" value 
of type "System.String" to type "OfficeOpenXml.ExcelRangeBase"."
At line:1 char:1
+ $Pivot.PivotTables.Add($Pivot.Cells["A:A"], $dataRange, "table")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
```

**Comment by dfinke** [comment]
# Checkout 

https://github.com/dfinke/ImportExcel/blob/master/Examples/PivotTable/MultiplePivotTables.ps1

![image](https://user-images.githubusercontent.com/67258/50725907-7e065980-10d3-11e9-9493-a0765ea7c056.png)

**Comment by pkarunkar** [comment]
Interesting.. I was using 5.4.0.. Let me update and see.

**Comment by pkarunkar** [comment]
Seems to working only when the source are Pivot address are from the same sheet. 
When I try to address it to different sheet to add pivot, it throws error.. Not sure if I did something wrong. 
Can you check this. 

`$data = ConvertFrom-Csv @"
Region,Date,Fruit,Sold
North,1/1/2017,Pears,50
South,1/1/2017,Pears,150
East,4/1/2017,Grapes,100
West,7/1/2017,Bananas,150
South,10/1/2017,Apples,200
North,1/1/2018,Pears,100
East,4/1/2018,Grapes,200
West,7/1/2018,Bananas,300
South,10/1/2018,Apples,400
"@ | Select-Object -Property Region, @{n = "Date"; e = {[datetime]::ParseExact($_.Date, "M/d/yyyy", (Get-Culture))}}, Fruit, Sold

$xlfile = "C:\Users\PavithrasagarK\Desktop\Newfolder\multiplePivotTables.xlsx"
#Remove-Item $xlfile -ErrorAction SilentlyContinue

$excel = $data | Export-Excel $xlfile -PassThru -AutoSize -TableName FruitData

**$excel.Workbook.Worksheets.Add("Sheet2")**

$pivotTableParams = @{
    PivotTableName  = "ByRegion"
    **Address         = $excel.Sheet2.cells["F1"]**
    SourceWorkSheet = $excel.Sheet1
    PivotRows       = echo Region Fruit Date
    PivotData       = @{'sold' = 'sum'}
    PivotTableStyle = 'Light21'
    GroupDateRow    = "Date"
    GroupDatePart   = echo Years Quarters
}

$pt = Add-PivotTable @pivotTableParams -PassThru

Close-ExcelPackage $excel -Show
`

**Comment by pkarunkar** [comment]
I am using your sample code.. 
Only 2 things changed is to add Sheet2 and Change Address of PivotParam to Sheet2 
I get this below error

```
Cannot index into a null array.
At C:\Users\PavithrasagarK\Documents\WindowsPowerShell\Modules\ImportExcel\5.4.4\PivotTable.ps1:196 char:9
+     if (-not $wsPivot.PivotTables[$pivotTableName] ) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
```

**Comment by pkarunkar** [comment]
Never Mind. It was my fault. I was using the variable $pivotTableParams = @{} more then once in the script and didn't realize it...  Thank you very much. It  is working as expected.
Closing this ticket.
