### ISSUE TITLE
ConvertFrom-ExcelToSqlInsert does not escape single quotes

### ISSUE THREAD

**Issue by DerValle** [dfinke/ImportExcel#525]
When I use the CmdLet on an Excel Sheet that contains text with single quotes, I get lot's of faulty quieries.
I would expect that the CmdLet makes sure that queries work regardless of the data quality.

Best regards and happy hacking

**Comment by dfinke** [comment]
Please, could you post and example xlsx file

**Comment by beckerben** [comment]
duplicate of #512
