### ISSUE TITLE
Export-Excel only first result displayed in cell and loses format

### ISSUE THREAD

**Issue by dustyjump** [dfinke/ImportExcel#528]
I'm attempting to export RSOP data, and in the securityfilter column, I'm only getting the first result, and losing formatting. 

Code:
```
	Get-GPResultantSetOfPolicy -reporttype xml -computer $sys -path $pwd\xml\$sys.xml
	[xml]$xml = get-content .\xml\$sys.xml
	$xml.documentelement.computerresults.gpo | select @{l="ServerName";e={$xml.documentelement.computerresults.name}},name, @{label="LinkOrder";EXPRESSION={$_.link.linkorder}},securityfilter | Sort-Object @{e={$_.LinkOrder -as [int]}} | Export-Excel -worksheetname "RSOP_$timestamp" -path .\output\$environment.xlsx -append -autosize
```

And the result;
![image](https://user-images.githubusercontent.com/819630/51338105-928d0f00-1a4e-11e9-8e8c-39205d6ff60b.png)

What it should be:
![image](https://user-images.githubusercontent.com/819630/51338160-bbad9f80-1a4e-11e9-8732-b56aeefc52e7.png)

**Comment by dustyjump** [comment]
`$sys` is the computer name.

**Comment by dfinke** [comment]
You can't just close it without letting us know the solution. ;-)

**Comment by dustyjump** [comment]
Yeah, I jumped the gun on that.. my bad. I think I know the cause, but I don't know how to resolve it. Most likely not an issue with the export-excel piece.

Dusty Jump

**Comment by dustyjump** [comment]
What I've determined is that this has to do with the XML. I'm sure there's a simple fix to this, but none of my Google searches return anything helpful. The issue is that for the `<SecurityFilter>` field, some systems have none or just one item; and for others, there are multiple results.

![image](https://user-images.githubusercontent.com/819630/51399525-cbd78480-1b0b-11e9-9358-fbce73074d8e.png)

The output when there are multiple results gets encapsulated in curly brackets `{result1, result2, result3}`

So for example, my output would look like this on screen:

```
PolicyName   SecurityFilterName
PolicyName   {SecurityFilterName1, SecurityFilterName2, SecurityFilterName3}
```

When I use the Export-Excel function, it works just fine for single result responses; However, if there are multiples, it removes the curly brackets and only displays the first result.

Using the example info from just above, my results will look like this in Excel:
![image](https://user-images.githubusercontent.com/819630/51399872-9b441a80-1b0c-11e9-8585-1f858fd8716a.png)

I hope this is helpful information, and thanks for reviewing!

**Comment by dfinke** [comment]
Could you post a scrubbed XML file? I believe it's because those arrays are not unrolled in Export-Excel. My guess is you need to shape the data before exporting.

**Comment by dustyjump** [comment]
[XML-Example.zip](https://github.com/dfinke/ImportExcel/files/2776033/XML-Example.zip)

Here you go sir. Again, I appreciate your help on this!

**Comment by ili101** [comment]
You can join the "securityfilter" data to one string with `$_.securityfilter -join ', '`
``` PowerShell
[xml]$xml = get-content C:\Example.xml
$Temp = $xml.documentelement.computerresults.gpo | select @{l = "ServerName"; e = {$xml.documentelement.computerresults.name}}, name, @{label = "LinkOrder"; EXPRESSION = {$_.link.linkorder}}, @{l = "securityfilter"; e = {$_.securityfilter -join ', '}} | Sort-Object @{e = {$_.LinkOrder -as [int]}}
$Temp | Export-Excel -worksheetname "RSOP_$timestamp" -append -autosize -now
```

**Comment by dustyjump** [comment]
@ili101 That got me what I needed thanks!
