### ISSUE TITLE
How to use Add-ExcelTable?

### ISSUE THREAD

**Issue by krohneschalk** [dfinke/ImportExcel#529]
Hey,

I want to use the Add-ExcelTable function. I tried to start with the example given.

`Add-ExcelTable -Range $ws.Cells[$dataRange] -TableName $TableName`

_$WS is a worksheet, and $dataRange is a string describing a range of cells - e.g. "A1:Z10"
this range which will become a table, named $TableName_

What has to be written into the $WS varible for it to work?

**Comment by dfinke** [comment]
Take a look here, see if that helps.
https://github.com/dfinke/ImportExcel/blob/master/__tests__/First10Races.tests.ps1#L31
