### ISSUE TITLE
Support -PassThru in Export-Excel to allow greater manipulation of the built worksheet

### ISSUE THREAD

**Issue by jhoneill** [dfinke/ImportExcel#53]
Currently Export-Excel ends like this 
`$pkg.Save()`
`$pkg.Dispose()`
`if($Show) {Invoke-Item $Path}`

I have modified mine so that it ends like this 
`if ($PassThru) { return $pkg }`
`else {`
`$pkg.Save()`
`$pkg.Dispose()`
`if($Show) {Invoke-Item $Path}`
`}`
# 

This means I can do this sort of thing
`$x = $avdata |export-excel -Path "$pwd\test2.xlsx" -TitleBold -AutoSize -FreezeTopRow -AutoFilter -PassThru`

`Add-ConditionalFormatting -WorkSheet $x.Workbook.Worksheets[1] -Address "b1:b1048576" -ForeGroundColor "RED"     -RuleType ContainsText -ConditionValue "2003"`
`$x.Workbook.Worksheets[1].Cells["D1:G1048576"].Style.Numberformat.Format = [cultureinfo]::CurrentCulture.DateTimeFormat.ShortDatePattern`
`$x.Workbook.Worksheets[1].Row(1).style.font.bold = $true`
`$x.Save() ; $x.Dispose() ; start .\test2.xlsx`

(`add-conditionalFormatting` is another function I added)

**Comment by dfinke** [comment]
Thanks for the two great suggestions. If you prefer, please consider forking this and doing a PR. Otherwise I'm happy to look into adding these.

**Comment by jhoneill** [comment]
Hi Doug - I think it is best NOT to fork ... although that's more work for you . 
I'll upload my extra formatting bits as well. They just sit alongside what's there and don't need any changes. 

I've also been looking at adding a "Package" parameter to export-excel  so I can do this sort of thing
`$x = $foo | export-excel -path "myfile.xlsx" -worksheetName "Sheet1" -passThru`
`$x =  $bar | export-excel -package $x -worksheetName "Sheet2" -passthru`
`$fud | export-excel -package $x --worksheetName "Sheet3"  -show `

so the parameters change like this 
`    [CmdletBinding(DefaultParameterSetName="Path")]`
`    Param(`
`        [Parameter(Mandatory=$true,ParameterSetName="Path")]`
`        [String]$Path,`
`        [Parameter(Mandatory=$true,ParameterSetName="Package")]`
`        [OfficeOpenXml.ExcelPackage]$ExcelPackage,`

and then the start if the body turns into 
`    begin   {`
`        try {`
`            if ($ExcelPackage) {`
`               $pkg = $ExcelPackage `
`               $Path = $pkg.File `
`}  `
`            Else {`
`                $Path = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)`
`                if (Test-Path $path) { Write-Debug "File `"$Path`" already exists" }`
`                $pkg = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path`
`            }`

**Comment by dfinke** [comment]
No problem, this is great. PRs are cleaner only because I might miss something.

Some of things you have I been holding in the wings, they're not exactly the same and may break you.

Thanks again, hopefully I can get these in soon.

Currently I'm participating in the hack week for the Visual Studio Code PowerShell Editor Services https://github.com/PowerShell/PowerShellEditorServices

**Comment by josheinstein** [comment]
Typically, the PassThru parameter would write out the objects that are piped into the command after doing something with it. (See Out-GridView for example.)

It seems like it would be unintuitive to have the command output the package itself. Just my two cents. I'm somewhat of a nazi when it comes to consistency in PowerShell.

**Comment by dfinke** [comment]
Too funny, I'm sitting here working on some things for this module and you respond :-)

I like consistency too. 

I like the passthru concept. So would a different named switch be better?

**Comment by josheinstein** [comment]
LOL I'm at a Christmas play and my kid was first so I am burning time browsing Github. What can I say, I'm a horrible person.  :)

I definitely like the idea of being able to echo the input back out the pipeline, as it would allow you to export to multiple formats in one go. Unfortunately I don't have a better suggestion for a parameter name to output the package, though I do see how it would be useful. Maybe someone on the PS team would know if there's any precedent?

**Comment by dfinke** [comment]
You are horrible :-).  I used to bring my laptop to my daughters baseball, soccer and basketball games.

We agree on being able to pass the object back to the pipeline.

I'll investigate a better name.

Thanks

**Comment by jhoneill** [comment]
Hey Both. 
The precedents are limited, but if you look at something like New-alias or Set-Variable or some of the AD commands passthru returns a newly created object rather than the literal sense of the object which came in goes out again to the next part of the pipeline. 
Generally it is used for "You don't normally output something , but this time I want output", which was my thinking.  I'm not especially hung up on it being passthru - using "outVariable" instead could be better - as I have it now, you can run it with the switch and not assign the result to a variable so file is opened, not saved and without the ExcelPackage object there is no way to save it. But OutVariable normally captures something which would be output anyway ...

**Comment by dfinke** [comment]
Yes, the concept is dead on. It's good to hash out the name for consistency. Add-Member has a passthru parameter too. Take an object, hang some more properties on it and then emit it back to the pipeline. 

That's a +1 for passthru.

**Comment by chreestopher** [comment]
what about -outputObject (or something similar)? 

that would clearly indicate that it is not just passing the input.
