### ISSUE TITLE
Unwanted Backgroud Colorchange 

### ISSUE THREAD

**Issue by tom2win** [dfinke/ImportExcel#532]
Hi 

After Importing a Big (10MB) Excel-File with (Open-ExcelPackage) and then direct Save it with Close ExcelPackage all the Data are correct, but in many Columns the complete Column has **some green Background Color.** I don't know why.
Can anybody help me?

Thanks a Lot
Tom

**Comment by pkarunkar** [comment]
Are you overwriting the data to the file which already had some texts with green backgrounds?
overwriting the data in the same sheet does not clear out the formatting of the cells. 

You probably need to use -clearsheet while exporting... 

Export-excel -path -clearsheet

**Comment by tom2win** [comment]
No, i just load/open it and then close without any changes. Then there are the green cells.

I try to use clearsheet and give you a Feedback. I hope the other Data are not touched with this parameter.

Thanks already.

**Comment by pkarunkar** [comment]
Clearsheet clears the data from the sheet.. If you are just opening and closing without changes, then it could be something else. Can you please attach the excel?

**Comment by tom2win** [comment]
Maybe you missunderstand me

**To Open** > $Excel =Open-ExcelPackage -Path <path-to-file>
**To Save** > Close-ExcelPackage $Excel

If this simple try don't work finde, i don't have to write a full script around.

I can not upload the Excel because of confidelity.

**Comment by pkarunkar** [comment]
We do not see any such issues. Could be something else in your excel file
that's causing it.

Did you try with a different excel sheet?
Is it happening for all excel in your machine?
What happens when you manually open and close the files?

**Comment by tom2win** [comment]
Did you try with a different excel sheet? 
>> If i try with small Excel Sheets, no problem. It works

Is it happening for all excel in your machine? 
>> No, and i tried on different machines. With the Big Excel (12MB) is a problem, with small files no problem.

What happens when you manually open and close the files?
When i manually open it with Excel and Save or SaveAs, there is no Problem.

**Comment by pkarunkar** [comment]
I couldn't replicate the issue...
Tried making a big excel by manually copying the data multiple times.
Open n close, nothing changes.

May be someone else have different ideas..
