### ISSUE TITLE
import-module

### ISSUE THREAD

**Issue by joe161314** [dfinke/ImportExcel#535]
hi, 

im having issues importing the module on a vm that isnt connected to the internet. i have copied the files to the powershell folder but when running Import-Module C:\Users\joe\Documents\WindowsPowerShell\Modules\ImportExcel

its returning 
Import-Module : The specified module 
'C:\Users\joe\Documents\WindowsPowerShell\Modules\ImportExcel' was not loaded because no valid 
module file was found in any module directory

**Comment by pkarunkar** [comment]
Can you check if ImportExcel.psm1 file is present. 
Is all the files present as per Github file lists. 
I would also try to run the command with -verbose and see what happens.

**Comment by robesmithjr** [comment]
May need to unblock the files if downloaded from the web and manually copied …

Rob
