### ISSUE TITLE
Import-Excel

### ISSUE THREAD

**Issue by quong** [dfinke/ImportExcel#536]
I have an excel sheet that looks something like this:

FirstName, LastName, NickName, PhoneNumber, MobileNumber (Headers)
Bob, Doe, bdoe (Uses formula to trim & concat FirstName & LastName), empty, empty
Jane, Doe, jdoe, empty, empty
empty,empty,(contains formula but because FirstName & LastName is empty; this is blank), empty, empty

I would like to import this excel sheet, but I only want to import rows 1 and 2 in its entirety even though the phone number, and mobile phone number is empty/null and ignore row 3 as it has no data.

Is this something I can currently do and if so, how would I go about doing this?

**Comment by pkarunkar** [comment]
Not Clear on the requirement. See if this may help. 
$data = ConvertFrom-Csv @"
FirstName, LastName, NickName, PhoneNumber, MobileNumber
Bob, Doe, bdoe, $null, $null
Jane, Doe, jdoe,$null, $null
$null, $null, $null, $null, $null

"@ | Select-Object -Property FirstName, LastName, NickName, PhoneNumber, MobileNumber

$xlfile = "C:\Users\PavithrasagarK\Desktop\Newfolder\TestNull.xlsx"
$data | Export-Excel $xlfile -AutoSize -Show

**Comment by quong** [comment]
Essentially,

How to Import-Excel but have it ignore rows/columns that contain formulas so the output does not display null/empty characters?

**Comment by pkarunkar** [comment]
Check This.. Below example is csv.. Let me check with excel

$data = ConvertFrom-Csv @"
FirstName, LastName, NickName, PhoneNumber, MobileNumber
Bob, Doe, bdoe,,
Jane, Doe, jdoe,,
,,,,

"@ | Select-Object -Property FirstName, LastName, NickName, PhoneNumber, MobileNumber 

$data | Where-Object { $_.PSObject.Properties.Value -ne ''}

**Comment by pkarunkar** [comment]
Same works. 

$xlfile = "C:\Users\PavithrasagarK\Desktop\Newfolder\TestNull.xlsx"
Import-Excel $xlfile |  Where-Object { $_.PSObject.Properties.Value -ne ''}

**Comment by pkarunkar** [comment]
@dfinke  @jhoneill 
I think this would be nice if we can add a parameter -ignoreEmptyRow :)
Every day even I work with excels containing empty rows... 
I do not know if it is worth it.. Decision is yours.

**Comment by dfinke** [comment]
Want to try and implement that and do a PR?

**Comment by pkarunkar** [comment]
@dfinke :  Are you asking me to? :) Lol. I don't think I have the level of expertise to do so. 
PR you mean peer review?

**Comment by dfinke** [comment]
Give it a try, you can't break anything. PR is a pull request, and through that a review is done before merging it to the rest of the code. It'll give you the opportunity to learn a bit about `git`, writing tests and the code base.

Think about it, no pressure. This feature isn't too big.

**Comment by pkarunkar** [comment]
hmmmm... Ok , I will try to have an extra protein shake tomorrow and give it a shot... 
And Yes, I would like to learn and help.. but worried I may end up troubling you more . hope @jhoneill  doesnt complete it in 2 minutes before I wake up tomorrow. Lol.

**Comment by pkarunkar** [comment]
@dfinke I dont know if I am doing things right. 
but from my local machine I added a switch param and inserted the code to ImportExcel.psm1 file.  
While creating pull request , ended up creating a fork to my name mapped to your master branch. 
Then uploaded the changed file and created a pull request from my repository. 

https://github.com/pkarunkar/ImportExcel/pull/1/files

I have no clue what I did. Lol. 
Please check and educate me. Thank you.

**Comment by dfinke** [comment]
@pkarunkar commented on the fork you did

**Comment by quong** [comment]
@pkarunkar 

Still getting these blank fields.

$xlsheet = ".\UserCreate1.xlsm"
$ADUsers = Import-Excel -Path $xlsheet -WorksheetName "Account Creation" | Where-Object { $_.PSObject.Properties.Value -ne ''}


FirstName      : Raymond
LastName       : Chu1
JobTitle       : Testing123
Property       : Test
Department     : Testing123
Password       : LofE9951+
OfficePhone    : 
MobilePhone    : 
OU             : OU=Test,OU=TestOU,DC=Testing,DC=local
Groups         : 
HomeDir        : TestSVR1
UserToCopyFrom : 
CopyGroups     : 

FirstName      : Raymond
LastName       : Chew
JobTitle       : Testing 123
Property       : Test
Department     : Testing123
Password       : NlxF7673*
OfficePhone    : 
MobilePhone    : 
OU             : OU=Test,OU=TestOU,DC=Testing,DC=local
Groups         : 
HomeDir        : TestSVR1
UserToCopyFrom : 
CopyGroups     : 

FirstName      : 
LastName       : 
JobTitle       : 
Property       : 
Department     : 
Password       : 
OfficePhone    : 
MobilePhone    : 
OU             : 
Groups         : 
HomeDir        : 
UserToCopyFrom : 
CopyGroups     : 

My going theory still thinks its because of my cells that contain formulas (could be wrong though)

**Comment by quong** [comment]
Thought it may have been the Data Validation drop down lists, but its not either.

**Comment by quong** [comment]
Using -DataOnly works but removes things like OfficePhone & MobilePhone from rows 1 & 2 from my above example

**Comment by pkarunkar** [comment]
OK that was strange. It didn't work for me when I tried to replicate with
your data.. However -ne $null fixes it.

Somewhere the excel sees data blank '' vs Null $null

. Try with $null and let me know.

**Comment by jhoneill** [comment]
We have a -DataOnly switch, this looks at the value of all the cells and ask "do any rows or columns only contain Null". An empty string is not null, and the formulas return empty strings. You can change the logic at line 386 in importExcel.psm1 and see if it works better for your use case. 

What you're describing is as designed, a formula which results in an empty string is treated as containing something. And if there is nothing in the phone column for any user, it will be trimmed off. 

That test on all the property values ... is deeply unreliable. 
$_.PSObject.Properties.Value 

Gives you an array of values, one for each property of $_  With an array. -eq  / -lt / -ne (etc) and -match -like return the objects in the array which match. 
-ne ''  will return all the nulls. -ne $null will return all the empty strings. (A nightmare to debug you have to count them and do all sorts). 
A single null is boolean false. So is a single empty string, but multiples are true (_because any multi-member array evaluates to true, regardless of what is in the members_). 
So  [bool](@('' , $null , $null , '') -ne '') is true but 
[bool](@('' , $null , '' , '') -ne '')  is false 
 
The person who said two wrongs don't make a right never tried 
[bool]@($false,$false)

(see https://twitter.com/jamesoneill/status/1085910297775357952 for a thread on shrodingers argument list). 

I would try 
($_.PSObject.Properties.Value -match '.').count 
That says if is not text, make it text. Then if it contains any character at all, it is part of the result set  
(@('' , $null , 0 , '') -match '.')  returns 0 
If you just get one zero back , it's not an array and 0 is boolean false. So that won't work. Hence the need to put the count on it.

**Comment by pkarunkar** [comment]
I may sound funny. But wondering if I use
($_. PSObject.Properties.Value - ne '') -or ($_.PSObject.Properties.Value -
ne $null)


If should throw true for both cases isn't it.?

**Comment by jhoneill** [comment]
It would return true 
if the values were   both halves return true. But you want to _not_ select that row. 
(@('', $null,$null,'')  - ne '') is true but we want it to be false 
(@('', $null,$null,'')  - ne $null) is true as well , and we'd like _that_ to be false. 

to the first one (@('', $null,$null,'')  - ne '') is the same as @('','123','Abc','')
if you are going to do that you need 
(@('', $null,$null,'')  - ne '') -ne $null)

**Comment by dfinke** [comment]
I didn't catch that an array was being operated on `($_.PSObject.Properties.Value -ne $null)`

Possibly comparing the count of matches could work.

```powershell
(@('', $null,$null,'') -ne '').Count
(@('', $null,$null,'') -ne '').Count
(@('', $null,$null,'') -ne $null).Count
(@('', $null,$null,'') -ne '').Count
(@('','123','Abc','') -ne '').Count

(@($null, $null,$null,$null) -ne '').Count -eq 0
(@($null, $null,$null,$null) -ne $null).Count -eq 0
```

```
2
2
2
2
2
False
True
```

**Comment by pkarunkar** [comment]
```
$a = @('', '','','')
$b = @('', $null,$null,'')
$c = @($null,$null,$null,$null)
$d = @('', $null,$null,'')
$e = @('','123','abc','')
($a.psobject.Properties.value -ne '').Count
($a.psobject.Properties.value -ne $null).Count
($b.psobject.Properties.value -ne '').Count
($b.psobject.Properties.value -ne $null).Count
($c.psobject.Properties.value -ne '').Count
($c.psobject.Properties.value -ne $null).Count
($d.psobject.Properties.value -ne '').Count
($d.psobject.Properties.value -ne $null).Count
($e.psobject.Properties.value -ne '').Count
($e.psobject.Properties.value -ne $null).Count
```
```
5
11
7
9
9
7
7
9
7
11
```

Doesn't seem to work.

**Comment by pkarunkar** [comment]
```
$a = @('', '','','')
$b = @('', $null,$null,'')
$c = @($null,$null,$null,$null)
$d = @('','123','abc','')
($a.psobject.Properties.value -ne '').Count
($a.psobject.Properties.value -ne $null).Count
($b.psobject.Properties.value -ne '').Count
($b.psobject.Properties.value -ne $null).Count
($c.psobject.Properties.value -ne '').Count
($c.psobject.Properties.value -ne $null).Count
($d.psobject.Properties.value -ne '').Count
($d.psobject.Properties.value -ne $null).Count
```
```
5
11
7
9
9
7
7
11
```

Doesnt seem to work.

**Comment by dfinke** [comment]
```powershell
$a.psobject.Properties
```

```
ReferencedMemberName : Length
ConversionType       : 
MemberType           : AliasProperty
TypeNameOfValue      : System.Int32
IsSettable           : False
IsGettable           : True
Value                : 4
Name                 : Count
IsInstance           : False

MemberType      : Property
Value           : 4
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Int32
Name            : Length
IsInstance      : True

MemberType      : Property
Value           : 4
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Int64
Name            : LongLength
IsInstance      : True

MemberType      : Property
Value           : 1
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Int32
Name            : Rank
IsInstance      : True

MemberType      : Property
Value           : {, , , }
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Object
Name            : SyncRoot
IsInstance      : True

MemberType      : Property
Value           : False
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Boolean
Name            : IsReadOnly
IsInstance      : True

MemberType      : Property
Value           : True
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Boolean
Name            : IsFixedSize
IsInstance      : True

MemberType      : Property
Value           : False
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Boolean
Name            : IsSynchronized
IsInstance      : True

```

**Comment by ili101** [comment]
are you guys testing arrays or PSCustomObjects?
``` Powershell
$Tests = @(
    {''}
    {$null}
    {0}
    {'abc'}
    {@('', '', '', '')}
    {@('', $null, $null, '')}
    {@($null, $null, $null, $null)}
    {@('', '123', 'abc', '')}
    {[PSCustomObject]@{Name1 = '' ; Name2 = $null ; Name3 = 0}}
    {[PSCustomObject]@{Name1 = '' ; Name2 = $null ; Name3 = ''}}
)

foreach ($Test in $Tests)
{
    # Get the test to Object to $TestObj
    $TestObj = . $Test

    # If we are testing PSCustomObject we need to copy it's Values into an array
    if ($TestObj -is [PSCustomObject])
    {
        $TestObj = $TestObj.PSObject.Properties.Value
    }

    # -match will return an array with only the matching values, if it's Count is 0 nothing found
    if ((@($TestObj) -match '.').Count)
    {
        'Not Empty: ' + $Test.ToString()
    }
    else
    {
        'Empty:     ' + $Test.ToString()
    }
}
```
```
Empty:     ''
Empty:     $null
Not Empty: 0
Not Empty: 'abc'
Empty:     @('', '', '', '')
Empty:     @('', $null, $null, '')
Empty:     @($null, $null, $null, $null)
Not Empty: @('', '123', 'abc', '')
Not Empty: [PSCustomObject]@{Name1 = '' ; Name2 = $null ; Name3 = 0}
Empty:     [PSCustomObject]@{Name1 = '' ; Name2 = $null ; Name3 = ''}
```

**Comment by pkarunkar** [comment]
@dfinke  This is beyond my skill to achieve it inside module. So, I give up now :) 
I will leave it open to others or if you think, this needs to be closed.
