### ISSUE TITLE
Add-Format

### ISSUE THREAD

**Issue by jhoneill** [dfinke/ImportExcel#54]
[Add-Format.txt](https://github.com/dfinke/ImportExcel/files/65159/Add-Format.txt)

I've added 4 functions to the module 
Add-ConditionalFormatting 
Set-Format
Set-ColumnWidth 
Set-RowHeight

So I can have code like this 
`$excel =  $invData | [snip] |  Export-Excel -WorksheetName "Server Anti-Virus" -AutoSize -FreezeTopRow -AutoFilter -PassThru -Path $FilePath`
`$wb = $excel.Workbook.Worksheets | Where-Object -Property name -EQ  "Server Anti-Virus" `
`Set-format $wb.Column(7), $wb.Column(8), $wb.Column(12) -HorizontalAlignment Right`
`Set-format $wb.Row(1) -HorizontalAlignment Left -Bold` 
`$wb.Cells["D1:K1048576"].Style.Numberformat.Format = [cultureinfo]::CurrentCulture.DateTimeFormat.ShortDatePattern`
`Add-ConditionalFormatting -WorkSheet $wb -Address "c1:c1048576" -BackGroundColor "Yellow"  -RuleType Expression   -ConditionValue 'AND(FIND("2008 R2",$B1),$C1<>"Service Pack 1")' `
`$excel.Save() ; $excel.Dispose() ; `

My guess is that other people may be looking at something similar, but just adding a contribution to the pot.

**Comment by dfinke** [comment]
That's great. Thanks! I have conditional formatting setup in some new pieces that I'm getting ready. I think having yours so it can be applied after the Export is a good thing.
