### ISSUE TITLE
Sorting imported

### ISSUE THREAD

**Issue by Razzbiz** [dfinke/ImportExcel#540]
Is there a way to sort imported excel sheets by column?

**Comment by pkarunkar** [comment]
Why not use sort-object after import?

**Comment by Razzbiz** [comment]
Well sounds like a good idea if it works. How would you go about doing that with the imported excel data?

**Comment by ili101** [comment]
``` powershell
Import-Excel -Path Book1.xlsx | Sort-Object -Property 'ColumnName'
```
