### ISSUE TITLE
sum a column

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#541]

**Comment by pkarunkar** [comment]
Just typing on the fly.

$xl = open-excelpackage test.xlsx
$xl.workbook.worksheet['sheet1'].cells['$targetcell' ].Formula
='Sum($startcol$row:$endcol$row)'

Close-exelpackage $xl - show

I guess this would be a good starting point.

**Comment by g-pearl** [comment]
Sorry I was in the middle of writing a request when machine crashed.  It looks like it opened a ticket without completing this.  Thanks
