### ISSUE TITLE
How do i merge a patch that I made to Charting.ps1?

### ISSUE THREAD

**Issue by robesmithjr** [dfinke/ImportExcel#543]
Hi,

II made a few minor changes to Charting.ps1, namely, the ability to export a static chart to an existing excel file and worksheet.  How can I merge this with Doug's master (I am not that knowledgeable at GitHub forks).

Here is the modified code:

function DoChart {
    param(
        $targetData,
        $title,
        $xlfile,
        $worksheet,
        [OfficeOpenXml.Drawing.Chart.eChartType]$ChartType,
        [Switch]$NoLegend,
        [Switch]$ShowCategory,
        [Switch]$ShowPercent
     )

     if($targetData[0] -is [System.ValueType]) {
         $chart = New-ExcelChartDefinition -YRange "A1:A$($targetData.count)" -Title $title -ChartType $ChartType
     } else {
         $xyRange = Get-XYRange $targetData

         $X = $xyRange.XRange.ExcelColumn
         $XRange = "{0}2:{0}{1}" -f $X,($targetData.count+1)

         $Y = $xyRange.YRange.ExcelColumn
         $YRange = "{0}2:{0}{1}" -f $Y,($targetData.count+1)

         $chart = New-ExcelChartDefinition -XRange $xRange -YRange $yRange -Title $title -ChartType $ChartType `
            -NoLegend:$NoLegend -ShowCategory:$ShowCategory -ShowPercent:$ShowPercent
     }

     if ($xlfile -eq $null) {$xlFile = [System.IO.Path]::GetTempFileName() -replace "tmp","xlsx"
     
                          $targetData | Export-Excel $xlFile -ExcelChartDefinition $chart -worksheetname $worksheet -Show -AutoSize                        
                         }
                         Else {
                                $targetData | Export-Excel $xlFile  -WorksheetName $worksheet -ExcelChartDefinition $chart -AutoSize 

                              }
     
     
}

function BarChart {
    param(
        [Parameter(ValueFromPipeline=$true)]
        $targetData,
        $title,
        $xlfile,
        $worksheet,
        [OfficeOpenXml.Drawing.Chart.eChartType]$ChartType="BarStacked",
        [Switch]$NoLegend,
        [Switch]$ShowCategory,
        [Switch]$ShowPercent
    )

    Begin   { $data = @() }
    Process { $data += $targetData}

    End {
        DoChart $data $title $xlfile $worksheet  -ChartType $ChartType `
            -NoLegend:$NoLegend -ShowCategory:$ShowCategory -ShowPercent:$ShowPercent
    }
}

function PieChart {
    param(
        [Parameter(ValueFromPipeline=$true)]
        $targetData,
        $title,
        $xlfile,
        $worksheet,
        [OfficeOpenXml.Drawing.Chart.eChartType]$ChartType="PieExploded3D",
        [Switch]$NoLegend,
        [Switch]$ShowCategory,
        [Switch]$ShowPercent
    )

    Begin   { $data = @() }
    Process { $data += $targetData}

    End {
        DoChart $data $title $xlfile $worksheet -ChartType $ChartType `
            -NoLegend:$NoLegend -ShowCategory:$ShowCategory -ShowPercent:$ShowPercent
    }
 }

function LineChart {
    param(
        [Parameter(ValueFromPipeline=$true)]
        $targetData,
        $title,
        $xlfile,
        $worksheet,
        [OfficeOpenXml.Drawing.Chart.eChartType]$ChartType="Line",
        [Switch]$NoLegend,
        [Switch]$ShowCategory,
        [Switch]$ShowPercent
    )

    Begin   { $data = @() }
    Process { $data += $targetData}

    End {
        DoChart $data $title $xlfile $worksheet -ChartType $ChartType `
            -NoLegend:$NoLegend -ShowCategory:$ShowCategory -ShowPercent:$ShowPercent
    }
}

function ColumnChart {
    param(
        [Parameter(ValueFromPipeline=$true)]
        $targetData,
        $title,
        $xlfile,
        $worksheet,
        [OfficeOpenXml.Drawing.Chart.eChartType]$ChartType="ColumnStacked",
        [Switch]$NoLegend,
        [Switch]$ShowCategory,
        [Switch]$ShowPercent
    )

    Begin   { $data = @() }
    Process { $data += $targetData}

    End {
        DoChart $data $title $xlfile $worksheet -ChartType $ChartType `
            -NoLegend:$NoLegend -ShowCategory:$ShowCategory -ShowPercent:$ShowPercent
    }
}

**Comment by dfinke** [comment]
Thanks for churning through all of that!

To increase the chances of getting this merged, here are the steps. Otherwise I need to do all of this :-)

Doing a pull request (PR) makes this easier. 

* Fork `ImportExcel` - Top right button, to your login
* Git clone that repo to you machine
* Make the changes
* Commit it back to your repo
* Last step, in the GitHub UI on the repo you just committed to, should be a `New Pull Request` button

Two things

Make sure all the tests run on you local box before and after you make your changes. 
Add tests to make sure your changes do what you expect.

**Comment by robesmithjr** [comment]
Doug,

Ok, I followed your instructions.  If I get some free time, I can try to add more options.

**Comment by dfinke** [comment]
Ok. I'll need to go through this first when I get time. Let's see how this shakes out first
