### ISSUE TITLE
Import-Module

### ISSUE THREAD

**Issue by swoonhusker1** [dfinke/ImportExcel#546]
I copied the module to my C:\Program Files\WindowsPowerShell\Modules\ImportExcel

Here is the error I get when trying to import module-
![image](https://user-images.githubusercontent.com/47569583/52650436-dfc69a00-2eaf-11e9-8c9e-e79df4931434.png)

I have powershell running as administrator and I have imported modules that I have downloaded in the past. Our company execution policy is remote-signed (I can't change it) and the message says this module is not digitally signed. Please help.

**Comment by robesmithjr** [comment]
Hi, my ExecutionPolicy is set to RemoteSigned, I do not see an error when importing the module.

If you downloaded the module from the web, did you "unblock" the files?  If your company allows, installing via install-module importexcel is very convenient.

Rob

**Comment by swoonhusker1** [comment]
Wow, I feel really stupid. I unblocked the file and unzipped again. Now I'm able to import the Module. Thank You!
