### ISSUE TITLE
Unable to read a cell when this one is a list

### ISSUE THREAD

**Issue by ccoupeau** [dfinke/ImportExcel#547]
Hi, 
I have some problems with command "Get-CellValue". 
I cant extract value text in the cell when cell content is a list :( as you can see in attached :(. 

Thanks for your help,
![image](https://user-images.githubusercontent.com/20579884/52847525-c0787880-310c-11e9-95e5-dae5e0e9d160.png)
![image](https://user-images.githubusercontent.com/20579884/52847549-cbcba400-310c-11e9-9419-44048ac0adcb.png)

**Comment by dfinke** [comment]
Please could you post a sample Excel file and Powershell script

**Comment by robert-i** [comment]
Looks like this module has been confused with PSExcel which is over here.. https://github.com/RamblingCookieMonster/PSExcel/

**Comment by robert-i** [comment]
Reading cell range that has data validation from list with this module works fine:

![image](https://user-images.githubusercontent.com/16002013/52978342-2432c800-33d1-11e9-9348-d6c44e48bb23.png)

```
$excel=Open-ExcelPackage ..\Temp\Output2.xlsx
$ws=$excel.Workbook.Worksheets[2]
$r=$ws.Cells["d2:d2"]
$r
```
![image](https://user-images.githubusercontent.com/16002013/52978442-9d321f80-33d1-11e9-9438-d3b00c02a59a.png)

**Comment by ccoupeau** [comment]
Oh nice,
Thanks you Robert-i !
Just a wrong command module used so :)
