### ISSUE TITLE
Set-ExcelRange Example

### ISSUE THREAD

**Issue by swoonhusker1** [dfinke/ImportExcel#548]
I've looked at the help examples for set-excel range, but haven't really found what I'm looking for. 

I would like to edit individual values of an excel file. Is there a place where I can see someone import, edit a cell's value, and export the file? Here is what I envision and I'm sorry if this doesn't make any sense-

`$ws = Import-Excel "C:\Temp\Test\filethatneedsedited.xlsx"

#I would like to change the value of a cell
Set-ExcelRange -Range $ws.Cells["A1"]  -value "Test"

$ws | Export-excel "C:\someotherlocation\editedfile.xlsx"`

**Comment by dfinke** [comment]
`Set-ExcelRange`

https://github.com/dfinke/ImportExcel/blob/master/Examples/ConditionalFormatting/Databar.ps1

`Open-ExcelPackage` `Close-ExcelPackage`
https://github.com/dfinke/ImportExcel/blob/master/Examples/CustomReporting/CustomReport.ps1

**Comment by pkarunkar** [comment]
Once you import the data to memory, then its the data in the memory that you are dealing with.. If there are unique identifiers, then you can use where-object to filter out the data and replace the value. 

If you want to edit it directly on the excel which is already created which I guess is the case, then go step by step imagining you are doing it manually. 

##Open the excel
$excel = Open-ExcelPackage -Path C:\Users\PavithrasagarK\Desktop\Newfolder\test.xlsx

##Select the Sheet you want to View
$ws = $excel.Workbook.Worksheets["Sheet1"]

##Select the Cell you want to edit
$cell = $ws.Cells["A1"]

##Type what you want to see
$cell.Value = " I LOVE IMPORTEXCEL :)"

##Close the Excel
Close-ExcelPackage $excel -show

**Comment by swoonhusker1** [comment]
Thank you both very much. These were extremely helpful and I'm getting exactly what I wanted.
