### ISSUE TITLE
Copy and Paste range of cells

### ISSUE THREAD

**Issue by swoonhusker1** [dfinke/ImportExcel#549]
I'm looking for a way to copy the values from a range of cells in one worksheet/excel file and paste them into a range of cells in another worksheet/excel file. I have been able to grab the range I want and view the values, but I can't figure out how to paste them. I tried using Set-ExcelRange to paste. Please help me figure out what I'm doing wrong or how I could better accomplish this goal. Here is what I have used-

$excel = Open-ExcelPackage -Path "C:\temp\copiedfrom.xlsx"
$ws = $excel.Workbook.Worksheets["Page 1"]
$range = $ws.Cells["B2:C3"]

I used $range.Value to verify that I have what I want

$excel1 = Open-ExcelPackage -Path "C:\temp\pastedto.xlsx"
$ws1 = $excel1.Workbook.Worksheets["Sheet1"]
Set-ExcelRange -Range $ws1.Cells["C2:D3"] -Value $range
Close-ExcelPackage $excel1 -show

The correct cells have been modified in the range of C2:D3, but it is not inserting the values from above, instead it is inserting the string "B2:C3" into all 4 cells.

I've tried searching in here and the internet for examples and haven't found what I need. Thank you for your help!

**Comment by robert-i** [comment]
-Value seems to be just that, value only so try using:
`Set-ExcelRange -Range $ws1.Cells["c2:d3"] -Value $range.value`

To preserve numberformat just add:
`-NumberFormat $range.Style.Numberformat.Format` 

All kinds of styling(bold/underline/border..) seems to have their own parameter.

**Comment by pkarunkar** [comment]
@robert-i  Just noticed that the $range.value is taken as System.object[] value while inserting. 

$ws.Cells["B2:C3"].Copy($ws1.Cells["C2:D3"]) 

This works.

**Comment by swoonhusker1** [comment]
Thank you both @robert-i and @pkarunkar ! you were both very helpful!
