### ISSUE TITLE
UNC path issue

### ISSUE THREAD

**Issue by mrutgers** [dfinke/ImportExcel#55]
I believe that there is a problem with the calls to Resolve-Path in <b>Export-ExcelSheet.ps1</b> and <b>ImportExcel.psm1</b> (twice)
For a remote path Resolve-Path returns PowerShell's internal path which starts with Microsoft.PowerShell.Core\FileSystem<b>::</b>
This is not a valid path because the colon character is only allowed as the second character in a path, for example: C:\folder1\folder2

This is the fragment that does not work with UNC paths: 
$Path = (Resolve-Path $Path).<b>Path</b>
This does work with UNC paths:
$Path = (Resolve-Path $Path).<b>ProviderPath</b>

**Comment by dfinke** [comment]
Thanks, I'll investigate

**Comment by urlocalguru** [comment]
I assume this is implied but as a side note just doing 
import-excel -path "\\networkshare\foo.xlsx" -sheet fools
also fails

**Comment by dfinke** [comment]
Looks like `New-Object -TypeName System.IO.FileStream` in Import-Excel is an issue and may be similar for the `Export-Excel` thanks to Phil LaVoie for the repro.

Hopefully will get to this soon.

Is it blocking you?

**Comment by mrutgers** [comment]
No, it is not blocking me because as far as I can tell using the <b>ProviderPath</b> property in all calls to Resolve-Path (in Export-ExcelSheet.ps1 and ImportExcel.psm1) will avoid the issue. 
I am still (slowly) making progress in working out what is needed to make the package work with PowerShell v2, because we are using mainly Server 2008R2 / Windows 7 where I work. Being able to generate XLSX files instead of plain CSV has the potential to simplify / enhance some of our processes.

**Comment by meterien** [comment]
I try to use the function **Get-ExcelSheetInfo** which work great with path. I have a specific UNC path with a space in it and it give an error (maybe it the same error): 

New-Object : Exception lors de l'appel de « .ctor » avec « 4 » argument(s) : « Le format du chemin d'accès donné n'est pas pris en charge. »
Au caractère D:\GitMETERIEN\MDTKonsole\Modules\ImportExcel\Get-ExcelSheetInfo.ps1:33 : 19
+ ...   $stream = New-Object -TypeName System.IO.FileStream -ArgumentList $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId :
+1: ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Thanks!

**Comment by Houndin** [comment]
I'm also experiencing trouble with Import-Excel  I've switched it to (Resolve-Path $path).ProviderPath but.... I have spaces in my UNC filename and am getting the same error as @meterien though, in English:
New-Object : Exception calling ".ctor" with "4" argument(s): "The given path's format is not supported."

**Comment by DarkLite1** [comment]
Is this not resolved now with the latest commit?

**Comment by Houndin** [comment]
@DarkLite1 I don't know.  I ended up not using Import-Excel as I had a deadline to meet.

**Comment by dfinke** [comment]
Yes, I checked that in for Import-Excel and published it
