### ISSUE TITLE
Conditional Test Hex Colours stopped working after version 5.4.0. it was working until 5.3.4

### ISSUE THREAD

**Issue by ranabanerjee15** [dfinke/ImportExcel#551]
Conditional Text Hex Colours stopped working after version 5.4.0. it was working until 5.3.4

Hello Doug, A big Thanks for this EXCELLENT module. I would like to flag that before the hex colours used to work in versions 5.3.4, it stopped working after that. 

Please see the code below:

` $batchname = 'Maintenance25'
 $text2 = New-ConditionalText 'Completed' -ConditionalTextColor White -BackgroundColor '#00b359' # green back ground with white fonts. Worked in 5.3.4
 $text1 = New-ConditionalText 'Failed' -ConditionalTextColor White -BackgroundColor '#FD625E' #red background with white fonts. Worked in 5.3.4
 

$paramExportExcel = @{
	Path = ".\$($batchname)_CutoverReport.xlsx"
	Show = $false
	AutoSize = $true
	TableName = 'CutoverReport'
	TableStyle = 'Light1'
	FreezeTopRow = $true
	BoldTopRow = $true
	WorkSheetname = 'CutoverReport'
	ConditionalText = $text1, $text2
	IncludePivotTable = $true
	PivotRows = 'Status'
	PivotData = 'Status'
	IncludePivotChart = $true
	ChartType = 'PieExploded3D'
}
    
$results | Export-Excel @paramExportExcel # $results has some data`

Please see the Screenshot attached
![2019-02-23 11_42_46-exc-mgtbk7p001](https://user-images.githubusercontent.com/33179430/53279966-e29f7580-3760-11e9-8a2f-83bad0b0c536.png)

**Comment by miitchyy** [comment]
Hey Rana,

I submitted a pull request for a fix on this. In the meantime you can convert your colours ahead of time using the cast as below:

```
$text2 = New-ConditionalText 'Completed' -ConditionalTextColor White -BackgroundColor ([System.Drawing.Color] '#00b359')
$text1 = New-ConditionalText 'Failed' -ConditionalTextColor White -BackgroundColor ([System.Drawing.Color] '#FD625E')
```

Kind regards,
Mitch

**Comment by jhoneill** [comment]
I made a change for compatibility with PS6 , but that meant you must pass a name, not a hex value. @miitchyy  has found a way to put back the support for Hex values without breaking PS6 compatibility. I've commented on the pull request, so have a look at that for more detail.

**Comment by ranabanerjee15** [comment]
> Hey Rana,
> 
> I submitted a pull request for a fix on this. In the meantime you can convert your colours ahead of time using the cast as below:
> 
> ```
> $text2 = New-ConditionalText 'Completed' -ConditionalTextColor White -BackgroundColor ([System.Drawing.Color] '#00b359')
> $text1 = New-ConditionalText 'Failed' -ConditionalTextColor White -BackgroundColor ([System.Drawing.Color] '#FD625E')
> ```
> Kind regards,
> Mitch

Many Thanks :-)
