### ISSUE TITLE
can any one help on how to copy unique values of one column to another column in same worksheet

### ISSUE THREAD

**Issue by jampaniharish** [dfinke/ImportExcel#559]

**Comment by jampaniharish** [comment]
[test.xlsx](https://github.com/dfinke/ImportExcel/files/2956708/test.xlsx) want to copy unique IP address from column a to column b.

**Comment by jampaniharish** [comment]
I have tried this it copy's all the data and question is how to copy only unique values from column A to C?

 $excel = Open-ExcelPackage -Path "C:\temp\test.xlsx"
 $ws = $excel.Workbook.Worksheets["sheet1"]
 $ws.Cells["A:A"].Copy($ws.Cells["C:c"])
 Close-ExcelPackage $excel -Show

**Comment by jampaniharish** [comment]
Thanks for the update but select-unique is not working.

> $data.column1header | select-unique | export-excel "test.xlsx" -startcolumn 3 -show
select-unique : The term 'select-unique' is not recognized as the name of a cmdlet, function, script file, or operable program. Chec
verify that the path is correct and try again.
At line:1 char:23
+ $data.column1header | select-unique | export-excel "test.xlsx" -start ...
+                       ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (select-unique:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pkarunkar** [comment]
:) you need to replace columnheader name with your column heading.. If
there is no heading, well n good. Just do $data | select.............

**Comment by pkarunkar** [comment]
And it's select -unique. There is a space after select and unique is a
switch. Sorry for the typo. I was typing in mobile while at work.
If no header, you can use -noheader switch while importing and just do
$data | select -unique........

**Comment by jampaniharish** [comment]
Thanks again for quick response,

Yes I have tried the same but no luck. I have only select-object, select-string, select-worksheet and select-xml methods when Used tab completion. I am missing something?

> $data = import-excel "test.xlsx" -startcolumn 1 -endcolumn 1
> $data

IP
--
10.36.39.3
10.36.39.11
10.36.39.88
10.39.1.101
10.39.1.101
10.39.1.101
10.39.96.72
10.39.96.72
10.39.96.72
10.36.39.3


> $data.ip
10.36.39.3
10.36.39.11
10.36.39.88
10.39.1.101
10.39.1.101
10.39.1.101
10.39.96.72
10.39.96.72
10.39.96.72
10.36.39.3
> $data.ip|Select-unique
Select-unique : The term 'Select-unique' is not recognized as the name of a cmdlet, function, script file, or operable program. Chec
verify that the path is correct and try again.
At line:1 char:10
+ $data.ip|Select-unique
+          ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Select-unique:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pkarunkar** [comment]
You still using select -unique without space.
I understand you get confused with verb-noun command format.

Please learn about alias.. Or use select-object -unique..

**Comment by jampaniharish** [comment]
Thanks a lot it worked. My bad I had read the command mistakenly as select-unique instead of select -unique (select space unique) went through the thread again and found the difference.
> $data.ip|Select -unique
10.36.39.3
10.36.39.11
10.36.39.88
10.39.1.101
10.39.96.72

**Comment by jampaniharish** [comment]
You still using select -unique without space.
I understand you get confused with verb-noun command format.

Please learn about alias.. Or use select-object -unique..

Thanks for the suggestion.

**Comment by jampaniharish** [comment]
I am new to use import excel module similarly how do we apply simple formulas on a column can you give any examples please.

fro example from the below how to get count of rows on salary column or how do we use sum function here. can you guide me to apply some formula. thanks in advance.

salary
10000
20000
30000
40000
-
-
-
-

**Comment by dfinke** [comment]
# Please review the link 

https://github.com/dfinke/ImportExcel/tree/master/Examples

# =Sum

Please review the examples to see how to use `Set-Format`.

![image](https://user-images.githubusercontent.com/67258/54229400-8ebfbb00-44da-11e9-8c64-e7cd2fb4f893.png)

**Comment by jampaniharish** [comment]
Thanks dfinke and pkarunkar for your help, I just started using github very recently and this community rocks.
