### ISSUE TITLE
Problem: getting data from calculated cells

### ISSUE THREAD

**Issue by paysonsolutions** [dfinke/ImportExcel#560]
Firstly, I may be going about this all wrong. If that is the case, let me know. 

I am trying to read data from a spreadsheet, and then work with that data:

$data = import-excel -path $filename -worksheet summary (where $filename = c:\path\filename.xlsx and summary is the name of the worksheet I want to read from). 

This results in $data containing this information:

index            : 1
Cluster          : 
CPU GHz Capacity : 
CPU GHz Used     : 
CPU % Free       : 
Mem Capacity GB  : 
Mem Used GB      : 
Mem % Free       : 

index            : 2
Cluster          : ABC Cluster
CPU GHz Capacity : #DIV/0!
CPU GHz Used     : #DIV/0!
CPU % Free       : #DIV/0!
Mem Capacity GB  : #DIV/0!
Mem Used GB      : #DIV/0!
Mem % Free       : #DIV/0!

my issue is ... when opened in excel, the cells (represented here by #DIV/0!) have calculated data which appears properly. 

What am I doing wrong?

**Comment by dfinke** [comment]
Looks right, can you post the xlsx?

**Comment by paysonsolutions** [comment]
[debug.cluster-stats.testing.xlsx](https://github.com/dfinke/ImportExcel/files/2963608/debug.cluster-stats.testing.xlsx)

Here is my file, which gets its data from a function in my script that uses ExportExcel (quite nicely).

**Comment by dfinke** [comment]
I opened the file and the summary sheet has the error

![image](https://user-images.githubusercontent.com/67258/54313548-fdbb1380-45af-11e9-9ca0-d3e09965f151.png)

**Comment by paysonsolutions** [comment]
I've felt smarter ... Seems like i was working with an empty output file (template), which is why all fields were showing the #DIV/0! error. I took the file I uploaded above, and did the exact same assignment operation as I indicated in my OP, and these are my results: 

index            : 1
Cluster          : 
CPU GHz Capacity : 
CPU GHz Used     : 
CPU % Free       : 
Mem Capacity GB  : 
Mem Used GB      : 
Mem % Free       : 

index            : 2
Cluster          : ABC Cluster
CPU GHz Capacity : 96
CPU GHz Used     : 2.5
CPU % Free       : 97.5
Mem Capacity GB  : 416
Mem Used GB      : 101.571428571429
Mem % Free       : 75.5

index            : 3
Cluster          : DEF Cluster
CPU GHz Capacity : 96
CPU GHz Used     : 1.47058823529412
CPU % Free       : 98.5294117647059
Mem Capacity GB  : 384
Mem Used GB      : 88.4117647058823
Mem % Free       : 76.8823529411765

index            : 4
Cluster          : GHI Cluster
CPU GHz Capacity : #DIV/0!
CPU GHz Used     : #DIV/0!
CPU % Free       : #DIV/0!
Mem Capacity GB  : #DIV/0!
Mem Used GB      : #DIV/0!
Mem % Free       : #DIV/0!

index            : 5
Cluster          : JKL Cluster
CPU GHz Capacity : #DIV/0!
CPU GHz Used     : #DIV/0!
CPU % Free       : #DIV/0!
Mem Capacity GB  : #DIV/0!
Mem Used GB      : #DIV/0!
Mem % Free       : #DIV/0!

index            : 6
Cluster          : MNO Cluster
CPU GHz Capacity : #DIV/0!
CPU GHz Used     : #DIV/0!
CPU % Free       : #DIV/0!
Mem Capacity GB  : #DIV/0!
Mem Used GB      : #DIV/0!
Mem % Free       : #DIV/0!

index            : 7
Cluster          : PQR Cluster
CPU GHz Capacity : 96
CPU GHz Used     : 4.5
CPU % Free       : 95.5
Mem Capacity GB  : 416
Mem Used GB      : 114.464285714286
Mem % Free       : 72.4285714285714

index            : 8
Cluster          : REG Cluster
CPU GHz Capacity : 224
CPU GHz Used     : 55.25
CPU % Free       : 75.2857142857143
Mem Capacity GB  : 2047
Mem Used GB      : 1108.71428571429
Mem % Free       : 45.8214285714286

... sigh, sorry to bother.

**Comment by paysonsolutions** [comment]
i had not been expecting ALL fields to be in error. The script takes a while to run, so in 'diags/testing' mode, it only checks a couple of clusters.

**Comment by dfinke** [comment]
Cool, glad it's working well for you though. If you've got questions, post them

**Comment by paysonsolutions** [comment]
actually ... it seems that I have to open the output spreadsheet in excel, and save it (without making any changes), for those calculated fields to get data. 
is that normal?

**Comment by dfinke** [comment]
No. not really.
