### ISSUE TITLE
Import 1 column excel data as a hash- table

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#561]
Hi,
kindly suggest how can I import data from excel sheet which has only 1 column into a hash table?

Currently I have the following two lines setup in my script. Line1 to import the column from excel and line 2 to convert the object to array. 

[array]$ValidStationNames = Import-Excel $ValidationRulesFolder\$ValidationRulesFileName -WorksheetName 'StationNames'

$ArrayValidStationNames=($ValidStationNames)."StationNames"

The reason I am trying to convert it to hash tables as I read that comparison can be super quick with hastables. Currently I run the below code to check if the cell value is in the array. if yes make it green if no make that cell red. 

If($worksheet.cells.Item($i, $LocationCodeColumn).value2 -in $ArrayValidStationNames)
 
 {
    $worksheet.cells.Item($i, $LocationCodeColumn).Interior.ColorIndex = 35;
 }
Else 
 {
 $worksheet.cells.Item($i, $LocationCodeColumn).Interior.ColorIndex = 45;

 }

Thanks in advance.

**Comment by pkarunkar** [comment]
```
$array = @('Hi', 'Hello', 'Greeting', 'Thankyou', 'Gracias', 'Adios')


$HashTable = @{}
For ($KeyIndex = 0; $KeyIndex -lt $array.Length; $KeyIndex += 2) {
    $Key   = $array[$KeyIndex]
    $Value = $array[$KeyIndex + 1]
    $HashTable.Add($Key, $Value) 
}

$HashTable
```

**Comment by jhoneill** [comment]
I would change the code like this 


```
$hash = @{}
foreach ($row in (Import-Excel YourPath -WorksheetName YourSheetName)) { $hash[$row.YourColumnName] = $true}
```

Then your _if_ becomes 
`if ( $hash[$worksheet.cells.Item($i, $LocationCodeColumn).value2 ]) { ... }
`

For lots of checks against a big list it is much faster than the using -in / -contains see 
https://jamesone111.wordpress.com/2017/03/13/improving-powershell-performance-with-hash-tables/
