### ISSUE TITLE
Convert spreadsheet to CSV

### ISSUE THREAD

**Issue by jwaldeck1** [dfinke/ImportExcel#563]
I'm looking to have a powershell script run to grab a spreadsheet and convert it to CSV. The spreadsheet changes names, but it always starts with the same phrase, so I want to use a wildcard to grab it. Is this something ImportExcel can do? Before I dive into it, I wanted to make sure this module will do what I need. And if anyone has any tips or scripts, please share as well. Thanks!

**Comment by pkarunkar** [comment]
```
"Hi" | Export-Excel C:\TEMP\testsheets.xlsx -WorksheetName Sheeeet1
"Bye" | Export-Excel C:\TEMP\testsheets.xlsx -WorksheetName Sheeeet2

$excel = Open-ExcelPackage C:\TEMP\testsheets.xlsx
$excel.Workbook.Worksheets | Select Name | where {$_.Name -imatch "Sheeet*"}
```

Output:
```
Name    
----    
Sheeeet1
Sheeeet2
```

Why change to csv while you can do everything from excel with this module?
