### ISSUE TITLE
Loop through dataset and add to hashtable

### ISSUE THREAD

**Issue by thefaan** [dfinke/ImportExcel#567]
Hi

I am using the ImportExcel module and making use of the Export-MultipleExcelSheets. I have a dataset that returns multiple tables and would like to loop through them instead of specifying the tables. The reason for this is that the known number of datatables in a dataset is not known.

`cls

$SQLServer = '.\SQLExpress';
$Database = 'AdventureWorks';
$sqlCommand = "SELECT * FROM sys.databases

SELECT * FROM sys.columns";
[String]$Path = "filesystem::C:\Temp\Databases_20190325.xlsx"

$connectionString = "Server=$SQLServer;Database=$Database;Integrated Security=true"
$connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
$command = New-Object System.Data.Sqlclient.Sqlcommand($sqlCommand, $connection)
$connection.Open()
$adapter = New-Object System.Data.sqlclient.SqlDataAdapter $command 
$dataset = New-Object System.Data.DataSet
$adapter.Fill($dataSet) > null
$connection.Close()

foreach($table in $dataset.Tables)
{
    Write-Host $table.TableName
    if ($($table.TableName) -eq 'table') {$Table1 = $table}
    if ($($table.TableName) -eq 'table1') {$Table2 = $table}
    if ($($table.TableName) -eq 'table2') {$Table3 = $table}
    if ($($table.TableName) -eq 'table3') {$Table4 = $table}
    if ($($table.TableName) -eq 'table4') {$Table5 = $table}
	if ($($table.TableName) -eq 'table5') {$Table6 = $table}
}
 
$DataToGather = @{
    Set1 = {$Table1}
    table1 = {$Table2}
    table2 = {$Table3}
    table3 = {$Table4}
    table4 = {$Table5}
	table5 = {$Table6}
}

#Export-MultipleExcelSheets -AutoSize $Path $DataToGather
$DataToGather

$DataToGather.Clear()`

I have tried the below but have not been very successful.

`$DataToGather = @{}  

foreach ($table in $dataset.Tables) {
    Write-Host $table.TableName
    Add-Member -InputObject $DataToGather -MemberType NoteProperty -Name $table.TableName -Value $table 
--Add-Member -MemberType NoteProperty -Name $table.TableName -Value $dataset.Tables['$($table.TableName)']
--$DataToGather.Add($table.TableName ,$table)
}`

**Comment by dfinke** [comment]
Rather than build up a hastable, I used this approach.

Does this do what you need?

```powershell
$sqlCommand = @"
SELECT * FROM SalesLT.Address
SELECT * FROM SalesLT.Customer
SELECT * FROM SalesLT.CustomerAddress
SELECT * FROM SalesLT.Product
SELECT * FROM SalesLT.ProductCategory
SELECT * FROM SalesLT.ProductDescription
SELECT * FROM SalesLT.ProductModel
"@


$connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
$command = New-Object System.Data.Sqlclient.Sqlcommand($sqlCommand, $connection)
$connection.Open()
$adapter = New-Object System.Data.sqlclient.SqlDataAdapter $command
$dataset = New-Object System.Data.DataSet
$null=$adapter.Fill($dataSet) 
$connection.Close()

$xlfile = "$env:TEMP\tables.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$count=1
foreach($table in $dataset.Tables) {
    $table| Export-Excel $xlfile -WorksheetName "Table$($count)" -AutoSize -AutoNameRange
    $count+=1
}

Invoke-Item $xlfile
```

**Comment by thefaan** [comment]
Hi Doug

This definitely does what I need it to do.

Thanks for your hep, appreciate it.
