### ISSUE TITLE
Get-CellStyle, Get-RowStyle, Get-ColumnStyle and Get-Format cmdlets?

### ISSUE THREAD

**Issue by riahc3** [dfinke/ImportExcel#568]
It would be nice if these three cmdlets exists in order to, for example, know if a cell/row/column has a background color, etc.

**Comment by riahc3** [comment]
Nothing?

**Comment by jhoneill** [comment]
Sorry - looks like everyone was expecting someone else to answer. We could add these 
but if you have ```

$xl = Open-ExcelPackage C:\Users\mcp\AppData\Local\Temp\Test1.xlsx 
then
```
$xl.<<sheetname>>.Column(1).style  
```
gives you what you need especially with .numberformat  .font .fill and .border items.   (ditto with .row(1) or ,Cells[1,5])  

If you want to test for the format it wouldn't be hard to add a test version of set-ExcelRange which comes back with $true or $false for whether your chosen format is applied.
