### ISSUE TITLE
Import multiple CSV Files or resolve error with truncated data

### ISSUE THREAD

**Issue by jaswicki** [dfinke/ImportExcel#569]
I am trying to Import multiple CSV files into a Workbook with each sheet taking the name of the CSV file. Is this an option witf Import-Excel?

**Comment by jaswicki** [comment]
As a side note the reason I need to do this is the script I am working on either truncates data or errors out when using Export-Excel to create a workbook with multiple sheets.

`$DaysAgo=(Get-Date).AddDays(-32)
$now = Get-Date
'Returning PCs with Password Last Set between ' + $DaysAgo + ' and ' + $now  #  -or (LastLogonTimeSTamp -gt $DaysAgo)

$domainNames = Get-ADForest
$now = Get-Date -format "yyyyMMdd"
$filename = $now + "PCHealth.xlsx"

foreach($domainName in $domainNames.Domains)

{
    $domainName + ' - ' + (get-date).ToString("HH:mm")

    $comps = Get-ADComputer -server $domainName -Filter {(PwdLastSet -gt $DaysAgo) } -Properties PwdLastSet,LastLogonTimeStamp,Description,OperatingSystem 
    
    $comps | Select-Object -Property DistinguishedName,Name,Enabled,Description,OperatingSystem, `

    @{Name="PwdLastSet";Expression={[datetime]::FromFileTime($_.PwdLastSet)}}, `

    @{Name="LastLogonTimeStamp";Expression={[datetime]::FromFileTime($_.LastLogonTimeStamp)}} |

    Export-Excel c:\temp\$filename -WorksheetName $domainname -FreezeTopRow -AutoSize
}`

If I have the Get-ADComputer line piped together as a one liner I get the error: 

> Get-ADComputer : The server has returned the following error: invalid enumeration context.

If I first put that info in a variable and then select and pipe it works for the most part except in my largest domain I only get 297 rows. If I change the Export-Excel to Export.csv and create a csv per domain the csv for my largest domain has 203,521 rows. 

I would prefer to use Export-Excel but only if it is reliable. Don't get me wrong. It is a great module, I am just having problems with this task.

**Comment by dfinke** [comment]
I'm not an expert with AD. Seems like there may be a property that export Excel doesn't handle. You could use export-csv first, then do an import-csv|export-Excel. 

Don't know if that helps.

It'd be good to narrow down the property and it's data in a small reproducible example. Then it can be determined if the module can be upgraded to handle that.

**Comment by jampaniharish** [comment]
Not sure if I have understood your requirement correctly I have couple of CVS files and I wanted to them to get added into excel file like each csv file as one work sheet I did like this.

import-Csv "MyCSvfile.csv" | Export-Excel "mynewcsvfile.xlsx" -WorksheetName "mycsvfile" -AutoSize
import-Csv "MyCSvfile1.csv" | Export-Excel "mynewcsvfile.xlsx" -WorksheetName "mycsvfile1" -AutoSize

The above commands will give me new excel file with name mynewcsvfile I gave here, and worksheets are named after my csv files.

**Comment by jhoneill** [comment]
Obvious things to try  
1.  Set $domainName and $DaysAgo and run 
```
$comps = Get-ADComputer -server $domainName -Filter {(PwdLastSet -gt $DaysAgo) } -Properties PwdLastSet,LastLogonTimeStamp,Description,OperatingSystem   | Select-Object -Property DistinguishedName,Name,Enabled,Description,OperatingSystem, `
    @{Name="PwdLastSet";Expression={[datetime]::FromFileTime($_.PwdLastSet)}}, `
    @{Name="LastLogonTimeStamp";Expression={[datetime]::FromFileTime($_.LastLogonTimeStamp)}}
```
 
Invalid enumeration context normally means you've sent something to get-ADComputer which you shouldn't have ... and shouldn't be caused by something further along the pipeline.  You can then check $comps.count and see if you have the expected number of items. 

2. Then send $comps to Export-Excel. If the last row of data is 293, and otheres are lost that is the 292nd item which $comps[291]; check whether you have got rows 0..291 or if you have some other selection. Then it may be obvious what is causing the other rows to be dropped.  

3. if you have many csv files in a folder you can do 
`dir *.csv  | foreach {import-csv $_.FullName | export-excel -path C:\temp\test44.xlsx -WorksheetName $_.name}
` 

or better -worksheetName {$_.name -replace "\.csv$","")

**Comment by uSlackr** [comment]
@jaswicki 
This [article](https://social.technet.microsoft.com/wiki/contents/articles/32418.active-directory-troubleshooting-server-has-returned-the-following-error-invalid-enumeration-context.aspx) is enlightening.
