### ISSUE TITLE
Warning when Ampersand ('&') in Column Header and generating a Pivot Table

### ISSUE THREAD

**Issue by pmd006** [dfinke/ImportExcel#570]
When loading in a .CSV file and the column headers have an '&' in them, and I try to create a pivot table, I get an warning message:

WARNING: Failed adding PivotTable 'MyPivot': Exception calling "Add" with "3" argument(s): "An error occurred while parsing EntityName. Line
 1, position 752."

My solution so far has just been to replace the '&' with 'and' before then piping into Export-Excel, and this works fine for my purposes. 

If I manually create the pivot in Excel, its able to handle the '&' in the headers without issue.

**Comment by dfinke** [comment]
# Fails here
https://github.com/dfinke/ImportExcel/blob/master/PivotTable.ps1#L217

$pivotTable = $wsPivot.PivotTables.Add($Address, $SourceWorkSheet.Cells[$SourceRange], $pivotTableName)

Could loop through the first row and check the headings for invalid names. The EPPlus `PivotTables.Add` does not create the same sort of PivotTable as when you do it manually in Excel 2016. Including colorization. Tried to move the `&` around in the column name, no luck.
