### ISSUE TITLE
Modifying workbok and export first sheet

### ISSUE THREAD

**Issue by cesarzapatawfm** [dfinke/ImportExcel#571]
I have this code that makes some changes and closes excel package. This works fine. 
I'm trying to export sheet1 after being saved to another workbook but no formulas, values only. 
I'm adding the export-excel at the end but my output file is empty. 

```
$f = "C:\Users\user1\S3\DC_In_Stock_Report.xlsx"
$excel = Open-ExcelPackage $f
$sheet1 = $excel.Workbook.Worksheets[1]
$sheet2 = $excel.Workbook.Worksheets[2]
$BorderColor = "Black"

  $sheet2.InsertColumn(5,1)
   Set-Format -Address $sheet2.Cells["E2"] -Value "Avg BOH" -Bold -BorderColor $BorderColor
   3..($sheet2.Dimension.Rows) |
    ForEach-Object {
    $sheet2.Cells["E$_"].Formula = "=AVERAGE(N$_,S$_,X$_,AC$_,AH$_,AM$_,AR$_)"        
    }

   $sheet1.InsertColumn(1,1)
   $sheet1.InsertColumn(12,2)
   Set-Format -Address $sheet1.Cells["A2"] -Value "REGION" -Bold -BorderColor $BorderColor
   Set-Format -Address $sheet1.Cells["L2"] -Value "Avg DOS" -Bold -BorderColor $BorderColor
   Set-Format -Address $sheet1.Cells["M2"] -Value "Avg BOH" -Bold -BorderColor $BorderColor

    
   3..($sheet1.Dimension.Rows) |
    ForEach-Object {
    $sheet1.Cells["A$_"].Value = "NA"
     $sheet1.Cells["L$_"].Formula = "=M$_/((F$_+N$_)/7)"
    $sheet1.Cells["M$_"].Formula = "=VLOOKUP(C$_,'A-INBOUND OUTBOUND DETAIL'!C:E,3,FALSE)"  
             
    }
  
Close-ExcelPackage $excel| export-excel "C:\Users\user1\S3\output.xlsx" -WorkSheetname First
or
 $sheet1| export-excel "C:\Users\user1\S3\output.xlsx" -WorkSheetname First
???
```
Is there a way to export sheet1 values only to another workbook? I looked and tried a few things with new luck.

**Comment by cesarzapatawfm** [comment]
I wanted to add that I tried export-csv but the issue is that the cells that contain formulas are blank on the CSV. Any way I can just keep the values ?

**Comment by jhoneill** [comment]
If you create the sheet as a file, formulas are not automatically converted to values until you open the file in excel. You can specify -Calculate when you close (or on export) , but it doesn't do every possible formula. 

You can't send data to sheet the way you are trying to in the first example. 
The nearest to what you want is ```
 
Close-ExcelPackage $excel -calculate
import-excel <<path>> -worksheet <<worksheetName>> | export-excel <path> <sheetname> 

```
