### ISSUE TITLE
ConvertTo-ExcelXlsx add -Destination path parameter

### ISSUE THREAD

**Issue by wsuhoey** [dfinke/ImportExcel#578]
It would be great if `ConvertTo-ExcelXlsx` supported a `-Destination` parameter, so that you could do something like:
```
$sourcepath = C:\source\file1.xls
$destinationpath = D:\converted\file1.xlsx
ConvertTo-ExcelXlsx -Source $sourcepath -Destination $destinationpath
```
So that the final output puts the converted xlsx file into the `$destination` path, instead of  defaulting to the same folder as the source, as it does today.

**Comment by wsuhoey** [comment]
Hello. Was this Closed as added or not added?

**Comment by dfinke** [comment]
Yes. not added. May review at another time.
