### ISSUE TITLE
Percentage in Chart-Pie3D

### ISSUE THREAD

**Issue by DillyBabu** [dfinke/ImportExcel#58]
Hi,
Thanks for this excellent module. Is there any option to have percentage in chart.

**Comment by dfinke** [comment]
Thank you.

That is not exposed. Could say some more about what you're looking for. Then I can better investigate.

**Comment by DillyBabu** [comment]
Hi,
In Excel chart we have AddLabel option ->Format Data Label ->Percentage
Attaching sample FYR. It would be helpful if we have this feature.

Thank You
![percentage](https://cloud.githubusercontent.com/assets/16417357/11994709/4a7f6d3c-aa69-11e5-9897-629cc8302d97.png)

**Comment by dfinke** [comment]
Thanks for the example. I'm experimenting with the basics and unfortunately exposing background and slice coloring is not easily done. Showing categories and percentages look better. More testing and then I'll make it available.

![image](https://cloud.githubusercontent.com/assets/67258/12003620/915a0d58-aaf4-11e5-8428-793acc88780b.png)

**Comment by DillyBabu** [comment]
Thanks a lot for your work. I will wait and look for the updated New-Excelchart function

**Comment by dfinke** [comment]
Ok, I've checked in this new functionality. I have not pushed it to the gallery yet. If you try out, let me know how it works.

**Comment by DillyBabu** [comment]
Yes, I checked  Export-excel function with showpercent and it works fine. Thanks again.

**Comment by dfinke** [comment]
Thanks for the suggestion and trying it out
