### ISSUE TITLE
Could not create Excel object in Azure Automation Runbook

### ISSUE THREAD

**Issue by jgb000** [dfinke/ImportExcel#581]
I'm trying to use the ImportExcel module with an Azure Automation Runbook, but running into trouble using ConvertTo-ExcelXlsx. I have a .xls file in blob storage that I retrieve in the runbook and save in a temporary location. I then need to convert the .xls file to a .xlsx file to continue processing it. Is it possible to use ConvertTo-ExcelXlsx in a runbook?

```
param(
    [Parameter(Mandatory=$true)]
    [String] $fileName
)

#Retrieve the file from Azure blob storage and save it in a temporary location to work on the contents of the file
$filePath = "$env:temp\$fileName"
$storageAccountName = 'someAccount'
$storageAccountKey = 'someKey'
$context = New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $storageAccountKey 
$cloudFile = Get-AzureStorageBlobContent -Container 'someContainer' -Blob $fileName -Context $context -Destination $env:temp -Force

ConvertTo-ExcelXlsx $filePath
```

When I test running this script, I see this error message:

![image](https://user-images.githubusercontent.com/34523352/56002021-c0b08100-5d15-11e9-9b1d-bbbc2063bb68.png)

**Comment by dfinke** [comment]
`ConvertTo-ExcelXlsx` requires Excel to be installed because it uses COM and "remote controls" Excel to open the file and then save it in the xlsx format.

**Comment by jgb000** [comment]
Thanks for the quick response. I have another related question. I was trying to convert from .xls to .xlsx so that I could then use `Import-Excel`. Does `Import-Excel` only work with .xlsx files?

**Comment by dfinke** [comment]
Yes, only with the newest version
