### ISSUE TITLE
Unable to retrieve value from cell based on a CSE formula

### ISSUE THREAD

**Issue by dxc-lamb** [dfinke/ImportExcel#582]
I have an Excel workbook "template" that contains a CSE formula for computing median values. One of the worksheets is populated with IIS log data using Export-Excel. If I try to then retrieve the value from a cell that uses the CSE formula, the value and text are empty. If I use Close-ExcelPackage -Calculate  $excel,  the text/value returns #NUM! when I open and read.

However, if I open the Excel file with Excel and save it and the use Open-ExcelPackage and evaluate the cell using $excel.Workbook.Worksheets[1].Cells[2,10].Text, I get a correct value. What is the Excel "save" doing that changes the behavior of the CSE formula based cell and how can I replicate that with what is available in ImportExcel?

**Comment by dfinke** [comment]
Could you post an xlsx with shows this?

**Comment by dxc-lamb** [comment]
[sample.xlsx](https://github.com/dfinke/ImportExcel/files/3077905/sample.xlsx)

I suggest making a copy of the file before working with it just in case... As I indicated in my original post, opening and saving with Excel eliminates the issue. But since this is for automated reporting from a server we don't want to install Excel on, I don't have a way of opening and saving before sending the final report.

Ran the following
$excel = Open-ExcelPackage "C:\temp\sample.xslx"
$excel.Workbook.Worksheets["PannelReport"].Cells[2,10]
Close-ExcelPackage $excel


With a response of:
Style                 : OfficeOpenXml.Style.ExcelStyle
StyleName             : Normal
StyleID               : 0
Value                 : 0

Text                  : 0
Formula               : MEDIAN(IF(A2=PannelLogs!D:D,PannelLogs!K:K))/1000
FormulaR1C1           : MEDIAN(IF(RC[-9]=PannelLogs!D:D,PannelLogs!K:K))/1000
Hyperlink             : 
Merge                 : False
AutoFilter            : False
IsRichText            : False
IsArrayFormula        : False
RichText              : {}
Comment               : 
Worksheet             : PannelReport
FullAddress           : 'PannelReport'!J2
FullAddressAbsolute   : 'PannelReport'!$J$2
ConditionalFormatting : OfficeOpenXml.ConditionalFormatting.RangeConditionalFormatting
DataValidation        : OfficeOpenXml.DataValidation.RangeDataValidation
Current               : 
Address               : J2
Start                 : OfficeOpenXml.ExcelCellAddress
End                   : OfficeOpenXml.ExcelCellAddress
Table                 : 
IsName                : False
Rows                  : 1
Columns               : 1

Thanks

**Comment by dfinke** [comment]
Do you have the script that creates this?

**Comment by dxc-lamb** [comment]
The formulas that are in column J of PannelReport aren't scripted. I start with a base Excel file, add data to the PannelLogs worksheet using ImportExcel. I then need to evaluate the "computed" values in column J after the data has been added. Looking at the spreadsheet I attached, I think there is an issue. Let me attach a new version in a few minutes.

Thanks

**Comment by dxc-lamb** [comment]
I was originally working with an XLSM file and switch to XLSX thinking that might be part of the problem. Come to find out the CSE functions aren't working in the XLSX version. However, the same issue exist in the XLSM version. Unfortunately I can't upload that to the forum since it isn't supported, due to obvious reasons.
