### ISSUE TITLE
ConvertToExcelXlsx more verbose error message

### ISSUE THREAD

**Issue by mattcushing** [dfinke/ImportExcel#583]
I'm having issues when I'm calling this, and I'm wondering if the messaging can be a little more verbose.

    try{    
        $Excel = New-Object -ComObject "Excel.Application"
        } catch {
            throw "Could not create Excel.Application ComObject. Please verify that Excel is installed."
        }

I'm logging errors to a file in my script and I grab this and Add-Content to my logfile.  Is it possible to add something like it in the throw for this section?
    catch{
            $ErrorMessage = $_.Exception.Message
            $FailedItem = $_.Exception.ItemName
                ((Get-Date).ToString() + " **ERROR-xls**: " + $ErrorMessage + " - " + $FailedItem) | Add-Content $LogFile;
            exit 999; #fail the SSIS job
    }

**Comment by dfinke** [comment]
Probably. One issue would be the `Add-Content`. Not everyone would want to write to a file.

**Comment by mattcushing** [comment]
Oh yeah, understood.  I just mean tagging the $errorMessage on the end of the throw so you can see what's causing the issue.  I'm having a problem because when I run it manually, it's fine.  But when it gets kicked off by a sqlagent job it fails and I can't catch why except the throw "Could not create...." message.  Thought tacking something else on there would allow me to get more specfic
