### ISSUE TITLE
Excel Date and Time Formatting

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#584]
Hello,

I use Export-Excel to create an Excel sheet from a CSV file. Column D contains a timestamp. 

Currently the column D of my output file has category "General". 
How can I set column D to category "Date"?
I think the final step would be to set the custom date and time formatting.

Sample: 12.10.2018 12:22:31
Category: General

Goal:
Category: Date
Type: dd.mm.yyyy hh:mm:ss

What I have so far:
# Export-Excel
$IMPORT = Import-Csv "$OUTPUT\Input.csv"
$IMPORT | Export-Excel -Path "$OUTPUT\Output.xlsx" -NoNumberConversion * -FreezeTopRow -BoldTopRow -AutoSize -AutoFilter -CellStyleSB {
# HorizontalAlignment "Center" of column A-B + D
param($WorkSheet)
$WorkSheet.Cells["A:B"].Style.HorizontalAlignment="Center"
$WorkSheet.Cells["D:D"].Style.HorizontalAlignment="Center"
$WorkSheet.Cells["D:D"].Style.Numberformat.Format="dd.mm.yyyy hh:mm:ss"
}

May you assist me? Thanks in advance.

**Comment by dfinke** [comment]
The date format is not something Excel will recognize. Off the top of my head, I would covert that when doing the `Import-Csv`, in a `foreach` loop to a datetime format, then `export-excel` and remove the switch `-NoNumberConversion`. Then you can apply the `NumberFormat`

**Comment by evild3ad** [comment]
$IMPORT = Import-Csv "$OUTPUT\Input.csv" | Sort-Object -Descending { $_."runtime [UTC]" -as [datetime] }
$IMPORT | Export-Excel -Path "$OUTPUT\Output.xlsx" -FreezeTopRow -BoldTopRow -AutoSize -AutoFilter -CellStyleSB {
# HorizontalAlignment "Center" of column A-B + D
param(
$WorkSheet
)
$WorkSheet.Cells["A:B"].Style.HorizontalAlignment="Center"
$WorkSheet.Cells["D:D"].Style.HorizontalAlignment="Center"
}
}

Note: "runtime [UTC]" is the name of my column D.

**Comment by dfinke** [comment]
Good stuff.

Note, you could also pipe directly to `Export-Excel`. Bypassing the $IMPORT variable.
