### ISSUE TITLE
Question about filter in pivot table

### ISSUE THREAD

**Issue by Arkheon** [dfinke/ImportExcel#586]
Hello ,

I have no problem with pivot  table creation and the -pivotfilter.
One question remains , for example : 

Fruit | value
------------ | -------------
apple | 5
banana | 10
grapes | 10

Filter on column "fruit"

Can i pass an argument after applying this filter to filter apple on opening my excel sheet ?
I want my sheet pre filtered 

Ty :)

**Comment by pkarunkar** [comment]
Refer
https://github.com/dfinke/ImportExcel/issues/521


This may help you.
