### ISSUE TITLE
Convert Excel worksheet to CSV with more rows than the Excel limit

### ISSUE THREAD

**Issue by slothspeich** [dfinke/ImportExcel#588]
We have a system generated Excel report that has more than the maximum number of rows Excel can open and it gets truncated when opened.  We would like to convert the file from xlsx to csv to import into another system, but both Import-Excel and ConvertFrom-ExcelData both stop producing data at the 1,048,576 limit and the remaining rows just contain the delimiters (which tells me it can read the file, it just stops processing).

Is there a way to override the default Excel limit using this tool, or any suggestions you might have?

**Comment by dfinke** [comment]
I don't know. That question should be followed up with the Microsoft Excel folks for a better answer.

**Comment by slothspeich** [comment]
Ah, okay.  I will look for a different solution.  Thanks for the quick reply!
