### ISSUE TITLE
Hyperlinks of drawings

### ISSUE THREAD

**Issue by TardisBeaubien** [dfinke/ImportExcel#589]
Some of our users have added hyperlinks to shapes and text boxes. I want to list and Test-Path those links. 

I can list the drawings with the Worksheet.Cells.Drawings collection, but OfficeOpenXml.Drawing.ExcelShape objects don't seem to have an hyperlink/address property. Is there a way to list those hyperlinks ?

Thank you !

**Comment by dfinke** [comment]
Don't know. You can search for EPPlus and see if that supports the property. EPPlus is what is being used to interact with the underlying Excel file. If I get time, I'll google it.
