### ISSUE TITLE
ConvertFrom-ExcelToSQLInsert - ConvertFrom-ExcelData : A parameter cannot be found that matches parameter name 'StartRow'.

### ISSUE THREAD

**Issue by whjelmar** [dfinke/ImportExcel#591]
ConvertFrom-ExcelData : A parameter cannot be found that matches parameter name 'StartRow'.
At line:98 char:27
+     ConvertFrom-ExcelData @params {
+                           ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-ExcelData], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,ConvertFrom-ExcelData

Checked the tests and there is no test coverage for this or many of the other parameters

**Comment by nlsdg** [comment]
This should be fixed by PR #769 when it is merged.

**Comment by ukrainian-serge** [comment]
Still same issue:

`ConvertFrom-ExcelData : A parameter cannot be found that matches parameter name 'StartRow'.`

Tried with aliases to no avail
