### ISSUE TITLE
Rows and columns reversed in pivot totlals 

### ISSUE THREAD

**Issue by jhoneill** [dfinke/ImportExcel#592]
Current the code in pivotTable.ps1 current reads like this 
   ```
if ($PivotTotals -eq "None" -or $PivotTotals -eq "Columns") { $pivotTable.RowGrandTotals = $false }
            elseif ($PivotTotals -eq "Both" -or $PivotTotals -eq "Rows") { $pivotTable.RowGrandTotals = $true  }
            if ($PivotTotals -eq "None" -or $PivotTotals -eq "Rows") { $pivotTable.ColumGrandTotals = $false }   # Epplus spelling mistake, not mine!
            elseif ($PivotTotals -eq "Both" -or $PivotTotals -eq "Columns") { $pivotTable.ColumGrandTotals = $true  }
         
```

The options in EPPlus are "Have a grand totals Column" and "Have a grand totals row".
The function describes them, as rows, and and column 
Totalling by **by-rows** should a totals **column** and vice versa. However at the moment selecting -pivottotals "rows" (plural) turns on the have-a-totals-row (singular)., option which totals by columns.  This is confusing but any change is likely to be a breaking one. So seeking suggestions for what is the best way forward.

**Comment by dfinke** [comment]
If I understand correctly, I think I don't, this is a string/feature naming issue?

In Excel, the `PivotTable Options` read and react the way PS and EPPlus work

![image](https://user-images.githubusercontent.com/67258/57543347-1df21f00-7322-11e9-850d-b516bc4489c0.png)

**Comment by jhoneill** [comment]
Hmmm. 
$path = "$Env:TEMP\test.xlsx"
remove-item -path $path -ErrorAction SilentlyContinue

```
$excel =  ConvertFrom-Csv    @"
Product, City, Gross, Net
Apple, London , 300, 250
Orange, London , 400, 350
Banana, London , 300, 200
Orange, Paris,   600, 500
Banana, Paris,   300, 200
Apple, New York, 1200,700
"@  | Export-Excel -PassThru  -Path $path

Add-PivotTable -Address $excel.Sheet1.Cells["F1"] -SourceWorkSheet $Excel.Sheet1 -SourceRange $Excel.Sheet1.Dimension.Address`
  -PivotTableName "Sales" -PivotRows "City" -PivotColumns "Product" -PivotData @{Gross="Sum"} -PivotTotals Rows  -Activate  -PassThru
 
 Close-ExcelPackage $excel -Show
```


So I've said PivotTotals ROWS and passthru shows it as 
```
ColumGrandTotals        : False
RowGrandTotals          : True
```

It looks like this 
![image](https://user-images.githubusercontent.com/16209593/57545289-c79cd480-7351-11e9-9063-baa3d4e8fade.png)

So its a row of totals, each one being the the total for a column.  Not adding totals to all the rows. 

![image](https://user-images.githubusercontent.com/16209593/57545031-fc5c5c00-7350-11e9-9801-836b87c40423.png)

And excel says these are totals FOR columns (not totals IN columns)  
So it does feel like it is the wrong way round :-)

**Comment by dfinke** [comment]
Got it. Yup, I switched the properties in the if stmts and it all lines up.

Time to break some eggs it seems.

**Comment by dfinke** [comment]
Do you have other changes besides that? Flipping the properties being set, is that enough? Do you want PR that code?

**Comment by jhoneill** [comment]
I think that's all that is needed code-wise (needs to be clear in the release notes and help text). Everything I've done has been committed and PR'd in so nothing more to send at the moment.
