### ISSUE TITLE
Import-Excel with 1 detail line doesn't create a proper object - adds don't work

### ISSUE THREAD

**Issue by evensolberg** [dfinke/ImportExcel#594]
Imagine 2 Excel files:

**file1.xlsx / Sheet1:**

Heading 1 | Heading 2 | Heading 3
----------- | ------------ | -----------
Item 1.1|Item 1.2|Item 1.3

**file2.xlsx / Sheet 1:**

Heading 1 | Heading 2 | Heading 3
----------- | ------------ | -----------
Item 1.1 | Item 1.2 | Item 1.3
Item 2.1 | Item 2.2 | Item 2.3

--------
**Doesn't Work:**

`$test = Import-Excel -Path file1.xlsx -WorksheetName Sheet1`
`$test += Import-Excel -Path file2.xlsx -WorksheetName Sheet1`

_Error message:_
> Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.

`$test.Length` after the first line above returns nothing.

**Works:**

`$test = Import-Excel -Path file2.xlsx -WorksheetName Sheet1`
`$test += Import-Excel -Path file1.xlsx -WorksheetName Sheet1`

_Note the reversed order!_

[file1.xlsx](https://github.com/dfinke/ImportExcel/files/3153504/file1.xlsx)
[file2.xlsx](https://github.com/dfinke/ImportExcel/files/3153505/file2.xlsx)

**Comment by scriptingstudio** [comment]
I think that the first case fails because the initial $test is not array.

**Comment by evensolberg** [comment]
That worked. Thanks! You just helped me take a 2-hour job down to 1 minute. 🥇
