### ISSUE TITLE
Importing Multiple Tables from one Sheet is Slow

### ISSUE THREAD

**Issue by brovoldt** [dfinke/ImportExcel#596]
I am working on trying to load a workbook into a database.  The workbook has multiple sheets and some of those sheets have many tables within each sheet.  I am able to pull the data the way I want however due to the size of the file of about 30MB it seems to be very slow each time I am pulling a new set of data.  Is there a more efficient way to pull multiple sheets or multiple tables per sheet to increase the speed?  

An example of the code I am using is below but this is only for 2 of the sheets in a workbook that has roughly 60 sheets.  Each table from each sheet is taking about 20-30 seconds and the number of rows is about 85 and the number of columns is about 10-12.  This example code takes about 5 minutes to complete.

$Premiums_Columns = @("IssueAge", "MNS", "MS", "MC", "FNS", "FS", "FC", "UNS", "US", "UC")
$Premiums_w_Pref_Columns = @("IssueAge", "MSPP", "MPP", "MNS", "MS", "MC", "FSPP", "FPP", "FNS", "FS", "FC", "UNS", "US", "UC")

$Sheets = @"
SheetName,PremType
100PL Prems,1
20PL Prems,2
"@ | ConvertFrom-Csv  

$dataArray = @()
$dataArray=$null 
#Premium Rates 
foreach ($Sheet in $Sheets) {
    #Bands
    $Prems_10K = Import-Excel -Path $SourceFile -WorksheetName $Sheet.SheetName -StartRow 7 -startcolumn 1 -endcolumn 10 -DataOnly -HeaderName $Premiums_Columns

    $Prems_25K = Import-Excel -Path $SourceFile -WorksheetName $Sheet.SheetName -StartRow 7 -startcolumn 11 -endcolumn 20 -DataOnly -HeaderName $Premiums_Columns

    $Prems_50K = Import-Excel -Path $SourceFile -WorksheetName $Sheet.SheetName -StartRow 7 -startcolumn 21 -endcolumn 30 -DataOnly -HeaderName $Premiums_Columns

    $Prems_100K = Import-Excel -Path $SourceFile -WorksheetName $Sheet.SheetName -StartRow 7 -startcolumn 31 -endcolumn 44 -DataOnly -HeaderName $Premiums_w_Pref_Columns

    $Prems_250K = Import-Excel -Path $SourceFile -WorksheetName $Sheet.SheetName -StartRow 7 -startcolumn 45 -endcolumn 58 -DataOnly -HeaderName $Premiums_w_Pref_Columns

    $dataArray += $Prems_250K | SELECT @{Name = 'PremiumType'; Expression = { $Sheet.PremType } }, @{Name = 'Band'; Expression = { "250000" } }, * | Where-Object { $_.IssueAge -ne $null }
    $dataArray += $Prems_10K | SELECT @{Name = 'PremiumType'; Expression = { $Sheet.PremType } }, @{Name = 'Band'; Expression = { "10000" } }, * | Where-Object { $_.IssueAge -ne $null }
    $dataArray += $Prems_25K | SELECT @{Name = 'PremiumType'; Expression = { $Sheet.PremType } }, @{Name = 'Band'; Expression = { "25000" } }, * | Where-Object { $_.IssueAge -ne $null }   
    $dataArray += $Prems_50K | SELECT @{Name = 'PremiumType'; Expression = { $Sheet.PremType } }, @{Name = 'Band'; Expression = { "50000" } }, * | Where-Object { $_.IssueAge -ne $null }  
    $dataArray += $Prems_100K | SELECT @{Name = 'PremiumType'; Expression = { $Sheet.PremType } }, @{Name = 'Band'; Expression = { "100000" } }, * | Where-Object { $_.IssueAge -ne $null } 
    
}

Is there a way to open the excel file once and reference the sheets and still pull multiple tables from a sheet?

**Comment by dfinke** [comment]
What if, your read all the data into PowerShell first? Then do select the columns you want to output? That way you read the file one time and use `Select-Object` to manipulate the results all in memory.

**Comment by jhoneill** [comment]
Really Import- should take an excel package so that if there is a need to read multiple sheets or multiple parts of a one or more sheets from a BIG file, EPPLUS doesn't open it for each one. I'm testing that now :-) Hopefully I'll have a PR in the next 24 hours

**Comment by dfinke** [comment]
Thanks! Yup, that's what I looked for and then went for the workaround.

**Comment by brovoldt** [comment]
Jhoneill - I was hoping that I could pass an excel package to Import when I started working on this and I think that would solve my problem.  Thank you

**Comment by jhoneill** [comment]
@brovoldt I've just tested and committed a change for that and @dfinke  will get a pull request for it in a minute. In the meantime you can pull the script from my git .

**Comment by dfinke** [comment]
Merged https://github.com/dfinke/ImportExcel/pull/602. Prepping to publish it.

**Comment by brovoldt** [comment]
Thank you very much for this update in my example of loading the file at this point there were 49 sets of data being pulled out of the sheets I have completed loading to this point.  

The old way ran in 21 minutes 
The new update using the excel package the same set of data was loaded in 2 minutes.  

I still have a lot more data to pull out of this spreadsheet and this will help tremendously with testing and making the process go much faster. 

Thank you again so much for the update.

**Comment by dfinke** [comment]
Thanks for the comment, so now instead of doing 3 runs in an hour, you can do 30.
