### ISSUE TITLE
Creating excel file from tab delimited or pipe delimited text file

### ISSUE THREAD

**Issue by lavnalla** [dfinke/ImportExcel#597]
I have a file Sample below

a|b|c|d|e|

I want to convert it into excel with pipe delimited. How do I do it?

I am trying the following

PS C:\Users\EliteBook 8570p> rm "c:\work\Test.xslx"; Get-Content "C:\work\test.txt" |  % {$_.replace("|","`t")} | Export-Excel "c:\work\Test.xslx"

It is giving invalid file. and If I open all tabs are gone and in one cell

**Comment by ili101** [comment]
Try this
`Import-Csv -Path C:\work\test.txt -Delimiter '|' | Export-Excel`

**Comment by lavnalla** [comment]
cool that worked thanks a bunch. how do i make 3 column text

**Comment by ili101** [comment]
@lavnalla What exactly do you mean by "how do i make 3 column text"?

**Comment by lavnalla** [comment]
when i create the excel file column c should be text format

**Comment by ili101** [comment]
@lavnalla If it being converted to a number you can prevent it by using `Export-Excel -NoNumberConversion 'C'`

**Comment by lavnalla** [comment]
ok thank you will try that
