### ISSUE TITLE
Row Grouping For Data Sheet

### ISSUE THREAD

**Issue by LaranIkal** [dfinke/ImportExcel#598]
Hello,

Thank you for the great module.

I am new to ImportExcel module.

Is there a way to do row grouping like the below link but using ImportExcel module?:
https://stackoverflow.com/questions/48352174/excel-add-row-grouping-using-powershell

I tried to look some sample of what I am asking for but I did not find anything.

I think I am asking for something like this Issue:
https://github.com/dfinke/ImportExcel/issues/107

But he seems to require a chart, I just want the data table in excel in order to add totals, based in the expanded group.

Thank you in advance.

**Comment by ili101** [comment]
Check this one https://github.com/dfinke/ImportExcel/issues/556

**Comment by LaranIkal** [comment]
Thank you so much, it is exactly what I need.
