### ISSUE TITLE
put new variable into next column

### ISSUE THREAD

**Issue by przekoz** [dfinke/ImportExcel#599]
How I can put $host in next column "B1"?
I can put all variables in one cell "A1" or A1..A2..A3

$Tab = [char]9
$Data=(Get-Date -UFormat "%Y.%m.%d")
$comp=$env:COMPUTERNAME

$ID = "$Data $Tab $comp"
$ID |   Export-excel c:\COMPUTERNAME.xlsx -WorksheetName Date -AutoSize

**Comment by dfinke** [comment]
# Create a PowerShell object, with properties

```powershell
$xlfile = "$env:temp\COMPUTERNAME.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = [PSCustomObject]@{
    Data=(Get-Date -UFormat "%Y.%m.%d")
    comp=$env:COMPUTERNAME
}

$data | Export-Excel $xlfile -AutoSize -Show
```

**Comment by uSlackr** [comment]
@przekoz If I can be so presumptive to generalize Doug's response. :-) 
Export-Excel works similar to export-csv in that we send objects to the spreadsheet that are transformed into different columns of the worksheet - one property per column.  

No need to try to navigate to a different cell to separate data,

**Comment by przekoz** [comment]
@dfinke  thanks for quick repley
@uSlackr I have similar problem in export-csv (showed metod by @dfinke  did'nt work)
```
$xlfile = "c:\temp\COMPUTERNAME.csv"
rm $xlfile -ErrorAction SilentlyContinue

$data = [PSCustomObject]@{
    Date = (Get-Date -UFormat "%Y.%m.%d")
    comp = $env:COMPUTERNAME
}

$data | Export-csv $xlfile -NoTypeInformation
```

**Comment by ili101** [comment]
@przekoz your code works for me. if you open the csv file in notepad dose it looks exactly like this?
![image](https://user-images.githubusercontent.com/6960531/58250031-15113c80-7d69-11e9-8e9b-65194aba884c.png)
If so your csv is good, the problem is probably with your version of Excel reading it wrong.
You can open Excel and go to `Data > Get Data > From File > From Text/Csv` and make sure it get the delimiter correctly (should be comma)

**Comment by przekoz** [comment]
@ili101  o'k but how i can import this csv file with cmdlet from importexcel module to xlsx like this

![Adnotacja 2019-05-23 140525](https://user-images.githubusercontent.com/23155635/58251492-112eeb80-7d64-11e9-9667-3b902ff4745c.png)

**Comment by dfinke** [comment]
# Convert the CSV data back into PowerShell Objects

```powershell
Import-csv "c:\temp\COMPUTERNAME.csv" | Export-Excel "$env:Temp\COMPUTERNAME.xlsx" -show
```

**Comment by ili101** [comment]
@przekoz  to convert csv to xlsx you can do:
`Import-Csv -Path "c:\temp\COMPUTERNAME.csv" | Export-Excel`

**Comment by przekoz** [comment]
great thanks Everyone. All works excelent
