### ISSUE TITLE
Can I add a non- columned row to a worksheet

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#600]
I use importexcel to create reports we use for compliance audits.  Auditors like some information on the report to show when & how it was generated.  I'd like to add a line or two at the top that is not part of the export data.  Thoughts on how to approach this?
I could build a custom object with the data - is there a way to export to object type to a worksheet?

\\Greg

**Comment by uSlackr** [comment]
I think I found a workable solution in one of the examples. I export the data, open the file, add rows to the top and specify data with Set-Format. 
If anyone has a idea for a better way, I'm all ears.

**Comment by dfinke** [comment]
Yes.  You can use `-PassThru` too, maybe you already are.

```powershell

$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel = gsv | Export-Excel $xlfile -StartRow 5 -PassThru -AutoSize

Set-Format -WorkSheet $excel.Sheet1 -Address a1 -Value "Hello World"
Set-Format -WorkSheet $excel.Sheet1 -Address b2 -Value (get-date).ToShortDateString()

Close-ExcelPackage $excel -Show 
```

**Comment by uSlackr** [comment]
Thanks. I need to remember that.  Since I'm generating a lot of similar reports I built a function to add the header info. 
I continue to be amazed by how powerful this package is. I jumped to PowerShell long ago, in part, because how easy import/export-csv made it to manipulate spreadsheet data,  ImportExcel brings that in spades.  
Thanks!

**Comment by jhoneill** [comment]
You can also specify -Title so you can put "Blah, blah generated so and so" 

The you want something more than one cell then the best thing is to specify -startRow and passthru, then us your own code to write the extra data you want  and close-excelPackage to save it. 
(you might even be able to create it as data and export-excel a second time into above the data)

**Comment by uSlackr** [comment]
Thanks for the help!
