### ISSUE TITLE
merge xlsx files 

### ISSUE THREAD

**Issue by przekoz** [dfinke/ImportExcel#601]
how can I merge or add one xlsx file with worksheets with other one?
file host1.xlsx:
![host1a](https://user-images.githubusercontent.com/23155635/58316447-ddab9a00-7e13-11e9-853d-16537e01a262.jpg)
![host1b](https://user-images.githubusercontent.com/23155635/58316453-e0a68a80-7e13-11e9-80ca-1dd0561a16cc.jpg)

and host2.xlsx
![host2a](https://user-images.githubusercontent.com/23155635/58316491-f6b44b00-7e13-11e9-8469-99c13164f06d.jpg)
![host2b](https://user-images.githubusercontent.com/23155635/58316505-fb78ff00-7e13-11e9-8655-89a6b5aa5472.jpg)

merge to one xlsx file with no reapeted columns names like this:
![allhost_a](https://user-images.githubusercontent.com/23155635/58316597-31b67e80-7e14-11e9-9cf4-301e407010ba.jpg)
![allhost_b](https://user-images.githubusercontent.com/23155635/58316604-34b16f00-7e14-11e9-85a3-bb76f62a65e7.jpg)

I try with merge-worksheet and copy-excelworksheet and others cmdlets with no result.

**Comment by dfinke** [comment]
```powershell
$host1 = "C:\Temp\tryMerge\host1.xlsx"
$host2 = "C:\Temp\tryMerge\host2.xlsx"
$combined = "C:\Temp\tryMerge\combined.xlsx"

rm $combined -ErrorAction SilentlyContinue

$(
    Import-Excel $host1 -WorksheetName sheet1
    Import-Excel $host2 -WorksheetName sheet1
) | Export-Excel $combined -WorksheetName Sheet1

$(
    Import-Excel $host1 -WorksheetName sheet2
    Import-Excel $host2 -WorksheetName sheet2
) | Export-Excel $combined -WorksheetName Sheet2 -Show
```

**Comment by jhoneill** [comment]
Have a look at the join-worksheet command. I built it for just this scenario.

**Comment by dfinke** [comment]
Yup, I followed the "merge" concept, forgot there was a join.

https://github.com/dfinke/ImportExcel/blob/53b63b37803d5b863630debcbb38ba06b6a9011a/Examples/JoinWorksheet/Join-Worksheet.sample.ps1
