### ISSUE TITLE
Documentation improvements for First Time User Experience

### ISSUE THREAD

**Issue by NReilingh** [dfinke/ImportExcel#605]
I wanted to raise a few suggestions for discussion relating to my first encounter with this package. Happy to work on PRs for anything within my skillset!

1. My first try after installing the module was `Import-Excel .\somefile.xls`. This failed with an exception that didn't give me a clear direction forward. I wonder if it's technically possible to recognize the incompatible file type and indicate that in the error message, or suggest the use of ConvertTo-ExcelXlsx.

2. From finding the module in the PSGallery and coming to this repo as the linked project site, I went looking for online documentation, since clicking around on a website is always a better exploratory experience than running Get-Help dozens of times. I don't necessarily know that automatically replicating PSHelp online for community projects (like in a GitHub wiki) is a solved problem, but it may be worth mulling over, considering this project provides so many commands. Reading comment-based help in source files isn't terrible, but since all of the files are at the root of the repo and not all of them are exported functions, the usability isn't great. Perhaps restructuring the repo itself would be a good idea?

3. The repo's homepage experience has a number of problems for someone looking for information on getting started:

* As mentioned, lots of files at the repo root to scroll past before you see any readme info
* Release notes go on forever. Consider putting them into a separate markdown file linked from the readme, or limiting to only the latest major version.
* The readme actually has sections for Examples and Known Issues after all of the release notes! One would usually assume that a release notes section so long must be the last section in the document, since you only need to keep scrolling if you want to go further back in time. These sections should probably be reordered so that Examples and Known Issues are first and release notes are at the end.
* Anchor links to the markdown headers for each section could be added in a contents structure near the top of the readme.

4. I would also suggest that it be conspicuously documented somewhere that .xls files are not natively supported. I couldn't find this information until I went looking for existing issues (#323). It makes perfect sense given the tooling that this code relies on, but that context isn't known to someone finding the package for the first time, and since xls files aren't going away any time soon (mostly due to old software that generates them automatically) I can see this being a source of frustration as it was for me.

**Comment by dfinke** [comment]
Thanks! PRs are welcome

**Comment by frippe75** [comment]
I'm to figure out how to open an existing workbook, target a worksheet and append a row using set-row.
Cannot get and existing file "opened". Looks like I have to use Export-Excel -Path and -Passthru
Get an error for using an existing file.

I also feel the structure of the lib somewhat awkward. 

Looks like set-row has the functionality of picking a new row if not specified. 
Maybe the module should have been PSExcel or something. I would really appreciate getting some tips on what I'm trying to accomplish. 

Thanks!

**Comment by frippe75** [comment]
Managed to get futher...


So I missed there was an Open-ExcelPackage

My first Set-Row will set "TEST" to all cells of the first available row.
The Set-Format allows me to target a particular cell but feels awkward. Maybe Set-Cell or Set-Cells where one could pass an Array to populate the range or a particular row.

What am I missing here? I need to append data to an already existing spreedsheet. Most examples are starting out deleting any existing file to create from scratch.
```
$excel = Open-ExcelPackage $popFile
$ws = $excel.Workbook.Worksheets["FR"]

Set-Row -Worksheet $ws -Value "TEST"
Set-Format -Address $ws.Cells["a10:d10"] -Value "C"
Set-CellStyle
Close-ExcelPackage $excel -Show
```

I could make a loop over my Array and use Set-Format -Address but that just feels overworked having a Excel library.

Any pointers? Thanks!

**Comment by dfinke** [comment]
https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L19

**Comment by frippe75** [comment]
Well that was easy! Thanks for the support and sorry for stealing the thread somewhat.

`$myhash | Export-Excel -Path $File -WorksheetName "FR" -Append`
