### ISSUE TITLE
Add title to Excel Spreadsheet, format it and spawn all columns.

### ISSUE THREAD

**Issue by LaranIkal** [dfinke/ImportExcel#606]
Hello,

I see there is a way to add a title to a Spreadsheet by using -Title "My title"

Is there a way to add additional formatting to the title?, showing a sample in the attached screenshot.

![TitleFormattingWish](https://user-images.githubusercontent.com/805410/58893417-c000ef00-86b5-11e9-944e-b2e452660bdc.PNG)

I am sorry if there is a way to do this formatting, I looked into the documentation but I did not see it.

Thank you and regards.

**Comment by uSlackr** [comment]
Yes, you can use the Set-Format or Set-ExcelRange commands to format the cell the title winds up in.  See some the examples for an example.

**Comment by dfinke** [comment]
Here's one way to use it.

https://github.com/dfinke/ImportExcel/blob/master/Examples/SetColumnBackgroundColor/SetColumnBackgroundColor.ps1

**Comment by jhoneill** [comment]
the command line support title bold,  title size, title background color and title pattern. If you want to change the type face, font color, apply italic or underline then you can use 
`$excel = <<your export command without -show>> -passthru `

and then either set-ExcelRange or 

`$excel.Sheet1.Cells["a1"].Style.Font.Color.SetColor("Red")`

followed by 
`close-excelPackage $excel   <<-show if you used it >>`

**Comment by LaranIkal** [comment]
Hello,

Thank you so much for all your help, I appreciate it a lot.

This is a sample of my actual code:

$f = "C:\temp\report.xlsx"
Remove-Item $f -ErrorAction Ignore

$data = @"
From,To,RDollars,RPercent,MDollars,MPercent,Revenue,Margin
Atlanta,New York,3602000,.0809,955000,.09,245,65
New York,Washington,4674000,.105,336000,.03,222,16
Chicago,New York,4674000,.0804,1536000,.14,550,43
New York,Philadelphia,12180000,.1427,-716000,-.07,321,-25
New York,San Francisco,3221000,.0629,1088000,.04,436,21
New York,Phoneix,2782000,.0723,467000,.10,674,33
"@ | ConvertFrom-Csv

$reportTitle = "Report Title"

#$reportColumns = ($data | get-member -type NoteProperty).count

$myReportData = $data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle -TitleBold -TitleSize 14 -PassThru

$workSheet = $myReportData.Workbook.WorkSheets[1]
Set-ExcelRange -Range $workSheet.Cells["A1:H1"] -BackgroundColor LightBlue
Export-Excel -ExcelPackage $myReportData

it gives me this output:
![TitleFormattingIGot](https://user-images.githubusercontent.com/805410/58927480-56fc9400-8714-11e9-8c6c-06cbc5bf79eb.PNG)

I want to merge all columns in blue and center the title.

I have been looking the docs but no clue on how to do that.

If you have some idea on how to format the title as mentioned, it would be great.

Thank you in advance.

**Comment by jhoneill** [comment]
This will do it for you  - replace the last line with these 3 . 
```
$myReportData.Workbook.Worksheets[1].cells["A1:H1"].Merge = $true
$myReportData.Workbook.Worksheets[1].cells["A1:H1"].Style.HorizontalAlignment = "Center"
Close-ExcelPackage $myReportData    
```
(you can add -show to the close command ) 
I'm not sure why I never put "merge" into Set-ExcelRange. I'll add that when I get a moment.  
@dfinke  I don't want to add any more switches to export, but do you think we should have "TitleCenter" and/or "TitleFontColor" ?

**Comment by dfinke** [comment]
Off the top of my head, maybe having something like TitleOptions makes.

**Comment by jhoneill** [comment]
Warning four dangerous words approaching:
_I've got an idea ..._

Let me work it up into some real code :-)

**Comment by LaranIkal** [comment]
Hello All,

Thank you so much for your help, now I have my report working, I just added some code to automatically get the last title column, here my final code:

$f = "C:\temp\report.xlsx"
Remove-Item $f -ErrorAction Ignore

$data = @"
From,To,RDollars,RPercent,MDollars,MPercent,Revenue,Margin
Atlanta,New York,3602000,.0809,955000,.09,245,65
New York,Washington,4674000,.105,336000,.03,222,16
Chicago,New York,4674000,.0804,1536000,.14,550,43
New York,Philadelphia,12180000,.1427,-716000,-.07,321,-25
New York,San Francisco,3221000,.0629,1088000,.04,436,21
New York,Phoneix,2782000,.0723,467000,.10,674,33
"@ | ConvertFrom-Csv

$reportTitle = "Report Title"

$myReportData = $data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle -TitleBold -TitleSize 14 -PassThru

$workSheet = $myReportData.Workbook.WorkSheets[1]

#Get title end column, considering a maximum of 78 report columns
$reportColumns = ($data | get-member -type NoteProperty).count
if( $reportColumns -le 26 ) { $titleColumnEnd = "$([char]$( 65 + ( $reportColumns - 1 ) ) )1" }
if( $reportColumns -gt 26 -And $reportColumns -le 52 ) { $titleColumnEnd = "A$([char]$( 65 + ( $reportColumns - 27 ) ) )1" }
if( $reportColumns -gt 52 -And $reportColumns -le 78 ) { $titleColumnEnd = "B$([char]$( 65 + ( $reportColumns - 53 ) ) )1" }

Set-ExcelRange -Range $workSheet.Cells["A1:$($titleColumnEnd)"] -BackgroundColor LightBlue
$myReportData.Workbook.Worksheets[1].cells["A1:$($titleColumnEnd)"].Merge = $true
$myReportData.Workbook.Worksheets[1].cells["A1:$($titleColumnEnd)"].Style.HorizontalAlignment = "Center"
Close-ExcelPackage $myReportData 


And my final output:
![TitleFormattingFinal](https://user-images.githubusercontent.com/805410/58967916-b42b3080-877a-11e9-978d-de57dc297c92.PNG)

**Comment by jhoneill** [comment]
PR will come soon but had to site around in a hospital this afternoon and spent the time making it work like this .

```
$style = New-ExcelStyle -BackgroundColor LightBlue -FontSize 14 -Bold -Range "A1:H1" -HorizontalAlignment Center -Merge
$data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle  -Style $style -sho
```

When you create a new style it takes all the same format options as Set-ExcelRange (which now also has an argument completer for font name and supports -Merge). 
Export-Excel takes one or more styles in -Style and applies them (much as it does for conditional formats etc. ).  At some stage I will add some parameter aliases - we have "foregroundColor" in one place and "fontcolor" somewhere else, so when I'm finished all the names should work in all the places.

**Comment by dfinke** [comment]
`-Style` is a single value or array?

**Comment by jhoneill** [comment]
Array :-)

**Comment by LaranIkal** [comment]
> PR will come soon but had to site around in a hospital this afternoon and spent the time making it work like this .
> 
> ```
> $style = New-ExcelStyle -BackgroundColor LightBlue -FontSize 14 -Bold -Range "A1:H1" -HorizontalAlignment Center -Merge
> $data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle  -Style $style -sho
> ```
> 
> When you create a new style it takes all the same format options as Set-ExcelRange (which now also has an argument completer for font name and supports -Merge).
> Export-Excel takes one or more styles in -Style and applies them (much as it does for conditional formats etc. ). At some stage I will add some parameter aliases - we have "foregroundColor" in one place and "fontcolor" somewhere else, so when I'm finished all the names should work in all the places.

Hello,

Thank you for your reply.

I have my code working as I said before but, anyway, I gave your code a try but I got the error below:

This is my code:
$f = "E:\tmp\report.xlsx"
Remove-Item $f -ErrorAction Ignore

$data = @"
From,To,RDollars,RPercent,MDollars,MPercent,Revenue,Margin
Atlanta,New York,3602000,.0809,955000,.09,245,65
New York,Washington,4674000,.105,336000,.03,222,16
Chicago,New York,4674000,.0804,1536000,.14,550,43
New York,Philadelphia,12180000,.1427,-716000,-.07,321,-25
New York,San Francisco,3221000,.0629,1088000,.04,436,21
New York,Phoneix,2782000,.0723,467000,.10,674,33
"@ | ConvertFrom-Csv

$reportTitle = "Report Title"

$style = New-ExcelStyle -BackgroundColor LightBlue -FontSize 14 -Bold -Range "A1:H1" -HorizontalAlignment Center -Merge
$data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle  -Style $style 


#$myReportData = $data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle -TitleBold -TitleSize 14 -PassThru
#$workSheet = $myReportData.Workbook.WorkSheets[1]
#Set-ExcelRange -Range $workSheet.Cells["A1:H1"] -BackgroundColor LightBlue
#Export-Excel -ExcelPackage $myReportData


The error I got:
New-ExcelStyle : The term 'New-ExcelStyle' is not recognized as the name of a cmdlet, function, script file, or operable program.

Anyway, thank you for your help.
