### ISSUE TITLE
finding a row

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#608]
I need to open a file and the row that contains "Results" in column B. I then plan to use that row as the start of an import.  Is there a trick I can use other than iterating through the rows?

\\Greg

**Comment by dfinke** [comment]
No tricks that I know of off the top of my head.

**Comment by jhoneill** [comment]
It's still doing an iteration but you can avoid writing a loop with 
`$ws.cells["b:b"].where({$_.value -eq "Results"}).start.row`

**Comment by DarkLite1** [comment]
If you want to import everything starting only from a specifc row you can use `StartRow`. But if you only want to import rows with a specific value in the column B I would import it all and then simply filter afterwards.

```powershell
$AllData = @(Import-Excel -Path ./MyFile.xlsx)

$AllData.Where( { $_.ColumnB -eq 'Results' }).foreach( {
    # Do your thing here
})
```

```powershell
help Import-Excel -Parameter StartRow

-StartRow <Int32>
    The row from where we start to import data, all rows above the StartRow are disregarded. By
    default this is the first row.
    When the parameters ΓÇÿ-NoHeaderΓÇÖ and ΓÇÿ-HeaderNameΓÇÖ are not provided, this row will contain the
    column headers that will be used as property names. When one of both parameters are provided,
    the property names are automatically created and this row will be treated as a regular row
    containing data.

    Required?                    false
    Position?                    named
    Default value                1
    Accept pipeline input?       false
    Accept wildcard characters?  false
```

**Comment by uSlackr** [comment]
Yours is cleaner than the solution I built.
The issue I dealing with is this sheet has three different “tables” in it and the first is offset a few lines.

My first cut hardwires the offsets.  Future iterations will look for them.

Function Find-Start{
              #returns header row of RT scan analysis host data
    $temp = import-excel $args[0] -startrow $ControlTbl -startcolumn 2
    $i = 0
    ForEach ($line in $temp) {
        if ($($line."control ID") -eq "Results"){
                #return [int]$i + $ControlTbl + $ResultsTbl
                $s = $i
                #write-host $s
                break
            } else {
                $i +=1}
        }
    $temp = $null
    $startrow = [int]$s + $ControlTbl + $ResultsTbl
    return $startrow

\\Greg

**Comment by uSlackr** [comment]
Thanks for the tip.
The issue is that there are multiple tables in the sheet.  The startrow of the table I need varies depending on the amount of data in other tables.  So I need to find that starting place before I import.


\\Greg

________________________________

**Comment by dfinke** [comment]
Another way to skin the cat. 

### The setup

```powershell
$xlfile="$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

ConvertFrom-Csv @"
Region,Item,TotalSold
North,pear,49
West,peach,42
East,kiwi,40
East,melon,76
West,apple,59
East,melon,22
East,orange,50
West,avocado,72
North,screwdriver,39
South,orange,41
"@ | Export-Excel $xlfile
```

### Get Row

```powershell
$data=Import-Excel $xlfile
for ($i = 0; $i -lt $data.count; $i++) {
    if($data[$i].Item -eq "kiwi") {$i}
}
```

**Comment by DarkLite1** [comment]
@dfinke I like getting the kiwi row :)

**Comment by uSlackr** [comment]
> It's still doing an iteration but you can avoid writing a loop with
> `$ws.cells["b:b"].where({$_.value -eq "Results"}).start.row`

I'm using this over my solution. It has the benefit of **not** relying on the structure of tables in the worksheet. It does require "Results" to be in column b but it is several less things that can change (in my particular data).
Thanks for the help.

**Comment by jhoneill** [comment]
@uSlackr  - if you don't know for sure that a particular property was placed in column b you can use a similar trick with cells["1:1"] to find the heading you want in the top row.  It's not _too_ hard to convert the address of the matching cell to B:B or whatever.

**Comment by uSlackr** [comment]
Understood. At this point, searching column B is the optimal approach. I'll revisit if the data changes.

**Comment by dfinke** [comment]
```powershell
PS C:\> 24..29 | Get-ExcelColumnName

ColumnNumber ColumnName
------------ ----------
          24 X
          25 Y
          26 Z
          27 AA
          28 BA
          29 CA
```

**Comment by DarkLite1** [comment]
On a side note, it's always better to work with consistent data. That's true not only in PowerShell but also in Excel. That's why I encourage people to use a column only for what it's meant for. /rantmodeoff
