### ISSUE TITLE
Next free line in existing document?

### ISSUE THREAD

**Issue by CptWindows** [dfinke/ImportExcel#609]
hi guys,

i just do some Active Directory evaluations with PS and now started to make some excel exports.
Now I want to do a yearly evaluation based on a script that runs once in a month.

Is it possible to add a new line on an existing document? like on this image:
![grafik](https://user-images.githubusercontent.com/13573595/59245973-1a043600-8c1b-11e9-88d2-213c8b08bf20.png)

Maybe someone could help me with some example code.

Thank you,
Michi

**Comment by dfinke** [comment]
This may help. 

https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L19

**Comment by CptWindows** [comment]
> 
> 
> This may help.
> 
> https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L19

Thank you 👍
