### ISSUE TITLE
Index sheet with link - Enhancement

### ISSUE THREAD

**Issue by DillyBabu** [dfinke/ImportExcel#61]
Hi,
It would be nice if export-excel function can create a Index page in sheet 1(Ascending order) with links to other excel sheets of the same workbook.

Thanks.

**Comment by dfinke** [comment]
Could you provide an example of what you mean?

**Comment by DillyBabu** [comment]
In Excel we have Insert -> HyperLink -> Place In this document 
I have attached a sample FYR. Here each department as seperate sheet is in ascending order and a the first page placed as Index page.
Thank you
![image](https://cloud.githubusercontent.com/assets/16417357/12111936/34539fec-b3bf-11e5-81e6-c8031c79dd26.png)

**Comment by dfinke** [comment]
Check out https://github.com/dfinke/ImportExcel/blob/master/Examples/SpreadsheetCells/HyperLink.ps1

You can import data into a sheet using the =HyperLink formula. 
The text is clickable.

Unfortunately, additional code is needed to underline the text and turn it blue. This is under investigation. 

If you can figure out how to do that part, let me know and I'll add it in.

**Comment by DillyBabu** [comment]
Hi
For getting all sheet names I used the below code. 

function Get-ExcelsheetNames {
    param(
        [Alias("FullName")]
        [Parameter(ValueFromPipelineByPropertyName=$true, ValueFromPipeline=$true, Mandatory=$true)]
        $Path,
        [Alias("Sheet")]
        $WorkSheetname=1
        )
    Process {

        $Path = (Resolve-Path $Path).Path
        write-debug "target excel file $Path"

        $stream = New-Object -TypeName System.IO.FileStream -ArgumentList $Path,"Open","Read","ReadWrite"
        $xl = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $stream

        $workbook  = $xl.Workbook

        $worksheet=$workbook.Worksheets.Name
        return $worksheet
        }
    }
    $AllSheetNames = Get-ExcelsheetNames -Path D:\Test\test.XLSX 
    #Till here it works fine.
    $AllSheetNames | Export-Excel -WorkSheetname Index -Path D:\Test\test.XLSX

But I am not able to add the content to existing excel sheet.
I am getting the following error:

Export-Excel : Exception calling "Save" with "0" argument(s): "Error saving file D:\Test\test.XLSX"

Thanks..

**Comment by dfinke** [comment]
It looks like you need to close the file and stream before piping to Export-Excel

**Comment by DillyBabu** [comment]
Hi 
If possible, can you provide the code to make a cell to link a worksheet instead of an URL( as given in your link). Color and Underline is not needed for me.
I tried, but i can only add the Index sheet but not able to do it as clickable

Thanks

**Comment by dfinke** [comment]
Found this but have not tried:

`=HYPERLINK("[C:\Users\osknows\Desktop\Book2.xlsm]Sheet3!B4","CLICK HERE")`
http://stackoverflow.com/questions/5807556/excel-hyperlink-to-different-workbook-and-specific-worksheet

This may work:
`=HYPERLINK("Sheet3!B4","CLICK HERE")`

**Comment by DillyBabu** [comment]
Hi Doug,
I am able to modify each cell with the following script. But I am struggling to iterate through each row to apply this format

$FullName = "C:\temp\temp.xlsx"
$xl = New-Object OfficeOpenXml.ExcelPackage $FullName
$workbook = $xl.Workbook
$worksheet=$workbook.Worksheets[1]

$worksheet.Cells["A2"].Style.Font.Color.SetColor("Blue")
$worksheet.Cells["A2"].Style.Font.UnderLine = $true
$worksheet.Cells["A2"].Formula = '=HYPERLINK("[.\]Admin!A1","Admin")'

$worksheet.Cells["A3"].Style.Font.Color.SetColor("Blue")
$worksheet.Cells["A3"].Style.Font.UnderLine = $true
$worksheet.Cells["A3"].Formula = '=HYPERLINK("[.\]Audit!A1","Audit")'

$xl.Save()

**Comment by dfinke** [comment]
Try using a `#` instead of `[.]`

```powershell
$f="C:\Temp\testlink.xlsx"

rm $f -ErrorAction Ignore

$(
    New-PSItem '=HYPERLINK("#ps!A1","GetProcess")' (echo Index ' ')
    New-PSItem '=HYPERLINK("#gsv!A1","GetService")' 
) | Export-Excel $f -WorkSheetname index 

ps|select Company, Handle | Export-Excel $f -WorkSheetname ps 
gsv| Export-Excel $f -WorkSheetname gsv -Show
```

**Comment by freedbygrace** [comment]
`Clear-Host

#Import required module(s)
    Try
        {
            Import-Module -Name "PSExcel"
        }
    Catch
        {
            If (!(Get-PackageProvider -ListAvailable | Where-Object {$_.Name -eq "NuGet"})) {Install-PackageProvider -Name "NuGet" -Scope AllUsers -Force -ErrorAction Stop -Verbose}
            Install-Module -Name "PSExcel" -Scope AllUsers -Force -Verbose
            Import-Module -Name "PSExcel" -Force
        }

$Workbook = $Null

$WorkbookExportPath = "$([Environment]::GetFolderPath("Desktop"))\Reports\ExportXLSX_$((Get-Date -Format "yyyyMMdd_HHmmss")).xlsx"

$WorkbookExportPathParent = Split-Path -Path $WorkbookExportPath -Parent

If (!(Test-Path -Path $WorkbookExportPathParent)) {New-Item -Path $WorkbookExportPathParent -ItemType Directory -Force -Verbose | Out-Null}

$Workbook = New-Excel -Path "$($WorkbookExportPath)"
                       
                        ### Begin Create any powershell object variables here, and prefix the variable name with "XLSX_" and the rest will be handled ###

$XLSX_Disks = Get-Disk | Select-Object -Property FriendlyName, DiskNumber, PartitionStyle, FirmwareVersion, OperationalStatus
$XLSX_Partitions = Get-Partition | Select-Object -Property DiskNumber, PartitionNumber, DriveLetter, GUID, IsBoot, Size
$XLSX_Volumes = Get-Volume | Select-Object -Property DriveLetter, FileSystem, FileSystemLabel, HealthStatus, DriveType, FileSystemType, Path

################################################################################################################################################################################################

$ObjectsToExport = Get-Variable -Name "XLSX_*"

ForEach ($Object In $ObjectsToExport)
    {
        $Workbook = New-Excel -Path "$($WorkbookExportPath)"
        Export-XLSX -Excel $Workbook -InputObject ($Object.Value) -WorksheetName "$($Object.Name.Split('_')[1])" -Table -TableStyle Light19 -Force -AutoFit
    }

$Workbook = New-Excel -Path "$($WorkbookExportPath)"

ForEach ($Item In $Workbook)
    {
        ForEach ($Worksheet In $Item.Workbook.Worksheets)
            {
                $FormatSheets_001 = $Item | Get-Worksheet -Name "$($Worksheet.Name)" | Format-Cell -Header -Bold $True -Underline $True -HorizontalAlignment Center -Size 14 -Autofit -AutofitMinWidth 60 -Passthru
                $FormatSheets_002 = $Item | Get-Worksheet -Name "$($Worksheet.Name)" | Format-Cell -StartRow 2 -HorizontalAlignment Center -Size 12 -Autofit -AutofitMinWidth 60 -Passthru

                $Cells = $Worksheet.Cells["$($Worksheet.Cells.Address)"]

                $CellsWithHyperlinks = $Cells | Where-Object {($_.Value -match "(http[s]?|[s]?ftp[s]?)(:\/\/)([^\s,]+)")}

                ForEach ($Cell In $CellsWithHyperlinks)
                    {
                        $SetTextColor = $Cell.Style.Font.Color.SetColor("Blue")
                        $UnderlineText = $Cell.Style.Font.UnderLine = $True
                        $SetCellFormula = $Cell.Formula = "=HYPERLINK(`"$($Cell.Value)`",`"$($Cell.Value)`")"
                    }
            }
    }

Save-Excel -Excel $Workbook -Close -Verbose

Try {Start-Process -FilePath "Excel.exe" -ArgumentList "`"$($WorkbookExportPath)`"" -WindowStyle Maximized} Catch {}`

Hope this helps! I spent a decent amount of time on this because I needed to use this for another project. I made it generic enough for it to work without modification.

**Comment by freedbygrace** [comment]
a PR?

**Comment by dfinke** [comment]
Yeah, pull request. Fork the code, do a checkout, add your changes, check it back in and then do a a PR (pull request).

**Comment by jhoneill** [comment]
Saw this and added a couple of lines to the recently added hyperlink handling, excel seems to set the links up as XL://internal/<address>
So you can now have 
`XL://internal/WorksheetName!A1` - which displays the link as `WorksheetName` (A1 is handled differently from other addresses)
`XL://internal/WorksheetName!E419` - which displays the link as `WorksheetName!E419`
`XL://internal/RangeName` - which displays the link as `RangeName`


So `"XL://internal/Sheet!A1", XL://internal/Sheet2!A1"     | export-excel -title "Index" …. `

**Comment by freedbygrace** [comment]
Yes my mistake!

**Comment by dfinke** [comment]
@freedbygrace no problem, improves this module. BTW, @RamblingCookieMonster initially forked/used my approach, then chatted and `ImportExcel` moved forward.
