### ISSUE TITLE
duplicated row invalidates file

### ISSUE THREAD

**Issue by Kmdkca** [dfinke/ImportExcel#611]
If the sheet have multiple columns with the same name, the add-PivotTable invalidates the file, even if they aren't used for the pivot table.
repro step:
Add col1, col2, col1, col3 to the same sheet
$temp = Open-ExcelPackage C:\Temp\test.xlsx -Verbose
Add-PivotTable -PivotTableName sheet1 -SourceWorkSheet sheettest -PivotRows col2 -PivotColumns col3 -ExcelPackage $temp
Close-ExcelPackage $temp -SaveAs C:\Temp\outtest.xlsx
Open file in excel

**Comment by jhoneill** [comment]
When I do this 
```
$data1 = convertfrom-csv @"
col1, col2
London,UK
Paris,France
"@

$data2 = convertfrom-csv @"
col1, col3
London,Rain
Paris,Sun
"@

del -ErrorAction SilentlyContinue "$env:Temp\test.xlsx"
$data1 | export-excel -Path "$env:Temp\test.xlsx" -WorksheetName sheettest

$data2 | export-excel -Path "$env:Temp\test.xlsx" -WorksheetName sheettest -StartColumn 3 

$temp = Open-ExcelPackage "$env:Temp\test.xlsx"
Add-PivotTable -PivotTableName sheet1 -SourceWorkSheet sheettest -PivotRows col2 -PivotColumns col3 -ExcelPackage $temp
Close-ExcelPackage $temp -Show

```
It opens OK and the pivot table adds a "2" the second "Col1" 
![image](https://user-images.githubusercontent.com/16209593/59349309-3e423e80-8d11-11e9-9866-621e5d43070d.png)

It may be - although it seems unlikely - that some versions of Excel can fix the duplicate name at load time. The way the table is created hasn't changed in newer versions so it isn't that. We could add a check for duplicate names.  But it might be that something else is causing the problem for you - what do you get with my sample code ? 

`Add-PivotTable -PivotTableName sheet1 -SourceWorkSheet sheettest -SourceRange "B1:D3 ... ` would exclude the first col1 if that helps

**Comment by Kmdkca** [comment]
Hi

Your example works fine.
However, my file fails. See attached sample and output
When I open the output I get this:
[cid:image005.jpg@01D521AF.3C4FBDF0]
Click yes
[cid:image006.jpg@01D521AF.3C4FBDF0]
My code:
$temp = Open-ExcelPackage C:\Temp\test.xlsx
Add-PivotTable -PivotTableName PT -SourceWorkSheet Sheet1 -PivotRows col3 -PivotColumns col4 -ExcelPackage $temp
Close-ExcelPackage $temp -SaveAs C:\Temp\testout.xlsx -Show

Using Excel 32bit 16.0.11601.20174

Your workaround is not that usable as the duplicated columns are in the middle of the others.

Thanks for a great library
Kim

**Comment by jhoneill** [comment]
I get the same as you and I'm on 64 bit excel, and slightly newer build. 
And it's not that your sheet only had one row of data and mine had 2 because I tested adding a row to yours. Still fails.  
That's a puzzle 
I like puzzles ... let me see what else it might be

**Comment by jhoneill** [comment]
If I copy your data into a new sheet , it all works. 
If I fix the column names,  add a second row of data, or even copy and paste my test data into your sheet it fails. 
I don't know what the issue but there seems to be something about that file. 
Can you see if you get the same - copy the data out of the test.xlsx you uploaded paste into a new file and see if the problem goes away ?

**Comment by Kmdkca** [comment]
This is freaking weird. 
If i create a new file from the blank template, even with unique headers, I cannot do the Add-PivotTable function without corrupting the file.
I can modify the cell values, without issues. e.g. $temp.Workbook.worksheets["Sheet1"].Cells["E2"].Value = "test"
The original excel file, was an export from a supportsystem, and if I fixed the headers to be unique that file worked fine with the Add-PivotTable
