### ISSUE TITLE
How-to: Import an Excel Table

### ISSUE THREAD

**Issue by frippe75** [dfinke/ImportExcel#612]
Import-Excel does not seem to support importing of Excel Tables??

I have a sheet containing multiple tables. And the keep moving around (for reasons I cant controll) so I can address the import using cell addresses.

Any tips?

**Comment by dfinke** [comment]
I had played around with Tables, here is a script, not sure if it still works.

https://gist.github.com/dfinke/33758a313a990a5b84850e0fc51e42d7

**Comment by frippe75** [comment]
Thanks! Will go ahead a try!

**Comment by jhoneill** [comment]
@dfinke  it would be pretty easy to add a parameter for a named range or table and  set start/end row/column to that range ... one for the enhancements list perhaps. (Although since I haven't added pester tests for the last few enhancements maybe I should get those done first!)

**Comment by dfinke** [comment]
Yes, that's where I was headed when I worked up that example a few months back. Was waiting to see how it panned out being useful. 

I've got a PR I was going to ask you to review, waiting to add unit tests first. It's there if you want to look, it adds trendlines to graphs.
