### ISSUE TITLE
Feature Request - Include support for trend lines on excel charts

### ISSUE THREAD

**Issue by BlackV** [dfinke/ImportExcel#614]
Working with a line graph

`$chartDef = New-ExcelChartDefinition -ChartType Line -XRange start -YRange duration -NoLegend -Width 1000 -Height 600 -Column 7`

Is there a way to also get trending added to that graph

**Comment by dfinke** [comment]
Got the basics working https://github.com/dfinke/ImportExcel/tree/EnableTrendLine
Need to write tests and try it out some more.

You can grab a copy if you want.
