### ISSUE TITLE
Exporting a cell with =hyperlink("x";"y") formula doesn't work

### ISSUE THREAD

**Issue by ManuCard** [dfinke/ImportExcel#618]
$Test_data = @"
Link
=HYPERLINK("WORKS")
=HYPERLINK("DOESNT";"WORK")
"@ | ConvertFrom-Csv

$Test_data | Export-Excel -now

First formula works.
Second one does not. I haven't found any way to export my data using export-excel. I have to resort to dropping my data into a .CSV file and opening that in excel. That gives no problem with the HYPERLINK formula when it has two parameters.

**Comment by dfinke** [comment]
@jhoneill Just wondering, I think I remember some "data scrubbing" around hyperlinks, off the top of your head, is that in play here?

**Comment by dfinke** [comment]
Not familiar with that syntax.

There are a few ways to create hyperlinks/

```powershell
[PSCustomObject]@{
    Google='=Hyperlink("http://google.com", "Google")'
    MSFT='=Hyperlink("http://microsoft.com", "microsoft")'
} | Export-Excel 
```

**Comment by jhoneill** [comment]
By phone ....

Thought I replied 
Problem is the use of semicolons.
In some languages (e.g. French) the list separator is semi colon (;) and that is what excel displays. Internally excel uses comma (,) and that is what you need to write to the xlsx. If you import from csv Excel may follow local language. Epplus never does

**Comment by ManuCard** [comment]
Thanks. 
Using a comma works. That resolves my issue.
