### ISSUE TITLE
Set-ExcelColumn -Hide troubles (Null array)

### ISSUE THREAD

**Issue by coltsy** [dfinke/ImportExcel#620]
Having an issue here trying to hide a particular column within a worksheet. I am piping the contents of an existing .csv on my computer into the `Export-Excel` function which is all working fine, but I am having trouble with some formatting. All I want to do is hide column 6 (F) on the worksheet that I am generating in the workbook. 

Relevant code is as follows: 
```
$importCsv = Import-Csv -Path $csvPath -Delimiter ','
$pkg = $importCsv | Export-Excel -Path $spreadsheetPath -WorksheetName "June 2019" -TableName table -TableStyle Light4 -FreezeTopRow
$wsData = $pkg.Workbook.Worksheets["June 2019"]
Set-ExcelColumn -Worksheet $wsData -Column 6 -Hide
```
When I run the script the spreadsheet gets generated with all my data, the table is formatted how I like, it all goes into a sheet called "June 2019", etc. but the single column does not hide and I get the following error:
```
Cannot index into a null array.
+ $wsData = $pkg.Workbook.Worksheets["June 2019"]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray

Set-ExcelColumn : Cannot bind argument to parameter 'Worksheet' because it is null.
+ Set-ExcelColumn -Worksheet $wsData -Column 6 -Hide
+                            ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Set-ExcelColumn], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Set-ExcelColumn
```

Any help is greatly appreciated.

**Comment by dfinke** [comment]
Looks like you need `-PassThru` on the `Export-Excel`

**Comment by coltsy** [comment]
Thanks for the suggestion, I tried using `-PassThru` but nothing happens at all when I run the script with that switch. Perhaps it is because I am running on a Mac? I have not been able to test it on Windows yet. Wondering if that might be the issue.

**Comment by dfinke** [comment]
Does the error go away when you use `-PassThru`? If so, yes, could be an issue on the Mac.

**Comment by coltsy** [comment]
Yes, there is no error at all when I run it with `-PassThru`, the file just does not write. Not going to worry about it - thanks again.
