### ISSUE TITLE
Is testing $PSBoundParameters needed?

### ISSUE THREAD

**Issue by Liturgist** [dfinke/ImportExcel#623]
This is not an "issue," but more of a general coding question. In the `Export-Excel` function, I see the following.
```
if  ($PSBoundParameters.ContainsKey("TitleBold")) {
    #Set title to Bold face font if -TitleBold was specified.
    #Otherwise the default will be unbolded.
    $ws.Cells[$Row, $StartColumn].Style.Font.Bold = [boolean]$TitleBold
}
```
Is there something important about testing `$PSBoundParameters` to see if the key was explicitly specified? Why not just use:
```
$ws.Cells[$Row, $StartColumn].Style.Font.Bold = [boolean]$TitleBold
    or
if ($TitleBold) { $ws.Cells[$Row, $StartColumn].Style.Font.Bold = [boolean]$TitleBold }
```

**Comment by ili101** [comment]
Well using it can potentially provide 2 benefits.
In your example the original code let you set it to: bold, non-bold or leave it as is (for example if you are editing an existing document). Without it you only get bold and non-bold options.

The second benefit is if you have a parameter that can take a number like "TableStyle"
If the value provided is 0 (Style index 0) and you do `if ($TableStyle)` the provided parameter will be ignored as 0 is $false and you will not set the style.
If you just use the value without checking it first and it's not provided it will crash.
