### ISSUE TITLE
Set-Format -Range for entire worksheet?

### ISSUE THREAD

**Issue by Liturgist** [dfinke/ImportExcel#624]
I want to set the -FontName and -FontSize for the entire spreadsheet.

How do I specify a -Range for the entire worksheet? Do I need to specify "A1:XFD1048576"?

I know that I will only use columns A-H. Should I specify "A1:H1048576"?

If only 300 rows are used in a spreadsheet, is there any added overhead if Set-Format is used on rows 301-1048576?

**Comment by dfinke** [comment]
## Try

This works, a little too much. Looks like it sets the correct range and a few cells around the Range. 
Will look at what is happening there.

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue


$excel = ConvertFrom-Csv @"
Region,Item,TotalSold
West,drill,92
East,saw,78
North,nail,16
South,screws,10
North,apple,21
North,orange,11
South,pear,47
East,hammer,35
West,peach,75
East,hammer,7
"@ | Export-Excel -Path $xlfile -PassThru

$ws = $excel.Workbook.Worksheets["Sheet1"]
$dimension = $ws.Dimension
$address=$dimension.address

Set-Format -WorkSheet $ws -Range $address  -FontName 'Comic Sans MS' -FontSize 12

Close-ExcelPackage -ExcelPackage $excel -Show
```

**Comment by dfinke** [comment]
## Update

I don't know how to programmatically get the max cols/rows of a sheet. Here is how you can get the `used` region.

I also set the entire sheet to a font/size. The file size was no bigger and the sheet opened quickly no problem. My guess is Excel saves this info but only renders/operates on it for cells with "data". 

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel = ConvertFrom-Csv @"
Region,Item,TotalSold
West,drill,92
East,saw,78
North,nail,16
South,screws,10
North,apple,21
North,orange,11
South,pear,47
East,hammer,35
West,peach,75
East,hammer,7
"@ | Export-Excel -Path $xlfile -PassThru

$ws = $excel.Workbook.Worksheets["Sheet1"]
$dimension = $ws.Dimension
$address=$dimension.address
#$address="A1:XFD1048576"
Set-Format -WorkSheet $ws -Range $address  -FontName 'Comic Sans MS' -FontSize 12
Close-ExcelPackage -ExcelPackage $excel -Show
```

**Comment by Liturgist** [comment]
Thanks, I will try that.

I would still like to know if there is additional overhead for sheets that have attributes for cells outside the range used.

**Comment by jhoneill** [comment]
Excel stores each format used in the sheet and then says "This cell uses this format". If you specify an over-size range the XML will hold entries for each cell with the style number.
To verify this change the last two lines to 
```
Set-ExcelRange -Range "A1:J20" -WorkSheet $ws -Bold
Close-ExcelPackage -ExcelPackage 
```
Then change the file extension to .ZIP open the zip file and look in xl\worksheets\ and look at sheet1.xml.

If to you want to change the normal style for the whole workbook use 
`$excel.Workbook.styles.NamedStyles[0].Style.WrapText = $true `

**Comment by dfinke** [comment]
@jhoneill  Interestingly, I set the entire sheet to use `-FontName 'Comic Sans MS' -FontSize 12`. The size of the xlsx file did not really increase from a "vanilla" xlsx.

**Comment by jhoneill** [comment]
hmm. It appears there is  special handling for the whole sheet.  

If I do 10 rows x 3 columns and apply the style to 20 rows x 10 columns I can see 200 cells in the XML, but if I apply it to the maximum area there are only 30 cells in the XML. 

If I add another sheet that is in calibri, so it hasn't changed the default style for the workbook, and I can't see where there is a default for one sheet of the work book (either on the EPPlus object or poking around in the the XML), but that is definitely the effect that I see.

**Comment by dfinke** [comment]
Kind of makes sense for the whole sheet, I was guessing they'd use a flyweight pattern to reduce the footprint.

**Comment by dfinke** [comment]
Kind of makes sense for the whole sheet, I was guessing they'd use a flyweight pattern to reduce the footprint.
