### ISSUE TITLE
How to insert a row or column?

### ISSUE THREAD

**Issue by Liturgist** [dfinke/ImportExcel#625]
How can I insert a new row or column?

I have an existing .xlsx to use as a template. On a single worksheet, there are items in groups. The number of rows needed depends on the data to be put onto the spreadsheet.

The entire worksheet could be constructed, but I would rather leave the pretty group headers and annotations in an existing .xlsx where they are easily changed.

ImportExcel is fantastic, BTW!

**Comment by Liturgist** [comment]
In ImportExcel\Examples\CustomReporting\CustomReport.ps1 I found something promising.
`$sheet1.InsertRow(1, 1)`
I will close this and give that a try.

**Comment by dfinke** [comment]
https://github.com/dfinke/ImportExcel/blob/master/Examples
https://github.com/dfinke/ImportExcel/blob/master/Examples/CustomReporting/CustomReport.ps1#L37
