### ISSUE TITLE
Copy existing worksheet?

### ISSUE THREAD

**Issue by Liturgist** [dfinke/ImportExcel#626]
I have an existing .xlsx file that I am using as a template. It is read with `Open-ExcelPackage` and I can make changes and write it using `Copy-ExcelWorksheet`. However, I can only write one (1) worksheet. I need to be able to duplicate other worksheets in the existing workbook, then make changes to them. It appears that I can make the changes, but they are never written out to the new .xlsx file. Only the first worksheet is in the newly created .xlsx file.

The error message is: "WARNING: Could not write to sheet 'SSIS 1' in the destination workbook"

```
Import-Module -Name ImportExcel
Add-Type -Assembly System.Drawing

$e = Open-ExcelPackage 'C:\path\to\template\file.xlsx'
$ws = $e.workbook.Worksheets['Overview']
Set-Format -WorkSheet $ws -Range "D8" -Bold -Value 'My Name'
# Set-Format
# insert rows
# etc...

# Copy the existing worksheet 'SSIS Package' to a new worksheet 'SSIS 1' ???
#
$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname "SSIS 1" `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['SSIS Package'])

$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname 'SSIS 2'

Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'Overview' `
    -DestinationWorkSheet 'Overview' -DestinationWorkbook 'C:\src\xl\t2.xlsx'

# the next two fail
#
Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'SSIS Package' `
    -DestinationWorkbook 'C:\src\xl\t2.xlsx' -DestinationWorkSheet 'SSIS 1'
### WARNING: Could not write to sheet 'SSIS 1' in the destination workbook

Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'SSIS Package' `
    -DestinationWorkbook 'C:\src\xl\t2.xlsx' -DestinationWorkSheet 'SSIS 1'
### WARNING: Could not write to sheet 'SSIS 1' in the destination workbook
```

**Comment by dfinke** [comment]
Not sure.

Curious, why not copy 'C:\path\to\template\file.xlsx' to a new file 'C:\src\xl\t2.xlsx', open the new one and operate on that?

**Comment by Liturgist** [comment]
I could copy the template workbook to a new workbook file. But, I still need to copy a worksheet inside the workbook to a new worksheet inside it. Then, save the entire workbook with all worksheets.

**Comment by jhoneill** [comment]
When the failure message comes back, what does $error[0] report. I tried a test and the sheet I was copying had tables and named ranges in it, and if these already exist in the the destination, there error is 
`Exception calling "Add" with "2" argument(s): "Part already exist" `

If I copy a sheet which doesn't have tables and ranges everything works. So I think this is a limitation in EPPLus exposed by the data.

**Comment by Liturgist** [comment]
I have tried to whittle this down to a simple example. The "Master.xlsx" file contains two (2) worksheets; "Overview" and "SSIS Package." I am expecting that the code will read in the "Master.xlsx" file, copy the "SSIS Package" worksheet twice, and write the result into "t2.xlsx." The result has only one (1) worksheet: "Overview."

[Master.xlsx](https://github.com/dfinke/ImportExcel/files/3368870/Master.xlsx)

```
$xlfile = "C:\src\xl\t2.xlsx"
if (Test-Path -Path $xlfile) { Remove-Item -Path $xlfile -Force }

Import-Module -Name ImportExcel
$e = Open-ExcelPackage 'C:\src\xl\Master.xlsx'

$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname "SSIS 1" `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['SSIS Package'])

$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname "SSIS 2" `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['SSIS Package'])

# At this point, $e shows that there are four (4) worksheets.
# [DBG]: PS C:\Users\liturgist> $e.Workbook
# Worksheets           : {Overview, SSIS 1, SSIS 2, SSIS Package}

Copy-ExcelWorkSheet -SourceWorkbook $e -DestinationWorkbook $xlfile

# The t2.xlsx file has only one (1) worksheet; Overview.
```

**Comment by jhoneill** [comment]
Copy-Excel Worksheet only copies one sheet, this
`Copy-ExcelWorkSheet -SourceWorkbook $e -DestinationWorkbook $xlfile`
Will copy the first sheet in $e to $xlfile. 

If I add 
`Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'SSIS Package' -DestinationWorkbook $xlfile -DestinationWorkSheet 'SSIS 1'
`
That works.

**Comment by Liturgist** [comment]
Many thanks. Making multiple `Copy-ExcelWorkSheet` calls is working.

Perhaps... `Copy-ExcelWorkBook` that would write everything. Or, add a `-WriteAllWorkSheets` parameter to `Copy-ExcelWorkSheet`. Would either of those be good?

**Comment by jhoneill** [comment]
Currently it needs a loop to copy everything.  Probably allowing wild cards in the source name if no destination name is given would be the best way. I'll see if it is practical ....

**Comment by Liturgist** [comment]
The problem appears to be content in the master template spreadsheet.
[m3.xlsx](https://github.com/dfinke/ImportExcel/files/3370822/m3.xlsx)
[m4.xlsx](https://github.com/dfinke/ImportExcel/files/3370824/m4.xlsx)

```
$xlfile = "C:\src\xl\t2.xlsx"
if (Test-Path -Path $xlfile) { Remove-Item -Path $xlfile -Force }

Import-Module -Name ImportExcel
$e = Open-ExcelPackage 'C:\src\xl\m3.xlsx'

$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname "SSIS 1" `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['SSIS Package'])

$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname "SSIS 2" `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['SSIS Package'])

# At this point, $e shows that there are four (4) worksheets.
# [DBG]: PS C:\Users\pwatson2> $e.Workbook
# Worksheets           : {Overview, SSIS 1, SSIS 2, SSIS Package}

Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'Overview' -DestinationWorkbook $xlfile

Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'SSIS 1' -DestinationWorkbook $xlfile
Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'SSIS 2' -DestinationWorkbook $xlfile

```
Running this code on m3.xlsx produces the following messages. And, the "SSIS 1' and 'SSIS 2" worksheets are not in the resulting t2.xlsx file.

```
[DBG]: PS C:\src\xl>
WARNING: Could not write to sheet 'SSIS 1' in the destination workbook
WARNING: Could not write to sheet 'SSIS 2' in the destination workbook

```
However, running the code above with m4.xlsx as the master template, it appears to work as expected. The only difference is that m4.xlsx has "SSIS Package" sheet line 8 deleted. This has a drop-down list box. Could that be a problem?

**Comment by jhoneill** [comment]
Definitely something weird in the data  - if I select A8:B8  in M3, do clear all and save it, everything is fine. As is, EPPlus gives an error on saving.

**Comment by Liturgist** [comment]
How can I do a "clear all" in code? The only "clear" I can find in the examples is the `-ClearSheet` switch.

**Comment by jhoneill** [comment]
```
$excel = Open-ExcelPackage C:\Users\mcp\AppData\Local\Temp\Master.xlsx                                                                                                                                                   
$ws = $excel.'SSIS Package'                                                                                                                                                                                              
$ws.Cells["a8:b8"].Clear()  
```
Will do it for you. `Set-ExcelRange` really should have a `-clear` option... 

I have posted an updated version of copy-excelWorksheet on my repo, this version lets you pipe sheets in e.g.
`$excel.workbook.worksheets | copy-excelWorksheet -destinationWorkbook foo.xlsx `

I might try to add -clear to set-excel range and then send @dfinke  a PR for both :-)

**Comment by dfinke** [comment]
That's clear.

**Comment by Liturgist** [comment]
Did a PR ever get merged in for this?

**Comment by Liturgist** [comment]
I am trying again. I was on ImportExcel 6.2.2 before. Now I am using 7.1.0. Here is a very simple example. It does not produce the same failures as before, but it does fail. This opens a spreadsheet with one (1) worksheet (Sheet1). It then tries to add and copy the one worksheet to two (2) others (Sheet2 and Sheet3). Is there something I am not doing correctly?

```
Import-Module -Name ImportExcel
#Add-Type -Assembly System.Drawing

$infile = 'C:/src/xl/filein002.xlsx'
$outfile = 'C:/src/xl/fileout002.xlsx'
if (Test-Path -Path $outfile) { Remove-Item -Path $outfile }

$e = Open-ExcelPackage $infile
$ws = $e.workbook.Worksheets['Sheet1']

# Copy the existing worksheet 'Sheet1' to a new worksheets
# 'Sheet2' and 'Sheet3'
#
$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname "Sheet2" `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['Sheet1'])

$null = Add-WorkSheet -ExcelPackage $e -WorkSheetname 'Sheet3' `
    -MoveAfter "*" -CopySource ($e.Workbook.Worksheets['Sheet1'])

# Save 'Sheet1' to the new output file.
#
Copy-ExcelWorkSheet -SourceWorkbook $e -SourceWorkSheet 'Sheet1' `
    -DestinationWorkSheet 'Sheet1' -DestinationWorkbook $outfile
```

This produces:
```
Exception calling "Save" with "0" argument(s): "Error saving file C:\src\xl\fileout002.xlsx"
At C:\Users\pwatson2\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Close-ExcelPack
age.ps1:27 char:29
+             else           {$ExcelPackage.Save()          }
+                             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
[filein002.xlsx](https://github.com/dfinke/ImportExcel/files/4519296/filein002.xlsx)

```
