### ISSUE TITLE
Control: Format cells

### ISSUE THREAD

**Issue by tomerikko** [dfinke/ImportExcel#631]
HI there, 
I have a script that is pushing out an excel file using this amazing module!
for some fields, in my example that are a formula to calculate a value, it decided to change the **cell formatting** from **General** to **Custom**.
I would like to forcibly revert back some fields to **General**, i assume i need to open he _worksheet $sheet = $excel.Workbook.Worksheets['sheet_name']_ and then use _Set-ExcelRange_  but i am not sure exactly how at least not to change the cell back to **General** formatting.
Anyone done this before and can share how?

![image](https://user-images.githubusercontent.com/10564814/61372628-fe362480-a897-11e9-95ee-f49cf5e9c175.png)

**Comment by dfinke** [comment]
```powershell
$xl = Open-ExcelPackage -Path "C:\CustomToGeneral.xlsx"

Set-Format -WorkSheet $xl.Workbook.Worksheets["Sheet1"] -Range B3 -NumberFormat 'General'

Close-ExcelPackage $xl -Show
```

**Comment by tomerikko** [comment]
Perfect. Thank you so much!
