### ISSUE TITLE
how to reference "pivot-table" object in Add-ExcelChart -PivotTable parameter

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#632]
Hello All,
i am testing a script where I want to create Mutliple charts with the same pivot data,
I am able to get the first chart using the below snippets

```
 $pivotTableParams = @{
    PivotTableName  = "PWAuditData1"
    Address         = $excel.Sheet1.cells["F1"]
    SourceWorkSheet = $excel.Sheet1
    PivotRows       = echo o_username
    PivotData       = @{'Total' = 'sum'}
    PivotTableStyle = 'Light21'

        PivotChartDefinition = @{
                        Title="Total Downloads by Users";
                        ChartType="ColumnClustered";
                        Column=5; Row=15; Width=600; Height=500;
                        YMajorUnit=500; YMinorUnit=100; 
                        LegendPosition="Bottom"
                                 }
}
```

and then call the above definition using 

$pt = Add-PivotTable @pivotTableParams -PassThru

I want to use the same data from above Pivot Table and insert for example a doughnut chart for which i use the Add-ExcelChart 

```
$pivotSheet=$excel.Sheet1

$pt1 = Add-ExcelChart  -Worksheet $excel.Sheet1 -PivotTable $pivotSheet.pivotTables[0] -ChartType Doughnut -Row 100 -Column 20 -PassThru
```

when the code runs, I am able to get the first chart, but for inserting the second chart it gives error as below,
Parameter set cannot be resolved using the specified named parameters 

![image](https://user-images.githubusercontent.com/48583862/61518538-59088100-aa3c-11e9-8b65-1ec931ddacda.png)

Question:
What is the correct way to reference the existing Pivot object which is already? placed on the sheet ?

Thanks for looking to this,
RJ

**Comment by dfinke** [comment]
Check this out, let me know if it doesn't do what you need.

https://github.com/dfinke/ImportExcel/blob/master/Examples/PivotTable/MultiplePivotTables.ps1

**Comment by jhoneill** [comment]
Two issues with add-ExcelChart as currently written. 
1. You can't specify both -worksheet and -pivotTable.  When called with -PivotTable the chart is created on the page where the data is . 
2. When a pivot chart is created  it uses a fixed name, so add-excelChart can't create two charts for one pivot. 

As a workaround use 
`$pt = Add-PivotTable @pivotTableParams -PassThru `
as before, and then 
```
$chart = $excel.Sheet1.Drawings.AddChart(("chart 2" ),"Doughnut",$pt)
$chart.SetPosition(100,0,20,0)  # X row, x offset, y row, y offset
$chart.SetSize(1000,500)   # Xpixels , yPixels
```

**Comment by cprograemer84** [comment]
Hi @dfinke  and @jhoneill 
Thanks a lot for looking into my query and responding to it. 
The solution provided by @jhoneill  has worked for me and I am able to plot multiple charts using the same pivot table. 


```
$pivotTableParams = @{
    PivotTableName  = "PWAuditData1"
    Address         = $excel.Sheet1.cells["F1"]
    SourceWorkSheet = $excel.Sheet1
    PivotRows       = echo o_username
    PivotData       = @{'Total' = 'sum'}
    PivotTableStyle = 'Light21'

        PivotChartDefinition = @{
                        Title="Total Downloads by Users";
                        ChartType="ColumnClustered";
                        Column=5; Row=15; 
                        Width=600; Height=500;
                        LegendPosition="Bottom"


                                }
   
     }

$pt = Add-PivotTable @pivotTableParams -PassThru`
$chart = $excel.Sheet1.Drawings.AddChart(("chart 2"),"Doughnut",$pt)
$chart.SetPosition(10,0,20,0)  # X row, x offset, y row, y offset
$chart.SetSize(1000,500)   # Xpixels , yPixels
$chart.DataLabel.ShowValue = $true

```

One follow up question, using the line of code 

`$chart.DataLabel.ShowValue = $true`


I was able to turn on the "Datalables" for the "Doughnut" chart.



How do I enable "DataLables" for charts created using Import-Excel module?

**Comment by cprograemer84** [comment]
Got the answer 

`$excel.Sheet1.Drawings["ChartPWAuditData1"].DataLabel.ShowValue= $true`

@jhoneill @dfinke  Thanks a ton.

**Comment by dfinke** [comment]
@jhoneill thoughts on effort and ROI of enabling that in function? 

`Get-ExcelDrawing -WorkSheet $ws -name yyz -ShowDataLabel`

Feels like it may be a nest of issues, and interesting.

**Comment by jhoneill** [comment]
The easiest way to do it is to split new-ExcelChart so all the set operations go into a new Set-ExcelChart; and have a new Get-ExcelDrawing which returns the chart. 

` Get-ExcelDrawing -WorkSheet $ws -name yyz | set-ExcelChart -ShowDataLabel`

Effort is minutes rather than hours. Return ... hard to estimate, but probably worth enough to a small number to make it worth doing.

**Comment by dfinke** [comment]
Yeah. Well, to the backlog it goes.

**Comment by jkratzenberg** [comment]
As cprograemer84 mentioned, adding **$chart.DataLabel.ShowValue = $true** to the Add-ExcelChart.ps1 file, line 133 in my .PS1 (7.0.0) added the labels automatically. (ColumnClustered chart type). I tested a few other types as well just fine.
