### ISSUE TITLE
get-help examples

### ISSUE THREAD

**Issue by arielf-mn** [dfinke/ImportExcel#633]
I'm wondering if there's a place that has a detailed list of the commands and what they do ( with examples). This would help immensely for us newbies that want to get up and running quickly and efficiently.

**Comment by dfinke** [comment]
https://github.com/dfinke/ImportExcel/tree/master/Examples

**Comment by jhoneill** [comment]
There are quite a lot of examples if you do 
`get-help import-excel -full `
or 
`get-help export-excel -full `

But there are bound to be things which could be added and would make things better. If *Anyone* has any they are welcome even if only posted here as  command-line and description we can put them into the help text. 

`get-command -Module importexcel | get-help | format-table name,synopsis `
Gives a list of commands an quick idea of what they do.
