### ISSUE TITLE
Feature Request: Get-WorkbookConnection

### ISSUE THREAD

**Issue by GarrettStrattonTR** [dfinke/ImportExcel#634]
Add a _Get-WorkbookConnection_ function which would return an array of the Excel workbook's data connections.  We can do this in COM, but I much prefer your solution. 

With COM, this is done via: 
```
$Excel = New-Object -comObject Excel.Application
$Workbook = $Excel.workbooks.open(<file path>) 
$Workbook.Connections
```

**Comment by dfinke** [comment]
So the `Connections` is for external connections that the worksheet can pull data from?

Took a fast spin in the EPPlus code that manipulates the underlying XML and did not see anything for connections. Also Googled.

Need to look into it more.
