### ISSUE TITLE
filter a table upon creation

### ISSUE THREAD

**Issue by tomerikko** [dfinke/ImportExcel#635]
Hi there, 
Can i filter a table before pushing it into the excel file? ('normal' table, not a pivot table)
currently i filter manually after a file is created.
what i want is the full data set in the table, but to filter base on specific value on a specific column.

My guess would be around: _**$xlpkg.Workbook.Worksheets["sheet name"].Tables["table name"]**_ - but this is as far as i go :)
Is that possible?

**Comment by tomerikko** [comment]
As an example, i want to filter the below table from the script, so when the excel file is opened, this table will be already filtered on specific team or on specific Action
![image](https://user-images.githubusercontent.com/10564814/61575899-87d13680-aad2-11e9-9c48-a5b85177f484.png)

**Comment by dfinke** [comment]
Looks like

> If you truly want to apply a filter to a column for output then then you have to do it manually since EPPlus does not natively apply filters.

https://stackoverflow.com/questions/32723483/adding-a-specific-autofilter-on-a-column

**Comment by tomerikko** [comment]
Looks Interesting, ill give it a spin.  thanks!

**Comment by tomerikko** [comment]
@dfinke   
Hi Doug, 
In version 6.2.4 it is written: "Creates a table, with filtering"  but i didnt find any further info on that.
Could this be a solution to my question above, and we can now filter a table once created?
if so, could anyone share an example code with me?

**Comment by dfinke** [comment]
@jhoneill @ili101 Could you shed some light on this, I vaguely remember what it was.

**Comment by ili101** [comment]
It just referring to the fact that AutoFilter is on by default. Not actually creating a filter. Sorry

**Comment by dfinke** [comment]
Yeah, that's what I thought, I'll update the readme
