### ISSUE TITLE
ColumnStack chart with two categories

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#641]
Dear All,
I am facing issue creating a Column Chart which has two category. 
I have attached my sample excel and code below

```
$StatsFolder="D:\Projects\Stats"
$StatsFile="Results.xlsx"

$excel =Open-ExcelPackage -Path $StatsFolder\$StatsFile
$ws=$excel.Sheet1
$row=$ws.Dimension.Rows 
$col=$ws.Dimension.Columns


Add-ExcelChart -Worksheet $ws -Title "Columns Test" -XRange A1:B$row -YRange @("C2:C$row","D2:D$row", "E2:E$row")  -LegendPosition Bottom -ChartType ColumnStacked -SeriesHeader "Orange", "Yellow", "Green"
Close-ExcelPackage -ExcelPackage $excel -Show
```

![image](https://user-images.githubusercontent.com/48583862/61924152-265d0c00-af99-11e9-8cd9-34532517ea49.png)

When I use the same data and manually insert a column chart, the data is correctly grouped based on the First Category (File1, File2, File3..etc) 

![image](https://user-images.githubusercontent.com/48583862/61924277-a6837180-af99-11e9-872d-f02ee85f0ba5.png)

Kindly suggest modification to the code so that I can get the results as shown in image 2
[Results.xlsx](https://github.com/dfinke/ImportExcel/files/3434071/Results.xlsx)

**Comment by jhoneill** [comment]
1. The wrong names on the far left, your code needs to start the labels from A2 not A1. 
2. Multi-level labels. There isn't an easy hook for this. but you can do 
```
$chart = Add-ExcelChart -passthru -Worksheet $ws -Title "Columns Test" -XRange A1:B$row -YRange @("C2:C$row","D2:D$row", "E2:E$row")  -LegendPosition Bottom -ChartType ColumnStacked -SeriesHeader "Orange", "Yellow", "Green"  
$chart.ChartXml.chartSpace.chart.plotArea.catAx.InnerXml += '<c:noMultiLvlLbl val="0" xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" />'        

```
This is in the category of "unsupported hack" but it works. It defaults to quite nasty borders round the labels so you might also want 
`$chart.XAxis.Border.Fill.Style = "NoFill"
`
the finish, as before,  with 
`Close-ExcelPackage -ExcelPackage $excel -Show
`

**Comment by dfinke** [comment]
That is hackalicious. Definitely not supported :)
