### ISSUE TITLE
PivotTable Options Display as classic PivotTable Layout and Field Settings as Repeat item labels

### ISSUE THREAD

**Issue by blhf** [dfinke/ImportExcel#643]
I have to create a workbook with 2 sheets. 1 for raw and the other 1 for summary.
Basically the data I have is:

![image](https://user-images.githubusercontent.com/10716429/62221521-59156300-b3e4-11e9-92ae-68942d70dc78.png)

This data came from SQL and I was able to export it to excel.

But my second challenge is how to create a summary in another worksheet.
something like this:

![image](https://user-images.githubusercontent.com/10716429/62221730-b7dadc80-b3e4-11e9-93e0-3e8516b4ce67.png)

Main objective is to tweak the Pivot table option like this.

![image](https://user-images.githubusercontent.com/10716429/62228377-1a85a580-b3f0-11e9-8052-249b00b900ed.png)

Then remove the totals per row. To have the same output as the fig 2. But can we do it as automated as I will do the automated email sending after this.

**Comment by dfinke** [comment]
Not sure I know how to get a pivot table in that shape. Pivot tables are hierarchical.

![image](https://user-images.githubusercontent.com/67258/62231320-d06dd700-b391-11e9-99d7-667d3fa9edd4.png)

**Comment by blhf** [comment]
[sample.xlsx](https://github.com/dfinke/ImportExcel/files/3453031/sample.xlsx)

Hi @dfinke . I attached the workbook.

**Comment by dfinke** [comment]
Thanks for the workbook. This is a new one on me. Don't know how to manually shape the pivot table the way you did. Here's mine.

@jhoneill Do you know how to shape the pivot table that way?

[pivot.xlsx](https://github.com/dfinke/ImportExcel/files/3453237/pivot.xlsx)

**Comment by jhoneill** [comment]
![image](https://user-images.githubusercontent.com/16209593/62254299-86680e00-b3f0-11e9-897d-15edabc757bc.png)
I can get roughly the same like this 
 ```
$excel = $data | export-excel -path $env:temp\temp.xlsx -PassThru                                                                                                                                                        
 $pivot  = Add-PivotTable -PivotTableName foo -ExcelPackage $excel -SourceWorkSheet sheet1 -PivotRows "Company Name", "CompanyID", "Country" -PivotData @{sales="Sum"} -NoTotalsInPivot  -PassThru                        
  $pivot.RowFields[0].SubTotalFunctions="None"                                                                                                                                                                             
  $pivot.RowFields[1].SubTotalFunctions="None"                                                                                                                                                                             
  $pivot.RowFields[2].SubTotalFunctions="None"                                                                                                                                                                             
  $pivot.RowFields[0].Compact = $false                                                                                                                                                                                     
  $pivot.RowFields[1].Compact = $false                                                                                                                                                                                     
  $pivot.RowFields[2].Compact = $false                                                                                                                                                                                     
  $pivot.RowFields[0].Outline = $false                                                                                                                                                                                     
  $pivot.RowFields[1].Outline = $false                                                                                                                                                                                     
  $pivot.RowFields[2].Outline = $false                                                                                                                                                                                     
  $pivot.EnableDrill = $false                                                                                                                                                                                              
  $pivot.ShowDrill = $false                                                                                                                                                                                                
 

```

I have to manually turn on "repeat label items" because that is not settable by EPPLus, and I can't set the column headings to be other than row labels and total

**Comment by dfinke** [comment]
Thanks @jhoneill, need to explore field settings. Too bad EPPlus doesn't support it.

**Comment by blhf** [comment]
@dfinke I found a work around for this. I used t-sql to do the data pivot for me. However if you find this issue worth looking into I'll be glad if I can be of any assistance. 

Thank you for this wonderful PS module. More power to you!
