### ISSUE TITLE
Data Labels 

### ISSUE THREAD

**Issue by tomerikko** [dfinke/ImportExcel#646]
When creating a table with _New-ExcelChartDefinition_
we have 2 flags for labels, -ShowCategory & -ShowPercent
any option to add the 'Data Labels ' option as in from the Excel UI > 'Chart Elements' ?
or add another option to 'Showdata' i want to add the value of the data on those bars as seen in the image below

![image](https://user-images.githubusercontent.com/10564814/62364822-cd562080-b522-11e9-82ec-97ddf393f3e1.png)

**Comment by tomerikko** [comment]
NO one has any idea on this question?

**Comment by cprograemer84** [comment]
Hi, 
this tread will answer your question
https://github.com/dfinke/ImportExcel/issues/632

**Comment by tomerikko** [comment]
it does indeed.

that there is no fashion way to do it for now :( .    
 thanks for the TIP though.
