### ISSUE TITLE
DisplayAsBlanks property in New-ExcelChartDefinition 

### ISSUE THREAD

**Issue by dptsay** [dfinke/ImportExcel#647]
I am new to the 'Charting' part of the Importexcel.  I am looking for a corresponding "DisplayAsBlanks" property of  EPPLUS ExcelChart Class in the New-ExcelChartDefinition.  I need Export-excel to ignore empty cells when generating Chart.
Thank you.

**Comment by jhoneill** [comment]
It's not in module at present, but I will loo at adding to Add-ExcelChart and to New-ExcelChartDefinition. 
For now, if you know something in the class you want to change if you call Add-ExcelChart with -PassThru you get an ExcelChart object back, which you can modify.

**Comment by dptsay** [comment]
Thank you for your help, I will follow your instruction.  During this investigation, I also discovered there is a problem with SeriesHeader parameter.  I am aware of the issue #495 which is closed now.  I used the example 2 from Charts\MultiSeries1.ps1, I can have up to three SeriesHeaders.  But if I modified the data to have 4 fields with 4 SeriesHeaders, when the chart is generated, ALL the Headers become "Series1", not the text I supplied in the parameter.  I am new to GitHub, please let me know if I need to file this as a New issue.  Thanks!

**Comment by jhoneill** [comment]
I modified that script to have 4 data columns and got 4 series and 4 series headers.  


```
$data = @"
A,B,C,D,Date
2,1,1,3,2016-03-29
5,10,1,7,2016-03-29
"@

$c = New-ExcelChartDefinition -Title Impressions `
    -ChartType Line   `
    -XRange "Impressions[Date]" `
    -YRange @("Impressions[D]","Impressions[C]","Impressions[B]","Impressions[A]") `
    -SeriesHeader 'D data','C data','B data','A data' `
    -Row 0 -Column 0

$data | ConvertFrom-Csv |   Export-Excel -path temp.xlsx -AutoSize -TableName Impressions
Export-Excel -path temp.xlsx -worksheetName chartPage -ExcelChartDefinition $c  -show

```

If you can post the script which is having the problem, I'll take a look  (keep it in this issue for now).

**Comment by dptsay** [comment]
I appreciate very much for your assistance.  I am able to copy and paste your modified sample program into my PowerShell Studio environment and generate a chart with 4 SeriesHeaders.  I don't know what happen to my previously sample program which generated a chart with 4 x "Series1" SeriesHeaders but I am going to base on your sample to incorporate my real data for the chart..
Again, I appreciate your help and I will close this issue now.
