### ISSUE TITLE
Import with Filter

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#649]
I have a large worksheet I want to import, but I only need part of the data.  Since I'll be doing a lot of manipulation, I'd like to filter the data during or after import.  The filter would be based on matching or not matching  particular cell value(s).

I don't see a filter mechanism in ImportExcel. Can you suggest a possible approach?

\\\Greg

**Comment by uSlackr** [comment]
Is this as simple as passing the import through a pipeline and filtering with a where clause?

**Comment by dfinke** [comment]
Off the top of my head, that was my thought.
