### ISSUE TITLE
Export-Excel creates corrupted file

### ISSUE THREAD

**Issue by megamorf** [dfinke/ImportExcel#65]
Hey Doug, 

first of all thanks a lot for this feature-rich module. I've followed its development for some time now but just today had the chance to actually use it for a report.

I ran into a problem with the Export-Excel function that prevents me from working with it - it creates corrupted excel documents all the time.
## Setup

PS v4.0
Win7 Pro SP1 (German)
Office 2010 ProPlus x86 (German)
## This is the error I get:

![link](http://i.imgur.com/ZuFfdks.png)
it says unreadable contents have been found and asks me if I'd like to recover them
## Code examples:

My first attempt

``` powershell
$file = 'D:\temp\myexcelreport.xlsx'
$excelParams = @{AutoSize = $true; AutoFilter = $true; TitleBold = $true; FreezeTopRow = $true}
gsv | Export-Excel @excelParams -Path $file -WorkSheetname 'Service stuff' -TableName 'ExtServices' -Title 'My services:' 
```

Second attempt trying to narrow it down but even this gives me a corrupted excel file.
`gsv | Export-Excel -Path D:\temp\myexcelreport.xlsx`

Using 2b7ffe0c124ff42454fc5026563b69f137e24076 as head revision.

I've been using an Export-Xlsx function from Luc Dekens for a while and haven't had any of these problems.

**Comment by dfinke** [comment]
Thanks for the bug report. Good news, I can repro the issue.

Can you try:
`rm D:\temp\myexcelreport.xlsx`
`gsv | Export-Excel -Path D:\temp\myexcelreport.xlsx`

That worked for me and I'll look into the bug.


Have you considered a career in QA? ;-)

Thanks
Doug

**Comment by dfinke** [comment]
OK, I think I've narrowed it down to `AutoFilter = $true` and `-Title 'My services:' `

Using TableName creates a table with filtering capability and that conflicts with AutoFilter.
I think the `-Title` logic may need improvement, it blindly adds that text to the first row and it causes a problem for auto filtering and tables.

```powershell
$excelParams = @{
    AutoSize      = $true
    TitleBold     = $true
    FreezeTopRow  = $true
    WorkSheetname = 'Service stuff' 
    TableName     = 'ExtServices' 
}

gsv | Export-Excel @excelParams -Path $file -Show
```

Thanks for reporting this.

Doug

**Comment by ili101** [comment]
Hi
I made a suggested fix that will prevent you from adding TableName with AutoFilter and from "Now" to add AutoFilter if TableName is set. #230
