### ISSUE TITLE
set-columm worksheet null

### ISSUE THREAD

**Issue by AdrianSaunders** [dfinke/ImportExcel#650]
Hi
I'm pretty new to Powershell, and not having much luck. I'm trying to search through a number of txt files for specific pattern push that in to an excel file and then do some string manipulation to create new columns with date and time formats.

I can do the first part using this
`Get-ChildItem "c:\troubleshooting\forcepoint\Fail_Open\$((Get-Date).ToShortDateString())\" -Filter *.txt | Select-String -Pattern 'Tray icon turned' | Select -Property filename, line | Export-Excel "c:\troubleshooting\forcepoint\Fail_Open\$((Get-Date).ToShortDateString())\failed_open.xlsx" -WorkSheetname "Trays" –PassThru`

Next I want to add the new columns
`Set-Column -Worksheet "Trays" -Column 3 -Heading "Machine" -Value {"=LEFT(A$row,LEN(A$row)-4)"} `

Now this is where I'm having trouble seems the worksheet value isn't correct. I've tried putting the export-excel part as a variable and then adding
`$WS = $xl.Workbook.Worksheets["Trays"]`
but just says the worksheet is null :-/
I know I'm doing something basic wrong but I can't understand what!

**Comment by jhoneill** [comment]
You probably missed -passthru off the end of the export excel command. If you 
`$xl = get-stuff  | export-excel <<params>> -passthru `
You can then do 
`set-column -excelPackage $xl -worksheet "trays" <<params>>`
and when you've finished 
`close-excelPackage $xl 
`

**Comment by AdrianSaunders** [comment]
I was using passthru but I think the site I was using as a reference messed it up
