### ISSUE TITLE
Charting - X - Y ranges - Formating 

### ISSUE THREAD

**Issue by WinOpsEngineer** [dfinke/ImportExcel#652]
I have some pre defined charts I would like to geenrate using thsi module .

The range from one chart reads like this =Worksheet1!$A$32:$A$44,Data!$C$32:$D$44.  How can I use this cmdlet  New-ExcelChartDefinition to acomplish teh same result?

**Comment by dfinke** [comment]
### Try this

```powershell
$xlfile="$env:TEMP\testChart.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$ecd = New-ExcelChart -XRange '=Sheet1!$A$2:$A$11' -YRange '=Sheet1!$C$2:$C$11'

ConvertFrom-Csv @"
Region,Item,TotalSold
North,apple,91
North,banana,66
East,screwdriver,41
West,peach,95
South,orange,29
East,kiwi,33
West,melon,44
North,drill,34
East,avocado,57
West,melon,52
"@ | Export-Excel $xlfile -Show -ExcelChartDefinition $ecd
```

![image](https://user-images.githubusercontent.com/67258/62811554-1896a300-bad0-11e9-9dc0-8dbbb3ec2b45.png)

**Comment by dfinke** [comment]
### Create a new worksheet for the chart

```powershell
$xlfile="$env:TEMP\testChart.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel =  ConvertFrom-Csv @"
Region,Item,TotalSold
North,apple,91
North,banana,66
East,screwdriver,41
West,peach,95
South,orange,29
East,kiwi,33
West,melon,44
North,drill,34
East,avocado,57
West,melon,52
"@ | Export-Excel $xlfile -PassThru

$ws = Add-WorkSheet -ExcelPackage $excel -WorksheetName Sheet2

Add-ExcelChart -Worksheet $ws -XRange '=Sheet1!$A$2:$A$11' -YRange '=Sheet1!$C$2:$C$11'

Close-ExcelPackage $excel -Show
```

**Comment by WinOpsEngineer** [comment]
Thank you

I am trying the below code and I am getting a refernce error Im not sure why..

$xlfile="$env:TEMP\testChart.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel =  ConvertFrom-Csv @'  
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5,	1542.2,	782.2,	552
June-2020,5	,1499.8	,805.5,	694
May-2020,5	,1457.,4	,828.8	,706
April-2020,5,1415,	852.1,	698
March-2020,5,	1372.6,	875.4,	652
February-2020,5	,1330.2	,898.7	,705
January-2020,6	,1287.8	,922,	805
December-2019,5	,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ | Export-Excel $xlfile  -AutoSize -StartRow 2 -TableName ITServiceDesk  -PassThru

$ws = Add-WorkSheet -ExcelPackage $excel -WorksheetName Sheet2

Add-ExcelChart -Worksheet $ws -XRange '=Sheet1!A2:A14' -YRange '=Sheet1!C2:D14' -ChartType Line
Close-ExcelPackage $excel -Show

**Comment by WinOpsEngineer** [comment]
I took a look thru github examples and foudn something . There is an example that creates the line chart correcly but i couldnt get it to work with another sheet. #1 is form the github page # 2 is creating  a blank chart on worksheet2


#1
$data = @"
Date,WindowsSeven,WindowsTen,PCsManaged
August-2020,2322,1300,3296
July-2020,2322,1300,3294
June-2020,2322,	1300,3294
May-2020,2322,1300,3289
April-2020,2322,1300,3289
March-2020,2322,1100,3290
February-2020,2322,1200,3290
January-2020,2322,1200,3280
December-2019,2322,11110,3280
November-2019,2322,1119,3280
October-2019,2322,1115,3280
September-2019,2322,1006,3273
"@ | ConvertFrom-Csv

$c = New-ExcelChart -Title OS `
    -ChartType Line -Header "Something" `
    -XRange "OS[Date]" `
    -YRange @("OS[WindowsSeven]","OS[WindowsTen]")

$data |
    Export-Excel temp2.xlsx -AutoSize -TableName OS -Show -ExcelChartDefinition $c


#2
$xlfile="$env:TEMP\testChart2.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel =  ConvertFrom-Csv @'  
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5,	1542.2,	782.2,	552
June-2020,5	,1499.8	,805.5,	694
May-2020,5	,1457.,4	,828.8	,706
April-2020,5,1415,	852.1,	698
March-2020,5,	1372.6,	875.4,	652
February-2020,5	,1330.2	,898.7	,705
January-2020,6	,1287.8	,922,	805
December-2019,5	,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ | Export-Excel $xlfile   -PassThru

$ws = Add-WorkSheet -ExcelPackage $excel -WorksheetName Sheet2

Add-ExcelChart -Worksheet $ws -Title OS   -XRange "OS[=Sheet1!Date]" `   -YRange @("OS[=Sheet1!WindowsSeven]","OS[Sheet1!WindowsTen]") -ChartType Line


Close-ExcelPackage $excel -Show

**Comment by WinOpsEngineer** [comment]
I got the chart to work with the below code ... the only thing I am missing is how to associate the legend with the 2 column names (Series 0 , Series 1)

$xlfile="$env:TEMP\testChart.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel =  ConvertFrom-Csv @'  
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5,	1542.2,	782.2,	552
June-2020,5	,1499.8	,805.5,	694
May-2020,5	,1457.,4	,828.8	,706
April-2020,5,1415,	852.1,	698
March-2020,5,	1372.6,	875.4,	652
February-2020,5	,1330.2	,898.7	,705
January-2020,6	,1287.8	,922,	805
December-2019,5	,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ | Export-Excel $xlfile   -PassThru

$ws = Add-WorkSheet -ExcelPackage $excel -WorksheetName Sheet2

Add-ExcelChart -Worksheet $ws -XRange '=Sheet1!$A$2:$A$13' -YRange @('=Sheet1!$C$2:$c$13','=Sheet1!$d$2:$d$13') -ChartType Line -Title OS 

Close-ExcelPackage $excel -Show

![Series1-2](https://user-images.githubusercontent.com/40338530/62815709-65877300-baea-11e9-82d2-84f07397bdcb.jpg)

**Comment by WinOpsEngineer** [comment]
I got it! Couldnt have figured it out with out you Doug, thank you!!

$xlfile="$env:TEMP\testChart.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel =  ConvertFrom-Csv @'  
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5,	1542.2,	782.2,	552
June-2020,5	,1499.8	,805.5,	694
May-2020,5	,1457.,4	,828.8	,706
April-2020,5,1415,	852.1,	698
March-2020,5,	1372.6,	875.4,	652
February-2020,5	,1330.2	,898.7	,705
January-2020,6	,1287.8	,922,	805
December-2019,5	,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ | Export-Excel $xlfile   -PassThru

$ws = Add-WorkSheet -ExcelPackage $excel -WorksheetName Sheet2

Add-ExcelChart -Worksheet $ws -XRange '=Sheet1!$A$2:$A$13' -YRange @('=Sheet1!$C$2:$c$13','=Sheet1!$d$2:$d$13') -ChartType Line -Title Tickets  -SeriesHeader 'TotalTicketsClosed',	'HelpDeskTicketsOpened'

Close-ExcelPackage $excel -Show

**Comment by WinOpsEngineer** [comment]
I do have a question Why in excel you can include the colmun name in the range but with the module it errors out? 

![PatchCompl](https://user-images.githubusercontent.com/40338530/62822923-550de180-bb58-11e9-8de5-8f3d8b8996d4.jpg)

**Comment by WinOpsEngineer** [comment]
Also is there a way to format the lines in the chart .. ie color and point size?

**Comment by dfinke** [comment]
Try using  `Export-Excel $xlfile -PassThru -AutoNameRange` the names should be available.

**Comment by WinOpsEngineer** [comment]
yes that removed the reference error! Thx :) . Is there a way to set the line color and width of a chart.
![Chart Settings](https://user-images.githubusercontent.com/40338530/62827185-6e368280-bb98-11e9-8019-d0039cbab493.jpg)

**Comment by cprograemer84** [comment]
Hi,
This post may answer your question. 
https://github.com/dfinke/ImportExcel/issues/507

**Comment by cprograemer84** [comment]
Hi,
The below modification has worked for me. can you check if this works for you?

```
$xlfile="$env:TEMP\testChart.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel = ConvertFrom-Csv @'
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5, 1542.2, 782.2, 552
June-2020,5 ,1499.8 ,805.5, 694
May-2020,5 ,1457.,4 ,828.8 ,706
April-2020,5,1415, 852.1, 698
March-2020,5, 1372.6, 875.4, 652
February-2020,5 ,1330.2 ,898.7 ,705
January-2020,6 ,1287.8 ,922, 805
December-2019,5 ,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ | Export-Excel $xlfile -PassThru

$ws = Add-WorkSheet -ExcelPackage $excel -WorksheetName Sheet2

$chart=Add-ExcelChart -PassThru -Worksheet $ws -XRange '=Sheet1!$A$2:$A$13' -YRange @('=Sheet1!$C$2:$c$13','=Sheet1!$d$2:$d$13') -ChartType Line -Title Tickets -SeriesHeader 'TotalTicketsClosed', 'HelpDeskTicketsOpened' 

$chart.Series[0].LineColor = [System.Drawing.Color]::ForestGreen
$chart.Series[1].LineWidth =4 

Close-ExcelPackage $excel -Show
```

**Comment by WinOpsEngineer** [comment]
WOW that works great! Thank you! I am shifting gears a little . I am looking to plot the chart via table names properties like below keeping it onone page so the hcarting is more dynamic. How can I do with the beow code?..Thx!

$Data = ConvertFrom-Csv @'
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5, 1542.2, 782.2, 552
June-2020,5 ,1499.8 ,805.5, 694
May-2020,5 ,1457.,4 ,828.8 ,706
April-2020,5,1415, 852.1, 698
March-2020,5, 1372.6, 875.4, 652
February-2020,5 ,1330.2 ,898.7 ,705
January-2020,6 ,1287.8 ,922, 805
December-2019,5 ,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ 
$c = New-ExcelChart -Title 'Helpdesk Tickets Opened/Closed' `
    -ChartType Line `
    -XRange "Helpdesk[Date]" `
    -YRange @("Helpdesk[TotalTicketsClosed]","Helpdesk[HelpDeskTicketsOpened]")  -SeriesHeader 'TotalTicketsClosed',	'HelpDeskTicketsOpened'

$data |
    Export-Excel V:\temp.xlsx -AutoSize -TableName Helpdesk -Show   -ExcelChartDefinition $c

**Comment by WinOpsEngineer** [comment]
I got works great Thank you!

$excelPath = "C:\Temp\Test3.xlsx"
Remove-Item $excelPath -ErrorAction Ignore

$Data = ConvertFrom-Csv @'
Date,HelpDeskStaff,TotalTicketsClosed,HelpDeskTicketsOpened,WebrequestsForService
August-2020,5,1584.6,758.9,604
July-2020,5, 1542.2, 782.2, 552
June-2020,5 ,1499.8 ,805.5, 694
May-2020,5 ,1457.,4 ,828.8 ,706
April-2020,5,1415, 852.1, 698
March-2020,5, 1372.6, 875.4, 652
February-2020,5 ,1330.2 ,898.7 ,705
January-2020,6 ,1287.8 ,922, 805
December-2019,5 ,1245.4,945.3,725
November-2019,4,1285,1002,925
October-2019,5,985,985,885
September-2019,5,1200,852,725
'@ 

$tableName = 'Helpdesk'
$splat = @{
    Title = 'Logging Level Summary'
    ChartType = 'Line'
    XRange = "$tableName[Date]"
    YRange = @("$tableName[HelpDeskTicketsOpened]","$tableName[TotalTicketsClosed]")
    SeriesHeader ='TotalTicketsClosed',	'HelpDeskTicketsOpened'
    Row = 15
    Column = 0
    Width = 500
    Height = 200
}

$xl = $Data  | Export-Excel -Path $excelPath -WorksheetName 'Data' -AutoSize -TableName $tableName -PassThru

$chart = Add-ExcelChart @splat -Worksheet $xl.Data -PassThru 
$chart.Series[0].LineColor = [System.Drawing.Color]::Red
$chart.Series[1].LineColor = [System.Drawing.Color]::Blue
$chart.Series[0].LineWidth =4 
$chart.Series[1].LineWidth =4 

Close-ExcelPackage $xl -Show

**Comment by dfinke** [comment]
Drop a comment to let us know if your Excel report was liked by others.
