### ISSUE TITLE
relative referencing

### ISSUE THREAD

**Issue by AdrianSaunders** [dfinke/ImportExcel#654]
Sorry for posting whats probably very basic but I've spent 2 days on this and I cant work it out or find the reference to using the correct cell reference.
I have a txt file, and using export-excel created a passthrough xlsx with some time/date columns.
My next step is to check for a value in a column, and depending on that value either post a '0'or subtract a time value from the previous value which are held in the same column

Column A     Column B      Column C
     0              12:00:00                0
     1              13:00:00           0:30:00     
     0              13:30:00                 0

Problem is I can work out the value for the relative cell reference;
Set-Column -Worksheet $ws -Column 3 -Heading "Duration" -Value { ("=IF(a2 <1, b3-b2,0)")} -NumberFormat 'long time'
I know it should be some variant on B$row but I can't find a reference for the usage.

many thanks

**Comment by dfinke** [comment]
`Set-Column` does not support the `-Formula` parameter.

Not sure of how to make this easier, you'll need to set the CELL references in each formula. I would either reshape the data or calc the time diff in PowerShell first and then export it to Excel.

```powershell
$xlfile = "$env:TEMP\tryit.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
flag,time,duration
0,12:00:00,
1,13:00:00,
0,13:30:00,
"@

$excel = $data | Export-Excel $xlfile -PassThru

Set-Format -WorkSheet $excel.Workbook.Worksheets["Sheet1"] -Range C2 -Formula "=IF(A2 < 1, b3-b2,0)" -NumberFormat 'Long Time'

Close-ExcelPackage $excel -Show
```

**Comment by ili101** [comment]
Can be done with a Table and referencing like this `[[#This Row],[time]]` (Shows as `[@time]` in Excel)
``` powershell
$xlfile = "$env:TEMP\tryit.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
flag,time,duration
0,12:00:00,
1,13:00:00,
0,13:30:00,
"@

$excel = $data | Export-Excel $xlfile -PassThru -TableName 'Data'

#Set-Format -WorkSheet $excel.Workbook.Worksheets["Sheet1"] -Range C2 -Formula "=IF(A2 < 1, b3-b2,0)" -NumberFormat 'Long Time'
$excel.Workbook.Worksheets["Sheet1"].Tables[0].Columns[-1].CalculatedColumnFormula = "=IF([[#This Row],[flag]] < 1, (OFFSET([[#This Row],[time]],1,0))-[[#This Row],[time]],0)"

Close-ExcelPackage $excel -Show
```

**Comment by dfinke** [comment]
Nice. No comment :-)

**Comment by jhoneill** [comment]
> `Set-Column` does not support the `-Formula` parameter.

However if the value parameter is a script block it will be evaluated. And if it begins with an = sign it will be treated as a formula. 

All it says in the help is 
```
-Value <Object>
    A value, formula or scriptblock to fill in. A script block can use $worksheet, $row, $column [number], $columnName [letter(s)], $startRow,  $startColumn, $endRow, $endColumn.
```
I'll look add adding an example when I have a chance. 

@AdrianSaunders 
`Set-Column -Worksheet $ws -Column 4 -heading "foobar" -Value { "=IF(a$row <1, b$($row+1)-b$row,0)"}
`
will put `IF(a3 <1, b4-b3,0)` in D3 etc

**Comment by jhoneill** [comment]
It turns out example #2 shows how this works.  But I've expanded it :-)
