### ISSUE TITLE
Style Setting throws consistent error

### ISSUE THREAD

**Issue by ethanhen** [dfinke/ImportExcel#655]
I'm trying to set a style on the chart in the Excel file I'm exporting, and I get the same error no matter what I try.

Here's my code:

    $data = Import-Excel -Path "C:\data\issue_types_2_electric_boogaloo.xlsx"

    $data | Export-Excel -Path test.xlsx -KillExcel -WorkSheetname "Test" -ClearSheet -IncludePivotTable  -PivotRows "Category" -PivotData @{"Count"="Sum"} -IncludePivotChart -ChartType Pie3D -Style 8 -ShowPercent -ShowCategory -show -NoLegend

And the error:

    Unable to index into an object of type System.Int32.
    At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\6.2.3\Export-Excel.ps1:1028 char:33
    +             if (-not $s.Range) {$s["Range"] = $ws.Dimension.Address }
    +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
        + FullyQualifiedErrorId : CannotIndex

**Comment by dfinke** [comment]
Could you also upload the xlsx, or a repro version? Thanks.

**Comment by ethanhen** [comment]
The xlsx I'm opening: 
[issue_types_2_electric_boogaloo.xlsx](https://github.com/dfinke/ImportExcel/files/3498155/issue_types_2_electric_boogaloo.xlsx)

The xlsx it outputs:
[test.xlsx](https://github.com/dfinke/ImportExcel/files/3498158/test.xlsx)

**Comment by dfinke** [comment]
@jhoneill `$Style` is typed to `[object[]]` used as a splat here. Makes sense, wanted to confirm. The intention is you can pass an array of hashtables to "bulk" apply formatting?

https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L1027

@ethanhen What were you looking to get as a result for `-Style 8` and the Pie3D?

**Comment by ethanhen** [comment]
This is the default style:
![image](https://user-images.githubusercontent.com/22712358/62966214-94e0fd00-bdd4-11e9-8b76-c0f1acf45884.png)

This is "Style 8":
![image](https://user-images.githubusercontent.com/22712358/62966288-b9d57000-bdd4-11e9-9b13-792c94e222a6.png)

The Pie3D just makes the pie chart 3D and tilted.

**Comment by dfinke** [comment]
Here is a way to get at the chart from the pivot table. It has as a `Style` property that takes an enum, `OfficeOpenXml.Drawing.Chart.eChartStyle`. It has 40+ styles. 8 did not work as above, so I'm not positive if this is it. Give it a try with different styles. You can check out the properties on the drawing by putting a breakpoint on Close-ExcelPackage and displaying the drawing:

`$excel.Sheet1PivotTable.Drawings[0]`


```powershell
$data = Import-Excel -Path ".\issue_types_2_electric_boogaloo.xlsx"

rm ".\DougTest.xlsx" -ErrorAction SilentlyContinue

$p=@{
    Path =".\DougTest.xlsx"
    #ClearSheet =$true
    IncludePivotTable  =$true
    PivotRows ="Category" 
    PivotData =@{"Count"="Sum"} 
    IncludePivotChart =$true
    ChartType ="Pie3D"
    ShowPercent= $true
    ShowCategory= $true
    NoLegend=$true
    Activate=$true
}

$excel = $data | 
    Export-Excel @p -Show -PassThru 


# [OfficeOpenXml.Drawing.Chart.eChartStyle]::GetNames([OfficeOpenXml.Drawing.Chart.eChartStyle])
$excel.Sheet1PivotTable.Drawings[0].Style=35

Close-ExcelPackage $excel -Show
```

**Comment by ethanhen** [comment]
Just tried all 48 styles, none of them are the right one. Damn.

**Comment by dfinke** [comment]
Yeah, there may be another property that needs setting. Google  for EPPlus and Chart Styles. Either it is not exposed or someone figured out how to do it in C# and then it can be done with PS.

**Comment by ethanhen** [comment]
[This code ](https://github.com/JanKallman/EPPlus/blob/4dacf27661b24d92e8ba3d03d51dd5468845e6c1/SampleApp/Sample9.cs#L190)looks like it's what we want. I don't know how this translates to PS from C#.

**Comment by dfinke** [comment]
Yeah, that's what we tried. I think there may be another setting that  is not implemented by the underlying library.

`$excel.Sheet1PivotTable.Drawings[0].Style=35`

is 

```powershell
$chart = $excel.Sheet1PivotTable.Drawings[0]
$chart.Style = [OfficeOpenXml.Drawing.Chart.eChartStyle]::style26
```

**Comment by jhoneill** [comment]
> @jhoneill `$Style` is typed to `[object[]]` used as a splat here. Makes sense, wanted to confirm. The intention is you can pass an array of hashtables to "bulk" apply formatting?

Yes.  Oddly there is no help for the style parameter but there are a couple of examples under examples\styles. 

I had a look at the chart XML after creating the chart, and then again after applying a style in Excel and re-opening. A lot of difference, it is not as simple as "apply style number x"

**Comment by jhoneill** [comment]
> [This code ](https://github.com/JanKallman/EPPlus/blob/4dacf27661b24d92e8ba3d03d51dd5468845e6c1/SampleApp/Sample9.cs#L190)looks like it's what we want. I don't know how this translates to PS from C#.

Yes.  If you create a column chart and set the style like that and open in Excel  - looks like a style is applied. But if you convert to a pie chart, set a style, save and re-open in PS the style is "none".
