### ISSUE TITLE
Password protect Excel Files inside a folder

### ISSUE THREAD

**Issue by blhf** [dfinke/ImportExcel#656]
Hi I would like to know if I can do a bulk password protect all excel workbooks inside a folder?

$FilePath = 'C:\test\'
$FileName = Get-ChildItem -Path 'C:\test\' -Name

ForEach( $files in $filename)
{
Import-Excel -Path $(-Join($FilePath,$files) -Password 'QWERTY'
}

**Comment by jhoneill** [comment]
```
Get-ChildItem -Path 'C:\test' | foreach-object {
  $excel = Open-ExcelPackage -Path $_
  $excel.Save("QWERTY")
}
```
Should do it.

**Comment by blhf** [comment]
Thank you for always helping.

**Comment by dfinke** [comment]
@jhoneill didn't know you could do that
