### ISSUE TITLE
Create Range Names based on Column name

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#658]
This is not an issue with the module.  
I have an issue with my incoming data being inconsistent.  I think I can fix it if I can create named ranges based on column names. This way I can address the named range in a formula and not the column letter.

Is there a shortcut to creating these on import?

\\Greg

**Comment by dfinke** [comment]
Did you mean using `Export-Excel`?

```powerShell


ConvertFrom-Csv @"
Region,Item,TotalSold,ByTwo
South,nail,20,=TotalSold*2
South,avocado,10,=TotalSold*2
South,avocado,91,=TotalSold*2
South,orange,45,=TotalSold*2
North,orange,88,=TotalSold*2
West,lime,27,=TotalSold*2
South,lime,79,=TotalSold*2
East,apple,87,=TotalSold*2
West,banana,76,=TotalSold*2
West,saw,8,=TotalSold*2
"@ | Export-Excel "$env:TEMP\namedRanges.xlsx" -AutoNameRange -show
```

**Comment by uSlackr** [comment]
That should work for me.
