### ISSUE TITLE
The term 'new-ConditionalText' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by taheito** [dfinke/ImportExcel#66]
Hello Doug. 
thanks a lot for the great work.
when trying to use the new feature conditional text it gives me this error 

new-ConditionalText : The term 'new-ConditionalText' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.

![doug](https://cloud.githubusercontent.com/assets/10360375/12410283/8f12ba60-be84-11e5-9dfe-a39e7a5a28b1.PNG)

**Comment by dfinke** [comment]
Thanks. Let me check a few things. Did you install from GitHub or the gallery?

**Comment by taheito** [comment]
I did both of them on 2 different servers and it is the same

**Comment by dfinke** [comment]
Hmm. Not sure. Could you please check some things.

* What version of PowerShell are you using?
* `gmo -ListAvailable ImportExcel | fl`
    * Go to the `Path` and see if the the file `New-ConditionalText.ps1` is there.
    * Is this line `. $PSScriptRoot\New-ConditionalText.ps1` in the file `ImportExcel.psm1`

**Comment by taheito** [comment]
I have installed the module using Install-Module -Name ImportExcel
however the New-ConditionalText.ps1 were not one of the files that have been downloaded, once i added it the function worked for me
thnx Doug
