### ISSUE TITLE
Get the value of a specifc cell and use it as the name of the exported file

### ISSUE THREAD

**Issue by ethanhen** [dfinke/ImportExcel#663]
How would I do that?

**Comment by DanielCosta1232** [comment]
There are multiple ways to do so, but without any information provided it's unclear what values you have.

Assuming the cell you want to obtain the value of remains static, you can do something like:

$Excel = Open-ExcelPackage -Path "C:\path\excel.xlsx"
$value = [string]$Excel.Workbook.Worksheets["Sheet1"].Cells["A19"].Value # .value can also be switched to .text

Then use whichever cmdlet you'd normally use to export using $value as the name of the file.

**Comment by DanielCosta1232** [comment]
There are multiple ways to do so, but without any information provided it's unclear what values you have.

Assuming the cell you want to obtain the value of remains static, you can do something like:

$Excel = Open-ExcelPackage -Path "C:\path\excel.xlsx"
$Value = [string]$Excel.Workbook.Worksheets["Sheet1"].Cells["A19"].Value 

Then use whichever cmdlet you'd normally use to export using $value as the name of the file.
