### ISSUE TITLE
Not really an issue but more of a statement/question

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#669]
The new version of Import-excel / EPPlus does a better job of autosizing columns.

I ran the following command under 6.2
get-service | Export-Excel -Path D:\62_excel.xlsx -AutoSize 

Then ran the following command under 6.5 
get-service | Export-Excel -Path D:\65_excel.xlsx -AutoSize 

And the columns auto size much better in the 65_excel

Is this just me or is this expected?

**Comment by dfinke** [comment]
Yes, the auto sizing has been improved in v6.5.
