### ISSUE TITLE
Export-Excel : Unable to find type [http://OfficeOpenXml.Style .ExcelFillStyle].

### ISSUE THREAD

**Issue by wajidgates** [dfinke/ImportExcel#67]
Hi,
Trying to Export-Excel and receiving below message:
Export-Excel : Unable to find type [http://OfficeOpenXml.Style .ExcelFillStyle].

Using Powershell v 5.0 and Office 2016.

Thank You

**Comment by dfinke** [comment]
Thank you. Did you install the module from the PowerShell gallery or drum GutHub?

**Comment by dfinke** [comment]
Thank you. Did you install the module from the PowerShell gallery or from GutHub?

**Comment by wajidgates** [comment]
I installed from GitHub.

**Comment by dfinke** [comment]
Thanks. I updated the install from github.
