### ISSUE TITLE
Export-Excel saving two worksheets selected

### ISSUE THREAD

**Issue by wgshef** [dfinke/ImportExcel#673]
When using Export-Excel to add a new worksheet to an existing xlsx file, it saves with the first two worksheets selected.

**Comment by jhoneill** [comment]
I've just tested this, and when adding a sheet it doesn't change the active / selected sheet Unless -Activate is specified when only the new sheet becomes active. 

Could you give a bit more info - what version are you using and ideally some script which causes this.

**Comment by wgshef** [comment]
Using ImportExcel v6.0.0, Excel 2010 (32-bit), Windows 7 Ultimate (64-bit),
PSVersion 5.0.10586.117

Step 1: Using Excel, create an excel spreadsheet on your desktop named
"Test.xlsx" (put anything you want in Sheet1), then close the spreadsheet.

Run this script:
'$ExcelFile = "$ENV:USERPROFILE\Desktop\Test.xlsx";
$a = @(1,2,3,4,5)
$a | Export-Excel $ExcelFile -WorksheetName MoreNewStuff -BoldTopRow
-FreezeTopRow -AutoSize -MoveToStart -Show;

The "MoreNewStuff" and "Sheet1" sheets are both selected.

**Comment by jhoneill** [comment]
OK. I can repro it now. 
It only happens with movetostart, and interestingly it doesn't happen if the file is created by export excel, and added to. Only if the file was saved by Excel. 

I'll dig a bit deeper. Unfortunately I'm going to be out of circulation for a few days so if I don't spot what it is fairly quickly it could be the end of next week before I get back to you.

**Comment by wgshef** [comment]
I suspect that it has to do with marking the sheet active. When Excel open,
it does it automatically on that last sheet being used (unless you
shift-select multiple sheets), and this does not happen automatically with
Export-Excel.

It also looks like using -Activate makes that new sheet be the only one
that is active. I can live with this. However, I found this when doing
testing, and was deleting the new sheet and ended up deleting two sheets.
Then the file was saved before noticing that it deleted two sheets. So I do
think that there being a fix for this, even though using -Activate does
prevent it.

**Comment by jhoneill** [comment]
It seems to be a bug in EPPlus. 
If there are 2 sheets in the workbook and add a third, you can end up with the two pre-existing worksheets active ... and I get the same thing if I use moveBefore(1) or moveToStart. The .viewTabSelected property reports correctly but Excel doesn't process it correctly.

**Comment by scriptingstudio** [comment]
I confirm. It works like wgshef said.

**Comment by wgshef** [comment]
Well, it looks like I'll just use the -Activate switch to control this.
Thanks for looking into it.
