### ISSUE TITLE
PivotTable in folder with multiple Excel files

### ISSUE THREAD

**Issue by montell83** [dfinke/ImportExcel#677]
Hello Doug,

I would like to create a Pivot Table in multiple Excel files in a specific folder (the data in the Excel files is similar)

For a single file it is working perfect:

`$excel  = Open-ExcelPackage -path 'C:\Users\mvdheijden\tZ\Output\SvHve.xlsx'
$pivotTableParams = @{
PivotTableName     = "KruisTabel2"
Address                  = $Excel.Sheet1.cells["H1"]
SourceWorkSheet  = $Excel.Sheet1
PivotRows               = echo naam_vol_3 groep sis_leer_achternaam_ISNUL
PivotColumns        = echo code
PivotData               = @{Code="Count"}
PivotTableStyle = 'Medium6'
}

Add-PivotTable @pivotTableParams -PassThru
Close-ExcelPackage $excel -Show`

Hope you can help.

**Comment by dfinke** [comment]
What issues do run up against?

**Comment by montell83** [comment]
Hello Doug,

 I managed to solve the Problem. Sorry for bothering you.

`
$Bestanden = Get-ChildItem "C:\Users\mvdheijden\tZ\Output\" *.xlsx


ForEach ($Bestand In $Bestanden) {
$Excel2 = Open-ExcelPackage -Path $Bestand.fullname

Add-PivotTable -PivotTableName 'KruisTabel2' -Address  $Excel2.Sheet1.cells["H1"] -SourceWorkSheet $Excel2.Sheet1 -PivotRows (echo naam_vol_3 groep sis_leer_achternaam_ISNUL) -PivotColumns (echo code) -PivotData @{Code="Count"} -PivotTableStyle 'Medium6' -PassThru

Close-ExcelPackage $Excel2
}`

Thanks

**Comment by dfinke** [comment]
No problem, glad you worked it out.
