### ISSUE TITLE
Import-Excel - if worksheet is null but headers exist bug

### ISSUE THREAD

**Issue by jakedenyer** [dfinke/ImportExcel#68]
Doug - 

Ran into an issue when importing an RVTools spreadsheet with Import-Excel. The headers were there but the rest of the sheet didnt have any values. I was getting 1 null set of objects and one set where the headers were populated as objects. 

![image](https://cloud.githubusercontent.com/assets/3172395/12496546/79839700-c064-11e5-8bda-adfbda5dde40.png)

I took the simple approach and just did an if statement where if the $rows variable is equal to 1 then make the object you return $null - if not populate with data. 		

	if ($rows -eq 1)
	{
		[PSCustomObject]$h = $null
	}
	else 
	{			
		foreach ($Row in ($HeaderRow+1)..$Rows) {
			$h=[Ordered]@{}
			foreach ($Column in 0..($Columns-1)) {
				if($Header[$Column].Length -gt 0) {
					$Name    = $Header[$Column]
					$h.$Name = $worksheet.Cells[$Row,($Column+1)].Value
				}
			}
			[PSCustomObject]$h
		}
	}

Hopefully this helps someone.

**Comment by dfinke** [comment]
Thanks for reporting. Looks useful to add to the base. If you want to do a PR, I'll review and merge. Otherwise I'll investigate.

Thanks again.

**Comment by jvaldezjr1** [comment]
Was this ever resolved?  I doubt it, I'm getting the same problem with a spreadsheet I'm trying to import also.  There isn't any data actually being imported, even when I pass -Sheet and -HeaderRow options

**Comment by vandreytrindade** [comment]
Hi,

I'm having this problem too.
Downloaded version 2.2.7 and it still exists...
Any news about it?

**Comment by dfinke** [comment]
Thanks for the nudge. I've put this higher in my todo list.

**Comment by dfinke** [comment]
Please post and excel sheet that repros this issue. Thank you.

**Comment by vandreytrindade** [comment]
dfinke,

It happens with any new Excel file with headers and nothing below it.
I'll share using OneDrive:
https://1drv.ms/f/s!Apl4WBNDrxJFj_hRZjVLC6Xs6frPfw

**Comment by dfinke** [comment]
Thanks
