### ISSUE TITLE
Need Help: ConditionalFormatting 

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#680]
Hi,

my sheet has 5 columns (A-E). Column B contains my conditional text/value. 

Is there a way to check row by row if there's the text "FILE" in the cell of column B and to colorize the cells A-E of the row when true (BackgroundColor).

Thanks in advance!

**Comment by dfinke** [comment]
Did a quick look at the EPPlus library, nothing popped out. It looks like it may be doable in Excel. 

Here's a possible solution:

```powershell
$xlFile = "$env:Temp\conditional.xlsx"

rm $xlFile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
ColA,ColB,ColC,ColD,ColE
1,file,3,4,5
1,2,3,4,5
1,2,3,4,5
1,2,3,4,5
1,file,3,4,5
1,2,3,4,5
1,2,3,4,file
1,file,3,4,5
"@

$xl = $data | Export-Excel $xlFile -PassThru

$ws=$xl.Sheet1

$rows=$ws.dimension.Rows

for ($row = 1; $row -le $rows; $row++) {
    if($ws.Cells[$row,2].value -eq "file") {
        Set-Format -Range "$($row):$($row)" -WorkSheet $ws -BackgroundColor LightBlue
    }
}

Close-ExcelPackage $xl -Show
```

**Comment by evild3ad** [comment]
My input is a CSV file...what I have so far:

    $IMPORT = Import-Csv "Input.csv" -Delimiter ","
    $IMPORT | Export-Excel -Path "Output.xlsx" -FreezeTopRow -BoldTopRow -AutoSize -AutoFilter -WorkSheetname "My_WorkSheet" -CellStyleSB {
    param($WorkSheet)

    # BackgroundColor and FontColor for specific cells of TopRow
    $BackgroundColor = [System.Drawing.Color]::FromArgb(50,60,220)
    Set-Format -Address $WorkSheet.Cells["A1:E1"] -BackgroundColor $BackgroundColor -FontColor White

    # Source: FILE --> Green
    $FileColor = [System.Drawing.Color]::FromArgb(0,176,80)
    ForEach( $Row in $IMPORT )
    {
    if ($Row.Source -eq "FILE")
    {
    Set-Format -Address ??? -BackgroundColor $FileColor -FontColor White
    }
    }

    # HorizontalAlignment "Center" of columns A-D
    $WorkSheet.Cells["A:D"].Style.HorizontalAlignment="Center"
    }

**Comment by jhoneill** [comment]
In Doug's example use 

`Add-ConditionalFormatting -Address $ws.Dimension.Address -WorkSheet $ws -RuleType 'Expression' -ConditionValue '$B1="File"' -BackgroundColor Green   
`

This will set all cells to be green if B for that row = File.  

Notes
1. You must get the quotes right, excel needs double quotes in a formula. 
2. If you start at Row 1, use $B1 (always column B and this row).

**Comment by dfinke** [comment]
### Feels a bit magical

And it works.

```powershell
$xlFile = "$env:Temp\conditional.xlsx"

rm $xlFile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
ColA,ColB,ColC,ColD,ColE
1,file,3,4,5
1,2,3,4,5
1,2,3,4,5
1,2,3,4,5
1,file,3,4,5
1,2,3,4,5
1,2,3,4,file
1,file,3,4,5
"@

$xl = $data | Export-Excel $xlFile -PassThru

$ws=$xl.Sheet1

Add-ConditionalFormatting -Address $ws.Dimension.Address -WorkSheet $ws -RuleType 'Expression' -ConditionValue '$B1="File"' -BackgroundColor Green


Close-ExcelPackage $xl -Show
```

**Comment by jhoneill** [comment]
> ### Feels a bit magical
> And it works.
> 

Yeah that's often been said of my solutions :-)

**Comment by dfinke** [comment]
lol, wondered if you code with a wizards hat on :)

**Comment by evild3ad** [comment]
Works! ;-)

    $IMPORT = Import-Csv "Input.csv" -Delimiter ","
    $IMPORT | Export-Excel -Path "Output.xlsx" -FreezeTopRow -BoldTopRow -AutoSize -AutoFilter -WorkSheetname "My_WorkSheet" -CellStyleSB {
    param($WorkSheet)

    # BackgroundColor and FontColor for specific cells of TopRow
    $BackgroundColor = [System.Drawing.Color]::FromArgb(50,60,220)
    Set-Format -Address $WorkSheet.Cells["A1:E1"] -BackgroundColor $BackgroundColor -FontColor White

    # HorizontalAlignment "Center" of columns A-D
    $WorkSheet.Cells["A:D"].Style.HorizontalAlignment="Center"

    # Source: FILE --> Green
    $FileColor = [System.Drawing.Color]::FromArgb(0,176,80)
    Add-ConditionalFormatting -Address $WorkSheet.Dimension.Address -WorkSheet $WorkSheet -RuleType 'Expression' -ConditionValue '$B1="FILE"' -BackgroundColor $FileColor
    }
