### ISSUE TITLE
Sum up in Pivot uses count of rows

### ISSUE THREAD

**Issue by STT42** [dfinke/ImportExcel#681]
I have a monthly excel file that contains the printer-log that I can monitor the monthly prints. To automate the Pivot I use yout great module like this:
`Import-Module ImportExcel
$data = Import-Csv C:\temp\_ps-excel\PrintAudit.csv -Delimiter ',' -Encoding Default 
#($data).count
$p=@{show=$false; autosize=$true;Autofilter=$true; IncludePivotTable=$true}
$p.pivotrows= 'PrinterName'
$p.pivotdata= 'PageCount'
$data | Export-Excel test-1.xlsx @p`

The result is
![01](https://user-images.githubusercontent.com/54315263/65416863-0dd26c00-ddf9-11e9-8622-a8e52e925018.png)
The sum is 100 which is the total of lines in the test excel file (reduced of the original).
After I uncheck and check the value "PageCount" the correct totals are shown. (242 printed pages)
![02](https://user-images.githubusercontent.com/54315263/65417001-643faa80-ddf9-11e9-8ac5-8d96402af53c.png)
Is this a bug or do I use something wrong?

**Comment by dfinke** [comment]
`$p.pivotdata= 'PageCount'` defaults to `count`. Pass a hashtable to `-PivotData` and can specify `sum`.

```powershell$xlfile = "$env:TEMP\sumPivot.xlsx"

rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
South,banana,31
West,lemon,38
North,screwdriver,49
South,banana,61
South,kiwi,45
East,orange,70
East,pear,38
East,avocado,75
East,pear,86
North,lime,24
"@

$data | Export-Excel $xlfile -Show -IncludePivotTable -PivotRows Region -PivotData @{'TotalSold'='sum'} -Activate
```

**Comment by STT42** [comment]
Awesome! Works perfectly. Thanks for the quick support and explanation.
