### ISSUE TITLE
Want to edit Existing excel without changing the formats already made

### ISSUE THREAD

**Issue by avinasshkummar** [dfinke/ImportExcel#682]
Want to edit Existing excel without changing the formats already made 

I have an excel already. don't want to import it and make changes like freeze pane delete top rows how to achieve without losing format

**Comment by jhoneill** [comment]
if you want to work on the contents without importing and re-exporting  Use 
```
$e= open-excelPackage 
#do what you need to on $e
save-excelpackage $e
```
The other functions will all work on an open package
