### ISSUE TITLE
Decimal Places

### ISSUE THREAD

**Issue by Roadieuk** [dfinke/ImportExcel#683]
Firstly thank you for creating such a wonderful module 👍 

It may be that I am not using this correctly,  but dealing with spreadsheets with decimal places showing #.00  when the spreadsheet is imported, it loses this formatting.  Note: I have different formats for different cells.  This needs to be translated as it is into powershell objects.

Thankyou in advance

N.

**Comment by dfinke** [comment]
Thank you, glad it is helpful.

`Import-Excel` imports only the raw data, not the formatting. You'll need to apply formatting once the data is in PowerShell.
