### ISSUE TITLE
Export-Excel issue with embedded commas?

### ISSUE THREAD

**Issue by caderoux** [dfinke/ImportExcel#685]
I am pulling a set of data directly from a view in SQL Server using InvokeSql-Cmd and the result set looks like this (everything strings) before I pipe it to Export-Excel:

Observation.Name         : Stenosis
Observation.Structure    : Mitral valve
Observation.SubStructure : NULL
Observation.Context      : Findings
Observation.Certainty    : Definite
Observation.Value        : Moderate
STCodeSet                : 5,8

Observation.Name         : Stenosis
Observation.Structure    : Mitral valve
Observation.SubStructure : NULL
Observation.Context      : Findings
Observation.Certainty    : Definite
Observation.Value        : Moderate to severe
STCodeSet                : 5,9

Observation.Name         : Stenosis
Observation.Structure    : Mitral valve
Observation.SubStructure : NULL
Observation.Context      : Findings
Observation.Certainty    : Definite
Observation.Value        : Present
STCodeSet                : 5

When I pipe it to Export-Excel, the embedded commas in the STCodeSet column are removed in excel.  Which is obviously a problem when 5,9 turns into 59

I have temporarily gotten around this by putting double-quotes in the column returned by the view, but I'd prefer not to have those quotes show up in the cell.

I'm wondering if there is a setting I should add.  I'm not using many settings on Export-Excel:

    $ExcelParams = @{
        Path = "$(Resolve-Path -Path ".")\MasterOutputData.xlsx"
        BoldTopRow = $true
        AutoSize = $true
        ExcludeProperty = @("ItemArray", "RowError", "RowState", "Table", "HasErrors")
    }

    Invoke-Sqlcmd @SQLParams -Query "SELECT * FROM TEST.ObservationMaster" |
        Export-Excel @ExcelParams -WorksheetName "ObservationMaster"

**Comment by jhoneill** [comment]
Because "," is the thousand separator (even though it is in the wrong place) the number parser treats 5,2 like 5,200 
You have two options    
Use ` -NoNumberConversion "StCodeSet" ` to stop the number parser working on that column.  On the items where you only have one number excel will report that you appear to have a number saved as text. 
Or if you are pre-processing the data use `-replace "," ";" `  or `-replace "," ",  "`

**Comment by caderoux** [comment]
Thanks, that does indeed stop the attempted number conversion.  And now the behavior is as expected for me.

It would appear to me that this is potentially a bug for people who DO want numeric conversion.  If 5,2 is being parsed as a number, it's highly unlikely to be considered equivalent to 52 in any number formatting preference - it's far more likely to be considered equivalent to 5.2 if you are importing data that was formatted in a different locale.  Probably should consider emitting a warning or an error.

**Comment by jhoneill** [comment]
In the code we use  this 
```
 $number = $null
If ( [Double]::TryParse($v, [System.Globalization.NumberStyles]::Any, [System.Globalization.NumberFormatInfo]::CurrentInfo, [Ref]$number)  { $ws.Cells[$Row, $ColumnIndex].Value = $number}     
```                      

NumberStyles ALL allows thousands, Decimal point, currency sign, exponent, hex, leading or trailing minus sign , brackets, and white space before or after (but not in the middle of) the number

[System.Globalization.NumberFormatInfo]::CurrentInfo
Says what is used as the decimal point, thousands, currency symbol, and minus sign. 

So if you switch from English to French or German you get "5,2" is Five point two. And "5.2" will be parsed as a thousand separator in a strange place. One of those also puts a space with the thousand separator, and I think [double]::parse copes. 

Yes if you import data formatted for locale X on a machine formatted for Locale Y you can either get errors on data which should be valid, or the parse works but the result isn't what you expected. We rely on people not to do that :-)

**Comment by DarkLite1** [comment]
@jhoneill  is right, we rely on people to take care of this. For this reason we use the function below. Hope this helps you out.

```powershell
Function Use-CultureHC {
    <#
    .SYNOPSIS
        Function that permits us to run PowerShell code in another culture (regional settings).

    .DESCRIPTION
        This function allows us to run PowerShell code in another culture (regional settings).

    .PARAMETER Culture
        The culture ID you want to use: en-US (English), de-DE (German), nl-BE (Belgium), ..

    .PARAMETER Code
        PowerShell code, like a script block, that you want to run using the specified culture.

    .EXAMPLE
        Use-CultureHC en-US {Get-Date}
        Outputs the current date in US format.

    .EXAMPLE
        Use-CultureHC de-DE {Get-Date}
        Outputs the current date in German format.

    .EXAMPLE
        Use-CultureHC nl-BE {Get-Date}
        Outputs the current date in Iraq format.

    .EXAMPLE
        Use-CultureHC nl-BE {Get-TimeStamp}
        Outputs the current date and time in a Belgium format.

    .EXAMPLE
         [system.Globalization.CultureInfo]::GetCultures('AllCultures')
         This command will list all the supported cultures on the system.  #>

    Param(
        [Parameter(Mandatory)]
        [System.Globalization.CultureInfo]$Culture,
        [Parameter(Mandatory)]
        [ScriptBlock]$Code
    )
    Process {
        trap {
            [System.Threading.Thread]::CurrentThread.CurrentCulture = $currentCulture
        }
        $currentCulture = [System.Threading.Thread]::CurrentThread.CurrentCulture
        [System.Threading.Thread]::CurrentThread.CurrentCulture = $Culture
        Invoke-Command $Code
        [System.Threading.Thread]::CurrentThread.CurrentCulture = $currentCulture
    }
}

```

**Comment by jhoneill** [comment]
@DarkLite1   V. useful , thanks for sharing that. 
There will always be some cases where a string comes back and it uses a list separator which is treated a group marker or decimal point ... in another thread IP addresses like 10.102.101.100 are read as 10 billion, 102 million 101 thousand , one hundred because the . is the thousand separator . 

Changing culture to stop a column parsing as a number when it shouldn't may have other side effects - so it needs to be used wisely :-)
