### ISSUE TITLE
Regular expression based data validation

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#686]
Hello All,
I am looking at this [[example code for data validation]](https://github.com/dfinke/ImportExcel/blob/9e92f2dbc62ead97a78ad64bd11c033fb8cf7822/Examples/ExcelDataValidation/MutipleValidations.ps1#L63)

and want to check is it possible to setup regular expression based data validation  like 

```
$MoreValidationParams = @{
    Range          = 'B2:B1001'
    ValidationType = 'Formula' #suggest what is appropriate to use regular expression
    ValueSet       = '^[A-Z]{4}[-][A-Z]{3}[-][A-Z&]{2,6}[-][\w]{5}$"'
    ErrorBody      = "Your input should be as per the standard  "
}
```
from help  I see "Formula" but not sure I setup a regular expression comparison formula 

-Formula <Object>
        The [first] data value as a formula. Use absolute formulas $A$1 if (e.g.) you want all cells to check against the same list

        Required?                    false
        Position?                    named
        Default value                
        Accept pipeline input?       false
        Accept wildcard characters?  false

Use Case: End users are provided with an excel interface to capture data and we need real time front end validation rather than processing the excel and finding out the values provided are not as per rules. 

PS: This module is great and I am very grateful to @dfinke  @jhoneill  and the team and request them to keep up with the good work.

**Comment by jhoneill** [comment]
Simple answer is no. 
The validation we're adding  is this
![image](https://user-images.githubusercontent.com/16209593/65760379-cf98bd80-e114-11e9-82e6-42e71639a610.png)
  
You can put a _formula_ in but Excel doesn't have a formula for for regex, and there's no explict "Match" 
You can roll your own regex support add via VBA. See  https://analystcave.com/excel-regex-tutorial/  
so you would need to add the VBA for regex support and then add the validation. 


And thanks for the PS , it's appreciated.
