### ISSUE TITLE
Send-SQLDataToExcel result differs from SQL query

### ISSUE THREAD

**Issue by dampfklon** [dfinke/ImportExcel#689]
When I try to export a rather large query (140000 rows) via Send-SQLDataToExcel I experience a rather strange error. The excel file contents differ from a query by Management Studio. 

There is one row, which contains mainly NULL but on the rows with content this content gets duplicated into the other rows where it should be NULL.

Any hints to debug this issue?

**Comment by dfinke** [comment]
@jhoneill what is your take? Do we need to see data?

**Comment by jhoneill** [comment]
First check that you've got a fairly up-to date version as we did change how this worked a few months ago. Then I would:
(1). Look at the spreadsheet and note the row number(s) of the affected rows.  You will need to subtract 2 from the number(s) as table rows count from zero and Excel counts from one, and row 1 is used for headings so data row 0 is in excel row 2. 
(2). Load Send-SQLDataToExcel.ps1  and Export-Excel.ps1 into the ISE or VS Code whichever you are happier with and set breakpoints
 in Send-SqlDataToExcel at line 166  (" `if     ($DataTable.Rows.Count) {` "  
and in export Excel.at lines  635 (" `$ColumnIndex         += $InputObject.Columns.Count - 1`")  and 1054 (" `Write-Verbose -Message "Saved workbook $($pkg.File)" `")
(3) Run your script and when dropped into the debugger, use
`$DataTable.Rows[<<your row number - 2 >>]`
to verify that  what came back in the query is what you expect. 
(4) Press [f5] to resume. And when dropped into the debugger a second time  type 
`$InputObject.Rows[<<your row number - 2 >>] ` to check nothing has changed in passing it to Excel 
(5) then type ` $ws.cells["<<your row number>>:<<your row number>>"] | ft address,value`
and see if the right data was posted into excel 
(4) Press [f5] to resume. And when dropped into the debugger a third time  type 
` $ws.cells["<<your row number>>:<<your row number>>"] | ft address,value`  again to see if it was messed up before saving. 

I've got a bad feeling that if the data that comes back is as expected and it is wrong when posted to Excel that's a bug with EpPlus, and we might have trouble getting it fixed. You can still send the data to export-excel "old style" but the performance on this size of data won't be great.

**Comment by dampfklon** [comment]
I thought i would run 6.5.1 but there were multiple versions installed. I removed the old version and now the error does not longer occur.

I am sorry that i bothered you, thanks for the help.

**Comment by jhoneill** [comment]
No worries. If only they were all that easy to solve :-)
