### ISSUE TITLE
New-ConditionalText Issue

### ISSUE THREAD

**Issue by SwarfegaGit** [dfinke/ImportExcel#69]
I am trying to do the following but the highlighting does not work...

> $High = @('1'..'35')
> 
> Get-Process | Export-Excel -Path document.xlsx -ConditionalText $(
>     New-ConditionalText -Text $High
> )

If I swap $High for text such as '32' it will highlight correctly.
Also I notice that if I do highlight '32' it will trigger on cells containing 32 such as '725454232846574'

I guess I could do with the use of comparison operators as it seems that currently it's doing -like '*32*'.

Really love this module by the way, keep up the great work.

**Comment by chreestopher** [comment]
The below works for me

```
$High = @('1'..'35')

Get-Process | Export-Excel -Path document.xlsx -ConditionalText $(
    $high | foreach {
        New-ConditionalText -Text $_
    }
)
```

**Comment by dfinke** [comment]
Also, the default `-ConditionalType` for text matching is `ContainsText`, and you can change that.

![image](https://cloud.githubusercontent.com/assets/67258/12921864/2a78b542-cf1d-11e5-8549-9d2076d549f0.png)

**Comment by SwarfegaGit** [comment]
Thanks.  That code works but it's doing conditional text on every cell.  The reason being it is taking single numbers and matching it, for example -like *1*.  At least every cell in my workbook has a number in it.

Correct me if I am wrong but none of those -ConditionType paramters are what I would expect to match a "-eq"?  I need a -ConditionalType EqualTo.
