### ISSUE TITLE
AutoSize is not working correct (when top row is bold)

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#690]
Here's my code:

    $IMPORT = Import-Csv "C:\Input.csv"
    $IMPORT | Export-Excel -Path "C:\Output.xlsx" -FreezeTopRow -BoldTopRow -AutoSize -AutoFilter -WorkSheetname "My Excel" -CellStyleSB {
    # HorizontalAlignment "Center" of columns A-H
    param($WorkSheet)
    $WorkSheet.Cells["A:H"].Style.HorizontalAlignment="Center"
    }

It seems that -AutoSize uses the standard text and NOT the bold one, so I always have to correct the auto size manually in Excel. Is this a bug or do I have to use another command/code?

Thanks in advance!

**Comment by dfinke** [comment]
I think it is because `-AutoFilter` is rendered when the sheet is opened and cannot be calculated when the sheet is created.
