### ISSUE TITLE
Export-Excel changes SQL date datatype to datetime in excel

### ISSUE THREAD

**Issue by duncfair** [dfinke/ImportExcel#692]
I am creating a series of spreadsheets for users based on a Code assigned to each person, i.e. all the rows from a table where MRPC = x.

I am using an array and a foreach and it works perfectly except the date columns from excel are datetime in the resulting spreadsheets. Is there a way to force excel to conform to the datatype sent to it?

**Comment by jhoneill** [comment]
Have you tried using the Send-SQLDataToExcel instead of Export-Excel - this drops a table straight into the spreadsheet 
Export-Excel converts dates / times / datetime objects to a floating point number and formats them correctly. The easiest thing may be to format the columns as date after doing the import.

**Comment by dfinke** [comment]
@jhoneill does Send-SQLDataToExcel do any data type translation. I'm guessing the "drops it straight in" does the data as is?

**Comment by jhoneill** [comment]
Send-SQLDataToExcel hands export-excel a dataTable object, and a stack of parameters.
When Export-Excel sees one of those it just calls EpPlus's  LoadFromDataTable method - it's as light touch as possible ....  
[checks ... ]
After tossing the data over the wall , Export-Excel then looks for columns in the table whose dataType is dateTime or timespan and sets the format on those in Excel. 
But a data table looks like it uses .NET types so it's possible that you can't get a pure date back you only ever get DateTime. Meaning _format the columns._ is the way forward.

**Comment by dfinke** [comment]
Cool. Figured I'd ask "Joe Walsh" how you played that riff :)
