### ISSUE TITLE
[How-to] Set cell format to text (for IP address) on export?

### ISSUE THREAD

**Issue by Tuumke** [dfinke/ImportExcel#693]
We use a invoke-restmethod to get a patern set from our netscaler, and i want to use export-excel and format the column as text. So the IP address are displayed correctly.
Most IP address are displayed correclty, but some others are not.
Most that start with 92. or 77. are fine, but for example this one isnt. Display of cell is fine, but value is not.
Displayed as: 46.144.20.19
Value of cell is: 461442019

**Comment by dfinke** [comment]
@jhoneill - just throwing this out, wondering it has to do with the culture? 

```powershell
$data = ConvertFrom-Csv @"
IP,Id
46.144.20.19,Test1
77.144.20.19,Test2
92.144.20.19,Test3
"@

$xlfile = "$env:TEMP\testIP.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data | Export-Excel $xlfile -Show
```

![image](https://user-images.githubusercontent.com/67258/66493844-bed93780-ea84-11e9-9bd3-8852aa4a1c6d.png)

**Comment by jhoneill** [comment]
It's probably culture.  
@Tuumke  does 
`(Get-Culture).NumberFormat.NumberGroupSeparator `
Say that your thousands separator is "." ? 

You can stop export-excel trying to parse a column as a number with 
`-NoNumberConversion "IP"`
(assuming your column is named IP)  this will fix it even if it is something else.

**Comment by Tuumke** [comment]
[8:17:01] S:\> (Get-Culture).NumberFormat.NumberGroupSeparator
,
[8:17:01] S:\>
