### ISSUE TITLE
Get cell style

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#694]
I've been searching for a way to retrieve cell style.
I've looked at #568 too.
But, if I try to get style of any applied predefined style all values are empty.
```
$xl = Open-ExcelPackage <file>
$xl.<sheetname>.cells['A2'].style.fill.BackgroundColor

Theme Tint Rgb Indexed
----- ---- --- -------
         0           0

...

Theme Tint Rgb      Indexed
----- ---- ---      -------
         0 FFFF0000       0
```
After that I apply my style, and it works!
Is there a way to retrieve a predefined cell style values?

**Comment by dfinke** [comment]
@jhoneill ?

**Comment by jhoneill** [comment]
Have a look at `$xl.workbook.styles`
This has numberformats and namedstyles. 
But I think "black text, white background" is not hard coded, but picked up from  the system, so the default is empty. 
Excel also "knows" some styles like "good" and "bad" but doesn't add them to the file until you use them.
You can also look at at a table `$xl.<sheetname>.tables[0].tableStyle`  but the meaning of "medium 6" doesn't seem to be embedded in the XLSX but decided by Excel at run time.

**Comment by scriptingstudio** [comment]
Unfortunately, I found nothing useful. I drop it.
Yes. Looks like embedded styles are resolved and applied at run time.
