### ISSUE TITLE
Surprise table format

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#695]
I have a script that exports some AD group memberships.  Once exported to Excel, it opens the file, adds some header columns, saves it them launches the file. 
The data is a simple string array of groupname, membername, group description
```
$AllGroups | Export-Excel -BoldTopRow -TitleBold -autosize $file #-now #Export all that group info to csv file.
Add-AuditHeader $file 
. $file
```
```
Function Add-AuditHeader{
    $file = $args[0]
    $ExPkg =  Open-ExcelPackage $file
    $sheet1 = $expkg.Workbook.Worksheets["sheet1"]
    $sheet1.InsertRow(1, 5)
    Set-Format -Address $sheet1.Cells["A1"] -Bold -Value "Date Generated: "
    Set-Format -Address $sheet1.Cells["A2"] -Bold -Value "Generated by:"
    Set-Format -Address $sheet1.Cells["A3"] -Bold -Value "Data From:"
    Set-Format -Address $sheet1.Cells["A4"] -Bold -Value "Desc:"
    Set-Format -Address $sheet1.Cells["B1"] -Value $logdate 
    Set-Format -Address $sheet1.Cells["B2"] -Value "$Env:Username"
    Set-Format -Address $sheet1.Cells["B3"] -Value "Admin Group Membership"
    Set-Format -Address $sheet1.Cells["B4"] -Value "All members of listed groups"
    Close-ExcelPackage $expkg 
}
```
So what is the question?  See the "-now" on the export-excel line?  If I uncomment that, the excel file launches, it still has the header information added by Add-AuditHeader but now the data has been formatted as a Table with filters and alternate row coloring.  Why?

**Comment by dfinke** [comment]
Leaky abstraction? :)   

Off the top of my head, `-now` was originally a quick start to pipe data to Excel, and autosize, create a table and add filtering.

Sounds like that code path is being executed.  Maybe a bug? Or a bug disguised as a feature?

**Comment by ili101** [comment]
```
-Now [<SwitchParameter>]
    The -Now switch is a shortcut that automatically creates a temporary file, enables "AutoSize", "TableName" and "Show", and opens the file immediately.

-Show [<SwitchParameter>]
    Opens the Excel file immediately after creation. Convenient for viewing the results instantly without having to search for the file first.
```
Is it doing something different then the parameter definition?

**Comment by uSlackr** [comment]
Ah – confused show with now. I was afraid it would be simple :-/   I’m an idiot at times.
TY



\\Greg

________________________________

**Comment by dfinke** [comment]
Perhaps that switch shouldn't light up depending on what else is selected.

**Comment by uSlackr** [comment]
Is that something you can control?


\\Greg

________________________________

**Comment by dfinke** [comment]
Not sure at this point. The parameters got out of control, should've moved them off to something like `ExportExcelOptions` function. Changing that may introduce lots of issues across all the params.

**Comment by uSlackr** [comment]
Also, it is curious that me Add-AuditHeader code works with the -show and -now commands.  I'd expect the file to be open already.  I suspect this reflects the time it takes to launch Excel and load the file

**Comment by ili101** [comment]
> Ah – confused show with now. I was afraid it would be simple :-/ I’m an idiot at times. TY

Yeah this two names can be confusing, happen to me to.

Currently it works like this:
`-Now` defined OR (ExcelPackage AND Path) not defined - Now mode used

`-Now` set the following parameters: `-Path`, `-AutoSize`, `-TableName` and `-Show`. you can override any of this `-Now` setting by adding them like `-Path foo` or  `-AutoSize:$false`.

**Comment by dfinke** [comment]
`-Now` is obsolete pretty much. `ps | select company, name, handles | export-excel` does that. In the broader sense, combination of params is a challenge and can lead to issues,

**Comment by ili101** [comment]
> Not sure at this point. The parameters got out of control, should've moved them off to something like `ExportExcelOptions` function. Changing that may introduce lots of issues across all the params.

Yes something like what they did in `New-ScheduledTask`:
``` powershell
$A = New-ScheduledTaskAction -Execute "Taskmgr.exe"
$T = New-ScheduledTaskTrigger -AtLogon
$P = New-ScheduledTaskPrincipal "Contoso\Administrator"
$S = New-ScheduledTaskSettingsSet
New-ScheduledTask -Action $A -Principal $P -Trigger $T -Settings $S
```
But it will be a big change and you need to set the option/s and then pass to the command. that can be cleaner but more lines of code to write.

**Comment by ili101** [comment]
> `-Now` is obsolete pretty much. `ps | select company, name, handles | export-excel` does that. In the broader sense, combination of params is a challenge and can lead to issues,

The switch became more of an edge case over time, the only use left for the switch right now (maybe i'm missing something) is:
``` powershell
ps | select company, name, handles | Export-Excel -Path $Path -Now
```
Instead off:
``` powershell
ps | select company, name, handles | Export-Excel -Path $Path -AutoSize -TableName '' -Show
```

**Comment by dfinke** [comment]
Yeah, without telemetry, not sure if this a breaking change.
