### ISSUE TITLE
Export-Excel IncludePivotTable - problem with -MoveToStart

### ISSUE THREAD

**Issue by idav77** [dfinke/ImportExcel#697]
I have created the following script to loop through a folder of CSV files, convert to XLSX, and insert a Pivot Table for each one.  It works, however I want the Worksheet with the Pivot Table to appear as the first (Active) sheet, not the second.  I tried to achieve this using one of the following positional parameters, but none of them seem to work, wherever they are placed: [-MoveToStart] [-MoveToEnd] [-MoveBefore <Object>] [-MoveAfter <Object>]

Get-ChildItem -path c:\temp\PhoneBills | Foreach {

$file = $_;

Import-Csv -Path $file.FullName | Export-Excel -Path "C:\Temp\Output\$($file.Name.Replace('.csv','')).xlsx" `
        -ExcludeProperty "Bill sequence number","Invoice number","Account (BAN)","Sub account (BEN)","Allocation code 1","Allocation code 2","Allocation code 3","Allocation code 4" `
        -WorksheetName Spend `
        -IncludePivotTable `
        -PivotTableName "Summary" `
        -PivotRows "User name","Country of origin","Dialled number" `
        -PivotData @{Cost = 'Sum'} `
        -AutoSize `
}

Any suggestions as to what I might be doing wrong, or do I need to use a different function to achieve this? I am new to PowerShell and the fantastic ImportExcel tool, so apologies if I have missed the obvious.

**Comment by dfinke** [comment]
@idav77 can you post the PowerShell the that does the `Move`? How many sheets are there on the workbook after this loop runs?

@jhoneill May be an off by one issue? in Epplus?

**Comment by jhoneill** [comment]
It needs to be split into 2 or 3 commands to do it. 
Export-excel with -includePivotTable will (IIRC) create the pivot table on a new sheet at the end of the workbook. In the example above
`-IncludePivotTable -PivotTableName "Summary" -PivotRows "User name","Country of origin","Dialled number" -PivotData @{Cost = 'Sum'} 
`

comes out and` -passthru` goes in and the line becomes 
`$xl = import ... | export-excel  ....   -passthru `
Then add the pivot table
`Add-PivotTable -ExcelPackage $xl -PivotTableName "Summary" -PivotRows "User name","Country of origin","Dialled number"  -PivotData @{Cost = 'Sum'} -activate`

-activate makes it active.  Then you can move it to the start 

$xl.Workbook.Worksheets.MoveToStart("Summary")

and save & close
`close-excelpackage $xl  `

@dfinke  I don't think this is the Epplus activate multiple sheets issue.

**Comment by idav77** [comment]
> @idav77 can you post the PowerShell the that does the `Move`? How many sheets are there on the workbook after this loop runs?
> 
> @jhoneill May be an off by one issue? in Epplus?

**Comment by idav77** [comment]
Sorry closed in error.  The original script that did the Move is this:

Get-ChildItem -path c:\temp\PhoneBills | Foreach {

$file = $_;

Import-Csv -Path $file.FullName | Export-Excel -Path "C:\Temp\Output\$($file.Name.Replace('.csv','')).xlsx" `
        -ExcludeProperty "Bill sequence number","Invoice number","Account (BAN)","Sub account (BEN)","Allocation code 1","Allocation code 2","Allocation code 3","Allocation code 4" `
        -WorksheetName Spend -AutoSize `
        -IncludePivotTable `
        -PivotTableName "Summary" -MoveToStart
        -PivotRows "User name","Country of origin","Dialled number" `
        -PivotData @{Cost = 'Sum'} `
    }

**Comment by dfinke** [comment]
Yeah, you need to do it as a multi-step process as @jhoneill describes, using `-PassThru` in the line that creates the xlsx, then using the returned xl package to move the sheet, and finally closing it.

**Comment by idav77** [comment]
> It needs to be split into 2 or 3 commands to do it.
> Export-excel with -includePivotTable will (IIRC) create the pivot table on a new sheet at the end of the workbook. In the example above
> `-IncludePivotTable -PivotTableName "Summary" -PivotRows "User name","Country of origin","Dialled number" -PivotData @{Cost = 'Sum'} `
> 
> comes out and` -passthru` goes in and the line becomes
> `$xl = import ... | export-excel .... -passthru `
> Then add the pivot table
> `Add-PivotTable -ExcelPackage $xl -PivotTableName "Summary" -PivotRows "User name","Country of origin","Dialled number" -PivotData @{Cost = 'Sum'} -activate`
> 
> -activate makes it active. Then you can move it to the start
> 
> `$xl.Workbook.Worksheets.MoveToStart("Summary") `
> and save & close
> `close-excelpackage $xl `
> 
> @dfinke I don't think this is the Epplus activate multiple sheets issue.

Thanks so much for this, however, when trying this out I get the error:
"WARNING: Failed adding PivotTable 'Summary': Cannot index into a null array."

I get the same result just trying this on one file on its own:

$xl = Import-Csv -Path 'C:\temp\PhoneBills\xxxxx.csv' | Export-Excel -Path "C:\Temp\Output\yyyyy.xlsx" `
-ExcludeProperty "Bill sequence number","Invoice number","Account (BAN)","Sub account (BEN)","Allocation code 1","Allocation code 2","Allocation code 3","Allocation code 4" `
-WorksheetName Spend -AutoSize -PassThru

Add-PivotTable -ExcelPackage $xl -PivotTableName "Summary" -PivotRows "User name","Country of origin","Dialled number" -PivotData @{Cost = 'Sum'} -activate

Close-ExcelPackage $xl

**Comment by idav77** [comment]
Hi again, 

Apologies if I am not seeing something here (I am new to Powershell), but can anyone see a reason I might be getting the error:
"WARNING: Failed adding PivotTable 'Summary': Cannot index into a null array."

And same result just trying this on one file on its own:

$xl = Import-Csv -Path 'C:\temp\PhoneBills\xxxxx.csv' | Export-Excel -Path "C:\Temp\Output\yyyyy.xlsx" -ExcludeProperty "Bill sequence number","Invoice number","Account (BAN)","Sub account (BEN)","Allocation code 1","Allocation code 2","Allocation code 3","Allocation code 4"
-WorksheetName Spend -AutoSize -PassThru

Add-PivotTable -ExcelPackage $xl -PivotTableName "Summary" -PivotRows "User name","Country of origin","Dialled number" -PivotData @{Cost = 'Sum'} -activate

Close-ExcelPackage $xl

**Comment by idav77** [comment]
Figured it out - it needs a second Worksheet created before adding the pivot table:

Get-ChildItem -path c:\temp\PhoneBills | Foreach {

$file = $_;


$xl = Import-Csv -Path $file.FullName | Export-Excel -Path "C:\Temp\Output\$($file.Name.Replace('.csv','')).xlsx" `
   -ExcludeProperty "Bill sequence number","Invoice number","Account (BAN)","Sub account (BEN)","Allocation code 1","Allocation code 2","Allocation code 3","Allocation code 4" `
   -WorksheetName Spend -Autosize -passthru `

    Add-WorkSheet -ExcelPackage $xl -WorksheetName Summary

    Add-PivotTable -ExcelPackage $xl -PivotTableName Summary `
    -Address $xl.Workbook.Worksheets[2].Cells["A1"] `
        -SourceWorkSheet $xl.Workbook.Worksheets[1] `
        -PivotRows "User name","Country of origin","Dialled number" `
        -PivotData @{Cost = 'Sum'} -activate

$xl.Workbook.Worksheets.MoveToStart("Summary")

Close-ExcelPackage $xl

}
