### ISSUE TITLE
[Question]Convert to Html?

### ISSUE THREAD

**Issue by DanteNahuel** [dfinke/ImportExcel#698]
Is there any way to convert a Worksheet to HTML and save it as such?

**Comment by ili101** [comment]
If it's something basic you can do
```powershell
Import-Excel -Path "$Path\file.xlsx" | ConvertTo-Html | Out-File "$Path\file.html"
```

**Comment by fredswims** [comment]
That is very interesting. I observed two things. 
The resultant HTML does not render the format as it appears in the worksheet; e.g., Bold. 
If your columns span a Pivot Table, only the leftmost column is converted to HTML. 

I use the SAVE-AS feature in Excel to produce HTML output of my selected range. That produces HTML that renders very much as it is display.  I am in the process of writing a vba script to automate that.  Which brings up another point; Is there a way to call and activate a vba procedure in a specific module within a xlsm file?

**Comment by DanteNahuel** [comment]
@fredswims Yes, correct, it doesn't render the format, which I find very weird.
How do you use the Save-as feature in powershell?

**Comment by fredswims** [comment]
@DanteNahuel Sorry about that. I do not use Powershell to use the Excel Save-as feature. I manually kick-off VBA procedures and macros in an open spreadsheet. I would love to be able to kick-off those procedures from a Powershell script. Sorry for the misunderstanding.

**Comment by ili101** [comment]
```powershell
$XlsxFile = "$Path\date.xlsx"
$HtmlFile = $XlsxFile -replace '\.xlsx$', '.html'

#Add-Type -AssemblyName "C:\Program Files\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Office.Interop.Excel.dll"
#[int][Microsoft.Office.Interop.Excel.XlFileFormat]::xlHtml # 44
$xlFixedFormat = 44

$Excel = New-Object -ComObject "Excel.Application"
$null = $Excel.Workbooks.Open($XlsxFile)
$Excel.ActiveWorkbook.SaveAs($HtmlFile, $xlFixedFormat)
$Excel.ActiveWorkbook.Close()
$Excel.Quit()
```
* You need to have Excel installed for this to work

**Comment by fredswims** [comment]
@ili101 Thank you for the tip. 
I have an excel macro that finds the range of a pivot table on a particular worksheet and saves the selection as an HTML file. Now I can invoke it from Powershell. 
...
$objExcel.Run("SaveAsHtmlBoys")
....
Thank you for the inspiration.
