### ISSUE TITLE
[Q] How to avoid a request to save?

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#699]
Once xlsx built and saved with the module, next open & close with excel app it requests to save the doc.
I tried -Calculate switch, no effect.
Is xlsx rendered at runtime or there is a trick?

**Comment by jhoneill** [comment]
Usually there is some rendering when the file is opened in Excel, which triggers a request to save. -Calculate does remove this sometimes, but it depends on what is in the sheet.
