### ISSUE TITLE
Issue regarding a table name

### ISSUE THREAD

**Issue by jswiftca** [dfinke/ImportExcel#701]
The table I am exporting to Excel with this module, has headings like CustomAttibute1 . 
How do I change the headings in the Excel SS to something more informative, like Firstname , LastName, Gender   etc

**Comment by dfinke** [comment]
Please provide an example of the data and how you are working with it in PowerShell and using the module.

**Comment by jswiftca** [comment]
Many thanks for the quick reply, 
I just solved my own problem after I found the -headings parameter in the import function. 
Great functions, they have save med much time.
