### ISSUE TITLE
Import-Excel - Error when Workbook has One Sheet

### ISSUE THREAD

**Issue by NomisJohnson** [dfinke/ImportExcel#705]
I get an error when I import a workbook with one sheet; when I open, add another sheet and save, it works fine.  Is this expected?

Failed importing the Excel workbook "path" with worksheet '': Cannot index into a null array.

Much appreciated!

Simon

**Comment by uSlackr** [comment]
Can you share some code?


\\\\Greg

________________________________

**Comment by NomisJohnson** [comment]
Of course, it is just a one-liner right now:

`gci S:\path\Development\Working\*.xlsx  | % {Import-Excel $_ }`

**Comment by uSlackr** [comment]
I do this all the time and it works fine.  Can you share a file or snippet?


\\Greg

________________________________

**Comment by jhoneill** [comment]
Is the one sheet (or first sheet in workbook) empty ? It's possible we don't trap that.

**Comment by ImportTaste** [comment]
Could it be you're targeting the incorrect extension? xls will need to be converted to a newer format and macro-enabled sheets are xlsm.
