### ISSUE TITLE
New-ConditionalText

### ISSUE THREAD

**Issue by SwarfegaGit** [dfinke/ImportExcel#71]
Sorry to have to open this as a new issue but I responded to a closed issue I raised and never got a response.  I couldn't see a way to message you directly.  Could you take a look for me please?

https://github.com/dfinke/ImportExcel/issues/69

**Comment by dfinke** [comment]
Sorry, forgot to comment that when I closed it. Added Equal and NotEqual as types.

![image](https://cloud.githubusercontent.com/assets/67258/13291989/f7a5903c-dae7-11e5-9e62-70bd985b9ceb.png)
