### ISSUE TITLE
Get-ExcelColumnName again

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#714]
This expression looks strange:
```
			if ($columnName.length -eq 0) {
				[char](65 + $modulo)
			}
```
It will never work. It shoots output, not the variable. Even if it worked (imagine) you would get an array of 2 elements instead of just a string. The first element is string, the second one is pscustomobject. 
So shecking "if ($columnName.length -eq 0)" in cycle is overhead. 
It does not make sense using arraylist, because in typical case array will be very short.

I would suggest this solution:
```
function Get-ExcelColumnName {
	param (
		[Parameter(ValueFromPipeline=$true)]
		$columnNumber = 1
	)

	Process {
		$dividend   = $columnNumber
		$columnName = @()
		while ($dividend -gt 0) {
			$modulo      = ($dividend - 1) % 26
			$columnName += [char](65 + $modulo)
			$dividend    = [int](($dividend - $modulo)/26)
		}

		if ($columnName.count -gt 1) {[array]::reverse($columnName)}
		[PSCustomObject]@{
			ColumnNumber = $columnNumber
			ColumnName   = -join $columnName
		}
	}
}
```
It is faster than arraylist version (in this case).

**Comment by uSlackr** [comment]
I used the list to allow inserts in order to fix the problem without re-writing.  There may very well be better solutions.  Feel free to fork the code and submit a PR.
