### ISSUE TITLE
MIssing export property

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#715]
This is not an issue, per se, but I'm trying ti understand a behaviour.

If I create a custom object and add it to an empty array, then add a similar object with an additional property, then export from export-excel, the additional property is not exported.

If on the other hand, I add an object with the property to an empty array, then add one that doesn't have it, the object missing the additional property simply export it as empty.

How are the exported properties determined?

**Comment by dfinke** [comment]
https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L665

Works similar to the PS object flow engine.

```powershell
[PSCustomObject]@{a=1;b=2}
[PSCustomObject]@{a=3;b=4;c=6}
```

## Prints

```
a b
- -
1 2
3 4
```

**Comment by jhoneill** [comment]
Update-FirstObjectProperties is there to fix this. 

The properties of the first object set the headings for the sheet.

**Comment by uSlackr** [comment]
Excellent!  Thank you

\\Greg

________________________________
