### ISSUE TITLE
Filter pivot table in code

### ISSUE THREAD

**Issue by damonbreeden** [dfinke/ImportExcel#717]
I am automating some work done by my team and one of their tasks is, after a pivot table gets created they then filter on specific systems in the 'Columns' field (using the filter dropdown in Excel) and also they filter the top 10, and sort Z-A.

I have a lot of the code figured out but I can't see how to do this, and this is one of the last steps I need to automate. My code looks like this:

```
Import-Csv -Path $csvFile | Export-Excel -Path $excelFile -WorksheetName "AWR" -KillExcel -PivotTableDefinition @{
        "5 and 6P Buffer Gets" = @{
            "SourceWorkSheet" = "AWR";
            "PivotRows" = "MODULE";
            "PivotColumns" = "SID";
            "PivotFilter" = "Attribute";
            "PivotData" = @{"Value" = "Sum"};
            "IncludePivotChart" = $true;
            "ChartTitle" = "*5/6P Systems - Number of Buffer Gets";
            "ChartType" = "ColumnStacked3D"                            
        }
```
They then filter on specific values in 'PivotColumns'

Is there a way?

**Comment by dfinke** [comment]
Please, could you post a screen shot of the what the end result looks like.

**Comment by damonbreeden** [comment]
After the pivot table is complete they filter out for specific systems listed in one of the columns "SID":

![image](https://user-images.githubusercontent.com/49255023/68413605-91071180-015c-11ea-9291-58a853ee1942.png)

Additionally they sort and filter the Values:

![image](https://user-images.githubusercontent.com/49255023/68413693-bb58cf00-015c-11ea-94f0-885e61c153d6.png)

It's similar to what was mentioned on #349 but I can't understand how to use it from that discussion, or indeed if it was actually solved.

**Comment by damonbreeden** [comment]
Things I've tried:
```
"PivotFilter" = @{"SID" = @("A6P", "A7P")};
"PivotColumns" = echo A6P A7P;
"PivotColumns" = @("A6P", "A7P");
"PivotFilter" = "A6P", "A7P";
```

But no luck so far.

To be honest I don't know if I should be working with the PivotFilter param or the PivotColumn param. The manual process has them filtering on the Column ("SID"), but the Filter ("Attribute") never gets filtered in any case.

**Comment by dfinke** [comment]
Looping in @jhoneill

**Comment by jhoneill** [comment]
> ... My code looks like this:
> 
> ```
> Import-Csv -Path $csvFile | Export-Excel -Path $excelFile -WorksheetName "AWR" -KillExcel -PivotTableDefinition @{
>         "5 and 6P Buffer Gets" = @{
>             "SourceWorkSheet" = "AWR";
>             "PivotRows" = "MODULE";
>             "PivotColumns" = "SID";
>             "PivotFilter" = "Attribute";
>             "PivotData" = @{"Value" = "Sum"};
>             "IncludePivotChart" = $true;
>             "ChartTitle" = "*5/6P Systems - Number of Buffer Gets";
>             "ChartType" = "ColumnStacked3D"                            
>         }
> ```
> 
> They then filter on specific values in 'PivotColumns'
> 
> Is there a way?

This is one of the things we would love to have but doesn't seem to be possible.  The way you're using PivotFilter/Column/Rows/Data here is correct. They MUST be the names of columns in the data.  I haven't checked but I'd the other way you tried will result in quite messy errors. 

Basically the module calls a library named EPPlus which does all the stuff to write an XLSX file. That file contains the specification for the pivot table (take the cells from _here_, and make a pivot _there_ using _this_ as Filter/Column/Rows/Data. ). The Pivot table doesn't exist until Excel opens, takes the specification, and creates one. And it doesn't seem possible to specify values for filters until then. A similar problem applies to ordinary tables, you can say you want to create one with filters, but you can't apply the filter. 

The only way I can see to do it is to open the file in Excel (using com objects) and have PowerShell drive Excel. 
@dfinke  Did we have an example of that somewhere? I think we did but not trusting my memory. Just thinking we should bundle an example, with details of how to turn a recorded macro in Excel into a script .

**Comment by damonbreeden** [comment]
Thanks, I thought that may be how this was going to conclude.

I found on #300:
```
$path = "$Env:TEMP\test.xlsm"
$excel = $stuff | Export-Excel -Path $path -PassThru
$m = $excel.Workbook.VbaProject.Modules.AddModule("Module1")
$m.Code = @"
xxxx
"@
```
Plus (also #300):
```
$excel = New-Object -ComObject Excel.Application
$excel.Visible = $true
$workbook = $excel.Workbooks.Add()
$sheet = $workbook.ActiveSheet
$excel.Run('.\Documents\ExcelWithMacro.xla!Hello')
```

I think this is going to be the solution.

**Comment by dfinke** [comment]
@jhoneill could you say a bit more about PS driving Excel in this scenario? Not sure there was, sounds like a good idea.

**Comment by jhoneill** [comment]
@dfinke  In the style of Export-Charts.PS1. 

You can put the macro in another file and run it against  the one you've just made or 
You can record a macro , so I took the little results.xlsx that is made by the "first10Races.tests" script 
and recorded a macro which line breaks looks like this 

```
Sub Macro1()
   Sheets("Analysis").Select
    ActiveSheet.PivotTables("Analysis").PivotFields("Driver").AutoSort xlDescending _
        , "Sum of Points", ActiveSheet.PivotTables("Analysis").PivotColumnAxis. _
        PivotLines(1), 1
End Sub
```

That needs to be translated in PS syntax but can be called over com.

**Comment by dfinke** [comment]
@jhoneill that wasn't easy :)  Even ran into a timing issue, I think, adding the sleep worked.
Still leaves and Excel instance running too.

As I remember, useful and super brittle.

```powershell
$path = "$env:TEMP\Results.xlsx"

$excel = New-Object -ComObject excel.application
$workbook = $excel.Workbooks.Open($path)

Start-Sleep -Milliseconds 250

$sheet = $workbook.sheets.Item("Analysis")
$null = $sheet.Activate()

$workbook.ActiveSheet.PivotTables("Analysis").PivotFields("Driver").AutoSort(2, "Sum of Points", $workbook.ActiveSheet.PivotTables("Analysis").PivotColumnAxis.PivotLines(1), 1)

$null = $workbook.Save()

$excel.DisplayAlerts = $false
$workbook.Close($false, $null, $null)
$null = $excel.Quit()
$null = [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel)

Invoke-Item $path
```
