### ISSUE TITLE
New-ConditionalText Filters

### ISSUE THREAD

**Issue by SwarfegaGit** [dfinke/ImportExcel#72]
Thanks for added Equal / NotEqual as a Conditional Type.  Can you add the equivalent of:

-ge (greater than or equal)
-gt (greater than)
-le (less than or equal)
-lt (less than)

?

Also could you add a way to only apply the conditional text to select columns.

**Comment by dfinke** [comment]
Make you a deal, I'll label this an enhancement and since it is open source, why don't you dig deeper and see if you can find clues how to?

**Comment by dfinke** [comment]
Implemented https://github.com/dfinke/ImportExcel/commit/8f05e9d57d0d7b90143ff0820c9d3bdfe8feca1b
