### ISSUE TITLE
Incorrect table when supplying DataTable with zero rows

### ISSUE THREAD

**Issue by techabilla** [dfinke/ImportExcel#720]
Sending a DataTable with columns, but no rows, should result in an empty table with just the header row, but what I'm seeing is a table with no header row, and one data row that contains the column names.

Expecting to see:
![image](https://user-images.githubusercontent.com/32886354/68911776-f9ca3b80-07a5-11ea-852b-bb48799d767f.png)

Seeing:
![image](https://user-images.githubusercontent.com/32886354/68911786-02227680-07a6-11ea-84a3-a77108cf05c4.png)

My code:
```
            $exportParams = @{
                Path = $outputPath
                InputObject = $dataSet.DataTable
                WorksheetName = $dataSet.ExcelExport.WorksheetName
                TableName = $dataSet.ExcelExport.TableName
                HideSheet = $dataSet.ExcelExport.WorksheetName
                ClearSheet = $true
                ExcludeProperty = @('RowError', 'RowState', 'Table', 'ItemArray', 'HasErrors')
            }
    
            $xlPkg = Export-Excel @exportParams -PassThru
```

Having looked at the Export-Excel code I'd guess this is an EPPlus issue, but thought I'd post in case there is a simple workaround.

Great module btw; thanks for making my life easier!

**Comment by techabilla** [comment]
Code to demonstrate the problem

```
$d = new-object system.data.datatable
$d.Columns.Add("column1")
$d | export-excel
```
... as opposed to...
```
$d = new-object system.data.datatable
$d.Columns.Add("column1")
$d.Rows.Add("value1")
$d | export-excel
```

**Comment by techabilla** [comment]
Have struggled to find a workaround for this. Adding a dummy row allows the table to be created, but I haven't been able to reliable 'empty' the table from PowerShell. At present I'm running a macro in the spreadsheet that checks for tables with dummy rows, and deletes the data range.

**Comment by ili101** [comment]
Excel can't have a table without a row, So if you create one from MS Excel it will set up an empty row as @techabilla showed in "Expecting to see".

So we can add one row as shown in "Fix option 2" below which seems to work.
Or we can do it directly in LoadFromDataTable "Fix option 1" below (that's what I was using back when I head my module fork before we added the DataTable support here) .

```powershell
# Setup
$DataTable = [Data.DataTable]::new('Test')
$null = $DataTable.Columns.Add('ID', [Int32])
$null = $DataTable.Columns.Add('Name')
$Path = Join-Path ([IO.Path]::GetTempPath()) 'test.xlsx'

# Fix option 1 use LoadFromDataTable with the 3 params option to set the table natively in one step.
Remove-Item -Path $Path -ErrorAction SilentlyContinue
$Excel = Export-Excel -Path $Path -PassThru
$ws = $Excel.Workbook.Worksheets[1]
$null = $ws.Cells[1, 1].LoadFromDataTable($DataTable, $true , 'Medium6')
Close-ExcelPackage -ExcelPackage $Excel
. $Path

# Fix option 2 add a secund line to Range
Remove-Item -Path $Path -ErrorAction SilentlyContinue
$Excel = Export-Excel -InputObject $DataTable -Path $Path -PassThru
$ws = $Excel.Workbook.Worksheets[1]
Add-ExcelTable -Range $ws.Cells['A1:B2']
Close-ExcelPackage -ExcelPackage $Excel
. $Path
```

**Comment by jhoneill** [comment]
You have two different things here 

`$datatable | export-excel`

Will send rows 1 by 1 . You need to exclude the extra row properties which aren't data columns and an empty table creates an empty sheet 
```
$d = new-object system.data.datatable
$d.Columns.Add("column1")
$d | export-excel
```
Gives a blank sheet.  Totally expected. 

If you pass a table in Input object, it is inserted as single item.   A data-table with the n rows, creates an n+1 row excel-table with the first row as a header row.  

@ili101 seems to have found a bug in EPPlus, because it shouldn't behave differently if the style is set explicitly but it does.  
Looking further, the current version won't  set the style on an inserted data table. 
So. What I propose to do is fix both things.  
1. Give -TableStyle a default value of medium6 
Line 481 becomes ` [OfficeOpenXml.Table.TableStyles]$TableStyle =  [OfficeOpenXml.Table.TableStyles]::Medium6,`
2. Set the style on an inserted data-table to the passed or defaulted Table style.
Line 628 becomes     `$null = $ws.Cells[$row,$StartColumn].LoadFromDataTable($InputObject, (-not $noHeader),$TableStyle )`
3. Only create a table on other exports if -TableStyle or -TableName is passed as a parameter.   (This is happening already but I can simplify some bits around line 810)

@techabilla you can apply those changes, or pick them up from my fork  (will be a couple of hours before I can commit them and I haven't tested them yet)

**Comment by jhoneill** [comment]
In the version now on my fork, export-excel.ps1 is modified so 
$d = new-object system.data.datatable
$d.Columns.Add("column1")
export-excel -inputobject $d 

Now does what the first post expected.  All the tests pass but if someone would like to do a bit more of a test before I send Doug a pull request that would be great.

**Comment by ili101** [comment]
This makes Excel Table the only option for PS DataTables, don't we want to preserve the options to use AutoFilter and without anything?
If the table name is not unique change the name back after LoadFromDataTable to not change the input object itself.

**Comment by jhoneill** [comment]
I'll fix the name thing.  I only found when I ran the tests that when the table format is specified EPPlus also has a problem with a clash of names (it doesn't without), and that was a quick hack. 
I don't think the option was there to use autofilter and no table when there _were_ rows I'll check.

**Comment by jhoneill** [comment]
OK What we have is 
`send-sqlDataToExcel  `- only sends an _empty_ table to excel if `-Force` is specified. 
It calls `Export-Excel -InputObject <table> -allOtherParams`  so from there on the behaviour should be the same whether you use send or export. 

If no path, or excel package object is specified or if -Now is specified, then Export-Excel goes into "**Now mode**" which sets defaults for the path, show, Auto size, and Table settings if they are not already specified, and **formats as a table by default**.   If TableName is Boolean and false a table name won't be set and no table will be created (it can be written like a switch `-Table:$false`)  to prevent table formatting in Now mode. 

**Outside of "Now mode"** data is only formatted as a table **IF** either `-TableName `or `-TableStyle`  are passed as parameters. This applies to  data tables (regardless of the number of rows) or any other data. 

`export-excel -Path $path -InputObject $DataTable -WorksheetName "Foo" -TableName "bar" -Show`
displays this with an empty table
![image](https://user-images.githubusercontent.com/16209593/68992453-90106700-0863-11ea-8cd8-d0e0c28a69fa.png)

Which was the original expectation. 
This is in my fork now. If it does what people want I'll send a PR through :-)

**Comment by ili101** [comment]
@jhoneill changes looks good from first glance, I will do some tests to see if I can find any problems.

**Comment by ili101** [comment]
@jhoneill I made some small fixes and sent you a PR https://github.com/jhoneill/ImportExcel/pull/1
If everything looks good to you you can approve my PR and make a PR to @dfinke in my opinion

**Comment by techabilla** [comment]
> Excel can't have a table without a row, So if you create one from MS Excel it will set up an empty row as @techabilla showed in "Expecting to see".

True, in terms of what is visible on screen, but the key thing (for me at least), is that the `ListObject.ListRows.Count` property for the table return a 0. That's how I'm measuring the number of rows in the table.

**Comment by ili101** [comment]
@techabilla This part looks like an EPPlus issue.
I made a workaround editing the xml: https://github.com/ili101/ImportExcel/commit/9b7a8878dfcf7beb82327e3fc711a76a5344ad75#diff-2312e8cdbe09401310dc615fad4e8d83
You can get the file from here https://github.com/ili101/ImportExcel/blob/xml/Export-Excel.ps1 load it and try.

**Comment by techabilla** [comment]
@ili101, that works perfectly; thank you.

**Comment by ili101** [comment]
Updated to support auto names https://github.com/ili101/ImportExcel/commit/cc7d18cc593cca06638c54ad06729214bc598278 .
@jhoneill @dfinke is editing the xml considered ok? I can PR to jhoneill if so.

**Comment by dfinke** [comment]
There are a few places where the underlying xml is edited directly. I'm not a fan, but it's probably a stable change in that Microsoft won't change it over time.

**Comment by ili101** [comment]
Hi @techabilla do you know if this table with 1 blank line instead of an "empty table" problem show itself in other places other then the VBA command `ListObject.ListRows.Count`?
Excel formulas `=ROWS(Table1)` `=COUNTA(Table1)` `=ISBLANK(Table1)` ignores this setting as I can see.
The only way to see the difference in Excel without VBA is that when it's empty the "Delete Table Rows" is grayed out.
![image](https://user-images.githubusercontent.com/6960531/69066236-9fd9a800-0a29-11ea-8e5a-ea0c99ec7998.png)
Is this effects something other then that?
Thank you

**Comment by techabilla** [comment]
Hi @ili101, No, I've not seen any other problems.

**Comment by techabilla** [comment]
@ili101 , I did just find something strange in Excel though. My table row counting function is marked as Application Volatile, which should cause it to be recalculated after any change in the spreadsheet, but I noticed that this is not 100% reliable. When adding rows to a table, the function updates correctly. When removing rows (except the last), the function updates correctly. But, when removing the last row, the function doesn't update. Forcing a re-calculation does work though. I re-wrote the function using a different technique (passing the Table object directly as a Range), but the results were no different. Not sure this is at all relevant for ImportExcel, but thought I'd pass it on.

**Comment by ili101** [comment]
The DataTable table format fix is ready, and we have the workaround for the empty table flag.
@techabilla I'm not using VBA usually so I'm not very familiar with it.
I did some tests with your function and it works for me as expected:
![ex](https://user-images.githubusercontent.com/6960531/69136280-3e661780-0ac3-11ea-98de-ef7a8e789b0c.gif)
Table created as empty by the module (Count 0), writing something is detected (Count 1), deleting the string don't delete the line (Count 1), deleting the line deletes the line (Back to count 0).
So it looks like we now create the empty table exactly like if it was created from excel itself.
So what else can we help with?
If the workaround for the empty table flag is not useful to you I think we can drop it and go with only the format fix.

**Comment by techabilla** [comment]
The workaround in your fork is working for me, @ili101. No further questions. Thanks to everyone for their help on this, and for creating & maintaining such a useful module.

**Comment by dfinke** [comment]
@ili101, @jhoneill should this be merged?
