### ISSUE TITLE
Need Help: Add-ConditionalFormatting - Field contains keyword (no exact match)

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#721]
Hi,

when $E1 contains the keyword ".exe" (no exact match) I would like to colorize the row. It's only working with an exact match. But I have text before and after ".exe" in this field.

    $MyColor = [System.Drawing.Color]::FromArgb(0,176,80)
    Add-ConditionalFormatting -Address $WorkSheet.Dimension.Address -WorkSheet $WorkSheet -RuleType 'Expression' -ConditionValue '$E1=".exe"' -BackgroundColor $MyColor

I tested "\*.exe\*" and -RuleType 'ContainsText' without success.

Thanks in advance!

**Comment by jhoneill** [comment]
Try 

NOT(ISERROR(FIND(".EXE",$E1)))

For the condition.

**Comment by evild3ad** [comment]
May you share more information...full command? Tried several combinations without success.

**Comment by jhoneill** [comment]
![image](https://user-images.githubusercontent.com/16209593/68979917-dda2ba80-07f6-11ea-8228-7c61df36f9a8.png)

instead of` -ConditionValue '$E1=".exe"'`

**Comment by dfinke** [comment]
### Learning Excel

![image](https://user-images.githubusercontent.com/67258/68980704-3bbba780-07cf-11ea-86af-17759f2653e5.png)

```powershell
$xlfile = "$env:TEMP\testCondition.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
West,pear,73
North,avocado,11
North,drill,41
West,pear,75
East,pear,50
South,avocado,86
West,nail,55
East,screws,20
East,hammer,5
West,nail,80
"@

$xl = $data | Export-Excel $xlfile -PassThru

$p = @{
    Address = $xl.Sheet1.Dimension.Address
    WorkSheet = $xl.Sheet1 
    RuleType = 'Expression'
    BackgroundColor = 'Cyan'
    ConditionValue = 'NOT(ISERROR(FIND("West",$A1)))'
}

Add-ConditionalFormatting @p

Close-ExcelPackage $xl -Show
```

**Comment by evild3ad** [comment]
Works! Thanks!
