### ISSUE TITLE
sum of the specified column value

### ISSUE THREAD

**Issue by Arbelac** [dfinke/ImportExcel#723]
Hi,

I want to sum of the specified column value such as C column.

My desired output :

<img width="389" alt="EXCEL_rehEWurxAV" src="https://user-images.githubusercontent.com/48718701/68989520-2a1ee200-0859-11ea-948c-9b2cf6635d13.png">

2-  My another question is : after these results want to convert to the pie chart in another sheet. 

Here is my script : https://pastebin.com/hsTxeuKX

thanks for your reply

**Comment by jhoneill** [comment]
If you're inserting with add-excel table,  

I think what you want is **`-totalsettings = @{"Tb Size"="Sum"}`**

**Comment by Arbelac** [comment]
Hi jhoneill,

I'm newbie for this module. I'dont understand what you mean by add-excel table.  How can I use this add-exceltable command ? please clarify.

**Comment by Arbelac** [comment]
powershell not working correctly.  Where am I missing ? 

```
$xlfile = "c:\ToolBox\reports.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data2 = ConvertFrom-Csv -InputObject @"
ID,Price2
1,10000
2,20000
3,30000
"@

$excel = $data2 | Export-excel -path $xlfile -WorksheetName Price -AutoSize -BoldTopRow -StartRow 2
        $ws = $excel.Workbook.Worksheets['1']
       
        $Table = Add-ExcelTable -Range $ws.Cells[$($ws.Dimension.address)] -TableStyle Medium6 -TableName TEST1 -TotalSettings @{"Price2" = "Sum"}

$data3 = ConvertFrom-Csv -InputObject @"
ID,Price3
1,10000
2,20000
3,30000
"@

$excel = $data3 | Export-excel -path $xlfile -WorksheetName Price -AutoSize -BoldTopRow -PassThru -TableName TEST2
        $ws = $excel.Workbook.Worksheets['Price']
       
        $Table = Add-ExcelTable -PassThru -Range $ws.Cells[$($ws.Dimension.address)] -TableStyle Medium6 -TableName TEST2 -TotalSettings @{"Price3" = "Sum"}

# Get the sheet named Sheet1
$ws = $excel.Workbook.Worksheets['Price']

# Create a hashtable with a few properties
# that you'll splat on Set-Format
$xlParams = @{WorkSheet=$ws;Bold=$true;FontSize=18;AutoSize=$true}

# Create the headings in the Excel worksheet
Set-Format -Range A1  -Value "TEST1" @xlParams
Set-Format -Range A8 -Value "TEST2" @xlParams


# Close and Save the changes to the Excel file
# Launch the Excel file using the -Show switch
Close-ExcelPackage $excel -Show
```

**Comment by uSlackr** [comment]
Can you tell us what isn’t working or what error you receive?

\\Greg

**Comment by Arbelac** [comment]
Here is my error message : 

Cannot index into a null array.
At line:12 char:9
+         $ws = $excel.Workbook.Worksheets['1']
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At line:14 char:52
+ ... ble = Add-ExcelTable -Range $ws.Cells[$($ws.Dimension.address)] -Tabl ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

**Comment by jhoneill** [comment]
> `Cannot index into a null array.`
>  `     $ws = $excel.Workbook.Worksheets['1']

Means you haven't assigned $Excel to anything - the file is saved if you **don't**  specify ` -Passthru` when you run `Export-Excel `, if you want to use it in the next step it needs `-passthru` also I'd expect ['1'] to fail - use `['sheet1']`

```
$excel = $data3 | Export-excel -path $xlfile -WorksheetName Price -AutoSize  -PassThru 
$ws = $excel.Workbook.Worksheets['Price']
Add-ExcelTable -Range $ws.Cells[$($ws.Dimension.address)] -TableStyle Medium6 -TableName TEST2 -TotalSettings @{"Price3" = "Sum"}
Close-ExcelPackage $excel -Show
```

Line 1 puts data in a sheet named price and returns an excelPackage object. 
line 2. uses the excelPackage object to get a worksheet
Line 3 creates a table which covers the whole data area of the sheet, with SUM in the totals row for the "Price 3" column. 
Line 4 closes (and saves) the file and opens it in Excel

**Comment by Arbelac** [comment]
Unfortunately same result.
Script : 

```
$xlfile = "c:\ToolBox\reports.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data2 = ConvertFrom-Csv -InputObject @"
ID,Price2
1,10000
2,20000
3,30000
"@

$excel = $data2 | Export-excel -path $xlfile -WorksheetName Price -AutoSize -BoldTopRow -StartRow 2
$ws = $excel.Workbook.Worksheets['sheet1']
$Table = Add-ExcelTable -Range $ws.Cells[$($ws.Dimension.address)] -TableStyle Medium6 -TableName TEST1 -TotalSettings @{"Price2" = "Sum"}


$data3 = ConvertFrom-Csv -InputObject @"
ID,Price3
1,10000
2,20000
3,30000
"@

$excel = $data3 | Export-excel -path $xlfile -WorksheetName Price -AutoSize  -PassThru 
$ws = $excel.Workbook.Worksheets['Price']
Add-ExcelTable -Range $ws.Cells[$($ws.Dimension.address)] -TableStyle Medium6 -TableName TEST2 -TotalSettings @{"Price3" = "Sum"}
# Get the sheet named Sheet1


$ws = $excel.Workbook.Worksheets['Price']

# Create a hashtable with a few properties
# that you'll splat on Set-Format
$xlParams = @{WorkSheet=$ws;Bold=$true;FontSize=18;AutoSize=$true}

# Create the headings in the Excel worksheet
Set-Format -Range A1  -Value "TEST1" @xlParams
Set-Format -Range A6 -Value "TEST2" @xlParams


# Close and Save the changes to the Excel file
# Launch the Excel file using the -Show switch
Close-ExcelPackage $excel -Show

```

output  

<img width="161" alt="EXCEL_oFStFT1p8W" src="https://user-images.githubusercontent.com/48718701/69045546-1a91cb80-0a08-11ea-8e3c-e35ba833fc51.png">


My desired output:


<img width="96" alt="EXCEL_8ULGcH9yE6" src="https://user-images.githubusercontent.com/48718701/69045721-7f4d2600-0a08-11ea-85f6-276a214c7e7d.png">

**Comment by jhoneill** [comment]
```
$excel = $data2 | Export-excel -path $xlfile -WorksheetName Price
$ws = $excel.Workbook.Worksheets['sheet1'] 
```
You created a sheet named "price", and then try to use one with the name "sheet1"

You haven't saved it Then you re-start the same file 

```
$xlfile = "c:\temp\reports.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data2 = ConvertFrom-Csv -InputObject @"
ID,Price2
1,10000
2,20000
3,30000
"@

$excel = $data2 | Export-excel -PassThru -path $xlfile -WorksheetName Price -AutoSize -Title "Test1" -TitleBold -TitleSize 18 
$ws = $excel.Workbook.Worksheets['Price']
$dataArea = $ws.Dimension.Address -replace "A1","A2" #Skip title row

Add-ExcelTable -Range $ws.Cells[$DataArea] -TableStyle Medium6 -TableName TEST2 -TotalSettings @{"Price2" = "Sum"} -ShowHeader:$false -ShowFilter:$false
Close-ExcelPackage $excel -Show
```

![image](https://user-images.githubusercontent.com/16209593/69061575-53826e00-0a11-11ea-94e1-e087765fea74.png)

**Comment by Arbelac** [comment]
So how can I append TEST2 header ? Am I correct ?

```
$xlfile = "c:\temp\reports.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data2 = ConvertFrom-Csv -InputObject @"
ID,Price2
1,10000
2,20000
3,30000
"@

$excel = $data2 | Export-excel -path $xlfile -WorksheetName Price -AutoSize -Title "Test1" -TitleBold -TitleSize 18 
$ws = $excel.Workbook.Worksheets['Price']
$dataArea = $ws.Dimension.Address -replace "A1","A2" #Skip title row

Add-ExcelTable -Range $ws.Cells[$DataArea] -TableStyle Medium6 -TableName TEST2 -TotalSettings @{"Price2" = "Sum"} -ShowHeader:$false -ShowFilter:$false
#Close-ExcelPackage $excel

$data3 = ConvertFrom-Csv -InputObject @"
ID,Price3
1,10000
2,20000
3,30000
"@

$excel = $data3 | Export-excel -PassThru -path $xlfile -WorksheetName Price -AutoSize -Title "Test2" -TitleBold -TitleSize 18 
$ws = $excel.Workbook.Worksheets['Price']
$dataArea = $ws.Dimension.Address -replace "A5","A6" #Skip title row

Add-ExcelTable -Range $ws.Cells[$DataArea] -TableStyle Medium6 -TableName TEST3 -TotalSettings @{"Price3" = "Sum"} -ShowHeader:$false -ShowFilter:$false
Close-ExcelPackage $excel -Show
```

<img width="96" alt="EXCEL_8ULGcH9yE6" src="https://user-images.githubusercontent.com/48718701/69119663-53817d00-0aa8-11ea-9849-2fb8b26a83d6.png">

**Comment by jhoneill** [comment]
At the end of the first block put 
`$TableStart  = $ws.Dimension.rows +4 `

Then in the next export-excel line 
`-Startrow ($tableStart -1)`
 
and then data area for the table becomes 
`$dataArea = $ws.Dimension.Address -replace "A1","A$TableStart" `

$dimension will always give the top left to bottom right cell of the whole sheet, so if you are adding  to a sheet you need to allow for that.

**Comment by Arbelac** [comment]
Like you said I have done. But I am getting a result like below.

<img width="146" alt="EXCEL_n5ToyvS0IE" src="https://user-images.githubusercontent.com/48718701/69129826-512b1d00-0ac0-11ea-8f83-3f64d755d340.png">

script : 

```
$xlfile = "c:\temp\reports.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data2 = ConvertFrom-Csv -InputObject @"
ID,Price2
1,10000
2,20000
3,30000
"@

$excel = $data2 | Export-excel -path $xlfile -WorksheetName Price -AutoSize -Title "Test1" -TitleBold -TitleSize 18 -PassThru
$ws = $excel.Workbook.Worksheets['Price']
$dataArea = $ws.Dimension.Address -replace "A1","A2" #Skip title row

Add-ExcelTable -Range $ws.Cells[$DataArea] -TableStyle Medium6 -TableName TEST2 -TotalSettings @{"Price2" = "Sum"} -ShowHeader:$false -ShowFilter:$false


$TableStart = $ws.Dimension.rows +4

$data3 = ConvertFrom-Csv -InputObject @"
ID,Price3
1,10000
2,20000
3,30000
"@

$excel = $data3 | Export-excel -PassThru -path $xlfile -WorksheetName Price -AutoSize -Title "Test2" -TitleBold -TitleSize 18 -Startrow ($tableStart -1)
$ws = $excel.Workbook.Worksheets['Price']
$dataArea = $ws.Dimension.Address -replace "A1","A$TableStart"

Add-ExcelTable -Range $ws.Cells[$DataArea] -TableStyle Medium6 -TableName TEST3 -TotalSettings @{"Price3" = "Sum"} -ShowHeader:$false -ShowFilter:$false
Close-ExcelPackage $excel -Show
```

**Comment by jhoneill** [comment]
This is because you are starting a new file in the second step, without saving it after the first 
So $ws.Dimension.Address runs from A9 to B13 instead of A1 to B13. 

if you have a passthru object and have not saved the file,  replace ` -path $xlfile` with` -excelPackage $excel` in the second step. Then you can add the second set of data, create the second table, and finally write the file.

**Comment by Arbelac** [comment]
thanks for your help. Now I solved my issue. Also , I didn't get answer for my another issue.
My another question is : I need to show the total number (TEST1:60000 and TEST2:60000) of price taken at the report and the % of the total for each type in pie chart in another sheet.

**Comment by Arbelac** [comment]
Any comment ?

**Comment by jhoneill** [comment]
If you know which column the data is in, the total is always in the last row. 
So you build up a list of cells to total.  If you start with 
$TotalCells = @() 

And then so where you have $tablestart =  add
`$totalCells += ("X" +$ws.Dimension.End.Row)`
 
You can get the formula with 
$Formula = $totalCells -join "+"

Then  
$ws.cells[<<row>>,<<column>>].Formula = $formula will put value in the cell

**Comment by the04dude** [comment]
@dfinke @all - I am trying to set the word "Total" into cell A5 of this image, but when I try Set-ExcelRange it does not override the built in total row settings from the excel table.  is this possible?

New here - please LMK if I should have started a new thread?  Thanks.

![image](https://user-images.githubusercontent.com/5123864/103386387-98aa1800-4acc-11eb-8853-d7c317142613.png)
