### ISSUE TITLE
Unable to Format PivotTable Pivot ROW as integer

### ISSUE THREAD

**Issue by idav77** [dfinke/ImportExcel#724]
Hi, thanks again for this amazing module.

In the below example, I am unable to get the PivotTable rows to format as integers.  The PivotData formats correctly, using PivotNumberFormat. Set-Format works correctly in the main sheet but not in the Pivot Table sheet, where the rows appear in Column B.  Any ideas?

Get-ChildItem -path c:\temp\PhoneBills | Foreach {
file = $_;
$xl = Import-Csv -Path $file.FullName -Encoding Default | Export-Excel -Path "C:\Temp\Output\$($file.Name.Replace('.csv','')).xlsx" `
   -ExcludeProperty "Bill sequence number","Invoice number","Account (BAN)","Sub account (BEN)","Allocation code 1","Allocation code 2","Allocation code 3","Allocation code 4" `
   -WorksheetName Spend -Autosize -AutoFilter -FreezeTopRow -BoldTopRow -passthru `

    Add-WorkSheet -ExcelPackage $xl -WorksheetName Summary

    Add-PivotTable -ExcelPackage $xl -PivotTableName Summary `
        -Address $xl.Workbook.Worksheets[2].Cells["B2"] `
        -SourceWorkSheet $xl.Workbook.Worksheets[1] `
        -PivotRows "User name","Country of origin","Dialled number" `
        -PivotData @{"Cost (£)"= 'Sum'} -activate -PivotNumberFormat "£#,##0.00" -PivotTableStyle Dark9
       
$xl.Workbook.Worksheets.MoveToStart("Summary")

#Works to format "Dialled Number" column in data sheet:
Set-Format $xl.Workbook.Worksheets[2].Cells["E:E"] -NumberFormat '0'

#Does not work to format Pivot Rows in Pivot Table:
$sheet2 = $xl.Workbook.Worksheets["Summary"]
Set-Format -Address $sheet2.Cells["B:B"] -Numberformat '0'

Close-ExcelPackage $xl

}

**Comment by dfinke** [comment]
Could you also post a sample csv file?

**Comment by idav77** [comment]
Thanks, uploaded as .txt as .csv seems to be unsupported as upload format:

[TEST USER.txt](https://github.com/dfinke/ImportExcel/files/3854479/TEST.USER.txt)

**Comment by dfinke** [comment]
I moved the `Set-Format $xl.Workbook.Worksheets["Spend"].Cells["E:E"] -NumberFormat '0'` before the the creation of the pivot table, no luck.

Can you get the formatting you want when have the sheet open in Excel?

If you can, try to replicate that in the script.

**Comment by idav77** [comment]
Yes, I can format the numbers in the open sheet without any issues.  I will have a go, thanks for looking.

**Comment by dfinke** [comment]
You could try searching `EPPlus Pivot format number`

**Comment by jhoneill** [comment]
Er. For  phone numbers you want the full number in the data export as a text string and then to use -NoNumberConversion  but your source data has already converted the phone number into 3.80673E+11 etc

The pivot table can specify "when you calculate the numbers , format them like this". But it can't specify anything to do with the labels (which is what the phone numbers are).  

What you need to here is simple. **Cheat**. These aren't numbers you calculate with, they are labels, so even with your last few digits turned to 0000 you can make them into text and use the text in the pivot like this 

```
$xl = {as before}
**Set-ExcelColumn -Worksheet $xl.Spend -Heading "Dialled Text" -Value {"=Text(E$row,""0"")"}**   
Add-WorkSheet {as before}

Add-PivotTable {as before - except **"Dialled number"** becomes **"Dialled Text"**}`
```

**Comment by idav77** [comment]
I have tested this and this works!  Thank you so much, this is so helpful to me!
