### ISSUE TITLE
Add UpdateRecord `ScriptMethod` to each row imported

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#725]
@jhoneill  - Working to add an UpdateRecord `ScriptMethod` to each row being imported.

https://github.com/dfinke/ImportExcel/commit/04f62e68d7cc35c7bf33200011b8c992ef391f7e

The `write-verbose` shows the correct row number, but the `UpdateRecord` method does not. I tried `GetNewClosure()` in the `Add-Member` call `$targetMethod.GetNewClosure()`, but it throws:

```
Exception calling "GetNewClosure" with "0" argument(s): "The attribute cannot be added because variable WorksheetName with value  would no longer 
be valid."
```

This is shows without using `GetNewClosure`.

![image](https://user-images.githubusercontent.com/67258/69012491-7e52c080-0944-11ea-84e9-1e95b2e83a67.png)

**Comment by jhoneill** [comment]
Hmm. I'm only seeing part of the story but once you have fetched the rows, the worksheet, excel package etc will all go out of scope , which sounds like the error message.

**Comment by dfinke** [comment]
Yeah, seems the error msg may be misleading. The data has been transformed to the $NewRow hash and the scriptblock for the ScriptMethod is using $R which is just the int, row number.

Interesting...
