### ISSUE TITLE
Adding multiple sheets in loop with only one save

### ISSUE THREAD

**Issue by c1arkbar** [dfinke/ImportExcel#727]
I am trying to loop over a dictionary and create a worksheet for each item in the dictionary.  My initial approach works but takes a big time hit because I it is exporting and saving on each pass.  A watered down example of this approach is below. 

foreach ($x in Get-Process | Where-Object {$_.Id -lt 1000}) { 
    Export-Excel -Path ./test.xlsx -ClearSheet -WorkSheetname $x.Id -Title $x.Name 
}

I end up with the desired result with each process ID as a new worksheet.  This example only takes a few seconds but for my use case it will be doing this about 70-100 worksheets with rows of data for each sheet anywhere from 30-100 rows.
![image](https://user-images.githubusercontent.com/22199785/69074335-c8937a80-09f4-11ea-9bab-a81293b8850c.png)

I have attempted to use the passthru and then a final save at the end but I am over writing my data and only ending up with the last result as a worksheet.  This method is almost instantaneous compared to the above method.
foreach ($x in Get-Process | Where-Object {$_.Id -lt 1000}) { 
    $excel = Export-Excel -Path ./test.xlsx -ClearSheet -WorkSheetname $x.Id -Title $x.Name -PassThru
}
Close-ExcelPackage $excel

![image](https://user-images.githubusercontent.com/22199785/69074631-5d967380-09f5-11ea-9c79-40e80dc331a3.png)

Can someone please assist me in setting this up so that I am not overwriting each previous worksheet.  I have attempted to add the ( += ) to my code but I get an error because there is no method named "op_Addition"
$excel += Export-Excel -Path ./test.xlsx -ClearSheet -WorkSheetname $x.Id -Title $x.Name -PassThru

**Comment by jhoneill** [comment]
the second and subsequent though the loop you need to do time you need to use 
`export-excel -excelPackage $excel`

It can be easier as 
```
$excel = Open-ExcelPackage ./test.xlsx -Create 
foreach () { $excel = whatever | export-excel -excelPackage $excel -passthrough <<etc>> }
Close-excelpackage $excel
```

**Comment by c1arkbar** [comment]
Thank you @jhoneill! The open package is exactly what I needed!
