### ISSUE TITLE
Export-Excel: Named column headers not working

### ISSUE THREAD

**Issue by Sevententh** [dfinke/ImportExcel#728]
Hi all,

Anybody know why the following will not export correctly? The values in the exported excel are nonsense. However, If I remove from the Select statement
**@{Name="SKU"; Expression={$TextLic}}** 
then it works fine

Simplified Code:
`
$Sku = @{
"O365_BUSINESS"					     = "O365 Business"
"POWER_BI_PRO"					     = "Power BI Pro"
"STANDARDPACK"					     = "Enterprise Plan E1"
"ENTERPRISEPACK"					 = "Enterprise Plan E3"
"ENTERPRISEPACKLRG"				     = "Enterprise Plan E3"
"ENTERPRISEWITHSCAL"				 = "Enterprise Plan E4"
}
#There are more rows in this - removed for example

$licensetype = Get-MsolAccountSku | Where {$_.ConsumedUnits -ge 1}
$LicenseTypeReport = "c:\tmp\Office365_Licenses_v1.0.xlsx"

foreach ($license in $licensetype) 
{ 
    $TextLic = $Sku.Item(($license.accountskuid -replace ":", ""))
    If (!($TextLic))
    {
        write-Verbose($license.accountskuid)
    }
    else
    {
        write-Verbose($TextLic)
        Get-MsolUser -all | where {$_.isLicensed -eq "True" -and $_.licenses.accountskuid -contains $license.accountskuid} | Select @{Name="SKU"; Expression={$TextLic}}, DisplayName, FirstName, LastName, Office, userprincipalname, City, Country, Department | Out-String | Export-Excel -Path $LicenseTypeReport -WorksheetName ($license.accountskuid -replace ":","_")
    }
} 

write-Verbose ("Script Completed.")
`

**Comment by scriptingstudio** [comment]
There is at least one error in expression: where {$.isLicensed -eq "True" -and $.licenses.accountskuid -contains $license.accountskuid}. $_.xxxx instead of $.xxxx. Operator -contains works with arrays - check your variables.

**Comment by jhoneill** [comment]
@scriptingstudio  I think that is because the two _ chars have been turned into "italic" by mark down. 

Sending anything through Out-string on the way to export-excel will not give a good result.  

Simple way to debug it. Remove | out-string | export-Excel ...

**Comment by dfinke** [comment]
Every time you use `Out-String`, PowerShell kills a kitten

**Comment by Sevententh** [comment]
Cheers guys, this worked by removing **| out-string**
I had also tried using **| format-table** which also didn't work

**Comment by scriptingstudio** [comment]
@Sevententh format-table and out-string kill objects so they should be used at the end of pipe

**Comment by jhoneill** [comment]
> @Sevententh format-table and out-string kill objects so they should be used at the end of pipe

And **only at the end** of the pipe. 

Generally if it is named Export- , Format- or Out-   it should be the last thing in a pipeline.  
The one exception being format- | out-file Foo.txt
