### ISSUE TITLE
New-ConditionalText Range, Export-Excel should assume -autorange if not supplied

### ISSUE THREAD

**Issue by jrich523** [dfinke/ImportExcel#73]
The help didnt really exist so I ran in to some problems using New-ConditionalText with a Range. Was only able to figure it out once i found the examples folder.

If no -Range or -AutoRange is supplied on Export-Excel it should assume autorange.

**Comment by dfinke** [comment]
Thanks, could say a bit more or post an example of what you ran up against?

**Comment by jrich523** [comment]
rm gps.xlsx -ea 0
gps | select processname,path | Export-Excel -Path gps.xlsx -ConditionalText $(
New-ConditionalText -Text System -ConditionalTextColor Red -Range ProcessName
)

This causes errors because -RangeName or -AutoRangeName was not used. However, whats the point in specifying -AutoRangeName if i cant use ConditionalText without it? Shouldnt you just check if ConditionalText is supplied, and if so, check for RangeName, and if not ASSUME AutoRangeName?

You're making me specify AutoRangeName when without it, all it does is error and fail


a get-help on Export-Excel only provides examples (very basic ones at that) and no parameter definitions.
on New-ConditionalText there is nothing as far as help.

**Comment by dfinke** [comment]
Perhaps. Range for `New-ConditionalText` can also be an Excel Range `A:A` for a column or `2:2` for a row or `A21:B36`

**Comment by jrich523** [comment]
So if New-ConditionalText has its Range specified in cell notation, rather than object property, i would assume you dont need -RangeName or -AutoRangeName provided?

What is autorangename doing? I would imagine it looks at the property names and figures out what location they are at and if a property name is specified figures out what column it is and uses that?

**Comment by dfinke** [comment]
` -AutoRangeName` uses the first row of the spreadsheet to create Excel named ranges. I implemented so I could use those named ranges when building charts.

I don't think I'll connect the conditional formatting to this or implement logic around it.

**Comment by jrich523** [comment]
gotcha,
it would be nice if the new-conditionaltext looked to see if the range made sense, and then if not, automatically implement the AutoRangeName on the export-excel... but.... i imagine that would be prohibitively difficult..

**Comment by dfinke** [comment]
It's also making too many guesses at the the intent of the script.
