### ISSUE TITLE
Send-SQLDataToExcel -Append // The last row of data is overwritten by a header

### ISSUE THREAD

**Issue by AlexBillon07** [dfinke/ImportExcel#730]
Powershell 5.1 and 6.2.1
ImportExcel 6.2.4 and 6.5.2

The command Send-SQLDataToExcel with the paramter -Append is not working correctly.

The header row is repeated and the last line of the previous table is overwritten by the header row.
![image](https://user-images.githubusercontent.com/33461310/69239112-c7e81900-0b99-11ea-8a6e-d1cbc47f3564.png)

Here is a script to reproduce the bug easily

```powershell
#Requires -Modules ImportExcel

$folder = "C:\temp"
$filePrefix = "File"
$fileName = "{2}_{0:yyyyMMddHHmmss}_{1}.xlsx" -f [datetime]::Now, [System.IO.Path]::GetRandomFileName(), $filePrefix
$path = Join-Path -Path $folder -ChildPath $fileName

# Create datatable
$dt = [System.Data.DataTable]::new()
[void] $dt.Columns.Add("Counter")
[void] $dt.Columns.Add("Field1")
[void] $dt.Columns.Add("Field2")

for ($i = 1; $i -le 3; $i++) {
    $row = $dt.NewRow()
    $row.Counter = $i
    $row.Field1 = "1st Field"
    $row.Field2 = "2nd Field"

    $dt.Rows.Add($row)
}

# Create Excel Package
$objExcel = Open-ExcelPackage -Path $path -Create 

# Insert 3 times the datatable
for ($i = 1; $i -le 3; $i++) {
    $objExcel = Send-SQLDataToExcel -DataTable $dt -ExcelPackage $objExcel -PassThru -WorksheetName $filePrefix -Append  -BoldTopRow
}

# Creation of file
Close-ExcelPackage -ExcelPackage $objExcel -Show
```

I hope this is clear enough

**Comment by dfinke** [comment]
@jhoneill do you want to hold off merging your last PR to see if this needs a fix?

**Comment by jhoneill** [comment]
-`Append` and the `LoadFromDataTable`  bits we use to avoid row-by-agonising-row writing are totally unaware of each other.  
Normally we go
```
write headers 
for each data row {move down 1 , write data}
```
for append we say
```
don't write headers 
Position cursor on last data row 
for each data row {move down 1 , write data}
```
for datatable we say 
```
{
Accept wherever the cursor is
LoadFromDataTable $inputObject, -not(NoHeader) <tableStyle>
}
```
That's not going to work with append as it is. I can fix it. If you want to sit on the PR for a few hours  :-)

**Comment by dfinke** [comment]
Yup. No rush. Won't be able to merge till later in the week.

**Comment by jhoneill** [comment]
I've added it to my fork - although I haven't added tests for it. All current tests still pass, so I'm fairly happy I'm not breaking anything 

The logic now is 
for datatable we say

```
{
   if we are appending  {
       increment row
       LoadFromDataTable $inputObject, $false #no header, no table style
       if table name was passed, OR a pre-existing table covers the whole sheet.  {
           [re]Create the Exceltable covering the old and new data
       }
   }
   else { 
      Accept wherever the cursor is
      LoadFromDataTable $inputObject, -not(NoHeader) <tableStyle>
  }
}
```

There is one case which I don't cover at the moment and has only occurred to me since I uploaded which is 
`Send-sql ... <with either table name or style>`
Creates an excel table. If name is omitted table name is used; if style is omitted medium6 is used. Then 
`Send-sql -append `
Extends the excel table over the appended data

`Send-sql ... <without table name or style>`
Adds the data with no excel table styling. 
`Send-sql -append  <with table NAME> `
Creates an excel table over the extended data. But `Send-sql -append  <with table STYLE> ` does not. 

I'll fix that. And add some tests. 

@AlexBillon07  would you like to try the version that's on my fork and let us know if it works for you?

**Comment by AlexBillon07** [comment]
@jhoneill 

I have now all the data but the top header disappeared.

![image](https://user-images.githubusercontent.com/33461310/69338533-b3705300-0c63-11ea-8568-a5475f9e98dd.png)


Plus, I have warnings :
```
WARNING: Failed adding named range '1' to worksheet 'File': Exception lors de l'appel de « Add » avec « 2 » argument(s) : « Name 1 contains invalid characters »
WARNING: AutoNameRange: Testing '' caused an error. This should be harmless, but a change of property name may be needed..
WARNING: Range name '1st Field' contains illegal characters, they will be replaced with '_'.
WARNING: Failed adding named range '1st_Field' to worksheet 'File': Exception lors de l'appel de « Add » avec « 2 » argument(s) : « Name 1st_Field contains invalid characters »
WARNING: AutoNameRange: Testing '' caused an error. This should be harmless, but a change of property name may be needed..
WARNING: Range name '2nd Field' contains illegal characters, they will be replaced with '_'.
WARNING: Failed adding named range '2nd_Field' to worksheet 'File': Exception lors de l'appel de « Add » avec « 2 » argument(s) : « Name 2nd_Field contains invalid characters »
WARNING: AutoNameRange: Testing '' caused an error. This should be harmless, but a change of property name may be needed..
WARNING: Failed adding named range '1' to worksheet 'File': Exception lors de l'appel de « Add » avec « 2 » argument(s) : « Name 1 contains invalid characters »
WARNING: AutoNameRange: Testing '' caused an error. This should be harmless, but a change of property name may be needed..
WARNING: Range name '1st Field' contains illegal characters, they will be replaced with '_'.
WARNING: Failed adding named range '1st_Field' to worksheet 'File': Exception lors de l'appel de « Add » avec « 2 » argument(s) : « Name 1st_Field contains invalid characters »
WARNING: AutoNameRange: Testing '' caused an error. This should be harmless, but a change of property name may be needed..
WARNING: Range name '2nd Field' contains illegal characters, they will be replaced with '_'.
WARNING: Failed adding named range '2nd_Field' to worksheet 'File': Exception lors de l'appel de « Add » avec « 2 » argument(s) : « Name 2nd_Field contains invalid characters »
WARNING: AutoNameRange: Testing '' caused an error. This should be harmless, but a change of property name may be needed..
```

**Comment by ili101** [comment]
@AlexBillon07 I made a comment on this in the PR in the same time you wrote you comment (:
Basically ignore -Append in the first loop (Ignore -Append if the ws is empty)
Probably not a perfect solution but it's better.

**Comment by jhoneill** [comment]
@ili101 / @AlexBillon07  Sorry recently started a new gig and coding late at night when my brain isn't working very well. I'll fix the missing header if you append with nothing in the file. The blank header rows is what causes the warnings.

**Comment by AlexBillon07** [comment]
@jhoneill No problem. The module is already so great and it is good that you keep it alive !
