### ISSUE TITLE
Export Google Sheet to Xlsx

### ISSUE THREAD

**Issue by blhf** [dfinke/ImportExcel#734]
Can I use this to export google sheet to a xlsx file?

**Comment by blhf** [comment]
https://stackoverflow.com/questions/27403907/can-excel-retrieve-data-from-google-drive-excel-spreadsheet I saw this link and wonder if this module can do this. Thank you

**Comment by dfinke** [comment]
No. This approach doesn't support query from web. The last time I played with Google sheets there was a REST API you can access the Google sheets, but that is not part of this module.
