### ISSUE TITLE
ImportExcel, New-ConditionalText, color the full line

### ISSUE THREAD

**Issue by lea13000** [dfinke/ImportExcel#737]
Bonjour,

I woul like, with Export-Excel, color the full line according to the value of a single column.
![image](https://user-images.githubusercontent.com/58072857/69429327-90ad6f80-0d33-11ea-925d-3b0c4d6f7e7a.png)
When B= Stopped, the full line is red.

For this, I would like to used this '=$B1="Stopped"'.

Here is the code : 

```
$ExcelParams = @{
    Path = $env:TEMP + '\Exceltest.xlsx'
    Show = $true
    Verbose = $true
}
Remove-Item -Path $ExcelParams.Path -Force -EA Ignore
$ct2 = New-ConditionalText -Range "A1:H8" -ConditionalType Equal  -ConditionValue  '=$B1="Stopped"' -ConditionalTextColor Red -BackgroundColor White
Get-Service | 
Select Name, Status, DisplayName, ServiceName |
Export-Excel @ExcelParams -ConditionalText $ct2 

```
But when I open Excel, it's looking for all the cells with **_=$B1="Stopped_** (Black) instead of  formula (Grenn) 
![image](https://user-images.githubusercontent.com/58072857/69428922-aa9a8280-0d32-11ea-853d-620e81b49420.png)

Thank you !

**Comment by jhoneill** [comment]
Bonjour ! 

It need the type to be "Expression" otherwise it searches for "=$B1" as text

The formula is entered without the first = sign - I can't remember if we remove it so  

`$ct2 = New-ConditionalText -Range "A1:H8" -ConditionalType Expression  -ConditionValue  '$B1="Stopped"' -ConditionalTextColor Red -BackgroundColor White 
`
Should do what you need.

**Comment by lea13000** [comment]
Thank you for your reply, 

Unfortunately... 
![image](https://user-images.githubusercontent.com/58072857/70418208-47fbf300-1a63-11ea-97d7-047578917022.png)

The argument "Expression" is not recognized.

**Comment by jhoneill** [comment]
Hmmm.  It looks like we didn't add expression to the types allowed in New-Conditional text 


`$ct2 = @{range= "A1:H8"; RuleType='Expression' ; ConditionValue=  '=$B1="Stopped"'; ForegroundColor="Red" ; BackgroundColor="White"} `
Should work until we can fix that .  
The names are the same as the parameters for ADD-ConditionalFormatting.

**Comment by lea13000** [comment]
Super it's good! Thank you so much !!!!!
One last question, how to select up to the last line of my file?
I tried with this : 

`"@{range= "A1:Range(`A` & Rows.Count).End(xlUp).Row" `
But i think I don't have a good method

**Comment by lea13000** [comment]
finally I will work on my complete file, so I remove range : 
`$ct2 = @{ RuleType='Expression' ; ConditionValue= '=$B1="Stopped"'; ForegroundColor="Red" ; BackgroundColor="White"} `
because by default it works on the complete file.

Thank you so much !!!!!
