### ISSUE TITLE
How to set the format of a column ( only contains numbers) to "text" with the true value 

### ISSUE THREAD

**Issue by SilenceLzx0311** [dfinke/ImportExcel#739]
A column in a Excel are numbers, and I need to change it to "text".
After using below cmd.

$x = Open-ExcelPackage $FilePath\$ExcelName
$y = $x.sheet1
Set-ExcelColumn -Worksheet $y -Column 3 -NumberFormat 'Text'
Close-ExcelPackage -ExcelPackage $x

The format is still not proper. 
For example, the value is 1090512990000000000, but it shows 1.09051E+18.
I knew that set the numberformat to '0' will make it looks OK, but actually I need to set the format to 'Text' and the value showing 1090512990000000000.
Could anyone kindly help on it?

**Comment by jhoneill** [comment]
I thought you meant you wanted "true for a number and something else for zero" 
[Green]"Positive";[Red]"Negative";[Blue]"Zero"

If you want text you can use =text(A1,"############################")

or you can format the cell with ##################
You'll need to use 18 # signs if the number goes to 10^18
