### ISSUE TITLE
Append data to existing worksheet

### ISSUE THREAD

**Issue by j123b** [dfinke/ImportExcel#74]
I can't find any way to append data to existing worksheet in excel file.
Data are always overwritten - no matter whether I use a parameter -WorkSheetname or not.
Anyone can help?

**Comment by dfinke** [comment]
There is no built in way to append data. You can use Import-Excel to read the data from the sheet, append the new data and then pipe back to Export-Excel.

**Comment by jhoneill** [comment]
I have implemented this. Hopefully I will upload later this week.

**Comment by sheldonhull** [comment]
I'm sorry @jhoneill  I'm totally missing how to do this. I've had to manually track a counter to do startrow for now which is confusing/error prone. Is there a way for me to continue to append to a worksheet built in now?

**Comment by dfinke** [comment]
I don't believe that got submitted

**Comment by jhoneill** [comment]
I will check what has happened with this - I thought I had submitted it, but I'm working with a version which is out of sync with what is here on GitHub,

**Comment by jhoneill** [comment]
Yes, from (IIRC) V4.0.4 you can use -Append and it will put the data in at the end of the sheet.

**Comment by dfinke** [comment]
It is in
