### ISSUE TITLE
Formating 

### ISSUE THREAD

**Issue by smadon** [dfinke/ImportExcel#740]
Hello,
First, sorry, I am not sure, I am asking in the correct place :-(

I would like to add on my excel export a auto-formatting on modification.
I would like that if somebody is doing modification on the excel I just created with the script Export-excel, that the modification will appear in a different color.
I attached the exemple of the option in Excel.
![ExcelConditionFormating](https://user-images.githubusercontent.com/4699304/69788387-ad77f600-11be-11ea-96df-025b600ade13.png)

Is this option possible with the conditionFormating?
Thanks for your help
Smadon

**Comment by dfinke** [comment]
![image](https://user-images.githubusercontent.com/67258/69807984-9e8c4600-11b4-11ea-86e9-1dd21c2dfa31.png)


```powershell
$xlfile = "$env:TEMP\test.xlsx"

rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
South,pear,67
North,melon,17
North,drill,28
West,hammer,26
South,avocado,49
East,lime,28
East,drill,93
South,kiwi,92
South,orange,52
South,kiwi,79
North,ham,32
"@

$cf1 = New-ConditionalText -ConditionalType Equal -Text hammer -BackgroundColor Aqua
$cf2 = New-ConditionalText -ConditionalType Equal -Text ham

$data | Export-Excel $xlfile -Show -ConditionalText $cf1, $cf2
```

**Comment by jhoneill** [comment]
If you want dynamic formatting, you need to create the sheet twice, and hide and protect one copy. Then in the visible, writable, copy you can have conditional formatting which says if the cells are not equal to their twin, make them red (or whatever). 

If you want to see how workbook X is different from workbook Y have a look at the Compare function in the module.
