### ISSUE TITLE
ConvertFrom-ExcelSheet enhancement

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#741]
### Issues:
- impossible to customize date format
- impossible to prevent formatting at all

### New parameters:
[string]$dateformat
[switch]$asText

### Changes in code:
```
$importparam = @{asText = $asText}
if ($dateformat) {$importparam['dateformat'] = $dateformat} 
foreach ($sheet in $targetSheets) {
    Write-Verbose "Exporting sheet: $($sheet.Name)"

    $params.Path = "$OutputPath\$($Sheet.Name)$Extension"

    Import-Excel $Path -Sheet $($sheet.Name) @importparam | Export-Csv @params
}
```

I would have added alias for the function, `[alias('ExportFrom-Excel')]`

**Comment by jhoneill** [comment]
Slightly confused. 
There is already an as text option. Since people are bound to want some columns as text and  some not, it is used as -asText * for all columns or -astext col1,col2,colx* for specific columns. 

dates come back as dates. You format them the same as the date returned by any other command.

**Comment by scriptingstudio** [comment]
'Astext' there is in import-excel not in ConvertFrom-ExcelSheet. Import-excel returns dates in default format, but I need it in custom format. That is why I have to customize ConvertFrom-ExcelSheet after module update.

**Comment by jhoneill** [comment]
Sorry, I saw the import-excel in the body and didn't read the title which said you were talking about ConvertFrom-Excel sheet. Convert probably should take -AsText and pass it through to Import. 

Import-excel does not turn dates into strings. 
```
>import-excel C:\temp\test.xlsx

Date                Name
----                ----
06/01/2001 00:00:00 Lucy
21/12/2005 00:00:00 Peter
```
Above, PowerShell is applying default formatting for dates (UK  in my case) , below it is applying a custom format 
```
>import-excel C:\temp\test.xlsx | ft @{f="MMMM-dd-yy";e='Date'},Name

Date           Name
----           ----
January-06-01  Lucy
December-21-05 Peter
```

I'll give some thought to what is the best thing to do for the export. Possibly supporting a `-Properties`  parameter in the style of a` Select-Object` ; I know you want something which transforms dates, but someone else will want different things on different columns, and another person will want to format numbers. If I can make one change to solve the problem for all those cases that's better.

**Comment by scriptingstudio** [comment]
Oh, I forgot that I have used a custom version of import-excel introduced -dataformat parameter because I needed 'dd-MM-yyyy' format.
