### ISSUE TITLE
[Feature] AWS Support

### ISSUE THREAD

**Issue by forensicsguy20012004** [dfinke/ImportExcel#747]
### The SitRep

* **As a:** User of the ImportExcel Powershell Module
* **I want:** To be able to use this module with AWS Lambda functions
  * Meaning the module should be allowed to be imported into a lambda function
  * The excel document should be able to be written to S3
* **So that:** I can create reports or csv files for use in my Big Data processing

-----

**Acceptance Criteria:**
 - [ ] TBD

------

**Tasks:**
 - [ ] TBD

**Comment by dfinke** [comment]
## Powershell Azure Function Return Excel File

It should work in AWS.

I did a write up on how to do this on Azure. Here it creates a REST endpoint you can access from a browser or Invoke-RestMethod, and will return an Excel file that gets created on Azure and is stored in Blob Storage.

https://github.com/dfinke/powershell-azure-function-return-excel-file

You need figure out how to install the module, then you can call from PowerShell, store the resulting xlsx and return it via the http request.

**Comment by forensicsguy20012004** [comment]
* @dfinke ... so far the very basics are working
  * utilizing Powershell 7 preview x64

```
#Requires -Modules @{ModuleName='AWSPowerShell.NetCore';ModuleVersion='4.0.0.0'}}
#Requires -Modules @{ModuleName='ImportExcel';ModuleVersion='6.5.3'}}
```

**Comment by forensicsguy20012004** [comment]
* The only problem I am running into is writing the file locally
* As you can see from the example below the variable ```$export``` holds the data object I want as an excel report
* However, in an AWS Lambda function I am not **guaranteed** any local storage during execution of the lamdba function...hence  ```-Path $FileNameExcel``` becomes a problem
   * However, AWS does have a Powershell cmd as well as .Net that would allow me to stream a data object to a bucket...
     * That said..can I pump Export-Excel to an independent object? If I can then I can stream the object, I think we would be golden

```
$export | Export-Excel -Path $FileNameExcel -WorkSheetname "Data" -TableName "Data" -TableStyle Medium15 -AutoSize -BoldTopRow  -AutoNameRange  `
-ConditionalFormat $(
    New-ConditionalFormattingIconSet -Range "C:C" -ConditionalFormat ThreeIconSet -IconType Arrows
    ) -ConditionalText $(
        New-ConditionalText stopped -ConditionalTextColor Red
    )
```
Here is the AWS Powershell cmd to upload via a stream
![image](https://user-images.githubusercontent.com/12624999/70439498-2b10f100-1a5e-11ea-9949-ca5797854e9b.png)
