### ISSUE TITLE
Additional Freeze Options for Export-Excel

### ISSUE THREAD

**Issue by pdwud** [dfinke/ImportExcel#75]
Could you add additional switches for -FreezeFirstColumn and -FreezeTopRowAndFirstColumn for the Export-Excel function?

I think they would just need to be added as parameters and this code added around line 304:

if($FreezeFirstColumn) {
            $ws.View.FreezePanes(1,2)
        }

if($FreezeTopRowAndFirstColumn) {
            $ws.View.FreezePanes(2,2)
        }

I'm not married to the names.

**Comment by dfinke** [comment]
C'mon, do a PR ;-)   I'll investigate. Did you try that code. did it work?

**Comment by pdwud** [comment]
Sorry :)  I'm just learning Git.  Actually, I didn't sign up until today and it's all thanks to your ImportExcel module!

I can try it but figured I'd throw it out there.

**Comment by dfinke** [comment]
No worries. Glad you signed up. It's the first step towards doing a PR.

Great suggestion too!

**Comment by dfinke** [comment]
Added, you need to grab it from github, I will publish it to the gallery at a later time.

Thanks for the suggestion.

https://github.com/dfinke/ImportExcel/commit/b6e7a59337a83f8ac6b2de913df1eae17ae17602

**Comment by pdwud** [comment]
You're fast!  I was just going to let you know I tested it and confirmed it works.  Thanks!

**Comment by dfinke** [comment]
Great. Hopefully what I changed works for you. Let me know if it doesn't.

**Comment by pdwud** [comment]
Looks great.  Nice addition with -FreezePane.

I'll try to learn how to do PRs and such so I can contribute more efficiently.  Thanks again, Doug!  I appreciate your work with this module.
