### ISSUE TITLE
How to add a cell value for subtotal row?

### ISSUE THREAD

**Issue by wangjy0909** [dfinke/ImportExcel#750]
dear all, i have a worksheet and format as table with such code:
```
![exp](https://user-images.githubusercontent.com/31000620/70489857-ca55e700-1b37-11ea-947a-9559ae6b4816.png)

$file = "C:\Users\admin\Documents\testfor billing.xlsx"
$excel = Export-excel $file -WorksheetName sheet1 -AutoSize -PassThru
$ws = $excel.Workbook.Worksheets['sheet1']
#echo $ws.Name.ToString()
$dataArea = $ws.Dimension.Address
Add-ExcelTable -Range $ws.Cells[$DataArea] -TableStyle Medium1 -TableName invioce -TotalSettings @{"Server price" = "Sum"; "sum" = "Sum";"Storage price" = "Sum"} -ShowHeader:$true -ShowFilter:$false  -ShowTotal:$true
Close-ExcelPackage $excel
```
I have 2 questions:
1. Now i need to add "Total" in the first cell of subtotal row. i tried 'Set-Format' command, but i can't set the value. not this command?
2. i don't find a command to get the SUM value of subtotal, return's null. can we get the SUM values of subtotal?

**Comment by wangjy0909** [comment]
![exp](https://user-images.githubusercontent.com/31000620/70489906-f1acb400-1b37-11ea-9576-b8f7820fa6d3.png)

this is the excel example. thanks.

**Comment by wangjy0909** [comment]
![exp](https://user-images.githubusercontent.com/31000620/70489982-291b6080-1b38-11ea-8fb9-33aeee0674ee.png)

**Comment by wangjy0909** [comment]
![exp](https://user-images.githubusercontent.com/31000620/70490047-5700a500-1b38-11ea-8898-681c34682303.png)

**Comment by dfinke** [comment]
The `Value` property on the subtotal is null. I suspect it is because it is part of the Table Structure in Excel. Not sure if there is a way to get that. @jhoneill may know of a method call or a way in to the XML.

![image](https://user-images.githubusercontent.com/67258/70575215-04dd7500-1b74-11ea-9a0a-d9db19efa3f6.png)

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
North,peach,6
South,hammer,17
South,orange,99
East,hammer,99
West,apple,65
West,lemon,59
East,peach,97
West,screwdriver,12
East,lime,20
West,hammer,96
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -AutoSize -PassThru

Add-ExcelTable -TableName iTable -Range $xl.Sheet1.Cells[$xl.Sheet1.Dimension.Address] -TotalSettings @{"TotalSold"="sum"} -ShowTotal -ShowHeader -ShowFilter:$false

Set-Format -Range 'A13' -Worksheet $xl.Sheet1 -Value 'Total'

Close-ExcelPackage $xl -Show
```

![image](https://user-images.githubusercontent.com/67258/70575350-58e85980-1b74-11ea-821c-fdd57ca5d720.png)

**Comment by jhoneill** [comment]
EPPlus can evaluate the subtotal but you need to force it to do so with 

`[OfficeOpenXml.CalculationExtension]::Calculate($xl.Workbook)`

I think if you set a value in the totals row it may be overwritten when excel loads the file. 
The alternative would be to manually write =Sum() or subtotal values to the row after the table
