### ISSUE TITLE
Need help: Conditional Formatting --> Color Scales

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#751]
How can I use following via ImportExcel:
Conditional Formatting --> Color Scales --> Green-Yellow-Red Color Scale for example for column D?

(Highest value = red, lowest value = green)

Thanks in advance!

**Comment by jhoneill** [comment]
```
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
North,peach,6
South,hammer,17
South,orange,99
East,hammer,99
West,apple,65
West,lemon,59
East,peach,97
West,screwdriver,12
East,lime,20
West,hammer,96
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -AutoSize -PassThru

$lastrow = $xl.Sheet1.Dimension.end.Row
$cf =  Add-ConditionalFormatting -Worksheet $xl.Sheet1 -Address "C2:C$lastrow" -RuleType TwoColorScale -PassThru -Reverse
$cf 

Close-ExcelPackage $xl -Show
```

$cf will show you the value of the conditional formatter - it goes from red-low to green-high by default and the `-reverse` switch makes green low and red high. 

You can change the the low/high to come be based on a value, or percentile, and so on, and pick your own color values.

**Comment by evild3ad** [comment]
Works! Thank you!

I changed only TwoColorScale to ThreeColorScale...looks much prettier.
