### ISSUE TITLE
[Question] Download a single file from repo via script 

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#752]
After refactor old download links got broken.
The link to download the master repo is `https://github.com/dfinke/ImportExcel/archive/master.zip`.
Say, I would like to download something from `Public` folder, what link would it be?

**Comment by jhoneill** [comment]
I just downloaded master from https://codeload.github.com/dfinke/ImportExcel/zip/master which contains the public folder. 
https://raw.githubusercontent.com/dfinke/ImportExcel/master/Public/Add-ConditionalFormatting.ps1
WIll get a file from the public folder directly.

**Comment by scriptingstudio** [comment]
That worked perfect! Thanks.
