### ISSUE TITLE
Import-Excel module help

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#756]
This is more of a question than an issue but how does one use the `Get-Help` to see the help text provided?

For example the file `Public\ConvertFrom-ExcelSheet.md` is available that contains the examples but they are not shown when the module is imported and the following is run `Get-Help ConvertFrom-ExcelSheet -Examples`. 

Am I missing something obvious here?

**Comment by dfinke** [comment]
The `Public\ConvertFrom-ExcelSheet.md` needs to be built into `en\ImportExcel-help.xml` with PlatyPS. There is work going on to make that part of the CI pipeline. `mdHelp` is the source directory, I believe it being in Public is staging/checking process, @jhoneill can correct me.

**Comment by jhoneill** [comment]
The MD files are built into a help IF they are in the mdhelp\Language.   The ones which are left with the PS1 files in the repo are templates _waiting to be completed_.   There may be some information in some of them, but they will be missing description and/or examples and/or parameter details. 

This was a quick and dirty way of addressing things which didn't have help which was a ready to publish and an obvious "ToDo" for the developers. 

IIRC I have just done some work on the one for convertFrom-ExcelSheet, and that will be in the next release.

**Comment by DarkLite1** [comment]
Thanks for the clarifications, but it's not a 100% clear yet to me. So after updating to the latest version where @jhoneill his changes are merged no help is shown when invoking `Get-Help ConvertFrom-ExcelSheet`. Is the purpose of the `.md` files not to have the function `Get-Help` return some information?

**Comment by jhoneill** [comment]
ConvertFrom-Excel worksheet doesn't have any help explaining the parameters, so instead of merging the help for it into the help XML it is "parked" waiting for @dfinke  or me to to write that help.  I **think** but I haven't check, it is the only command which had examples before but was not sufficiently complete to build into the XML.  If you've seen any others let us know,

**Comment by DarkLite1** [comment]
Thanks James I get it now. I check `Get-Help Import-Excel` and that seems to work just fine because of the `.xml` file present in the `en` folder as Dough explained. So the `.md` files are just temporary files until the `.xml` is created which produces the help information. 

Thanks for clarifying this, I will close this issue.
