### ISSUE TITLE
Conditional Formating Data in Pivot Table

### ISSUE THREAD

**Issue by soul4soul** [dfinke/ImportExcel#757]
I'm trying to figure out if it's possible to apply conditional formatting rules to a pivot table. I did a search of open issues and found this comment. Am I interpreting it correctly that I can't use this module for such a task?

>Sorry.  I tried to answer your original question without testing it, and I've ended up misleading you. 
>
>Because the way pivot tables are handled, there is no data in target sheet until you open the file in Excel and it processes the Pivot table, and this will cause all the formatting functions to fail
>You can use 
>```
>$Pkg.ProgramsPivotTable .Row(2).style.font.bold  = $true
>$Pkg.ProgramsPivotTable .Row(2).style.textRotation = 90 
>```
>But when the pivot table is created it will have a table style applied to it so the part of row 2 outside the table will get the formatting, but the bit you want won't. 
>Unfortunately the scope to format a pivot table, is limited to number format and table style.

_Originally posted by @jhoneill in https://github.com/dfinke/ImportExcel/issues/471#issuecomment-431933526_

**Comment by jhoneill** [comment]
I just double checked this.
If you define a pivot table, then apply conditional formatting to cells which include the table's area
And then open the file in Excel, Excel will remove conditional formatting from the area occupied by the pivot. 
So I formatted B1:C1000 , and after inserting the pivot table which goes to J10, the conditional rule applies to B1:C1 and B11:C1000, but B2:C10 are de-formatted.

**Comment by soul4soul** [comment]
After hints from your comments and a bit of googling I'm able to reproduce the effect of `Add-ConditionalFormatting`. I have the following code and when I open the excel sheet the formatting still is crushed on the pivot table. The pivot table doesn't show any formatting but when I look at the condition rules for the cell they exist. Any ideas?

```ps
        $objExcel = New-Object -ComObject Excel.Application
        $objworkbook = $objExcel.Workbooks.Open("${PWD}\\${file}")
        $wkst = $objworkbook.Worksheets("Pivot")
        $wkst.Range("B2:B50").FormatConditions.Delete()

        # Param1
        $xlCellValue = 1

        # Param2
        $xlEqual = 3
        $xlLess = 6

        $wkst.Range("B2:B50").FormatConditions.Add($xlCellValue, $xlEqual, 1)
        $wkst.Range("B2:B50").FormatConditions.Item(1).Interior.Color = 0xFF90EE90 #vbGreen #LightGreen
        $wkst.Range("B2:B50").FormatConditions.Item(1).Font.Color =  0xFF008000 #vbGreen #DarkGreen

        $wkst.Range("B2:B50").FormatConditions.Add($xlCellValue, $xlLess, 1)
        $wkst.Range("B2:B50").FormatConditions.Item(2).Interior.Color = 0xFFFFC0CB #vbGreen #Pink
        $wkst.Range("B2:B50").FormatConditions.Item(2).Font.Color = 0xFF8B0000 #vbGreen #DarkRed

        $objworkbook.Save()
        $objworkbook.close($false)
```

![image](https://user-images.githubusercontent.com/5142635/71127560-55c71c00-21b9-11ea-8bd8-d20451f23dc6.png)

**Comment by soul4soul** [comment]
I was unable to get this to work reliably using COM.  It seems there are settings for the Pivot table that prevent it from being reformatted on open but I didn't test them.
```ps
$wkst.PivotTables(1).HasAutoFormat = #1 or 0
$wkst.PivotTables(1).PreserveFormatting = #1 or 0
```
I decided to stop using COM since it has other issues. The main one is that it can't open files on network drives.

What I ended up doing was making a global VB macro. Now I just run the macro to format the table as desired. I was even able to add the macro to the quick actions bar so its always available as a single click.

**Comment by dfinke** [comment]
Do you run the macro manually, or by doing a -PassThru?

**Comment by soul4soul** [comment]
I run it manually when I open the excel workbook.  Which command has this `-PassThru` argument?

**Comment by dfinke** [comment]
Export-Excel. You can then get to object model and you can get to the VBA. Not sure if you can run it. Don't think I've tried it, only injected VBA. 


You can also use Open-ExcelPackage on an existing xlsx and use the object model.
