### ISSUE TITLE
Getting error loading a spreadsheet using ConvertFrom-ExcelData

### ISSUE THREAD

**Issue by realpobblebonk** [dfinke/ImportExcel#759]
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.0.0\Public\ConvertFrom-ExcelData.ps1:27 char:11
+         & $scriptBlock $PropertyNames $record
[TestInput.xlsx](https://github.com/dfinke/ImportExcel/files/3989968/TestInput.xlsx)

+           ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

I am now having to look at/review an alternative as I am on a time crunch with the project I am working on.

Even if there is an older version where this isn't an issue please let me know so I can use that while you fix the current one.

**Comment by dfinke** [comment]
Please post a script showing how you're using this.
