### ISSUE TITLE
 Can't add row

### ISSUE THREAD

**Issue by a2iz** [dfinke/ImportExcel#760]
There is a file with employees, for example John, Smith, +11111111, ... I want to add a row in excel document.

$e = open-excelPackage -Path .\test.xlsx -KillExcel
$ws = $e.Workbook.Worksheets['sheet1']
Set-ExcelRow -Worksheet $ws -Value @('1','2','3')
Close-ExcelPackage $e

As a result, I get in each column the value 1. 
I want to pick up the values ​​on the assembly line and fill them in columns in order.
I can’t figure out how to do this. Help please.

**Comment by jhoneill** [comment]
If you have a sheet with headings , and you have objects with the same properties of the headings, export-excel -APPEND.  will do what you want. 
Set-excelRow is intended to format a row, or set the same value (usually a formula, or the result of the running a script block) in all the row's cells. 
You can use 
`$r = $ws.dimension.end.row +1  `
and then 
```
$C = 1 
foreach ($value in @(1,2,3) ) {$ws.cells[$r,$c].value = $value; $c += 1} 

```

Hope that helps. but let us know if not. Response might be a bit hit and miss over the holiday period.

**Comment by a2iz** [comment]
Yes. I have sheet with headings. But the table has hyperlinks. Hyperlinks did not copy after import-excel export-excel. That's why I decided to do it through open-excel. 
Now I realized that Set-ExcelRow does not have such functionality, although it would be convenient. I had an idea to make through cells and you confirmed it. 
Your code works great. Thanks.
