### ISSUE TITLE
Conditional formatting with Expression not working

### ISSUE THREAD

**Issue by lucdekens** [dfinke/ImportExcel#761]
It looks as if **Conditional Formatting** with an **Expression** is not working correctly.
The rule is added but not applied.
When opening the spreadsheet, going to Conditional Formatting and opening the rule in Edit without changing anything, the rule is applied.

ImportExcel 7.0.1

PS: the value for ConditionValue is apparently accepted with a '=' in front and without.
Is that on purpose?

Code to demonstrate

```powershell
$xlsxName = '.\report.xlsx'
$wsName = 'TestSheet1'
$data = @'
Field1,Field2,Field3
1,2,A
3,2,B
4,4,C
5,10,D
6,3,E
'@

$sExport = @{
    Path = $xlsxName
    WorksheetName = $wsName
    ClearSheet = $true
    FreezeTopRow = $true
    AutoNameRange = $true
    AutoSize = $true
    TitleBold = $true
    PassThru = $true
}
$excel = ConvertFrom-Csv -InputObject $data | Export-Excel @sExport

$sCond = @{
    WorkSheet = $excel.Workbook.Worksheets[$wsName]
    RuleType = 'Expression'
    ConditionValue = 'IF(NUMBERVALUE(A2)>NUMBERVALUE(B2),TRUE,FALSE)'
    BackgroundColor = 'yellow'
    Range = 'C2:C6'
}
Add-ConditionalFormatting @sCond

Close-ExcelPackage -ExcelPackage $excel -Show
```

**Comment by jhoneill** [comment]
I've been able to repro this in more than one version. I'll look into the cause when I have a little more time, but I've already ruled out obvious versions of "you need to write the expression _this_ way"  :-).

**Comment by dfinke** [comment]
If I click on `Conditional Formatting` and edit the rule, and click `ok` it then seems to apply correctly. The expression looks good. Maybe EPPlus or the code is not setting everything correctly.

**Comment by lucdekens** [comment]
Indeed, the <Edit> action seems to trigger some kind of a recalc or refresh.
Not sure if that is foreseen in EPPlus.
I couldn't find a method that vaguely looks like that.

**Comment by jhoneill** [comment]
Expression works OK in other cases, and I recently made a change for something (can't remember what) specific to expression - which is why I checked the pre-release version. 
I also wondered is the presence or absence of the = sign. (no). Is it  IF <something> True,false would <something> on its own work - I.e. are true and false being broken (no).   
Excel doesn't change what's in the box when you do edit / ok.  

I'll see what I can find...

**Comment by jhoneill** [comment]
OK. I think I have the answer. 
The _other cases_ we've used are very simple expressions. 
The formulas need to be entered as 
`ConditionValue = '_xlfn.NUMBERVALUE(A2)>_xlfn.NUMBERVALUE(B2)'`
I'm not clear why this notation is needed here but not in a cell formula. Possibly EEPlus smooths out one but not the other.  @lucdekens  ... that's a workround for now 
@dfinke  ... my instinct says we should  try to recognize formulas and prepend them with _xlfn time is a bit short at the moment, but I'll look at it when I get the chance.

**Comment by dfinke** [comment]
Cool. That seems to be a challenging parsing problem. 

`IF(NUMBERVALUE(A2)>NUMBERVALUE(B2),TRUE,FALSE)`
->
`IF(_xlfn.NUMBERVALUE(A2)>_xlfn.NUMBERVALUE(B2),TRUE,FALSE)`

**Comment by jhoneill** [comment]
I'm hoping  ` -replace  '(\w+\()'  , '_xlfn.$1'` will do it, but if it is different prefixes (or none) depending on the function it would be horrible. Need to test it and see. Easy to write, utter pig to test.

**Comment by dfinke** [comment]
Ah, I see, the `fn()` pattern only that needs the prefix. Brute force testing or do you know of a list that has what is what?

**Comment by jhoneill** [comment]
I don't _know_ ... but I'm _assuming_ that it is `macroSheet.FunctionName()` or `_xlfn.functionName()` I just need to ensure that I don't catch things like `a1 * (b2 + c3)`  but I _think_ only functions can have a letter or number no space and a (.   But I'm not going to test every function in Excel !

**Comment by lucdekens** [comment]
It seems that the NUMBERVALUE function is a strange one.
It is not listed when you do

```
$excel.Workbook.FormulaParserManager.GetImplementedFunctions()
```

Although Excel lists it as a Text function.

And when I leave the NUMBERVALUE function out and rely on Excel to compare the cell values, it works.
The issue is that the comparison is done, even if the cell doesn't contain a number.

```
$xlsxName = '.\report.xlsx'
$wsName = 'TestSheet1'
$data = @'
Field1,Field2,Field3
1,2,A
3,2,B
AB,2,B
3,21,B
4,4,C
5,10,D
6,3,E
'@

if(Test-Path -Path $xlsxName){
    Remove-Item -Path $xlsxName -Confirm:$false
}

$sExport1 = @{
    Path = $xlsxName
    WorksheetName = $wsName
    ClearSheet = $true
    FreezeTopRow = $true
    AutoNameRange = $true
    AutoSize = $true
    TitleBold = $true
    PassThru = $true
}
$excel = ConvertFrom-Csv -InputObject $data | Export-Excel @sExport1

$sCond = @{
    WorkSheet = $excel.Workbook.Worksheets[$wsName]
    RuleType = 'Expression'
    ConditionValue = 'IF(A2 > B2,TRUE,FALSE)'
    BackgroundColor = 'yellow'
    Range = 'C2:C8'
}
Add-ConditionalFormatting @sCond

Close-ExcelPackage -ExcelPackage $excel -Show
```

**Comment by lucdekens** [comment]
In fact a working solution would be

```
    ConditionValue = 'AND(ISNUMBER(A2),ISNUMBER(B2),A2>B2)'
```

**Comment by dfinke** [comment]
Thanks for drilling in and the great clues.

**Comment by dfinke** [comment]
Cool

```powershell
function Get-ExcelImplementedFunctions {
    $xlfileName = "$env:temp\ExcelImplementedFunctions.xlsx"
    rm $xlfileName -ErrorAction SilentlyContinue
    
    $excel = "" | Export-Excel -Path $xlfileName -PassThru 
    $excel.Workbook.FormulaParserManager.GetImplementedFunctions() | sort key
    Close-ExcelPackage $excel
    
    rm $xlfileName -ErrorAction SilentlyContinue
}
```

**Comment by dfinke** [comment]
@jhoneill do you want to still implement the replace?

**Comment by jhoneill** [comment]
I'm thinking now that a global replace isn't helpful, and the Implemented Functions list is the ones which EPPlus can calculate in a formula, not the list of ones built into Excel .  
So I was thinking about something to get Conditional formatting so you can set it in excel and get it, and then apply it to a new sheet.
