### ISSUE TITLE
Import NonHidden Rows

### ISSUE THREAD

**Issue by g-pearl** [dfinke/ImportExcel#762]
Using part of the data from one of the examples
```
----------------------------------------------
    | File: Movies.xlsx     -      Sheet: Actors |
    ----------------------------------------------
    |           A           B            C       |
    |1     First Name    Last Name    Address    |
    |2     Chuck         Norris       California |
    |3     Jean-Claude   Vandamme     Brussels   |
    ----------------------------------------------
```
But in Excel the Second Line/Row is hidden

When I do import Excel I expect to only see only Jean-claude but I get both Chuck and Jean-Claude.

This is an account tracking sheet that I need to maintain account history but I do not always want to see it so we hide a row.  How can I make sure that I am only getting active (AKA Visible Accounts)

I have tried using open-excelpackage and import-excel and they both show all data.

Any advise is greatly appreciated.  Thanks

**Comment by dfinke** [comment]
Please, could you post an xlsx example.

**Comment by jhoneill** [comment]
If you are using open-excel package, to read data, as you move to each new row you can look at at $worksheet.row($rowNumber).Hidden and skip the row if it is true. 

We could add switches to import-Excel -SkipHiddenRows , -SkipHiddenColumns but at the moment data is data, and "hidden" is _formatting_ so we import all the data and mostly ignore the formatting.

**Comment by dfinke** [comment]
Not really a fan of adding switches for these sorts of one offs at this point.

**Comment by g-pearl** [comment]
I would agree no use adding extra things that are not useful for the masses.  I will work to scrub some data and post.  

After I posted I created a brand new file with 2 columns and hid some data and it only imported the visible data.  The one difference  between the new file and the existing is that the existing was upgraded from older versions of excel and I wonder it something did not convert exactly correct.  I still have the base line file so I am going to try to reconnect and tray again.

I will hopefully have more (including example xlsx)  soon.

Thanks

**Comment by g-pearl** [comment]
Example File
[Access-Publish.xlsx](https://github.com/dfinke/ImportExcel/files/4019449/Access-Publish.xlsx)

Command that I using and results
```
import-excel -Path "D:\Access-Publish.xlsx" -WorksheetName test -StartRow 3 -DataOnly

Full Name       : User 1
Username        : user1
Password        : password1
EACA            : 1/3/2020 12:00:00 AM
Client Corner   : X
Expiration Date : 1/15/2020 12:00:00 AM
Deleted         : 

Full Name       : Hidden User
Username        : hidden1
Password        : hidden1
EACA            : 1/3/2019 12:00:00 AM
Client Corner   : X
Expiration Date : 
Deleted         : 1/4/2019 12:00:00 AM
```

I was expecting not to see "Hidden User"
