### ISSUE TITLE
Export-Excel creates max empty rows in excel in sheets

### ISSUE THREAD

**Issue by morayho** [dfinke/ImportExcel#763]
I am switching from W7 to Server 2016 for work. Om my pc this function works without any problem, but on Server 2016 Export-Excel produces max empty rows in sheets. Together with this the coloring of rows --->  Where-Object {$_ % 2 -eq 1}   ----> does not work anymore, all is colored grey instead of odd rows. Powershell version 5.1 on both so I can not pinpoint the problem.

**Comment by morayho** [comment]
addition:  WARNING: Failed processing CellStyleSB in worksheet 'Disks': Exception setting "PatternType": "Array dimensions exceeded supported range."

**Comment by jhoneill** [comment]
You might need to give us a little more to work with.

**Comment by morayho** [comment]
Good day,

Problem shows up when using the CellStyleSB parameter, when using not all goes well but for readability it would be nice to have the grey colored rows:



$sheet_style = {param($workSheet,$totalRows,$lastColumn)

        Set-CellStyle $workSheet 1 $LastColumn Solid Gray

        foreach($row in (2..$totalRows | Where-Object {$_ % 2 -eq 1}))   {
            Set-CellStyle $workSheet $row $LastColumn Solid LightGray    }
               } # end-of-sheetstyle

$sheetdata | Export-Excel $filename -AutoSize -BoldTopRow -AutoFilter -FreezeTopRow -WorkSheetname $sheetname -CellStyleSB $sheet_style -ConditionalText $( 
        New-ConditionalText -Range A2:A$($sheetdata.Count +1) -ConditionalType EndsWith(".") 0x00ffff -BackgroundColor red  )

please the result in the excel-sheet,

although the parameters are not passed, it never has been a problem for a good working code and good result, until now I changed to run the code from Server 2016.



[cDOT-report-v9.73b_ct_2020-01-03.xlsx](https://github.com/dfinke/ImportExcel/files/4019440/cDOT-report-v9.73b_ct_2020-01-03.xlsx)
