### ISSUE TITLE
Get Excel Row And Col

### ISSUE THREAD

**Issue by itamartz** [dfinke/ImportExcel#766]
Can I use this module to find something in Excel?
I want to do import-Excel | Where {$_. ------ }
And Then I want to update the records in Excel 

Does this module support this?

BR, 
Itamar

**Comment by uSlackr** [comment]
Yes it works.  Please try.


\\Greg

________________________________

**Comment by jhoneill** [comment]
Yes you can, but the module only does part of the work for you. 
Import-Excel takes a sheet from your workbook and returns an object for each row. It's not really designed to write back. 

You can do 
```
$excel  = Open-ExcelPackage -path foo.xlsx
$ws = $excel.NameOfYourSheet 
$ws.cells | where {$_.value  -gt $foo} 
``` 

or `$ws.cells["b2:b3"] #for a range`
or `$ws.cells["3:3"]  #for a row`
or `$ws.cells["b:b"]  #for a column`

then you can do  `| foreach {$_.value += 99} ` or whatever ; and finally
`close-excelPackage $excel`
