### ISSUE TITLE
Help examples for Convert-FromExcelSheet no longer match

### ISSUE THREAD

**Issue by chadcarlton** [dfinke/ImportExcel#767]
To be clear.. this is picking nits...

Defaults are CSV

example reads:

    -------------------------- EXAMPLE 1 --------------------------

    PS C:\>ConvertFrom-ExcelSheet .\TestSheets.xlsx .\data

    Reads each sheet in TestSheets.xlsx and outputs it to the data directory as the sheet name with the extension .txt

    -------------------------- EXAMPLE 2 --------------------------

    PS C:\>ConvertFrom-ExcelSheet .\TestSheets.xlsx .\data sheet?0

    Reads and outputs sheets like Sheet10 and Sheet20 form TestSheets.xlsx and outputs it to the data directory as the sheet name with the extension .txt

**Comment by dfinke** [comment]
Great opportunity to make a pull request and fix, :)
