### ISSUE TITLE
Convert worksheet to .ps1 template?

### ISSUE THREAD

**Issue by ImportTaste** [dfinke/ImportExcel#771]
I have a very particular use case in which I need to generate a bunch of Excel worksheets, pulling data from something like a csv file and transplanting it onto a template via a drag and drop operation.

However, I worry about coworkers filling out fields on the template by mistake or not copying the template with the script.

So I would like to know if there's a way I could convert the template into a series of commands that will give me the same worksheet output, or perhaps some other format that could be stored in an object within the file. If possible I would like to avoid it having to create a 'temp file' to perform its operations, but beggars can't be choosers.

I've poured over the documentation and I'm not seeing an especially obvious way of doing this.

**Comment by uSlackr** [comment]
I’m pretty certain there is nothing to read an existing excel file and use it as a template.  But, putting your steps into code has the exact outcome as using a template.

I have a script that does something like the following:

Opens a group of Excel and CSV files and imports (while filtering ) them into different sheets of a new workbook
Creates new columns and builds formulas that reference values and lookups in the various sheets
Sets the format of different columns and rows on each sheet

Each time I run this I use different data, but  get a similar working and looking output file.

It isn’t simple or easy, but it is doable.  I suggest tackling one step at a time.  Read the examples as training materials.
Come back here when you have a particular question about how something works or if you aren’t sure on how to approach a task.

\\Greg
