### ISSUE TITLE
read value from calculated cell in workbook

### ISSUE THREAD

**Issue by paysonsolutions** [dfinke/ImportExcel#772]
I have an automated process that creates an excel workbook. The resulting workbook has a worksheet named Summary which has a number of cells that get values by evaluating formulas. These formulas get their data from cells in other worksheets in the workbook. 

I am trying to use ImportExcel to open the workbook and get the values from the cells in from the Summary worksheet. All calculated fields return a value of #Div/0! Only after I open the workbook in excel, and save it, do the calculated cells get values I can query successfully. 

What am I doing wrong?

**Comment by dfinke** [comment]
I don't believe there is a way to calculate the workbook if it has not been opened? @jhoneill not sure if you saw a method on the object model?
