### ISSUE TITLE
Excel Styles

### ISSUE THREAD

**Issue by Olddog1** [dfinke/ImportExcel#773]
I have one question about Excel Styles.
 
When I use the com object I have been using 
 
$range = $ws.range('A1:Z1')
$range.font.bold = 'true'
$Range.Style = "Heading 2"
 
How would I call the "Heading 2" style with Export-Excel?

**Comment by dfinke** [comment]
Is `Heading 2` a style name you set up in the workbook?

**Comment by Olddog1** [comment]
No it's built into Excel. Here is a Macro I recorded:
Sub Style()
' Style Macro
'
    Range("A1:D1").Select
    Selection.Style = "Heading 2"
End Sub
