### ISSUE TITLE
Conditional Formatting Blank Cells

### ISSUE THREAD

**Issue by naterrey** [dfinke/ImportExcel#778]
What is the best way to conditionally format a blank cell? I am dividing data by an empty column and want to color the empty column in the middle blue but when I specify no text colors everything except the empty column blue because of the assumed wildcard. Is there another method?
The only way I can think is loop through the Table and rename each "rowerror" value to '     ' and set that as the conditional text but I don't really want to do that.

        $FillBlanks = New-ConditionalText -BackgroundColor Blue

        $BackupSupportList|Select-object -Property User,ID,Team,Title,Mobile,Ext,@{Name=' ';Expression={$_.rowerror}},ToExt,ToUser,ToID,ToTeam,ToTitle,ToMobile|Export-Excel -now -StartRow 6 -AutoSize -AutoFilter -ConditionalFormat $FillBlanks -IncludePivotTable #-TitleFillPattern Blue # -ConditionalFormat $FillBlanks #-ConditionalFormat  -TitleFillPattern Blue

**Comment by naterrey** [comment]
Update: I was able to fill the specific column G:G after finding the new-excelstyle method, but it would still be nice to know how I could fill blank columns for other purposes so I don't have to specify ranges.

**Comment by dfinke** [comment]
## Try 
### New-ConditionalText -ConditionalType ContainsBlanks 
![image](https://user-images.githubusercontent.com/67258/74384002-5a294300-4dbe-11ea-83c1-0381837cf455.png)

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
West,lemon,52
West,avocado,8
West,melon,18
North,other,
East,banana,91
South,peach,18
West,peach,56
East,screws,1
West,peach,25
West,,35
East,hammer,4
North,screws,49
,test,35
"@

$ConditionalText = New-ConditionalText -ConditionalType ContainsBlanks -BackgroundColor Green
$xl = Export-Excel -InputObject $data -Path $xlfile -ConditionalText $ConditionalText -Show
```

**Comment by naterrey** [comment]
that works, thank you! I hadn't seen that condition in notes before :)
