### ISSUE TITLE
Formatting Numbers

### ISSUE THREAD

**Issue by jdhitsolutions** [dfinke/ImportExcel#78]
I've looked through the help and issues here and haven't found anything that would seem to address this issue. 

If I run a command like this:
get-ciminstance win32_logicaldisk -filter "drivetype=3" | Select DeviceID,Volumename,Size,Freespace | Export-Excel -Show -AutoSize -Path C:\work\disks.xlsx

I get a  spreadsheet, but the disk sizes are shown as 2.14746E+11 instead of the number formatted 214746263552. Is there some parameter I'm missing to set format the cells or range? Or is this something to put on the wish list?

**Comment by dfinke** [comment]
The is Excel magic that needs to be undone. I'll investigate.

**Comment by dfinke** [comment]
Thanks for adding the issue @jdhitsolutions. Added NumberFormat. Checkout https://github.com/dfinke/ImportExcel/tree/master/Examples/NumberFormat
