### ISSUE TITLE
Export-Excel closes ExcelPackage

### ISSUE THREAD

**Issue by clsmith70** [dfinke/ImportExcel#785]
When looping over multiple datasets that are being exported to one Excel workbook, each call to Export-Excel closes the workbook referenced by the package.  This also renders the Close-ExcelPackage command unnecessary.  Can you add a switch or code path so that when working with a package it isn't closed when one set of data is exported?  I have found a work-around for this behavior, but it doesn't make sense to use Open-ExcelPackage with each iteration of the loop.

[ExcelPackageLoops.txt](https://github.com/dfinke/ImportExcel/files/4214314/ExcelPackageLoops.txt)

**Comment by dfinke** [comment]
@clsmith70 curious, the Excel file is opened and processing on the file continues there?

I was experimenting with this the other day, if the xlsx is open it fails, can add `-NoSave` , then no issues. Probably need better messages there, need to look to see if the scenario can be accommodated.

```powershell
$xl=Open-ExcelPackage -Path c:\temp\testData.xlsx

$column = 1
for ($row = 1; $row -lt $xl.Sheet1.Dimension.Rows; $row++) { 
    $xl.Sheet1.Cells[$row,$column].value    
}

Close-ExcelPackage -ExcelPackage $xl
```

**Comment by jhoneill** [comment]
Export closes Unless `-PassThru`  is specified. If you want to keep the file open 
`$e = $x | export-excel -passthru <params >
`
you can specify` -excelPackage $e `in future calls to export which will close, unless `-passthru` is given, so the last call to export typically closes the file. 

You can do other work on the file and the use ` close-excelPackage ` - that is only there to close the file if either
1. You opened it not using import
2. You created it but hadn't saved it in export.
