### ISSUE TITLE
[issue-question] Workbook/worksheet properties

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#787]
Below is workbook properties created by the module. "Created" property has a wrong date but the file lastupdate time is correct. If I open a file created with Excel app `importexcel` module will show a correct date.
```
CorePropertiesXml     : #document
Title                 : 
Subject               : 
Author                : 
Comments              : 
Keywords              : 
LastModifiedBy        : Мотиенко Сергей Геннадьевич
LastPrinted           : 
Created               : 01-01-0001 0:00:00
Category              : 
Status                : 
ExtendedPropertiesXml : #document
Application           : Microsoft Excel
HyperlinkBase         : 
AppVersion            : 16.0300
Company               : 
Manager               : 
Modified              : 20-02-2020 14:54:32
LinksUpToDate         : False
HyperlinksChanged     : False
ScaleCrop             : False
SharedDoc             : False
CustomPropertiesXml   : #document
```

One more question. I could not find "Modified" property for worksheets. Do sheets not have lastupdate info?

**Comment by dfinke** [comment]
The module doesn't do anything with those properties. You can use `-PassThru` and then set them in your script.

**Comment by scriptingstudio** [comment]
Worksheet properties seem to be in use. Is it possible to add custom properties to worksheet object?
My excel file has 40-50 sheets and it is useful to know modifydate.

**Comment by dfinke** [comment]
Not to save that I know of. The underlying XML data is the OpenOffice XML spec.
