### ISSUE TITLE
Looking for a function to create new workbooks based on column value in a existing workbook

### ISSUE THREAD

**Issue by Espnlee1** [dfinke/ImportExcel#788]
Looking for a function to create new workbooks based on column value in a existing workbook.

For example, if I have an existing workbook and I want to separate the workbook on column J that includes a companies email.

I would like all of the existing data, and formats associated with each email address to be exported and saved to its own workbook.

As a better example I have attached a link of this process in VBA.  Of course I would like to know if this exits in PowerShell with less code.  Thank you

https://youtu.be/48oUxaL7X6c

**Comment by dfinke** [comment]
### Here's one possible approach

[employee.xlsx](https://github.com/dfinke/ImportExcel/files/4241285/employee.xlsx)

```powershell
$xlfile = "$env:TEMP\employee.xlsx"

foreach($supvervisor in (Import-Excel $xlfile | group 'supervisor name')) {
    $newXlfile = "$env:TEMP\$($supvervisor.name).xlsx"
    rm $newXlfile -ErrorAction SilentlyContinue
    
    $supvervisor.group | Export-Excel $newXlfile -AutoSize -AutoFilter

    $newXlfile
}
```

**Comment by Espnlee1** [comment]
Wow Doug this is awesome and Thank you!

I have a few questions can you please explain the below.  Why is the variable in parenthesis and why is $ outside of the parenthesis.  I do understand $supervisior.name references the column in the workbook but I have never seen a variable initialized this way in my 8 months of PowerShell scripting lol.  Thank you for quick and effective response.

$($supvervisor.name)

**Comment by dfinke** [comment]
The $() is a subexperession. Because it is all in a string, powershell would not be able to determine that .name was a property

**Comment by Espnlee1** [comment]
Wow never knew that! Would you like me to close this issue?

**Comment by dfinke** [comment]
Thanks for the question, I'll close it.
