### ISSUE TITLE
As some point above 6000 records, no longer iterating "empty" fields, reusing previous record's data

### ISSUE THREAD

**Issue by dfsaqwe** [dfinke/ImportExcel#789]
I'm using this module to export AD users from powershell to excel.
Running following command

`get-aduser -filter * -server *** -Properties enabled, samaccountname, displayname, givenname, surname, emailaddress, title, company, department, officephone, ipphone, mobilephone, office, streetaddress, city, state, postalcode, country, Manager, CanonicalName, UserPrincipalName,HomeDirectory, HomeDrive, LastLogonDate,CannotChangePassword,PasswordExpired,PasswordLastSet,PasswordNeverExpires,PasswordNotRequired,ScriptPath,whenCreated | select-object -property enabled, samaccountname, displayname, givenname, surname, emailaddress, UserPrincipalName, title, company, department, officephone, ipphone, mobilephone, office, streetaddress, city, state, postalcode, country, @{n="ManagerDN";e={get-aduser $_.Manager | select-object -ExpandProperty distinguishedname}},@{n="ManagerFullName";e={get-aduser $_.Manager | select-object -ExpandProperty Name}},@{n="ManagerFirstName";e={get-aduser $_.Manager | select-object -ExpandProperty givenname}},@{n="ManagerLastName";e={get-aduser $_.Manager | select-object -ExpandProperty surname}}, CanonicalName, HomeDirectory, HomeDrive, LastLogonDate,CannotChangePassword,PasswordExpired,PasswordLastSet,PasswordNeverExpires,PasswordNotRequired,ScriptPath,whenCreated | export-excel "\\***\ADUsers_Corporate.xlsx"`

I noticed at some point past 6000 records, entries which should have blank fields, ie entry has no email address, instead are utilizing the previous records entry, so that unique email address shows up twice now.
<img width="522" alt="issue" src="https://user-images.githubusercontent.com/61512594/75366598-f6f2e280-588c-11ea-9db0-6ca951a866c1.png">

**Comment by dfsaqwe** [comment]
A little further testing, seems to occur when specifying an existing file.

**Comment by jhoneill** [comment]
Existing file was my first thought. If you use `-clearSheet` it will delete and recreate the sheet; I added that option for exactly this case :-)
