### ISSUE TITLE
Suggestion: TitleBold should be a switch

### ISSUE THREAD

**Issue by jdhitsolutions** [dfinke/ImportExcel#79]
The TitleBold parameter for Export-Excel should really be a switch parameter. The only time you are going to use the parameter is when you want the title to be bold.

**Comment by dfinke** [comment]
And here I was hoping for a PR ;-)

Thanks Jeff. Great suggestion.

**Comment by jdhitsolutions** [comment]
If I can figure out all this git voodoo, I'll give it a try.

**Comment by dfinke** [comment]
If you're not already using it, try https://desktop.github.com/

You've forked the project, so now you can make edits and check that in when you're ready. Those edits are only on your branch, doesn't change the master. 

Then, you can issue a PR (pull request). I get notified, it still hasn't made it to the master until I do a merge. In the PR, you and I can work on it and discuss and when ready, it can be merged back to the master.

Easy peasy.

**Comment by jdhitsolutions** [comment]
I've made the changes locally. Trying to get them pushed back up using Git from the command line but I may cheat and use the desktop GUI.

**Comment by dfinke** [comment]
It's not cheating, it's keeping it simple.
