### ISSUE TITLE
Exporting issue - Error with formulas with more than simple references displaying call values of #NAME?

### ISSUE THREAD

**Issue by christianlagiewka** [dfinke/ImportExcel#790]
I've run into an issue where calculated values (for instance, using a VLOOKUP) show a result of 
 #NAME? in the cells where the calculation takes place. If I use a simple reference (=$A2) then there are no issues.

If within Excel (using Excel365) and I go into the formula cell and press enter, it correctly calculates the result.

I've created and attached a quick PowerShell script that demonstrates this. I have no idea what I am missing or doing wrong. I've created the string in many different ways, tried row references like
**[@[ColumnName]]** that don't also work.

Does anyone have any ideas? I originally encountered this issue while pulling in data from Ivanti via REST, importing another spreadsheet, and creating a custom report page with a PSCustomObject that includes formulas that reference other worksheets, tables, etc. I've broken it down to a simple test that replicates the issue.

[Exceltesting.txt](https://github.com/dfinke/ImportExcel/files/4258370/Exceltesting.txt)

**Comment by dfinke** [comment]
## Fixed

`Table_TestData2[]` added the braces. It's an Excel thing.

```powershell
#Import-Module ImportExcel

$TestOutputfile = "$env:temp\TestExcelFile.xlsx"
Remove-Item $TestOutputfile -ErrorAction SilentlyContinue


$CSV_File1 = @"
"Asset Tag","ID","Full Name"
"MACHINENAME1","USER1","User Full Name 1"
"MACHINENAME2","USER2","User Full Name 2"
"MACHINENAME3","USER3","User Full Name 3"
"@

$CSV_File2 = @"
"Asset Tag","DETECTED_ID"
"MACHINENAME1","LOOKUPTESTUSER1"
"MACHINENAME2","LOOKUPTESTUSER1"
"MACHINENAME3","LOOKUPTESTUSER1"
"@

$TestData1 = $CSV_File1 | ConvertFrom-Csv
$TestData2 = $CSV_File2 | ConvertFrom-Csv
$TestData1 | Add-Member NoteProperty SimpleRef $NULL
$TestData1 | Add-Member NoteProperty FormulaTest $NULL



For ($i = 0; $i -lt $($TestData1.count); $i++) {
    $ExcelRowNum = $i + 2
    $TestData1[$i].SimpleRef = "=TestData2!`$B$($ExcelRowNum)"
    $TestData1[$i].FormulaTest = "=VLOOKUP(`$A$($ExcelRowNum),Table_TestData2[],2,0)"    
}



$ExportSplat1 = @{
    Path = $TestOutputfile
    Autosize = $True
    WorkSheetName = "TestData1"
    TableName = "Table_TestData1"
    FreezeTopRow = $True
    AutoFilter = $True
    BoldTopRow = $True
    NoNumberConversion = '*'
}

$ExportSplat2 = @{
    Path = $TestOutputfile
    Autosize = $True
    WorkSheetName = "TestData2"
    TableName = "Table_TestData2"
    FreezeTopRow = $True
    AutoFilter = $True
    BoldTopRow = $True
    NoNumberConversion = '*'
    Show = $True
    KillExcel = $True
}


$TestData1 | Export-Excel @ExportSplat1
$TestData2 | Export-Excel @ExportSplat2
```

**Comment by christianlagiewka** [comment]
Wow. So simple. Thank you! I've spent much of today and yesterday trying 
to figure it out, trying different test scenarios, different data, etc.

Being the author, how did you find out about that /Gotcha/?

Is there any way I can contribute to the documentation of that issue, or 
any of other /things that may trip you up/?

**Comment by dfinke** [comment]
Hat tip to @jhoneill on that, he found it when adding functionality to the module.

I like the idea of a "Things That Can Trip You Up" write-up. To start, you could fork the repo and do a PR adding a file `ThingsThatCanTripYouUp.md` next to the `README.md`.

Thank you for the offer!

**Comment by christianlagiewka** [comment]
Done. I'll add more as I encounter additional quirks.

**Comment by uSlackr** [comment]
This is interesting.  I have a whole set of table references that worked fine back in September when I last used this script.  No braces worked fine back then.

$Win7DeviationFormula = "=IF( COUNTIFS(Win7Baseline!Control,D2,Win7Baseline!Setting,""Same as CIS"")=0,""Deviation"",""No Deviation"")"
$Win10DeviationFormula = "=IF( COUNTIFS(Win10Baseline!Control,D2,Win10Baseline!Setting,""Same as CIS"")=0,""Deviation"",""No Deviation"")"

\\Greg
