### ISSUE TITLE
How to format cells only with values. 

### ISSUE THREAD

**Issue by anilgo123** [dfinke/ImportExcel#791]
i want to border the range of cells that have values in it. ImportExcel should automatically select those cells and border it.
Need help.

**Comment by jhoneill** [comment]
Conditional formatting ?

**Comment by anilgo123** [comment]
hmmm, I think it should be conditional, cause whenever I run the report I am able to apply table formatting however unable to border all the cells within that range.
everytime i run the report data varies so depending on that excel should border the cells contains data.

Hope you got what i want....

**Comment by jhoneill** [comment]
I first read it as a "I want  a box around each cell which has a value in it"  Which would be conditional formatting. 
If your data goes from A1 to Z9  and want to draw an outline around A1:Z9 that's easy enough to do.
I'll try to give an example of whichever one it is later - just doing some quick answers on the train at the moment.

**Comment by anilgo123** [comment]
Sure thank you, will wait for your reply

**Comment by jhoneill** [comment]
This will do it. 
It appears at border around doesn't support "internal border", and we didn't put border into conditional formatting. This will draw a box round every cell with something in it. 

```
$e = get-command *conditi* | select name,version,source | export-excel -path "$env:temp\xx.xlsx" -PassThru
$e.Sheet1.Cells | foreach {$_.style.Border.BorderAround([OfficeOpenXml.Style.ExcelBorderStyle]::Medium)}
Close-ExcelPackage $e -show
```

Using `[OfficeOpenXml.Style.ExcelBorderStyle]::` lets you tab-complete for different border styles

**Comment by dfinke** [comment]
## another way

![image](https://user-images.githubusercontent.com/67258/75593913-d8d7de80-5a54-11ea-9a97-f2b5ee7b6137.png)

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
South,melon,47
South,orange,84
West,hammer,81
South,nail,62
East,lime,74
West,pear,88
East,drill,26
South,saw,42
East,kiwi,46
North,banana,2
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru

$border='thin'
$range = $xl.Sheet1.Dimension.Address

Set-Format -Worksheet $xl.sheet1 -Range $range -BorderBottom $border -BorderTop $border -BorderLeft $border -BorderRight $border

Close-ExcelPackage $xl -Show
```

**Comment by dfinke** [comment]
## another way?

![image](https://user-images.githubusercontent.com/67258/75594018-3c620c00-5a55-11ea-8b7c-9228513ac179.png)


```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
South,melon,47
South,orange,84
West,hammer,81
South,nail,62
East,lime,74
West,pear,88
East,drill,26
South,saw,42
East,kiwi,46
North,banana,2
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru

$border='thin'
$range = $xl.Sheet1.Dimension.Address

Set-Format -Worksheet $xl.sheet1 -Range $range -BorderBottom $border -BorderTop $border -BorderLeft $border -BorderRight $border

Close-ExcelPackage $xl -Show


```

**Comment by anilgo123** [comment]
Wow!!!  Thank you so very much... and I learned something about the "dimension.address" today

i am also trying to merge the offset cell with the same data in it. 
In case i need help i will check with you guys with the new issue

Thanks a ton, you guys rock :)
