### ISSUE TITLE
Import-Excel from a Data Table instead of Sheet with Row/column co-ordinates

### ISSUE THREAD

**Issue by o-o00o-o** [dfinke/ImportExcel#794]
Hi something I hoped would be simple would be to get the contents of a data table from my excel workbook

I can do it by 

``` powershell
$excelPath = "myExcel.xlsx"
$tableName = "Table1"
$excel = Open-ExcelPackage $excelPath
$table = $excel.workbook.Worksheets.tables | ?{$_.Name -eq $tableName}
$ws = $table.workSheet
[OfficeOpenXml.ExcelAddress]::TranslateToR1C1($table.Address.Address,0,0) -match 'R\[?(?<startrow>-?\d+)\]?C\[?(?<startcol>-?\d+)\]?(:R\[?(?<endrow>-?\d+)\]?C\[?(?<endcol>-?\d+)\]?)?'
Close-ExcelPackage $excel
$tableData = Import-Excel -FullName $excelPath -sheet $ws -StartRow $matches.startrow -StartColumn $matches.startcol -EndRow $matches.endrow -EndColumn $matches.endcol
```

Any chance we could add an alternative param to Import-Excel that allows just taking a TableName instead of a worksheet and row/col?

Would you accept a PR? I can see a lot of outstanding ones...

**Comment by o-o00o-o** [comment]
just noticed #558 not sure if it is supposed to do the same thing or not but if so it doesn't seem necessary to have the worksheet name as an arg as table names must be unique in the entire workbook

But it did show me that I can avoid my regex by simply using $table.address.Start.Row, Start.Column etc.. 

``` powershell
$excelPath = "myExcel.xlsx"
$tableName = "Table1"
$excel = Open-ExcelPackage $excelPath
$table = $excel.workbook.Worksheets.tables | ?{$_.Name -eq $tableName}
$ws = $table.workSheet
Close-ExcelPackage $excel
$tableData = Import-Excel -FullName $excelPath -sheet $ws -StartRow $table.address.start.row -StartColumn $table.address.start.column -EndRow $table.address.end.row  -EndColumn $table.address.end.column
```

better but not as good as 

``` powershell
$excelPath = "myExcel.xlsx"
$tableName = "Table1"
Import-Excel -FullName $excelPath -Table $tableName
```

**Comment by o-o00o-o** [comment]
actually I would really want this to give me access to all tables without needing to provide the table name for each case, just like Import-Excel does for each worksheet, so it would be good if this could populate a DataTables member of the PSCustomObject returned from Import-Excel, so then we could do 

``` powershell
$excel Import-Excel -FullName $excelPath
$excel.Tables["Table1"] | Format-Table
```

**Comment by dfinke** [comment]
Here was an initial way I started on that. You can source the ps1, it has an error you can ignore, and the functions work. To add it to the overall module, it needs to be cleaned up and unit tests have to be added.

https://github.com/dfinke/ImportExcel/blob/master/GetExcelTable.ps1
