### ISSUE TITLE
Export-Excel -FreezeTopRow with -Title

### ISSUE THREAD

**Issue by patware** [dfinke/ImportExcel#795]
Let me start with thank you.

When using the FreezeTopRow, Export-Excel it freezes the excel row 1 of the sheet.  But, when combined with a -Title "Foo", row 1 has the description "Foo" and the table actually starts at row 2.

I believe that the FreezeTopRow should act on the table's header.

Same for 
-FreezeTopRow 
-FreezeTopRowFirstColumn

Note 1: I understand this could be a breaking change
Note 2: I'm aware I can use the FreezePane instead

**Comment by jhoneill** [comment]
You're right. It should freeze the header, but it actually freezes row 1. 
Alternatively. "Top Row" should only mean one row, and there is a problem if someone specifies start at row 10, do we keep that row and the 9 above it visible ?

Technically it is a breaking change but I think it is unlikely that anyone relies on freezing the title and not the headers.   
@dfinke  - thoughts ?  Change the existing switch; add -freezeHeader or leave as is ?

**Comment by dfinke** [comment]
Fixing the switch. Don't know how many this will break. Don't remember seeing lots of traffic on this issue.

**Comment by jhoneill** [comment]
Do you mean you are fixing it, or you think that's the best way (in which case I'll do it :-) )

**Comment by dfinke** [comment]
Sorry :). Thought it was the best way. Not sure it needs fixing, I wouldn't be able to get to it till the weekend, maybe, but there are a couple things that can be published.  

Please have at it :)

**Comment by jhoneill** [comment]
OK, I'll take it. I have a nice extra example to go in the next PR too. Covert Nunit output from pester to a spreadsheet.
