### ISSUE TITLE
More Pivots from the same worksheet [question/problem]

### ISSUE THREAD

**Issue by darkunicum** [dfinke/ImportExcel#797]
Hello! 

I want to automate a script which creates 3 different pivot tables from a data worksheet.

This is my code:

```
Import-Csv $csvpath -Delimiter ";" | Export-Excel -WorksheetName "PivotDataWorkheet" -FreezeTopRowFirstColumn -TableName "Data" -Path C:\temp\myexcel.xlsx -AutoSize -MaxAutoSizeRows 2 -TableStyle None -TitleSize 20
Export-Excel -Path C:\temp\myexcel.xlsx -WorksheetName "PivotDataWorkheet" -IncludePivotTable -PivotRows first_date, last_date, fqdn -PivotData @{"title"="Count"} -PivotFilter Category -PivotTableName Date
Export-Excel -Path C:\temp\myexcel.xlsx -WorksheetName "PivotDataWorkheet" -IncludePivotTable -PivotRows title -PivotData @{"title"="Count"} -PivotFilter Category -PivotTableName Title 
Export-Excel -Path C:\temp\myexcel.xlsx -WorksheetName "PivotDataWorkheet" -IncludePivotTable -PivotRows fqdn -PivotData @{"title"="Count"} -PivotFilter Category -PivotTableName Fqdn 
```

Somehow always only the last row compiles, the other 2 worksheets are created but no pivot table is created there.

Could you tell me if I make some syntactic mistake with your module?

Best regards,
Roland

**Comment by pkarunkar** [comment]
You are using the same worksheet and not specifying the start address of
the second pivot.

Last one is compiled since previous pivots are overwritten.

**Comment by darkunicum** [comment]
Could you elaborate which parameter needs to be used to define a new pivot to a new worksheet from the same data?

**Comment by pkarunkar** [comment]
Multiple ways:
You can create Excel without pivot. Then create hashtable like

$pvtparam =@{
Pivottablename = "xyz"
Address = $xl.sheet1.cells["C1]
}

Then open excel package,
Add-pivotable @pvtparam

Or you should be able to pass this to export-excel -pivottabledefintion.

Sorry I am typing from mobile at work :)
Will assist you better later today if you are not able to figure it out.

Look into old issues that are closed. I believe it was discussed a number
of times.

**Comment by pkarunkar** [comment]
I just noticed that there is a great example.

Try
get-help export-excel -examples


And check out example 11..

**Comment by dfinke** [comment]
yes. Plus you can try that code already worked up here https://github.com/dfinke/ImportExcel/blob/master/Examples/TryMultiplePivotTablesFromOneSheet.ps1
