### ISSUE TITLE
Leading zeros are removed even after selecting text format for column

### ISSUE THREAD

**Issue by MarcVndrhgn** [dfinke/ImportExcel#798]
I am trying to export csv file to excel; these csv files have columns with number containing leading zeros.
So in order for excel to keep them, you need to set the format cell to 'text'.
in powershell I only do that : 
`$mycsv = Import-Csv "$env:TEMP\List_20200304093550.csv" -Delimiter '§' -Encoding Default

$mycsv | Export-Excel "$env:TEMP\myxlsx.xlsx" -AutoSize -StartRow 1 -Numberformat 'Text'`

But when I open the file in excel, the cell format is well set on Text but the data in the columns have lost the leading zeros.
It looks like the cell format is applied after the data has been imported.
So I tried to create an empty excel file and setting the cell format to Text (that is ok, there is no data in the excel file and the column format cells is set on Text), I then imported the csv by doing this : 
`$mycsv | Export-Excel "$env:TEMP\myxlsx.xlsx" -AutoSize -StartRow 1 -Append -Numberformat 'Text'` but with the same result.
I even noticed that if I omit the -Numberformat 'Text' when doing the import, the cell format is back on General.
So the import definitively removed any settings already set on the worksheet.

Any idea ?

**Comment by jhoneill** [comment]
If you specify "no number conversion" does that  make any difference ?  

Given "0001"  export-excel sees that parses as a number, and sets the value of the cell to 1. 
`-NoNumberConversion *`  or `-NoNumberConversion MyColumnName` stops that parsing. 

Personally I would allow numbers to go into the sheet as numbers (not text) and then apply the format "0000" to get leading zeros, but the there are multiple ways to get the same result.

**Comment by MarcVndrhgn** [comment]
Thank you very much, it does indeed make a difference and the leading zero's are now visible.
My bad, I hadn't seen this option.
Thanks

**Comment by jhoneill** [comment]
@MarcVndrhgn  you're welcome. Don't worry, it's easy to miss some of the options :-)
