### ISSUE TITLE
"Cannot index into a null array" if document is not re-saved

### ISSUE THREAD

**Issue by borutlape** [dfinke/ImportExcel#799]
Hi,

I am trying to automate parsing of XLSX reports generated by an application.
If the document is parsed directly after generating, I get an error: 
    + CategoryInfo          : OperationStopped: (Failed importin...o a null array.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook 'xxx.xlsx' with worksheet 'sheet3': Cannot index into a null array. 

If I just open and save the document, the parsing finishes smoothly.
I assume this has to do with Microsoft Protection but I don't have an idea how to overcome it.

Regards,
Borut

**Comment by dfinke** [comment]
Please could you post an example of an xlsx and script that shows the issue.

**Comment by borutlape** [comment]
I have sent you the examples directly on your email.

**Comment by A8d13l** [comment]
What was the resolution to this issue?

**Comment by borutlape** [comment]
Hi,

The issue was on our side, in the source file...
