### ISSUE TITLE
Multiple PivotTables

### ISSUE THREAD

**Issue by RamblingCookieMonster** [dfinke/ImportExcel#8]
Hi Doug!

Noticed your note on multiple PivotTables - ran into the same issue trying to come up with a fun demo for my boss.

Added a repro to an [issue on codeplex](https://epplus.codeplex.com/workitem/14695) - They released the fix last night, pulled [4.0.4](https://epplus.codeplex.com/releases/view/118053) down, and it seems to be working now.

Cheers!

**Comment by dfinke** [comment]
Awesome, thatnks for connectoing the dots and getting that fixed. I'll take a look.

**Comment by RamblingCookieMonster** [comment]
Your welcome, thanks for all the fun ideas in ImportExcel : )  On a side note, feel free to close this out and add the DLL on your end, if you end up wanting to add it.  Felt odd submitting a PR with just a DLL
