### ISSUE TITLE
ConvertTo-ExcelXlsx not working

### ISSUE THREAD

**Issue by jxgabel** [dfinke/ImportExcel#801]
Having a problem using ConvertTo-ExcelXlsx.  If I call the command inside a .ps1 script setup as a scheduled task it just doesn't seem to do anything.  Redirecting output I get the following clue below.  The first two possibilities mentioned aren't true.  Not sure on the 3rd one, but if I run this same command against the same file (<path> listed below is fully qualified), same folder structure on the same server in the ISE, it works as expected.  Any suggestions?

Microsoft Excel cannot access the file 
'<path>\tempdata.xls'. There are several possible 
reasons:

• The file name or path does not exist.
• The file is being used by another program.
• The workbook you are trying to save has the same name as a currently open workbook.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.0.0\Public\ConvertTo-ExcelXlsx.ps1:49 
char:9
+         $null = $Excel.Workbooks.Open($xlsFile.FullName)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.0.0\Public\ConvertTo-ExcelXlsx.ps1:50 
char:9
+         $Excel.ActiveWorkbook.SaveAs($xlsxPath, $xlFixedFormat)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.0.0\Public\ConvertTo-ExcelXlsx.ps1:51 
char:9
+         $Excel.ActiveWorkbook.Close()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by dfinke** [comment]
Did you solve it?

**Comment by jxgabel** [comment]
> Did you solve it?

I did not, but given the urgent necessity of the business process it was an easier workaround to make the business line that generates the older .xls file move to a newer format .xlsx file, negating the need for a conversion.  A crude but effective workaround. :)
