### ISSUE TITLE
Append data to next open column instead of row?

### ISSUE THREAD

**Issue by whpeterson** [dfinke/ImportExcel#805]
Is there a way to loop through data and append the results to the next column with a custom header, instead of the next open row?  Thanks!

**Comment by dfinke** [comment]
Can you post an example of what you're looking to do? This is for an already existing Excel file?

**Comment by whpeterson** [comment]
Actually I figured it out!

I set
$column = 1
for the start of the script.

Then I start my loop and for the first time I use export-excel, I use
-startcolumn $column and then the next line of code is $column =
$column+1.  So the next time through the results go to the next column and
so on.

I did have another question though - what is the easiest way to center data
horizontally in a column?  I've looked at different examples and it seems
complex for what I'm trying to do. I just have certain columns where I'd
like the data centered in the cell.  Thanks.

**Comment by dfinke** [comment]
You can use `-HorizontalAlignment Center` on the `Set-Format` function.

https://github.com/dfinke/ImportExcel/blob/12fa49e3142af2178ae1c6b18d8c757af0d629ac/Examples/ExcelBuiltIns/DSUM.ps1#L20

**Comment by whpeterson** [comment]
I saw that option, but am not sure how to add it to my scripts.

I usually gather all kinds of data and then put it into a variable and so
at the end of my script it looks like this:

$Data | Export-Excel $results -worksheetname "something" -autosize
-autofilter -boldtoprow -append

How would I use the set-format function for this example?

**Comment by dfinke** [comment]
In that sample, it uses -PassThru. Then you have access to the Excel document and you can use set-format to change the columns. 

There is no option on the Export-Excel function to set that.
