### ISSUE TITLE
Export data with "table cell reference" 

### ISSUE THREAD

**Issue by patware** [dfinke/ImportExcel#807]
When exporting data containing a formula with "structured references", the exported xls treats the reference as an error '#REF'

To reproduce

```Powershell
$data = @([PSCustomObject][Ordered]@{id=1;name="John Doe";dateOfBirth=(get-date -year 1990 -Month 1 -Day 1);age="=YEAR(NOW())-YEAR([@dateOfBirth])";yearNow="=YEAR(NOW())"})

$data | export-excel -Path Foo.xlsx -TableName "Bar"
```
the yearNow worked.  but the age formula becomes =YEAR(NOW())-YEAR(#REF!)

| id | name | dateOfBirth | age | yearNow |
| --- | --- | --- | --- | --- |
| 1 | John Doe | 1990.01.01 08:50 | #REF! | 2020 |

I understand I could calculate the values in PowerShell, but some formulas like vlookup make the the sheet more dynamic.

This might be similar to https://github.com/dfinke/ImportExcel/issues/790

**Comment by dfinke** [comment]
## AutoNameRange

You need to add the `AutoNameRange` switch so you can reference that property in formulas.

I also remove the `@` from `dateOfBirth` in `age`.

```powershell
$XLFILE="$ENV:TEMP\Foo.xlsx"
rm $XLFILE -ErrorAction SilentlyContinue

$data = @(
    [PSCustomObject][Ordered]@{
        id=1
        name="John Doe"
        dateOfBirth=(get-date -year 1990 -Month 1 -Day 1)
        age="=YEAR(NOW())-YEAR([dateOfBirth])"
        yearNow="=YEAR(NOW())"
    }
)

$data | export-excel -Path $XLFILE -TableName "Bar" -Show -AutoNameRange -AutoSize
```

**Comment by patware** [comment]
HA !  you're amazing.

**Comment by patware** [comment]
Would it make sense to generate a PowerShell warning whenever the export-excel finds a formula containing a "structured reference" but not the -AutoNameRange switch ?  

Would it slow down noticeably the export-excel method ?  If so, maybe adding a "-diagnose" or "-troubleshoot" switch ?

Something like:

Warning: the column {columnName} contains a formula with structured reference but you didn't specify the -AutoNameRange.  

I like what the -verbose produces btw.

**Comment by dfinke** [comment]
It would also involve parsing formulas and figuring out built-in names, variables etc. That was on the table at one point. Too much work to build and maintain.
