### ISSUE TITLE
Export-Excel converts some unicode in cell contents 

### ISSUE THREAD

**Issue by mrstevec** [dfinke/ImportExcel#809]
I'm seeing the string values of some cells getting parsed as unicode, when I just want them left as unchanged strings. I've encountered this with both 7.0.1 and 7.1.0. 

With a simplified example CSV containing:
`Column 1,Column 2`
`O_x002f_S_x0020_Checks,`

Importing the CSV is successful. I see the unchanged data in the PSObjects. 
Then, exporting that CSV data ends up in Excel as: 
**O/S_x0020_Checks**

Note that it only converted the forward slash from it's unicode (x002f), but leaves the space (x0020) unchanged. 
Also, if I open the CSV directly in Excel, the value is unchanged from the original, as expected. The change seems to be happening during the Export-Excel step.

I've tried  passing -NoNumberConversion * with no change in the behavior. 

![ParsedUnicode](https://user-images.githubusercontent.com/3779109/77395851-b38e7580-6d5f-11ea-8f7b-235895d684d4.png)

**Comment by jhoneill** [comment]
This appears to be how excel renders that text. 
I did the same as a you and saw the same result in excel, but without closing (and saving) I imported the data back. 
```
>import-excel C:\Users\xxxxx\AppData\Local\Temp\tmp67E2.xlsx

Column 1               Column 2
--------               --------
O_x002f_S_x0020_Checks         
```

Then I saved closed and saved the document and ran the command again 
```
>import-excel C:\Users\P10506~1\AppData\Local\Temp\tmp67E2.xlsx

Column 1         Column 2
--------         --------
O/S_x0020_Checks         
```

Which seems to indicate that what you have in the CSV file gets written to the XLSX file but is interpreted oddly by Excel
If I paste your string into excel, save and import ... more wierdness
![image](https://user-images.githubusercontent.com/16209593/77458195-b5a31380-6df5-11ea-9b12-9ea55c586eb2.png)


But if I crack open the file (rename to zip, poke and prod the XML files)
![image](https://user-images.githubusercontent.com/16209593/77458779-a2447800-6df6-11ea-9a45-2ef915e5fa35.png)
I get a third version of that string. 

That did make me wonder if when the file is written something strange happens. So I did the export again and did the same to the file 
![image](https://user-images.githubusercontent.com/16209593/77459380-8d1c1900-6df7-11ea-80d4-833c7c624b77.png)

It's not quite  the same was what we write and read back. I don't understand why the additional _x005F has become _ and the _x002F has become / but _x0020 has not become space. Clearly EPPlus processes these codes one way, and Excel a slightly different way, but it's not something under our control I'm afraid.

**Comment by mrstevec** [comment]
Thanks for so quickly taking a look at the issue and providing a thorough explanation. If I get some time, I'll try reproducing the issue directly with EPPlus and raise an issue over there if successful. 
In the meantime, since I'm programmatically reading and writing these values, I'll just unescape prior to writing to the xlsx, and re-escape when reading from the xlsx.

**Comment by dfinke** [comment]
EPPlus has stopped development. They are moving towards a paid product.
