### ISSUE TITLE
Condtional Formating - Not ThisMonth

### ISSUE THREAD

**Issue by WinOpsEngineer** [dfinke/ImportExcel#810]
With New-ConditionalText   is there a way to do condtional coloring if  the date is not from "ThisMonth"  or if the date is X days old?

example - 

 $data |Export-Excel c:\temp\patched.xlsx -Show `
    -ConditionalText (New-ConditionalText   -ConditionalType ThisMonth -BackgroundColor Green)

**Comment by dfinke** [comment]
@jhoneill was thinking of using `-ConditionalType Expression` don't see a `-Formula` parameter on that function, No examples either :)

Before I go done the rabbit hole wanted to get a second opinion.

**Comment by jhoneill** [comment]
Excel doesn't have ready made conditional formats for "`not <date test>`"  So you can choose "today", "This month" etc, but not "Not today"  
You can format a whole column with the "Not This month" format and then apply a "This month" conditional to put this months values back to normal text. I think I used that dodge in the compare worksheet stuff I did. 
 
Or you can `-conditionalType Expression`. The formula goes in `-Text` if using` New-ConditionalText ` and in `-conditionValue` if calling `add-ConditionalFormatting`  directly  

if the formatting range is B2:B20  the formula `B2<TODAY()-DAY(TODAY())+1` will select anything from prior months  (or just `today() - 60` for a fixed number of days) . `B2>DATE(YEAR(NOW()),MONTH(NOW())+1,1)-1` will select anything from future months. 
If you specify the address without $ signs it will treat it as a relative address

Yes. I should write a pile of examples. Added to the to do list.

**Comment by dfinke** [comment]
@jhoneill Cool. Thanks! Yeah I saw the `B2` approach. The "Excel Way" is to use expressions, now armed with the `-Text` way. I'll add a `TODO` and will spin up some examples.

**Comment by dfinke** [comment]
## First Pass

***for the  `'A2=today() - 60'` to work, need to change the 1/28/2020***

![image](https://user-images.githubusercontent.com/67258/77828099-f51c7900-70ef-11ea-8df9-cadbfceb5094.png)

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Date,ItemName,TotalSold
1/1/2020,orange,37
2/1/2020,nail,11
3/1/2020,apple,36
4/1/2020,orange,86
5/1/2020,screwdriver,96
1/28/2020,lime,34
1/1/2020,drill,7
1/1/2020,apple,4
1/1/2020,screwdriver,97
1/1/2020,drill,6
"@ | select @{n='Date';e={get-date $_.date}},ItemName,TotalSold

$p=@{
    ConditionalType='Expression'    
    Range="A2:A11"
}

$future='A2>DATE(YEAR(NOW()),MONTH(NOW())+1,1)-1'
$sixty='A2=today() - 60'

$ct1 = New-ConditionalText -Text $future @p -BackgroundColor red
$ct2 = New-ConditionalText -Text $sixty  @p -BackgroundColor green -ConditionalTextColor white 

$xl = Export-Excel -InputObject $data -Path $xlfile -AutoSize -ConditionalFormat $ct1,$ct2 -PassThru

Set-Format -Worksheet $xl.Sheet1 -Range "A:A" -NumberFormat 'Short Date'

Close-ExcelPackage $xl -Show
```

**Comment by WinOpsEngineer** [comment]
Hi Doug 

I am running that code and only  the dates that fall into red are bing formatted no green

![image](https://user-images.githubusercontent.com/40338530/77860791-20ca5c80-71df-11ea-924c-f2135c7fde0a.png)

**Comment by dfinke** [comment]
for the 'A2=today() - 60' to work, need to change the 1/28/2020

That date is now 61 days old :)

**Comment by WinOpsEngineer** [comment]
Thank you :)
