### ISSUE TITLE
Import-Excel: Use a Column as an Object

### ISSUE THREAD

**Issue by kesch095** [dfinke/ImportExcel#811]
Hey there,

thank you for this really nice Module!

I got a question though: 
The Import-Excel cmdlet clearly states, that each row represented in an excel file is formatted as an object.
Is it somehow possible to represent each Column as an object?

Greetings

**Comment by jhoneill** [comment]
Not as implemented at present. 
If instead of having property names  in row 1 and each row of data being an object with those properties
you want, column 1 to hold the property names and each column of data to be an object with those   properties, it would be possible to make a custom version of the import-excel function (including its embedded get-propertyNames function) which switches rows and columns around. 

It would be more complicated to **export** in columns instead of rows, and I would prefer not to add an import which we can't re-export.  If you aren't able to make the changes yourself @dfinke  or I might be able to produce an example you can use.

**Comment by dfinke** [comment]
Also, could you post an example of what you're looking for. Sounds like a custom sample is the start and then see if it can be generalized.

**Comment by Kivikaki** [comment]
Hi,
sorry for the late reply. 

@jhoneill 
Thats exactly what i want to achieve. I actually don't even need the export function for my use case.

As for the example:
I am a system engineer in an it company and created a preinstallation worksheet for our customers. I want to be able to extract the information the customer typed into the worksheet and configure - in this example - a set of VMware ESXi Hosts according to the information in the worksheet. 
For that i already created a set of PowerShell scripts. I now need to import the information from the worksheet.

[Example.xlsx](https://github.com/dfinke/ImportExcel/files/4443439/Example.xlsx)

**Comment by jhoneill** [comment]
Here's a little sample . 

```PowerShell
Function Import-Bycolumns    {
    Param(
        [Parameter(Mandatory=$true)]
        [OfficeOpenXml.ExcelPackage]$ExcelPackage,
        [Int]$StartRow = 1,
        [String]$WorksheetName,
        [Int]$EndRow ,
        [Int]$StartColumn = 1,
        [Int]$EndColumn  
    )
    Function Get-RowNames {
        [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseSingularNouns', '', Justification = "Name would be incorrect, and command is not exported")]
        param(
            [Parameter(Mandatory)]
            [Int[]]$Rows,
            [Parameter(Mandatory)]
            [Int]$StartColumn
        )    
        foreach ($R in $Rows) {
            #allow "False" or "0" to be  headings
            $Worksheet.Cells[$R, $StartColumn] | Where-Object {-not [string]::IsNullOrEmpty($_.Value) } | Select-Object @{N = 'Row'; E = { $R } }, Value
        }    
    }

    if     (-not  $WorksheetName) { $Worksheet = $ExcelPackage.Workbook.Worksheets[1] }
    elseif (-not ($Worksheet = $ExcelPackage.Workbook.Worksheets[$WorkSheetName])) {
        throw "Worksheet '$WorksheetName' not found, the workbook only contains the worksheets '$($ExcelPackage.Workbook.Worksheets)'. If you only wish to select the first worksheet, please remove the '-WorksheetName' parameter." ; return
    }

    if (-not $EndRow   ) { $EndRow     = $Worksheet.Dimension.End.Row }
    if (-not $EndColumn) { $EndColumn = $Worksheet.Dimension.End.Column }
                
    $Rows    = $Startrow .. $EndRow  ;
    $Columns = (1 + $StartColumn)..$EndColumn

    if ((-not $rows) -or (-not ($PropertyNames = Get-RowNames -Rows $Rows -StartColumn $StartColumn))) {
        throw "No headers found in left coulmn '$Startcolumn'. "; return
    }
    if (-not $Columns) {
        Write-Warning "Worksheet '$WorksheetName' in workbook contains no data in the rows after left column '$StartColumn'"
    }
    else {
        foreach ($c in $Columns) {
            $NewColumn = [Ordered]@{ }
            foreach ($p in $PropertyNames) {
                $NewColumn[$p.Value] = $Worksheet.Cells[$p.row,$c].text
            }
            [PSCustomObject]$NewColumn
        }
    }
}


$excel  = Open-ExcelPackage $env:TEMP\test.xlsx
Import-Bycolumns $excel 
```

It could have more of the bits of import excel added to it but I propose to just leave it as an example

**Comment by dfinke** [comment]
@jhoneill would that make sense to add as an example in the repo?

**Comment by Kivikaki** [comment]
Thank you, thats exactly what i needed!

**Comment by jhoneill** [comment]
@Kivikaki  glad to hear it. 

@dfinke  yes it would. I can add it next time I do something or you can copy/paste :-)
