### ISSUE TITLE
Enhancement Request - Add Credential Parameter

### ISSUE THREAD

**Issue by Skatterbrainz** [dfinke/ImportExcel#812]
If there already is a way to invoke Import-Excel or Get-ExcelWorkbookInfo with -Credential please let me know?  Otherwise, would it be possible to add this for reading files on network shares which require alt credentials, and not having to use PS Session objects?  Thank you!

**Comment by dfinke** [comment]
Would be good t make that consistent. In the meantime, `Import-Excel` has a `-Password` parameter and `Open-ExcelPackage` does too. You can use the `Open-ExcelPackage` to do what `Get-ExcelWorkbookInfo` does and you should be in business.

**Comment by Skatterbrainz** [comment]
The challenge I'm facing right now is connecting to a file on a share using alternate credentials as part of an automation process (service account). Pssession seems to be the only option for now.
