### ISSUE TITLE
Macro VBA

### ISSUE THREAD

**Issue by ptondoh** [dfinke/ImportExcel#814]
Hi Doug.
Thanks for you module. 
I try to execute macro but I can't.
I see this post https://github.com/dfinke/ImportExcel/issues/57#issuecomment-167433059

But the option VBA don't exist in the new module. How can I execute VBA macro.

Thanks for your help.

**Comment by jhoneill** [comment]
This module reads and writes .XLSX files without using Excel. 
To run a Macro you need to use COM to create and Excel Application object, and tell Excel to run your macro. 
Somewhere we did have a guide for how to Add the VBA to the file being created, but run VBA, do some (but not all) calculations, render charts and pivot tables, apply filters to data and a few other things the file must be opened in Excel.

**Comment by ptondoh** [comment]
Ok. But in the example HelloWorldVBA.ps1 there is :
$xlfile = "$env:temp\test.xlsm"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$Excel = ConvertFrom-Csv @"
Region,Item,TotalSold
West,screwdriver,98
West,kiwi,19
North,kiwi,47
West,screws,48
West,avocado,52
East,avocado,40
South,drill,61
North,orange,92
South,drill,29
South,saw,36
"@ | Export-Excel $xlfile -PassThru -AutoSize -Autofilter

$wb = $Excel.Workbook
$sheet = $wb.Worksheets["Sheet1"]
$wb.CreateVBAProject()

$code = @"
Public Function HelloWorld() As String
    HelloWorld = "Hello World"
End Function

Public Function DoSum() As Integer
    DoSum = Application.Sum(Range("C:C"))
End Function
"@

$module = $wb.VbaProject.Modules.AddModule("PSExcelModule")
$module.Code = $code

Set-ExcelRange -Worksheet $sheet -Range "h7" -Formula "HelloWorld()" -AutoSize
Set-ExcelRange -Worksheet $sheet -Range "h8" -Formula "DoSum()" -AutoSize

Close-ExcelPackage $Excel -Show

The code run without excel application installed.
![image](https://user-images.githubusercontent.com/31854175/79229229-aa5d6980-7e30-11ea-81b5-5caa1b7104c6.png)


I have a macro which merges the lines which have the same string in the same column.
I tried: Set-ExcelRange -Worksheet $ sheet -Range "A2: A" -Formula "Fusion()" -AutoSize
But formula is for a cell not a column. But the macro is load :
![image](https://user-images.githubusercontent.com/31854175/79229741-86e6ee80-7e31-11ea-94f4-1eea0305e2ce.png)

Do you have any ideas how to run a macro for one or more columns with this module?

**Comment by jhoneill** [comment]
No. That puts the code in the file. The code doesn't execute unless you load the file into excel. 

You can create a user defined function, and add the VBA.  In that Set-Excel range you can set just one cell with "A2:A2" - it looks like the formula doesn't change in different cells so you don't need to use a script block there.

**Comment by ptondoh** [comment]
OK. Expect-Excel cannot execute macro on a column but only on cell.
I will search again on the web.
Thank you.
