### ISSUE TITLE
Dynamic range select and merge cells

### ISSUE THREAD

**Issue by DjScava** [dfinke/ImportExcel#815]
Hello, i have a task to create report monthly and send it as Excel table with some specific formatting.
I have a sheet with size in columns that changed based on how many days was in month. and i need to merge first line with width of all of that columns. for example in January there will be 32 cells merged in 1-st row. in February 29(30) cells... 
How to do it using powershell and maybe export-excel module? i didn't found solution. please help.

**Comment by jhoneill** [comment]
There's an example here. https://github.com/dfinke/ImportExcel/blob/master/Examples/Styles/NewExcelStyle.ps1

For this one I'd end that one with 
```PowerShell
$excel =  $data | Export-Excel $xlfile -Show -AutoSize -AutoFilter -Title $reportTitle -PassThru
$range = $excel.sheet1.Dimension.Address -replace "\d+","1"                 
Set-ExcelRange -Range $range -Worksheet $excel.sheet1 -Merge                
Close-ExcelPackage $excel -show 
```
First line keeps the file open 
Second line gets the size of the sheet and changes all the numbers to 1 (change the sheet name if necessary, and you could select a different row) - so the range is row 1 for the width of the cells
Line 3 merges cells in the range  - you can apply other formatting there
And the last line saves and opens the file.

**Comment by DjScava** [comment]
Nice. thanks.
