### ISSUE TITLE
Redirect verbose messages to a variable or redirect to log file

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#816]
Dear All,
I am using the module to perform excel based manipulation on schedule. 
Most of the module have a -Verbose switch 

`Copy-ExcelWorkSheet -SourceWorkbook $Xl -sourceWorksheet 1  -DestinationWorkbook $Xl -DestinationWorksheet "Sheet 2" -Verbose
`
What I would like to do is capture the Messages generated by using the "Verbose" to go to my log file, so that I can review them latter /on demand to see how the script is performing as it works with different input excel files.

To do my logging, I use an additional module called "PSlogging" , So i need help to understand once I run the command  in verbose mode, how do I capture it and then write to log file as below in my Pseudo code.

```
Log-Start -LogPath $logpath -LogName $logfile -ScriptVersion $sScriptVersion
Log-Write -LogPath  $fullLogPath  -LineValue "$([DateTime]::Now): Script started"

Copy-ExcelWorkSheet -SourceWorkbook $Xl -sourceWorksheet 1  -DestinationWorkbook $Xl -DestinationWorksheet "Sheet 2" -Verbose

Log-Write -LogPath  $fullLogPath  -LineValue  'Verbose message from above command'
```

Thanks in advance.

**Comment by jhoneill** [comment]
Unlike warning and error there isn't a -VerboseVariable option in the common parameters so the best solution is to use 4>  or 4>> which redirects verbose (2 does, error, 3 is warning, 4, verbose, 5 debug, 6 information and HOST  * is all of them)
