### ISSUE TITLE
Get-Command -Module ImportExcel 

### ISSUE THREAD

**Issue by rbutgins21** [dfinke/ImportExcel#817]
This isn't showing me any modules when running this command.  Needing to use ExportExcel.

**Comment by dfinke** [comment]
How was this resolved?

**Comment by rbutgins21** [comment]
Had to use the following command:

powershell –ExecutionPolicy Bypass

**Comment by rbutgins21** [comment]
I'm now having issues with the following:

$someCollection | export-excel -tablename SomeTable -tablesytyle Medium13 -path C:\users\me\ExcelFileWithATableGeneratedByPowershell.xlsx

**Comment by rbutgins21** [comment]
Can $someCollection be replace with s:\sharepoint_activity_online.xls in the command below?  I am just trying to copy from xls to xls and wrapping a table around the data in the target file.


$someCollection | export-excel -tablename SomeTable -tablesytyle Medium13 -path C:\users\me\ExcelFileWithATableGeneratedByPowershell.xlsx

**Comment by dfinke** [comment]
Only xlsx is supported, not xls. The xls would need to be saved in a newer version.

**Comment by rbutgins21** [comment]
Here is what I am getting (new to powershell):

PS C:\WINDOWS\system32> s:\sharepoint_online_actvity.xlsx | export-excel -tablename table1 -tablesytyle Medium13 -path s:\sharepoint_online_activity1.xlsx

s:\sharepoint_online_actvity.xlsx : The term 's:\sharepoint_online_actvity.xlsx' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ s:\sharepoint_online_actvity.xlsx | export-excel -tablename table1 -t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (s:\sharepoint_online_actvity.xlsx:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rbutgins21** [comment]
If I want to copy data from an existing xlsx file to a new xlsx file and convert to table, what do replace $someCollection with?

$someCollection | export-excel -tablename table1 -path s:\sharepoint_online_activity1.xlsx
