### ISSUE TITLE
Import-Excel How can I do foreach ($cell in $row)

### ISSUE THREAD

**Issue by stigeide2** [dfinke/ImportExcel#818]
I would like to loop through the cells in the row like this:
    $rows = Import-Excel -Path "...."
    foreach ($row in $rows) {
        foreach ($cell in $row) {
        Write-Output $cell[1]
        }
    }

How can I do this without referring to the column name $($row.P2)

**Comment by jhoneill** [comment]
1. You don't want to use Import-Excel. Use Open-Excel package. 
2. The Sheet object isn't a nice array of rows (or columns) with cells for foreach to use. Row and column objects exist but really only for fomatting. 
3. $cell[1] wouldn't mean anything. A cell has an address, a style  if you want the value you could do this 

```powershell
$excel  = Open-ExcelPackage $env:TEMP\test.xlsx
$excel.sheet1.cells | sort @{e={$_.start.row}},@{e={$_.start.column}} | select -expand value
```

Import-Excel assumes a square of data, usually headings in the top row, and each row after that is a row of data which becomes  an object with a property for each heading.

**Comment by stigeide2** [comment]
> Could you say a bit more about what you're trying to do. Import-Excel returns an array of objects with property names and no info about the underlying spread sheet.

Thank you.
I am building an Oracle insert statement from the values of each row.
Example code:

    $rows = Import-Excel -Path "$($PWD)\$($Path)"
    foreach ($row in $rows) {
    if (<column is a date>) {
        $V,$z,$x = [datetime]::FromOADate("$($row.P1)").ToString([cultureinfo]::GetCultureInfo('en-US')).split(' ',3)
         $V = "TO_DATE('$($V)', 'mm/dd/yyyy')"}
    else {$V="'" + $($row.P1) + "'"}
   $query = "INSERT INTO $($Target) ($($Columns)) VALUES ($($V)";

Here $($row.P1) returns the value of the first column in the given row. I would like to loop through all the values in a row

**Comment by stigeide2** [comment]
This works, but very slow:

    For ($i=$ws.Dimension.Start.row; $i -le $ws.Dimension.end.row; $i++) {
    For ($j=[System.Decimal]::Parse($StartColumn); $j -le [System.Decimal]::Parse($EndColumn); $j++) {
    $v=$ws.Cells[$i,$j].Value
    echo $v >> "$($PWD)\Query.txt"
    }
    }

Do you have a tip to what I could do to speed things up?
