### ISSUE TITLE
DuplicateValues diffrence between Add-Conditionalformating vs New-ConditionalText

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#819]
Hello All,

I have spotted an issue when applying conditional formatting using the two different methods as described below

When using New-Conditional Text, the final results is as shown in the image

```
$UniqueValues=New-ConditionalText -ConditionalType UniqueValues -Range A:A -BackgroundColor lightgreen -ConditionalTextColor DarkGreen
$DuplicateValues=New-ConditionalText -ConditionalType DuplicateValues -Range A:A
$Data| Export-Excel $DuplicateFilePath -AutoFilter -AutoSize -ConditionalText($DuplicateValues,$UniqueValues)
```
![image](https://user-images.githubusercontent.com/48583862/79944091-47597b80-849d-11ea-9b5b-6db77c9cf648.png)

But when using Add-CoditionalFomating , the output is as shown in image 2. 
and is not working and the data is not highlighted. 

`Add-ConditionalFormatting -Worksheet $Xl.Workbook.Worksheets["ValidationResult_CF"] -Range "A2:A1048576" -RuleType DuplicateValues -ForegroundColor Red -BackgroundColor LightPink`

![image](https://user-images.githubusercontent.com/48583862/79944270-b0d98a00-849d-11ea-9e25-533a6d80637d.png)

**Question:** Why this is different? while the "RuleType" switch does given the option to utilize "duplicate" and "unique" values still excel interprets its as a formula.

**Resolution Needed:** I am trying to add multiple conditional formatting based on forumlas and inbuilt functions.

**Comment by cprograemer84** [comment]
Hi,
One more issue, I am unable to move the conditional formatting to a different sheet, 
i tried to use to add the sheet name but it didn't  work.  ValidationResult_CF!A:A 

New-ConditionalText -ConditionalType UniqueValues -Range ValidationResult_CF!A:A -BackgroundColor lightgreen -ConditionalTextColor DarkGreen

**Comment by jhoneill** [comment]
> Question: Why this is different? while the "RuleType" switch does given the option to utilize "duplicate" and "unique" values still excel interprets its as a formula.


That's weird and I'll need to check it properly - as you say if you specify -Ruletype the next thing on the command line should be the value to go in ruletype, it shouldn't get associated with the formula. I need to get on my other machine to check this out 

On the second one you can't specify a range of cells to work on in EPPlus as a string with a worksheet name at the start as you would in excel. I did look at going back and retrofitting this ability  but it's needs to be changed in many places. You can specify the worksheet when calling add-conditional formatting.
