### ISSUE TITLE
Charts with multiple series doesn't seem to work

### ISSUE THREAD

**Issue by redoz** [dfinke/ImportExcel#82]
I was trying to add two series to one chart using the following code:
```
Import-Module -Name ImportExcel -Verbose
$raw = @"
A,B,C,Date
2,1,1,2016-03-29
5,10,1,2016-03-29
"@
$data = ConvertFrom-Csv -InputObject $raw
Remove-Item -LiteralPath C:\temp\temp.xlsx
$data | Export-Excel -Path c:\temp\temp.xlsx -AutoSize -TableName Impressions -Show -ExcelChartDefinition @(
    New-ExcelChart -Title Impressions -ChartType Line -Header "Something" -XRange "Impressions[Date]" -YRange @("Impressions[B]","Impressions[A]")
) 
```

But it doesn't seem to work, it would appear that ```XRange``` referenced on https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L359 should actually be ```YRange``` (as that is the property it indexes into in the loop: https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L365).

**Comment by dfinke** [comment]
Thanks for posting. I like where this is heading. I had not considered this approach.

I'll investigate. Feel free to do a PR if you get there first.
