### ISSUE TITLE
How to get value from a .xlxs sheet specific cell then use that as varable in PS

### ISSUE THREAD

**Issue by rhannigan** [dfinke/ImportExcel#820]
Hi 
 to start with i am new to PS i have created a code below that works fine for the machine that has excel installed but the actual machines that I am building will not have excel installed i came across 2 modules ImportExcel and PSExcel.  PS excel has a Get-CellValue but when i use this 
![Get-Cell Value](https://user-images.githubusercontent.com/64148559/79993924-3284e400-84ad-11ea-8574-ce181f7499af.PNG)

I am trying to take the values of a cell with in a worksheet to use this to then rename, allocate ip address this cell value to both the renaming and ip address of the the network cards.  The xlxs is a master record for all IP addressing and each site is different for our HMI connections yes i can do this manually but as part of the build process as each site has 3 machines with 12 NIC connections and with each image deployed windows automatically assigns the -Interface description differently 

My current code that works (this is just one adaptor currently to keep it short) 
`#select excel file you want to read
>> $FilePath = "C:\Users\RH34322\Desktop\test.xlsx"
>> $SheetName1 = "Summary"
   $SheetName2 = "132 HMI Ports"
>>
>> #create new excel COM object
>> $objExcel = New-Object -ComObject Excel.Application
>> $objExcel.Visible = $false
>>
>> #open excel file
>> $wb = $excel.workbooks.open($FilePath)
>>
>> #select excel sheet to read data
>> $WorkSheet = $wb.Worksheets.Item($SheetName)
>>
>> #select Cells to read
>> $LocalName1 = $WorkSheet1.Range("E72").Text
>> $AdaptorName1 = $Worksheet1.Range("G72").Text
>> $LocalName2 = $WorkSheet1.Range("E73").Text
>> $AdaptorName2 = $Worksheet1.Range("G73").Text
   $IpAddress1 = $worksheet2.Range ("C37").Text

>>
>> #rename both scada ports then team then allocate ip address and subnet
>> Rename-NetAdapter -InterfaceDescription $AdaptorName1 -newname $LocalName1
>> Rename-NetAdapter -InterfaceDescription $AdaptorName2 -newname $LocalName2
>> NEW-NetSwitchTeam -name "TEAM_Onboard_A-Onboard_B_SCADA" -teammembers $LocalName1,$LocalName2
>> $interface = Get-NetIPInterface -InterfaceAlias "TEAM_Onboard_A-Onboard_B_SCADA" -AddressFamily IPv4
>> $interface | Remove-NetRoute -AddressFamily IPv4 -Confirm:$false
>> $Interface | New-NetIpAddress -IpAddress $IpAddress1 -PrefixLength 28 -DefaultGateway 172.216.22.30

>>$excel.Quit()

>>#force stop Excel process
>>Stop-Process -Name EXCEL -Force`

I am hoping that somebody may be able to help point me to the correct syntax to use for either modules or by using open office.  I only require to get the information into PS no changes to the excel sheet as once created becomes a fixed record.

Cheers hopefully here back soon 

thank you

**Comment by cprograemer84** [comment]
Hi, 
copying pasting the below snippet from another tread that I had kept handy in my notes,
$excel  = Open-ExcelPackage -path foo.xlsx
$ws = $excel.NameOfYourSheet 
$ws.cells | where {$_.value  -gt $foo} 
or $ws.cells["b2:b3"] #for a range
or $ws.cells["3:3"] #for a row
or $ws.cells["b:b"] #for a column

 and finally
close-excelPackage $excel
