### ISSUE TITLE
Support to add comment

### ISSUE THREAD

**Issue by alwaysharsha** [dfinke/ImportExcel#823]
Can we add support to comment on the cell when a condition is met.

**Comment by dfinke** [comment]
Quick pass through the EPPlus source, doesn't look like they support that. Needs investigation.

**Comment by vandreytrindade** [comment]
Hi! I'm trying to use your module to finally stop using Excel DCOM to edit a xlsx file.

Everything works fine using the **Open-ExcelPackage*** cmdlet.
When I try to add a comment it returns that the comment is added:
[![Add-Comment.jpg](https://i.postimg.cc/sfmxwhX4/Add-Comment.jpg)](https://postimg.cc/Bt8Jvt2j)
But when I try to open the file it says that it has problems and if I want to recover it.
Then it show an error saying that comments were removed:
[![Error.jpg](https://i.postimg.cc/fLZWvzQP/Error.jpg)](https://postimg.cc/8FKVpV5d)

Any idea why?
