### ISSUE TITLE
Exception calling "Save" with "0" argument(s): Export-Excel.ps1:672 char:32

### ISSUE THREAD

**Issue by wyzerd** [dfinke/ImportExcel#825]
Fails sporadically on this call:
$ProjectSet | Export-Excel -Path $Outpath -FreezeTopRow -AutoSize -WorksheetName $SheetName -Append

PS D:\Repos\AzDO-Dev\Powershell> $PSVersionTable

Name                           Value                                                                                                                                                                       
----                           -----                                                                                                                                                                       
PSVersion                      5.1.17763.1007                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                     
BuildVersion                   10.0.17763.1007                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                         
SerializationVersion           1.1.0.1       

It runs fine for 1000 times and fails a few.

But when it fails, the file is destroyed.

**Comment by dfinke** [comment]
Seems like it may be the data in $ProjectSet causing the issue. You could save the that data in a separate file before exporting so you can better inspect it when it fails.

**Comment by wyzerd** [comment]
I tried to upload the file. I don't see anything amiss. 

But it fails to upload. I pasted the text below with identifiers changed. (Admin, User and OrgName)

The last error added a little something extra that I hadn't seen on previous failures:

`Test-Path : Access is denied
At C:\Users\garchibald002\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Open-ExcelPackage.ps1:23 char:28
+     if ($Create -and -not (Test-Path -Path $path)) {
+                            ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (D:\Repos\AzDO-D...it-orgname.xlsx:String) [Test-Path], UnauthorizedAccessException
    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.TestPathCommand
 
Could not open Excel Package D:\Repos\AzDO-Dev\Powershell\Audit\2020-Orgname.xlsx
At C:\Users\garchibald002\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:125 char:16
+         catch {throw "Could not open Excel Package $path"}
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not open ...it-domain3.xlsx:String) [], RuntimeException`


Below is the Data from $ProjectSet:
`
timestamp        : 2020-04-12T02:04:57.847Z
details          : USER was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Admin
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 155.201.35.117

timestamp        : 2020-04-11T15:27:46.52Z
details          : User was removed as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-11T15:18:49.913Z
details          : User was removed as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-14T08:32:56.493Z
details          : User was added as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-13T19:26:50.167Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-13T19:26:49.743Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-13T18:35:53.327Z
details          : User was added as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-13T15:54:26.4Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Admin
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 63.162.225.42

timestamp        : 2020-04-13T14:53:17.977Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-13T14:53:17.67Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-16T09:08:59.833Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-16T09:08:57.213Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-16T07:23:31.687Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-16T07:23:31.237Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T21:49:34.357Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T21:49:30.5Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T20:46:12.927Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Admin
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 155.201.35.58

timestamp        : 2020-04-15T20:26:27.31Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T20:26:26.923Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T15:07:28.71Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Admin
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 155.201.35.69

timestamp        : 2020-04-15T14:25:17.07Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T14:25:16.75Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T13:41:05.493Z
details          : User was added as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T13:31:46.62Z
details          : User was added as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T13:18:29.187Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T13:18:28.787Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T11:46:18.453Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-15T11:46:17.733Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-17T17:58:46.95Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-17T17:58:46.6Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-17T13:49:47.327Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-17T13:49:46.87Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-19T17:38:52.63Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Admin
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 155.201.35.69

timestamp        : 2020-04-19T17:17:11.397Z
details          : User was removed as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-19T17:15:06.17Z
details          : User was removed as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-19T17:14:31.173Z
details          : User was removed as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-19T16:58:54.88Z
details          : User was removed as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-22T07:56:09.38Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-22T07:56:08.527Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-21T22:30:49.44Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-21T22:30:48.983Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-21T17:58:15.927Z
details          : User was added as a member of group [DevOps-Org-Name]\Team Foundation Licensed Users
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

timestamp        : 2020-04-21T17:58:15.51Z
details          : User was removed as a member of group [DevOps-Org-Name]\DirectoryServiceAddMember-89f26cd5-87c5-4c17-93f0-b229d24abf6b-Group
actorDisplayName : Azure DevOps Service
scopeDisplayName : DevOps-Org-Name (Organization)
scopeType        : enterprise
ipAddress        : 

`

**Comment by dfinke** [comment]
You're going to need to whittle this down to a simple set of data and script that repros the issue.

**Comment by wyzerd** [comment]
I'm working on it.

**Comment by wyzerd** [comment]
Running it in smaller sets it completed without issue. 

It was parsing a log with 21 days. 

Unfortunately, like I said at the beginning this is a very intermittent failure. I added some sleeps because there are multiple saves in a loop. I suspect it is not completely closed when the next save hits. But I am unable to get it to happen on smaller datasets. 

I think what I will do is copy the file off before the new set runs and at the end if the files doesn't exist, restore the copy and try again. It's not an ideal solution, but the log I am saving off only goes 90 days and is used for auditing. 

Thanks for your quick attention on this and if I get a definitive answer to the root cause, I'll be sure to share it with you.
