### ISSUE TITLE
Totals Row in Tables

### ISSUE THREAD

**Issue by Vixine** [dfinke/ImportExcel#828]
Hi,

I must be thinking about this wrong, but I couldn't find a way to show the totals row when exporting to a table.

**Comment by dfinke** [comment]
Only a table can be created. Don't recall enabling adding totals. I believe it would be possible if you use `-PassThru` and then using PowerShell to set the the table properties to enable this.

@jhoneill ?

**Comment by dfinke** [comment]
## Add-ExcelTable

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
East,saw,29
South,nail,87
North,peach,87
West,avocado,51
West,banana,58
West,peach,14
South,lemon,15
North,melon,51
North,banana,69
East,screws,58
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -AutoSize -PassThru

$worksheet = $xl.Sheet1

$table = Add-ExcelTable -PassThru -Range $worksheet.cells[1, 1, 11, 3] -TableName "AllResults" `
    -TotalSettings @{"TotalSold"="Sum"; "Region" = "Count"}
    
Close-ExcelPackage $xl -Show
```

![image](https://user-images.githubusercontent.com/67258/80321616-77ca4e00-87ec-11ea-933b-1991d4701e44.png)
