### ISSUE TITLE
Failed creating property name

### ISSUE THREAD

**Issue by uSlackr** [dfinke/ImportExcel#829]
I'm trying to import using this command:
`$t = import-excel "Scan_Results_PA-13_test.xlsx" -startrow 8`

Results in this error: (file attached)
```
WARNING: Selecting columns 1 to 0 might give odd results.
Failed importing the Excel workbook 'J:\Net_ClientCD\RShearer\POAMS\Scan
Report\PA\Scan_Report_30_Day_Vulnerability\Scans to Combine\Scan_Results_PA-13_test.xlsx' with worksheet '': Failed
creating property names: Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.0.1\Public\Import-Excel.ps1:196 char:17
+ ...     catch { throw "Failed importing the Excel workbook '$Path' with w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed importin...o a null array.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook 'J:\Net_ClientCD\RShearer\POAMS\Scan Report\PA\Scan
   _Report_30_Day_Vulnerability\Scans to Combine\Scan_Results_PA-13_test.xlsx' with worksheet '': Failed creating pr
  operty names: Cannot index into a null array.
```

[Scan_Results_PA-13_test.xlsx](https://github.com/dfinke/ImportExcel/files/4547096/Scan_Results_PA-13_test.xlsx)

**Comment by dfinke** [comment]
Confirmed, I also copied it to another xlsx. Could you try to isolate the bad column?

**Comment by uSlackr** [comment]
If I select all and copy to another workbook, the import works fine.  some weird corruption? I have three workbooks, all were created as CSV and saved as xlsx.  Two of the three show this behavior.  The book I posted was 6500 lines long. I cut all but a few lines and still have the issue.

**Comment by dfinke** [comment]
Yeah, can't tell yet. I assumed the error being in a column, not a row. Not clear to me what the issue is.

**Comment by uSlackr** [comment]
I removed several columns containing "weird data" to no avail.

**Comment by dfinke** [comment]
@uSlackr were you able to resolve this?

**Comment by uSlackr** [comment]
No, but I’m pretty certain it is the file

\\Greg

________________________________

**Comment by Johno-AU** [comment]
Just ran into this error, saved a copy of the file and it first prompted  to save the file as a "strict Open XML spreadsheet (*.xlsx)", saved the copy as a "Excel Workbook (*.xlsx)", and then I was able to import the file.
