### ISSUE TITLE
Importing module on macOS results in failure due to incorrect placement of `finally` block

### ISSUE THREAD

**Issue by scrthq** [dfinke/ImportExcel#832]
On the PSM1 for ImportExcel v7.1.0, the last `finally` statement is wrapped within the `catch` statement preceding it instead of just after, resulting in the module failing to import if the `if` statement checking for `($IsLinux -or $IsMacOS) -or $env:NoAutoSize` returns `$true`:

![image](https://user-images.githubusercontent.com/12724445/80764781-0699dc00-8b07-11ea-8cfb-2c011be67a24.png)

***

Should be a simple fix, PR coming in shortly for it.

**Comment by scrthq** [comment]
PR opened with fix: https://github.com/dfinke/ImportExcel/pull/835

**Comment by dfinke** [comment]
Continue to review
