### ISSUE TITLE
Remove formulas, leave only data

### ISSUE THREAD

**Issue by msnbnntt** [dfinke/ImportExcel#833]
Hello,

I have a rather large Excel document that contains data from several different systems and builds a summary\comparison sheet which utilizes multiple vlookups per row. 

There's around 25k rows, with 23 columns that have formulas in it (mostly vlookup).

That being said, ImportExcel handles creating this document like a champ. 

The issue comes when I first open the Excel document. It takes a couple minutes for Excel to fully calculate everything and open. Once open, I have to copy the summary sheet & paste it as value, or else it's very laggy. And that would be fine if I only needed this report once, but I've been asked to make it weekly.

What I need to do if find a way to do the formulas, but leave only the data in the final report.

With a small amount of sample data, I've found this to work:
```
Close-ExcelPackage $Summary -Calculate
Import-Excel -Path $Summary -WorksheetName "Summary" | Export-Excel -Path $ReportPath -WorksheetName "Summary"

```

However, when applying this solution to the full report, it hangs on the calculating part (indefinitely). Any ideas?

**Comment by dfinke** [comment]
@msnbnntt does it hang on `Close-ExcelPackage`?

@jhoneill any ideas?

**Comment by jhoneill** [comment]
It would not surprise me if EPPlus had problems with Vlookup, especially with very large numbers of them  (it's the kind of thing where it would be very easy to leak memory. I'd look at what the CPU and memory consumption are doing while that close -calculate is running.  I'm going to bet on one thread running flat out (so 100/cores % CPU ) and memory consumption rising .  

So... if you're running on a machine where you have Excel, I'd use COM to open in Excel, wait while all the Vlookups go on, and then save and close. Then do the import/export (we did have a copy sheet to avoid doing that and losing all the formatting). It's not going to speed things up, but it can be automated so at least you won't have to sit and watch it.

**Comment by msnbnntt** [comment]
@dfinke Yes, it hangs there when I add -Calculate. If I don't add that flag, it'll finish, but then I can't import\export the sheet to get just only the data.

I've actually re-written my report to not use any more formulas. Converted all my data into HashTables and basically did my own version of vlookups.

Now I'm only using this module to export the finished Excel doc.
