### ISSUE TITLE
convert text file to excel file

### ISSUE THREAD

**Issue by alzahrania2** [dfinke/ImportExcel#836]
I have txt file and I want to use powershell command to export it in excel

usually i do this manually to export txt file as a data:

open excel
go to data 
export txt file
end

Thanks in advance for your great github

**Comment by ImportTaste** [comment]
I submitted a documentation-based PR that I'm still waiting to be approved that should help you out. For now, you can view it using this link:

https://github.com/ImportTaste/ImportExcel/blob/readme-chlog_redux/README.md#function-overview

**Comment by alzahrania2** [comment]
Thanks for your feedback. I didnt see any thing related to my subject. Let me explain it again. 

I am using cmd analysis event command but it only give me the output in .txt file. 

Command looks like like: 
Analysis_sysmon.exe -i -w  > network.txt

Usually I have to go to excel and go to data and import “network.txt”.  it will give me in excel table so I can filter it. Excel usually segregate the text to columns table without using condition. 

I want to use your pwoershell module to do it. Is it possible ?

**Comment by ImportTaste** [comment]
Yes, it's definitely possible. Hard to tell how difficult it would be without an example of the output, however.

**Comment by alzahrania2** [comment]
output txt file below

https://file.io/5TwBqN24

**Comment by alzahrania2** [comment]
output file attached

[network.txt](https://github.com/dfinke/ImportExcel/files/4578632/network.txt)

**Comment by ImportTaste** [comment]
Alright so it's all separated by tabs, shouldn't be too hard. Just turn each line into an array and then do an incrementing ForEach loop with the Set-ExcelRange command.

**Comment by dfinke** [comment]
Give this a try

```powershell
import-csv -Delimiter "`t" \network.txt | Export-Excel
```

![image](https://user-images.githubusercontent.com/67258/81030264-383bdb80-8e56-11ea-8e7b-ffab60f6c81f.png)

**Comment by alzahrania2** [comment]
Amazing it works. Big thanks to you  You made someone here happy :)

**Comment by alzahrania2** [comment]
Can you tell what is the function of “‘t”

**Comment by dfinke** [comment]
`t is a special character that represents a `tab` in PowerShell.
