### ISSUE TITLE
skipping first row

### ISSUE THREAD

**Issue by ilovefood2** [dfinke/ImportExcel#838]
is there a way to skip the first row when using Send-SQLDataToExcel ? 
i have a query and return a report, but first row needs to be skipped when importing to excel.

thanks

**Comment by dfinke** [comment]
Form PowerShell you can pipe it to `Select-Object`. `| Select-Object -Skip 1`

**Comment by ilovefood2** [comment]
Send-SQLDataToExcel -Connection "Server=$($server);Database=$($database);Trusted_Connection=True;" -MsSQLserver -SQL "$($SQLquery)"  -WorkSheetname Test -Path $path | Select-Object -Skip 1
 
I have this command, still doesn't work, can you please help? 


> Form PowerShell you can pipe it to `Select-Object`. `| Select-Object -Skip 1`

**Comment by dfinke** [comment]
Sorry, Send-SQLDataToExcel doesn't support that.
