### ISSUE TITLE
Add-ConditionalFormatting when multiple criteria are matched!!

### ISSUE THREAD

**Issue by ksbsantoshkumar** [dfinke/ImportExcel#842]
Is there a better way to use add-conditionalformatting when multiple criteria are matched? As per my below code, I get the entire E column highlighted rather than just the cell whose reference row's column B has the value as 'C:'.

`$excel = Import-Excel "C:\test1\disk.xlsx" | Export-Excel "C:\test1\disk.xlsx" -WorksheetName "disk" -AutoSize -FreezeTopRow -AutoFilter -PassThru

$ws = $excel.Workbook.Worksheets[1]

$lastrow = $ws.Dimension.end.Row

if ((($excel.Workbook.Worksheets[1].Cells["b2:b$lastRow"]).Value -like "c:" ) -and ($excel.Workbook.Worksheets[1].Cells["e2:e$lastRow"]).Value -le "80"  ) {
Add-ConditionalFormatting -WorkSheet $excel.Workbook.Worksheets[1] -Address "b2:b$lastRow" -backGroundColor "RED" -RuleType ContainsText -ConditionValue "c:" 
Add-ConditionalFormatting -WorkSheet $excel.Workbook.Worksheets[1] -Address "e2:e$lastRow" -backGroundColor "RED" -RuleType LessThan 80}

$excel.Save() ; $excel.Dispose()`

<img width="694" alt="err log" src="https://user-images.githubusercontent.com/7608629/81733695-12df4b00-94b0-11ea-98bd-346ec1014819.png">

**Comment by dfinke** [comment]
Please could you post the sample data as a CSV, in a string.

**Comment by ksbsantoshkumar** [comment]
[disk.xlsx](https://github.com/dfinke/ImportExcel/files/4617897/disk.xlsx)

**Comment by ksbsantoshkumar** [comment]
systemname | deviceid | volumename | Total Size(GB) | Free Space(GB) | Free % | PSComputerName
-- | -- | -- | -- | -- | -- | --
test | C: | Windows | 235.27 | 44.61 | 18.96 | localhost
test | D: | New Volume | 0.15 | 0.12 | 78.22 | localhost
test | C: | Windows | 235.27 | 44.61 | 18.96 | 127.0.0.1
test | D: | New Volume | 0.15 | 0.12 | 78.22 | 127.0.0.1

**Comment by dfinke** [comment]
You can use `Close-ExcelPackage $excel -Show`  in place of the `$excel.Save() ; $excel.Dispose()`

Not sure I understand what you want.

The second `Add-ConditionalFormatting` highlights everything because you specify `LessThan 80`, change 80 to 4 and it will only highlight two cells in that column.

**Comment by ksbsantoshkumar** [comment]
What I need is to highlight the cells in column E, when the drive letter is C: in clolumn B and when the value of column E is less than 80. So, ideally I shouldn't be getting highlights in rows where D: is written in column B.

Thank you on the closure part suggestion, BTW.

**Comment by dfinke** [comment]
This is more of an Excel question.
@jhoneill How would you construct that conditional? Sounds like a formula of sorts to do the do the "lookup" and value checking.

**Comment by jhoneill** [comment]
Yes its a formula. If the data starts in row 2 write it the conditionvalue as 'and(Left(B2,2)="c:" , E2<80)'
unless you write $C$2 as the condition fills down the row number will update. Just make sure the formula is the row number of the starting row.

**Comment by ksbsantoshkumar** [comment]
Thank you @dfinke @jhoneill for your ideas which contributed to the intended result.

I managed with below:

`Add-ConditionalFormatting -WorkSheet $excel.Workbook.Worksheets[1] -Address "e2:e$lastRow" -backGroundColor "Green" -RuleType Expression  -ConditionValue '=AND(B2="C:",E2<80)'
`
