### ISSUE TITLE
Generated tables do not auto-extend their formulas

### ISSUE THREAD

**Issue by christianlagiewka** [dfinke/ImportExcel#846]
I have a quick question regarding the tables created by ImportExcel and the export-excel function.

The tables are being created, but if I try to add another cell of data, it doesn't auto-add the appropriate to the column when the table range auto-extends as well. Shouldn't it?

I can even copy the data from the table into the same file, then insert the table (and set the _My Table has Headers_ option) and it will work within Excel.

I've attached the PowerShell script (as .txt) that I use to generate the example.

[Example of tables not autoextended their formulas.txt](https://github.com/dfinke/ImportExcel/files/4639697/Example.of.tables.not.autoextended.their.formulas.txt)

Excel 365's own options to auto-extend new data in tables is enabled.

I encountered this while creating a generic lookup table of Active Directory information that others can reference in their own spreadsheets. Instead of creating a lookup table with 100 or so rows on a separate worksheet, I was planning on including just a single example table entry and the consumers of the spreadsheet can paste their list of user ID's into the spreadsheet and have it auto-extend.

Thank you for any assistance.

**Comment by dfinke** [comment]
Not super familiar with the extending of the table. I was able to run your example and at the row after the last one, I started adding date in column A and the table extended.
