### ISSUE TITLE
How to refresh an existing Excel file with ODBC connections

### ISSUE THREAD

**Issue by hugh-martin** [dfinke/ImportExcel#847]
I have a scenario where I need to open an existing Excel file (.xls or .xlsx), refresh the file (it has two ODBC connections), and save the changes that result from the refresh. I need to do this in an automated fashion on a computer that does not have Excel on it.  It does, however, have the ODBC connection definitions. I understand that this is not possible with Import-Excel, but posting here to see if anyone has any other suggestions.  Thanks.

**Comment by vs4vijay** [comment]
Hi, Is this possible to call "RefreshAll()" method in workbook by using "**ImportExcel**" Module?
