### ISSUE TITLE
Export-excel -IncludePivotTable doesn't exist

### ISSUE THREAD

**Issue by Rdkotadia** [dfinke/ImportExcel#848]
I have installed module ImportExcel module in my windows 10 Professional version, it has  PSversion 5.1.18362.752. when I use Export-excel module with switch  -IncludePivotTable, it doesn't recognize it, However I can other switch called -IncludePivotChart.  how can I solve this problem.

**Comment by dfinke** [comment]
Please post an example of what you are trying to do.
