### ISSUE TITLE
MultiLevel Category Labels

### ISSUE THREAD

**Issue by asciiota** [dfinke/ImportExcel#849]
I have run into an issue that is similar to #641 where I have an XRange containing dates and hours in each day where I want to show both the hours in the day and the day.

![image](https://user-images.githubusercontent.com/48511146/82222629-b329e980-9960-11ea-9613-9d597895264e.png)

When doing this manually it requires you to check the Multi-Level Category Labels checkbox
![image](https://user-images.githubusercontent.com/48511146/82222750-dfde0100-9960-11ea-8bc7-792bf461304c.png)

Using VBA it would require
    ActiveSheet.ChartObjects("Chart6F14").Activate
    ActiveChart.Axes(xlCategory).TickLabels.MultiLevel = True

I have not been able to find a powershell method of achieving the same result and have tried the unsupported hack mentioned in #641 but always get an error 
The property 'InnerXml' cannot be found on this object. Verify that the property exists and can be set.

I was wondering if someone has since found a means of achieving this or if there are plans to add this capability to ImportExcel at any time in the future.

Thanks for the great work and support

**Comment by dfinke** [comment]
Googled 'TickLabels MultiLevel EPPlus', quick scan, didn't see anything. Could you set a breakpoint in the PS where the chart is created/added and check what is on the that object, `Get-Member`? See if there is a setting of sorts for that?

**Comment by asciiota** [comment]
Hi Sorry I have not replied sooner.  I was using the PassThru function and then using the Add-ExcelTable to add a table to the spreadsheet.  The Get-Member function does not return anything when using the Add-ExcelTable function.  I found that I had to use ImportExcel to preload the spreadsheet with all the data and then fall back to using PowerShell and Excel to create the chart.  When you specify the data-range for a chart using Powershell to drive Excel, Excel seems to automatically recognize that it needs to enable the Multi-Level Axis Category.  As a result I have fallen back to Excel to create this particular chart.  While I would be happy to share the script with you it is a bit long ... and probably long winded ... to be posted into this forum.  For the moment I have a solution that is delivering the required result ... and ImportExcel has enabled it to run in 40 seconds rather that 7 minutes.

**Comment by dfinke** [comment]
Sorry, I wasn't specific. I meant to say put a breakpoint inside the function Add-ExcelChart in the module. Could you post a script and some data the did this? I might be able to poke around.

Also, what contributed to the going from 420 seconds to 40? VBA was used initially?

**Comment by asciiota** [comment]
Hi
Thanks, I did not realize I could set a break point in a module outside of my own so I learnt something new :-).  Unfortunately it did not help me identify any Property I could leverage to control this setting.  I have attached a sample with some dummy data.  I have also included a spreadsheet that contains the desired output and one that shows the current output.  I have put some comments on line 83 in the script.  
[Issue_849.zip](https://github.com/dfinke/ImportExcel/files/4668810/Issue_849.zip)

The original process was using a very old method of populating the data into the spreadsheet.  It was literally writing one cell at a time.  Using your tool it can suck the data in and apply a range of formats very quickly.  Which is what I am currently doing however I am still having to finish of the customization of the spreadsheet by having PowerShell open the file with Excel and perform the required steps.  Even so your tool had a huge improvement on the time it takes to generate the report.  So please keep up the good work it is appreciated by many.
