### ISSUE TITLE
Export-MultipleExcelSheets.ps1 : superfluous ampersand ?

### ISSUE THREAD

**Issue by vandma** [dfinke/ImportExcel#851]
Hi,

The ampersand in line 24 is likely superfluous as it attempts to evaluate $entry.Value as a command
before piping it to Export-Excel

Sample error :

< snip >
UserState:
  UserStateChangedOn:
  UserType: Member
}
' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-MultipleExcelSheets.ps1:24 char:11
+         & $entry.Value | Export-Excel @parameters
+           ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (class User {
  ...Type: Member
}
:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by dfinke** [comment]
@jhoneill I don't see an example for this or tests. Any ideas?

**Comment by jhoneill** [comment]
I think it's one of yours (I never use .getenumerator. - not on principle just habit), and where I had done anything with the code I sorted out help and examples.  If there's no help I probably looked at it and ran away :-) 

It looks like the  $infoMap is meant to be a hash table of Worksheetname = Command_to_run 
so you might have 
@{users = "Get-aduser -filter *" ; computers = "Get-AdComputer" }

**Comment by vandma** [comment]
OK, I interpreted $infoMap as a hash of whatever enumerable Export-Excel can handle : arrays, hashes, ...
Which works perfectly fine ... without the ampersand.

**Comment by dfinke** [comment]
Oh yeah, thanks @jhoneill. Another example of why I should do documentation. Back in the early days when I was just experimenting with things. 

Maybe this should be removed?

**Comment by jhoneill** [comment]
Possibly move it the examples folder and include some explanation.
