### ISSUE TITLE
Install-Module -Name ImportExcel -Force WARNING: Unable to resolve package source

### ISSUE THREAD

**Issue by MSIH** [dfinke/ImportExcel#853]
When I try to install the module with powerhsell 5.1 I get this error:

nstall-Module -Name ImportExcel -Force

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api 
/v2'.
PackageManagement\Install-Package : No match was found for the specified
search criteria and module name 'ImportExcel'. Try Get-PSRepository to see all
available registered module repositories.
At C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809
char:21

**Comment by stahler** [comment]
Had the same issue.  
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
This explains it nicely. 
[https://jaapwesselius.com/2020/04/08/install-module-msonline-fails-with-unable-to-download-from-uri/](url)
