### ISSUE TITLE
Export-excel fails if called after import-excel

### ISSUE THREAD

**Issue by jensenjk** [dfinke/ImportExcel#857]
$scriptName = "CreateNewUser"
$scriptVer = "CET v1.0 2020.05.20"
$scriptDir = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent
$phonelist= Import-xlsx -path "s:\scripts\powershell\ad\workday\Telefonliste.xlsx" -header Extension,fullnumber,empname
get-service | export-excel r:\jkj.xlsx

this script fails with Add-Worksheet : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters t
hat take pipeline input.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:129 char:26
+             $ws = $pkg | Add-Worksheet @params

Changing the order - Export first then import - Export works
$scriptName = "CreateNewUser"
$scriptVer = "CET v1.0 2020.05.20"
$scriptDir = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent

get-service | export-excel r:\jkj.xlsx
$phonelist= Import-xlsx -path "s:\scripts\powershell\ad\workday\Telefonliste.xlsx" -header Extension,fullnumber,empname

**Comment by jensenjk** [comment]
Running version 7.1.0 of ImportExcel

**Comment by jhoneill** [comment]
The command is import-excel - do you have something else named import-xlsx ? Might that be redefining add-worksheet ?

**Comment by uSlackr** [comment]
Maybe run `get-command export-excel` after running both examples and compare the output
