### ISSUE TITLE
EPPlus License compliance - grey area

### ISSUE THREAD

**Issue by kilasuit** [dfinke/ImportExcel#859]
Whilst looking into EPPLls licensing for another project, I came across their note that v5 of EPPlus uses a dual licensing system which isn't simple as whilst it implies that it can be used for non-commercial means, I read it as users of this module in a commercial setting would all require a commerical license to be able to do so as per their licensing page https://www.epplussoftware.com/en/LicenseOverview & as a project that I know makes heavy use of EPPlus, I felt this needed raising.

This, I don't believe is made clear anywhere, and clarity on this is needed as to ensure this project is not falling foul of being incorrectly licensed, although it seems that if you were to stick on the last v4 version then the licensing becomes much less muddy and much more simplistic to follow

**Comment by dfinke** [comment]
Thanks, yeah, been following the EPPlus transition, waiting till the dust settles. When they announced this on their repo lots of folks raised many questions. We'll see how this all plays out and then move forward.
