### ISSUE TITLE
Import-Excel file headers to string array variable?

### ISSUE THREAD

**Issue by dburtsev** [dfinke/ImportExcel#860]
Import-Excel headers to string array variable?
$var = Import-Excel -Path $ExcelFileName -WorksheetName 'Sheet1' -StartRow 1 -EndRow 1 -DataOnly -NoHeader

We receive excel files from vendor. The number of columns between 5 and 7 (depends on vendor). How can I read column headers into array?
Thank you

**Comment by dfinke** [comment]
Please post an example.

**Comment by dburtsev** [comment]
This is Excel file:
Commodity Code,Status,Contract ID,Default Comm Code Line No
93000000000,Valid,XY1-001-20181202386,1

This is my code:
$ExcelFileName ='c:\dir\book1.xlsx'
[string[]]$hrds = @()
$var = Import-Excel -Path $ExcelFileName -WorksheetName 'Sheet1' -StartRow 1 -EndRow 1 -DataOnly -NoHeader
$hrds = $var.ToString()
$hrds

**Comment by dfinke** [comment]
```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Commodity Code,Status,Contract ID,Default Comm Code Line No
93000000000,Valid,XY1-001-20181202386,1
"@

Export-Excel -InputObject $data -Path $xlfile

$var = Import-Excel -Path $xlfile  -WorksheetName 'Sheet1' -StartRow 1 -EndRow 1 -DataOnly -NoHeader

$hdr = foreach ($name in $var.psobject.Properties.name) {
    $var.$name
}
 
$hdr
```

**Comment by dburtsev** [comment]
Works.
Thank you.
