### ISSUE TITLE
How to read one column from Excel into string array?

### ISSUE THREAD

**Issue by dburtsev** [dfinke/ImportExcel#861]
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue
$data = ConvertFrom-Csv @"
Commodity Code,Status,Contract ID,Default Comm Code Line No
93000000000,Valid,XY1-001-20181202386,1
93000000001,Valid,XY1-001-20181202386,1
"@
Export-Excel -InputObject $data -Path $xlfile
$var = Import-Excel -Path $xlfile -WorksheetName 'Sheet1' -StartColumn 1 -EndColumn 1 -DataOnly 
$values = foreach ($name in $var.psobject.Properties.name) {
        $var.$name
    }
Write-Host "Found Commodity Codes:"   
$values
Write-Host "End of script"

Output:
Found Commodity Codes:
2
2
1
End of script
Commodity Code
--------------
   93000000000
   93000000001
False
True
False
2

**Comment by dfinke** [comment]
Ok, this is not a forum for general PowerShell questions. What you are asking is not specific to ImportExcel.

`Import-Excel` reads and presents data the same way many other PowerShell functions do. It returns an object array, and each object will have a set of property names. Accessing the object with a property name is accessing by column.

```
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Commodity Code,Status,Contract ID,Default Comm Code Line No
93000000000,Valid,XY1-001-20181202386,1
93000000001,Valid,XY1-001-20181202386,1
"@

Export-Excel -InputObject $data -Path $xlfile

$data = Import-Excel $xlfile

$data.Status
```

**Comment by dburtsev** [comment]
Thank you, it works now.

$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue
$data = ConvertFrom-Csv @"
Commodity Code,Status,Contract ID,Default Comm Code Line No
93000000000,Valid,XY1-001-20181202386,1
93000000001,Valid,XY1-001-20181202386,1
"@
Export-Excel -InputObject $data -Path $xlfile
$data = Import-Excel $xlfile -StartColumn 1 -EndColumn 1 
$results = [System.Collections.ArrayList]::new()
[string]$str = [string]::Empty
foreach($ln in $data)
    {   
    $str = $ln | Select-Object -ExpandProperty "Commodity Code" -Property Name | Out-String
    [void]$results.Add($str)
    }
$results.Count
$results
Write-Host "End of script"
