### ISSUE TITLE
Named @references in formulas not showing in Excel

### ISSUE THREAD

**Issue by samuelblowes** [dfinke/ImportExcel#866]
I'm importing a CSV and adding a new column for a formula (it's the same formula for every row). Here's the formula:

`=SUMIFS([FolderSize],[FullName],([@FullName] & "*"),[Destination],[@Destination])`

The entire thing outputs back to a CSV just fine with the formula in tact, however when I export to Excel, the formula shows up as this:
`=SUMIFS([FolderSize],[FullName],(#REF! & "*"),[Destination],#REF!)`

So it appears that a named @reference in the formula is not making it to the spreadsheet, although referencing a named range seems to work fine. 

For context, the CSV is a dump of each folder on a file share with it's full path [FullName] with their respective storage sizes [FolderSize]. The formula sums the size of each folder and any other folder whose [FullName] begins with the same path as the selected row—a poor-man's regex by catting the FullName & "*"—and where the [Destination] cell matches the selected row.

**Comment by samuelblowes** [comment]
I found a workaround: If I change `[@FullName]` to `[[#This Row],[FullName]]`, Excel renders it back to `[@FullName]` in the spreadsheet.

**Comment by dfinke** [comment]
Couple things, if you can, please post the script (both versions if possible). Are you also using `-AutoNameRange`?

For that syntax, wonder if @jhoneill has some insight?

**Comment by ashwinshrinivas** [comment]
@samuelblowes thanks for that workaround - I spent a lot of time trying to debug what I was doing wrong before discovering this. However it still doesn't quite work for me - I'm getting an additional '@'  between the = and the formula name (SUMIFS in your case). Here is my sample code:

```
$ExcelParams = @{
    Path    = 'c:\temp\test.xlsx'
    Show    = $true
}
Remove-Item -Path $ExcelParams.Path -Force -EA Ignore

@('A', 'B') |
ForEach-Object {
    [PSCustOmobject][Ordered]@{
        Category     = 'Alphabets'
        SubCategory  = $_
        FullEPName   = '=CONCAT([[#This Row],[Category]], ": ", [[#This Row],[SubCategory]])'
    }
} |
Export-Excel @ExcelParams -TableName 'TestTable'
```

Output:

```
Category | SubCategory | FullEPName
Alphabets | A | =@CONCAT([@Category], ": ", [@SubCategory])
Alphabets | B | =@CONCAT([@Category], ": ", [@SubCategory])
```

Notice the extra '@' between the = and the CONCAT. Any ideas on what I might be doing wrong?

**Comment by ashwinshrinivas** [comment]
Actually the problem seems specific to the CONCAT function! If I use "SUM", it works fine. In fact if I use the older CONCATENATE, it also works fine! Mysterious indeed - is it possible there is a list of builtins being looked up to determine if function, and if not it is attempting to interpret as a named reference and thus adding an '@'? And perhaps since CONCAT is newer it is not finding in its list?

**Comment by samuelblowes** [comment]
I’m getting the same issue with =MAXIFS(), but not with =SUMIFS(); it’s converting it to =@MAXIFS()

**Comment by mikerosile** [comment]
> I’m getting the same issue with =MAXIFS(), but not with =SUMIFS(); it’s converting it to =@maxifs()

Regarding the use of MAXIFS, try prefixing the function name with "_xlfn.", for example, "_xlfn.MAXIFS".  The MAXIFS function is specific to newer versions of Excel, and Microsoft uses specific prefixes to address newer functions as a way to maintain backwards compatibility with various functions of Excel.

The other prefix that I noticed which Microsoft uses is "_xlws." .. as for which functions require _xlfn or _xlws, I do not have an exhaustive list, and not sure where such a list might be.
