### ISSUE TITLE
How to make a Formula with Set-Format

### ISSUE THREAD

**Issue by Rivalld** [dfinke/ImportExcel#867]
Hello

Im Trying to fill a Cell with a Formula via Set-Format

`Set-Format -Range E6 -Formula {"=COUNTIF(C:C;F6)"} -Worksheet $ws`

Im not sure how to use it.
Is this Syntax correct?

Thanks

**Comment by dfinke** [comment]
`Set-Format -Range E6 -Formula "=COUNTIF(C:C,F2)" -Worksheet $ws`

**Comment by Rivalld** [comment]
Thanks!
The Syntax is correct but when I open the Excel-File it is corrupted.
Thats the Error-Message
"Excel found unreadable content in file error. Do you want to recover the contents of this workbook?"

Here is the Logfile-Error:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error169400_01.xml</logFileName><summary>Error in file 'Path'</summary><removedRecords><removedRecord>Deleted records: Formula of /xl/worksheets/sheet1.xml-Part</removedRecord></removedRecords></recoveryLog>

Do you have any Idea why?

**Comment by Rivalld** [comment]
Thanks alot!
It finally Works :)
