### ISSUE TITLE
Add-ExcelChart / Width Parameter Not Applying

### ISSUE THREAD

**Issue by OralSeth** [dfinke/ImportExcel#868]
When Creating a Worksheet with 2 charts, both of them have the width set to '430'.

Yet, the result is:

- Chart1 Width = 962
- Chart2 Width = 757

The Height Parameter appears to be working fine; not sure why the Width would be having any issues.  My first (and best) guess, is that it's just me.

Anyway - this is all super incredible, and I can't thank you guys enough for what you're doing/have done/may do/etc!

**Comment by dfinke** [comment]
Thanks! Could you post a sample showing  the issue?

**Comment by OralSeth** [comment]
Sure!

Code is:

```powershell
$data = @"
Used,Free
25474.47,2342.39
,
Used,Free
45229.27,6450.264
"@ | ConvertFrom-Csv -NoTypeInformation

$out = "$env:TEMP\test.xlsx"
Remove-Item $out -ErrorAction Ignore

$excel = $data | Export-Excel -Path $out -WorksheetName "Charts" -StartRow 1 -StartColumn 1 -PassThru

$chartParams = @{
  Worksheet       = $excel.Report
  Title           = 'Test Chart 1'
  ChartType       = 'Pie'
  Column          = 0
  Row             = 0
  RowOffSetPixels = 5
  XRange          = "Charts!A1:B1"
  YRange          = "Charts!A2:B2"
  Width           = 430
  Height          = 211
  ShowPercent     = $true
}

$chart = Add-ExcelChart @chartParams -PassThru

$chartParams.Title = 'Test Chart 2'
$chartParams.Column = 4
$chartParams.XRange = "Charts!A4:B4"
$chartParams.YRange = "Charts!A5:B5"

$chart = Add-ExcelChart @chartParams -PassThru

Close-ExcelPackage $excel
```

And the output screenshot is attached

:)

![testCharts](https://user-images.githubusercontent.com/44983168/85044099-ccd27280-b152-11ea-9db9-1b5d6bf0b3fe.png)
