### ISSUE TITLE
Scientific notation in decimal field

### ISSUE THREAD

**Issue by tomvanstraelen** [dfinke/ImportExcel#869]
Hello,

When importing an Excel file containing small numbers, these small numbers are retrieved in scientific notation. And this is causing an error when we try to load this data to a decimal field in our database as the scientific notation can't be converted to a numeric value by SQL Server.
This is with version 7.1.0

There is issue 537 'Convert scientific notation to decimal'
https://github.com/dfinke/ImportExcel/pull/537

It seems that this fix was not integrated, is that correct ?

Thank you for looking into this.
And thank you for creating this module !

**Comment by dfinke** [comment]
That wasn't integrated because there were no unit tests written for it.
