### ISSUE TITLE
Cannot import data from Table - Need example?

### ISSUE THREAD

**Issue by DEberhardt** [dfinke/ImportExcel#871]
Hello,

first of all: Thank you! This looks like a lot of work that will help me save a lot of manual labour. 
I found a few videos on how to Create Excel files, but not how to read from them. I am stumped a bit. So this is less of an issue, more of a documentation issue (happy to write it down to add to the Project btw, once I have tackled it :))

I need to figure out how to do the following:
- I import a Spreadsheet (which we use as an input-form), Open-ExcelPackage - OK :)
`$InputFile = Open-ExcelPackage -Path $File`

- I drill down to the Sheet and Table I want - OK
`$InputFile.$SheetName.Tables[$Table]`

- I have the Tables Address (B30:H35) and number of columns (6) and rows (7)
```
Start   : OfficeOpenXml.ExcelCellAddress
End     : OfficeOpenXml.ExcelCellAddress
Table   : 
Address : B30:H35
IsName  : False
Rows    : 6
Columns : 7
```

I do not know how to now plug that into Import-Excel:
I have the following, but it wants numeric values to know where to start and end.
`Import-Excel -ExcelPackage $InputFile -WorksheetName $SheetName -StartRow 30 -StartColumn 2 -EndRow 36 -EndColumn 9` 

How do I translate B30:H35 into these 4 numeric values
OR
How do I plug the Object (Type: ExcelTable) into the Import-Excel function

I don't seem to be able to produce what I need.
I have found Get-XYRange, but its output is not numeric...

------------------------------
OK. After writing this, taking a break I figured it out
Here is my solution:
```
$XLTable = $InputFile.$SheetName.Tables[$Table]

$SC = $XLTable.Address.Start.Column
$SR = $XLTable.Address.Start.Row

$EC = $XLTable.Address.End.Column
$ER = $XLTable.Address.End.Row

$PSObject = Import-Excel -ExcelPackage $InputFile -WorksheetName $SheetName -StartRow $SR -StartColumn $SC -EndRow $ER -EndColumn $EC
```

I still wonder whether there is an easier way. Whether the Import-Excel can get a Parameter "TableName" that reads the whole table and returns as PSItem for it.

Followup. Could it also get a Parameter "DefinedName" that returns the value of the defined name in the sheet?

**Comment by dfinke** [comment]
There is no parameter on `Import-Excel` for that. The below is in the repo, it will be moved out of the module and setup as an example.

For the `DefinedName`, probably won't extend this to do that. Be great if you worked up an example, please share if you do.

https://github.com/dfinke/ImportExcel/blob/master/GetExcelTable.ps1

**Comment by DEberhardt** [comment]
These examples are great, thank you!
I am wondering if they are part of the Module, but not exposed?

Will share if I find out how to get the defined names out :)

**Comment by dfinke** [comment]
You're welcome. They are part of it, don't depend on it. They are probably going to be moved to the examples folder. They are no unit tests for it. If they get test coverage, they may stay in the module.

**Comment by DEberhardt** [comment]
oh. forgot to action this one. sorry.
Yes, closing is good. Managed to extract what I needed, but haven't managed to document anything worthy of feedback.
