### ISSUE TITLE
TextToColumns Method

### ISSUE THREAD

**Issue by Tuupli** [dfinke/ImportExcel#879]
With the COM Object, it's possible to convert Text to Columns with a delimiter.

For example, i have strings of Text "Matthew | Mark | Luke | John" in Column 11, that i would parse to columns 2,3,4,5 under COM

#This is our source column
$wsRange1=$xlWorkSheet.Columns(11)
#and our target column
$wsRange2=$xlWorkSheet.Columns(2)
$xlOtherChar="|" #Have to use var, otherwise it will delimit on the ", as the 1st character passed

$wsRange1.TextToColumns($wsRange2,1,-4142,'False','False','False','False','False','True',$xlOtherChar)

#Delete the FULL description column, since we no longer need it having converted all data to other columns
$wsRange1.Delete()

Appears that this functionality is NOT available in ImportExcel? 
Method invocation failed because [OfficeOpenXml.ExcelColumn] does not contain a method named 'TextToColumns'.

**Comment by dfinke** [comment]
No, that method is not implemented in the underlying EPPlus library, which is built by other developers.
