### ISSUE TITLE
AutoSize leaves columns a little short

### ISSUE THREAD

**Issue by tkindy** [dfinke/ImportExcel#88]
When I use Export-Excel with the -AutoSize switch, the columns are indeed resized, but they aren't resized properly. They end up being a few pixels short and still cut off the end of the data in those cells.

**Comment by dfinke** [comment]
Thanks for the issue. Yes, unfortunately the autosize is not 100%. It is a limitation because the spreadsheet needs to be launched so Excel can calculate other aspects.

**Comment by tkindy** [comment]
Ah, okay. Thank you for your time. And great work on the module altogether!

**Comment by dfinke** [comment]
Thanks! Hopefully the underlying .NET pieces this depends on may be able to solve that over time.
