### ISSUE TITLE
Exception calling “Save” with “0” argument(s): "Error saving file

### ISSUE THREAD

**Issue by sbirq** [dfinke/ImportExcel#880]
I made a Powershell script which can be used to append data to an Excel file. However, it returns the following error when the file contains formulas:

``` Exception calling "Save" with "0" argument(s): "Error saving file"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.0.1\Public\Export-Excel.ps1:657 char:32
+             else           {   $pkg.Save() }
+                                ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```

The following formulas are used:

```
=VLOOKUP([@Name];CLUMEM;2;FALSE)-[@UsedMemoryGB]
=IF(OR(End<Start;[@[First Response (SLA Metrics)]]<[@[Date/time of creation]]);0;(NETWORKDAYS([@[Date/time of creation]];[@[First Response (SLA Metrics)]];HolidayList)-(NETWORKDAYS([@[Date/time of creation]];[@[Date/time of creation]];HolidayList)*IF(MOD([@[Date/time of creation]];1)>End;1;(MAX(Start;MOD([@[Date/time of creation]];1))-Start)/(End-Start)))-(NETWORKDAYS([@[First Response (SLA Metrics)]];[@[First Response (SLA Metrics)]];HolidayList)*IF(MOD([@[First Response (SLA Metrics)]];1)<Start;1;(End-MIN(End;MOD([@[First Response (SLA Metrics)]];1)))/(End-Start))))*(End-Start)*24)
```

When I delete the columns containing the formulas it works. What can I do to append to the Excel file without removing formulas?

Code:
```
Import-Module ImportExcel
$object = Import-Excel 'C:\Users\Desktop\source.xlsx' -WorksheetName 'Sheet1'
$object | Export-Excel 'C:\Users\Desktop\dest.xlsx' -WorksheetName 'Sheet1' -Append
```

**Comment by dfinke** [comment]
@jhoneill is there a way to re-work the formula `=VLOOKUP([@Name];CLUMEM;2;FALSE)-[@UsedMemoryGB]`? Tried it in a clean workbook, took out the `@` `[]`.

The Dest.xlsx doesn't have named ranges for all the columns, can that cause the problem?

**Comment by sbirq** [comment]
[Source.xlsx](https://github.com/dfinke/ImportExcel/files/4840380/Source.xlsx)
[dest.xlsx](https://github.com/dfinke/ImportExcel/files/4840381/dest.xlsx)

Thanks for your help. Added new files. Apparently the problem is caused by 2 formulas:

> 
> =VLOOKUP([@Name];CLUMEM;2;FALSE)-[@UsedMemoryGB]
> =IF(OR(End<Start;[@[First Response (SLA Metrics)]]<[@[Date/time of creation]]);0;(NETWORKDAYS([@[Date/time of creation]];[@[First Response (SLA Metrics)]];HolidayList)-(NETWORKDAYS([@[Date/time of creation]];[@[Date/time of creation]];HolidayList)*IF(MOD([@[Date/time of creation]];1)>End;1;(MAX(Start;MOD([@[Date/time of creation]];1))-Start)/(End-Start)))-(NETWORKDAYS([@[First Response (SLA Metrics)]];[@[First Response (SLA Metrics)]];HolidayList)*IF(MOD([@[First Response (SLA Metrics)]];1)<Start;1;(End-MIN(End;MOD([@[First Response (SLA Metrics)]];1)))/(End-Start))))*(End-Start)*24)

**Comment by sbirq** [comment]
Thanks for your help guys. Updated my post with the new files (apparently there is another formula causing the problems).

**Comment by Luuk34** [comment]
The problem seems not to be in  a formula. Just trying to export a sheet give same error:

PS D:\TEMP> Import-Module ImportExcel
PS D:\TEMP> Export-Excel 'dest.xlsx'
Exception calling "Save" with "0" argument(s): "Error saving file D:\TEMP\dest.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
+             else           {   $pkg.Save() }
+                                ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

**Comment by sbirq** [comment]
> 
> 
> The problem seems not to be in a formula. Just trying to export a sheet give same error:
> 
> PS D:\TEMP> Import-Module ImportExcel
> PS D:\TEMP> Export-Excel 'dest.xlsx'
> Exception calling "Save" with "0" argument(s): "Error saving file D:\TEMP\dest.xlsx"
> At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
> 
>     * ```
>               else           {   $pkg.Save() }
>       ```
> 
>     * ```
>                                  ~~~~~~~~~~~
>       ```
>       
>       
>       
>       * CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>       * FullyQualifiedErrorId : InvalidOperationException

After deleting column 'S' in 'Changes' and 'K' in Cluster, it worked for me. This deleted both formulas from the Excel file.

**Comment by Luuk34** [comment]
> > The problem seems not to be in a formula. Just trying to export a sheet give same error:
> > PS D:\TEMP> Import-Module ImportExcel
> > PS D:\TEMP> Export-Excel 'dest.xlsx'
> > Exception calling "Save" with "0" argument(s): "Error saving file D:\TEMP\dest.xlsx"
> > At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
> > ```
> > * ```
> >           else           {   $pkg.Save() }
> >   ```
> > 
> > * ```
> >                              ~~~~~~~~~~~
> >   ```
> >   
> >   
> >   
> >   * CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> >   * FullyQualifiedErrorId : InvalidOperationException
> > ```
> 
> After deleting column 'S' in 'Changes' and 'K' in Cluster, it worked for me. This deleted both formulas from the Excel file.
> 
> ```
> Import-Module ImportExcel
> $object = Import-Excel 'C:\Users\user\Desktop\source.xlsx' -WorksheetName 'Cluster'
> $object | Export-Excel 'C:\Users\user\Desktop\dest.xlsx' -WorksheetName 'Cluster' -Append
> ```

When just clearing the formula's from those cell (leaving the columns in place) the error is also not there
PS D:\TEMP> Import-Module ImportExcel
PS D:\TEMP> $object = Import-Excel 'source.xlsx' -WorksheetName 'Cluster'
PS D:\TEMP> $object | Export-Excel 'dest.xlsx' -WorksheetName 'Cluster' -Append -Verbose
VERBOSE: Worksheet 'Cluster' already existed.
VERBOSE: Saved workbook D:\TEMP\dest.xlsx

But when opening dest.xlsx:
an error is shown. When i let EXCEL2013 repair it, it shows this logfile:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error196920_01.xml</logFileName><summary>Errors were detected in file 'D:\TEMP\dest.xlsx'</summary><removedRecords summary="Following is a list of removed records:"><removedRecord>Removed Records: Named range from /xl/workbook.xml part (Workbook)</removedRecord></removedRecords></recoveryLog>

Before running the script EXCEL did not complain about anything.
The reason for EXCEL starting to complain are a result of this script.

**Comment by sbirq** [comment]
> 
> 
> > > The problem seems not to be in a formula. Just trying to export a sheet give same error:
> > > PS D:\TEMP> Import-Module ImportExcel
> > > PS D:\TEMP> Export-Excel 'dest.xlsx'
> > > Exception calling "Save" with "0" argument(s): "Error saving file D:\TEMP\dest.xlsx"
> > > At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
> > > ```
> > > * ```
> > >           else           {   $pkg.Save() }
> > > ```
> > > 
> > > 
> > > 
> > > * ```
> > >                              ~~~~~~~~~~~
> > >   ```
> > >   
> > >   
> > >   
> > >   * CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> > >   * FullyQualifiedErrorId : InvalidOperationException
> > 
> > 
> > After deleting column 'S' in 'Changes' and 'K' in Cluster, it worked for me. This deleted both formulas from the Excel file.
> > ```
> > Import-Module ImportExcel
> > $object = Import-Excel 'C:\Users\user\Desktop\source.xlsx' -WorksheetName 'Cluster'
> > $object | Export-Excel 'C:\Users\user\Desktop\dest.xlsx' -WorksheetName 'Cluster' -Append
> > ```
> 
> When just clearing the formula's from those cell (leaving the columns in place) the error is also not there
> PS D:\TEMP> Import-Module ImportExcel
> PS D:\TEMP> $object = Import-Excel 'source.xlsx' -WorksheetName 'Cluster'
> PS D:\TEMP> $object | Export-Excel 'dest.xlsx' -WorksheetName 'Cluster' -Append -Verbose
> VERBOSE: Worksheet 'Cluster' already existed.
> VERBOSE: Saved workbook D:\TEMP\dest.xlsx
> 
> But when opening dest.xlsx:
> an error is shown. When i let EXCEL2013 repair it, it shows this logfile:
> 
> error196920_01.xml
> Errors were detected in file 'D:\TEMP\dest.xlsx'
> Removed Records: Named range from /xl/workbook.xml part (Workbook)
> 
> Before running the script EXCEL did not complain about anything.
> The reason for EXCEL starting to complain are a result of this script.

I know this error pops up after appending but this has nothing to do with the exception right? I can simply let Excel repair the document and ignore the error. The exception is caused by the formulas..

**Comment by sbirq** [comment]
Removed the bad records: 

[dest.xlsx](https://github.com/dfinke/ImportExcel/files/4840887/dest.xlsx)
