### ISSUE TITLE
Using -ClearSheet gives unhandled exception

### ISSUE THREAD

**Issue by Ef-Di** [dfinke/ImportExcel#882]
When using Export-Excel with -ClearSheet, I get an unhandled exception.

`Export-Excel -NumberFormat 'Text' -StartRow $(($existornot).count+1) -NoHeader -NoNumberConversion * -ClearSheet 
-WorksheetName "$(if((Get-Date).ToString('dddd') -eq 'Monday')
{"Compared to $((Get-Date).AddDays(-3).ToString('MM_dd_yyyy'))"}
else{"Compared to $((Get-Date).AddDays(-1).ToString('MM_dd_yyyy'))"})" -path $exexportpath`

This gives the output "Unhandled Exception: Cannot print exception string because Exception.ToString() failed."

Shortly after this the powershell window closes. 

It doesn't seem to happen if the worksheet name is a regular string.

**Comment by dfinke** [comment]
To make this more workable/debuggable, please set the parameters to variables and then pass those to the parameters on `Import-Excel`

**Comment by Ef-Di** [comment]
> To make this more workable/debuggable, please set the parameters to variables and then pass those to the parameters on `Import-Excel`

OK, I did that, and I no longer get the unhandled exception, but now somehow my conditional formatting broke and the sheet is still not being cleared when I run the export a second time.

`$comparesheet = $(if((Get-Date).ToString('dddd') -eq 'Monday'){"Compared to $((Get-Date).AddDays(-3).ToString('MM_dd_yyyy'))"}else{"Compared to $((Get-Date).AddDays(-1).ToString('MM_dd_yyyy'))"})

...

Export-Excel -NumberFormat 'Text' -StartRow $(($existornot).count+1) -NoHeader -NoNumberConversion * -ClearSheet -WorksheetName "$comparesheet" -path $exexportpath -ConditionalText $(New-ConditionalText -ConditionalType ContainsText "text 1" -BackgroundColor LightBlue), $(New-ConditionalText -ConditionalType ContainsText "text 2" -BackgroundColor LightPink), $(New-ConditionalText -ConditionalType ContainsText "text 3" -BackgroundColor LightGreen)`

The error I get for the conditional formatting is "Error applying conditional formatting to worksheet Cannot bind argument to parameter 'Address' because it is null."

I also want to add that the original command works just fine without the -ClearSheet, and with the conditional formatting.
