### ISSUE TITLE
Export-Excel creates corrupt Excel file for strings longer than 255 characters

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#883]
Thank you for continuing the work on this amazing module. We use it almost every day and it makes our managers happy. Now on to the issue. When trying to export strings longer than 255 characters a corrupt Excel file is generated. More info on [StackOverflow](https://stackoverflow.com/questions/28197219/exceptionthe-total-length-of-a-datavalidation-list-cannot-exceed-255-characters).

### Reproduction steps

1. Execute the code: below
```powershell
$ExcelParams = @{
    Path         = 'c:\Test\corruptFile.xlsx'
    AutoSize     = $true
    FreezeTopRow = $true
}

's' * 255 | Export-Excel @ExcelParams -WorksheetName Errors -TableName Errors # success
's' * 256 | Export-Excel @ExcelParams -WorksheetName Errors -TableName Errors # failure
```
2. Open the file and notice Excel prompting that the file is corrupt
![image](https://user-images.githubusercontent.com/10828570/86108201-29bf1880-bac3-11ea-99e2-a1a92dc6511a.png)

3. When saying yes, Excel complains that the file is in use:
![image](https://user-images.githubusercontent.com/10828570/86108286-422f3300-bac3-11ea-84f9-8c3f45b684bc.png)

It appears that longer strings are generating a corrupt Excel file when using `Export-Excel`. However, when manually updating the Excel cell to a long string by hand, the file does not get corrupted. It seems like EPPLUS or the module is not handling this correctly. 

Thank you for having a look at this.

**Comment by Luuk34** [comment]
I think it's only for Column names which are longer than 255 characters?   This means that long string in a 'normal' cell are working ok

I have tested this by addding "<S>TEST</S>" to the xml, and then running the script, and indeed the error is gone!

**Comment by DarkLite1** [comment]
Nice catch! I tested it with `-NoHeader` but this doesn't fix the issue. Probably because it's in a table form.

**Comment by DarkLite1** [comment]
@dfinke I don't think this should be closed. An improvement in the code is required I believe.

**Comment by dfinke** [comment]
PRs are welcome
