### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by baha00** [dfinke/ImportExcel#887]
I hate asking this type of questions but is there any guide how to? 

I just want convert Xlsl to Csv... thats all with ConvertFrom-ExcelSheet

**Comment by uSlackr** [comment]
In general, the example are the guide.  Best play with it a bit to understand how it works.  Converting XLSX to csv could be as easy as `import-excel filename | export-csv -notypeinformation filename2`.  This assumes there is a single sheet and the top row is the header row.
