### ISSUE TITLE
Blank cells

### ISSUE THREAD

**Issue by alonax** [dfinke/ImportExcel#888]
Following some PowerShell manipulations I got to a state where I have an object containing the row data which I would like to export to excel and analyse using Pivot Table.
The old fashion way is to use Export-CSV and then creating the Pivot Table.
Using Export-Excel I was hoping to automate the procedure. However, it seems that Export-Excel treats blank values as none blank values and thus, being counted in the Pivot Table (this is not the case when exporting the data using Export-CSV).

Any idea, what should be done in order to count only none empty / blank cells?

**Comment by dfinke** [comment]
Please, could you post the data, script and resulting xlsx.
