### ISSUE TITLE
Find last filled row number of a column in a worksheet

### ISSUE THREAD

**Issue by robliv** [dfinke/ImportExcel#889]
Hi, I'm trying to set up a dashboard in a worksheet that has multiple Pivot tables. The data they display will be changing and so the Pivot table size in rows will be changing and I need to define where to place the next pivot table without it overwriting data in the previous cells. Is there a way to find the last filled row number of a column or the cell where a pivot table ends? Thanks!

**Comment by dfinke** [comment]
Looks like the `Dimension` property on the Pivot Table sheet does not get populated. There may be a property on the pivot table itself.

![image](https://user-images.githubusercontent.com/67258/86533744-4d0e0d00-bea1-11ea-907c-dff7ed1763c3.png)

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
East,screws,55
East,avocado,57
North,pear,29
North,lime,71
West,avocado,25
South,melon,100
East,peach,61
East,pear,67
North,orange,1
North,screwdriver,76
"@


$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru -PivotData @{TotalSold='sum'} -PivotRows Region -Activate

Close-ExcelPackage $xl -Show
```
