### ISSUE TITLE
Exception calling “Save” with “0” argument(s): "Error saving file

### ISSUE THREAD

**Issue by dlek10** [dfinke/ImportExcel#890]
Just trying to get any data to export results in an error. I have tried different destination paths, different data sets, different methods and they all fail with the same error. This is the first time I have tried using this module so I can't say if prior versions worked. Here is sample code that fails:

$path = "E:\Output.xlsx"
$sheet1 = ConvertFrom-Csv @"
Region,Item,TotalSold
West,melon,27
"@
$sheet1 | Export-Excel $path -WorksheetName Sheet1

Exception calling "Save" with "0" argument(s): "Error saving file E:\Output.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
+             else           {   $pkg.Save() }
+                                ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

I have also tried to debug with ISE but couldn't find anything useful. 

PS Version
-------
5.1.14393.3471

**Comment by dfinke** [comment]
### Does this work?

```powershell
$sheet1 = ConvertFrom-Csv @"
Region,Item,TotalSold
West,melon,27
"@

$sheet1 | Export-Excel 
```

**Comment by dlek10** [comment]
WOW, Thanks for the quick reply! This is what I get when I run that:

WARNING: Failed autosizing columns of worksheet 'Sheet1': Exception calling "AutoFitColumns" with "0" argument(s):
"Object reference not set to an instance of an object."
Exception calling "Save" with "0" argument(s): "Error saving file
C:\Users\sv-sp16_farm\AppData\Local\Temp\tmpE9A2.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
+             else           {   $pkg.Save() }
+                                ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

Invoke-Item : Cannot find path 'C:\Users\sv-account\AppData\Local\Temp\tmpE9A2.xlsx' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:694 char:26
+             if ($Show) { Invoke-Item $Path }
+                          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\sv-acc...mp\tmpE9A2.xlsx:String) [Invoke-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.InvokeItemCommand

**Comment by dlek10** [comment]
Some additional info: 
I am attempting to run this on a Windows 2016 Standard server that does not have Excel installed. I have tried running this using an account with full access permissions and in both regular and elevated mode. Same error each time.

I was, however, able to successfully run the same snippet on a Windows 10 machine (with Excel installed) running PowerShell 5.1.18362.752 without any issues using the same 7.1.0 module.

**Comment by dfinke** [comment]
Excel only needs to be installed if you use the `-Show` switch. `Export-Excel` with no param has `-Show` as the default. I have not tried to run it on Win 2016. Permissions is my best guess. Is `$path = "E:\Output.xlsx"` a network drive? If so, try outputting to a local drive on that server.

**Comment by dlek10** [comment]
I have tried saving to multiple different local drives and locations with the same outcome. The account that I am using is a privileged account that I know has access to the destination locations but it is possible it is being blocked somewhere else. I am not sure what processes are being used in the module (particularly the .Save() method in Export-Excel.ps1) or where to check for permission issues but I'll keep digging. Thanks again for the help and the quick replies. Really appreciate it!

**Comment by dlek10** [comment]
In case it helps, here is more detailed error output when running this commmand:

$path = "C:\scripts\Output.xlsx"

$sheet1 = ConvertFrom-Csv @"
Region,Item,TotalSold
West,melon,27
"@

$sheet1 | Export-Excel $path -WorksheetName Sheet1
 
Exception calling "Save" with "0" argument(s): "Error saving file C:\scripts\Output.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 char:32
+             else           {   $pkg.Save() }
+                                ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException



PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "Save" with "0" 
                        argument(s): "Error saving file C:\scripts\Output.xlsx" ---> System.InvalidOperationException: 
                        Error saving file C:\scripts\Output.xlsx ---> System.NullReferenceException: Object reference 
                        not set to an instance of an object.
                           at 
                        OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingCollection..ctor(ExcelWorksheet 
                        worksheet)
                           at OfficeOpenXml.ExcelWorksheet.get_ConditionalFormatting()
                           at OfficeOpenXml.ExcelStyles.UpdateXml()
                           at OfficeOpenXml.ExcelWorkbook.Save()
                           at OfficeOpenXml.ExcelPackage.Save()
                           --- End of inner exception stack trace ---
                           at OfficeOpenXml.ExcelPackage.Save()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at 
                        System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception 
                        exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Export-Excel<End>, C:\Program 
                        Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1: line 672
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

MyCommand             : 
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 672
OffsetInLine          : 32
HistoryId             : -1
ScriptName            : C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1
Line                  :             else           {   $pkg.Save() }
                        
PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1:672 
                        char:32
                        +             else           {   $pkg.Save() }
                        +                                ~~~~~~~~~~~
PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public
PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Export-Excel.ps1
InvocationName        : 
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 

00000000000000000000000000000000000000000000000000000000000000000000000000000000

ErrorRecord                 : Exception calling "Save" with "0" argument(s): "Error saving file C:\scripts\Output.xlsx"
WasThrownFromThrowStatement : False
Message                     : Exception calling "Save" with "0" argument(s): "Error saving file C:\scripts\Output.xlsx"
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.InvalidOperationException: Error saving file C:\scripts\Output.xlsx ---> 
                              System.NullReferenceException: Object reference not set to an instance of an object.
                                 at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingCollection..ctor(Exce
                              lWorksheet worksheet)
                                 at OfficeOpenXml.ExcelWorksheet.get_ConditionalFormatting()
                                 at OfficeOpenXml.ExcelStyles.UpdateXml()
                                 at OfficeOpenXml.ExcelWorkbook.Save()
                                 at OfficeOpenXml.ExcelPackage.Save()
                                 --- End of inner exception stack trace ---
                                 at OfficeOpenXml.ExcelPackage.Save()
                                 at CallSite.Target(Closure , CallSite , Object )
TargetSite                  : Void ConvertToMethodInvocationException(System.Exception, System.Type, System.String, 
                              Int32, System.Reflection.MemberInfo)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationExceptio
                              n(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo 
                              memberInfo)
                                 at CallSite.Target(Closure , CallSite , Object )
                                 at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame 
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087

11111111111111111111111111111111111111111111111111111111111111111111111111111111

Message        : Error saving file C:\scripts\Output.xlsx
Data           : {}
InnerException : System.NullReferenceException: Object reference not set to an instance of an object.
                    at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingCollection..ctor(ExcelWorksheet 
                 worksheet)
                    at OfficeOpenXml.ExcelWorksheet.get_ConditionalFormatting()
                    at OfficeOpenXml.ExcelStyles.UpdateXml()
                    at OfficeOpenXml.ExcelWorkbook.Save()
                    at OfficeOpenXml.ExcelPackage.Save()
TargetSite     : Void Save()
StackTrace     :    at OfficeOpenXml.ExcelPackage.Save()
                    at CallSite.Target(Closure , CallSite , Object )
HelpLink       : 
Source         : EPPlus
HResult        : -2146233079

22222222222222222222222222222222222222222222222222222222222222222222222222222222

Message        : Object reference not set to an instance of an object.
Data           : {}
InnerException : 
TargetSite     : Void .ctor(OfficeOpenXml.ExcelWorksheet)
StackTrace     :    at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingCollection..ctor(ExcelWorksheet 
                 worksheet)
                    at OfficeOpenXml.ExcelWorksheet.get_ConditionalFormatting()
                    at OfficeOpenXml.ExcelStyles.UpdateXml()
                    at OfficeOpenXml.ExcelWorkbook.Save()
                    at OfficeOpenXml.ExcelPackage.Save()
HelpLink       : 
Source         : EPPlus
HResult        : -2147467261
