### ISSUE TITLE
Adding Hyperlinks

### ISSUE THREAD

**Issue by gbargsley** [dfinke/ImportExcel#892]
I am trying to figure out how to add links from the Window Group rows on this example to point to a different worksheet.  I have tried to follow the example that uses the import-csv of a file, but I am gathering my data differently and having trouble translating the code to work with my example.

So for instance I would like to take the two rows and make the Group Name a hyperlink that goes to an ADAccount worksheet where the users in the group are listed.

![image](https://user-images.githubusercontent.com/169602/87806812-0b744f00-c81d-11ea-9c0a-9e179ee3d29a.png)

**Comment by dfinke** [comment]
@gbargsley please could you post a mock up of an xlsx of what you'd like the end result to look like etc. Including the hyper links that link to the other sheets.

**Comment by gbargsley** [comment]
Here is a sample of what I am trying to accomplish.  I generate this report with PowerShell and would like the ability to add the hyperlink to any GranteeType of Windows_Group will take you to the ADAccounts worksheet and highlight the rows with the matching ParentADLogin.
[Copy of userpermissions.xlsx](https://github.com/dfinke/ImportExcel/files/4941528/Copy.of.userpermissions.xlsx)

**Comment by dfinke** [comment]
Check out https://github.com/dfinke/ImportExcel/blob/master/Examples/HyperLinks/Races.ps1

**Comment by gbargsley** [comment]
That is the example I was going from. But since I am loading the excel from a variable that is loaded from running a function I am not sure how to build the range and the hyperlink command.

**Comment by MikeyBronowski** [comment]
#983 adding a link to this in case someone else needs it
