### ISSUE TITLE
Getting Pivot Table generated data without launching xlsx in Excel

### ISSUE THREAD

**Issue by nbhms** [dfinke/ImportExcel#893]
As the title says, is it possible with importexcel to get the data that would be generated by a pivot table without opening the .xlsx file in Excel and having Excel generate the data?  

I receive an Excel file with a pivot table in it, where the sender is auto-generating the Excel file and pivot table - so the data that I need that is generated by the pivot table is not there until the Excel file has been opened in Excel at least once and then saved.  I can then access the file via importexcel in powershell and get/manipulate the data.  I can accomplish that with the "New-Object -comobject Excel.Application" and launch the file, and then do a save, close, quit via PowerShell on a machine with Excel installed, but I'd prefer to do it all with importexcel so the script can be run on machines without Excel installed.

I tried opening the file via open-excelpackage and then closing it with close-excelpackage and "-calculate", but that doesn't do it.

Is there a way to generate that data via importexcel or does something like that require Excel?

**Comment by dfinke** [comment]
The only way to do that is as you did, `New-Object -ComObject`.
