### ISSUE TITLE
Don't know how make a chart with 2 'X' values

### ISSUE THREAD

**Issue by ChrisCrager** [dfinke/ImportExcel#894]
Hello,

I am trying to make a clustered bar graph with 2 X values. It could be a Pivot or a regular bar chart, that doesn't matter. But I am having issues getting anything to work. When I try a Pivot table, it gets the data, but doesn't put them in the right places and a bar chart does not see the data at all. The X values are percentages that I've calculated from the data and the Y is time in Months

Here is what I want it to look like from a sheet I created manually:
![image](https://user-images.githubusercontent.com/68599690/88062805-e9394480-cb2e-11ea-9b7f-68be2bdb154e.png)

Here is the sheet I created with Import-Excel. I need to get the data from Column H-J Row 1-5.
![image](https://user-images.githubusercontent.com/68599690/88063483-b04d9f80-cb2f-11ea-9f7a-a19f7ed19ca7.png)

If I were to make a Pivot Table manually with that data, I would want it to look like this:
![image](https://user-images.githubusercontent.com/68599690/88063842-1df9cb80-cb30-11ea-952a-2807985de109.png)

Columns A-C I created with seperate Export-Excel functions. The rest of it I have in a single function with passthru. I am fairly new to this module and I've tried many many variations and attempts to get this to work. Any help would be greatly appreciated.

**Comment by ChrisCrager** [comment]
Also my main problem with the Pivot table is Legend Series(Column) to contain "Values" like in the previous picture.

**Comment by dfinke** [comment]
@ChrisCrager could you post the data and script you are using. Not sure this can be fully achieved with the module.

**Comment by ChrisCrager** [comment]
@dfinke Thank you for looking at this. I've actually got some of this figured out.
This is the script I have now:
          `
$pkg = "" | Export-Excel $xPath -AutoSize -PassThru
$ws = $pkg.Workbook.Worksheets["Windows_Machines"]
$dimR = $ws.Dimension.Rows
Set-ExcelRange -Range $ws.Cells["I2:J$($dimR)"] -NumberFormat "0.00%"
$ws.Cells["D1"].Value = "DS11"
$ws.Cells["E1"].Value = "DS22"
$ws.Cells["F1"].Value = "Totals"
$ws.Cells["F2"].Value = "PCs"
$ws.Cells["F3"].Value = "DS1"
$ws.Cells["F4"].Value = "DS2"
$ws.Cells["I1"].Value = "DS2"
$ws.Cells["J1"].Value = "DS1"
$ws.Cells["H1"].Value = "Months"
$ws.cells["G2"].Formula = "=COUNTA(A:A)-1"
$ws.cells["G3"].Formula = "=COUNTIF(D:D,`"Yes`")"
$ws.cells["G4"].Formula = "=COUNTIF(E:E,`"Yes`")"
2..($dimR)|
    ForEach-Object {
        $ws.Cells["D$_"].Formula = "=if(isna(VLOOKUP(A$($_),DS1_Computers!A:A,1,0)),`"No`",`"Yes`")"
        $ws.Cells["E$_"].Formula = "=if(isna(VLOOKUP(A$($_),DS2!A:A,1,0)),`"No`",`"Yes`")"
        }
3..($month) |
    ForEach-Object {
        $mName = (Get-Culture).DateTimeFormat.GetMonthName($_)
        $ws.Cells["H$($_ - 1)"].Value = $mName
        $ws.Cells["I$($_ - 1)"].Value = $MonthNumbers.$($mName).DS2
        $ws.Cells["J$($_ -1)"].Value = $MonthNumbers.$($mName).DS1
        }
2..5 |
    ForEach-Object{
        $ws.Cells["L$_"].Formula = "=countif(C:C,K$_)"
        }
$ws.cells.AutoFitColumns()
Add-PivotTable -ExcelPackage $pkg -SourceRange $pkg.Windows_Machines.Cells["H1:J5"] `
  ` -PivotTableName "DSGraph" -SourceWorksheet $ws -PivotRows "Months"  -PivotData @{'DS2' = 'Sum'; 'DS1' = 'Sum'} `
    -PivotDataToColumn -Activate -PivotChartDefinition @{ 
    Title="DS";
    ChartType = "BarClustered"
    Column=11; Width = 500; Height = 360;
    YMajorUnit=.2; YMinorUnit=.1; YAxisNumberFormat="0.00%"; YMax=1
    LegendPosition = "Bottom"
    }

Close-ExcelPackage $pkg -Show` 

That gets me this worksheet:
![image](https://user-images.githubusercontent.com/68599690/88585975-6aa24280-d019-11ea-8ef2-382c4acc5caf.png)

And this graph on a different sheet:
![image](https://user-images.githubusercontent.com/68599690/88586110-99201d80-d019-11ea-9d6f-0d2ad1c82d79.png)

Which is essentially how I want the graph to look. I would only want to change the style of the graph and the bar colors if possible.

Which I guess is my only real question now, is if you can change the bar color or chart style. Is there a way to see all of the available options in "-PivotChartDefinition"? I've mainly been guessing and getting lucky a couple of times. 

While I was writing this and trying to get an expample, I fixed the other problem I was having so this is pretty much it. I still need to work on optimizing.

**Comment by dfinke** [comment]
For `-PivotChartDefinition`, you should be able to checkout the `New-PivotTableDefinition` and add the params to the hashtable. 

![image](https://user-images.githubusercontent.com/67258/88595957-10fa4200-d032-11ea-9437-40d0ec729d67.png)

## Also

Off the top of my head. Setting up most of the data like this, and then exporting it. Including the "most" formulas, maybe. 

This example shows the `-PassThru`, and you can then do the `Set-ExcelRange` formatting etc.

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
West,peach,88
South,avocado,29
South,saw,17
East,drill,23
West,hammer,58
North,hammer,55
South,pear,34
East,pear,94
East,screws,26
North,avocado,19
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru

Close-ExcelPackage $xl -Show
```

**Comment by ChrisCrager** [comment]
But even that list doesn't show whats possible. "YMajorUnit" for example. I got that off of your other examples but got "YMax" by guessing and trying things. Is there a way to see EVERYTHING that is possible for the definition? Is that defined in your module or in excel itself?

**Comment by dfinke** [comment]
Check out too. 

![image](https://user-images.githubusercontent.com/67258/88598446-4c4b3f80-d037-11ea-8ac1-23f4607315c1.png)

**Comment by ChrisCrager** [comment]
Ah, thank you. So it looks like there isn't a way to change the chart style or column color then. That is alright, I don't mind doing that manually, this has still been a big help!

**Comment by dfinke** [comment]
Yeah, there are challenges with some components, rendering at runtime etc.  Thanks for the questions.
