### ISSUE TITLE
How to determine the row and cell of a value?

### ISSUE THREAD

**Issue by kap260** [dfinke/ImportExcel#895]
I am using Import-Excel to grab all the information in an XLSX file.  Next, I use a ForEach to iterate through the created table.

$tbl_ListOfDrw_PCS = Import-Excel -Path ($PW_PCS_CheckedOutFile.CheckedOutLocalFileName) -WorksheetName $XLS_PCS_Sheet.Name -StartRow 8

#ITERATE THROUGH THE LIST OF DRAWING ON THE SHEET IN THE PCS SPREADSHEET
forEach ($PCS_Sheet_DGN in $tbl_ListOfDrw_PCS)
{
}

How do I determine the row and cell number for a value in the row?

thanks!
Kirk Peterson

**Comment by dfinke** [comment]
You could use the `for` loop. `$row` is the row in the sheet, you need to handle the offset for the StartRow and PowerShell arrays start at zerp.

```powershell
for ($row = 0; $i -lt $tbl_ListOfDrw_PCS.Count; $i++) {
}
```

The property names on the object need to be "counted" and to get the correct index number.

Then you need to use something like $wb.worksheets["sheet1"].Cells[$row, $colindex] if you want update the data in the worksheet. There is nothing out of the box that makes that simpler.
