### ISSUE TITLE
Exception calling “Save” with “0” argument(s): "Error saving file

### ISSUE THREAD

**Issue by chazlander** [dfinke/ImportExcel#898]
When adding a worksheet to another excel package, I'm unable to save it.

Line 43 is the one in question.
![Code](https://imgur.com/Hsnloxh.png)

The error executing Line 45
![Error](https://imgur.com/ZrHhld3.png)

If I comment out the Add-Worksheet command, saves just fine, but I need to clone that sheet.

**Comment by dfinke** [comment]
Please post a a script that repros the issue.
