### ISSUE TITLE
Display Iconsets based on text (Set Custom Number formatting)

### ISSUE THREAD

**Issue by ntorrey** [dfinke/ImportExcel#899]
Thank you! Is there any way to set up custom number formatting so I can display iconsets based on text rather than numbers? 
(ex. Set the word "Done" = 1, "Working" = 0, "Not Done" = -1)
This way I could get cells that look like:
&check; &nbsp;&nbsp;Done
&nbsp;!&nbsp;&nbsp;&nbsp;Working
&nbsp;X&nbsp;&nbsp;Not Done

An example of what I want to do is here: http://www.bradedgar.com/excel-custom-number-formatting-conditionally-format-text-fields-icon-sets-using-number-formatting/

**Comment by dfinke** [comment]
Not that I know of off the top of my head. I don't believe so. The library used to create the xlsx is EPPlus. I don't know if is supports this feature.
