### ISSUE TITLE
Set a column to a certain type (number, text, date, etc)?

### ISSUE THREAD

**Issue by riahc3** [dfinke/ImportExcel#901]
Hello

When using Export-Excel, Im getting a issue where one of the columns are getting inserted as numbers and Excel displays them incorrectly.

I was wondering if there is a way to force set column A as text, column B as number, etc.

Thank you

**Comment by dfinke** [comment]
Give this a try.

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold,Price
West,avocado,16,3.2
North,screws,33,43.1
East,screws,76,2
West,avocado,24,6
West,peach,27,1.12
South,saw,6,3.8721
North,pear,73,10
East,kiwi,57,11
North,lime,95,19
East,hammer,21,5
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -AutoSize -PassThru

Set-Format -Worksheet $xl.Sheet1 -Range "C:C" -NumberFormat 'Text'
Set-Format -Worksheet $xl.Sheet1 -Range "D:D" -NumberFormat 'Currency'

Close-ExcelPackage $xl -Show
```

**Comment by riahc3** [comment]
> ```powershell
> Set-Format -Worksheet $xl.Sheet1 -Range "C:C" -NumberFormat 'Text'
> Set-Format -Worksheet $xl.Sheet1 -Range "D:D" -NumberFormat 'Currency'
> ```

Thanks. I think it sort of worked but there is 74,76,8,9.......Like it only sorts them by the first digit.

That might be a Excel thing....I dont know.

**Comment by riahc3** [comment]
The thing is that excel still complains about the column needs to be a number but if i right click on it....its a number.

Seems like a weird bug.

**Comment by john-gawrysiak** [comment]
I'm having a similar issue where text that can be interpreted as scientific notation is stored as number format in Excel.
Using the above example code and inserting the following values in column C, I get the following results:

00e14 -> 0
123e4 -> 1230000
12e34 -> 1.2E+35

I discovered this issue and tried to use the NumberFormat 'Text' parameter with Export-Excel command with no luck. In Excel, the column format is Text, so it seems like the data is being treated as a number during the export. Tried to append data to the existing worksheet with Column C formatted as Text, and the results are the same.

For the moment, I am adding a non-numeric char to the string and it is treated as text, but dealing with the extra char in downstream scripts and reports is quickly becoming unmanageable.

Great work on this module, btw. Hope this issue can be resolved, but my guess is that Excel is the problem...

**Comment by dfinke** [comment]
@john-gawrysiak thanks, can you post a small repro script and data. Maybe it can fixed.

**Comment by john-gawrysiak** [comment]
@dfinke I created a script that reproduces the issue. When viewing in Excel all of the cells show as Text-formatted, yet it treated the data as numbers and reformatted it. Thanks for taking a look at this. I just stumbled upon this issue today, so not urgent.

``$Data = @(
    [PSCustomObject]@{
        Name = 'Test1'
        Actual = '0123e'
    } | Add-Member -MemberType ScriptProperty -Name 'Intended' -Value { "Should be $($this.Actual)" } -PassThru
    ,[PSCustomObject]@{
        Name = 'Test2'
        Actual = '00e12'
    } | Add-Member -MemberType ScriptProperty -Name 'Intended' -Value { "Should be $($this.Actual)" } -PassThru
    ,[PSCustomObject]@{
        Name = 'Test3'
        Actual = '12e34'
    } | Add-Member -MemberType ScriptProperty -Name 'Intended' -Value { "Should be $($this.Actual)" } -PassThru
    ,[PSCustomObject]@{
        Name = 'Test4'
        Actual = '12345'
    } | Add-Member -MemberType ScriptProperty -Name 'Intended' -Value { "Should be $($this.Actual)" } -PassThru
)

$Data

$ExcelParams = @{
    Path         = "$env:TEMP\test.xlsx"
    Show         = $true
    Numberformat = 'Text'
    ClearSheet   = $true
    AutoSize     = $true
}

$Data | Export-Excel @ExcelParams

**Comment by dfinke** [comment]
Glad you found the `-NoNumberConversion` parameter, was going to try you repro and see if that fixed it.
