### ISSUE TITLE
not working in powershell schedueled tasks?

### ISSUE THREAD

**Issue by filipheens** [dfinke/ImportExcel#902]
Hi, I made a script where I use the ConvertTo-ExcelXlsx part.
It runs perfect when logged in, but when I run it as a schedueled task I'm getting an error.
PS>TerminatingError(ConvertTo-ExcelXlsx): "Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))"
how can I troubleshoot what is wrong?

**Comment by dfinke** [comment]
That was contributed by someone in the community. It needs to launch Excel in the background in order to work. No sure you can do that from a task or it may be permissions.

**Comment by filipheens** [comment]
Hi Dfinke, 
tnx for the prompt answer, 
It helped met a lot...

I don't know if my answer is also seen by others (1st time on github ;-))
But this solved my problem.
https://superuser.com/questions/579900/why-cant-excel-open-a-file-when-run-from-task-scheduler
and more exactly this


It's likely a DCOM permissions issue. Automating Excel is sometimes fraught with peril...

The only way I've found around issues such as this is to set Excel to run as a specific user through DCOM permissions.

    Open Component Services (Start -> Run, type in dcomcnfg)
    Drill down to Component Services -> Computers -> My Computer and click on DCOM Config
    Right-click on Microsoft Excel Application and choose Properties
    In the Identity tab select This User and enter the ID and password of an interactive user account (domain or local) and click Ok

Keeping it as the interactive user or the launching doesn't work with the task scheduler unfortunately, even when setting the task up to run under an account that has admin access to the machine.

**Comment by dfinke** [comment]
Thanks for following that up and posting the solution.
