### ISSUE TITLE
Question. Background Color, color doesn't seem to be available, can the Color Index be used?

### ISSUE THREAD

**Issue by get-name24** [dfinke/ImportExcel#905]
HI All

I've been working with someone to create an excel file for a monthly report.  When it was first created it was created using the old Com objects and needed to be run manually.  We are trying to update the script to use Export-Excel to create the report and ran into a minor issue that I"m stuck on.

The problem is related to the background colors.  I have found how to use the Conditional Text setting and I'm able to get some colors working, but others don't seem to work.  An example is trying to use "light orange" as the background color.  Light Orange doesn't seem to be available but i found that  Dark Orange and Orange work.  

Since i know the Color Index numbers, is there a way to use those instead of using the name? Or maybe the RGB number? Is there a different way I can set the background color that I have overlooked?  

if you look at the link below, I know i need color 40 and 45 but just can't seem to find a matching color with conditional formatting.  
https://www.pk-anexcelexpert.com/wp-content/uploads/VBATutorial/VBA-36.jpg

any suggestions and assistance is greatly appreciated.  

Thanks
Greg

**Comment by dfinke** [comment]
### Try FromArgb

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
South,saw,100
West,screws,100
West,peach,98
South,pear,26
West,hammer,75
East,melon,74
North,kiwi,48
East,orange,26
South,peach,48
West,banana,48
"@

$ct = New-ConditionalText -Text South -BackgroundColor ([System.Drawing.Color]::FromArgb(217,217,217)) -ForeGroundColor Green

Export-Excel -InputObject $data -Path $xlfile -Show -ConditionalText $ct
```

![image](https://user-images.githubusercontent.com/67258/90657826-d8085400-e210-11ea-92c1-a835a91c8dea.png)

**Comment by get-name24** [comment]
That works exactly like i need it too.  Thanks for the help and quick response.  

Greg
