### ISSUE TITLE
Exporting extra columns for Invoke-SqlCmd

### ISSUE THREAD

**Issue by RavKing** [dfinke/ImportExcel#907]
I'm using Invoke-SqlCmd using PowerShell. In the object shows selected column but when i'm exporting using Export-Excel i'm seeing following 5 extract column in output. I saw the response for someone reported using -ExcludeProperty as workaround. Just want to check is that is fixed or not? I'm using as a common method which calls this logic of Export-Excel, Lot other methods some of them are SQL queries some of them are objects to export. I'm using ImportExcel 7.0.0. 

- ItemArray, RowError, RowState, Table, HasErrors

Please let me know is this is resolved or i have user workaround by using -ExcludeProperty ItemArray, RowError, RowState, Table, HasErrors. Is there any issues for other type of objects calling same method?

**Comment by dfinke** [comment]
You'll need to use `-ExcludeProperty` when you don't want data to be exported to Excel.
