### ISSUE TITLE
Cannot save excel file

### ISSUE THREAD

**Issue by feardamhan** [dfinke/ImportExcel#912]
Simple process of the following errors out for me:

$sourceWorkbook = Open-ExcelPackage -Path .\test-input.xlsx
 Close-ExcelPackage $sourceWorkbook -SaveAs newfile.xlsx

Exception calling "SaveAs" with "1" argument(s): "Error saving file F:\Scripts\newfile.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Close-ExcelPackage.ps1:23 char:29
+             else           {$ExcelPackage.SaveAs( $SaveAs)}
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

**Comment by dfinke** [comment]
## This seems to works

```
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
North,saw,44
West,drill,5
South,avocado,24
West,kiwi,64
East,orange,63
North,screws,50
East,avocado,2
West,orange,87
North,drill,21
South,drill,49
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru

Close-ExcelPackage $xl


$newxlfile = "$env:TEMP\testX.xlsx"

$sourceWorkbook = Open-ExcelPackage -Path $xlfile
Close-ExcelPackage $sourceWorkbook -SaveAs $newxlfile
```

**Comment by feardamhan** [comment]
I'll try your exact steps and revert back with findings. 

Ultimately what I want to do is open an existing file (not created via powershell) read values from named cells, open a different spreadsheet (newer version of same excel sheet) and write those values into the corresponding cells of the new file and save. 

It's to avoid transcribing 1000+ values between old and new versions of the same files. 

I have most of it done ie reading the old file to excelpackage, reading new file to different excelpackage, grabbing values from first excelpackage and inserting them to the second excelpackage. Currently failing on the last step to save the updates new file. But as shown on OP my save was failing with even a basic open and resave.

**Comment by feardamhan** [comment]
Ok, so your sample code works, but this doesnt. Ideas?

PS F:\Scripts> $sourceWorkbook = Open-ExcelPackage -path test-input.xlsx
PS F:\Scripts> $newWorkbook = "newfile.xlsx"
PS F:\Scripts> $targetWorkbook = Open-ExcelPackage -Path test-output.xlsx
PS F:\Scripts> $targetWorkbook.workbook.Names["named_cell"].Value
PS F:\Scripts> $targetWorkbook.workbook.Names["named_cell"].Value = "2332"
PS F:\Scripts> $targetWorkbook.workbook.Names["named_cell"].Value
2332
PS F:\Scripts> Close-ExcelPackage $targetWorkbook -SaveAs $newWorkbook
Exception calling "SaveAs" with "1" argument(s): "Error saving file F:\Scripts\newfile.xlsx"
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.0\Public\Close-ExcelPackage.ps1:23 char:29
+             else           {$ExcelPackage.SaveAs( $SaveAs)}
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
`

**Comment by dfinke** [comment]
Hmm, don't know. Could be the ImportExcel part is having issues with the underlying data/structure. Would need to narrow this down with a repro. The EPPlus.dll is used to work with the xlsx and xml internals, it could be having an issue. If so, may not be fixable, that code is managed by others.

**Comment by feardamhan** [comment]
Any way to diagnose further? Would a copy of the file help at least determine the offender in this case?

**Comment by pkarunkar** [comment]
I was trying to replicate this with named cell (Single Cell and with Range). Both ways it is working fine. 
This could be one off issue.

Is this happening everytime? Did you try close powershell session and reopen a new session? 
Close all excel Processes and start again. ? 

Yes, attaching file would help in replicating the issue. 
Also remember you are passing the 2332 value as a string which may show warning "Number stored as Text" even if saveas is successful.

**Comment by feardamhan** [comment]
Yep. Tried new sessions. Excel itself is not installed as this is running on a server. In the case of 2332 thats just a test case for the example of the problem. there are many different types of inputs to be transferred, but ultimately, if they were all as text, that would be fine. I will drop you the file on email. Would rather not post it here.

**Comment by feardamhan** [comment]
[test-input.xlsx](https://github.com/dfinke/ImportExcel/files/5168436/test-input.xlsx)
@pkarunkar Example source file attached. hoping you can figure out why I cant save it after loading into an ExcelPackage

**Comment by pkarunkar** [comment]
Can you give me which name cell you are going to update. ? 
I don't see anything as named_cell.. 

![image](https://user-images.githubusercontent.com/44933985/92125631-3ca8de80-edcd-11ea-8aa4-61dbe824edb3.png)

**Comment by pkarunkar** [comment]
Never Mind, I tried to update ServerPort Named cell and it gives me the error.

**Comment by feardamhan** [comment]
Should have said 'named_cell' was just for the example above. There are 1000+ named cells in the file

**Comment by pkarunkar** [comment]
Forget about updating named cell. I am not able to open and save your excel . It works with simple excel or other excel files but not the attached file. Not sure how to debug this to figure out what is causing it. 

`$source = Open-ExcelPackage "C:\Users\PavithrasagarK\Desktop\Newfolder\test-input - Copy.xlsx" 
$source.Save()`

`PS C:\Users\PavithrasagarK> $source.Save()
Exception calling "Save" with "0" argument(s): "Error saving file C:\Users\PavithrasagarK\Desktop\Newfolder\test-input - 
Copy.xlsx"
At line:1 char:1
+ $source.Save()
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException`

**Comment by feardamhan** [comment]
Yep. Thats exactly the issue I reported in the OP. The retrieving and updating of named cells is not the issue. After opening this file, I cannot save it to the original file name or to a new file name. There is nothing terribly complex in this file. Several tabs, merged cells, some very basic formulas and references, and some conditional formatting. Do any of these features stand out to you guys as being problematic?

**Comment by dfinke** [comment]
Yeah, seems is something with your xlsx, could be EPPlus DLL being used cannot handle it. Sorry, not sure of a way forward at the moment.

**Comment by pkarunkar** [comment]
@feardamhan Try without the first sheet, Deployment Options. Looks like that contains something that EPPlus Doesn't like :) or Doesn't support with current version like Doug mentioned above.

**Comment by feardamhan** [comment]
Thanks folks. So I managed to track down the cause to a single cell. No idea why, I wiped the contents of the cell (values, data validation, conditional formatting) and set it up exactly the same again (at least to the naked eye) and it now saves perfectly. Do you mind telling me what you did to debug that tab in particular?
