### ISSUE TITLE
Struggling with adding password at save

### ISSUE THREAD

**Issue by jb78** [dfinke/ImportExcel#914]
I've googled, dove into the help and modules and I just cannot get this to work.

```
$excel=Open-ExcelPackage -path 'c:\test\jbtest.xlsx' -Create
$ws=Add-WorkSheet -ExcelPackage $excel

$excel.save("test")
```

I get the following error:

Exception calling "Save" with "1" argument(s): "Error saving file C:\test\jbtest.xlsx"

Everything that I've read seems to point that this should work.  I've tried various ways of setting the password all ending in an error with saving.  Any thoughts here?

**Comment by nlsdg** [comment]
What version of ImportExcel and Powershell are you using?
I've done the exact same commands as you with ImportExcel 7.1.1.
It works with Windows Powershell v5.1 and fails on Powershell Core 7.0.3.

From a comment on issue #637, that appears to be a problem with the EPPlus dll.
