### ISSUE TITLE
How to import the module in offline mode ?

### ISSUE THREAD

**Issue by vmaruhpe** [dfinke/ImportExcel#917]
How do we import this module in offline mode when there is no internet connectivity ?

**Comment by nlsdg** [comment]
You can import on one computer, and copy the ImportExcel subfolder from the modules folder to the modules folder on another computer.
And then use import-module as usual.

**Comment by nlsdg** [comment]
See the Powershell documentation: https://docs.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7
