### ISSUE TITLE
SUGGESTION:  Activate Specific PivotFilter

### ISSUE THREAD

**Issue by cmrsearch** [dfinke/ImportExcel#918]
Could not find a suggestion box, so leaving a message here.  Started using ImportExcel to up my reporting game from raw CSV to XLSX with autogenerated PivotTables & Charts.  This module has been absolutely fantastic, but to date I have not been able to find a way to Create a Pivot Table with one (or even more) active Filter(s) upon creation.  

Example:  I extract a list of On-Prem ADUsers from my Active Directory environment, using Export-Excel to export Sheet1 and New-PivotTableDefinition to add the Pivot Table and Chart on Sheet2.  Easy.  Well, what if there needs to be an emphasis in the Pivot & Chart to focus on when they receive it?  i.e. I'm adding a PivotFilter on the ADUser attribute "Enabled" (possibly another attribute that contains the user's "Region").  At this time, I can set the PivotFilter "Enabled","Region" for the reader to manually select from, but I cannot give it to them pre-set so that the immediate focus is on "Enabled"="True" and/or "Region"="NorthAmerica". 

Thank you for your time and consideration.

**Comment by MikeyBronowski** [comment]
I know it is a long time since the question was posted, but I found this. Might be supported in the 
[new version of EPPlus](https://github.com/EPPlusSoftware/EPPlus/pull/137)

**Comment by dfinke** [comment]
Yes, it looks to be implemented in the new EPPlus. There are lots of challenges and considerations to move to the new version though.
