### ISSUE TITLE
RFI: Is it possible to replace cell text by an image/icon? 

### ISSUE THREAD

**Issue by Geo-Ron** [dfinke/ImportExcel#919]
For example,

I would like a boolean value replaced in the excel by:

- True:    ![image](https://user-images.githubusercontent.com/23144316/93095714-bf6e4b00-f6a3-11ea-9f84-894dae6b98a2.png)
- False:   ![image](https://user-images.githubusercontent.com/23144316/93095857-efb5e980-f6a3-11ea-8c5b-27e63b126a33.png)

Would that be possible?
I have searched the examples but could not find any guidance...

**Comment by dfinke** [comment]
Interesting question. That's an Excel question. If you can find a way, this PowerShell mpdule may be able to automate it. I'd start by looking into `Conditional Formatting` and see what clues come from that.
