### ISSUE TITLE
SQL problems with single quotes - previously fixed, current code missing the fix.

### ISSUE THREAD

**Issue by sthoen** [dfinke/ImportExcel#920]
This was the code change that has been missed - fix #732 referred to this:

"'" + (($record.$propertyName) -replace "'","''") + "'"

**Comment by dfinke** [comment]
@beckerben wanted to get your input on this

**Comment by sthoen** [comment]
Sorry Doug, new this.  Have you merged the fix again?  If so, do I just update the PowerShell module?  Thank you.

**Comment by dfinke** [comment]
I didn't work with this fix directly. Trying to track it down.

I see a line here `ConvertFrom-ExcelToSQLInsert.ps1` that is similar. I don't see unit tests. 

Need to dig in some more.

**Comment by sthoen** [comment]
Let me know how I can assist.   I deal with hospital admissions and discharges and I finally have a name with a single quote in it that fails.

**Comment by dfinke** [comment]
Sorry, don't have an ETA on this
