### ISSUE TITLE
SeriesHeader ignored if more than 2 series used

### ISSUE THREAD

**Issue by lucdekens** [dfinke/ImportExcel#924]
Module ImportExcel 7.1.1

A New-ExcelChartDefintion with 3 series defined on the YRange parameter and 3 names specified the SeriesHeader parameter, shows the series as 'Series 1','Series 1','Series 1'.
No typo, indeed 3 times 'Series 1'.

When I remove 1 series and 1 header, the cmdlet works as intended, and the Legend shows the specified headers.

**Comment by dfinke** [comment]
Thanks Luc. Yes, unfortunately, have not been able to track down why,
