### ISSUE TITLE
Running slow when running as a script

### ISSUE THREAD

**Issue by lepri13** [dfinke/ImportExcel#925]
Hi,

When I run the module in ISE or CLI it's wicked quick. 

However once I wrap in into the script (I pipe out SQL query result about 900 Rows) if I run the script in ISE it works great. If I run the same as a script in powershell it takes orders of magnitude longer to run.

Is this expected behaviour? I think it has to do with how powershell is trying to run it.

Any advice would be really helpful

**Comment by dfinke** [comment]
Can you post an example?

**Comment by lepri13** [comment]
$result1 | Export-Excel C:\Users\XXXXXX\Desktop\XXXXX_REPORT_.xlsx -WorksheetName RAW -AutoSize

$result1 is the output from the SQL select. About 900 rows 25 colums

**Comment by lepri13** [comment]
If I run in ISE I can get about 17K lines of the same report in sub 60 seconds, running it as ps1 takes over 10 hours :) there is something a miss. If there is anything I can do testing wise let me know.

**Comment by dfinke** [comment]
Not sure off the top of my head why the environments would make it slower. 
You can also try `-InputObject`:

```powershell
Export-Excel C:\Users\XXXXXX\Desktop\XXXXX_REPORT_.xlsx -WorksheetName RAW  -InputObject $result1 -AutoSize
```

This bypasses `parameter binding`, and is faster.

**Comment by lepri13** [comment]
With -InputObject
ISE - 3 seconds
ps1 - 1 min 45 seconds

**Comment by dfinke** [comment]
I have no clue. Guess you'll need to use ISE all the time :-)

Are they the same version of ImportExcel in ISE and at the CLI?

**Comment by lepri13** [comment]
Yes, tested on two other machies with the same result. Also tried sigle thread mode just in case still the same. Powershell treats scripts differnetly from CLI and ISE.
