### ISSUE TITLE
[HELP] Creating Hyperlink in Excel File

### ISSUE THREAD

**Issue by gbargsley** [dfinke/ImportExcel#926]
I am looking for some guidance on making these Hyperlinks work within the same file.  I am not able to change the example to fit my script.

I would like to make the Name column on the Logins worksheet a hyperlink to the ADGroupAccounts worksheet. In the example I notice the Group-Object is building the list of objects to create Hyperlinks and the Foreach on Results is building a Range.  I cannot seem to figure that part out and combine it with the New-Object for Hyperlink

![image](https://user-images.githubusercontent.com/169602/94750103-f5b9f480-034a-11eb-8424-428cec4770a8.png)

![image](https://user-images.githubusercontent.com/169602/94750301-59442200-034b-11eb-989d-5acaae5185e9.png)

`# Get all instance logins

$Logins = Get-DbaLogin -SqlInstance $SQLInstance -ExcludeLogin $excludeLogin -ExcludeFilter $excludeLoginFilter
$LoginsGroups = $Logins | Where-Object LoginType -EQ "WindowsGroup" | Group-Object -Property Name
$LoginsGroups.Name`

`## Export Logins

$excelLoginSplatting = @{
    Path = $excelFilepath 
    WorkSheetname = "Logins"
    TableName = "Logins"
    FreezeTopRow = $freezeTopRow
    TableStyle = $tableStyle
    AutoSize = $autoSize
}
$Logins | Select-Object "Name", "LoginType", "CreateDate", "LastLogin" | 
    Sort-Object Name | Export-Excel @excelLoginSplatting
$LoginsGroup | ForEach-Object {(New-Object -TypeName OfficeOpenXml.ExcelHyperLink -ArgumentList "Logins!$($_.Name)" , "$($Logins.LoginType -eq 'WindowsGroup')")} | Export-Excel @excelLoginSplatting`

Any help or guidance would be greatly appreciated.

**Comment by gbargsley** [comment]
Hello sir.

Have you had any time to see what is possible for this situation?

**Comment by dfinke** [comment]
Sorry no. Have you looked at this example? https://github.com/dfinke/ImportExcel/blob/PrepForPester/Examples/SpreadsheetCells/HyperLink.ps1

**Comment by gbargsley** [comment]
I tried to use that. However since I was loading the data differently I could not get the example to work with my data set.

**Comment by sba923** [comment]
> Sorry no. Have you looked at this example? https://github.com/dfinke/ImportExcel/blob/PrepForPester/Examples/SpreadsheetCells/HyperLink.ps1

404...

I'm looking for a way to change simple values to values + hyperlink, what I would get in Excel using Ctrl+K. Is that at all possible with `ImportExcel`?
