### ISSUE TITLE
Remove existing conditional formatting in Excel file

### ISSUE THREAD

**Issue by tolecnal** [dfinke/ImportExcel#927]
I have a little question in regards to conditional formatting with the module. I've noticed that the formatting I've applied to a document "stacks up", by that I mean that any formatting previously applied to a file is kept and any new formatting is appended to the document.

Is there any way to clear any existing formatting in the document using this module? I've looked at all the cmdlets and I can't say that I have seen one that does this.

It would be very useful to remove any existing conditional formatting to ensure that the new formatting applied is indeed correct.

**Comment by dfinke** [comment]
The last three line opens, removes the conditional formatting, and closes the xlsx.

Hope this helps.

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
West,banana,19
East,kiwi,33
East,screws,40
North,screws,69
West,saw,25
West,saw,76
West,kiwi,37
East,melon,74
East,kiwi,14
West,screwdriver,42
"@

Export-Excel -InputObject $data -Path $xlfile -ConditionalText (New-ConditionalText -Text saw), (New-ConditionalText -Text kiwi -ConditionalTextColor DarkBlue -BackgroundColor Azure)

$xl=Open-ExcelPackage -Path $xlfile

$xl.Workbook.Worksheets["Sheet1"].ConditionalFormatting.RemoveAll()

Close-ExcelPackage $xl -Show
```

**Comment by tolecnal** [comment]
Hi again, and apologies for the late response. I can confirm that _ConditionalFormatting.RemoveAll()_ did the trick.

Thanks so much for your help, much appreciated.
