### ISSUE TITLE
Enhancement Request - Workbook File Properties

### ISSUE THREAD

**Issue by Skatterbrainz** [dfinke/ImportExcel#932]
Would it be possible to add support for writing document properties on the .xlsx itself?  For example, in Excel, click File / Info / Properties / Advanced Properties and modifying the Summary tab options like Title, Subject, Author, etc.

**Comment by dfinke** [comment]
Good question. Could you maybe scout out if EPPlus supports writing out that info? EPPlus is the .Net library I use that I use to create the xlsx files.
