### ISSUE TITLE
Send-SQLDataToExcel -ExcludeProperty not working as expected

### ISSUE THREAD

**Issue by Cory-PCI** [dfinke/ImportExcel#933]
I am using Send-SQLDataToExcel and I hoped to use the -ExcludeProperty switch to remove some columns that are undesired but are not present in all databases. Unfortunately, the Excluded columns still get imported into Excel. Is this parameter still supported?

This is an example of what I have tried:
Send-SQLDataToExcel -sql $query -MsSQLserver -Connection $ConStr  -FreezeTopRowFirstColumn -WorkSheetName UsCntl -ExcludeProperty UsName -AutoSize -BoldTopRow -force -path $FileName -ErrorAction Stop 

I do not get an error nor warning, just get the column specified in the ExcludeProperty unexpectedly.

**Comment by dfinke** [comment]
Looks like that parameter is still supported. Haven't tried it lately though,
