### ISSUE TITLE
-NoNumberConversion not working

### ISSUE THREAD

**Issue by dyde121** [dfinke/ImportExcel#934]
As I understand it adding -NoNumberConversion * to Export-Excel should ensure that data comes across as text rather than being converted to a number, however this doesn't appear to be working.

Issue I am having is shown below when exporting the same data to CSV vs Excel using
Export-Excel -FreezeTopRow -Path C:\Temp\Report.xlsx -NoNumberConversion *

CSV:
Status,SyncStage,RecipientTypeDetails
Completed,SyncFinished,UserMailbox

Export-Excel:
Status,SyncStage,RecipientTypeDetails
10,100,1

**Comment by ThubLives** [comment]
The `-NoNumberConversion` parameter still seems to do nothing, either with a wildcard or with a specific heading string.  Should it be removed if it's not going to be fixed?

**Comment by stahler** [comment]
Odd.  This parameter has always worked for me.
```PowerShell
$xlFile = "$env:TEMP\KeepLeadingZeros.xlsx"
Remove-Item -Path $xlFile -ErrorAction SilentlyContinue

# create some data 
$data = ConvertFrom-Csv @"
Name,ID,sysID
Thom,001,00010
Wes,010,0100
Gern,100,1001
Hari,002,0021
Shawn,111,1111
"@

Export-Excel -InputObject $data -Path $xlFile -Show -NoNumberConversion *

# or Export-Excel -InputObject $data -Path $xlFile -Show -NoNumberConversion ID, SysID
```
![image](https://user-images.githubusercontent.com/1991193/164513824-ca43310c-f254-4337-bee2-0d8c0488f095.png)

**Comment by ThubLives** [comment]
False alarm, I guess.
The script I was using to test this is gone and all my subsequent tests seem to be working, so I must have been using it wrong or had some version inconsistency in one of my many PowerShell sessions.
