### ISSUE TITLE
Delete worksheet on non-windows systems

### ISSUE THREAD

**Issue by fastGEAR** [dfinke/ImportExcel#935]
Thank you for great module! It saves me from daily routine.

Is there any way to remove worksheet on non-windows system(debian)?
Used version 7.1.1

Code:
...
$ex.Workbook.Worksheets.Delete("2020May")
MethodInvocationException: Exception calling "Delete" with "1" argument(s): "System.Windows.Extensions types are not supported on this platform."
...
also tried 
...
 $ex.Workbook.Worksheets["$actSheet"].Delete()
InvalidOperation: Method invocation failed because [OfficeOpenXml.ExcelWorksheet] does not contain a method named 'Delete'.
...
and variations...

**Comment by dfinke** [comment]
See if this works.

`Remove-Worksheet -Path $xlFile1 -WorksheetName Target1, Sheet1`

https://github.com/dfinke/ImportExcel/blob/88e2a23e1b2dac5d6ecea05058f6f42efc44b2f4/Public/Remove-Worksheet.ps1#L6

**Comment by fastGEAR** [comment]
nope.. sry.

Remove-Worksheet -Path "ShouldBeFullPathOrDoesn'tMatter?.xlsx" -WorksheetName "2020May"
MethodInvocationException: /home/[username]/.local/share/powershell/Modules/ImportExcel/7.1.1/Public/Remove-Worksheet.ps1:22
Line |
  22 |                      $pkg.Workbook.Worksheets.Delete($wsn)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Delete" with "1" argument(s): "System.Windows.Extensions types are not supported on this platform."

I should mention that file created in xls manually, long time ago. 

Everything except this working fine. 
One more thing: I had to delete a bunch of worksheets (~50) to make script working a while ago, it was failed on Close-ExcelPackage $excel -Calculate

**Comment by dfinke** [comment]
Yeah, the `xls` could be the issue. This module does not work with those files. There may be "attributes" left over from the `xls` that is causing this.

**Comment by fastGEAR** [comment]
*currently it's in xlsx
Is there any option to get rid of those "hidden" attributes? Recreate file/move sheets to new file/anything else?
If no solution - close the ticket please.

Thank you!

**Comment by dfinke** [comment]
Don't really know. Try a fresh xlsx and see if you can delete a worksheet from it. A sanity check to make sure the ImportExcel module isn't the issue.

**Comment by fastGEAR** [comment]
Tried
[https://github.com/dfinke/ImportExcel/blob/master/Examples/AddWorkSheet/AddMultiWorkSheet.ps1](https://github.com/dfinke/ImportExcel/blob/master/Examples/AddWorkSheet/AddMultiWorkSheet.ps1)
and then
`$excel.Workbook.Worksheets.Delete(1)`
**works perfectly fine.**

I guess refactor existing file is the way...
