### ISSUE TITLE
How to insert an array of values

### ISSUE THREAD

**Issue by MartinM85** [dfinke/ImportExcel#936]
Is there any way how to insert a multi-dimensional array of values?

I've tried

```
$file = "C:\Temp\Test1.xlsx"

$data = @(("header1","header2","header3"),(2,5,8),(3,6,9))

$excel = $data | Export-Excel -WorksheetName "Sheet1" -Path $file -PassThru

Close-ExcelPackage $excel -Show
```

but data are inserted in one column and I would like have it in range A1:C3. 
The number of columns is dynamic in my case, so I cannot use PSObject.

**Comment by dfinke** [comment]
`Export-Excel` is designed only to handle arrays of objects in a PowerShell array. 

If you can programmatically shape your arrays something like this, you can transform it to what `Export-Excel` can work with.

```powershell
$xlfile = ".\test.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$headers = ("header1", "header2", "header3")
$data = $(
    , (2, 5, 8)
    , (3, 6, 9)
) 

$records = for ($row = 0; $row -lt $data.Count; $row++) {
    $currentRow = $data[$row]
    $output = [Ordered]@{}
    for ($colIdx = 0; $colIdx -lt $headers.Count; $colIdx++) {
        $output[$headers[$colIdx]] = $currentRow[$colIdx]
    }
    [PSCustomobject]$output
}

$records | Export-Excel -Path $xlfile -Show
```

![image](https://user-images.githubusercontent.com/67258/96610289-75dbd600-12c9-11eb-850f-f7a0e6cad821.png)

**Comment by MartinM85** [comment]
Thanks
