### ISSUE TITLE
Error Message: "Unable to find type [OfficeOpenXml.ExcelPackage]."

### ISSUE THREAD

**Issue by barowe** [dfinke/ImportExcel#937]
I installed latest version"7.1.1" AND removed all the older versions.

I import the module in the scripts like this**:**
`Import-Module "C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1\ImportExcel.psm1"`

I started getting this error after I removed the older versions.
I solved the err by adding this statement right after the import of the module**:**
`Add-type -path "C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1\epplus.dll"`

PS > $psversionTable

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by dahuison** [comment]
To16qwwLpSDngpgkf3cBZbRPW39h9x3dvdMk
