### ISSUE TITLE
Advanced Pivot Table Options

### ISSUE THREAD

**Issue by jaswicki** [dfinke/ImportExcel#939]
I am trying to create Pivot tables from an existing Excel Worksheet and haven't had any luck at all. I have tried Importing the sheet to a variable and Opening the workbook as an Excel Package.  The only examples I have found are using tiny data sets that are supplied within the code. Does anyone have an example adding a pivot table to an existing XLSX?

I also want to format the Pivot table in Tabular Form Layout but haven't figured that out either. 

Any help is appreciated.

**Comment by dfinke** [comment]
This may help. The `-PassThru` is similar to what the `Open-ExcelPackage` does you need to use `Close-ExcelPackage` on the variable that you set the open to, so it can be saved.

`Add-PivotTable` is the way to go.

https://github.com/dfinke/ImportExcel/blob/e42f23cd7cf2fa4747d195f9e8ce4eea268430ac/Examples/PivotTable/MultiplePivotTables.ps1#L1

For a tabular layout, not sure how to solve that.

**Comment by jaswicki** [comment]
Thank you for the reply. I will give it shot. If anyone else has an idea on the Tabular Format it would be appreciated.

**Comment by uSlackr** [comment]
> No I never did. Sadly we do those steps manually.

One thing that might help.  Open an excel file containing  the pivot as you'd like it and examine it using powershell
```$ex = open-excelpackage mypivot.xlsx
$ex.Workbook.Worksheets['mysheet']
$ex.Workbook.Worksheets['summary'].PivotTables
$ex.Workbook.Worksheets['summary'].PivotTables[0]
```
I'm finding it very useful to reconstruct in code what is already have done manually

**Comment by jaswicki** [comment]
Thanks, I'll check it out.
