### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by wyzerd** [dfinke/ImportExcel#941]
All of my automation started failing on hosted agents with this:

`DEBUG: 00:00:01.1036993 Iterating 'ImportExcel'.

DEBUG: 00:00:01.1081797 There are '0' registered sources in 'NuGet' provider.

DEBUG: 00:00:01.1098478 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered sources in 'NuGet' provider.

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.

DEBUG: 00:05:51.9447846 Completed iterating for 'ImportExcel'.`

**Comment by dfinke** [comment]
I believe the Microsoft PowerShell Gallery is experiencing and outage.
