### ISSUE TITLE
[Question] Share Workbook status

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#942]
Is there a way to find out `Share Workbook` status? I thought it's `ShareDoc` property but it's always false. I could not find corresponding property in excelpackage object.

**Comment by dfinke** [comment]
Good question, don't know. You can rename the xlsx to zip, unzip it and look at the xml files, see if ShareDoc is there. I don't if the EPPlus library exposes that. Those are the first couple clues.

**Comment by scriptingstudio** [comment]
Found nothing intersting in xml files.

**Comment by dfinke** [comment]
Was that xlsx one created with the module? Wonder if it gets sets based on how/where it gets created?

**Comment by scriptingstudio** [comment]
No, it was created manualy.
