### ISSUE TITLE
Running Total | Graph

### ISSUE THREAD

**Issue by scm7ak** [dfinke/ImportExcel#944]
Hi there,

does anyone know if you can automatically create a chart that has a running total available with it? e.g...

I have Sales each month, and I want to see a line (not trend line) that shows the running total total. The X would be the Months, and the Y would be the sales, but I want to see the running total.

The actual graph that this works with is the Waterfall in excel, but this is not available in ImportExcel.

thanks,

**Comment by scm7ak** [comment]
just adding a comment to avoid the original post from going stale. Will only do this the one time.

Thanks.

**Comment by dfinke** [comment]
Sorry, unfortunately the Waterfall graph is not available in the module or the underlying library (which I do not maintain).
