### ISSUE TITLE
Cannot convert the "OfficeOpenXml.ExcelPackage" value of type "OfficeOpenXml.ExcelPackage" to type "OfficeOpenXml.ExcelPackage".

### ISSUE THREAD

**Issue by rlburkey** [dfinke/ImportExcel#945]
Good Afternoon!

I'm trying to import an excel spreadsheet, but receive an error, any help is appreciated.

I have installed/imported the ImportExcel module:

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     7.1.1      ImportExcel                         {Add-ConditionalFormatting, Add-ExcelChart, Add-ExcelDataV...

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.19041.546
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.546
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

The command I tried to use:
$Var = Import-Excel -Path $PathToWorksheet -WorksheetName $WorksheetName

The Error:
Cannot convert the "OfficeOpenXml.ExcelPackage" value of type "OfficeOpenXml.ExcelPackage" to type
"OfficeOpenXml.ExcelPackage".
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:111 char:17
+ ...             $ExcelPackage = New-Object -TypeName OfficeOpenXml.ExcelP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:113 char:24
+                 else { $ExcelPackage.Load($stream) }
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:218 char:47
+ ...               if ($Path) { $stream.close(); $ExcelPackage.Dispose() }
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by dfinke** [comment]
What is the `$PathToWorksheet` set to?

**Comment by rlburkey** [comment]
I tried a few different values for $PathToWorksheet, "worksbook.xlsx", ".\workbook.xlsx", "c:\temp\workbook.xlsx" and also without using a variable assignment, just typing in the file location.

**Comment by dfinke** [comment]
Seems like the xlsx has a problem. Can you open it in Excel directly?

**Comment by rlburkey** [comment]
Good Morning!

I can open the xlsx in Excel without issues.  I also just created a new xlsx doc with just one row of data (header1, header2, header3) saved it, and receive the same error.

**Comment by dfinke** [comment]
Not sure what the issue is. I'm running pS 7, and the latest Excel module. Created a new Excel file with just the header and get this as expected.

![image](https://user-images.githubusercontent.com/67258/98713274-62b2a800-2355-11eb-9de4-badf86db4ffe.png)

Added some data

![image](https://user-images.githubusercontent.com/67258/98713395-91c91980-2355-11eb-9eac-4a8911c5f59a.png)

**Comment by rlburkey** [comment]
Thanks for  your feedback, I just tried in PS7 and it worked as expected.  Must be something with 5.1.

**Comment by dfinke** [comment]
Seems to work for me.

![image](https://user-images.githubusercontent.com/67258/98718456-7b728c00-235c-11eb-8762-475dd5bb29b8.png)

**Comment by rlburkey** [comment]
I just uninstalled the module and reinstalled (which I also did yesterday before opening the request) and now its working.  Bizarre.  Thanks for your assistance!
