### ISSUE TITLE
Find and replace across worksheets in excel

### ISSUE THREAD

**Issue by whpeterson** [dfinke/ImportExcel#947]
Is there a way to do a find and replace across multiple worksheets in one excel file?  I have some values listed in cells in one worksheet and I'd like to be able to find that value and replace it with something different from another cell in a second worksheet.  Similar to a vlookup.  Thanks.

**Comment by dfinke** [comment]
There is nothing built into the PowerShell module to do that. You would need to loop through all the sheets and cells and use PowerShell to find and replace.
