### ISSUE TITLE
Setting orientation of a particular worksheet

### ISSUE THREAD

**Issue by martinaraftery** [dfinke/ImportExcel#948]
Is it possible to set the orientation of a worksheet using ImportExcel and other page setup properties?

Something like this:

$ws = $excel.Workbook.Worksheets['MyWorkSheet']
$ws.PageSetup.Orientation = 2   # for landscape.

Getting the following error when I try this: "The property 'Orientation' cannot be found on this object. Verify that the property exists and can be set."

**Comment by dfinke** [comment]
I don't know where/if that `Orientation` exists. You'd need to hunt for it.

**Comment by martinaraftery** [comment]
Found it.  
For anyone else that may be interested, need to use the Excel.Application -ComObject.

$Excel = New-Object -ComObject Excel.Application
$Doc  = $Excel.Workbooks.Open($File)
ForEach ($Worksheet in $Doc.Worksheets)
{
    $Worksheet.Activate()
    $Doc.ActiveSheet.PageSetup.PrintGridlines = $True
    $Doc.ActiveSheet.PageSetup.Orientation = 2
    $Doc.ActiveSheet.PageSetup.Zoom = $False
    $Doc.ActiveSheet.PageSetup.FitToPagesWide = 1           
    $Doc.ActiveSheet.PageSetup.FitToPagesTall = 1        
}
$Doc.Sheets(1).Select()

**Comment by scriptingstudio** [comment]
```
$ws.PrinterSettings.Orientation = [OfficeOpenXml.eOrientation]'Landscape'
$ws.PrinterSettings.PaperSize = 'A4'
```
