### ISSUE TITLE
Mange Data Model Relationships

### ISSUE THREAD

**Issue by Sladersca** [dfinke/ImportExcel#962]
Is there any way to manage data relationships, and then create a pivot table using the data model?

![Excel-Data-Relationships](https://user-images.githubusercontent.com/23408487/101067665-6e148000-355d-11eb-8db2-22f538655ad3.png)

**Comment by dfinke** [comment]
I have never used Excel `Relationships`. Nothing in the PowerShell module supports that at this time.
