### ISSUE TITLE
Font Style and Effects are changed when renaming worksheets

### ISSUE THREAD

**Issue by icattagrimes** [dfinke/ImportExcel#963]
Hello,
I am using the ImportExcel module to rename the first worksheet in Excel to a specific name for all .xlsx files in a specific folder.

I am able to achieve the desired goal with the following code:
```
Clear-Host
$directory = "C:\PowerShell\BA"
$file = Get-ChildItem -Path $directory -Name -Include *.xlsx
$wsname = "Sheet1"
Write-Output $file

foreach ($i in $file )
{
$xl= Open-ExcelPackage "C:\PowerShell\BA\$i"
$sheet1 = $xl.Workbook.Worksheets[1]
$sheet1.Name = $wsname
Close-ExcelPackage $xl
}
```

But one thing I have noticed is that on certain files, the font style has been changed to Bold and the Strikethrough effect has been applied to all cells.  What is strange to me is that I have 9 .xlsx in the folder for testing purposes and this is only happening to 3 of the files.  Any thoughts on what could be causing this issue and how to resolve it so that it does not happen?

**Comment by dfinke** [comment]
Have not heard of that. Sound like those 3 files have some issues. Don't know if you can recreate those from scratch and try again?

**Comment by icattagrimes** [comment]
Thanks for the reply Doug - these are files we receive from a vendor.  I'll try another batch we have received in the past to see if the issue occurs with them as well.

**Comment by dfinke** [comment]
## -WhatIf

See if a new sheet in a new xlsx shows the same issues.

```powershell
Import-Excel "C:\PowerShell\BA\fileInQuestion.xlsx" -WorksheetName "yyz" | 
Export-Excel  -Path "C:\PowerShell\BA\newFile.xlsx" -WorksheetName Sheet1 -Show
```

**Comment by icattagrimes** [comment]
Hey Doug - Thanks again for the reply.  I ran the code you proposed and that does not give me the issues where the font is changed to bold & italic and with the strikethrough effect.

**Comment by dfinke** [comment]
Leads me to believe there is something out of sorts with the original.

**Comment by icattagrimes** [comment]
Seems like it is an issue with the vendor files - I grabbed previous sets from this particular vendor and they exhibited the same behavior.  To get around this, I renamed the first sheet - then exported the spreadsheets to a temp directory where I applied some formatting and then removed the files we received from the vendor and copied the new files back to my source directory. 

I might could have combined some of the `foreach` loops - but I wasn't sure how and this runs pretty quickly as is.

```
#Clear-Host
$directory = "C:\PowerShell\BA\"
$tempdirectory = "C:\PowerShell\BA\NewFiles\"
$file = Get-ChildItem -Path $directory -Name -Include *.xlsx
$wsname = "Sheet1"
$filetype = "*.xlsx"
$sourcefiles = -join ($directory,$filetype)
$destinationfiles = -join ($tempdirectory,$filetype)
#Write-Output $file

foreach ($i in $file )
{
$xl= Open-ExcelPackage "C:\PowerShell\BA\$i"
$sheet1 = $xl.Workbook.Worksheets[1]
$sheet1.Name = $wsname
Close-ExcelPackage $xl
}

foreach ($i in $file)
{
Import-Excel "C:\PowerShell\BA\$i" -WorksheetName Sheet1 | Export-Excel -Path "C:\PowerShell\BA\NewFiles\$i" -WorksheetName Sheet1 -AutoSize -FreezeTopRow -BoldTopRow
}

foreach ($i in $file)
{
$x2= Open-ExcelPackage "C:\PowerShell\BA\NewFiles\$i"
Set-Format -Worksheet $w2 -Range "A:AZ" -VerticalAlignment Center -HorizontalAlignment Center
Close-ExcelPackage $x2
}

Remove-Item $sourcefiles | Where { ! $_.PSIsContainer }
Move-Item -Path $destinationfiles -Destination $sourcepath -Force
```
