### ISSUE TITLE
Import data from a pre-define table within a worksheet

### ISSUE THREAD

**Issue by dwchan69** [dfinke/ImportExcel#964]
Can ImportExcel put data from specific define tables within a worksheet?  Let say you have 3 unique set of data, right now each dataset is its own worksheet.  I can pull and load the data individually like this

$DataSourcePath = "G:\Transfer\VMware.xlsx"
$InfraParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'Infra'
$EmailParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'Email'
$VMParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'VM Templates'

But it is possible to have all 3 datasets on the same worksheet but different tables?  IF so, what's the syntax to address it?

**Comment by dfinke** [comment]
## Something like this

The first is easiest. You need figure out where to start the next table. There is also a `StartColumn` parameter.

```PowerShell
$DataSourcePath = "G:\Transfer\VMware.xlsx"

$InfraParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'Infra'
$EmailParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'Email'
$VMParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'VM Templates'

$InfraParameters | Export-Excel -Path $DataSourcePath -WorksheetName JustTables -TableName Infra
$EmailParameters | Export-Excel -Path $DataSourcePath -WorksheetName JustTables -TableName EmailParameters  -StartRow <You Need to Calculate>
$VMParameters | Export-Excel -Path $DataSourcePath -WorksheetName JustTables -TableName VMParameters -StartRow <You Need to Calculate>
```

**Comment by dwchan69** [comment]
Sweet, I have to try it out.  I get it separate worksheet is the easiest but for date entries and in some case overall appearance, layout may be better if you have multiple on the same sheet

![image](https://user-images.githubusercontent.com/36751593/101098581-2a3b6e00-3591-11eb-9e98-57058de63536.png)

I defined a name for each of the tables I am using.  So if i understood you correctly, the code would be something like

**Comment by dwchan69** [comment]
$RolesParameters | Export-Excel -Path $DataSourcePath -WorksheetName 'Lookup_Tables' -TableName 'Roles'
$SizeParameters | Export-Excel -Path $DataSourcePath -WorksheetName 'Lookup_Tables' -TableName' Size'  -StartRow 2
$Use_CasesParameters | Export-Excel -Path $DataSourcePath -WorksheetName 'Lookup_Tables'  -TableName 'Use_Casses' -StartRow <You Need to Calculate>

**Comment by dfinke** [comment]
Looks good.

Check this out also, https://github.com/dfinke/ImportExcel/blob/master/Examples/Tables/MultipleTables.ps1

**Comment by dwchan69** [comment]
FYI, I tried this out and got the following error

$VMRoles = Import-Excel -Path $DataSourcePath -WorksheetName 'LookUp_Tables' -TableName 'tbl_Roles' -StartRow 2

Import-Excel : A parameter cannot be found that matches parameter name 'TableName'.
At D:\VMware\WindowsVM.ps1:7 char:78
+ ... ath $DataSourcePath -WorksheetName 'LookUp_Tables' -TableName 'tbl_Ro ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-Excel], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Import-Excel

**Comment by dfinke** [comment]
`-TableName` is on `Export-Excel`. There are no helpers to read just tables.

It's more involved to read tables from the Excel "Object Model".

**Comment by dwchan69** [comment]
OK got it, is there any article or URL you can point me to ?

**Comment by dfinke** [comment]
Sorry, don't have any for that.

**Comment by dfinke** [comment]
## Here is a quick idea

If you can work this up further, make it generic, and add unit tests. It'd be a nice addition to the module.

```powershell
$xlfile = "$env:TEMP\test.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
North,banana,30
East,lime,2
South,lime,61
East,orange,72
North,drill,31
East,screwdriver,8
North,lemon,63
East,nail,64
South,nail,64
West,melon,46
"@

Export-Excel -InputObject $data -Path $xlfile -TableName Sample1
Export-Excel -InputObject $data -Path $xlfile -TableName Sample2 -StartColumn 5 

$WorksheetName = "Sheet1"
$xl = Open-ExcelPackage -Path $xlfile

function GetTableData {
    param($Address)

    $params = @{
        Path          = $xlfile 
        WorksheetName = $WorksheetName 
        StartRow      = $Address.Start.Row 
        EndRow        = $Address.End.Row 
        StartColumn   = $Address.Start.Column 
        EndColumn     = $Address.End.Column
    }
    
    Import-Excel @params
}

foreach ($table in $xl.$WorksheetName.Tables) {
    [PSCustomObject][Ordered]@{
        TableName = $table.Name
        Data      = GetTableData $table.Address
    }
}

Close-ExcelPackage -ExcelPackage $xl
```
