### ISSUE TITLE
How to pull in one specific row only

### ISSUE THREAD

**Issue by dwchan69** [dfinke/ImportExcel#965]
I am able to pull in my worksheet by "$OSSpecParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'OSCustomSpec'"  I can even control the row with the switch 'startrow 1'

But however, how can I use another define variable from my code to control which row I want to pull in?  For example, let say I have a variable $Spec='win10 spec' and my worksheet looks like this

![image](https://user-images.githubusercontent.com/36751593/101270573-433a4f80-3748-11eb-861f-20978e699f4c.png)

When I call up import-excel, I only want to pull up the 2nd row of data where Name equal to the $OS value of 'win10 spec'

**Comment by dfinke** [comment]
`Import-Excel` is designed to read data from sheets and cells. You need to pull back the data and then use PowerShell to search/subset it.
