### ISSUE TITLE
Failed importing with row paremeters

### ISSUE THREAD

**Issue by dwchan69** [dfinke/ImportExcel#966]
When I try to read in the first row of data, with the following code, no issue

$DataSourcePath = "G:\Transfer\VMware.xlsx" # Path to Excel Worksheet as the data sources
$OSSpecParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'OSCustomSpec' -StartRow 1 -EndRow 2

![image](https://user-images.githubusercontent.com/36751593/101295181-10e12e80-37ea-11eb-9138-31d4aeae73e9.png)

But why when I switch it over to next row like this later on in my code

$OSSpecParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'OSCustomSpec' -StartRow 2 -EndRow 3
I get the following error?

Failed importing the Excel workbook 'G:\Transfer\VMware.xlsx' with worksheet 'OSCustomSpec': Duplicate column headers found 
on row '2' in columns '3 4 5 8'. Column headers must be unique, if this is not a requirement please use the '-NoHeader' or 
'-HeaderName' parameter.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:216 char:21
+ ...     catch { throw "Failed importing the Excel workbook '$Path' with w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed importin...ame' parameter.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook 'G:\Transfer\VMware.xlsx' with worksheet 'OSCustomSpec': Du 
   plicate column headers found on row '2' in columns '3 4 5 8'. Column headers must be unique, if this is not a requirement  
   please use the '-NoHeader' or '-HeaderName' parameter.

**Comment by nlsdg** [comment]
Read the error message carefully: it tries to interpret the first row (row 2 of the file) as a header row.
You have the same value in more than one column (Tataoui in colum3 and 4 and blank in 5 and 8), which isn't allowed in a header row.
So the solution might be to use the -NoHeader parameter or the -HeaderName parameter. Depends on your code...
In your first import, you're importing the header row, so no surprise that worked.

**Comment by dwchan69** [comment]
I did saw the error but didn't understand the context.  Given your feedback, how do I explicitly call out row 1 as the header row?  not sure if it is possible.  I updated my code to where I initially read in one column (treating it as if it was the primary key for the table)  I put it in a loop to determine the position to which row of data I would need, than I would go back to retrieve the entire row, but only a single row , and this is when I ran into the error

$OSSpecName = Import-Excel -Path $DataSourcePath -WorksheetName 'OSCustomSpec' -HeaderName Name
$targetSpec = $VMParameters.VM_Spec
#$targetSpec = 'Win2019 Spec'
$EndRow = 1
do {
$compare = $OSSpecName.Item($EndRow).name
Write-Host $compare
$EndRow++
write-host $compare, $EndRow
} until ($targetSpec -eq $compare)
write-host 'End count is' $EndRow
$StartRow = $EndRow - 1
write-host 'start count is' $StartRow

**Comment by dwchan69** [comment]
Also, I left column 5 and 8 blank for here as It contains password info.  Just don't understand why this works
$OSSpecParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'OSCustomSpec'
while this does not
$OSSpecParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'OSCustomSpec' -StartRow $StartRow -EndRow $EndRow

perhaps I misunderstood the purpose for the startrow and endrow switches
