### ISSUE TITLE
Add option to disable hyperlinking

### ISSUE THREAD

**Issue by dbaileyut** [dfinke/ImportExcel#971]
Hi,

Using ImportExcel 7.1.1, there doesn't appear to be a way to disable making text a hyperlink if there's letters on either side of a colon. E.g.:

`[PSCustomObject]@{Test='abc:123'} | Export-Excel -Path test123.xlsx`

Results in this:
![image](https://user-images.githubusercontent.com/7095040/101946419-91ba7480-3bb4-11eb-9503-940114744e08.png)

I have some data that matches this format but I'd like it to be plain text and not a hyperlink. Am I missing something? If not, could you add a parameter or format option to disable hyperlinking?

Thanks!

**Comment by dfinke** [comment]
No there is no helper functions for the or examples. You'd need to use `-PassThru` and `Set-Format` for the range(s) to turn off the underline.

**Comment by dbaileyut** [comment]
That would turn off the underline, but wouldn't it still be a hyperlink?

**Comment by dbaileyut** [comment]
I think what I'm asking is an option to avoid falling into code paths where "IsWellFormedUriString" evaluates as true like this:

https://github.com/dfinke/ImportExcel/blob/0a77a83e35e516b96af7dcee99e945d639c23506/Public/Export-Excel.ps1#L331-L341

**Comment by dfinke** [comment]
Understood. Sorry, at this point, I don't have the time to build that or add the tests to prove it out.

**Comment by JoelWiesmann** [comment]
@dbaileyut  I had the same issue today. I solved it with a little workaround:
[PSCustomObject]@{Test='="abc:asd123"'} | Export-Excel -Path test123.xlsx

Might not be the best solution for all use-cases, but for me it works.
