### ISSUE TITLE
Issue utilizing the Export-MultipleExcelSheets function

### ISSUE THREAD

**Issue by shubinsb** [dfinke/ImportExcel#972]
Hello,

I have a PS script that looks through a bunch of objects and saves them as a variable. Whenever calling the Export-MultipleExcelSheets function, I get the following error:

Export-Excel : Exception calling "Save" with "0" argument(s): "Error saving file C:\Users\bshub\Downloads"
At line:24 char:30
+             & $entry.Value | Export-Excel @parameters
+                              ~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (:) [Export-Excel], MethodInvocationException
   + FullyQualifiedErrorId : InvalidOperationException,Export-Excel

I'm calling it by using Export-MultipleExcelSheets -Path C:\Users\bshub\Downloads -InfoMap $DatatoExport -Show -AutoSize

I have confirmed the module is loaded as Export-Excel seems to work when called on it's own.

Any help would be greatly appreciated. Thanks!

**Comment by shubinsb** [comment]
I'm dumb and missed a variable!

**Comment by dfinke** [comment]
What variable did you miss?

**Comment by shubinsb** [comment]
I neglected to set a variable for file output location. I figured it'd just
dump one out into the temp folder automatically like it does when just
running the base module but it doesn't.
