### ISSUE TITLE
Suggestion - Example with Multiple Worksheets

### ISSUE THREAD

**Issue by TrevorWesterdahl** [dfinke/ImportExcel#973]
I just started testing this an hour ago and love it so far. I didn't see a clear example of how to create a workbook with multiple worksheets. Would be grateful for a simple example with simple data in multiple sheets. Do we just create a workbook the normal way, then use the append option specifying a different worksheet? Any help is appreciated.

**Comment by TrevorWesterdahl** [comment]
Just donated $30 for the fast response and as a general thank you. Appreciated.

**Comment by dfinke** [comment]
Thank you very much. Very much appreciate!

**Comment by TrevorWesterdahl** [comment]
You are welcome. Hope more do the same. You put a lot work into this and it works really, really well.

**Comment by dfinke** [comment]
@TrevorWesterdahl did that do what you needed?

**Comment by TrevorWesterdahl** [comment]
Yes, thank you. Worked great.
