### ISSUE TITLE
How to get Now formatting without opening spreadsheet?

### ISSUE THREAD

**Issue by TrevorWesterdahl** [dfinke/ImportExcel#975]
Hoping this is a simple question. The auto-formatting performed when using the Now option works perfectly for what I need. How do I get the same formatting without opening the spreadsheet?

**Comment by dfinke** [comment]
I'm not sure what you mean by "without opening". The `-Now` sets a few things, `-AutoSize`, `-TableName Table` and `-AutoFilter`.

**Comment by TrevorWesterdahl** [comment]
It was the TableName that got me. Figured it out now. Thanks again.  Works great.
