### ISSUE TITLE
Define Namespace in Excel Worksheet

### ISSUE THREAD

**Issue by krichardson77** [dfinke/ImportExcel#976]
I am using the Import-Excel module for PowerShell and I’m trying to define a namespace in an excel file using the Open-ExcelPackage command.  I am able to retrieve the workbook and the worksheet and see all the data, but I don’t see how to define a Range of data and then Define the Name.  Is there a way to do this?

**Comment by dfinke** [comment]
There is an `-AutoNameRange` switch on `Export-Excel`. It creates named ranges for each property.

```powershell
$xlfile = "$env:TEMP\test.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Region,Item,TotalSold
East,lime,59
West,pear,75
West,screwdriver,38
South,peach,1
East,screws,55
North,hammer,35
West,banana,76
East,nail,25
West,pear,77
East,screws,96
"@

$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru

$range = $xl.Sheet1.Cells["B4:B7"]
$xl.Sheet1.Names.Add("Section", $range)

Close-ExcelPackage $xl -show
```

**Comment by krichardson77** [comment]
Thank you for the information.  It did work to create a Defined Namespace in the Excel spreadsheet, but there is a problem with how it works.

It seems that using the $range variable as you did to get the Dimensions of the selected cells causes the output of the cells to go to the screen.  This is causing it to take a very long time to run and would be much longer if I had the full spreadsheet.

Is there any way to suppress this output of the Cell information to the screen?  I ran your example above and it appears to do the same thing.

**Comment by dfinke** [comment]
```powershell
$null = $xl.Sheet1.Names.Add("Section", $range)
```

**Comment by krichardson77** [comment]
The last thing I am having trouble with is the scope of the Defined Namespace.  It also defaults the scope of the namespace to the name of the WorkSheet, but I need the scope to be Workbook.  Is there a way to make the scope of the defined namespace Workbook?

**Comment by dfinke** [comment]
Don't know. You can try and see if there is a Names collection the Workbook. Not sure if Excel lets you do that from the UI.
