### ISSUE TITLE
Problems with Export-Excel

### ISSUE THREAD

**Issue by FinnMacCool** [dfinke/ImportExcel#977]
I regularly create a CSV file where some lines have a string value (always the same) in the last column (G) and others do not. This file is then converted to XLSX using the following command:

Get-Content E:\file_name.csv | ConvertFrom-Csv -Delimiter ';' | Export-Excel E:\file_name.xlsx

This worked for quite a while, but suddenly the conversion started also setting the value for many lines that didn't have it in the CSV. After some rather fruitless testing and changing the SQL script that handles the export to CSV back and forth, the conversion seems to work correctly again for some reason (with the exact same code and configurations as before).
However, as the conversion also has to work when I'm away, I would really appreciate it if you could either fix this or tell me how to prevent it from happening again. (I realise this report may be a little too vague to work from, but one can hope.)

Another problem (or feature?) that I noticed along the way is that if you name the output file "Test.xlsx", the conversion will add information about currently running processes to the result.

**Comment by scriptingstudio** [comment]
More short way:
`Import-Csv E:\file_name.csv -Delimiter ';' -encoding default | Export-Excel E:\file_name.xlsx`

**Comment by FinnMacCool** [comment]
Thanks for the tip.
Now the last two lines (out of about 1100) are repeated at the end.

**Comment by scriptingstudio** [comment]
Check your CSV with this
`Import-Csv E:\file_name.csv -Delimiter ';' -encoding default | out-gridview`

**Comment by FinnMacCool** [comment]
Hmm, with
`Import-Csv E:\file_name.csv -Delimiter ';' | select-object -last 2 | Export-Excel E:\file_name.xlsx`,
the two repeated lines replaced the first two lines instead. The same happened with
`Import-Csv E:\file_name.csv -Delimiter ';' | select-object -last 0 | Export-Excel E:\file_name.xlsx`
and
`Import-Csv E:\file_name.csv -Delimiter ';' | select-object -first 0 | Export-Excel E:\file_name.xlsx`.
With
`Import-Csv E:\file_name.csv -Delimiter ';' -encoding default | select-object -first 1100 | Export-Excel E:\file_name.xlsx`,
it seems to work for now.
Curiouser and curiouser...

**Comment by scriptingstudio** [comment]
It is probably your CSV contains something that corrupts output. Does `out-gridview` output look correct?

**Comment by FinnMacCool** [comment]
Yes, it does.

**Comment by scriptingstudio** [comment]
BTW, `-last 0` and `-first 0` are meaningless. The argument is count, NOT index. For index there is parameter `-index`. 
If except the fact that `export-excel` works correct but the problem persists you can try this
```
# to rebuild data
import-csv | export-csv
# then
import-csv | export-excel
```
Play with `select-object` to find corrupted data.

**Comment by FinnMacCool** [comment]
I only used `-last 0` and `-first 0`  to see if the number of repeated lines was in any way dependant on the count (which it was not).

Running
```
Import-Csv E:\file_name.csv -Delimiter ';' -encoding default | Export-Csv E:\file_name2.csv

Import-Csv E:\file_name2.csv -Delimiter ';' -encoding default | Export-Excel E:\file_name.xlsx
```
resulted in a CSV file that had all values surrounded separately with quotation marks (but everything was displayed as a single column via out-gridview) and the special characters were messed up despite `-encoding default`.
Oddly enough, the XLSX file that was generated from that had the same messed up column followed by the correctly displayed values (to the right).

Most vexing...

**Comment by FinnMacCool** [comment]
So, did you fix something or was this just not enough info to work from?
