### ISSUE TITLE
EPPlus Replacement

### ISSUE THREAD

**Issue by Tiberriver256** [dfinke/ImportExcel#979]
Hey thanks for this awesome module. This is more just a curiosity question. Now that EPPlus is commercially licensed (since v5) are you planning on a replacement? or would you just stay on v4 as long as possible?

**Comment by Tiberriver256** [comment]
Thanks for the reply! I'll be curious to see which way you head :)

**Comment by dfinke** [comment]
Do you have a preference? Is there a feature(s) in v5 you are looking for?

**Comment by RenatoGregio** [comment]
@dfinke thanks a lot for this amazing module. With then we can build our inventory tool. 
do you know a way to create treemap without EPPlus v5?

**Comment by dfinke** [comment]
@RenatoGregio No, don't know, not sure it can be. If possible, it'd be great to see how your building that tool.

**Comment by RenatoGregio** [comment]
> @RenatoGregio No, don't know, not sure it can be. If possible, it'd be great to see how your building that tool.

Our tool is Azure Resource Inventory. Now we are working on V2 :) 

https://github.com/azureinventory/ARI

**Comment by dfinke** [comment]
Thanks! Great to see this used in the Azure space. I'll keep my ear to the ground about a treemap, but I don't think that'll happen.

**Comment by dfinke** [comment]
I did start porting the module to EPPlus v5, lots of breaking changes. I stopped for several reasons. The primary reason being v5 requires a paid license for use in commercial settings. 

Here is a treemap 🙂. I don't believe I will make this public though.

![image](https://user-images.githubusercontent.com/67258/132764115-265d0fd1-7d5a-4484-8c5d-8191537c6ea4.png)
