### ISSUE TITLE
Office 365 removing attachments

### ISSUE THREAD

**Issue by jasongreb** [dfinke/ImportExcel#98]
When generating a file with ImportExcel and sending it through Office 365, it appears to be getting removed. I unfortunately don't have access to our email system so I can't dig deeper there, but I wanted to know if anyone had similar issues. I read somewhere that it might help to have some of the document properties set, but that hasn't helped. I added the following to Export-Excel.ps1 at line 73, thought it might be a nice addition, maybe pass it as an object.

```
        $pkg.Workbook.Properties.Application = "Microsoft Excel"
        $pkg.Workbook.Properties.Company = $Company
        $pkg.Workbook.Properties.AppVersion = "14.000"
        $pkg.Workbook.Properties.Author = $Author
```

**Comment by dfinke** [comment]
Thanks. I can bake that in and maybe add two params for the company and author. Let me know if you get any answers for emailing.

**Comment by jasongreb** [comment]
I'm not quite sure what the version should be. I just stuck that number in. There might be a best practice on that. Nothing on the emailing yet. Still trying to find out why they are different. The only difference that sticks out so far is that EPPlus adds carriage returns in the XML and Excel does not.
