### ISSUE TITLE
Filling in Empty Cells - Drop Fill

### ISSUE THREAD

**Issue by WinOpsEngineer** [dfinke/ImportExcel#980]
Hello

I am trying to automate the filling of empty cells. 

I have a column named 'MR #'(A1) that has numeric code. Column D is the corresponding description. There are  random  empty cells  till the next 'MR#' value. I wanted to see if it was possible to "drop fill" all the empty cells (under 'MR#' column A) until I hit the next cell that has a value and then repeat until all the cells have been filled. 

The drop fill also can not auto increment the value - it has to remain the same #.

If "drop fill" is not an option some type of loop setting the empty values would be ok to.

Attached is an example work book

[example.xlsx](https://github.com/dfinke/ImportExcel/files/5775527/example.xlsx)
 workbook

Thank you for any help on this

**Comment by jhoneill** [comment]
```PowerShell
$xlpath      =  "~\Downloads\test.xlsx" 
$sheetName   = "Sheet1"
$fillColumn  = 1 # Column "A"

$xlpkg       = Open-ExcelPackage -Path $xlpath
$sheet       = $xlpkg.Workbook.Worksheets[$sheetName]

foreach ($row in (1..$sheet.Dimension.Rows)) {
    if   ($sheet.Cells[$row,$fillColumn].value) { 
          $currentValue = $sheet.Cells[$row,$fillColumn].value }
    else {$sheet.Cells[$row,$fillColumn].value = $currentValue }
 }
 Close-ExcelPackage $xlpkg -Show
```


That should do it

**Comment by WinOpsEngineer** [comment]
Amazing!! Thank you 👍 so much

**Comment by dfinke** [comment]
@WinOpsEngineer let me know of this works for you. It's a good candidate to add to the Examples folder.

**Comment by WinOpsEngineer** [comment]
Yes it did work but it is copying the # value as a string causing the workbook to put 2 green arrows in each cell. is there anyway to  copy and format the cell as an int if its an int?

se attahced pic

![number_stored_asText](https://user-images.githubusercontent.com/40338530/103960189-945eaa00-511f-11eb-86ec-cbfa516e64e6.png)

**Comment by jhoneill** [comment]
Your original value was a string so it copied the string. 
If you know the values are really numbers you can but this in the `if` block
```PowerShell
          $currentValue = $sheet.Cells[$row,$fillColumn].value -as [Long] 
```

To be more generic you'd use something like this. 
```PowerShell
          $currentValue = $sheet.Cells[$row,$fillColumn].value
          $number       = $null
          if ([Double]::TryParse($currentValue, [System.Globalization.NumberStyles]::Any, [System.Globalization.NumberFormatInfo]::CurrentInfo, [Ref]$number)) {
            $currentValue = $number
          }
```
I might even make this 
```
$sheet.Cells[$row,$fillColumn].value = $currentValue 
```
_unconditional_ so that if you have a string to start it gets converted into a number. 


@dfinke - it would make a nice addition to the examples. When one of us has time (!)

**Comment by dfinke** [comment]
@jhoneill Once it is sorted out, I'll take a deeper look, and then add it. I see where it is going. When I read "Filling In" I thought of the Excel shortcut keys and I didn't think it thru to a code solution.

**Comment by WinOpsEngineer** [comment]
That fixed it. The excel workbook looks great. Thank you!
