### ISSUE TITLE
Trying to save Excel file with .SaveAs

### ISSUE THREAD

**Issue by krichardson77** [dfinke/ImportExcel#981]
I am opening an Excel file, making changes and then saving.  I realized when I receive the file directly from the source and try to do a .SaveAs operation that it always gives me an error:

$excel = Open-ExcelPackage -Path $ExcelInputFile

$excel.SaveAs("\\mmbfile\RiskM\TravelersForAnalytics\Test1234.xlsx")
Exception calling "SaveAs" with "1" argument(s): "Error saving file \\mmbfile\RiskM\TravelersForAnalytics\Test1234.xlsx"
At line:1 char:1
+ $excel.SaveAs("\\mmbfile\RiskM\TravelersForAnalytics\Test1234.xlsx")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

The error is nondescriptive and doesn't tell me what the problem is.  I realized if I save the file in Excel before try to save, that is doesn't error.  I am the owner of the file in both situations and the only difference is the "Last Saved By" field on the file.  

I have tried within the Powershell module to figure out what the problem is, but nothing seems to work.  Do you know how to fix this?

**Comment by dfinke** [comment]
Can you post the file?

**Comment by krichardson77** [comment]
[5 Year All Lines Report.xlsx](https://github.com/dfinke/ImportExcel/files/5783777/5.Year.All.Lines.Report.xlsx)

Here is an example file that I am trying to save.  I assume it will still have the problem after I copy it.  Let me know if get the same issue.

**Comment by dfinke** [comment]
I get the same issue.  It is dying in a lower layer that I don't have control over, not sure if more details can be pulled from it either.

The size of the xlsx goes to 2630 from 2432 (original file). So Excel can read it, and may add the need info when saved for the PowerShell module.

For now, you'll need a better xlsx. You could possibly use the `-Com` switch on the `New-Object` function.

https://github.com/dfinke/ImportExcel/blob/04b7895d1ec23d295243773ac522d80321a240e1/Public/ConvertTo-ExcelXlsx.ps1#L1
