### ISSUE TITLE
How to filter a column after Export-Excel

### ISSUE THREAD

**Issue by skest3qc** [dfinke/ImportExcel#982]
Hi,

i am using this little code to see how i can filter a column in Excel (Column :StartType = Disabled)

```
$Services = Get-Service | Select-Object Status, Name, DisplayName, StartType 

$Services | Export-Excel -Path C:\TEMP\Services.xlsx -AutoFilter -AutoSize -Show

```
I know i can filter it with Get-Service but i would like to keep all objects and filter (default filter) in Excel

Would this be possible?

**Comment by dfinke** [comment]
At this time that is not doable with the module, unfortunately. It is not available in the underlying API.
