### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by RHJBiesters** [dfinke/ImportExcel#984]
Hello,

I am trying to get number and date formatting correct using Export-Excel. I am making progress but I am still not there.

Using the following command (-numberformat '#,000.00')  I am able to set get currency correctly. But the formatting is set to all columns. Is there a way to set a different Numberformat for different columns as I would like to have it switched off for normal text and have a different one for dates? Or should I approach it a total different way? After 2 days of Googling no progress so that why to ask the question here.

$excel = echo $CSV1 | Export-Excel -Path $XSLXName -AutoSize -BoldTopRow -NoNumberConversion 'InvoiceNo','CustomerNo' **-numberformat '#,000.00'** -WorksheetName $sheetName -Style $style  -CellStyleSB {
          param($workSheet)  		  
          $WorkSheet.Column(2).Width=15
          $WorkSheet.Column(4).Style.HorizontalAlignment="Left"
          $WorkSheet.Cells["A4:E4"].Style.Font.Bold = $true
       }

**Comment by dfinke** [comment]
Yes, try Set-ExcelRange. It lets you specify any range and change things about the data, fonts, and more.

**Comment by RHJBiesters** [comment]
Do you have an example as I have a the moment no idea how to get this work.

**Comment by dfinke** [comment]
It could be that your dates are being stored as strings.

https://github.com/dfinke/ImportExcel/tree/master/Examples

**Comment by RHJBiesters** [comment]
Not really. The setting in Excel is DATE (*14 03 2012), which is fine. The only issue at the moment is that if I open the Excel the date is formatted as in the CSV file. If I select one of the date fields and give an enter in the box just below the ribbon, the value in the fields is transformed to the one as set in the regional setting. 

So I can set the settings of a specific column to Date, but the value is not converted. I have to do an manual action to get it executed. Found no way around this. I will check you examples to see if I can find a way to sort this out. Thanks for your support.

**Comment by dfinke** [comment]
```powershell
$xlfile = "$env:TEMP\test.xlsx"
Remove-Item $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Jan,Feb
1/6/2021,2/25/2021
1/26/2021,2/19/2021
1/20/2021,2/23/2021
1/18/2021,2/18/2021
1/21/2021,2/15/2021
1/30/2021,2/22/2021
1/2/2021,2/8/2021
1/28/2021,2/5/2021
1/23/2021,2/9/2021
1/12/2021,2/11/2021
"@ 

foreach ($row in $data) {
    $row.Jan = get-date $row.Jan 
}

$xl = Export-Excel -InputObject ([docvt[]]$data) -Path $xlfile -AutoSize -PassThru

Set-ExcelRange -Worksheet $xl.Sheet1 -Range A:A -NumberFormat 'MMM-dd'
Set-ExcelRange -Worksheet $xl.Sheet1 -Range B:B -NumberFormat 'dd-MMM-yyy' # does nothing, the Column 'Feb' is a `String`

Close-ExcelPackage $xl -Show
```

**Comment by RHJBiesters** [comment]
Thanks for the demo. I believe it has something to do with our Excel version as the correct data formats are only taken into account when giving an enter in every date field. From that moment the date is formatted correctly and acting like a date. I am contacting an Excel expert to get this sorted out.

**Comment by RHJBiesters** [comment]
By changing my PS script using your example I was able to get it to work. Thanks for the support. Number as Date formatting is correct and useable now.

**Comment by RHJBiesters** [comment]
Thanks for the support.
