### ISSUE TITLE
How to export a value or comment to the cell of a workbook that is currently open

### ISSUE THREAD

**Issue by thomaslo88** [dfinke/ImportExcel#986]
Hi, I am not sure if the similar question was ever posted and answered but I am trying to figure out how to write a value or comment into the cell of a workbook that is already open and it has to be open at all times for some applications. I have tried to use functions such as Open-ExcelPackage and Export-Excel but no luck. Can anyone provide an example to show how it can be done using the Import-Excel module? Thank you very much.

**Comment by dfinke** [comment]
Sorry, the module does not support working with documents that are open.

**Comment by thomaslo88** [comment]
Thank you for your instant response, Doug! I was suspecting the module doesn't support this. Now I can look for other approaches that may help accomplish my goal. Thanks for confirming it again!

**Comment by dfinke** [comment]
Also, https://github.com/dfinke/ImportExcel/pull/958 supports writing comments, but not while the Excel doc is opened
