### ISSUE TITLE
Worksheet Tab Color

### ISSUE THREAD

**Issue by rzippo** [dfinke/ImportExcel#987]
Is there a way to set the tab color of a given worksheet?

**Comment by MikeyBronowski** [comment]
Try something like that:
```powershell
Set-Location $env:TEMP
$excelFiles = "ImportExcelHowTo.xlsx"
Remove-Item $excelFiles -ErrorAction SilentlyContinue

# create a file
$excelPackage = 1..10 | Export-Excel -Path $excelFiles -PassThru

# get the worksheets
$excel = $excelPackage.Workbook.Worksheets['Sheet1']

# see the color
$excel.TabColor

# set the color
$excel.TabColor = 'Yellow'


Close-ExcelPackage $excelPackage -Show

```

**Comment by rzippo** [comment]
Thanks, this works.
Is there some documentation to search for issues like this?

**Comment by MikeyBronowski** [comment]
I guess you could have a read [here](https://documentation.help/OfficeOpenXML/7a4fc7c0-12dd-d239-9261-f4ca38b8523f.htm) or [here ](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.sheetproperties.tabcolor?view=openxml-2.8.1)

**Comment by dfinke** [comment]
The `-PassThru` switch on `Export-Excel` returns the the "Excel Object". Then you can use the Microsoft Object Model documentation to figure out how to do these types of operations. 

```powershell
$excelPackage = 1..10 | Export-Excel -Path $excelFiles -PassThru
```
