### ISSUE TITLE
read in a cell as an array

### ISSUE THREAD

**Issue by dwchan69** [dfinke/ImportExcel#990]
I have a cell in excel that has multiple entries, like this

![image](https://user-images.githubusercontent.com/36751593/105901143-edb54d00-5fea-11eb-9430-699025f2eb84.png)

ESX01=192.168.10.20,ESX02=192.168.10.21,ESX03=192.168.10.22,ESX04=192.168.10.23

I can read and pass that cell into powershell but it comes across as a single string of variable

$MgmtVCSAParameters = Import-Excel -Path $DataSourcePath -WorksheetName 'Mgmt-VCSA'
$test = $MgmtVCSAParameters.MgmtESXHosts

I can't seem to get it to convert to an array, similar to doing this manually

$Test = @{
    "ESX01" = "192.168.10.20"
    "ESX02" = "192.168.10.21"
    "ESX03" = "192.168.10.22"
    "ESX04" = "192.168.10.23"
    }
Any feedback would be appreciated

**Comment by dfinke** [comment]
The `$Test = @{}` is a hash table.

```powershell
(Import-Excel .\test.xlsx).MgmtESXHosts.split(',') | foreach {$k,$v=$_.split('='); @{$k.trim()=$v}}
```

```
Name                           Value
----                           -----
ESX01                          192.168.10.20
ESX02                          192.168.10.21
ESX03                          192.168.10.22
ESX04                          192.168.10.23
```

**Comment by dwchan69** [comment]
Interestingly, even though the values seem right, the behaviors are not the same.  For example, using a static values

$NestedESXiHostnameToIPs = @{
    "ESX01" = "192.168.10.20"
    "ESX02" = "192.168.10.21"
    "ESX03" = "192.168.10.22"
    "ESX04" = "192.168.10.23"
    }
And where I just echo out the variable - echo $NestedESXiHostnameToIPs, the value and format are as follow

PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs

Name                           Value                                                                                       
----                           -----                                                                                       
ESX03                          192.168.10.22                                                                               
ESX01                          192.168.10.20                                                                               
ESX04                          192.168.10.23                                                                               
ESX02                          192.168.10.21 

And when i recall the array using the following
$NestedESXiHostnameToIPs.GetEnumerator() | Sort-Object -Property Value | Foreach-Object {
    $VMName = $_.Key
    $VMIPAddress = $_.Value
    write-host $VMName, $VMIPAddress
}

My output looks like this, as expected
ESX01 192.168.10.20
ESX02 192.168.10.21
ESX03 192.168.10.22
ESX04 192.168.10.23

However, when I try to load in the array with importexcel

$NestedESXiHostnameToIPs = $MgmtVCSAParameters.MgmtESXHosts.split(',') | foreach {$K,$V=$_.split('='); @{$K.trim()=$V}}

The array seem to ingest and format the data properly, as when I echo the variable, it looks the same as if I set the array manually
PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs

Name                           Value                                                                                       
----                           -----                                                                                       
ESX03                          192.168.10.22                                                                               
ESX01                          192.168.10.20                                                                               
ESX04                          192.168.10.23                                                                               
ESX02                          192.168.10.21 

However, when i used the import-excel load array, and run the same recall statement I did earlier

$NestedESXiHostnameToIPs.GetEnumerator() | Sort-Object -Property Value | Foreach-Object {
    $VMName = $_.Key
    $VMIPAddress = $_.Value
    write-host $VMName, $VMIPAddress
}

The output is blank!  What did I miss?

**Comment by scriptingstudio** [comment]
you missed underscores + undesirable `select-object` which breaks output object
```
$VMName = $_.Key
$VMIPAddress = $_.Value
```

**Comment by dwchan69** [comment]
Sorry, for some reason the underscore did not copy and paste over..  But i did include the underscore, same error

**Comment by dwchan69** [comment]
$NestedESXiHostnameToIPs.GetEnumerator() | Sort-Object -Property Value | Foreach-Object {
    $VMName = $_.Key
    $VMIPAddress = $_.Value
    write-host $VMName, $VMIPAddress
}

**Comment by dwchan69** [comment]
and sorry for being a newbie, but do not understand the last part to your comment 
"undesirable select-object which breaks output object"

**Comment by scriptingstudio** [comment]
I misprinted and deleted that part

**Comment by scriptingstudio** [comment]
trying to repro your case

 data from Excel:
$test = 'ESX01=192.168.10.20,ESX02=192.168.10.21,ESX03=192.168.10.22,ESX04=192.168.10.23'

converting to hashtable:
$NestedESXiHostnameToIPs = @{}
$test.split(',') | % {
	$key,$value = $_.split('=')
	$NestedESXiHostnameToIPs[$key] = $value
}
$NestedESXiHostnameToIPs
```
Name                           Value
----                           -----
ESX03                          192.168.10.22
ESX01                          192.168.10.20
ESX04                          192.168.10.23
ESX02                          192.168.10.21
```

**Comment by dwchan69** [comment]
OK, I did some more debugging and it turns out even though visually, it seems to look the same, the actual data structure is different.

For manual entries

$NestedESXiHostnameToIPs = @{
    "ESX01" = "192.168.10.20"
    "ESX02" = "192.168.10.21"
    "ESX03" = "192.168.10.22"
    "ESX04" = "192.168.10.23"
    }

PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs.count
4

PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs[1]
* it is not set as an array it seem

when using import-excel
    $NestedESXiHostnameToIPs = $MgmtVCSAParameters.MgmtESXHosts.split(',') | foreach {$K,$V=$_.split('='); @{$K.trim()=$V}}

Looks the same, the count is the same
PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs

Name                           Value                                                                                       
----                           -----                                                                                       
ESX01                          192.168.10.20                                                                               
ESX02                          192.168.10.21                                                                               
ESX03                          192.168.10.22                                                                               
ESX04                          192.168.10.23                                                                               



PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs.count
4

PS C:\Users\Administrator> echo $NestedESXiHostnameToIPs[1]

Name                           Value                                                                                       
----                           -----                                                                                       
ESX02                          192.168.10.21  

But it is an array in this case

**Comment by scriptingstudio** [comment]
`$NestedESXiHostnameToIPs` is not an indexed array. It is a `hashtable`, so called named array or dictionary. You can call its members by name. Indexed array is called by index.

**Comment by dwchan69** [comment]
Thank you, you code seem  to work better than the initial one

$NestedESXiHostnameToIPs = @{}
$MgmtVCSAParameters.MgmtESXHosts.split(',') | % {
$key,$value = $_.split('=')
$NestedESXiHostnameToIPs[$key] = $value
}

versus 

    $NestedESXiHostnameToIPs = $MgmtVCSAParameters.MgmtESXHosts.split(',') | foreach {$K,$V=$_.split('='); @{$K.trim()=$V}}

I will take a closer look and try to figure out why , lol

**Comment by scriptingstudio** [comment]
that is the same but more compact

**Comment by dwchan69** [comment]
In short, it seems that

this way, it read the data into $NestedESXiHostnameToIPs as an array
$NestedESXiHostnameToIPs = $MgmtVCSAParameters.MgmtESXHosts.split(',') | foreach {$K,$V=$_.split('='); @{$K.trim()=$V}}

versus the latter read it in as a hash table
$NestedESXiHostnameToIPs = @{}
$MgmtVCSAParameters.MgmtESXHosts.split(',') | % {
$key,$value = $_.split('=')
$NestedESXiHostnameToIPs[$key] = $value
}

**Comment by dwchan69** [comment]
It still have one issue to read in as a hash, when using this

$NestedESXiHostnameToIPs = @{}
    $MgmtVCSAParameters.MgmtESXHosts.split(',') | % {
    $key,$value = $_.split('=')
    $NestedESXiHostnameToIPs[$key] = $value
    }
the output of the variable is missing some value as the name in the hash

Name                           Value                                                                                       
----                           -----                                                                                       
ESX01                          192.168.10.20                                                                               
...                            192.168.10.23                                                                               
...                            192.168.10.22                                                                               
...                            192.168.10.21 

Also is interesting it is not sort

**Comment by dwchan69** [comment]
ok, looks like I got it, but don't fully understand it ;)  This seems to work as expected

$NestedESXiHostnameToIPs = $MgmtVCSAParameters.MgmtESXHosts.split(',') | foreach {$Key,$Value=$_.split('='); @{$Key.trim()=$Value}}
$i = 0
$NestedESXiHostnameToIPs.GetEnumerator() | Sort-Object -Property Value | Foreach-Object {
    $VMName = $NestedESXiHostnameToIPs[$i].Keys
    $VMIPAddress = $NestedESXiHostnameToIPs[$i].Values
    write-host $VMName, $VMIPAddress
    $i=$i+1
}

And the output looks like this

ESX01 192.168.10.20
ESX02 192.168.10.21
ESX03 192.168.10.22
ESX04 192.168.10.23

**Comment by scriptingstudio** [comment]
Expression
`$NestedESXiHostnameToIPs = $MgmtVCSAParameters.MgmtESXHosts.split(',') | foreach {$Key,$Value=$_.split('='); @{$Key.trim()=$Value}}` creates array of hashtables. That is why it confuses.

My example creates a single hashtable. That is the difference. That is why you get different results.
