### ISSUE TITLE
Set-Column 

### ISSUE THREAD

**Issue by dejvoch-cz** [dfinke/ImportExcel#994]
Dears, 
I am just trying to use set-column to add additional column to the worksheet. Column should be containing data which are in array, all of them are System.Int32 type. 
Not sure if I get the functionality right, but imagine something like that:

```
$array = 0,1,2,12,25,11
$ExcelToEdit = Open-ExcelPackage -Path $excelPath
Set-Column -ExcelPackage $ExcelToEdit -WorksheetName "Total" -Column 3 -value $array
 $exceltoedit | Close-ExcelPackage 
```

When I open the excel to see results, in the Column C I see the first value of the $array in each row (everywhere is 0) instead of row1: 0
row2: 1
row3: 2
row4: 12
etc... 
Could you tell me whether I understand the set-column -value right, or do I need to do anything else to reach the desired scenario? 

Thank you for hints, not sure whether this is issue on my side or bug or I just got it wrongly. 
Regards
David

**Comment by dfinke** [comment]
You need to loop through the array and set the cells individually. `Set-Column` operates on a column but does not "unroll" the array, setting the data in the cells like that.

```powershell
$xl = Open-ExcelPackage .\Book1.xlsx

$xl.Sheet1.Cells[2, 3].Value = 10
$xl.Sheet1.Cells[3, 3].Value = 20
$xl.Sheet1.Cells[4, 3].Value = 30

# $arr = 10, 20, 30

# $column = 3
# for ($row = 0; $row -lt $arr.Count; $row++) {
#     $xl.Sheet1.Cells[($row + 2), $column].Value = $arr[$row]
# }

Close-ExcelPackage $xl -Show
```
