### ISSUE TITLE
import-excel skips last column

### ISSUE THREAD

**Issue by dideldum73** [dfinke/ImportExcel#996]
Hi,

i am havin g trouble importing some excel files. Usually most of them are processed fine, but in some cases, the last column isn't processed.

i am using the function like this:
   $impExcel = import-excel $_.Fullname -DataOnly
but tried it also without -DataOnly

I don't know, what the reason ist, when the last column is skipped - tried with format, or adding a value to first row - strange behavior. But alway reproducable on the same file. Uploaded an example.

[NANUSHKA DL LT Okt..xlsx](https://github.com/dfinke/ImportExcel/files/5968675/NANUSHKA.DL.LT.Okt.xlsx)

Lines look like this: 

@{Lieferdatum Tag=Total; Bestellpositionen Bestellnummer=Total; Artikel Division=Total; Artikel Area=Total; Artikel EK-Gruppe=Total; Artikel Primärer Kreditor=Total; Artikel Marke=Total; Artikel Warengruppe=Total; Artikel Artikelnummer=Total; Artikel Produktname=Total; Artikelvariante Variantenname=Total; Externe Artikelnummer=; Farbe=; Größe=; Strichcode=; Bestellmenge=4071; Bestellwert=476096,65}

but missing: Online=

Any Idea?

Thanks,
Stephan

ps. great module! Love it :-)

**Comment by dfinke** [comment]
Can you confirm you see the `Online` property is you specify the sheet name?

```powershell
$r=Import-Excel C:\NANUSHKA.DL.LT.Okt.xlsx -WorksheetName tabelle1
$r[0]
```

**Comment by dideldum73** [comment]
Hi Doug,

wow, yes, i can confirm this - the "online" property is there, if i specify the sheet name. 

I also see difference in the amount of lines: with the worksheetname specified i get a rusult of 22 Lines (which is the correct amount of lines in excel) - if i don't use the worksheetname parameter the result has 3510 lines [Object[3510]].

Regards,
Stephan

**Comment by dfinke** [comment]
Yeah, I think the file has issues, I don't think this can be solved by the PowerShell module.

**Comment by dideldum73** [comment]
hmm - unfortunately there are a couple of files like this, it's not only one - and it an ongoing process, i'll get those files with new data frequently. The sheets have different names so the workaround with sheetname doesn't help me in this case. Can i use an index instead of workheetname? Whould hate to switch back to excel com...

**Comment by dfinke** [comment]
You could use `Get-ExcelSheetInfo` and get the name of the sheets. `Import-Excel` only supports a name for the worksheet.

**Comment by dideldum73** [comment]
good idea, thank you - will try that.

**Comment by dideldum73** [comment]
ok, found the reason - checked the workbook.xml, there is a hidden Worksheet with - guess - 3510 lines and no "online"  key

       <sheet name="Bestellmenge und Bestellwert pe" sheetId="1" **state="hidden"** r:id="rId1"/>
        <sheet name="Tabelle1" sheetId="2" r:id="rId2"/>

so the module does exactly what it should do, it reads the first worksheet in the dokument. So no error, no need for an workaround.

**Comment by dfinke** [comment]
Hmm, good to know. Thanks!
