### ISSUE TITLE
question about date formatting when import from sql

### ISSUE THREAD

**Issue by charlhollander** [dfinke/ImportExcel#999]
Hi Doug, 
i'm using the importExcel Module to make excel files from sql query's.
very nice sofar, you've  made a great tool!
I have a question about date formatting;
in a SQL query containing various fields there is  a date field wich is presented as convert(date,[datefield],23) 

the query presents the date as yyyy-mm-dd
the import excel tool turns it into a date with a time stamp,  it is needed it without the time stamp
is this explained somewhere in the documentation? do you have a hint form me?
many thanks!
Charl Hollander

**Comment by MikeyBronowski** [comment]
@charlhollander could you please provide a code sample you use?

From my side, I can tell I noticed this (date column is a date type, not datetime):

`$SQLresults = Invoke-DbaQuery -SqlInstance $s1 -Database ImportExcel -Query 'SELECT * FROM ImportExcelTable'`

$SQLresults result below:
```
int date                datetime            varchar          
--- ----                --------            -------          
  1 02/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
  2 20/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
  3 22/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
  4 02/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
  5 02/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
  6 02/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
  8 02/02/2020 00:00:00 02/02/2020 02:02:02 ImportExcel-HowTo
```
Even though in SSMS it looks like that:
![image](https://user-images.githubusercontent.com/13431760/109060652-92f03d80-76dd-11eb-8252-fd9fce9fef48.png)

Can you check if the results have the timestamp prior to exporting them with the module?
